GMP系统: com.gmp.auth.service.AuthServiceImpl Class Reference
com.gmp.auth.service.AuthServiceImpl Class Reference
认证服务实现类
Public Member Functions
LoginResponse login (LoginRequest request, String ipAddress, String userAgent)
用户登录
void logout (String username, String token)
用户登出
TokenResponse refreshToken (String refreshToken)
刷新访问令牌
boolean validateToken (String token)
验证JWT令牌
java.util.Set< String > getUserRoles (String username)
获取用户所有角色
java.util.List< String > getUserPermissions (String username)
获取用户所有权限
boolean hasPermission (String username, String... requiredPermissions)
验证用户权限
boolean hasRole (String username, String... requiredRoles)
验证用户角色
Private Member Functions
void logFailedLoginAttempt (User user, String reason, String ipAddress, String userAgent)
记录登录失败
void logSuccessfulLogin (User user, String ipAddress, String userAgent)
记录登录成功
Private Attributes
UserRepository userRepository
OperationLogRepository operationLogRepository
PasswordEncoder passwordEncoder
JwtConfig jwtConfig
RedisTemplate< String, Object > redisTemplate
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(AuthServiceImpl.class)
Detailed Description
认证服务实现类
Author
GMP系统开发团队
Definition at line 29 of file AuthServiceImpl.java.
Member Function Documentation
getUserPermissions()
java.util.List< String > com.gmp.auth.service.AuthServiceImpl.getUserPermissions (String username)
获取用户所有权限
Parameters
username 用户名
Returns
权限列表
Implements com.gmp.auth.service.AuthService.
Definition at line 255 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.AuthServiceImpl.hasPermission().
getUserRoles()
java.util.Set< String > com.gmp.auth.service.AuthServiceImpl.getUserRoles (String username)
获取用户所有角色
Parameters
username 用户名
Returns
角色列表
Implements com.gmp.auth.service.AuthService.
Definition at line 248 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.AuthServiceImpl.hasRole().
hasPermission()
boolean com.gmp.auth.service.AuthServiceImpl.hasPermission (String username, String... requiredPermissions)
验证用户权限
Parameters
username 用户名
requiredPermissions 需要的权限列表
Returns
是否有权限
Implements com.gmp.auth.service.AuthService.
Definition at line 262 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.getUserPermissions().
hasRole()
boolean com.gmp.auth.service.AuthServiceImpl.hasRole (String username, String... requiredRoles)
验证用户角色
Parameters
username 用户名
requiredRoles 需要的角色列表
Returns
是否有角色
Implements com.gmp.auth.service.AuthService.
Definition at line 269 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.getUserRoles().
logFailedLoginAttempt()
void com.gmp.auth.service.AuthServiceImpl.logFailedLoginAttempt (User user, String reason, String ipAddress, String userAgent) private
记录登录失败
Definition at line 222 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.log, and com.gmp.auth.service.AuthServiceImpl.operationLogRepository.
Referenced by com.gmp.auth.service.AuthServiceImpl.login().
login()
LoginResponse com.gmp.auth.service.AuthServiceImpl.login (LoginRequest request, String ipAddress, String userAgent)
用户登录
Parameters
request 登录请求
ipAddress 客户端IP地址
userAgent 用户代理
Returns
登录响应，包含JWT令牌
Implements com.gmp.auth.service.AuthService.
Definition at line 50 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.jwtConfig, com.gmp.auth.service.AuthServiceImpl.log, com.gmp.auth.service.AuthServiceImpl.logFailedLoginAttempt(), com.gmp.auth.service.AuthServiceImpl.logSuccessfulLogin(), com.gmp.auth.service.AuthServiceImpl.passwordEncoder, com.gmp.auth.service.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.AuthServiceImpl.userRepository.
logout()
void com.gmp.auth.service.AuthServiceImpl.logout (String username, String token)
用户登出
Parameters
username 用户名
token JWT令牌
Implements com.gmp.auth.service.AuthService.
Definition at line 136 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.jwtConfig, com.gmp.auth.service.AuthServiceImpl.log, com.gmp.auth.service.AuthServiceImpl.operationLogRepository, com.gmp.auth.service.AuthServiceImpl.redisTemplate, and com.gmp.auth.service.AuthServiceImpl.userRepository.
logSuccessfulLogin()
void com.gmp.auth.service.AuthServiceImpl.logSuccessfulLogin (User user, String ipAddress, String userAgent) private
记录登录成功
Definition at line 236 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.log, and com.gmp.auth.service.AuthServiceImpl.operationLogRepository.
Referenced by com.gmp.auth.service.AuthServiceImpl.login().
refreshToken()
TokenResponse com.gmp.auth.service.AuthServiceImpl.refreshToken (String refreshToken)
刷新访问令牌
Parameters
refreshToken 刷新令牌
Returns
新的令牌响应
Implements com.gmp.auth.service.AuthService.
Definition at line 180 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.jwtConfig, com.gmp.auth.service.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.AuthServiceImpl.login(), and com.gmp.auth.service.AuthServiceImpl.refreshToken().
validateToken()
boolean com.gmp.auth.service.AuthServiceImpl.validateToken (String token)
验证JWT令牌
Parameters
token JWT令牌
Returns
是否有效
Implements com.gmp.auth.service.AuthService.
Definition at line 215 of file AuthServiceImpl.java.
References com.gmp.auth.service.AuthServiceImpl.jwtConfig.
Member Data Documentation
jwtConfig
JwtConfig com.gmp.auth.service.AuthServiceImpl.jwtConfig private
Definition at line 43 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.login(), com.gmp.auth.service.AuthServiceImpl.logout(), com.gmp.auth.service.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.AuthServiceImpl.validateToken().
log
final Logger com.gmp.auth.service.AuthServiceImpl.log = LoggerFactory.getLogger(AuthServiceImpl.class) static private
Definition at line 31 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.logFailedLoginAttempt(), com.gmp.auth.service.AuthServiceImpl.login(), com.gmp.auth.service.AuthServiceImpl.logout(), and com.gmp.auth.service.AuthServiceImpl.logSuccessfulLogin().
operationLogRepository
OperationLogRepository com.gmp.auth.service.AuthServiceImpl.operationLogRepository private
Definition at line 37 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.logFailedLoginAttempt(), com.gmp.auth.service.AuthServiceImpl.logout(), and com.gmp.auth.service.AuthServiceImpl.logSuccessfulLogin().
passwordEncoder
PasswordEncoder com.gmp.auth.service.AuthServiceImpl.passwordEncoder private
Definition at line 40 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.login().
redisTemplate
RedisTemplate<String, Object> com.gmp.auth.service.AuthServiceImpl.redisTemplate private
Definition at line 46 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.logout().
userRepository
UserRepository com.gmp.auth.service.AuthServiceImpl.userRepository private
Definition at line 34 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.AuthServiceImpl.getUserPermissions(), com.gmp.auth.service.AuthServiceImpl.getUserRoles(), com.gmp.auth.service.AuthServiceImpl.login(), com.gmp.auth.service.AuthServiceImpl.logout(), and com.gmp.auth.service.AuthServiceImpl.refreshToken().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/AuthServiceImpl.java