GMP系统: com.gmp.equipment.controller.MaintenanceRecordControllerTest Class Reference
com.gmp.equipment.controller.MaintenanceRecordControllerTest Class Reference
MaintenanceRecordController的单元测试类
Package Functions
void setUp ()
void getById_success ()
void getByMaintenanceNumber_success ()
void listPage_success ()
void listByEquipmentId_success ()
void listByMaintenancePlanId_success ()
void listByDateRange_success () throws ParseException
void listByDateRange_invalidDateFormat () throws ParseException
void checkMaintenanceNumber_success ()
void create_success ()
void update_success ()
void delete_success ()
void deleteBatch_success ()
Private Attributes
MaintenanceRecordService maintenanceRecordService
MaintenanceRecordController maintenanceRecordController
Detailed Description
MaintenanceRecordController的单元测试类
Definition at line 26 of file MaintenanceRecordControllerTest.java.
Member Function Documentation
checkMaintenanceNumber_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.checkMaintenanceNumber_success () package
Definition at line 198 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.checkMaintenanceNumber(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
create_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.create_success () package
Definition at line 217 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.create(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
delete_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.delete_success () package
Definition at line 264 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.delete(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
deleteBatch_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.deleteBatch_success () package
Definition at line 281 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.deleteBatch(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
getById_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.getById_success () package
Definition at line 40 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.getById(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
getByMaintenanceNumber_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.getByMaintenanceNumber_success () package
Definition at line 60 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.getByMaintenanceNumber(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
listByDateRange_invalidDateFormat()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_invalidDateFormat () throws ParseException package
Definition at line 182 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.listByDateRange(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
listByDateRange_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_success () throws ParseException package
Definition at line 156 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.listByDateRange(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
listByEquipmentId_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByEquipmentId_success () package
Definition at line 112 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.listByEquipmentId(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
listByMaintenancePlanId_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByMaintenancePlanId_success () package
Definition at line 134 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.listByMaintenancePlanId(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
listPage_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.listPage_success () package
Definition at line 80 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordController.listPage(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, and com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService.
setUp()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.setUp () package
Definition at line 35 of file MaintenanceRecordControllerTest.java.
update_success()
void com.gmp.equipment.controller.MaintenanceRecordControllerTest.update_success () package
Definition at line 241 of file MaintenanceRecordControllerTest.java.
References com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController, com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService, and com.gmp.equipment.controller.MaintenanceRecordController.update().
Member Data Documentation
maintenanceRecordController
MaintenanceRecordController com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordController private
Definition at line 32 of file MaintenanceRecordControllerTest.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.checkMaintenanceNumber_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.create_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.delete_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.deleteBatch_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.getById_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.getByMaintenanceNumber_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_invalidDateFormat(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByEquipmentId_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByMaintenancePlanId_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listPage_success(), and com.gmp.equipment.controller.MaintenanceRecordControllerTest.update_success().
maintenanceRecordService
MaintenanceRecordService com.gmp.equipment.controller.MaintenanceRecordControllerTest.maintenanceRecordService private
Definition at line 29 of file MaintenanceRecordControllerTest.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.checkMaintenanceNumber_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.create_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.delete_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.deleteBatch_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.getById_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.getByMaintenanceNumber_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_invalidDateFormat(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByEquipmentId_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByMaintenancePlanId_success(), com.gmp.equipment.controller.MaintenanceRecordControllerTest.listPage_success(), and com.gmp.equipment.controller.MaintenanceRecordControllerTest.update_success().
The documentation for this class was generated from the following file:
equipment-service/src/test/java/com/gmp/equipment/controller/MaintenanceRecordControllerTest.java