GMP系统: com.gmp.training.service.impl.TrainingSessionServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingSessionServiceImplTest Class Reference
培训场次服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByCourseId ()
void testFindByTrainerId ()
void testFindByStatus ()
void testFindByTrainingMethod ()
void testFindByLocation ()
void testFindByDateRange ()
void testFindFutureSessions ()
void testFindCompletedSessions ()
void testFindOngoingSessions ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testGetActualParticipantsCount ()
void testGetAttendanceRate ()
void testSearch ()
Private Attributes
TrainingSessionRepository trainingSessionRepository
TrainingSessionServiceImpl trainingSessionService
TrainingSession trainingSession
Detailed Description
培训场次服务实现的单元测试
Definition at line 28 of file TrainingSessionServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.setUp () package
Definition at line 39 of file TrainingSessionServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testBatchUpdateStatus () package
Definition at line 256 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.batchUpdateStatus().
testDelete()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testDelete () package
Definition at line 94 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindAll () package
Definition at line 79 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findAll().
testFindByCourseId()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByCourseId () package
Definition at line 103 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findByCourseId().
testFindByDateRange()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByDateRange () package
Definition at line 180 of file TrainingSessionServiceImplTest.java.
testFindById()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindById () package
Definition at line 68 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findById().
testFindByLocation()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByLocation () package
Definition at line 165 of file TrainingSessionServiceImplTest.java.
testFindByStatus()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByStatus () package
Definition at line 133 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStatus().
testFindByTrainerId()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByTrainerId () package
Definition at line 118 of file TrainingSessionServiceImplTest.java.
testFindByTrainingMethod()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByTrainingMethod () package
Definition at line 148 of file TrainingSessionServiceImplTest.java.
testFindCompletedSessions()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindCompletedSessions () package
Definition at line 213 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findCompletedSessions().
testFindFutureSessions()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindFutureSessions () package
Definition at line 197 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findFutureSessions().
testFindOngoingSessions()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindOngoingSessions () package
Definition at line 228 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.findOngoingSessions().
testGetActualParticipantsCount()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testGetActualParticipantsCount () package
Definition at line 267 of file TrainingSessionServiceImplTest.java.
testGetAttendanceRate()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testGetAttendanceRate () package
Definition at line 277 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.getAttendanceRate().
testSave()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testSave () package
Definition at line 56 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testSearch () package
Definition at line 291 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.search().
testUpdateStatus()
void com.gmp.training.service.impl.TrainingSessionServiceImplTest.testUpdateStatus () package
Definition at line 243 of file TrainingSessionServiceImplTest.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.updateStatus().
Member Data Documentation
trainingSession
TrainingSession com.gmp.training.service.impl.TrainingSessionServiceImplTest.trainingSession private
Definition at line 36 of file TrainingSessionServiceImplTest.java.
trainingSessionRepository
TrainingSessionRepository com.gmp.training.service.impl.TrainingSessionServiceImplTest.trainingSessionRepository private
Definition at line 31 of file TrainingSessionServiceImplTest.java.
trainingSessionService
TrainingSessionServiceImpl com.gmp.training.service.impl.TrainingSessionServiceImplTest.trainingSessionService private
Definition at line 34 of file TrainingSessionServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingSessionServiceImplTest.java