GMP系统: com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest Class Reference
com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest Class Reference
Public Member Functions
String getPassword ()
void setPassword (String password)
String getUsername ()
void setUsername (String username)
Private Attributes
String password
String username
Detailed Description
Definition at line 1407 of file GMPComprehensiveAuthIntegrationTest.java.
Member Function Documentation
getPassword()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.getPassword ()
Definition at line 1411 of file GMPComprehensiveAuthIntegrationTest.java.
getUsername()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.getUsername ()
Definition at line 1413 of file GMPComprehensiveAuthIntegrationTest.java.
setPassword()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.setPassword (String password)
Definition at line 1412 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testGMPComprehensiveAcceptance(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordPolicyValidation().
setUsername()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.setUsername (String username)
Definition at line 1414 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testGMPComprehensiveAcceptance(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordPolicyValidation().
Member Data Documentation
password
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.password private
Definition at line 1408 of file GMPComprehensiveAuthIntegrationTest.java.
username
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordPolicyRequest.username private
Definition at line 1409 of file GMPComprehensiveAuthIntegrationTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/GMPComprehensiveAuthIntegrationTest.java