GMP系统: com.gmp.training.service.impl.TrainingRecordServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingRecordServiceImplTest Class Reference
培训记录服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByUserId ()
void testFindBySessionId ()
void testFindByCourseId ()
void testFindByStatus ()
void testFindByDepartmentId ()
void testFindByPositionId ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testFindByUserIdAndCourseId ()
void testGetUserCompletionRate ()
void testGetCourseCompletionRate ()
void testSearch ()
void testBatchCreate ()
Private Attributes
TrainingRecordRepository trainingRecordRepository
TrainingRecordServiceImpl trainingRecordService
TrainingRecord trainingRecord
Detailed Description
培训记录服务实现的单元测试
Definition at line 27 of file TrainingRecordServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.setUp () package
Definition at line 38 of file TrainingRecordServiceImplTest.java.
testBatchCreate()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testBatchCreate () package
Definition at line 267 of file TrainingRecordServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testBatchUpdateStatus () package
Definition at line 205 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.batchUpdateStatus().
testDelete()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testDelete () package
Definition at line 93 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindAll () package
Definition at line 78 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findAll().
testFindByCourseId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByCourseId () package
Definition at line 132 of file TrainingRecordServiceImplTest.java.
testFindByDepartmentId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByDepartmentId () package
Definition at line 162 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.findByDepartmentId().
testFindById()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindById () package
Definition at line 67 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findById().
testFindByPositionId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByPositionId () package
Definition at line 177 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.findByPositionId().
testFindBySessionId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindBySessionId () package
Definition at line 117 of file TrainingRecordServiceImplTest.java.
testFindByStatus()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByStatus () package
Definition at line 147 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.findByStatus().
testFindByUserId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByUserId () package
Definition at line 102 of file TrainingRecordServiceImplTest.java.
testFindByUserIdAndCourseId()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByUserIdAndCourseId () package
Definition at line 216 of file TrainingRecordServiceImplTest.java.
testGetCourseCompletionRate()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testGetCourseCompletionRate () package
Definition at line 241 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.getCourseCompletionRate().
testGetUserCompletionRate()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testGetUserCompletionRate () package
Definition at line 229 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.getUserCompletionRate().
testSave()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testSave () package
Definition at line 56 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testSearch () package
Definition at line 253 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.search().
testUpdateStatus()
void com.gmp.training.service.impl.TrainingRecordServiceImplTest.testUpdateStatus () package
Definition at line 192 of file TrainingRecordServiceImplTest.java.
References com.gmp.training.service.impl.TrainingRecordServiceImpl.updateStatus().
Member Data Documentation
trainingRecord
TrainingRecord com.gmp.training.service.impl.TrainingRecordServiceImplTest.trainingRecord private
Definition at line 35 of file TrainingRecordServiceImplTest.java.
trainingRecordRepository
TrainingRecordRepository com.gmp.training.service.impl.TrainingRecordServiceImplTest.trainingRecordRepository private
Definition at line 30 of file TrainingRecordServiceImplTest.java.
trainingRecordService
TrainingRecordServiceImpl com.gmp.training.service.impl.TrainingRecordServiceImplTest.trainingRecordService private
Definition at line 33 of file TrainingRecordServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingRecordServiceImplTest.java