GMP系统: com.gmp.training.service.impl.TrainingNeedServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingNeedServiceImplTest Class Reference
培训需求服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByName ()
void testFindByDepartmentId ()
void testFindByStatus ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testFindApprovedNeeds ()
void testSearch ()
Private Attributes
TrainingNeedRepository trainingNeedRepository
TrainingNeedServiceImpl trainingNeedService
TrainingNeed trainingNeed
Detailed Description
培训需求服务实现的单元测试
Definition at line 27 of file TrainingNeedServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.setUp () package
Definition at line 38 of file TrainingNeedServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testBatchUpdateStatus () package
Definition at line 158 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.batchUpdateStatus().
testDelete()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testDelete () package
Definition at line 91 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindAll () package
Definition at line 76 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findAll().
testFindApprovedNeeds()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindApprovedNeeds () package
Definition at line 169 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.findApprovedNeeds().
testFindByDepartmentId()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByDepartmentId () package
Definition at line 115 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.findByDepartmentId().
testFindById()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindById () package
Definition at line 65 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findById().
testFindByName()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByName () package
Definition at line 100 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.findByName().
testFindByStatus()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByStatus () package
Definition at line 130 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.findByStatus().
testSave()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testSave () package
Definition at line 53 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testSearch () package
Definition at line 184 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.search().
testUpdateStatus()
void com.gmp.training.service.impl.TrainingNeedServiceImplTest.testUpdateStatus () package
Definition at line 145 of file TrainingNeedServiceImplTest.java.
References com.gmp.training.service.impl.TrainingNeedServiceImpl.updateStatus().
Member Data Documentation
trainingNeed
TrainingNeed com.gmp.training.service.impl.TrainingNeedServiceImplTest.trainingNeed private
Definition at line 35 of file TrainingNeedServiceImplTest.java.
trainingNeedRepository
TrainingNeedRepository com.gmp.training.service.impl.TrainingNeedServiceImplTest.trainingNeedRepository private
Definition at line 30 of file TrainingNeedServiceImplTest.java.
trainingNeedService
TrainingNeedServiceImpl com.gmp.training.service.impl.TrainingNeedServiceImplTest.trainingNeedService private
Definition at line 33 of file TrainingNeedServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingNeedServiceImplTest.java