GMP系统: com.gmp.qms.service.messaging.McpMessageService Class Reference
com.gmp.qms.service.messaging.McpMessageService Class Reference
MCP消息服务，用于处理系统间的消息发送操作
Classes
interface MessageCallback
消息回调接口
Public Member Functions
String sendToEdms (Object payload, String operation)
发送消息到EDMS系统
String sendToMes (Object payload, String operation)
发送消息到MES系统
String sendToLims (Object payload, String operation)
发送消息到LIMS系统
String sendToErp (Object payload, String operation)
发送消息到ERP系统
String sendToTraining (Object payload, String operation)
发送消息到培训系统
String sendToEquipment (Object payload, String operation)
发送消息到设备系统
String sendPriorityMessage (String targetSystem, Object payload, String operation, int priority)
发送优先级消息
String sendDelayedMessage (String targetSystem, Object payload, String operation, long delayMs)
发送延迟消息
String sendMessageWithCallback (String targetSystem, Object payload, String operation, MessageCallback callback)
发送带回调的消息
Private Member Functions
String sendMessage (String targetSystem, String routingKey, Object payload, String operation)
通用消息发送方法
Map< String, Object > createMessageWrapper (Object payload, String operation)
创建消息包装器，添加必要的元数据
Private Attributes
RabbitTemplate rabbitTemplate
McpPerformanceConfig performanceConfig
McpMonitoringService monitoringService
Detailed Description
MCP消息服务，用于处理系统间的消息发送操作
Author
GMP系统开发团队
Definition at line 22 of file McpMessageService.java.
Member Function Documentation
createMessageWrapper()
Map< String, Object > com.gmp.qms.service.messaging.McpMessageService.createMessageWrapper (Object payload, String operation) private
创建消息包装器，添加必要的元数据
Definition at line 241 of file McpMessageService.java.
Referenced by com.gmp.qms.service.messaging.McpMessageService.sendDelayedMessage(), com.gmp.qms.service.messaging.McpMessageService.sendMessageWithCallback(), and com.gmp.qms.service.messaging.McpMessageService.sendPriorityMessage().
sendDelayedMessage()
String com.gmp.qms.service.messaging.McpMessageService.sendDelayedMessage (String targetSystem, Object payload, String operation, long delayMs)
发送延迟消息
Definition at line 116 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.createMessageWrapper(), com.gmp.qms.service.messaging.McpMessageService.monitoringService, and com.gmp.qms.service.messaging.McpMessageService.rabbitTemplate.
sendMessage()
String com.gmp.qms.service.messaging.McpMessageService.sendMessage (String targetSystem, String routingKey, Object payload, String operation) private
通用消息发送方法
Definition at line 206 of file McpMessageService.java.
Referenced by com.gmp.qms.service.messaging.McpMessageService.sendToEdms(), com.gmp.qms.service.messaging.McpMessageService.sendToEquipment(), com.gmp.qms.service.messaging.McpMessageService.sendToErp(), com.gmp.qms.service.messaging.McpMessageService.sendToLims(), com.gmp.qms.service.messaging.McpMessageService.sendToMes(), and com.gmp.qms.service.messaging.McpMessageService.sendToTraining().
sendMessageWithCallback()
String com.gmp.qms.service.messaging.McpMessageService.sendMessageWithCallback (String targetSystem, Object payload, String operation, MessageCallback callback)
发送带回调的消息
Definition at line 154 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.createMessageWrapper(), com.gmp.qms.service.messaging.McpMessageService.monitoringService, and com.gmp.qms.service.messaging.McpMessageService.rabbitTemplate.
sendPriorityMessage()
String com.gmp.qms.service.messaging.McpMessageService.sendPriorityMessage (String targetSystem, Object payload, String operation, int priority)
发送优先级消息
Definition at line 78 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.createMessageWrapper(), com.gmp.qms.service.messaging.McpMessageService.monitoringService, and com.gmp.qms.service.messaging.McpMessageService.rabbitTemplate.
sendToEdms()
String com.gmp.qms.service.messaging.McpMessageService.sendToEdms (Object payload, String operation)
发送消息到EDMS系统
Definition at line 36 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
sendToEquipment()
String com.gmp.qms.service.messaging.McpMessageService.sendToEquipment (Object payload, String operation)
发送消息到设备系统
Definition at line 71 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
sendToErp()
String com.gmp.qms.service.messaging.McpMessageService.sendToErp (Object payload, String operation)
发送消息到ERP系统
Definition at line 57 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
sendToLims()
String com.gmp.qms.service.messaging.McpMessageService.sendToLims (Object payload, String operation)
发送消息到LIMS系统
Definition at line 50 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
sendToMes()
String com.gmp.qms.service.messaging.McpMessageService.sendToMes (Object payload, String operation)
发送消息到MES系统
Definition at line 43 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
sendToTraining()
String com.gmp.qms.service.messaging.McpMessageService.sendToTraining (Object payload, String operation)
发送消息到培训系统
Definition at line 64 of file McpMessageService.java.
References com.gmp.qms.service.messaging.McpMessageService.sendMessage().
Member Data Documentation
monitoringService
McpMonitoringService com.gmp.qms.service.messaging.McpMessageService.monitoringService private
Definition at line 31 of file McpMessageService.java.
Referenced by com.gmp.qms.service.messaging.McpMessageService.sendDelayedMessage(), com.gmp.qms.service.messaging.McpMessageService.sendMessageWithCallback(), and com.gmp.qms.service.messaging.McpMessageService.sendPriorityMessage().
performanceConfig
McpPerformanceConfig com.gmp.qms.service.messaging.McpMessageService.performanceConfig private
Definition at line 28 of file McpMessageService.java.
rabbitTemplate
RabbitTemplate com.gmp.qms.service.messaging.McpMessageService.rabbitTemplate private
Definition at line 25 of file McpMessageService.java.
Referenced by com.gmp.qms.service.messaging.McpMessageService.sendDelayedMessage(), com.gmp.qms.service.messaging.McpMessageService.sendMessageWithCallback(), and com.gmp.qms.service.messaging.McpMessageService.sendPriorityMessage().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/messaging/McpMessageService.java