GMP系统: com.gmp.auth.entity.User Class Reference
com.gmp.auth.entity.User Class Reference
Classes
enum UserStatus
用户状态枚举
Public Member Functions
Long getId ()
String getUsername ()
String getLoginIp ()
Integer getLoginAttempts ()
String getFullName ()
String getPassword ()
获取密码哈希 用于密码验证
List< UserRole > getUserRoles ()
获取用户角色列表
void setUserRoles (List< UserRole > userRoles)
设置用户角色列表
UserStatus getUserStatus ()
void setLastLoginTime (LocalDateTime lastLoginTime)
void setLastLoginIp (String lastLoginIp)
boolean isActive ()
检查用户是否处于活跃状态
void setActive (boolean active)
设置用户活跃状态
void setLocked (boolean locked)
设置用户锁定状态
void setExpired (boolean expired)
设置用户过期状态
String getLastLoginSession ()
获取上次登录会话ID
boolean isPasswordSoonExpired ()
检查密码是否即将过期
void setPassword (String password)
设置密码
void setPasswordLastChanged (java.time.LocalDateTime passwordLastChanged)
设置密码最后修改时间
void setPasswordExpired (boolean passwordExpired)
设置密码是否过期
boolean isLocked ()
判断用户是否被锁定
boolean isPasswordExpired ()
判断密码是否过期
void incrementLoginAttempts ()
增加登录尝试次数
void resetLoginAttempts ()
重置登录尝试次数
void lockAccount (int lockMinutes)
锁定用户账户
boolean isMfaEnabled ()
void setMfaEnabled (boolean mfaEnabled)
String getMfaSecretKey ()
void setMfaSecretKey (String mfaSecretKey)
String getMfaRecoveryCodes ()
void setMfaRecoveryCodes (String mfaRecoveryCodes)
LocalDateTime getMfaLastVerified ()
void setMfaLastVerified (LocalDateTime mfaLastVerified)
List< String > getRecoveryCodesList ()
获取恢复码列表
void setRecoveryCodesList (List< String > codes)
设置恢复码列表
String getRecoveryCodesHash ()
获取恢复码哈希值（兼容方法）
void setRecoveryCodesHash (String recoveryCodesHash)
设置恢复码哈希值（兼容方法）
void setLastLoginSession (Object session)
设置最后登录会话信息
void setLastLoginUserAgent (String userAgent)
设置最后登录User-Agent信息（兼容方法）
boolean useRecoveryCode (String code)
验证并使用恢复码
Private Attributes
List< UserRole > userRoles = new ArrayList<>()
Long id
String username
String email
String mobile
String fullName
String passwordHash
UserStatus userStatus = UserStatus.ACTIVE
LocalDateTime lastLoginTime
String lastLoginIp
LocalDateTime passwordExpiredAt
Integer loginAttempts = 0
LocalDateTime lockedUntil
LocalDateTime createdAt
LocalDateTime updatedAt
Long createdBy
Long updatedBy
Integer version = 1
boolean mfaEnabled = false
String mfaSecretKey
String mfaRecoveryCodes
LocalDateTime mfaLastVerified
Detailed Description
Definition at line 40 of file User.java.
Member Function Documentation
getFullName()
String com.gmp.auth.entity.User.getFullName ()
Definition at line 60 of file User.java.
getId()
Long com.gmp.auth.entity.User.getId ()
Definition at line 43 of file User.java.
getLastLoginSession()
String com.gmp.auth.entity.User.getLastLoginSession ()
获取上次登录会话ID
Definition at line 135 of file User.java.
getLoginAttempts()
Integer com.gmp.auth.entity.User.getLoginAttempts ()
Definition at line 55 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking(), com.gmp.auth.entity.UserTest.testLoginAttemptsManagement(), and com.gmp.auth.entity.UserTest.testUserCreation().
getLoginIp()
String com.gmp.auth.entity.User.getLoginIp ()
Definition at line 51 of file User.java.
getMfaLastVerified()
LocalDateTime com.gmp.auth.entity.User.getMfaLastVerified ()
Definition at line 348 of file User.java.
getMfaRecoveryCodes()
String com.gmp.auth.entity.User.getMfaRecoveryCodes ()
Definition at line 340 of file User.java.
getMfaSecretKey()
String com.gmp.auth.entity.User.getMfaSecretKey ()
Definition at line 332 of file User.java.
getPassword()
String com.gmp.auth.entity.User.getPassword ()
获取密码哈希 用于密码验证
Definition at line 68 of file User.java.
getRecoveryCodesHash()
String com.gmp.auth.entity.User.getRecoveryCodesHash ()
获取恢复码哈希值（兼容方法）
Definition at line 376 of file User.java.
getRecoveryCodesList()
List< String > com.gmp.auth.entity.User.getRecoveryCodesList ()
获取恢复码列表
Definition at line 359 of file User.java.
getUsername()
String com.gmp.auth.entity.User.getUsername ()
Definition at line 47 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testUserCreation().
getUserRoles()
List< UserRole > com.gmp.auth.entity.User.getUserRoles ()
获取用户角色列表
Definition at line 79 of file User.java.
getUserStatus()
UserStatus com.gmp.auth.entity.User.getUserStatus ()
Definition at line 90 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking(), com.gmp.auth.entity.UserTest.testUserCreation(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
incrementLoginAttempts()
void com.gmp.auth.entity.User.incrementLoginAttempts ()
增加登录尝试次数
Definition at line 302 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testLoginAttemptsManagement().
isActive()
boolean com.gmp.auth.entity.User.isActive ()
检查用户是否处于活跃状态
Definition at line 105 of file User.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE.
isLocked()
boolean com.gmp.auth.entity.User.isLocked ()
判断用户是否被锁定
Definition at line 286 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking(), and com.gmp.auth.entity.UserTest.testLockedUserDetection().
isMfaEnabled()
boolean com.gmp.auth.entity.User.isMfaEnabled ()
Definition at line 324 of file User.java.
isPasswordExpired()
boolean com.gmp.auth.entity.User.isPasswordExpired ()
判断密码是否过期
Definition at line 295 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testPasswordExpiration().
isPasswordSoonExpired()
boolean com.gmp.auth.entity.User.isPasswordSoonExpired ()
检查密码是否即将过期
Returns
是否即将过期
Definition at line 144 of file User.java.
lockAccount()
void com.gmp.auth.entity.User.lockAccount (int lockMinutes)
锁定用户账户
Definition at line 317 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking().
resetLoginAttempts()
void com.gmp.auth.entity.User.resetLoginAttempts ()
重置登录尝试次数
Definition at line 309 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testLoginAttemptsManagement().
setActive()
void com.gmp.auth.entity.User.setActive (boolean active)
设置用户活跃状态
Definition at line 112 of file User.java.
References com.gmp.auth.entity.User.UserStatus.INACTIVE.
setExpired()
void com.gmp.auth.entity.User.setExpired (boolean expired)
设置用户过期状态
Definition at line 126 of file User.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE.
setLastLoginIp()
void com.gmp.auth.entity.User.setLastLoginIp (String lastLoginIp)
Definition at line 98 of file User.java.
setLastLoginSession()
void com.gmp.auth.entity.User.setLastLoginSession (Object session)
设置最后登录会话信息
Definition at line 390 of file User.java.
setLastLoginTime()
void com.gmp.auth.entity.User.setLastLoginTime (LocalDateTime lastLoginTime)
Definition at line 94 of file User.java.
setLastLoginUserAgent()
void com.gmp.auth.entity.User.setLastLoginUserAgent (String userAgent)
设置最后登录User-Agent信息（兼容方法）
Definition at line 397 of file User.java.
setLocked()
void com.gmp.auth.entity.User.setLocked (boolean locked)
设置用户锁定状态
Definition at line 119 of file User.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE.
setMfaEnabled()
void com.gmp.auth.entity.User.setMfaEnabled (boolean mfaEnabled)
Definition at line 328 of file User.java.
setMfaLastVerified()
void com.gmp.auth.entity.User.setMfaLastVerified (LocalDateTime mfaLastVerified)
Definition at line 352 of file User.java.
setMfaRecoveryCodes()
void com.gmp.auth.entity.User.setMfaRecoveryCodes (String mfaRecoveryCodes)
Definition at line 344 of file User.java.
setMfaSecretKey()
void com.gmp.auth.entity.User.setMfaSecretKey (String mfaSecretKey)
Definition at line 336 of file User.java.
setPassword()
void com.gmp.auth.entity.User.setPassword (String password)
设置密码
Parameters
password 密码
Definition at line 155 of file User.java.
setPasswordExpired()
void com.gmp.auth.entity.User.setPasswordExpired (boolean passwordExpired)
设置密码是否过期
Parameters
passwordExpired 密码过期状态
Definition at line 171 of file User.java.
setPasswordLastChanged()
void com.gmp.auth.entity.User.setPasswordLastChanged (java.time.LocalDateTime passwordLastChanged)
设置密码最后修改时间
Parameters
passwordLastChanged 密码最后修改时间
Definition at line 163 of file User.java.
setRecoveryCodesHash()
void com.gmp.auth.entity.User.setRecoveryCodesHash (String recoveryCodesHash)
设置恢复码哈希值（兼容方法）
Definition at line 383 of file User.java.
setRecoveryCodesList()
void com.gmp.auth.entity.User.setRecoveryCodesList (List< String > codes)
设置恢复码列表
Definition at line 369 of file User.java.
setUserRoles()
void com.gmp.auth.entity.User.setUserRoles (List< UserRole > userRoles)
设置用户角色列表
Definition at line 86 of file User.java.
useRecoveryCode()
boolean com.gmp.auth.entity.User.useRecoveryCode (String code)
验证并使用恢复码
Definition at line 404 of file User.java.
Member Data Documentation
createdAt
LocalDateTime com.gmp.auth.entity.User.createdAt private
Definition at line 232 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAuditFields().
createdBy
Long com.gmp.auth.entity.User.createdBy private
Definition at line 239 of file User.java.
email
String com.gmp.auth.entity.User.email private
Definition at line 188 of file User.java.
fullName
String com.gmp.auth.entity.User.fullName private
Definition at line 197 of file User.java.
id
Long com.gmp.auth.entity.User.id private
Definition at line 177 of file User.java.
lastLoginIp
String com.gmp.auth.entity.User.lastLoginIp private
Definition at line 215 of file User.java.
lastLoginTime
LocalDateTime com.gmp.auth.entity.User.lastLoginTime private
Definition at line 211 of file User.java.
lockedUntil
LocalDateTime com.gmp.auth.entity.User.lockedUntil private
Definition at line 227 of file User.java.
loginAttempts
Integer com.gmp.auth.entity.User.loginAttempts = 0 private
Definition at line 224 of file User.java.
mfaEnabled
boolean com.gmp.auth.entity.User.mfaEnabled = false private
Definition at line 251 of file User.java.
mfaLastVerified
LocalDateTime com.gmp.auth.entity.User.mfaLastVerified private
Definition at line 260 of file User.java.
mfaRecoveryCodes
String com.gmp.auth.entity.User.mfaRecoveryCodes private
Definition at line 257 of file User.java.
mfaSecretKey
String com.gmp.auth.entity.User.mfaSecretKey private
Definition at line 254 of file User.java.
mobile
String com.gmp.auth.entity.User.mobile private
Definition at line 192 of file User.java.
passwordExpiredAt
LocalDateTime com.gmp.auth.entity.User.passwordExpiredAt private
Definition at line 218 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testPasswordExpiration().
passwordHash
String com.gmp.auth.entity.User.passwordHash private
Definition at line 202 of file User.java.
updatedAt
LocalDateTime com.gmp.auth.entity.User.updatedAt private
Definition at line 236 of file User.java.
updatedBy
Long com.gmp.auth.entity.User.updatedBy private
Definition at line 242 of file User.java.
username
String com.gmp.auth.entity.User.username private
Definition at line 183 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking(), com.gmp.auth.entity.UserTest.testLoginAttemptsManagement(), and com.gmp.auth.entity.UserTest.testUserCreation().
userRoles
List<UserRole> com.gmp.auth.entity.User.userRoles = new ArrayList<>() private
Definition at line 74 of file User.java.
userStatus
UserStatus com.gmp.auth.entity.User.userStatus = UserStatus.ACTIVE private
Definition at line 208 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testLockedUserDetection(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
version
Integer com.gmp.auth.entity.User.version = 1 private
Definition at line 247 of file User.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/User.java