GMP系统: com.gmp.auth.service.MfaSessionManager Class Reference
com.gmp.auth.service.MfaSessionManager Class Reference
MFA会话管理器，用于存储用户在第一阶段登录成功后的临时会话
Classes
class MfaSession
MFA会话内部类
Public Member Functions
String createSession (User user)
创建新的MFA会话
MfaSession getSession (String sessionId)
获取会话信息
void invalidateSession (String sessionId)
使会话失效
void cleanupExpiredSessions ()
清理过期会话（可以通过定时任务调用）
Private Member Functions
boolean isSessionExpired (MfaSession session)
检查会话是否过期
Private Attributes
final Map< String, MfaSession > sessions = new ConcurrentHashMap<>()
Static Private Attributes
static final int SESSION_TIMEOUT_MINUTES = 10
Detailed Description
MFA会话管理器，用于存储用户在第一阶段登录成功后的临时会话
Definition at line 15 of file MfaSessionManager.java.
Member Function Documentation
cleanupExpiredSessions()
void com.gmp.auth.service.MfaSessionManager.cleanupExpiredSessions ()
清理过期会话（可以通过定时任务调用）
Definition at line 72 of file MfaSessionManager.java.
References com.gmp.auth.service.MfaSessionManager.SESSION_TIMEOUT_MINUTES, and com.gmp.auth.service.MfaSessionManager.sessions.
createSession()
String com.gmp.auth.service.MfaSessionManager.createSession (User user)
创建新的MFA会话
Definition at line 26 of file MfaSessionManager.java.
References com.gmp.auth.service.MfaSessionManager.sessions.
getSession()
MfaSession com.gmp.auth.service.MfaSessionManager.getSession (String sessionId)
获取会话信息
Definition at line 36 of file MfaSessionManager.java.
References com.gmp.auth.service.MfaSessionManager.invalidateSession(), com.gmp.auth.service.MfaSessionManager.isSessionExpired(), and com.gmp.auth.service.MfaSessionManager.sessions.
invalidateSession()
void com.gmp.auth.service.MfaSessionManager.invalidateSession (String sessionId)
使会话失效
Definition at line 56 of file MfaSessionManager.java.
References com.gmp.auth.service.MfaSessionManager.sessions.
Referenced by com.gmp.auth.service.MfaSessionManager.getSession().
isSessionExpired()
boolean com.gmp.auth.service.MfaSessionManager.isSessionExpired (MfaSession session) private
检查会话是否过期
Definition at line 65 of file MfaSessionManager.java.
References com.gmp.auth.service.MfaSessionManager.MfaSession.getCreatedAt(), and com.gmp.auth.service.MfaSessionManager.SESSION_TIMEOUT_MINUTES.
Referenced by com.gmp.auth.service.MfaSessionManager.getSession().
Member Data Documentation
SESSION_TIMEOUT_MINUTES
final int com.gmp.auth.service.MfaSessionManager.SESSION_TIMEOUT_MINUTES = 10 static private
Definition at line 18 of file MfaSessionManager.java.
Referenced by com.gmp.auth.service.MfaSessionManager.cleanupExpiredSessions(), and com.gmp.auth.service.MfaSessionManager.isSessionExpired().
sessions
final Map<String, MfaSession> com.gmp.auth.service.MfaSessionManager.sessions = new ConcurrentHashMap<>() private
Definition at line 21 of file MfaSessionManager.java.
Referenced by com.gmp.auth.service.MfaSessionManager.cleanupExpiredSessions(), com.gmp.auth.service.MfaSessionManager.createSession(), com.gmp.auth.service.MfaSessionManager.getSession(), and com.gmp.auth.service.MfaSessionManager.invalidateSession().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/MfaSessionManager.java