GMP系统: com.gmp.mes.entity.ProductionOrderTest Class Reference
com.gmp.mes.entity.ProductionOrderTest Class Reference
生产订单实体类的单元测试
Package Functions
void setUp ()
void testIdGetterAndSetter ()
void testOrderNumberGetterAndSetter ()
void testProductIdGetterAndSetter ()
void testProductNameGetterAndSetter ()
void testQuantityGetterAndSetter ()
void testUnitGetterAndSetter ()
void testPlanStartTimeGetterAndSetter ()
void testPlanEndTimeGetterAndSetter ()
void testActualStartTimeGetterAndSetter ()
void testActualEndTimeGetterAndSetter ()
void testStatusGetterAndSetter ()
void testPriorityGetterAndSetter ()
void testApplicantGetterAndSetter ()
void testApproverGetterAndSetter ()
void testDepartmentGetterAndSetter ()
void testRemarkGetterAndSetter ()
void testProductionBatchesGetterAndSetter ()
void testAddProductionBatch ()
void testRemoveProductionBatch ()
void testEqualsAndHashCode ()
void testToString ()
Private Attributes
ProductionOrder productionOrder
Detailed Description
生产订单实体类的单元测试
Author
gmp-system
Definition at line 17 of file ProductionOrderTest.java.
Member Function Documentation
setUp()
void com.gmp.mes.entity.ProductionOrderTest.setUp () package
Definition at line 22 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testActualEndTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testActualEndTimeGetterAndSetter () package
Definition at line 90 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getActualEndTime(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setActualEndTime().
testActualStartTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testActualStartTimeGetterAndSetter () package
Definition at line 83 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getActualStartTime(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setActualStartTime().
testAddProductionBatch()
void com.gmp.mes.entity.ProductionOrderTest.testAddProductionBatch () package
Definition at line 152 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.addProductionBatch(), com.gmp.mes.entity.ProductionOrder.getProductionBatches(), and com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testApplicantGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testApplicantGetterAndSetter () package
Definition at line 111 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getApplicant(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setApplicant().
testApproverGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testApproverGetterAndSetter () package
Definition at line 118 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testDepartmentGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testDepartmentGetterAndSetter () package
Definition at line 125 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getDepartment(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setDepartment().
testEqualsAndHashCode()
void com.gmp.mes.entity.ProductionOrderTest.testEqualsAndHashCode () package
Definition at line 177 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder, com.gmp.mes.entity.ProductionOrder.setId(), and com.gmp.mes.entity.ProductionOrder.setOrderNumber().
testIdGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testIdGetterAndSetter () package
Definition at line 27 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getId(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setId().
testOrderNumberGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testOrderNumberGetterAndSetter () package
Definition at line 34 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getOrderNumber(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setOrderNumber().
testPlanEndTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testPlanEndTimeGetterAndSetter () package
Definition at line 76 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getPlanEndTime(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setPlanEndTime().
testPlanStartTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testPlanStartTimeGetterAndSetter () package
Definition at line 69 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getPlanStartTime(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setPlanStartTime().
testPriorityGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testPriorityGetterAndSetter () package
Definition at line 104 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getPriority(), com.gmp.mes.entity.ProductionOrder.OrderPriority.HIGH, com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setPriority().
testProductIdGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testProductIdGetterAndSetter () package
Definition at line 41 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testProductionBatchesGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testProductionBatchesGetterAndSetter () package
Definition at line 139 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getProductionBatches(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setProductionBatches().
testProductNameGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testProductNameGetterAndSetter () package
Definition at line 48 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testQuantityGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testQuantityGetterAndSetter () package
Definition at line 55 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder.
testRemarkGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testRemarkGetterAndSetter () package
Definition at line 132 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getRemark(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setRemark().
testRemoveProductionBatch()
void com.gmp.mes.entity.ProductionOrderTest.testRemoveProductionBatch () package
Definition at line 163 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.addProductionBatch(), com.gmp.mes.entity.ProductionOrder.getProductionBatches(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.removeProductionBatch().
testStatusGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testStatusGetterAndSetter () package
Definition at line 97 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.OrderStatus.COMPLETED, com.gmp.mes.entity.ProductionOrder.getStatus(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setStatus().
testToString()
void com.gmp.mes.entity.ProductionOrderTest.testToString () package
Definition at line 194 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrderTest.productionOrder, com.gmp.mes.entity.ProductionOrder.setId(), and com.gmp.mes.entity.ProductionOrder.setOrderNumber().
testUnitGetterAndSetter()
void com.gmp.mes.entity.ProductionOrderTest.testUnitGetterAndSetter () package
Definition at line 62 of file ProductionOrderTest.java.
References com.gmp.mes.entity.ProductionOrder.getUnit(), com.gmp.mes.entity.ProductionOrderTest.productionOrder, and com.gmp.mes.entity.ProductionOrder.setUnit().
Member Data Documentation
productionOrder
ProductionOrder com.gmp.mes.entity.ProductionOrderTest.productionOrder private
Definition at line 19 of file ProductionOrderTest.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.setUp(), com.gmp.mes.entity.ProductionOrderTest.testActualEndTimeGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testActualStartTimeGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testAddProductionBatch(), com.gmp.mes.entity.ProductionOrderTest.testApplicantGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testApproverGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testDepartmentGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testEqualsAndHashCode(), com.gmp.mes.entity.ProductionOrderTest.testIdGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testOrderNumberGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testPlanEndTimeGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testPlanStartTimeGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testPriorityGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testProductIdGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testProductionBatchesGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testProductNameGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testQuantityGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testRemarkGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testRemoveProductionBatch(), com.gmp.mes.entity.ProductionOrderTest.testStatusGetterAndSetter(), com.gmp.mes.entity.ProductionOrderTest.testToString(), and com.gmp.mes.entity.ProductionOrderTest.testUnitGetterAndSetter().
The documentation for this class was generated from the following file:
mes-service/src/test/java/com/gmp/mes/entity/ProductionOrderTest.java