GMP系统: com.gmp.edms.service.impl.MinioFileStorageServiceImpl Class Reference
com.gmp.edms.service.impl.MinioFileStorageServiceImpl Class Reference
MinIO文件存储服务实现
Public Member Functions
String uploadFile (MultipartFile file, String bucketName, String prefix) throws Exception
上传文件
InputStream downloadFile (String bucketName, String filePath) throws Exception
下载文件
void deleteFile (String bucketName, String filePath) throws Exception
删除文件
void batchDeleteFiles (String bucketName, List< String > filePaths) throws Exception
批量删除文件
boolean fileExists (String bucketName, String filePath)
检查文件是否存在
String generatePresignedUrl (String bucketName, String filePath, int expiration) throws Exception
生成预签名URL
Map< String, Object > getFileInfo (String bucketName, String filePath) throws Exception
获取文件信息
void copyFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
复制文件
void moveFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
移动文件
List< String > listFiles (String bucketName, String prefix)
列出存储桶中的文件
void createBucket (String bucketName) throws Exception
创建存储桶
void deleteBucket (String bucketName) throws Exception
删除存储桶
boolean bucketExists (String bucketName)
检查存储桶是否存在
List< String > listBuckets ()
列出所有存储桶
boolean directoryExists (String bucketName, String directoryPath)
检查目录是否存在
void createDirectory (String bucketName, String directoryPath)
创建目录
void deleteDirectory (String bucketName, String directoryPath) throws Exception
删除目录
String getContentType (String bucketName, String filePath)
获取文件内容类型
long getFileLastModified (String bucketName, String filePath) throws Exception
获取文件最后修改时间
long getFileSize (String bucketName, String filePath) throws Exception
获取文件大小
Map< String, Long > getBucketStorageInfo (String bucketName) throws Exception
获取存储桶存储使用情况
Private Attributes
MinioClient minioClient
String defaultBucket
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(MinioFileStorageServiceImpl.class)
Detailed Description
MinIO文件存储服务实现
Definition at line 49 of file MinioFileStorageServiceImpl.java.
Member Function Documentation
batchDeleteFiles()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.batchDeleteFiles (String bucketName, List< String > filePaths) throws Exception
批量删除文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 122 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteDirectory(), and com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testBatchDeleteFiles().
bucketExists()
boolean com.gmp.edms.service.impl.MinioFileStorageServiceImpl.bucketExists (String bucketName)
检查存储桶是否存在
Implements com.gmp.edms.service.FileStorageService.
Definition at line 282 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getBucketStorageInfo(), com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testBucketExists(), and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile().
copyFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.copyFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
复制文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 210 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.moveFile(), and com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testCopyFile().
createBucket()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createBucket (String bucketName) throws Exception
创建存储桶
Implements com.gmp.edms.service.FileStorageService.
Definition at line 266 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testCreateBucket(), and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile().
createDirectory()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createDirectory (String bucketName, String directoryPath)
创建目录
Implements com.gmp.edms.service.FileStorageService.
Definition at line 338 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
deleteBucket()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteBucket (String bucketName) throws Exception
删除存储桶
Implements com.gmp.edms.service.FileStorageService.
Definition at line 274 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDeleteBucket().
deleteDirectory()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteDirectory (String bucketName, String directoryPath) throws Exception
删除目录
Implements com.gmp.edms.service.FileStorageService.
Definition at line 363 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.batchDeleteFiles(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listFiles().
deleteFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteFile (String bucketName, String filePath) throws Exception
删除文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 109 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.moveFile(), and com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDeleteFile().
directoryExists()
boolean com.gmp.edms.service.impl.MinioFileStorageServiceImpl.directoryExists (String bucketName, String directoryPath)
检查目录是否存在
Implements com.gmp.edms.service.FileStorageService.
Definition at line 310 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
downloadFile()
InputStream com.gmp.edms.service.impl.MinioFileStorageServiceImpl.downloadFile (String bucketName, String filePath) throws Exception
下载文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 96 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDownloadFile().
fileExists()
boolean com.gmp.edms.service.impl.MinioFileStorageServiceImpl.fileExists (String bucketName, String filePath)
检查文件是否存在
Implements com.gmp.edms.service.FileStorageService.
Definition at line 154 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testFileExists(), and com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testFileExists_FileNotFound().
generatePresignedUrl()
String com.gmp.edms.service.impl.MinioFileStorageServiceImpl.generatePresignedUrl (String bucketName, String filePath, int expiration) throws Exception
生成预签名URL
Implements com.gmp.edms.service.FileStorageService.
Definition at line 172 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testGeneratePresignedUrl().
getBucketStorageInfo()
Map< String, Long > com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getBucketStorageInfo (String bucketName) throws Exception
获取存储桶存储使用情况
Implements com.gmp.edms.service.FileStorageService.
Definition at line 443 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.bucketExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
getContentType()
String com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getContentType (String bucketName, String filePath)
获取文件内容类型
Implements com.gmp.edms.service.FileStorageService.
Definition at line 378 of file MinioFileStorageServiceImpl.java.
getFileInfo()
Map< String, Object > com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileInfo (String bucketName, String filePath) throws Exception
获取文件信息
Implements com.gmp.edms.service.FileStorageService.
Definition at line 188 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testGetFileInfo().
getFileLastModified()
long com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileLastModified (String bucketName, String filePath) throws Exception
获取文件最后修改时间
Implements com.gmp.edms.service.FileStorageService.
Definition at line 410 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
getFileSize()
long com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileSize (String bucketName, String filePath) throws Exception
获取文件大小
Implements com.gmp.edms.service.FileStorageService.
Definition at line 424 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, com.gmp.edms.service.impl.MinioFileStorageServiceImpl.log, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
listBuckets()
List< String > com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listBuckets ()
列出所有存储桶
Implements com.gmp.edms.service.FileStorageService.
Definition at line 293 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testListBuckets().
listFiles()
List< String > com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listFiles (String bucketName, String prefix)
列出存储桶中的文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 238 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteDirectory(), and com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testListFiles().
moveFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImpl.moveFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
移动文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 228 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.copyFile(), and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteFile().
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testMoveFile().
uploadFile()
String com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile (MultipartFile file, String bucketName, String prefix) throws Exception
上传文件
Implements com.gmp.edms.service.FileStorageService.
Definition at line 60 of file MinioFileStorageServiceImpl.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.bucketExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createBucket(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket, and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testUploadFile().
Member Data Documentation
defaultBucket
String com.gmp.edms.service.impl.MinioFileStorageServiceImpl.defaultBucket private
Definition at line 57 of file MinioFileStorageServiceImpl.java.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.batchDeleteFiles(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.copyFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createDirectory(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteDirectory(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.directoryExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.downloadFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.fileExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.generatePresignedUrl(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getBucketStorageInfo(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileInfo(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileLastModified(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileSize(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listFiles(), and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile().
log
final Logger com.gmp.edms.service.impl.MinioFileStorageServiceImpl.log = LoggerFactory.getLogger(MinioFileStorageServiceImpl.class) static private
Definition at line 51 of file MinioFileStorageServiceImpl.java.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileSize().
minioClient
MinioClient com.gmp.edms.service.impl.MinioFileStorageServiceImpl.minioClient private
Definition at line 54 of file MinioFileStorageServiceImpl.java.
Referenced by com.gmp.edms.service.impl.MinioFileStorageServiceImpl.batchDeleteFiles(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.bucketExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.copyFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createBucket(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createDirectory(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteBucket(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.directoryExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.downloadFile(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.fileExists(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.generatePresignedUrl(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getBucketStorageInfo(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileInfo(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileLastModified(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileSize(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listBuckets(), com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listFiles(), and com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/MinioFileStorageServiceImpl.java