GMP系统: com.gmp.equipment.controller.EquipmentController Class Reference
com.gmp.equipment.controller.EquipmentController Class Reference
设备控制器 提供设备相关的RESTful API接口
Public Member Functions
ResponseEntity< ResponseResult< EquipmentDTO > > getById (@PathVariable Long id)
ResponseEntity< ResponseResult< EquipmentDTO > > getByCode (@PathVariable String code)
ResponseEntity< ResponseResult< EquipmentDTO > > getBySerialNumber (@PathVariable String serialNumber)
ResponseEntity< ResponseResult< PageResultDTO< EquipmentDTO > > > listPage (@RequestParam(required=false) String keyword, @RequestParam(required=false) Long equipmentTypeId, @RequestParam(required=false) String status, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
ResponseEntity< ResponseResult< List< EquipmentDTO > > > listAll ()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > listByEquipmentTypeId (@PathVariable Long equipmentTypeId)
ResponseEntity< ResponseResult< List< EquipmentDTO > > > listAvailable ()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > listNeedCalibration ()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > listNeedMaintenance ()
ResponseEntity< ResponseResult< Boolean > > checkCode (@RequestParam String code, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< Boolean > > checkSerialNumber (@RequestParam String serialNumber, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< EquipmentDTO > > create (@RequestBody EquipmentDTO equipmentDTO)
ResponseEntity< ResponseResult< EquipmentDTO > > update (@PathVariable Long id, @RequestBody EquipmentDTO equipmentDTO)
ResponseEntity< ResponseResult< EquipmentDTO > > enable (@PathVariable Long id)
ResponseEntity< ResponseResult< EquipmentDTO > > disable (@PathVariable Long id)
ResponseEntity< ResponseResult< EquipmentDTO > > updateStatus (@PathVariable Long id, @RequestParam String status)
ResponseEntity< ResponseResult< EquipmentDTO > > updateCalibrationDate (@PathVariable Long id, @RequestParam String nextCalibrationDate)
ResponseEntity< ResponseResult< EquipmentDTO > > updateMaintenanceDate (@PathVariable Long id, @RequestParam String nextMaintenanceDate)
ResponseEntity< ResponseResult< Boolean > > delete (@PathVariable Long id)
ResponseEntity< ResponseResult< Boolean > > deleteBatch (@RequestBody List< Long > ids)
Private Attributes
EquipmentService equipmentService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(EquipmentController.class)
Detailed Description
设备控制器 提供设备相关的RESTful API接口
Definition at line 26 of file EquipmentController.java.
Member Function Documentation
checkCode()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentController.checkCode (@RequestParam String code, @RequestParam(required=false) Long id)
Definition at line 167 of file EquipmentController.java.
checkSerialNumber()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentController.checkSerialNumber (@RequestParam String serialNumber, @RequestParam(required=false) Long id)
Definition at line 180 of file EquipmentController.java.
create()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.create (@RequestBody EquipmentDTO equipmentDTO)
Definition at line 193 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.create_success().
delete()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentController.delete (@PathVariable Long id)
Definition at line 305 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.delete_success().
deleteBatch()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentController.deleteBatch (@RequestBody List< Long > ids)
Definition at line 321 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.deleteBatch_success().
disable()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.disable (@PathVariable Long id)
Definition at line 241 of file EquipmentController.java.
enable()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.enable (@PathVariable Long id)
Definition at line 225 of file EquipmentController.java.
getByCode()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.getByCode (@PathVariable String code)
Definition at line 51 of file EquipmentController.java.
getById()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.getById (@PathVariable Long id)
Definition at line 35 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.getById_notFound(), and com.gmp.equipment.controller.EquipmentControllerTest.getById_success().
getBySerialNumber()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.getBySerialNumber (@PathVariable String serialNumber)
Definition at line 67 of file EquipmentController.java.
listAll()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listAll ()
Definition at line 102 of file EquipmentController.java.
listAvailable()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listAvailable ()
Definition at line 128 of file EquipmentController.java.
listByEquipmentTypeId()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listByEquipmentTypeId (@PathVariable Long equipmentTypeId)
Definition at line 115 of file EquipmentController.java.
listNeedCalibration()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listNeedCalibration ()
Definition at line 141 of file EquipmentController.java.
listNeedMaintenance()
ResponseEntity< ResponseResult< List< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listNeedMaintenance ()
Definition at line 154 of file EquipmentController.java.
listPage()
ResponseEntity< ResponseResult< PageResultDTO< EquipmentDTO > > > com.gmp.equipment.controller.EquipmentController.listPage (@RequestParam(required=false) String keyword, @RequestParam(required=false) Long equipmentTypeId, @RequestParam(required=false) String status, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
Definition at line 83 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.listPage_success().
update()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.update (@PathVariable Long id, @RequestBody EquipmentDTO equipmentDTO)
Definition at line 209 of file EquipmentController.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.update_success().
updateCalibrationDate()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.updateCalibrationDate (@PathVariable Long id, @RequestParam String nextCalibrationDate)
Definition at line 273 of file EquipmentController.java.
updateMaintenanceDate()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.updateMaintenanceDate (@PathVariable Long id, @RequestParam String nextMaintenanceDate)
Definition at line 289 of file EquipmentController.java.
updateStatus()
ResponseEntity< ResponseResult< EquipmentDTO > > com.gmp.equipment.controller.EquipmentController.updateStatus (@PathVariable Long id, @RequestParam String status)
Definition at line 257 of file EquipmentController.java.
Member Data Documentation
equipmentService
EquipmentService com.gmp.equipment.controller.EquipmentController.equipmentService private
Definition at line 31 of file EquipmentController.java.
logger
final Logger com.gmp.equipment.controller.EquipmentController.logger = LoggerFactory.getLogger(EquipmentController.class) static private
Definition at line 28 of file EquipmentController.java.
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/controller/EquipmentController.java