GMP系统: com.gmp.qms.service.impl.DeviationServiceImplTest Class Reference
com.gmp.qms.service.impl.DeviationServiceImplTest Class Reference
DeviationServiceImpl单元测试
Package Functions
void setUp ()
void testGetDeviationById ()
void testGetDeviationByIdNotFound ()
void testGetDeviationByCode ()
void testCreateDeviation ()
void testUpdateDeviation ()
void testFindAllDeviations ()
void testSearchDeviations ()
void testUpdateDeviationStatus ()
void testGenerateDeviationCode ()
void testAddAttachment () throws IOException
void testAddAttachmentNotFound ()
void testAddAttachmentIOException () throws IOException
void testRemoveAttachment ()
void testRemoveAttachmentDeviationNotFound ()
void testRemoveAttachmentNotFound ()
void testFindOverdueDeviations ()
Private Attributes
DeviationRepository deviationRepository
DeviationAttachmentRepository deviationAttachmentRepository
DeviationServiceImpl deviationService
Deviation deviation
DeviationDTO deviationDTO
Detailed Description
DeviationServiceImpl单元测试
Author
GMP系统开发团队
Definition at line 45 of file DeviationServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.qms.service.impl.DeviationServiceImplTest.setUp () package
Definition at line 60 of file DeviationServiceImplTest.java.
testAddAttachment()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testAddAttachment () throws IOException package
Definition at line 193 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.addAttachment().
testAddAttachmentIOException()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testAddAttachmentIOException () throws IOException package
Definition at line 233 of file DeviationServiceImplTest.java.
testAddAttachmentNotFound()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testAddAttachmentNotFound () package
Definition at line 216 of file DeviationServiceImplTest.java.
testCreateDeviation()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testCreateDeviation () package
Definition at line 114 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.createDeviation().
testFindAllDeviations()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testFindAllDeviations () package
Definition at line 139 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.findAllDeviations().
testFindOverdueDeviations()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testFindOverdueDeviations () package
Definition at line 307 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.findOverdueDeviations().
testGenerateDeviationCode()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testGenerateDeviationCode () package
Definition at line 181 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.generateDeviationCode().
testGetDeviationByCode()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testGetDeviationByCode () package
Definition at line 103 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationByCode().
testGetDeviationById()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testGetDeviationById () package
Definition at line 81 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById().
testGetDeviationByIdNotFound()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testGetDeviationByIdNotFound () package
Definition at line 92 of file DeviationServiceImplTest.java.
testRemoveAttachment()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testRemoveAttachment () package
Definition at line 258 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.removeAttachment().
testRemoveAttachmentDeviationNotFound()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testRemoveAttachmentDeviationNotFound () package
Definition at line 280 of file DeviationServiceImplTest.java.
testRemoveAttachmentNotFound()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testRemoveAttachmentNotFound () package
Definition at line 293 of file DeviationServiceImplTest.java.
testSearchDeviations()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testSearchDeviations () package
Definition at line 153 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.searchDeviations().
testUpdateDeviation()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testUpdateDeviation () package
Definition at line 127 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviation().
testUpdateDeviationStatus()
void com.gmp.qms.service.impl.DeviationServiceImplTest.testUpdateDeviationStatus () package
Definition at line 170 of file DeviationServiceImplTest.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviationStatus().
Member Data Documentation
deviation
Deviation com.gmp.qms.service.impl.DeviationServiceImplTest.deviation private
Definition at line 56 of file DeviationServiceImplTest.java.
deviationAttachmentRepository
DeviationAttachmentRepository com.gmp.qms.service.impl.DeviationServiceImplTest.deviationAttachmentRepository private
Definition at line 51 of file DeviationServiceImplTest.java.
deviationDTO
DeviationDTO com.gmp.qms.service.impl.DeviationServiceImplTest.deviationDTO private
Definition at line 57 of file DeviationServiceImplTest.java.
deviationRepository
DeviationRepository com.gmp.qms.service.impl.DeviationServiceImplTest.deviationRepository private
Definition at line 48 of file DeviationServiceImplTest.java.
deviationService
DeviationServiceImpl com.gmp.qms.service.impl.DeviationServiceImplTest.deviationService private
Definition at line 54 of file DeviationServiceImplTest.java.
The documentation for this class was generated from the following file:
qms-service/src/test/java/com/gmp/qms/service/impl/DeviationServiceImplTest.java