GMP系统: com.gmp.mes.service.ProductionOrderService Class Reference
com.gmp.mes.service.ProductionOrderService Class Reference
生产订单服务 - 实现订单管理的核心业务逻辑
Public Member Functions
ProductionOrder createOrder (ProductionOrder order)
创建生产订单
ProductionOrder createProductionOrder (ProductionOrder order)
创建生产订单（兼容方法）
Optional< ProductionOrder > getOrderById (Long id)
根据ID获取订单
Optional< ProductionOrder > getProductionOrderById (Long id)
根据ID获取订单（兼容方法）
Optional< ProductionOrder > getOrderByNumber (String orderNumber)
根据订单编号获取订单
Optional< ProductionOrder > getProductionOrderByOrderNumber (String orderNumber)
根据订单编号获取订单（兼容方法）
List< ProductionOrder > getAllOrders ()
获取所有订单
List< ProductionOrder > getAllProductionOrders ()
获取所有订单（兼容方法）
List< ProductionOrder > getOrdersByStatus (ProductionOrder.OrderStatus status)
根据状态获取订单
List< ProductionOrder > getProductionOrdersByStatus (ProductionOrder.OrderStatus status)
根据状态获取订单（兼容方法）
List< ProductionOrder > getProductionOrdersByApplicant (String applicant)
根据申请人获取订单
List< ProductionOrder > getProductionOrdersByPlanDateRange (LocalDate startDate, LocalDate endDate)
根据计划日期范围获取订单
List< ProductionOrder > findOrdersByProductCode (String productCode)
根据产品代码查询订单
ProductionOrder updateOrder (ProductionOrder order)
更新订单
ProductionOrder submitOrder (String orderNumber)
提交订单审批
ProductionOrder approveOrder (String orderNumber, String approver)
批准订单
ProductionOrder cancelOrder (String orderNumber)
取消订单
ProductionOrder updateProductionOrder (ProductionOrder order)
更新生产订单
void deleteOrder (Long id)
删除订单
boolean deleteProductionOrder (Long id)
删除订单（兼容方法）
ProductionOrder submitProductionOrder (Long id, String submitter)
通过ID提交订单
ProductionOrder approveProductionOrder (Long id, String approver)
通过ID批准订单
ProductionOrder rejectProductionOrder (Long id, String rejecter, String reason)
拒绝订单
ProductionOrder cancelProductionOrder (Long id, String canceller, String reason)
通过ID取消订单
Private Member Functions
String generateOrderNumber ()
生成订单编号
Private Attributes
ProductionOrderRepository productionOrderRepository
Detailed Description
生产订单服务 - 实现订单管理的核心业务逻辑
Author
gmp-system
Definition at line 22 of file ProductionOrderService.java.
Member Function Documentation
approveOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.approveOrder (String orderNumber, String approver)
批准订单
Parameters
orderNumber 订单编号
approver 批准人
Returns
批准后的订单
Definition at line 210 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
approveProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.approveProductionOrder (Long id, String approver)
通过ID批准订单
Parameters
id 订单ID
approver 批准人
Returns
批准后的订单
Definition at line 347 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testApproveProductionOrder().
cancelOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.cancelOrder (String orderNumber)
取消订单
Parameters
orderNumber 订单编号
Returns
取消后的订单
Definition at line 234 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
cancelProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.cancelProductionOrder (Long id, String canceller, String reason)
通过ID取消订单
Parameters
id 订单ID
canceller 取消人
reason 取消原因
Returns
取消后的订单
Definition at line 399 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testCancelProductionOrder().
createOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.createOrder (ProductionOrder order)
创建生产订单
Parameters
order 生产订单对象
Returns
创建的生产订单
Definition at line 34 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.generateOrderNumber(), and com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderService.createProductionOrder().
createProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.createProductionOrder (ProductionOrder order)
创建生产订单（兼容方法）
Parameters
order 生产订单对象
Returns
创建的生产订单
Definition at line 53 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.createOrder().
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testCreateProductionOrder().
deleteOrder()
void com.gmp.mes.service.ProductionOrderService.deleteOrder (Long id)
删除订单
Parameters
id 订单ID
Definition at line 293 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getOrderById(), and com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
deleteProductionOrder()
boolean com.gmp.mes.service.ProductionOrderService.deleteProductionOrder (Long id)
删除订单（兼容方法）
Parameters
id 订单ID
Returns
删除结果
Definition at line 311 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testDeleteProductionOrder().
findOrdersByProductCode()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.findOrdersByProductCode (String productCode)
根据产品代码查询订单
Parameters
productCode 产品代码
Returns
订单列表
Definition at line 164 of file ProductionOrderService.java.
generateOrderNumber()
String com.gmp.mes.service.ProductionOrderService.generateOrderNumber () private
生成订单编号
Returns
订单编号
Definition at line 423 of file ProductionOrderService.java.
Referenced by com.gmp.mes.service.ProductionOrderService.createOrder(), and com.gmp.mes.service.ProductionOrderServiceTest.testGenerateOrderNumber().
getAllOrders()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getAllOrders ()
获取所有订单
Returns
订单列表
Definition at line 102 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderService.getAllProductionOrders().
getAllProductionOrders()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getAllProductionOrders ()
获取所有订单（兼容方法）
Returns
订单列表
Definition at line 111 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getAllOrders().
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testGetAllProductionOrders().
getOrderById()
Optional< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getOrderById (Long id)
根据ID获取订单
Parameters
id 订单ID
Returns
订单对象
Definition at line 63 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderService.deleteOrder(), com.gmp.mes.service.ProductionOrderService.getProductionOrderById(), and com.gmp.mes.service.ProductionOrderService.updateProductionOrder().
getOrderByNumber()
Optional< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getOrderByNumber (String orderNumber)
根据订单编号获取订单
Parameters
orderNumber 订单编号
Returns
订单对象
Definition at line 83 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderService.getProductionOrderByOrderNumber().
getOrdersByStatus()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getOrdersByStatus (ProductionOrder.OrderStatus status)
根据状态获取订单
Parameters
status 订单状态
Returns
订单列表
Definition at line 121 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderService.getProductionOrdersByStatus().
getProductionOrderById()
Optional< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getProductionOrderById (Long id)
根据ID获取订单（兼容方法）
Parameters
id 订单ID
Returns
订单对象
Definition at line 73 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getOrderById().
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testCreateProductionBatch(), com.gmp.mes.service.ProductionOrderServiceTest.testGetProductionOrderById(), and com.gmp.mes.service.ProductionOrderServiceTest.testGetProductionOrderByIdNotFound().
getProductionOrderByOrderNumber()
Optional< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getProductionOrderByOrderNumber (String orderNumber)
根据订单编号获取订单（兼容方法）
Parameters
orderNumber 订单编号
Returns
订单对象
Definition at line 93 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getOrderByNumber().
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testGetProductionOrderByOrderNumber().
getProductionOrdersByApplicant()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getProductionOrdersByApplicant (String applicant)
根据申请人获取订单
Parameters
applicant 申请人
Returns
订单列表
Definition at line 141 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
getProductionOrdersByPlanDateRange()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getProductionOrdersByPlanDateRange (LocalDate startDate, LocalDate endDate)
根据计划日期范围获取订单
Parameters
startDate 开始日期
endDate 结束日期
Returns
订单列表
Definition at line 152 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
getProductionOrdersByStatus()
List< ProductionOrder > com.gmp.mes.service.ProductionOrderService.getProductionOrdersByStatus (ProductionOrder.OrderStatus status)
根据状态获取订单（兼容方法）
Parameters
status 订单状态
Returns
订单列表
Definition at line 131 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getOrdersByStatus().
rejectProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.rejectProductionOrder (Long id, String rejecter, String reason)
拒绝订单
Parameters
id 订单ID
rejecter 拒绝人
reason 拒绝原因
Returns
拒绝后的订单
Definition at line 373 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testRejectProductionOrder().
submitOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.submitOrder (String orderNumber)
提交订单审批
Parameters
orderNumber 订单编号
Returns
提交后的订单
Definition at line 187 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
submitProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.submitProductionOrder (Long id, String submitter)
通过ID提交订单
Parameters
id 订单ID
submitter 提交人
Returns
提交后的订单
Definition at line 324 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testSubmitProductionOrder().
updateOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.updateOrder (ProductionOrder order)
更新订单
Parameters
order 订单对象
Returns
更新后的订单
Definition at line 176 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
updateProductionOrder()
ProductionOrder com.gmp.mes.service.ProductionOrderService.updateProductionOrder (ProductionOrder order)
更新生产订单
Parameters
order 订单对象
Returns
更新后的订单
Definition at line 259 of file ProductionOrderService.java.
References com.gmp.mes.service.ProductionOrderService.getOrderById(), and com.gmp.mes.service.ProductionOrderService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionOrderServiceTest.testUpdateProductionOrder().
Member Data Documentation
productionOrderRepository
ProductionOrderRepository com.gmp.mes.service.ProductionOrderService.productionOrderRepository private
Definition at line 25 of file ProductionOrderService.java.
Referenced by com.gmp.mes.service.ProductionOrderService.approveOrder(), com.gmp.mes.service.ProductionOrderService.approveProductionOrder(), com.gmp.mes.service.ProductionOrderService.cancelOrder(), com.gmp.mes.service.ProductionOrderService.cancelProductionOrder(), com.gmp.mes.service.ProductionOrderService.createOrder(), com.gmp.mes.service.ProductionOrderService.deleteOrder(), com.gmp.mes.service.ProductionOrderService.deleteProductionOrder(), com.gmp.mes.service.ProductionOrderService.getAllOrders(), com.gmp.mes.service.ProductionOrderService.getOrderById(), com.gmp.mes.service.ProductionOrderService.getOrderByNumber(), com.gmp.mes.service.ProductionOrderService.getOrdersByStatus(), com.gmp.mes.service.ProductionOrderService.getProductionOrdersByApplicant(), com.gmp.mes.service.ProductionOrderService.getProductionOrdersByPlanDateRange(), com.gmp.mes.service.ProductionOrderService.rejectProductionOrder(), com.gmp.mes.service.ProductionOrderService.submitOrder(), com.gmp.mes.service.ProductionOrderService.submitProductionOrder(), com.gmp.mes.service.ProductionOrderService.updateOrder(), and com.gmp.mes.service.ProductionOrderService.updateProductionOrder().
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/service/ProductionOrderService.java