GMP系统: com.gmp.qms.service.impl.CapaServiceImplTest Class Reference
com.gmp.qms.service.impl.CapaServiceImplTest Class Reference
CapaServiceImpl单元测试
Package Functions
void setUp ()
void testGetCapaById ()
void testGetCapaByIdNotFound ()
void testGetCapaByCode ()
void testCreateCapa ()
void testUpdateCapa ()
void testFindAllCapas ()
void testSearchCapas ()
void testUpdateCapaStatus ()
void testGenerateCapaCode ()
void testAddAttachment ()
void testRemoveAttachment ()
void testRemoveAttachmentNotFound ()
void testFindOverdueCapas ()
void testAddAttachmentSuccess ()
Private Attributes
CapaRepository capaRepository
CapaServiceImpl capaService
Capa capa
CapaDTO capaDTO
Detailed Description
CapaServiceImpl单元测试
Author
GMP系统开发团队
Definition at line 41 of file CapaServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.qms.service.impl.CapaServiceImplTest.setUp () package
Definition at line 53 of file CapaServiceImplTest.java.
testAddAttachment()
void com.gmp.qms.service.impl.CapaServiceImplTest.testAddAttachment () package
Definition at line 192 of file CapaServiceImplTest.java.
testAddAttachmentSuccess()
void com.gmp.qms.service.impl.CapaServiceImplTest.testAddAttachmentSuccess () package
Definition at line 255 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.addAttachment().
testCreateCapa()
void com.gmp.qms.service.impl.CapaServiceImplTest.testCreateCapa () package
Definition at line 110 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.createCapa().
testFindAllCapas()
void com.gmp.qms.service.impl.CapaServiceImplTest.testFindAllCapas () package
Definition at line 138 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.findAllCapas().
testFindOverdueCapas()
void com.gmp.qms.service.impl.CapaServiceImplTest.testFindOverdueCapas () package
Definition at line 238 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.findOverdueCapas().
testGenerateCapaCode()
void com.gmp.qms.service.impl.CapaServiceImplTest.testGenerateCapaCode () package
Definition at line 180 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.generateCapaCode().
testGetCapaByCode()
void com.gmp.qms.service.impl.CapaServiceImplTest.testGetCapaByCode () package
Definition at line 99 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.getCapaByCode().
testGetCapaById()
void com.gmp.qms.service.impl.CapaServiceImplTest.testGetCapaById () package
Definition at line 77 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.getCapaById().
testGetCapaByIdNotFound()
void com.gmp.qms.service.impl.CapaServiceImplTest.testGetCapaByIdNotFound () package
Definition at line 88 of file CapaServiceImplTest.java.
testRemoveAttachment()
void com.gmp.qms.service.impl.CapaServiceImplTest.testRemoveAttachment () package
Definition at line 210 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.removeAttachment().
testRemoveAttachmentNotFound()
void com.gmp.qms.service.impl.CapaServiceImplTest.testRemoveAttachmentNotFound () package
Definition at line 226 of file CapaServiceImplTest.java.
testSearchCapas()
void com.gmp.qms.service.impl.CapaServiceImplTest.testSearchCapas () package
Definition at line 152 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.searchCapas().
testUpdateCapa()
void com.gmp.qms.service.impl.CapaServiceImplTest.testUpdateCapa () package
Definition at line 126 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.updateCapa().
testUpdateCapaStatus()
void com.gmp.qms.service.impl.CapaServiceImplTest.testUpdateCapaStatus () package
Definition at line 169 of file CapaServiceImplTest.java.
References com.gmp.qms.service.impl.CapaServiceImpl.updateCapaStatus().
Member Data Documentation
capa
Capa com.gmp.qms.service.impl.CapaServiceImplTest.capa private
Definition at line 49 of file CapaServiceImplTest.java.
capaDTO
CapaDTO com.gmp.qms.service.impl.CapaServiceImplTest.capaDTO private
Definition at line 50 of file CapaServiceImplTest.java.
capaRepository
CapaRepository com.gmp.qms.service.impl.CapaServiceImplTest.capaRepository private
Definition at line 44 of file CapaServiceImplTest.java.
capaService
CapaServiceImpl com.gmp.qms.service.impl.CapaServiceImplTest.capaService private
Definition at line 47 of file CapaServiceImplTest.java.
The documentation for this class was generated from the following file:
qms-service/src/test/java/com/gmp/qms/service/impl/CapaServiceImplTest.java