GMP系统: com.gmp.training.service.impl.TrainingPlanServiceImpl Class Reference
com.gmp.training.service.impl.TrainingPlanServiceImpl Class Reference
培训计划服务实现类
Public Member Functions
TrainingPlanServiceImpl (TrainingPlanRepository repository)
Optional< TrainingPlan > findByName (String name)
根据计划名称查找培训计划
List< TrainingPlan > findByYear (Integer year)
查找特定年度的培训计划
List< TrainingPlan > findByYearAndQuarter (Integer year, Integer quarter)
查找特定年度和季度的培训计划
List< TrainingPlan > findByOwner (User owner)
查找特定负责人的培训计划
List< TrainingPlan > findByStatus (TrainingPlan.Status status)
查找特定状态的培训计划
List< TrainingPlan > findByTrainingNeed (TrainingNeed trainingNeed)
查找特定培训需求关联的培训计划
List< TrainingPlan > findByPlanStartDateBetween (LocalDate startDate, LocalDate endDate)
查找时间范围内的培训计划
List< TrainingPlan > findByDepartmentId (Long departmentId)
查找部门相关的培训计划
TrainingPlan updateStatus (Long id, TrainingPlan.Status status)
更新培训计划状态
int batchUpdateStatus (List< Long > ids, TrainingPlan.Status status)
批量更新培训计划状态
List< TrainingPlan > findActivePlans ()
获取当前活跃的培训计划
List< TrainingPlan > findCompletedPlans ()
获取已完成的培训计划
List< TrainingPlan > search (String keyword)
搜索培训计划
Double calculateCompletionRate (Long id)
计算培训计划的实际完成率
Double calculateActualCost (Long id)
计算培训计划的实际花费
TrainingPlan save (TrainingPlan plan)
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Protected Member Functions
String getEntityName ()
Detailed Description
培训计划服务实现类
Author
GMP系统开发团队
Definition at line 23 of file TrainingPlanServiceImpl.java.
Constructor & Destructor Documentation
TrainingPlanServiceImpl()
com.gmp.training.service.impl.TrainingPlanServiceImpl.TrainingPlanServiceImpl (TrainingPlanRepository repository)
Definition at line 26 of file TrainingPlanServiceImpl.java.
References repository.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingPlanServiceImpl.batchUpdateStatus (List< Long > ids, TrainingPlan.Status status)
批量更新培训计划状态
Parameters
ids 计划ID列表
status 状态
Returns
影响的行数
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 84 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testBatchUpdateStatus().
calculateActualCost()
Double com.gmp.training.service.impl.TrainingPlanServiceImpl.calculateActualCost (Long id)
计算培训计划的实际花费
Parameters
id 计划ID
Returns
实际花费
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 125 of file TrainingPlanServiceImpl.java.
calculateCompletionRate()
Double com.gmp.training.service.impl.TrainingPlanServiceImpl.calculateCompletionRate (Long id)
计算培训计划的实际完成率
Parameters
id 计划ID
Returns
完成率（0-100）
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 115 of file TrainingPlanServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testCalculateCompletionRate().
count()
long com.gmp.training.service.BaseService< T, ID >.count () inherited
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity) inherited
删除实体
Parameters
entity 实体对象
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll () inherited
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities) inherited
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id) inherited
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id) inherited
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findActivePlans()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findActivePlans ()
获取当前活跃的培训计划
Returns
活跃的培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 98 of file TrainingPlanServiceImpl.java.
References repository.
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll () inherited
查询所有实体
Returns
实体列表
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable) inherited
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort) inherited
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids) inherited
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findByDepartmentId()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByDepartmentId (Long departmentId)
查找部门相关的培训计划
Parameters
departmentId 部门ID
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 66 of file TrainingPlanServiceImpl.java.
References repository.
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id) inherited
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
findByName()
Optional< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByName (String name)
根据计划名称查找培训计划
Parameters
name 计划名称
Returns
培训计划信息
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 31 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByName().
findByOwner()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByOwner (User owner)
查找特定负责人的培训计划
Parameters
owner 负责人
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 46 of file TrainingPlanServiceImpl.java.
References repository.
findByPlanStartDateBetween()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByPlanStartDateBetween (LocalDate startDate, LocalDate endDate)
查找时间范围内的培训计划
Parameters
startDate 开始日期
endDate 结束日期
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 61 of file TrainingPlanServiceImpl.java.
References repository.
findByStatus()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByStatus (TrainingPlan.Status status)
查找特定状态的培训计划
Parameters
status 状态
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 51 of file TrainingPlanServiceImpl.java.
References repository.
findByTrainingNeed()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByTrainingNeed (TrainingNeed trainingNeed)
查找特定培训需求关联的培训计划
Parameters
trainingNeed 培训需求
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 56 of file TrainingPlanServiceImpl.java.
References repository.
findByYear()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByYear (Integer year)
查找特定年度的培训计划
Parameters
year 年度
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 36 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByYear().
findByYearAndQuarter()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findByYearAndQuarter (Integer year, Integer quarter)
查找特定年度和季度的培训计划
Parameters
year 年度
quarter 季度
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 41 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByYearAndQuarter().
findCompletedPlans()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.findCompletedPlans ()
获取已完成的培训计划
Returns
已完成的培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 105 of file TrainingPlanServiceImpl.java.
References repository.
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id) inherited
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
getEntityName()
String com.gmp.training.service.impl.TrainingPlanServiceImpl.getEntityName () protected
Definition at line 144 of file TrainingPlanServiceImpl.java.
save() [1/2]
T com.gmp.training.service.BaseService< T, ID >.save (T entity) inherited
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
save() [2/2]
TrainingPlan com.gmp.training.service.impl.TrainingPlanServiceImpl.save (TrainingPlan plan)
Definition at line 135 of file TrainingPlanServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testSave().
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities) inherited
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
search()
List< TrainingPlan > com.gmp.training.service.impl.TrainingPlanServiceImpl.search (String keyword)
搜索培训计划
Parameters
keyword 关键词
Returns
培训计划列表
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 110 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testSearch().
updateStatus()
TrainingPlan com.gmp.training.service.impl.TrainingPlanServiceImpl.updateStatus (Long id, TrainingPlan.Status status)
更新培训计划状态
Parameters
id 计划ID
status 状态
Returns
更新后的培训计划
Implements com.gmp.training.service.TrainingPlanService.
Definition at line 72 of file TrainingPlanServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingPlanServiceImplTest.testUpdateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingPlanServiceImpl.java