GMP系统: com.gmp.auth.exception.GlobalExceptionHandlerTest Class Reference
com.gmp.auth.exception.GlobalExceptionHandlerTest Class Reference
GlobalExceptionHandler 单元测试类
Package Functions
void setUp ()
void handleAuthenticationException_BadCredentials ()
测试处理BadCredentialsException异常
void handleAuthenticationException_Disabled ()
测试处理DisabledException异常
void handleAuthenticationException_Locked ()
测试处理LockedException异常
void handleAuthenticationException_Generic ()
测试处理通用AuthenticationException异常
void handleAccessDeniedException ()
测试处理AccessDeniedException异常
void handleValidationException ()
测试处理MethodArgumentNotValidException异常
void handleTokenException ()
测试处理TokenException异常
void handleTokenException_Expired ()
测试处理TokenException的子类异常 - ExpiredTokenException
void handleTokenException_Invalid ()
测试处理TokenException的子类异常 - InvalidTokenException
void handleGenericException ()
测试处理通用Exception异常
void errorResponseGettersAndSetters ()
测试ErrorResponse类的getter和setter方法
void errorResponseAddDetail ()
测试ErrorResponse类的addDetail方法
void testMissingBusinessExceptionDoesNotBreakOtherFunctionality ()
测试当BusinessException缺失时不影响其他异常处理 注：BusinessException类不存在，因此handleBusinessException方法不会被测试
Private Attributes
GlobalExceptionHandler exceptionHandler
final String testRequestUri = "/api/auth/login"
Detailed Description
GlobalExceptionHandler 单元测试类
Definition at line 27 of file GlobalExceptionHandlerTest.java.
Member Function Documentation
errorResponseAddDetail()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.errorResponseAddDetail () package
测试ErrorResponse类的addDetail方法
Definition at line 320 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandler.ErrorResponse.addDetail().
errorResponseGettersAndSetters()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.errorResponseGettersAndSetters () package
测试ErrorResponse类的getter和setter方法
Definition at line 289 of file GlobalExceptionHandlerTest.java.
handleAccessDeniedException()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAccessDeniedException () package
测试处理AccessDeniedException异常
Definition at line 140 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleAccessDeniedException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleAuthenticationException_BadCredentials()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_BadCredentials () package
测试处理BadCredentialsException异常
Definition at line 43 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, and com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException().
handleAuthenticationException_Disabled()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Disabled () package
测试处理DisabledException异常
Definition at line 68 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleAuthenticationException_Generic()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Generic () package
测试处理通用AuthenticationException异常
Definition at line 116 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleAuthenticationException_Locked()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Locked () package
测试处理LockedException异常
Definition at line 92 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleGenericException()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleGenericException () package
测试处理通用Exception异常
Definition at line 265 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleGenericException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleTokenException()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException () package
测试处理TokenException异常
Definition at line 193 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleTokenException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleTokenException_Expired()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Expired () package
测试处理TokenException的子类异常 - ExpiredTokenException
Definition at line 217 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleTokenException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleTokenException_Invalid()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Invalid () package
测试处理TokenException的子类异常 - InvalidTokenException
Definition at line 241 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleTokenException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
handleValidationException()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.handleValidationException () package
测试处理MethodArgumentNotValidException异常
Definition at line 164 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, com.gmp.auth.exception.GlobalExceptionHandler.handleValidationException(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri.
setUp()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.setUp () package
Definition at line 34 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler.
testMissingBusinessExceptionDoesNotBreakOtherFunctionality()
void com.gmp.auth.exception.GlobalExceptionHandlerTest.testMissingBusinessExceptionDoesNotBreakOtherFunctionality () package
测试当BusinessException缺失时不影响其他异常处理 注：BusinessException类不存在，因此handleBusinessException方法不会被测试
Definition at line 341 of file GlobalExceptionHandlerTest.java.
References com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler, and com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException().
Member Data Documentation
exceptionHandler
GlobalExceptionHandler com.gmp.auth.exception.GlobalExceptionHandlerTest.exceptionHandler private
Definition at line 29 of file GlobalExceptionHandlerTest.java.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAccessDeniedException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_BadCredentials(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Disabled(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Generic(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Locked(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleGenericException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Expired(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Invalid(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleValidationException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.setUp(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testMissingBusinessExceptionDoesNotBreakOtherFunctionality().
testRequestUri
final String com.gmp.auth.exception.GlobalExceptionHandlerTest.testRequestUri = "/api/auth/login" private
Definition at line 31 of file GlobalExceptionHandlerTest.java.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAccessDeniedException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Disabled(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Generic(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Locked(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleGenericException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Expired(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Invalid(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.handleValidationException().
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/exception/GlobalExceptionHandlerTest.java