GMP系统: com.gmp.qms.security.McpPrincipal Class Reference
com.gmp.qms.security.McpPrincipal Class Reference
MCP主体，存储MCP客户端的身份信息和相关上下文数据
Public Member Functions
Set< String > getRoles ()
获取客户端的角色列表
Set< String > getPermissions ()
获取客户端的权限列表
Map< String, Object > getContext ()
获取客户端的上下文信息
boolean hasRole (String role)
检查客户端是否有指定的角色
boolean hasPermission (String permission)
检查客户端是否有指定的权限
boolean isExpired ()
检查令牌是否过期
Package Functions
public< T > T getClaim (String key, Class< T > valueType)
获取声明中的自定义属性
Private Attributes
final String clientId
客户端唯一标识
final String clientType
客户端类型（如：AI模型、系统服务等）
final Claims claims
原始JWT声明，包含所有认证信息
Detailed Description
MCP主体，存储MCP客户端的身份信息和相关上下文数据
Author
GMP系统开发团队
Definition at line 19 of file McpPrincipal.java.
Member Function Documentation
getClaim()
public< T > T com.gmp.qms.security.McpPrincipal.getClaim (String key, Class< T > valueType) package
获取声明中的自定义属性
Definition at line 87 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.claims.
getContext()
Map< String, Object > com.gmp.qms.security.McpPrincipal.getContext ()
获取客户端的上下文信息
Definition at line 62 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.claims.
getPermissions()
Set< String > com.gmp.qms.security.McpPrincipal.getPermissions ()
获取客户端的权限列表
Definition at line 50 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.claims.
Referenced by com.gmp.qms.security.McpPrincipal.hasPermission().
getRoles()
Set< String > com.gmp.qms.security.McpPrincipal.getRoles ()
获取客户端的角色列表
Definition at line 39 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.claims.
Referenced by com.gmp.qms.security.McpPrincipal.hasRole().
hasPermission()
boolean com.gmp.qms.security.McpPrincipal.hasPermission (String permission)
检查客户端是否有指定的权限
Definition at line 80 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.getPermissions().
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission().
hasRole()
boolean com.gmp.qms.security.McpPrincipal.hasRole (String role)
检查客户端是否有指定的角色
Definition at line 73 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.getRoles().
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission().
isExpired()
boolean com.gmp.qms.security.McpPrincipal.isExpired ()
检查令牌是否过期
Definition at line 94 of file McpPrincipal.java.
References com.gmp.qms.security.McpPrincipal.claims.
Member Data Documentation
claims
final Claims com.gmp.qms.security.McpPrincipal.claims private
原始JWT声明，包含所有认证信息
Definition at line 34 of file McpPrincipal.java.
Referenced by com.gmp.qms.security.McpPrincipal.getClaim(), com.gmp.qms.security.McpPrincipal.getContext(), com.gmp.qms.security.McpPrincipal.getPermissions(), com.gmp.qms.security.McpPrincipal.getRoles(), and com.gmp.qms.security.McpPrincipal.isExpired().
clientId
final String com.gmp.qms.security.McpPrincipal.clientId private
客户端唯一标识
Definition at line 24 of file McpPrincipal.java.
clientType
final String com.gmp.qms.security.McpPrincipal.clientType private
客户端类型（如：AI模型、系统服务等）
Definition at line 29 of file McpPrincipal.java.
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/security/McpPrincipal.java