GMP系统: com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport Class Reference
com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport Class Reference
Public Member Functions
String getTimestamp ()
void setTimestamp (String timestamp)
String getPeriod ()
void setPeriod (String period)
long getTotalCalls ()
void setTotalCalls (long totalCalls)
double getSuccessRate ()
void setSuccessRate (double successRate)
long getAverageResponseTime ()
void setAverageResponseTime (long averageResponseTime)
long getP95ResponseTime ()
void setP95ResponseTime (long p95ResponseTime)
long getP99ResponseTime ()
void setP99ResponseTime (long p99ResponseTime)
double getErrorRate ()
void setErrorRate (double errorRate)
Map< String, Long > getSystemDistribution ()
void setSystemDistribution (Map< String, Long > systemDistribution)
Private Attributes
String timestamp
String period
long totalCalls
double successRate
long averageResponseTime
long p95ResponseTime
long p99ResponseTime
double errorRate
Map< String, Long > systemDistribution
Detailed Description
Definition at line 141 of file McpPerformanceReportService.java.
Member Function Documentation
getAverageResponseTime()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getAverageResponseTime ()
Definition at line 161 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.averageResponseTime.
getErrorRate()
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getErrorRate ()
Definition at line 167 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.errorRate.
getP95ResponseTime()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getP95ResponseTime ()
Definition at line 163 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p95ResponseTime.
getP99ResponseTime()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getP99ResponseTime ()
Definition at line 165 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p99ResponseTime.
getPeriod()
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getPeriod ()
Definition at line 155 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.period.
getSuccessRate()
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getSuccessRate ()
Definition at line 159 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.successRate.
getSystemDistribution()
Map< String, Long > com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getSystemDistribution ()
Definition at line 169 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.systemDistribution.
getTimestamp()
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getTimestamp ()
Definition at line 153 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.timestamp.
getTotalCalls()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getTotalCalls ()
Definition at line 157 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.totalCalls.
setAverageResponseTime()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setAverageResponseTime (long averageResponseTime)
Definition at line 162 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.averageResponseTime.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setErrorRate()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setErrorRate (double errorRate)
Definition at line 168 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.errorRate.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setP95ResponseTime()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP95ResponseTime (long p95ResponseTime)
Definition at line 164 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p95ResponseTime.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setP99ResponseTime()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP99ResponseTime (long p99ResponseTime)
Definition at line 166 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p99ResponseTime.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setPeriod()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setPeriod (String period)
Definition at line 156 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.period.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setSuccessRate()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSuccessRate (double successRate)
Definition at line 160 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.successRate.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setSystemDistribution()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSystemDistribution (Map< String, Long > systemDistribution)
Definition at line 170 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.systemDistribution.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setTimestamp()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTimestamp (String timestamp)
Definition at line 154 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.timestamp.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
setTotalCalls()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTotalCalls (long totalCalls)
Definition at line 158 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.totalCalls.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
Member Data Documentation
averageResponseTime
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.averageResponseTime private
Definition at line 146 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getAverageResponseTime(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setAverageResponseTime().
errorRate
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.errorRate private
Definition at line 149 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getErrorRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setErrorRate().
p95ResponseTime
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p95ResponseTime private
Definition at line 147 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getP95ResponseTime(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP95ResponseTime().
p99ResponseTime
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.p99ResponseTime private
Definition at line 148 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getP99ResponseTime(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP99ResponseTime().
period
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.period private
Definition at line 143 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getPeriod(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setPeriod().
successRate
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.successRate private
Definition at line 145 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSuccessRate().
systemDistribution
Map<String, Long> com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.systemDistribution private
Definition at line 150 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getSystemDistribution(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSystemDistribution().
timestamp
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.timestamp private
Definition at line 142 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getTimestamp(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTimestamp().
totalCalls
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.totalCalls private
Definition at line 144 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.getTotalCalls(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTotalCalls().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpPerformanceReportService.java