GMP系统: com.gmp.auth.service.TotpUtilsTest Class Reference
com.gmp.auth.service.TotpUtilsTest Class Reference
TotpUtils工具类单元测试 测试基于时间的一次性密码生成和验证的核心功能
Package Functions
void setUp ()
void testGenerateSecretKey ()
void testGenerateTotpCode ()
void testVerifyTotpCodeValid ()
void testVerifyTotpCodeInvalid ()
void testGetRemainingSeconds ()
void testEdgeCaseEmptySecretKey ()
void testEdgeCaseNullSecretKey ()
void testBase32Decoding ()
void testTimestampCalculation ()
Private Attributes
TotpUtils totpUtils
String testSecretKey
String testUsername
String testIssuer
Detailed Description
TotpUtils工具类单元测试 测试基于时间的一次性密码生成和验证的核心功能
测试覆盖范围：
密钥生成功能
TOTP算法实现
验证码验证
二维码URL生成
剩余有效期计算
HMAC-SHA1算法实现
Author
GMP系统开发团队
Definition at line 34 of file TotpUtilsTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.service.TotpUtilsTest.setUp () package
Definition at line 44 of file TotpUtilsTest.java.
testBase32Decoding()
void com.gmp.auth.service.TotpUtilsTest.testBase32Decoding () package
Definition at line 192 of file TotpUtilsTest.java.
testEdgeCaseEmptySecretKey()
void com.gmp.auth.service.TotpUtilsTest.testEdgeCaseEmptySecretKey () package
Definition at line 153 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
testEdgeCaseNullSecretKey()
void com.gmp.auth.service.TotpUtilsTest.testEdgeCaseNullSecretKey () package
Definition at line 165 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
testGenerateSecretKey()
void com.gmp.auth.service.TotpUtilsTest.testGenerateSecretKey () package
Definition at line 53 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateSecretKey().
testGenerateTotpCode()
void com.gmp.auth.service.TotpUtilsTest.testGenerateTotpCode () package
Definition at line 82 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode().
testGetRemainingSeconds()
void com.gmp.auth.service.TotpUtilsTest.testGetRemainingSeconds () package
Definition at line 143 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.getRemainingSeconds().
testTimestampCalculation()
void com.gmp.auth.service.TotpUtilsTest.testTimestampCalculation () package
Definition at line 208 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode().
testVerifyTotpCodeInvalid()
void com.gmp.auth.service.TotpUtilsTest.testVerifyTotpCodeInvalid () package
Definition at line 108 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.verifyTotpCode().
testVerifyTotpCodeValid()
void com.gmp.auth.service.TotpUtilsTest.testVerifyTotpCodeValid () package
Definition at line 95 of file TotpUtilsTest.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
Member Data Documentation
testIssuer
String com.gmp.auth.service.TotpUtilsTest.testIssuer private
Definition at line 41 of file TotpUtilsTest.java.
testSecretKey
String com.gmp.auth.service.TotpUtilsTest.testSecretKey private
Definition at line 39 of file TotpUtilsTest.java.
testUsername
String com.gmp.auth.service.TotpUtilsTest.testUsername private
Definition at line 40 of file TotpUtilsTest.java.
totpUtils
TotpUtils com.gmp.auth.service.TotpUtilsTest.totpUtils private
Definition at line 37 of file TotpUtilsTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/TotpUtilsTest.java