GMP系统: com.gmp.auth.entity.UserRoleTest Class Reference
com.gmp.auth.entity.UserRoleTest Class Reference
UserRole实体单元测试
Package Functions
void testUserRoleCreation ()
void testUserRoleWithExpiration ()
void testInactiveUserRole ()
void testUserRolePrePersist ()
void testUserRoleWithAssignedTime ()
void testUserRoleAuditFields ()
void testUserRoleExpirationNullCheck ()
void testUserRoleExpirationExactTime ()
void testMultipleUserRoles ()
void testUserRoleBulkOperations ()
void testUserRoleStatusTransitions ()
Detailed Description
UserRole实体单元测试
Author
GMP系统开发团队
Definition at line 16 of file UserRoleTest.java.
Member Function Documentation
testInactiveUserRole()
void com.gmp.auth.entity.UserRoleTest.testInactiveUserRole () package
Definition at line 70 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testMultipleUserRoles()
void com.gmp.auth.entity.UserRoleTest.testMultipleUserRoles () package
Definition at line 176 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleAuditFields()
void com.gmp.auth.entity.UserRoleTest.testUserRoleAuditFields () package
Definition at line 124 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.userId.
testUserRoleBulkOperations()
void com.gmp.auth.entity.UserRoleTest.testUserRoleBulkOperations () package
Definition at line 197 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.userId.
testUserRoleCreation()
void com.gmp.auth.entity.UserRoleTest.testUserRoleCreation () package
Definition at line 19 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleExpirationExactTime()
void com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationExactTime () package
Definition at line 157 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleExpirationNullCheck()
void com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationNullCheck () package
Definition at line 144 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testUserRolePrePersist()
void com.gmp.auth.entity.UserRoleTest.testUserRolePrePersist () package
Definition at line 84 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.onCreate(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleStatusTransitions()
void com.gmp.auth.entity.UserRoleTest.testUserRoleStatusTransitions () package
Definition at line 221 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleWithAssignedTime()
void com.gmp.auth.entity.UserRoleTest.testUserRoleWithAssignedTime () package
Definition at line 105 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.onCreate(), and com.gmp.auth.entity.UserRole.userId.
testUserRoleWithExpiration()
void com.gmp.auth.entity.UserRoleTest.testUserRoleWithExpiration () package
Definition at line 37 of file UserRoleTest.java.
References com.gmp.auth.entity.UserRole.isValid(), and com.gmp.auth.entity.UserRole.userId.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/UserRoleTest.java