GMP系统: com.gmp.auth.service.impl.RolePermissionServiceImpl Class Reference
com.gmp.auth.service.impl.RolePermissionServiceImpl Class Reference
角色权限管理服务实现
Public Member Functions
List< RolePermission > assignPermissionsToRole (Long roleId, List< Long > permissionIds)
为角色分配多个权限
void removePermissionFromRole (Long roleId, Long permissionId)
移除角色的权限
List< Permission > getRolePermissions (Long roleId)
获取角色的所有权限
Set< String > getRolePermissionCodes (Long roleId)
获取角色的权限代码集合
List< Permission > getUserPermissions (Long userId)
获取用户的所有权限（通过角色继承）
Set< String > getUserPermissionCodes (Long userId)
获取用户的权限代码集合
boolean hasPermission (Long userId, String permissionCode)
检查用户是否拥有指定权限
boolean hasAnyPermission (Long userId, List< String > permissionCodes)
检查用户是否拥有指定权限之一
boolean hasAllPermissions (Long userId, List< String > permissionCodes)
检查用户是否拥有所有指定权限
RolePermission assignPermissionToRole (Long roleId, Long permissionId)
为角色分配权限
Private Attributes
RolePermissionRepository rolePermissionRepository
PermissionRepository permissionRepository
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(RolePermissionServiceImpl.class)
Detailed Description
角色权限管理服务实现
Author
GMP系统开发团队
Definition at line 27 of file RolePermissionServiceImpl.java.
Member Function Documentation
assignPermissionsToRole()
List< RolePermission > com.gmp.auth.service.impl.RolePermissionServiceImpl.assignPermissionsToRole (Long roleId, List< Long > permissionIds)
为角色分配多个权限
Parameters
roleId 角色ID
permissionIds 权限ID列表
Returns
分配结果列表
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 40 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.assignPermissionToRole().
assignPermissionToRole()
RolePermission com.gmp.auth.service.impl.RolePermissionServiceImpl.assignPermissionToRole (Long roleId, Long permissionId)
为角色分配权限
Parameters
roleId 角色ID
permissionId 权限ID
Returns
分配结果
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 115 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.log.
Referenced by com.gmp.auth.service.impl.RolePermissionServiceImpl.assignPermissionsToRole().
getRolePermissionCodes()
Set< String > com.gmp.auth.service.impl.RolePermissionServiceImpl.getRolePermissionCodes (Long roleId)
获取角色的权限代码集合
Parameters
roleId 角色ID
Returns
权限代码集合
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 74 of file RolePermissionServiceImpl.java.
getRolePermissions()
List< Permission > com.gmp.auth.service.impl.RolePermissionServiceImpl.getRolePermissions (Long roleId)
获取角色的所有权限
Parameters
roleId 角色ID
Returns
权限列表
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 68 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.permissionRepository.
getUserPermissionCodes()
Set< String > com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissionCodes (Long userId)
获取用户的权限代码集合
Parameters
userId 用户ID
Returns
权限代码集合
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 87 of file RolePermissionServiceImpl.java.
Referenced by com.gmp.auth.service.impl.RolePermissionServiceImpl.hasAllPermissions(), com.gmp.auth.service.impl.RolePermissionServiceImpl.hasAnyPermission(), and com.gmp.auth.service.impl.RolePermissionServiceImpl.hasPermission().
getUserPermissions()
List< Permission > com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissions (Long userId)
获取用户的所有权限（通过角色继承）
Parameters
userId 用户ID
Returns
权限列表
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 81 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.permissionRepository.
hasAllPermissions()
boolean com.gmp.auth.service.impl.RolePermissionServiceImpl.hasAllPermissions (Long userId, List< String > permissionCodes)
检查用户是否拥有所有指定权限
Parameters
userId 用户ID
permissionCodes 权限代码列表
Returns
是否拥有所有权限
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 108 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissionCodes().
hasAnyPermission()
boolean com.gmp.auth.service.impl.RolePermissionServiceImpl.hasAnyPermission (Long userId, List< String > permissionCodes)
检查用户是否拥有指定权限之一
Parameters
userId 用户ID
permissionCodes 权限代码列表
Returns
是否拥有任一权限
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 101 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissionCodes().
hasPermission()
boolean com.gmp.auth.service.impl.RolePermissionServiceImpl.hasPermission (Long userId, String permissionCode)
检查用户是否拥有指定权限
Parameters
userId 用户ID
permissionCode 权限代码
Returns
是否拥有
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 94 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissionCodes().
removePermissionFromRole()
void com.gmp.auth.service.impl.RolePermissionServiceImpl.removePermissionFromRole (Long roleId, Long permissionId)
移除角色的权限
Parameters
roleId 角色ID
permissionId 权限ID
Implements com.gmp.auth.service.RolePermissionService.
Definition at line 59 of file RolePermissionServiceImpl.java.
References com.gmp.auth.service.impl.RolePermissionServiceImpl.rolePermissionRepository.
Member Data Documentation
log
final Logger com.gmp.auth.service.impl.RolePermissionServiceImpl.log = LoggerFactory.getLogger(RolePermissionServiceImpl.class) static private
Definition at line 29 of file RolePermissionServiceImpl.java.
Referenced by com.gmp.auth.service.impl.RolePermissionServiceImpl.assignPermissionToRole().
permissionRepository
PermissionRepository com.gmp.auth.service.impl.RolePermissionServiceImpl.permissionRepository private
Definition at line 35 of file RolePermissionServiceImpl.java.
Referenced by com.gmp.auth.service.impl.RolePermissionServiceImpl.getRolePermissions(), and com.gmp.auth.service.impl.RolePermissionServiceImpl.getUserPermissions().
rolePermissionRepository
RolePermissionRepository com.gmp.auth.service.impl.RolePermissionServiceImpl.rolePermissionRepository private
Definition at line 32 of file RolePermissionServiceImpl.java.
Referenced by com.gmp.auth.service.impl.RolePermissionServiceImpl.removePermissionFromRole().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/RolePermissionServiceImpl.java