GMP系统: com.gmp.edms.service.impl.DocumentCategoryServiceImplTest Class Reference
com.gmp.edms.service.impl.DocumentCategoryServiceImplTest Class Reference
Package Functions
void setUp ()
void testCreateCategory ()
void testUpdateCategory ()
void testDeleteCategory ()
void testBatchDeleteCategories ()
void testGetCategoryById ()
void testGetCategoryByCode ()
void testListCategories ()
void testGetRootCategories ()
void testGetChildCategories ()
void testGetCategoryTree ()
void testUpdateCategoryStatus ()
void testCheckCategoryCodeExists ()
void testGetCategoryPath ()
void testUpdateParentCategory ()
void testBatchUpdateCategoryStatus ()
void testValidateCategoryPath ()
void testGetParentCategories ()
Private Attributes
DocumentCategoryRepository documentCategoryRepository
ModelMapper modelMapper
DocumentCategoryServiceImpl documentCategoryService
DocumentCategory category
DocumentCategoryDTO categoryDTO
DocumentCategory parentCategory
DocumentCategoryDTO parentCategoryDTO
Detailed Description
Definition at line 23 of file DocumentCategoryServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.setUp () package
Definition at line 40 of file DocumentCategoryServiceImplTest.java.
testBatchDeleteCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testBatchDeleteCategories () package
Definition at line 138 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchDeleteCategories().
testBatchUpdateCategoryStatus()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testBatchUpdateCategoryStatus () package
Definition at line 303 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchUpdateCategoryStatus().
testCheckCategoryCodeExists()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testCheckCategoryCodeExists () package
Definition at line 254 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCategoryCodeExists().
testCreateCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testCreateCategory () package
Definition at line 74 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory().
testDeleteCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testDeleteCategory () package
Definition at line 120 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.deleteCategory().
testGetCategoryByCode()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryByCode () package
Definition at line 172 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryByCode().
testGetCategoryById()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryById () package
Definition at line 157 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById().
testGetCategoryPath()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryPath () package
Definition at line 268 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryPath().
testGetCategoryTree()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryTree () package
Definition at line 225 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree().
testGetChildCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetChildCategories () package
Definition at line 209 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getChildCategories().
testGetParentCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetParentCategories () package
Definition at line 322 of file DocumentCategoryServiceImplTest.java.
testGetRootCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetRootCategories () package
Definition at line 193 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getRootCategories().
testListCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testListCategories () package
Definition at line 188 of file DocumentCategoryServiceImplTest.java.
testUpdateCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateCategory () package
Definition at line 98 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory().
testUpdateCategoryStatus()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateCategoryStatus () package
Definition at line 241 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategoryStatus().
testUpdateParentCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateParentCategory () package
Definition at line 283 of file DocumentCategoryServiceImplTest.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory().
testValidateCategoryPath()
void com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testValidateCategoryPath () package
Definition at line 317 of file DocumentCategoryServiceImplTest.java.
Member Data Documentation
category
DocumentCategory com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.category private
Definition at line 34 of file DocumentCategoryServiceImplTest.java.
categoryDTO
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.categoryDTO private
Definition at line 35 of file DocumentCategoryServiceImplTest.java.
documentCategoryRepository
DocumentCategoryRepository com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.documentCategoryRepository private
Definition at line 26 of file DocumentCategoryServiceImplTest.java.
documentCategoryService
DocumentCategoryServiceImpl com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.documentCategoryService private
Definition at line 32 of file DocumentCategoryServiceImplTest.java.
modelMapper
ModelMapper com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.modelMapper private
Definition at line 29 of file DocumentCategoryServiceImplTest.java.
parentCategory
DocumentCategory com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.parentCategory private
Definition at line 36 of file DocumentCategoryServiceImplTest.java.
parentCategoryDTO
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.parentCategoryDTO private
Definition at line 37 of file DocumentCategoryServiceImplTest.java.
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/impl/DocumentCategoryServiceImplTest.java