GMP系统: com.gmp.training.service.impl.TrainingNeedServiceImpl Class Reference
com.gmp.training.service.impl.TrainingNeedServiceImpl Class Reference
培训需求服务实现类
Public Member Functions
TrainingNeedServiceImpl (TrainingNeedRepository repository)
Optional< TrainingNeed > findByName (String name)
根据需求名称查找培训需求
List< TrainingNeed > findByDepartmentId (Long departmentId)
查找部门的培训需求
List< TrainingNeed > findByPositionId (Long positionId)
查找岗位的培训需求
List< TrainingNeed > findByStatus (TrainingNeed.Status status)
查找特定状态的培训需求
List< TrainingNeed > findByCreator (User creator)
查找创建者的培训需求
List< TrainingNeed > findBySubmitTimeBetween (LocalDateTime startTime, LocalDateTime endTime)
查找特定时间段内提交的培训需求
List< TrainingNeed > findByPriority (TrainingNeed.Priority priority)
根据优先级查找培训需求
List< TrainingNeed > findApprovedNeeds ()
查找已批准的培训需求
List< TrainingNeed > findPendingNeeds ()
查找未处理的培训需求
TrainingNeed updateStatus (Long id, TrainingNeed.Status status, String remark)
更新培训需求状态
int batchUpdateStatus (List< Long > ids, TrainingNeed.Status status, String remark)
批量更新培训需求状态
List< TrainingNeed > search (String keyword)
搜索培训需求
TrainingNeed save (TrainingNeed need)
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Protected Member Functions
String getEntityName ()
Detailed Description
培训需求服务实现类
Author
GMP系统开发团队
Definition at line 22 of file TrainingNeedServiceImpl.java.
Constructor & Destructor Documentation
TrainingNeedServiceImpl()
com.gmp.training.service.impl.TrainingNeedServiceImpl.TrainingNeedServiceImpl (TrainingNeedRepository repository)
Definition at line 25 of file TrainingNeedServiceImpl.java.
References repository.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingNeedServiceImpl.batchUpdateStatus (List< Long > ids, TrainingNeed.Status status, String remark)
批量更新培训需求状态
Parameters
ids 需求ID列表
status 状态
remark 备注
Returns
影响的行数
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 87 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testBatchUpdateStatus().
count()
long com.gmp.training.service.BaseService< T, ID >.count () inherited
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity) inherited
删除实体
Parameters
entity 实体对象
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll () inherited
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities) inherited
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id) inherited
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id) inherited
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll () inherited
查询所有实体
Returns
实体列表
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable) inherited
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort) inherited
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids) inherited
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findApprovedNeeds()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findApprovedNeeds ()
查找已批准的培训需求
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 65 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindApprovedNeeds().
findByCreator()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByCreator (User creator)
查找创建者的培训需求
Parameters
creator 创建者
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 50 of file TrainingNeedServiceImpl.java.
References repository.
findByDepartmentId()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByDepartmentId (Long departmentId)
查找部门的培训需求
Parameters
departmentId 部门ID
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 35 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByDepartmentId().
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id) inherited
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
findByName()
Optional< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByName (String name)
根据需求名称查找培训需求
Parameters
name 需求名称
Returns
培训需求信息
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 30 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByName().
findByPositionId()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByPositionId (Long positionId)
查找岗位的培训需求
Parameters
positionId 岗位ID
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 40 of file TrainingNeedServiceImpl.java.
References repository.
findByPriority()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByPriority (TrainingNeed.Priority priority)
根据优先级查找培训需求
Parameters
priority 优先级
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 60 of file TrainingNeedServiceImpl.java.
References repository.
findByStatus()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findByStatus (TrainingNeed.Status status)
查找特定状态的培训需求
Parameters
status 状态
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 45 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindByStatus().
findBySubmitTimeBetween()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findBySubmitTimeBetween (LocalDateTime startTime, LocalDateTime endTime)
查找特定时间段内提交的培训需求
Parameters
startTime 开始时间
endTime 结束时间
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 55 of file TrainingNeedServiceImpl.java.
References repository.
findPendingNeeds()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.findPendingNeeds ()
查找未处理的培训需求
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 70 of file TrainingNeedServiceImpl.java.
References repository.
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id) inherited
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
getEntityName()
String com.gmp.training.service.impl.TrainingNeedServiceImpl.getEntityName () protected
Definition at line 117 of file TrainingNeedServiceImpl.java.
save() [1/2]
T com.gmp.training.service.BaseService< T, ID >.save (T entity) inherited
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
save() [2/2]
TrainingNeed com.gmp.training.service.impl.TrainingNeedServiceImpl.save (TrainingNeed need)
Definition at line 107 of file TrainingNeedServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testSave().
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities) inherited
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
search()
List< TrainingNeed > com.gmp.training.service.impl.TrainingNeedServiceImpl.search (String keyword)
搜索培训需求
Parameters
keyword 关键词
Returns
培训需求列表
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 100 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testSearch().
updateStatus()
TrainingNeed com.gmp.training.service.impl.TrainingNeedServiceImpl.updateStatus (Long id, TrainingNeed.Status status, String remark)
更新培训需求状态
Parameters
id 需求ID
status 状态
remark 备注
Returns
更新后的培训需求
Implements com.gmp.training.service.TrainingNeedService.
Definition at line 76 of file TrainingNeedServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingNeedServiceImplTest.testUpdateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingNeedServiceImpl.java