GMP系统: com.gmp.equipment.controller.MaintenanceRecordController Class Reference
com.gmp.equipment.controller.MaintenanceRecordController Class Reference
设备维护记录控制器 提供维护记录相关的RESTful API接口
Public Member Functions
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > getById (@PathVariable Long id)
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > getByMaintenanceNumber (@PathVariable String maintenanceNumber)
ResponseEntity< ResponseResult< PageResultDTO< MaintenanceRecordDTO > > > listPage (@RequestParam(required=false) Long equipmentId, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > listByEquipmentId (@PathVariable Long equipmentId)
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > listByMaintenancePlanId (@PathVariable Long maintenancePlanId)
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > listByDateRange (@RequestParam String startDate, @RequestParam String endDate) throws ParseException
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > getLatestByEquipmentId (@PathVariable Long equipmentId)
ResponseEntity< ResponseResult< Boolean > > checkMaintenanceNumber (@RequestParam String maintenanceNumber, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > create (@RequestBody MaintenanceRecordDTO maintenanceRecordDTO)
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > update (@PathVariable Long id, @RequestBody MaintenanceRecordDTO maintenanceRecordDTO)
ResponseEntity< ResponseResult< Boolean > > delete (@PathVariable Long id)
ResponseEntity< ResponseResult< Boolean > > deleteBatch (@RequestBody List< Long > ids)
Private Attributes
MaintenanceRecordService maintenanceRecordService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(MaintenanceRecordController.class)
Detailed Description
设备维护记录控制器 提供维护记录相关的RESTful API接口
Definition at line 29 of file MaintenanceRecordController.java.
Member Function Documentation
checkMaintenanceNumber()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.MaintenanceRecordController.checkMaintenanceNumber (@RequestParam String maintenanceNumber, @RequestParam(required=false) Long id)
Definition at line 149 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.checkMaintenanceNumber_success().
create()
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > com.gmp.equipment.controller.MaintenanceRecordController.create (@RequestBody MaintenanceRecordDTO maintenanceRecordDTO)
Definition at line 162 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.create_success().
delete()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.MaintenanceRecordController.delete (@PathVariable Long id)
Definition at line 194 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.delete_success().
deleteBatch()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.MaintenanceRecordController.deleteBatch (@RequestBody List< Long > ids)
Definition at line 210 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.deleteBatch_success().
getById()
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > com.gmp.equipment.controller.MaintenanceRecordController.getById (@PathVariable Long id)
Definition at line 38 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.getById_success().
getByMaintenanceNumber()
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > com.gmp.equipment.controller.MaintenanceRecordController.getByMaintenanceNumber (@PathVariable String maintenanceNumber)
Definition at line 54 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.getByMaintenanceNumber_success().
getLatestByEquipmentId()
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > com.gmp.equipment.controller.MaintenanceRecordController.getLatestByEquipmentId (@PathVariable Long equipmentId)
Definition at line 133 of file MaintenanceRecordController.java.
listByDateRange()
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > com.gmp.equipment.controller.MaintenanceRecordController.listByDateRange (@RequestParam String startDate, @RequestParam String endDate) throws ParseException
Definition at line 112 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_invalidDateFormat(), and com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByDateRange_success().
listByEquipmentId()
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > com.gmp.equipment.controller.MaintenanceRecordController.listByEquipmentId (@PathVariable Long equipmentId)
Definition at line 86 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByEquipmentId_success().
listByMaintenancePlanId()
ResponseEntity< ResponseResult< List< MaintenanceRecordDTO > > > com.gmp.equipment.controller.MaintenanceRecordController.listByMaintenancePlanId (@PathVariable Long maintenancePlanId)
Definition at line 99 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.listByMaintenancePlanId_success().
listPage()
ResponseEntity< ResponseResult< PageResultDTO< MaintenanceRecordDTO > > > com.gmp.equipment.controller.MaintenanceRecordController.listPage (@RequestParam(required=false) Long equipmentId, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
Definition at line 70 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.listPage_success().
update()
ResponseEntity< ResponseResult< MaintenanceRecordDTO > > com.gmp.equipment.controller.MaintenanceRecordController.update (@PathVariable Long id, @RequestBody MaintenanceRecordDTO maintenanceRecordDTO)
Definition at line 178 of file MaintenanceRecordController.java.
Referenced by com.gmp.equipment.controller.MaintenanceRecordControllerTest.update_success().
Member Data Documentation
logger
final Logger com.gmp.equipment.controller.MaintenanceRecordController.logger = LoggerFactory.getLogger(MaintenanceRecordController.class) static private
Definition at line 31 of file MaintenanceRecordController.java.
maintenanceRecordService
MaintenanceRecordService com.gmp.equipment.controller.MaintenanceRecordController.maintenanceRecordService private
Definition at line 34 of file MaintenanceRecordController.java.
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/controller/MaintenanceRecordController.java