GMP系统: com.gmp.hr.mapper.EmployeeMapperImpl Class Reference
com.gmp.hr.mapper.EmployeeMapperImpl Class Reference
Public Member Functions
EmployeeDTO toDTO (Employee employee)
将员工实体转换为DTO
Employee toEntity (EmployeeDTO dto)
将员工DTO转换为实体
List< EmployeeDTO > toDTOList (List< Employee > employees)
将员工实体列表转换为DTO列表
Employee updateEntityFromDTO (EmployeeDTO dto, Employee entity)
更新员工实体
Public Attributes
EmployeeMapper INSTANCE = Mappers.getMapper(EmployeeMapper.class)
Protected Member Functions
QualificationDTO qualificationToQualificationDTO (Qualification qualification)
List< QualificationDTO > qualificationSetToQualificationDTOList (Set< Qualification > set)
TrainingRecordDTO trainingRecordToTrainingRecordDTO (TrainingRecord trainingRecord)
List< TrainingRecordDTO > trainingRecordSetToTrainingRecordDTOList (Set< TrainingRecord > set)
Private Member Functions
Long employeeDepartmentId (Employee employee)
String employeeDepartmentDepartmentName (Employee employee)
Long employeePositionId (Employee employee)
String employeePositionPositionName (Employee employee)
Detailed Description
Definition at line 23 of file EmployeeMapperImpl.java.
Member Function Documentation
employeeDepartmentDepartmentName()
String com.gmp.hr.mapper.EmployeeMapperImpl.employeeDepartmentDepartmentName (Employee employee) private
Definition at line 134 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
employeeDepartmentId()
Long com.gmp.hr.mapper.EmployeeMapperImpl.employeeDepartmentId (Employee employee) private
Definition at line 119 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
employeePositionId()
Long com.gmp.hr.mapper.EmployeeMapperImpl.employeePositionId (Employee employee) private
Definition at line 149 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
employeePositionPositionName()
String com.gmp.hr.mapper.EmployeeMapperImpl.employeePositionPositionName (Employee employee) private
Definition at line 164 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
qualificationSetToQualificationDTOList()
List< QualificationDTO > com.gmp.hr.mapper.EmployeeMapperImpl.qualificationSetToQualificationDTOList (Set< Qualification > set) protected
Definition at line 199 of file EmployeeMapperImpl.java.
References com.gmp.hr.mapper.EmployeeMapperImpl.qualificationToQualificationDTO().
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
qualificationToQualificationDTO()
QualificationDTO com.gmp.hr.mapper.EmployeeMapperImpl.qualificationToQualificationDTO (Qualification qualification) protected
Definition at line 179 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.qualificationSetToQualificationDTOList().
toDTO()
EmployeeDTO com.gmp.hr.mapper.EmployeeMapperImpl.toDTO (Employee employee)
将员工实体转换为DTO
Parameters
employee 员工实体
Returns
员工DTO
Implements com.gmp.hr.mapper.EmployeeMapper.
Definition at line 26 of file EmployeeMapperImpl.java.
References com.gmp.hr.mapper.EmployeeMapperImpl.employeeDepartmentDepartmentName(), com.gmp.hr.mapper.EmployeeMapperImpl.employeeDepartmentId(), com.gmp.hr.mapper.EmployeeMapperImpl.employeePositionId(), com.gmp.hr.mapper.EmployeeMapperImpl.employeePositionPositionName(), com.gmp.hr.mapper.EmployeeMapperImpl.qualificationSetToQualificationDTOList(), and com.gmp.hr.mapper.EmployeeMapperImpl.trainingRecordSetToTrainingRecordDTOList().
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTOList().
toDTOList()
List< EmployeeDTO > com.gmp.hr.mapper.EmployeeMapperImpl.toDTOList (List< Employee > employees)
将员工实体列表转换为DTO列表
Parameters
employees 员工实体列表
Returns
员工DTO列表
Implements com.gmp.hr.mapper.EmployeeMapper.
Definition at line 81 of file EmployeeMapperImpl.java.
References com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
toEntity()
Employee com.gmp.hr.mapper.EmployeeMapperImpl.toEntity (EmployeeDTO dto)
将员工DTO转换为实体
Parameters
dto 员工DTO
Returns
员工实体
Implements com.gmp.hr.mapper.EmployeeMapper.
Definition at line 58 of file EmployeeMapperImpl.java.
trainingRecordSetToTrainingRecordDTOList()
List< TrainingRecordDTO > com.gmp.hr.mapper.EmployeeMapperImpl.trainingRecordSetToTrainingRecordDTOList (Set< TrainingRecord > set) protected
Definition at line 239 of file EmployeeMapperImpl.java.
References com.gmp.hr.mapper.EmployeeMapperImpl.trainingRecordToTrainingRecordDTO().
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.toDTO().
trainingRecordToTrainingRecordDTO()
TrainingRecordDTO com.gmp.hr.mapper.EmployeeMapperImpl.trainingRecordToTrainingRecordDTO (TrainingRecord trainingRecord) protected
Definition at line 212 of file EmployeeMapperImpl.java.
Referenced by com.gmp.hr.mapper.EmployeeMapperImpl.trainingRecordSetToTrainingRecordDTOList().
updateEntityFromDTO()
Employee com.gmp.hr.mapper.EmployeeMapperImpl.updateEntityFromDTO (EmployeeDTO dto, Employee entity)
更新员工实体
Parameters
dto 员工DTO
entity 员工实体
Returns
更新后的员工实体
Implements com.gmp.hr.mapper.EmployeeMapper.
Definition at line 95 of file EmployeeMapperImpl.java.
Member Data Documentation
INSTANCE
EmployeeMapper com.gmp.hr.mapper.EmployeeMapper.INSTANCE = Mappers.getMapper(EmployeeMapper.class) inherited
Definition at line 21 of file EmployeeMapper.java.
The documentation for this class was generated from the following file:
hr-service/target/generated-sources/annotations/com/gmp/hr/mapper/EmployeeMapperImpl.java