GMP系统: com.gmp.auth.entity.OperationLog Class Reference
com.gmp.auth.entity.OperationLog Class Reference
用户操作审计日志实体
Classes
class Builder
Builder内部类
enum Module
模块枚举
enum OperationType
操作类型枚举
enum Result
操作结果枚举
Public Member Functions
OperationLog ()
无参构造函数
OperationLog (Long id, Long userId, String username, String operation, String module, String action, Result result, String ipAddress, String userAgent, String requestData, String responseData, LocalDateTime operationTime, Integer durationMs, String metadata)
全参构造函数
Long getId ()
void setId (Long id)
Long getUserId ()
void setUserId (Long userId)
String getUsername ()
void setUsername (String username)
String getOperation ()
void setOperation (String operation)
String getModule ()
void setModule (String module)
String getAction ()
void setAction (String action)
Result getResult ()
void setResult (Result result)
String getIpAddress ()
void setIpAddress (String ipAddress)
String getUserAgent ()
void setUserAgent (String userAgent)
String getRequestData ()
void setRequestData (String requestData)
String getResponseData ()
void setResponseData (String responseData)
LocalDateTime getOperationTime ()
void setOperationTime (LocalDateTime operationTime)
Integer getDurationMs ()
void setDurationMs (Integer durationMs)
String getMetadata ()
void setMetadata (String metadata)
Static Public Member Functions
static Builder builder ()
Builder方法实现
static OperationLog createLoginLog (Long userId, String username, String ipAddress, String userAgent, boolean success)
创建登录日志
static OperationLog createLogoutLog (Long userId, String username, String ipAddress)
创建登出日志
static OperationLog createUserOperationLog (Long userId, String username, OperationType operationType, String action, boolean success)
创建用户操作日志
Protected Member Functions
void onCreate ()
预持久化处理
Private Attributes
Long id
Long userId
String username
String operation
String module
String action
Result result = Result.SUCCESS
String ipAddress
String userAgent
String requestData
String responseData
LocalDateTime operationTime
Integer durationMs
String metadata
Detailed Description
用户操作审计日志实体
Author
GMP系统开发团队
Definition at line 20 of file OperationLog.java.
Constructor & Destructor Documentation
OperationLog() [1/2]
com.gmp.auth.entity.OperationLog.OperationLog ()
无参构造函数
Definition at line 74 of file OperationLog.java.
References com.gmp.auth.entity.OperationLog.Result.SUCCESS.
OperationLog() [2/2]
com.gmp.auth.entity.OperationLog.OperationLog (Long id, Long userId, String username, String operation, String module, String action, Result result, String ipAddress, String userAgent, String requestData, String responseData, LocalDateTime operationTime, Integer durationMs, String metadata)
全参构造函数
Definition at line 82 of file OperationLog.java.
Member Function Documentation
builder()
static Builder com.gmp.auth.entity.OperationLog.builder () static
Builder方法实现
Definition at line 105 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLoginLog(), com.gmp.auth.entity.OperationLog.createLogoutLog(), and com.gmp.auth.entity.OperationLog.createUserOperationLog().
createLoginLog()
static OperationLog com.gmp.auth.entity.OperationLog.createLoginLog (Long userId, String username, String ipAddress, String userAgent, boolean success) static
创建登录日志
Definition at line 408 of file OperationLog.java.
References com.gmp.auth.entity.OperationLog.Module.AUTH, com.gmp.auth.entity.OperationLog.builder(), com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.OperationType.LOGIN, com.gmp.auth.entity.OperationLog.Result.SUCCESS, and com.gmp.auth.entity.OperationLog.Builder.userId.
createLogoutLog()
static OperationLog com.gmp.auth.entity.OperationLog.createLogoutLog (Long userId, String username, String ipAddress) static
创建登出日志
Definition at line 425 of file OperationLog.java.
References com.gmp.auth.entity.OperationLog.Module.AUTH, com.gmp.auth.entity.OperationLog.builder(), com.gmp.auth.entity.OperationLog.OperationType.LOGOUT, com.gmp.auth.entity.OperationLog.Result.SUCCESS, and com.gmp.auth.entity.OperationLog.Builder.userId.
createUserOperationLog()
static OperationLog com.gmp.auth.entity.OperationLog.createUserOperationLog (Long userId, String username, OperationType operationType, String action, boolean success) static
创建用户操作日志
Definition at line 440 of file OperationLog.java.
References com.gmp.auth.entity.OperationLog.builder(), com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.Result.SUCCESS, com.gmp.auth.entity.OperationLog.Module.USER, and com.gmp.auth.entity.OperationLog.Builder.userId.
getAction()
String com.gmp.auth.entity.OperationLog.getAction ()
Definition at line 246 of file OperationLog.java.
getDurationMs()
Integer com.gmp.auth.entity.OperationLog.getDurationMs ()
Definition at line 302 of file OperationLog.java.
getId()
Long com.gmp.auth.entity.OperationLog.getId ()
Definition at line 206 of file OperationLog.java.
getIpAddress()
String com.gmp.auth.entity.OperationLog.getIpAddress ()
Definition at line 262 of file OperationLog.java.
getMetadata()
String com.gmp.auth.entity.OperationLog.getMetadata ()
Definition at line 310 of file OperationLog.java.
getModule()
String com.gmp.auth.entity.OperationLog.getModule ()
Definition at line 238 of file OperationLog.java.
getOperation()
String com.gmp.auth.entity.OperationLog.getOperation ()
Definition at line 230 of file OperationLog.java.
getOperationTime()
LocalDateTime com.gmp.auth.entity.OperationLog.getOperationTime ()
Definition at line 294 of file OperationLog.java.
getRequestData()
String com.gmp.auth.entity.OperationLog.getRequestData ()
Definition at line 278 of file OperationLog.java.
getResponseData()
String com.gmp.auth.entity.OperationLog.getResponseData ()
Definition at line 286 of file OperationLog.java.
getResult()
Result com.gmp.auth.entity.OperationLog.getResult ()
Definition at line 254 of file OperationLog.java.
getUserAgent()
String com.gmp.auth.entity.OperationLog.getUserAgent ()
Definition at line 270 of file OperationLog.java.
getUserId()
Long com.gmp.auth.entity.OperationLog.getUserId ()
Definition at line 214 of file OperationLog.java.
getUsername()
String com.gmp.auth.entity.OperationLog.getUsername ()
Definition at line 222 of file OperationLog.java.
onCreate()
void com.gmp.auth.entity.OperationLog.onCreate () protected
预持久化处理
Definition at line 396 of file OperationLog.java.
References com.gmp.auth.entity.OperationLog.Result.SUCCESS.
setAction()
void com.gmp.auth.entity.OperationLog.setAction (String action)
Definition at line 250 of file OperationLog.java.
setDurationMs()
void com.gmp.auth.entity.OperationLog.setDurationMs (Integer durationMs)
Definition at line 306 of file OperationLog.java.
setId()
void com.gmp.auth.entity.OperationLog.setId (Long id)
Definition at line 210 of file OperationLog.java.
setIpAddress()
void com.gmp.auth.entity.OperationLog.setIpAddress (String ipAddress)
Definition at line 266 of file OperationLog.java.
setMetadata()
void com.gmp.auth.entity.OperationLog.setMetadata (String metadata)
Definition at line 314 of file OperationLog.java.
setModule()
void com.gmp.auth.entity.OperationLog.setModule (String module)
Definition at line 242 of file OperationLog.java.
setOperation()
void com.gmp.auth.entity.OperationLog.setOperation (String operation)
Definition at line 234 of file OperationLog.java.
setOperationTime()
void com.gmp.auth.entity.OperationLog.setOperationTime (LocalDateTime operationTime)
Definition at line 298 of file OperationLog.java.
setRequestData()
void com.gmp.auth.entity.OperationLog.setRequestData (String requestData)
Definition at line 282 of file OperationLog.java.
setResponseData()
void com.gmp.auth.entity.OperationLog.setResponseData (String responseData)
Definition at line 290 of file OperationLog.java.
setResult()
void com.gmp.auth.entity.OperationLog.setResult (Result result)
Definition at line 258 of file OperationLog.java.
setUserAgent()
void com.gmp.auth.entity.OperationLog.setUserAgent (String userAgent)
Definition at line 274 of file OperationLog.java.
setUserId()
void com.gmp.auth.entity.OperationLog.setUserId (Long userId)
Definition at line 218 of file OperationLog.java.
setUsername()
void com.gmp.auth.entity.OperationLog.setUsername (String username)
Definition at line 226 of file OperationLog.java.
Member Data Documentation
action
String com.gmp.auth.entity.OperationLog.action private
Definition at line 42 of file OperationLog.java.
durationMs
Integer com.gmp.auth.entity.OperationLog.durationMs private
Definition at line 66 of file OperationLog.java.
id
Long com.gmp.auth.entity.OperationLog.id private
Definition at line 24 of file OperationLog.java.
ipAddress
String com.gmp.auth.entity.OperationLog.ipAddress private
Definition at line 50 of file OperationLog.java.
metadata
String com.gmp.auth.entity.OperationLog.metadata private
Definition at line 69 of file OperationLog.java.
module
String com.gmp.auth.entity.OperationLog.module private
Definition at line 38 of file OperationLog.java.
operation
String com.gmp.auth.entity.OperationLog.operation private
Definition at line 34 of file OperationLog.java.
operationTime
LocalDateTime com.gmp.auth.entity.OperationLog.operationTime private
Definition at line 63 of file OperationLog.java.
requestData
String com.gmp.auth.entity.OperationLog.requestData private
Definition at line 56 of file OperationLog.java.
responseData
String com.gmp.auth.entity.OperationLog.responseData private
Definition at line 59 of file OperationLog.java.
result
Result com.gmp.auth.entity.OperationLog.result = Result.SUCCESS private
Definition at line 47 of file OperationLog.java.
userAgent
String com.gmp.auth.entity.OperationLog.userAgent private
Definition at line 53 of file OperationLog.java.
userId
Long com.gmp.auth.entity.OperationLog.userId private
Definition at line 27 of file OperationLog.java.
username
String com.gmp.auth.entity.OperationLog.username private
Definition at line 30 of file OperationLog.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/OperationLog.java