GMP系统: com.gmp.crm.dto.ApiResponse< T > Class Template Reference
com.gmp.crm.dto.ApiResponse< T > Class Template Reference
通用API响应DTO
Classes
class PageResponse
分页响应
Public Member Functions
ApiResponse ()
构造函数
Static Public Member Functions
static< T > ApiResponse< T > success (T data)
成功响应
static ApiResponse< Void > success ()
成功响应（无数据）
static< T > ApiResponse< T > error (int code, String message)
错误响应
Private Attributes
int code
响应状态码
String message
响应消息
T data
响应数据
LocalDateTime timestamp
响应时间
Detailed Description
通用API响应DTO
Author
TRAE AI
Definition at line 13 of file ApiResponse.java.
Constructor & Destructor Documentation
ApiResponse()
com.gmp.crm.dto.ApiResponse< T >.ApiResponse ()
构造函数
Definition at line 38 of file ApiResponse.java.
References com.gmp.crm.dto.ApiResponse< T >.ApiResponse().
Referenced by com.gmp.crm.dto.ApiResponse< T >.ApiResponse(), com.gmp.crm.dto.ApiResponse< T >.error(), and com.gmp.crm.dto.ApiResponse< T >.success().
Member Function Documentation
error()
static< T > ApiResponse< T > com.gmp.crm.dto.ApiResponse< T >.error (int code, String message) static
错误响应
Parameters
code 错误码
message 错误消息
Returns
错误响应对象
Definition at line 72 of file ApiResponse.java.
References com.gmp.crm.dto.ApiResponse< T >.ApiResponse(), com.gmp.crm.dto.ApiResponse< T >.code, and com.gmp.crm.dto.ApiResponse< T >.message.
success() [1/2]
static ApiResponse< Void > com.gmp.crm.dto.ApiResponse< T >.success () static
成功响应（无数据）
Returns
成功响应对象
Definition at line 61 of file ApiResponse.java.
References com.gmp.crm.dto.ApiResponse< T >.success().
Referenced by com.gmp.crm.dto.ApiResponse< T >.success().
success() [2/2]
static< T > ApiResponse< T > com.gmp.crm.dto.ApiResponse< T >.success (T data) static
成功响应
Parameters
data 响应数据
Returns
成功响应对象
Definition at line 48 of file ApiResponse.java.
References com.gmp.crm.dto.ApiResponse< T >.ApiResponse(), and com.gmp.crm.dto.ApiResponse< T >.data.
Member Data Documentation
code
int com.gmp.crm.dto.ApiResponse< T >.code private
响应状态码
Definition at line 18 of file ApiResponse.java.
Referenced by com.gmp.crm.dto.ApiResponse< T >.error().
data
T com.gmp.crm.dto.ApiResponse< T >.data private
响应数据
Definition at line 28 of file ApiResponse.java.
Referenced by com.gmp.crm.dto.ApiResponse< T >.success().
message
String com.gmp.crm.dto.ApiResponse< T >.message private
响应消息
Definition at line 23 of file ApiResponse.java.
Referenced by com.gmp.crm.dto.ApiResponse< T >.error().
timestamp
LocalDateTime com.gmp.crm.dto.ApiResponse< T >.timestamp private
响应时间
Definition at line 33 of file ApiResponse.java.
The documentation for this class was generated from the following file:
crm-sales/src/main/java/com/gmp/crm/dto/ApiResponse.java