GMP系统: com.gmp.auth.entity.UserTest Class Reference
com.gmp.auth.entity.UserTest Class Reference
User实体单元测试
Package Functions
void testUserCreation ()
void testUserStatusEnum ()
void testLoginAttemptsManagement ()
void testAccountLocking ()
void testLockedUserDetection ()
void testPasswordExpiration ()
void testUserStatusValidation ()
void testAuditFields ()
Detailed Description
User实体单元测试
Author
GMP系统开发团队
Definition at line 16 of file UserTest.java.
Member Function Documentation
testAccountLocking()
void com.gmp.auth.entity.UserTest.testAccountLocking () package
Definition at line 79 of file UserTest.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE, com.gmp.auth.entity.User.getLoginAttempts(), com.gmp.auth.entity.User.getUserStatus(), com.gmp.auth.entity.User.isLocked(), com.gmp.auth.entity.User.lockAccount(), com.gmp.auth.entity.User.UserStatus.LOCKED, and com.gmp.auth.entity.User.username.
testAuditFields()
void com.gmp.auth.entity.UserTest.testAuditFields () package
Definition at line 157 of file UserTest.java.
References com.gmp.auth.entity.User.createdAt.
testLockedUserDetection()
void com.gmp.auth.entity.UserTest.testLockedUserDetection () package
Definition at line 97 of file UserTest.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE, com.gmp.auth.entity.User.isLocked(), com.gmp.auth.entity.User.UserStatus.LOCKED, and com.gmp.auth.entity.User.userStatus.
testLoginAttemptsManagement()
void com.gmp.auth.entity.UserTest.testLoginAttemptsManagement () package
Definition at line 55 of file UserTest.java.
References com.gmp.auth.entity.User.getLoginAttempts(), com.gmp.auth.entity.User.incrementLoginAttempts(), com.gmp.auth.entity.User.resetLoginAttempts(), and com.gmp.auth.entity.User.username.
testPasswordExpiration()
void com.gmp.auth.entity.UserTest.testPasswordExpiration () package
Definition at line 122 of file UserTest.java.
References com.gmp.auth.entity.User.isPasswordExpired(), and com.gmp.auth.entity.User.passwordExpiredAt.
testUserCreation()
void com.gmp.auth.entity.UserTest.testUserCreation () package
Definition at line 19 of file UserTest.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE, com.gmp.auth.entity.User.getLoginAttempts(), com.gmp.auth.entity.User.getUsername(), com.gmp.auth.entity.User.getUserStatus(), and com.gmp.auth.entity.User.username.
testUserStatusEnum()
void com.gmp.auth.entity.UserTest.testUserStatusEnum () package
Definition at line 40 of file UserTest.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE, com.gmp.auth.entity.User.UserStatus.EXPIRED, com.gmp.auth.entity.User.UserStatus.INACTIVE, and com.gmp.auth.entity.User.UserStatus.LOCKED.
testUserStatusValidation()
void com.gmp.auth.entity.UserTest.testUserStatusValidation () package
Definition at line 143 of file UserTest.java.
References com.gmp.auth.entity.User.UserStatus.ACTIVE, com.gmp.auth.entity.User.UserStatus.EXPIRED, com.gmp.auth.entity.User.getUserStatus(), com.gmp.auth.entity.User.UserStatus.INACTIVE, com.gmp.auth.entity.User.UserStatus.LOCKED, and com.gmp.auth.entity.User.userStatus.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/UserTest.java