GMP系统: com.gmp.auth.service.MfaSessionManagerTest Class Reference
com.gmp.auth.service.MfaSessionManagerTest Class Reference
MfaSessionManager的单元测试类
Package Functions
void setUp ()
void testCreateSession ()
void testCreateSessionWithNullUser ()
void testGetSession ()
void testGetNonExistentSession ()
void testGetNullSessionId ()
void testInvalidateSession ()
void testInvalidateNullSession ()
void testFailedAttempts ()
void testCleanupExpiredSessions ()
Private Attributes
MfaSessionManager mfaSessionManager
User testUser
Detailed Description
MfaSessionManager的单元测试类
Definition at line 17 of file MfaSessionManagerTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.service.MfaSessionManagerTest.setUp () package
Definition at line 25 of file MfaSessionManagerTest.java.
testCleanupExpiredSessions()
void com.gmp.auth.service.MfaSessionManagerTest.testCleanupExpiredSessions () package
Definition at line 141 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.cleanupExpiredSessions(), com.gmp.auth.service.MfaSessionManager.createSession(), com.gmp.auth.service.MfaSessionManager.getSession(), and com.gmp.auth.service.MfaSessionManager.invalidateSession().
testCreateSession()
void com.gmp.auth.service.MfaSessionManagerTest.testCreateSession () package
Definition at line 35 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.createSession().
testCreateSessionWithNullUser()
void com.gmp.auth.service.MfaSessionManagerTest.testCreateSessionWithNullUser () package
Definition at line 46 of file MfaSessionManagerTest.java.
testFailedAttempts()
void com.gmp.auth.service.MfaSessionManagerTest.testFailedAttempts () package
Definition at line 113 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.createSession(), com.gmp.auth.service.MfaSessionManager.getSession(), and com.gmp.auth.service.MfaSessionManager.MfaSession.incrementFailedAttempts().
testGetNonExistentSession()
void com.gmp.auth.service.MfaSessionManagerTest.testGetNonExistentSession () package
Definition at line 70 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.getSession().
testGetNullSessionId()
void com.gmp.auth.service.MfaSessionManagerTest.testGetNullSessionId () package
Definition at line 80 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.getSession().
testGetSession()
void com.gmp.auth.service.MfaSessionManagerTest.testGetSession () package
Definition at line 55 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.createSession(), and com.gmp.auth.service.MfaSessionManager.getSession().
testInvalidateNullSession()
void com.gmp.auth.service.MfaSessionManagerTest.testInvalidateNullSession () package
Definition at line 106 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.invalidateSession().
testInvalidateSession()
void com.gmp.auth.service.MfaSessionManagerTest.testInvalidateSession () package
Definition at line 90 of file MfaSessionManagerTest.java.
References com.gmp.auth.service.MfaSessionManager.createSession(), com.gmp.auth.service.MfaSessionManager.getSession(), and com.gmp.auth.service.MfaSessionManager.invalidateSession().
Member Data Documentation
mfaSessionManager
MfaSessionManager com.gmp.auth.service.MfaSessionManagerTest.mfaSessionManager private
Definition at line 20 of file MfaSessionManagerTest.java.
testUser
User com.gmp.auth.service.MfaSessionManagerTest.testUser private
Definition at line 22 of file MfaSessionManagerTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/MfaSessionManagerTest.java