GMP系统: com.gmp.qms.client.MesClientFallback Class Reference
com.gmp.qms.client.MesClientFallback Class Reference
MES系统客户端降级类，实现服务降级机制 当MES系统不可用时，提供默认响应，确保QMS系统正常运行
Public Member Functions
BatchInfoDTO getBatchInfo (String batchNumber)
ProcessParameterDTO getProcessParameters (String processId)
void sendNotification (NotificationDTO notificationDTO)
String getBatchStatus (String batchNumber)
ProcessParameterDTO getBatchProcessExecution (String batchNumber)
BatchInfoDTO getBatchInfo (@PathVariable("batchNumber") String batchNumber)
获取批次信息
ProcessParameterDTO getProcessParameters (@PathVariable("processId") String processId)
获取工艺参数
void sendNotification (@RequestBody NotificationDTO notificationDTO)
发送通知到MES系统
String getBatchStatus (@PathVariable("batchNumber") String batchNumber)
获取批次生产状态
ProcessParameterDTO getBatchProcessExecution (@PathVariable("batchNumber") String batchNumber)
获取批次的工艺执行记录
Private Member Functions
void recordFallbackRequest (String operation, String identifier)
记录降级请求信息
void saveToRetryQueue (String operation, Object data)
保存到重试队列
Detailed Description
MES系统客户端降级类，实现服务降级机制 当MES系统不可用时，提供默认响应，确保QMS系统正常运行
Author
GMP系统开发团队
Definition at line 17 of file MesClientFallback.java.
Member Function Documentation
getBatchInfo() [1/2]
BatchInfoDTO com.gmp.qms.client.MesClient.getBatchInfo (@PathVariable("batchNumber") String batchNumber) inherited
获取批次信息
Parameters
batchNumber 批次号
Returns
批次信息
getBatchInfo() [2/2]
BatchInfoDTO com.gmp.qms.client.MesClientFallback.getBatchInfo (String batchNumber)
Definition at line 20 of file MesClientFallback.java.
References com.gmp.qms.client.MesClientFallback.recordFallbackRequest().
getBatchProcessExecution() [1/2]
ProcessParameterDTO com.gmp.qms.client.MesClient.getBatchProcessExecution (@PathVariable("batchNumber") String batchNumber) inherited
获取批次的工艺执行记录
Parameters
batchNumber 批次号
Returns
工艺参数信息
getBatchProcessExecution() [2/2]
ProcessParameterDTO com.gmp.qms.client.MesClientFallback.getBatchProcessExecution (String batchNumber)
Definition at line 61 of file MesClientFallback.java.
References com.gmp.qms.client.MesClientFallback.recordFallbackRequest().
getBatchStatus() [1/2]
String com.gmp.qms.client.MesClient.getBatchStatus (@PathVariable("batchNumber") String batchNumber) inherited
获取批次生产状态
Parameters
batchNumber 批次号
Returns
生产状态
getBatchStatus() [2/2]
String com.gmp.qms.client.MesClientFallback.getBatchStatus (String batchNumber)
Definition at line 54 of file MesClientFallback.java.
References com.gmp.qms.client.MesClientFallback.recordFallbackRequest().
getProcessParameters() [1/2]
ProcessParameterDTO com.gmp.qms.client.MesClient.getProcessParameters (@PathVariable("processId") String processId) inherited
获取工艺参数
Parameters
processId 工艺ID
Returns
工艺参数信息
getProcessParameters() [2/2]
ProcessParameterDTO com.gmp.qms.client.MesClientFallback.getProcessParameters (String processId)
Definition at line 34 of file MesClientFallback.java.
References com.gmp.qms.client.MesClientFallback.recordFallbackRequest().
recordFallbackRequest()
void com.gmp.qms.client.MesClientFallback.recordFallbackRequest (String operation, String identifier) private
记录降级请求信息
Parameters
operation 操作类型
identifier 标识符
Definition at line 79 of file MesClientFallback.java.
Referenced by com.gmp.qms.client.MesClientFallback.getBatchInfo(), com.gmp.qms.client.MesClientFallback.getBatchProcessExecution(), com.gmp.qms.client.MesClientFallback.getBatchStatus(), com.gmp.qms.client.MesClientFallback.getProcessParameters(), and com.gmp.qms.client.MesClientFallback.sendNotification().
saveToRetryQueue()
void com.gmp.qms.client.MesClientFallback.saveToRetryQueue (String operation, Object data) private
保存到重试队列
Parameters
operation 操作类型
data 数据对象
Definition at line 89 of file MesClientFallback.java.
Referenced by com.gmp.qms.client.MesClientFallback.sendNotification().
sendNotification() [1/2]
void com.gmp.qms.client.MesClient.sendNotification (@RequestBody NotificationDTO notificationDTO) inherited
发送通知到MES系统
Parameters
notificationDTO 通知信息
sendNotification() [2/2]
void com.gmp.qms.client.MesClientFallback.sendNotification (NotificationDTO notificationDTO)
Definition at line 47 of file MesClientFallback.java.
References com.gmp.qms.client.MesClientFallback.recordFallbackRequest(), and com.gmp.qms.client.MesClientFallback.saveToRetryQueue().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/client/MesClientFallback.java