GMP系统: com.gmp.auth.entity.UserRole Class Reference
com.gmp.auth.entity.UserRole Class Reference
用户角色关联实体
Public Member Functions
boolean isValid ()
检查关联是否有效
Protected Member Functions
void onCreate ()
预持久化处理
Private Attributes
Long id
Long userId
Long roleId
Boolean isActive = true
LocalDateTime assignedAt
LocalDateTime expiredAt
Long assignedBy
LocalDateTime assignedAtAudit
Detailed Description
用户角色关联实体
Author
GMP系统开发团队
Definition at line 23 of file UserRole.java.
Member Function Documentation
isValid()
boolean com.gmp.auth.entity.UserRole.isValid ()
检查关联是否有效
Definition at line 57 of file UserRole.java.
Referenced by com.gmp.auth.entity.UserRoleTest.testInactiveUserRole(), com.gmp.auth.entity.UserRoleTest.testMultipleUserRoles(), com.gmp.auth.entity.UserRoleTest.testUserRoleCreation(), com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationExactTime(), com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationNullCheck(), com.gmp.auth.entity.UserRoleTest.testUserRoleStatusTransitions(), and com.gmp.auth.entity.UserRoleTest.testUserRoleWithExpiration().
onCreate()
void com.gmp.auth.entity.UserRole.onCreate () protected
预持久化处理
Definition at line 68 of file UserRole.java.
Referenced by com.gmp.auth.entity.UserRoleTest.testUserRolePrePersist(), and com.gmp.auth.entity.UserRoleTest.testUserRoleWithAssignedTime().
Member Data Documentation
assignedAt
LocalDateTime com.gmp.auth.entity.UserRole.assignedAt private
Definition at line 42 of file UserRole.java.
assignedAtAudit
LocalDateTime com.gmp.auth.entity.UserRole.assignedAtAudit private
Definition at line 51 of file UserRole.java.
assignedBy
Long com.gmp.auth.entity.UserRole.assignedBy private
Definition at line 48 of file UserRole.java.
expiredAt
LocalDateTime com.gmp.auth.entity.UserRole.expiredAt private
Definition at line 45 of file UserRole.java.
id
Long com.gmp.auth.entity.UserRole.id private
Definition at line 27 of file UserRole.java.
isActive
Boolean com.gmp.auth.entity.UserRole.isActive = true private
Definition at line 39 of file UserRole.java.
roleId
Long com.gmp.auth.entity.UserRole.roleId private
Definition at line 35 of file UserRole.java.
userId
Long com.gmp.auth.entity.UserRole.userId private
Definition at line 31 of file UserRole.java.
Referenced by com.gmp.auth.entity.UserRoleTest.testInactiveUserRole(), com.gmp.auth.entity.UserRoleTest.testMultipleUserRoles(), com.gmp.auth.entity.UserRoleTest.testUserRoleAuditFields(), com.gmp.auth.entity.UserRoleTest.testUserRoleBulkOperations(), com.gmp.auth.entity.UserRoleTest.testUserRoleCreation(), com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationExactTime(), com.gmp.auth.entity.UserRoleTest.testUserRoleExpirationNullCheck(), com.gmp.auth.entity.UserRoleTest.testUserRolePrePersist(), com.gmp.auth.entity.UserRoleTest.testUserRoleStatusTransitions(), com.gmp.auth.entity.UserRoleTest.testUserRoleWithAssignedTime(), and com.gmp.auth.entity.UserRoleTest.testUserRoleWithExpiration().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/UserRole.java