GMP系统: com.gmp.auth.service.impl.AuthServiceImpl Class Reference
com.gmp.auth.service.impl.AuthServiceImpl Class Reference
Public Member Functions
UserDetails loadUserByUsername (String username) throws UsernameNotFoundException
LoginResponse login (LoginRequest request, String ipAddress, String userAgent)
用户登录
void logout (String username, String token)
用户登出
TokenResponse refreshToken (String refreshToken)
刷新访问令牌
boolean validateToken (String token)
验证JWT令牌
Long getUserIdFromToken (String token)
从令牌中获取用户ID
boolean hasPermission (String username, String... requiredPermissions)
验证用户权限
boolean hasRole (String username, String... requiredRoles)
验证用户角色
List< String > getUserPermissions (String username)
获取用户所有权限
Set< String > getUserRoles (String username)
获取用户所有角色
List< String > getUserPermissions (Long userId, Long organizationId)
Set< String > getUserRoles (Long userId, Long organizationId)
boolean changePassword (String username, PasswordChangeRequest request)
boolean resetPassword (String username, String newPassword)
重置密码
List< String > regenerateRecoveryCodes (String username)
重新生成恢复码
String getPasswordComplexityRequirements ()
获取密码复杂度要求
LoginResponse verifyMfa (MfaVerifyRequest request)
验证MFA
Integer getSubsystemAccessLevel (String username, String subsystemCode)
获取用户对子系统的访问级别
boolean hasSubsystemAccess (String username, String subsystemCode)
验证用户是否有子系统访问权限
boolean hasSubsystemAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统访问权限
List< String > getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
Map< String, Integer > getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
List< String > getUserAccessibleSubsystems (Long userId, Long organizationId)
Map< String, Integer > getUserSubsystemAccessLevels (Long userId, Long organizationId)
boolean hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统写权限
boolean hasSubsystemWriteAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统写权限
Set< String > getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
boolean hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
boolean hasSubsystemAdminAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统管理员权限
boolean hasOrganizationAccess (Long userId, Long organizationId)
验证用户是否有权限访问指定组织
boolean changePassword (String username, com.gmp.auth.dto.PasswordChangeRequest request)
修改密码
Private Member Functions
String generateRandomRecoveryCode ()
生成随机恢复码
boolean verifyRecoveryCode (User user, String code)
验证恢复码
void removeUsedRecoveryCode (User user, String usedCode)
移除已使用的恢复码
Private Attributes
UserRepository userRepository
AuditLogService auditLogService
UserPasswordHistoryService userPasswordHistoryService
UserOrganizationRoleService userOrganizationRoleService
PasswordEncoder passwordEncoder
SubsystemService subsystemService
JwtProperties jwtProperties
JwtUtil jwtUtil
TokenBlacklistService tokenBlacklistService
UserRoleService userRoleService
RolePermissionService rolePermissionService
AuthenticationManager authenticationManager
PasswordPolicyService passwordPolicyService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(AuthServiceImpl.class)
Detailed Description
Definition at line 58 of file AuthServiceImpl.java.
Member Function Documentation
changePassword() [1/2]
boolean com.gmp.auth.service.AuthService.changePassword (String username, com.gmp.auth.dto.PasswordChangeRequest request) inherited
修改密码
处理用户密码修改请求
Parameters
username 用户名
request 密码修改请求，包含旧密码和新密码
Returns
boolean 如果密码修改成功返回true，否则返回false
See also
com.gmp.auth.dto.PasswordChangeRequest
changePassword() [2/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.changePassword (String username, PasswordChangeRequest request)
Definition at line 509 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.impl.AuthServiceImpl.passwordEncoder, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), and com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success().
generateRandomRecoveryCode()
String com.gmp.auth.service.impl.AuthServiceImpl.generateRandomRecoveryCode () private
生成随机恢复码
Definition at line 625 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes().
getPasswordComplexityRequirements()
String com.gmp.auth.service.impl.AuthServiceImpl.getPasswordComplexityRequirements ()
获取密码复杂度要求
获取系统的密码复杂度要求描述
Returns
String 密码复杂度要求描述
Implements com.gmp.auth.service.AuthService.
Definition at line 630 of file AuthServiceImpl.java.
getSubsystemAccessLevel()
Integer com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel (String username, String subsystemCode)
获取用户对子系统的访问级别
获取用户对指定子系统的访问级别
Parameters
username 用户名
subsystemCode 子系统代码
Returns
Integer 访问级别，无权限返回0
Implements com.gmp.auth.service.AuthService.
Definition at line 828 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.getUserSubsystemAccessLevels(), com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess(), com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testGetSubsystemAccessLevel().
getUserAccessibleSubsystemCodes()
Set< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
获取用户可以访问的所有子系统代码集合
Parameters
username 用户名
Returns
Set<String> 子系统代码集合
Implements com.gmp.auth.service.AuthService.
Definition at line 979 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserAccessibleSubsystems(), com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess(), com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
getUserAccessibleSubsystems() [1/2]
List< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems (Long userId, Long organizationId)
Definition at line 906 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.logger, and com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService.
getUserAccessibleSubsystems() [2/2]
List< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
获取用户可以访问的所有子系统列表
Parameters
username 用户名
Returns
List<String> 可访问的子系统列表
Implements com.gmp.auth.service.AuthService.
Definition at line 889 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess(), and com.gmp.auth.service.impl.AuthServiceImpl.login().
getUserIdFromToken()
Long com.gmp.auth.service.impl.AuthServiceImpl.getUserIdFromToken (String token)
从令牌中获取用户ID
Parameters
token JWT令牌
Returns
用户ID
Definition at line 393 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.logger.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.refreshToken().
getUserPermissions() [1/2]
List< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions (Long userId, Long organizationId)
Definition at line 468 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesAcrossOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesInOrganization(), and com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService.
getUserPermissions() [2/2]
List< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions (String username)
获取用户所有权限
获取用户拥有的所有权限列表
Parameters
username 用户名
Returns
java.util.List<String> 用户权限列表
Implements com.gmp.auth.service.AuthService.
Definition at line 453 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), and com.gmp.auth.service.impl.AuthServiceImpl.login().
getUserRoles() [1/2]
Set< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles (Long userId, Long organizationId)
Definition at line 486 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.getUserRoleCodesInOrganization(), and com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService.
getUserRoles() [2/2]
Set< String > com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles (String username)
获取用户所有角色
获取用户拥有的所有角色列表
Parameters
username 用户名
Returns
java.util.Set<String> 用户角色列表
Implements com.gmp.auth.service.AuthService.
Definition at line 461 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles().
getUserSubsystemAccessLevels() [1/2]
Map< String, Integer > com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels (Long userId, Long organizationId)
Definition at line 922 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserSubsystemAccessLevels(), com.gmp.auth.service.impl.AuthServiceImpl.logger, and com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService.
getUserSubsystemAccessLevels() [2/2]
Map< String, Integer > com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
获取用户对所有子系统的访问级别映射
Parameters
username 用户名
Returns
Map<String, Integer> 子系统代码与访问级别的映射
Implements com.gmp.auth.service.AuthService.
Definition at line 898 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess(), com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImplTest.testGetSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_NoAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_ReadAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithAdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithoutAdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_AdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_HasWriteAccess(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_NoWriteAccess().
hasOrganizationAccess()
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasOrganizationAccess (Long userId, Long organizationId)
验证用户是否有权限访问指定组织
Parameters
userId 用户ID
organizationId 组织ID
Returns
有权限返回true，否则返回false
Definition at line 1044 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess(), and com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService.
hasPermission()
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasPermission (String username, String... requiredPermissions)
验证用户权限
验证用户是否拥有指定的权限
Parameters
username 用户名
requiredPermissions 需要的权限列表
Returns
boolean 如果用户拥有所有指定权限返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 405 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesAcrossOrganizations(), com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission().
hasRole()
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasRole (String username, String... requiredRoles)
验证用户角色
验证用户是否拥有指定的角色
Parameters
username 用户名
requiredRoles 需要的角色列表
Returns
boolean 如果用户拥有所有指定角色返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 425 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.getUserRoleCodesInOrganization(), com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole().
hasSubsystemAccess() [1/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统访问权限
Parameters
userId 用户ID
organizationId 组织ID
subsystemCode 子系统代码
Returns
有权限返回true，否则返回false
Definition at line 870 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), and com.gmp.auth.service.impl.AuthServiceImpl.logger.
hasSubsystemAccess() [2/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess (String username, String subsystemCode)
验证用户是否有子系统访问权限
验证用户是否可以访问指定的子系统
Parameters
username 用户名
subsystemCode 子系统代码
Returns
boolean 如果用户有访问权限返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 856 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_NoAccess(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_ReadAccess().
hasSubsystemAdminAccess() [1/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统管理员权限
Parameters
userId 用户ID
organizationId 组织ID
subsystemCode 子系统代码
Returns
有权限返回true，否则返回false
Definition at line 1019 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.logger.
hasSubsystemAdminAccess() [2/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
检查用户是否对指定子系统有管理权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
boolean 如果用户有管理权限返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 1002 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithAdminAccess(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithoutAdminAccess().
hasSubsystemWriteAccess() [1/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess (Long userId, Long organizationId, String subsystemCode)
检查用户是否有子系统写权限
Parameters
userId 用户ID
organizationId 组织ID
subsystemCode 子系统代码
Returns
有权限返回true，否则返回false
Definition at line 958 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.logger.
hasSubsystemWriteAccess() [2/2]
boolean com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统写权限
Implements com.gmp.auth.service.AuthService.
Definition at line 941 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_AdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_HasWriteAccess(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_NoWriteAccess().
loadUserByUsername()
UserDetails com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername (String username) throws UsernameNotFoundException
Definition at line 115 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImpl.userRepository, and com.gmp.auth.service.impl.AuthServiceImpl.userRoleService.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_AccountDisabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_UserNotFound().
login()
LoginResponse com.gmp.auth.service.impl.AuthServiceImpl.login (LoginRequest request, String ipAddress, String userAgent)
用户登录
处理用户登录请求，验证用户凭证，生成JWT令牌
Parameters
request 登录请求，包含用户名和密码
ipAddress 客户端IP地址，用于审计日志
userAgent 用户代理，用于审计日志
Returns
LoginResponse 登录响应，包含JWT令牌和用户信息
See also
com.gmp.auth.dto.LoginRequest
com.gmp.auth.dto.LoginResponse
Implements com.gmp.auth.service.AuthService.
Definition at line 156 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.authenticationManager, com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), com.gmp.auth.service.UserOrganizationRoleService.getUserRoleCodesInOrganization(), com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess(), com.gmp.auth.service.impl.AuthServiceImpl.jwtProperties, com.gmp.auth.service.impl.AuthServiceImpl.jwtUtil, com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired(), and com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success().
logout()
void com.gmp.auth.service.impl.AuthServiceImpl.logout (String username, String token)
用户登出
处理用户登出请求，将JWT令牌加入黑名单
Parameters
username 用户名
token JWT令牌
Implements com.gmp.auth.service.AuthService.
Definition at line 282 of file AuthServiceImpl.java.
References com.gmp.auth.service.TokenBlacklistService.blacklistToken(), com.gmp.auth.service.impl.AuthServiceImpl.jwtUtil, com.gmp.auth.service.impl.AuthServiceImpl.logger, and com.gmp.auth.service.impl.AuthServiceImpl.tokenBlacklistService.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLogout().
refreshToken()
TokenResponse com.gmp.auth.service.impl.AuthServiceImpl.refreshToken (String refreshToken)
刷新访问令牌
使用刷新令牌生成新的访问令牌
Parameters
refreshToken 刷新令牌
Returns
com.gmp.auth.dto.TokenResponse 新的令牌响应
See also
com.gmp.auth.dto.TokenResponse
Implements com.gmp.auth.service.AuthService.
Definition at line 306 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.getUserIdFromToken(), com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess(), com.gmp.auth.service.TokenBlacklistService.isTokenBlacklisted(), com.gmp.auth.service.impl.AuthServiceImpl.jwtProperties, com.gmp.auth.service.impl.AuthServiceImpl.jwtUtil, com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImpl.tokenBlacklistService, com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService, com.gmp.auth.service.impl.AuthServiceImpl.userRepository, and com.gmp.auth.service.impl.AuthServiceImpl.validateToken().
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
regenerateRecoveryCodes()
List< String > com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes (String username)
重新生成恢复码
为用户重新生成MFA恢复码
Parameters
username 用户名
Returns
java.util.List<String> 新的恢复码列表
Implements com.gmp.auth.service.AuthService.
Definition at line 583 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.generateRandomRecoveryCode(), com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.AuditLogService.logSecurityEvent(), and com.gmp.auth.service.impl.AuthServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes(), and com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes_MfaNotEnabled().
removeUsedRecoveryCode()
void com.gmp.auth.service.impl.AuthServiceImpl.removeUsedRecoveryCode (User user, String usedCode) private
移除已使用的恢复码
Definition at line 809 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
resetPassword()
boolean com.gmp.auth.service.impl.AuthServiceImpl.resetPassword (String username, String newPassword)
重置密码
重置用户密码
Parameters
username 用户名
newPassword 新密码
Returns
boolean 如果密码重置成功返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 537 of file AuthServiceImpl.java.
References com.gmp.auth.service.impl.AuthServiceImpl.auditLogService, com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.AuditLogService.logPasswordReset(), com.gmp.auth.service.impl.AuthServiceImpl.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImpl.passwordPolicyService, com.gmp.auth.service.UserPasswordHistoryService.savePasswordHistory(), com.gmp.auth.service.impl.AuthServiceImpl.userPasswordHistoryService, com.gmp.auth.service.impl.AuthServiceImpl.userRepository, and com.gmp.auth.service.PasswordPolicyService.validatePassword().
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success().
validateToken()
boolean com.gmp.auth.service.impl.AuthServiceImpl.validateToken (String token)
验证JWT令牌
验证JWT令牌的有效性，包括签名、过期时间等
Parameters
token JWT令牌
Returns
boolean 如果令牌有效返回true，否则返回false
Implements com.gmp.auth.service.AuthService.
Definition at line 368 of file AuthServiceImpl.java.
References com.gmp.auth.service.TokenBlacklistService.isTokenBlacklisted(), com.gmp.auth.service.impl.AuthServiceImpl.logger, and com.gmp.auth.service.impl.AuthServiceImpl.tokenBlacklistService.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_BlacklistedToken(), and com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_ExpiredToken().
verifyMfa()
LoginResponse com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa (MfaVerifyRequest request)
验证MFA
验证多因素认证码
Parameters
request MFA验证请求，包含用户名和MFA码
Returns
LoginResponse 登录响应，包含JWT令牌
See also
com.gmp.auth.dto.MfaVerifyRequest
com.gmp.auth.dto.LoginResponse
Implements com.gmp.auth.service.AuthService.
Definition at line 635 of file AuthServiceImpl.java.
References com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImpl.jwtUtil, com.gmp.auth.service.impl.AuthServiceImpl.logger, com.gmp.auth.service.AuditLogService.logLoginFailure(), com.gmp.auth.service.AuditLogService.logSecurityEvent(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImpl.removeUsedRecoveryCode(), com.gmp.auth.service.impl.AuthServiceImpl.userRepository, com.gmp.auth.service.impl.AuthServiceImpl.userRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.verifyRecoveryCode().
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_InvalidSession(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
verifyRecoveryCode()
boolean com.gmp.auth.service.impl.AuthServiceImpl.verifyRecoveryCode (User user, String code) private
验证恢复码
Definition at line 792 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
Member Data Documentation
auditLogService
AuditLogService com.gmp.auth.service.impl.AuthServiceImpl.auditLogService private
Definition at line 66 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.resetPassword().
authenticationManager
AuthenticationManager com.gmp.auth.service.impl.AuthServiceImpl.authenticationManager private
Definition at line 97 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.login().
jwtProperties
JwtProperties com.gmp.auth.service.impl.AuthServiceImpl.jwtProperties private
Definition at line 81 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.login(), and com.gmp.auth.service.impl.AuthServiceImpl.refreshToken().
jwtUtil
JwtUtil com.gmp.auth.service.impl.AuthServiceImpl.jwtUtil private
Definition at line 84 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImpl.logout(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
logger
final Logger com.gmp.auth.service.impl.AuthServiceImpl.logger = LoggerFactory.getLogger(AuthServiceImpl.class) static private
Definition at line 60 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.getUserIdFromToken(), com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess(), com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImpl.logout(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImpl.resetPassword(), com.gmp.auth.service.impl.AuthServiceImpl.validateToken(), and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
passwordEncoder
PasswordEncoder com.gmp.auth.service.impl.AuthServiceImpl.passwordEncoder private
Definition at line 75 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), and com.gmp.auth.service.impl.AuthServiceImpl.resetPassword().
passwordPolicyService
PasswordPolicyService com.gmp.auth.service.impl.AuthServiceImpl.passwordPolicyService private
Definition at line 100 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.resetPassword().
rolePermissionService
RolePermissionService com.gmp.auth.service.impl.AuthServiceImpl.rolePermissionService private
Definition at line 93 of file AuthServiceImpl.java.
subsystemService
SubsystemService com.gmp.auth.service.impl.AuthServiceImpl.subsystemService private
Definition at line 78 of file AuthServiceImpl.java.
tokenBlacklistService
TokenBlacklistService com.gmp.auth.service.impl.AuthServiceImpl.tokenBlacklistService private
Definition at line 87 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.logout(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), and com.gmp.auth.service.impl.AuthServiceImpl.validateToken().
userOrganizationRoleService
UserOrganizationRoleService com.gmp.auth.service.impl.AuthServiceImpl.userOrganizationRoleService private
Definition at line 72 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles(), com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), com.gmp.auth.service.impl.AuthServiceImpl.hasOrganizationAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasPermission(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), com.gmp.auth.service.impl.AuthServiceImpl.login(), and com.gmp.auth.service.impl.AuthServiceImpl.refreshToken().
userPasswordHistoryService
UserPasswordHistoryService com.gmp.auth.service.impl.AuthServiceImpl.userPasswordHistoryService private
Definition at line 69 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.resetPassword().
userRepository
UserRepository com.gmp.auth.service.impl.AuthServiceImpl.userRepository private
Definition at line 63 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems(), com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles(), com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), com.gmp.auth.service.impl.AuthServiceImpl.hasPermission(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess(), com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess(), com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername(), com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImpl.resetPassword(), and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
userRoleService
UserRoleService com.gmp.auth.service.impl.AuthServiceImpl.userRoleService private
Definition at line 90 of file AuthServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername(), and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/AuthServiceImpl.java