GMP系统: com.gmp.mes.service.ProductionBatchService Class Reference
com.gmp.mes.service.ProductionBatchService Class Reference
生产批次服务 - 实现批次管理的核心业务逻辑
Public Member Functions
ProductionBatch createBatch (ProductionBatch batch)
创建生产批次
Optional< ProductionBatch > getBatchById (Long id)
根据ID获取批次
Optional< ProductionBatch > getBatchByNumber (String batchNumber)
根据批次编号获取批次
List< ProductionBatch > getAllBatches ()
获取所有批次
List< ProductionBatch > getBatchesByStatus (ProductionBatch.BatchStatus status)
根据状态获取批次
List< ProductionBatch > getBatchesByOrderId (Long orderId)
根据订单ID获取批次
ProductionBatch updateBatch (ProductionBatch batch)
更新批次
ProductionBatch startBatch (String batchNumber, String equipmentId)
开始批次生产
ProductionBatch completeBatch (String batchNumber)
完成批次生产
ProductionBatch suspendBatch (String batchNumber)
暂停批次生产
ProductionBatch resumeBatch (String batchNumber)
恢复暂停的批次
ProductionBatch failBatch (String batchNumber, String notes)
标记批次失败
void deleteBatch (Long id)
删除批次
ProductionBatch completeProductionBatch (Long batchId, String operator, Integer completedQuantity)
完成生产批次（按ID）
ProductionBatch failProductionBatch (Long batchId, String operator, String reason)
标记生产批次为失败（按ID）
ProductionBatch resumeProductionBatch (Long batchId, String operator)
恢复暂停的生产批次（按ID）
void deleteProductionBatch (Long batchId)
删除生产批次（兼容方法）
List< ProductionBatch > getProductionBatchesByTimeRange (LocalDateTime startTime, LocalDateTime endTime)
根据时间范围获取生产批次
List< ProductionBatch > getActiveProductionBatches ()
获取活跃的生产批次（进行中或已暂停）
ProductionBatch updateProductionBatch (ProductionBatch batch)
更新生产批次（兼容方法）
ProductionBatch startProductionBatch (Long batchId, String equipmentId)
开始生产批次（按ID）
ProductionBatch pauseProductionBatch (Long batchId, String operator, String reason)
暂停生产批次（按ID）
List< ProductionBatch > getProductionBatchesByOrderId (Long orderId)
根据订单ID获取生产批次列表
List< ProductionBatch > getProductionBatchesByStatus (ProductionBatch.BatchStatus status)
根据状态获取生产批次列表
List< ProductionBatch > getProductionBatchesByEquipmentId (String equipmentId)
根据设备ID获取生产批次列表
ProductionBatch createProductionBatch (ProductionBatch batch)
创建生产批次（兼容方法）
List< ProductionBatch > getAllProductionBatches ()
获取所有生产批次（兼容方法）
Optional< ProductionBatch > getProductionBatchById (Long batchId)
根据ID获取生产批次（兼容方法）
Optional< ProductionBatch > getProductionBatchByBatchNumber (String batchNumber)
根据批次号获取生产批次
Private Member Functions
void updateOrderStatusIfNeeded (ProductionBatch batch)
如果订单的所有批次都完成，则更新订单状态
String generateBatchNumber ()
生成批次编号
Private Attributes
ProductionBatchRepository productionBatchRepository
ProductionOrderRepository productionOrderRepository
Detailed Description
生产批次服务 - 实现批次管理的核心业务逻辑
Author
gmp-system
Definition at line 23 of file ProductionBatchService.java.
Member Function Documentation
completeBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.completeBatch (String batchNumber)
完成批次生产
Parameters
batchNumber 批次编号
Returns
完成生产的批次
Definition at line 142 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository, and com.gmp.mes.service.ProductionBatchService.updateOrderStatusIfNeeded().
completeProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.completeProductionBatch (Long batchId, String operator, Integer completedQuantity)
完成生产批次（按ID）
Parameters
batchId 批次ID
operator 操作员
completedQuantity 完成数量
Returns
完成的批次
Definition at line 251 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById(), com.gmp.mes.service.ProductionBatchService.productionBatchRepository, and com.gmp.mes.service.ProductionBatchService.updateOrderStatusIfNeeded().
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testCompleteProductionBatch().
createBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.createBatch (ProductionBatch batch)
创建生产批次
Parameters
batch 生产批次对象
Returns
创建的生产批次
Definition at line 38 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.generateBatchNumber(), and com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchService.createProductionBatch().
createProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.createProductionBatch (ProductionBatch batch)
创建生产批次（兼容方法）
Parameters
batch 批次对象
Returns
创建的批次
Definition at line 441 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.createBatch().
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testCreateProductionBatch().
deleteBatch()
void com.gmp.mes.service.ProductionBatchService.deleteBatch (Long id)
删除批次
Parameters
id 批次ID
Definition at line 238 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchService.deleteProductionBatch().
deleteProductionBatch()
void com.gmp.mes.service.ProductionBatchService.deleteProductionBatch (Long batchId)
删除生产批次（兼容方法）
Parameters
batchId 批次ID
Definition at line 319 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.deleteBatch().
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testDeleteProductionBatch().
failBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.failBatch (String batchNumber, String notes)
标记批次失败
Parameters
batchNumber 批次编号
notes 失败原因
Returns
标记为失败的批次
Definition at line 214 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
failProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.failProductionBatch (Long batchId, String operator, String reason)
标记生产批次为失败（按ID）
Parameters
batchId 批次ID
operator 操作员
reason 失败原因
Returns
失败的批次
Definition at line 277 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById(), and com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
generateBatchNumber()
String com.gmp.mes.service.ProductionBatchService.generateBatchNumber () private
生成批次编号
Returns
批次编号
Definition at line 498 of file ProductionBatchService.java.
Referenced by com.gmp.mes.service.ProductionBatchService.createBatch(), and com.gmp.mes.service.ProductionBatchServiceTest.testGenerateBatchNumber().
getActiveProductionBatches()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getActiveProductionBatches ()
获取活跃的生产批次（进行中或已暂停）
Returns
活跃批次列表
Definition at line 341 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getAllBatches()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getAllBatches ()
获取所有批次
Returns
批次列表
Definition at line 75 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getAllProductionBatches()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getAllProductionBatches ()
获取所有生产批次（兼容方法）
Returns
所有批次列表
Definition at line 450 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testGetAllProductionBatches().
getBatchById()
Optional< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getBatchById (Long id)
根据ID获取批次
Parameters
id 批次ID
Returns
批次对象
Definition at line 56 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchService.completeProductionBatch(), com.gmp.mes.service.ProductionBatchService.failProductionBatch(), com.gmp.mes.service.ProductionBatchService.getProductionBatchById(), com.gmp.mes.service.ProductionBatchService.pauseProductionBatch(), com.gmp.mes.service.ProductionBatchService.resumeProductionBatch(), and com.gmp.mes.service.ProductionBatchService.startProductionBatch().
getBatchByNumber()
Optional< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getBatchByNumber (String batchNumber)
根据批次编号获取批次
Parameters
batchNumber 批次编号
Returns
批次对象
Definition at line 66 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getBatchesByOrderId()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getBatchesByOrderId (Long orderId)
根据订单ID获取批次
Parameters
orderId 订单ID
Returns
批次列表
Definition at line 95 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getBatchesByStatus()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getBatchesByStatus (ProductionBatch.BatchStatus status)
根据状态获取批次
Parameters
status 批次状态
Returns
批次列表
Definition at line 85 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getProductionBatchByBatchNumber()
Optional< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchByBatchNumber (String batchNumber)
根据批次号获取生产批次
Parameters
batchNumber 批次号
Returns
批次对象
Definition at line 470 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testGetProductionBatchByBatchNumber().
getProductionBatchById()
Optional< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchById (Long batchId)
根据ID获取生产批次（兼容方法）
Parameters
batchId 批次ID
Returns
批次对象
Definition at line 460 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById().
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testCreateBatchOperation(), and com.gmp.mes.service.ProductionBatchServiceTest.testGetProductionBatchById().
getProductionBatchesByEquipmentId()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchesByEquipmentId (String equipmentId)
根据设备ID获取生产批次列表
Parameters
equipmentId 设备ID
Returns
批次列表
Definition at line 430 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getProductionBatchesByOrderId()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchesByOrderId (Long orderId)
根据订单ID获取生产批次列表
Parameters
orderId 订单ID
Returns
批次列表
Definition at line 410 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testGetProductionBatchesByOrderId().
getProductionBatchesByStatus()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchesByStatus (ProductionBatch.BatchStatus status)
根据状态获取生产批次列表
Parameters
status 批次状态
Returns
批次列表
Definition at line 420 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
getProductionBatchesByTimeRange()
List< ProductionBatch > com.gmp.mes.service.ProductionBatchService.getProductionBatchesByTimeRange (LocalDateTime startTime, LocalDateTime endTime)
根据时间范围获取生产批次
Parameters
startTime 开始时间
endTime 结束时间
Returns
批次列表
Definition at line 330 of file ProductionBatchService.java.
pauseProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.pauseProductionBatch (Long batchId, String operator, String reason)
暂停生产批次（按ID）
Parameters
batchId 批次ID
operator 操作员
reason 暂停原因
Returns
暂停的批次
Definition at line 391 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById(), and com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testPauseProductionBatch().
resumeBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.resumeBatch (String batchNumber)
恢复暂停的批次
Parameters
batchNumber 批次编号
Returns
恢复的批次
Definition at line 191 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
resumeProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.resumeProductionBatch (Long batchId, String operator)
恢复暂停的生产批次（按ID）
Parameters
batchId 批次ID
operator 操作员
Returns
恢复的批次
Definition at line 300 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById(), and com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testResumeProductionBatch().
startBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.startBatch (String batchNumber, String equipmentId)
开始批次生产
Parameters
batchNumber 批次编号
equipmentId 设备ID
Returns
开始生产的批次
Definition at line 118 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
startProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.startProductionBatch (Long batchId, String equipmentId)
开始生产批次（按ID）
Parameters
batchId 批次ID
equipmentId 设备ID
Returns
开始生产的批次
Definition at line 367 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.getBatchById(), and com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testStartProductionBatch().
suspendBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.suspendBatch (String batchNumber)
暂停批次生产
Parameters
batchNumber 批次编号
Returns
暂停的批次
Definition at line 169 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
updateBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.updateBatch (ProductionBatch batch)
更新批次
Parameters
batch 批次对象
Returns
更新后的批次
Definition at line 106 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository.
Referenced by com.gmp.mes.service.ProductionBatchService.updateProductionBatch().
updateOrderStatusIfNeeded()
void com.gmp.mes.service.ProductionBatchService.updateOrderStatusIfNeeded (ProductionBatch batch) private
如果订单的所有批次都完成，则更新订单状态
Parameters
batch 批次对象
Definition at line 479 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.productionBatchRepository, and com.gmp.mes.service.ProductionBatchService.productionOrderRepository.
Referenced by com.gmp.mes.service.ProductionBatchService.completeBatch(), and com.gmp.mes.service.ProductionBatchService.completeProductionBatch().
updateProductionBatch()
ProductionBatch com.gmp.mes.service.ProductionBatchService.updateProductionBatch (ProductionBatch batch)
更新生产批次（兼容方法）
Parameters
batch 批次对象
Returns
更新后的批次
Definition at line 355 of file ProductionBatchService.java.
References com.gmp.mes.service.ProductionBatchService.updateBatch().
Referenced by com.gmp.mes.service.ProductionBatchServiceTest.testUpdateProductionBatch().
Member Data Documentation
productionBatchRepository
ProductionBatchRepository com.gmp.mes.service.ProductionBatchService.productionBatchRepository private
Definition at line 26 of file ProductionBatchService.java.
Referenced by com.gmp.mes.service.ProductionBatchService.completeBatch(), com.gmp.mes.service.ProductionBatchService.completeProductionBatch(), com.gmp.mes.service.ProductionBatchService.createBatch(), com.gmp.mes.service.ProductionBatchService.deleteBatch(), com.gmp.mes.service.ProductionBatchService.failBatch(), com.gmp.mes.service.ProductionBatchService.failProductionBatch(), com.gmp.mes.service.ProductionBatchService.getActiveProductionBatches(), com.gmp.mes.service.ProductionBatchService.getAllBatches(), com.gmp.mes.service.ProductionBatchService.getAllProductionBatches(), com.gmp.mes.service.ProductionBatchService.getBatchById(), com.gmp.mes.service.ProductionBatchService.getBatchByNumber(), com.gmp.mes.service.ProductionBatchService.getBatchesByOrderId(), com.gmp.mes.service.ProductionBatchService.getBatchesByStatus(), com.gmp.mes.service.ProductionBatchService.getProductionBatchByBatchNumber(), com.gmp.mes.service.ProductionBatchService.getProductionBatchesByEquipmentId(), com.gmp.mes.service.ProductionBatchService.getProductionBatchesByOrderId(), com.gmp.mes.service.ProductionBatchService.getProductionBatchesByStatus(), com.gmp.mes.service.ProductionBatchService.pauseProductionBatch(), com.gmp.mes.service.ProductionBatchService.resumeBatch(), com.gmp.mes.service.ProductionBatchService.resumeProductionBatch(), com.gmp.mes.service.ProductionBatchService.startBatch(), com.gmp.mes.service.ProductionBatchService.startProductionBatch(), com.gmp.mes.service.ProductionBatchService.suspendBatch(), com.gmp.mes.service.ProductionBatchService.updateBatch(), and com.gmp.mes.service.ProductionBatchService.updateOrderStatusIfNeeded().
productionOrderRepository
ProductionOrderRepository com.gmp.mes.service.ProductionBatchService.productionOrderRepository private
Definition at line 29 of file ProductionBatchService.java.
Referenced by com.gmp.mes.service.ProductionBatchService.updateOrderStatusIfNeeded().
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/service/ProductionBatchService.java