GMP系统: com.gmp.training.service.impl.DepartmentServiceImpl Class Reference
com.gmp.training.service.impl.DepartmentServiceImpl Class Reference
部门服务实现类
Public Member Functions
Department save (Department department)
保存部门
void deleteById (Long id)
根据ID删除部门
Optional< Department > findById (Long id)
根据ID查询部门
List< Department > findAll ()
查询所有部门
Page< Department > findAll (Pageable pageable)
分页查询部门
List< Department > findByNameContaining (String name)
根据名称模糊查询部门
List< Department > findActiveDepartments ()
查询所有启用的部门
Page< Department > findActiveDepartments (Pageable pageable)
查询所有启用的部门（分页）
List< Department > findChildrenByParentId (Long parentId)
根据上级部门ID查询子部门
List< Department > findAncestorsById (Long id)
根据部门ID查询所有祖先部门
List< Department > findDescendantsById (Long id)
根据部门ID查询所有后代部门
List< Department > findRootDepartments ()
查询根部门（无上级部门的部门）
List< Department > findByGmpRelated (boolean gmpRelated)
根据GMP关联状态查询部门
Page< Department > findByGmpRelated (boolean gmpRelated, Pageable pageable)
根据GMP关联状态查询部门（分页）
boolean existsByName (String name, Long excludeId)
检查部门名称是否已存在
boolean existsByCode (String code, Long excludeId)
检查部门编码是否已存在
void updateStatus (Long id, Department.Status status)
更新部门状态
List< Department > findByManagerId (Long managerId)
根据部门负责人查询部门
Optional< Department > findByCode (String code)
根据部门编码查询部门
boolean existsByName (String name)
检查部门名称是否已存在（新增操作）
boolean existsByCode (String code)
检查部门编码是否已存在（新增操作）
Department updateStatus (Long id, Boolean active)
更新部门状态
Department updateParent (Long id, Long parentId)
更新部门父级
Integer batchDisable (List< Long > ids)
批量禁用部门
Private Member Functions
void findDescendantsRecursive (Long parentId, List< Department > descendants)
Private Attributes
final DepartmentRepository departmentRepository
Detailed Description
部门服务实现类
Author
GMP系统开发团队
Definition at line 25 of file DepartmentServiceImpl.java.
Member Function Documentation
batchDisable()
Integer com.gmp.training.service.impl.DepartmentServiceImpl.batchDisable (List< Long > ids)
批量禁用部门
Parameters
ids 部门ID列表
Returns
影响的行数
Implements com.gmp.training.service.DepartmentService.
Definition at line 206 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus().
deleteById()
void com.gmp.training.service.impl.DepartmentServiceImpl.deleteById (Long id)
根据ID删除部门
Parameters
id 部门ID
Implements com.gmp.training.service.DepartmentService.
Definition at line 35 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
existsByCode() [1/2]
boolean com.gmp.training.service.impl.DepartmentServiceImpl.existsByCode (String code)
检查部门编码是否已存在（新增操作）
Parameters
code 部门编码
Returns
是否已存在
Implements com.gmp.training.service.DepartmentService.
Definition at line 170 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.existsByCode().
existsByCode() [2/2]
boolean com.gmp.training.service.impl.DepartmentServiceImpl.existsByCode (String code, Long excludeId)
检查部门编码是否已存在
Parameters
code 部门编码
excludeId 排除的部门ID（用于更新操作）
Returns
是否已存在
Implements com.gmp.training.service.DepartmentService.
Definition at line 139 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.existsByCode().
existsByName() [1/2]
boolean com.gmp.training.service.impl.DepartmentServiceImpl.existsByName (String name)
检查部门名称是否已存在（新增操作）
Parameters
name 部门名称
Returns
是否已存在
Implements com.gmp.training.service.DepartmentService.
Definition at line 165 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.existsByName().
existsByName() [2/2]
boolean com.gmp.training.service.impl.DepartmentServiceImpl.existsByName (String name, Long excludeId)
检查部门名称是否已存在
Parameters
name 部门名称
excludeId 排除的部门ID（用于更新操作）
Returns
是否已存在
Implements com.gmp.training.service.DepartmentService.
Definition at line 131 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.existsByName().
findActiveDepartments() [1/2]
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findActiveDepartments ()
查询所有启用的部门
Returns
启用的部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 60 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findActiveDepartments() [2/2]
Page< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findActiveDepartments (Pageable pageable)
查询所有启用的部门（分页）
Parameters
pageable 分页参数
Returns
启用的部门分页结果
Implements com.gmp.training.service.DepartmentService.
Definition at line 65 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findAll() [1/2]
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findAll ()
查询所有部门
Returns
部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 45 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findAll() [2/2]
Page< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findAll (Pageable pageable)
分页查询部门
Parameters
pageable 分页参数
Returns
部门分页结果
Implements com.gmp.training.service.DepartmentService.
Definition at line 50 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findAncestorsById()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findAncestorsById (Long id)
根据部门ID查询所有祖先部门
Parameters
id 部门ID
Returns
祖先部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 75 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findByCode()
Optional< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findByCode (String code)
根据部门编码查询部门
Parameters
code 部门编码
Returns
部门实体
Implements com.gmp.training.service.DepartmentService.
Definition at line 160 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findByGmpRelated() [1/2]
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findByGmpRelated (boolean gmpRelated)
根据GMP关联状态查询部门
Parameters
gmpRelated 是否GMP关联
Returns
部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 109 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findByGmpRelated() [2/2]
Page< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findByGmpRelated (boolean gmpRelated, Pageable pageable)
根据GMP关联状态查询部门（分页）
Parameters
gmpRelated 是否GMP关联
pageable 分页参数
Returns
部门分页结果
Implements com.gmp.training.service.DepartmentService.
Definition at line 120 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findById()
Optional< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findById (Long id)
根据ID查询部门
Parameters
id 部门ID
Returns
部门实体
Implements com.gmp.training.service.DepartmentService.
Definition at line 40 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.updateParent(), and com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus().
findByManagerId()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findByManagerId (Long managerId)
根据部门负责人查询部门
Parameters
managerId 部门负责人ID
Returns
部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 155 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findByNameContaining()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findByNameContaining (String name)
根据名称模糊查询部门
Parameters
name 部门名称
Returns
部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 55 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findChildrenByParentId()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findChildrenByParentId (Long parentId)
根据上级部门ID查询子部门
Parameters
parentId 上级部门ID
Returns
子部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 70 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
findDescendantsById()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsById (Long id)
根据部门ID查询所有后代部门
Parameters
id 部门ID
Returns
后代部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 88 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsRecursive().
findDescendantsRecursive()
void com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsRecursive (Long parentId, List< Department > descendants) private
Definition at line 94 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsRecursive().
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsById(), and com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsRecursive().
findRootDepartments()
List< Department > com.gmp.training.service.impl.DepartmentServiceImpl.findRootDepartments ()
查询根部门（无上级部门的部门）
Returns
根部门列表
Implements com.gmp.training.service.DepartmentService.
Definition at line 104 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
save()
Department com.gmp.training.service.impl.DepartmentServiceImpl.save (Department department)
保存部门
Parameters
department 部门实体
Returns
保存后的部门实体
Implements com.gmp.training.service.DepartmentService.
Definition at line 30 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
updateParent()
Department com.gmp.training.service.impl.DepartmentServiceImpl.updateParent (Long id, Long parentId)
更新部门父级
Parameters
id 部门ID
parentId 父部门ID
Returns
更新后的部门
Implements com.gmp.training.service.DepartmentService.
Definition at line 192 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.training.service.impl.DepartmentServiceImpl.findById().
updateStatus() [1/2]
Department com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus (Long id, Boolean active)
更新部门状态
Parameters
id 部门ID
active 是否激活
Returns
更新后的部门
Implements com.gmp.training.service.DepartmentService.
Definition at line 175 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.training.service.impl.DepartmentServiceImpl.findById().
updateStatus() [2/2]
void com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus (Long id, Department.Status status)
更新部门状态
Parameters
id 部门ID
status 部门状态
Implements com.gmp.training.service.DepartmentService.
Definition at line 147 of file DepartmentServiceImpl.java.
References com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository.
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.batchDisable().
Member Data Documentation
departmentRepository
final DepartmentRepository com.gmp.training.service.impl.DepartmentServiceImpl.departmentRepository private
Definition at line 27 of file DepartmentServiceImpl.java.
Referenced by com.gmp.training.service.impl.DepartmentServiceImpl.deleteById(), com.gmp.training.service.impl.DepartmentServiceImpl.existsByCode(), com.gmp.training.service.impl.DepartmentServiceImpl.existsByName(), com.gmp.training.service.impl.DepartmentServiceImpl.findActiveDepartments(), com.gmp.training.service.impl.DepartmentServiceImpl.findActiveDepartments(), com.gmp.training.service.impl.DepartmentServiceImpl.findAll(), com.gmp.training.service.impl.DepartmentServiceImpl.findAll(), com.gmp.training.service.impl.DepartmentServiceImpl.findAncestorsById(), com.gmp.training.service.impl.DepartmentServiceImpl.findByCode(), com.gmp.training.service.impl.DepartmentServiceImpl.findByGmpRelated(), com.gmp.training.service.impl.DepartmentServiceImpl.findByGmpRelated(), com.gmp.training.service.impl.DepartmentServiceImpl.findById(), com.gmp.training.service.impl.DepartmentServiceImpl.findByManagerId(), com.gmp.training.service.impl.DepartmentServiceImpl.findByNameContaining(), com.gmp.training.service.impl.DepartmentServiceImpl.findChildrenByParentId(), com.gmp.training.service.impl.DepartmentServiceImpl.findDescendantsRecursive(), com.gmp.training.service.impl.DepartmentServiceImpl.findRootDepartments(), com.gmp.training.service.impl.DepartmentServiceImpl.save(), com.gmp.training.service.impl.DepartmentServiceImpl.updateParent(), com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus(), and com.gmp.training.service.impl.DepartmentServiceImpl.updateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/DepartmentServiceImpl.java