GMP系统: com.gmp.edms.service.impl.DocumentCategoryServiceImpl Class Reference
com.gmp.edms.service.impl.DocumentCategoryServiceImpl Class Reference
文档分类服务实现
Public Member Functions
DocumentCategoryDTO createCategory (DocumentCategoryCreateDTO categoryCreateDTO)
创建分类
DocumentCategoryDTO updateCategory (Long id, DocumentCategoryUpdateDTO categoryUpdateDTO)
更新分类
void deleteCategory (Long id)
删除分类
void batchDeleteCategories (List< Long > ids)
批量删除分类
DocumentCategoryDTO getCategoryById (Long id)
根据ID获取分类
DocumentCategoryDTO getCategoryByCode (String categoryCode)
根据编码获取分类
PageResponseDTO< DocumentCategoryDTO > queryCategories (PageRequestDTO pageRequest, String keyword)
分页查询分类
List< DocumentCategoryDTO > getRootCategories ()
获取根分类列表
List< DocumentCategoryDTO > getChildCategories (Long parentId)
获取子分类列表
List< DocumentCategoryDTO > getCategoryTree ()
获取分类树
void updateParentCategory (Long id, Long parentId)
更新父分类
void updateCategoryStatus (Long id, String status)
更新分类状态
boolean checkCategoryCodeExists (String categoryCode, Long excludeId)
检查分类编码是否存在
List< DocumentCategoryDTO > getCategoriesByLevel (Integer level)
根据层级获取分类
List< DocumentCategoryDTO > getAllCategories ()
获取所有分类
List< DocumentCategoryDTO > getCategoryPath (Long categoryId)
获取分类路径
void batchUpdateCategoryStatus (List< Long > ids, String status)
批量更新分类状态
Private Member Functions
void updateParent (DocumentCategory category, Long parentId)
更新父分类
boolean checkCircularReference (Long categoryId, Long parentId)
检查是否存在循环引用
void updateChildCategoryPaths (Long parentId, String parentPath)
更新子分类的路径
Object getFieldValue (Object obj, String fieldName)
使用反射安全获取字段值
void setFieldValue (Object obj, String fieldName, Object value)
使用反射安全设置字段值
java.lang.reflect.Field findField (Class<?> clazz, String fieldName)
递归查找字段，包括父类
Private Attributes
DocumentCategoryRepository documentCategoryRepository
ModelMapper modelMapper
Detailed Description
文档分类服务实现
Definition at line 31 of file DocumentCategoryServiceImpl.java.
Member Function Documentation
batchDeleteCategories()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchDeleteCategories (List< Long > ids)
批量删除分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 157 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testBatchDeleteCategories().
batchUpdateCategoryStatus()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchUpdateCategoryStatus (List< Long > ids, String status)
批量更新分类状态
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 412 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategoryStatus().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testBatchUpdateCategoryStatus().
checkCategoryCodeExists()
boolean com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCategoryCodeExists (String categoryCode, Long excludeId)
检查分类编码是否存在
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 336 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testCheckCategoryCodeExists().
checkCircularReference()
boolean com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCircularReference (Long categoryId, Long parentId) private
检查是否存在循环引用
Definition at line 457 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent().
createCategory()
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory (DocumentCategoryCreateDTO categoryCreateDTO)
创建分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 42 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testCreateCategory().
deleteCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.deleteCategory (Long id)
删除分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 140 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testDeleteCategory().
findField()
java.lang.reflect.Field com.gmp.edms.service.impl.DocumentCategoryServiceImpl.findField (Class<?> clazz, String fieldName) private
递归查找字段，包括父类
Definition at line 542 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.findField(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue().
getAllCategories()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getAllCategories ()
获取所有分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 356 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
getCategoriesByLevel()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoriesByLevel (Integer level)
根据层级获取分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 345 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
getCategoryByCode()
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryByCode (String categoryCode)
根据编码获取分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 186 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryByCode().
getCategoryById()
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById (Long id)
根据ID获取分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 164 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryById().
getCategoryPath()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryPath (Long categoryId)
获取分类路径
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 367 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryPath().
getCategoryTree()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree ()
获取分类树
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 254 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetCategoryTree().
getChildCategories()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getChildCategories (Long parentId)
获取子分类列表
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 243 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetChildCategories().
getFieldValue()
Object com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue (Object obj, String fieldName) private
使用反射安全获取字段值
Definition at line 511 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCircularReference(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryPath(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.queryCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory().
getRootCategories()
List< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getRootCategories ()
获取根分类列表
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 232 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testGetRootCategories().
queryCategories()
PageResponseDTO< DocumentCategoryDTO > com.gmp.edms.service.impl.DocumentCategoryServiceImpl.queryCategories (PageRequestDTO pageRequest, String keyword)
分页查询分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 196 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper.
setFieldValue()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue (Object obj, String fieldName, Object value) private
使用反射安全设置字段值
Definition at line 527 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategoryStatus(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent().
updateCategory()
DocumentCategoryDTO com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory (Long id, DocumentCategoryUpdateDTO categoryUpdateDTO)
更新分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 95 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateCategory().
updateCategoryStatus()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategoryStatus (Long id, String status)
更新分类状态
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 320 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchUpdateCategoryStatus(), and com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateCategoryStatus().
updateChildCategoryPaths()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths (Long parentId, String parentPath) private
更新子分类的路径
Definition at line 491 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory().
updateParent()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent (DocumentCategory category, Long parentId) private
更新父分类
Definition at line 422 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCircularReference(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory().
updateParentCategory()
void com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory (Long id, Long parentId)
更新父分类
Implements com.gmp.edms.service.DocumentCategoryService.
Definition at line 303 of file DocumentCategoryServiceImpl.java.
References com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository, com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent().
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImplTest.testUpdateParentCategory().
Member Data Documentation
documentCategoryRepository
DocumentCategoryRepository com.gmp.edms.service.impl.DocumentCategoryServiceImpl.documentCategoryRepository private
Definition at line 34 of file DocumentCategoryServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.batchDeleteCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCategoryCodeExists(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.checkCircularReference(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.deleteCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getAllCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoriesByLevel(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryByCode(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryPath(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getChildCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getRootCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.queryCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategoryStatus(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateChildCategoryPaths(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParent(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateParentCategory().
modelMapper
ModelMapper com.gmp.edms.service.impl.DocumentCategoryServiceImpl.modelMapper private
Definition at line 37 of file DocumentCategoryServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentCategoryServiceImpl.createCategory(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getAllCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoriesByLevel(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryByCode(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryById(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryPath(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getCategoryTree(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getChildCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.getRootCategories(), com.gmp.edms.service.impl.DocumentCategoryServiceImpl.queryCategories(), and com.gmp.edms.service.impl.DocumentCategoryServiceImpl.updateCategory().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/DocumentCategoryServiceImpl.java