GMP系统: com.gmp.edms.entity.DocumentVersion Class Reference
com.gmp.edms.entity.DocumentVersion Class Reference
文档版本实体类 对应数据库中的document_versions表
Public Member Functions
String getFormattedFileSize ()
String getFullFileName ()
Long getDocumentId ()
获取关联文档ID
void setDocumentId (Long documentId)
设置文档ID
void setComments (String comments)
设置备注信息
String getCreatedBy ()
void setCreatedBy (String createdBy)
LocalDateTime getCreatedTime ()
void setCreatedTime (LocalDateTime createdTime)
Private Member Functions
Object getFieldValue (Object obj, String fieldName)
使用反射获取对象字段值
void setFieldValue (Object obj, String fieldName, Object value)
使用反射设置对象字段值
java.lang.reflect.Field findField (Class<?> clazz, String fieldName)
查找字段，包括父类中的字段
Private Attributes
Long id
Document document
String versionNumber
String versionType = "REVISION"
String changeReason
String changeSummary
String author
String reviewer
String approver
LocalDateTime approvalDate
String filePath
String fileName
String fileType
Long fileSize
String checksum
String comments
Boolean isCurrent = false
LocalDateTime createdAt
String createdBy
LocalDateTime createdTime
Detailed Description
文档版本实体类 对应数据库中的document_versions表
Definition at line 16 of file DocumentVersion.java.
Member Function Documentation
findField()
java.lang.reflect.Field com.gmp.edms.entity.DocumentVersion.findField (Class<?> clazz, String fieldName) private
查找字段，包括父类中的字段
Definition at line 186 of file DocumentVersion.java.
getCreatedBy()
String com.gmp.edms.entity.DocumentVersion.getCreatedBy ()
Definition at line 205 of file DocumentVersion.java.
Referenced by com.gmp.edms.entity.DocumentVersionTest.testVersionBasicProperties().
getCreatedTime()
LocalDateTime com.gmp.edms.entity.DocumentVersion.getCreatedTime ()
Definition at line 213 of file DocumentVersion.java.
getDocumentId()
Long com.gmp.edms.entity.DocumentVersion.getDocumentId ()
获取关联文档ID
Definition at line 115 of file DocumentVersion.java.
getFieldValue()
Object com.gmp.edms.entity.DocumentVersion.getFieldValue (Object obj, String fieldName) private
使用反射获取对象字段值
Definition at line 136 of file DocumentVersion.java.
getFormattedFileSize()
String com.gmp.edms.entity.DocumentVersion.getFormattedFileSize ()
Definition at line 82 of file DocumentVersion.java.
getFullFileName()
String com.gmp.edms.entity.DocumentVersion.getFullFileName ()
Definition at line 101 of file DocumentVersion.java.
Referenced by com.gmp.edms.entity.DocumentVersionTest.testGetFullFileName(), com.gmp.edms.entity.DocumentVersionTest.testGetFullFileNameWithNullFileName(), and com.gmp.edms.entity.DocumentVersionTest.testGetFullFileNameWithNullVersionNumber().
setComments()
void com.gmp.edms.entity.DocumentVersion.setComments (String comments)
设置备注信息
Definition at line 201 of file DocumentVersion.java.
setCreatedBy()
void com.gmp.edms.entity.DocumentVersion.setCreatedBy (String createdBy)
Definition at line 209 of file DocumentVersion.java.
Referenced by com.gmp.edms.entity.DocumentVersionTest.setUp().
setCreatedTime()
void com.gmp.edms.entity.DocumentVersion.setCreatedTime (LocalDateTime createdTime)
Definition at line 217 of file DocumentVersion.java.
setDocumentId()
void com.gmp.edms.entity.DocumentVersion.setDocumentId (Long documentId)
设置文档ID
Definition at line 125 of file DocumentVersion.java.
setFieldValue()
void com.gmp.edms.entity.DocumentVersion.setFieldValue (Object obj, String fieldName, Object value) private
使用反射设置对象字段值
Definition at line 166 of file DocumentVersion.java.
Member Data Documentation
approvalDate
LocalDateTime com.gmp.edms.entity.DocumentVersion.approvalDate private
Definition at line 49 of file DocumentVersion.java.
approver
String com.gmp.edms.entity.DocumentVersion.approver private
Definition at line 46 of file DocumentVersion.java.
author
String com.gmp.edms.entity.DocumentVersion.author private
Definition at line 40 of file DocumentVersion.java.
changeReason
String com.gmp.edms.entity.DocumentVersion.changeReason private
Definition at line 34 of file DocumentVersion.java.
changeSummary
String com.gmp.edms.entity.DocumentVersion.changeSummary private
Definition at line 37 of file DocumentVersion.java.
checksum
String com.gmp.edms.entity.DocumentVersion.checksum private
Definition at line 64 of file DocumentVersion.java.
comments
String com.gmp.edms.entity.DocumentVersion.comments private
Definition at line 67 of file DocumentVersion.java.
createdAt
LocalDateTime com.gmp.edms.entity.DocumentVersion.createdAt private
Definition at line 74 of file DocumentVersion.java.
createdBy
String com.gmp.edms.entity.DocumentVersion.createdBy private
Definition at line 76 of file DocumentVersion.java.
createdTime
LocalDateTime com.gmp.edms.entity.DocumentVersion.createdTime private
Definition at line 78 of file DocumentVersion.java.
document
Document com.gmp.edms.entity.DocumentVersion.document private
Definition at line 25 of file DocumentVersion.java.
fileName
String com.gmp.edms.entity.DocumentVersion.fileName private
Definition at line 55 of file DocumentVersion.java.
filePath
String com.gmp.edms.entity.DocumentVersion.filePath private
Definition at line 52 of file DocumentVersion.java.
fileSize
Long com.gmp.edms.entity.DocumentVersion.fileSize private
Definition at line 61 of file DocumentVersion.java.
fileType
String com.gmp.edms.entity.DocumentVersion.fileType private
Definition at line 58 of file DocumentVersion.java.
id
Long com.gmp.edms.entity.DocumentVersion.id private
Definition at line 20 of file DocumentVersion.java.
isCurrent
Boolean com.gmp.edms.entity.DocumentVersion.isCurrent = false private
Definition at line 70 of file DocumentVersion.java.
reviewer
String com.gmp.edms.entity.DocumentVersion.reviewer private
Definition at line 43 of file DocumentVersion.java.
versionNumber
String com.gmp.edms.entity.DocumentVersion.versionNumber private
Definition at line 28 of file DocumentVersion.java.
versionType
String com.gmp.edms.entity.DocumentVersion.versionType = "REVISION" private
Definition at line 31 of file DocumentVersion.java.
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/entity/DocumentVersion.java