GMP系统: com.gmp.equipment.entity.Equipment Class Reference
com.gmp.equipment.entity.Equipment Class Reference
GMP设备台账实体
Classes
enum EquipmentStatus
设备状态枚举（生命周期状态）
enum OperationalStatus
运行状态枚举（当前运行状态）
Public Member Functions
boolean isRunnable ()
判断设备是否可以运行
boolean isMaintenanceDue ()
判断设备是否需要维护
boolean isCalibrationOverdue ()
判断设备校准是否过期
boolean isUnderWarranty ()
判断设备是否处于质保期内
BigDecimal getUsageYears ()
获取设备使用年限
void prePersist ()
实体创建前的钩子方法，设置创建时间和更新时间
void preUpdate ()
实体更新前的钩子方法，更新最后修改时间
Private Attributes
Long id
主键ID
String equipmentCode
String equipmentName
String equipmentType
String description
设备描述
String manufacturer
String model
设备型号
String serialNumber
设备序列号
String powerRating
String voltage
BigDecimal weightKg
String dimensions
String location
放置位置
String workshop
String area
EquipmentStatus equipmentStatus = EquipmentStatus.INACTIVE
OperationalStatus operationalStatus = OperationalStatus.STOPPED
BigDecimal purchaseCost
LocalDateTime purchaseDate
String currency
LocalDateTime warrantyExpiry
BigDecimal depreciationYears
LocalDateTime installationDate
LocalDateTime commissioningDate
LocalDateTime lastMaintenanceDate
LocalDateTime nextMaintenanceDate
LocalDateTime lastCalibrationDate
LocalDateTime nextCalibrationDate
Boolean criticalEquipment = false
String riskLevel
String usageRequirements
String sensorId
Boolean monitoringEnabled = false
LocalDateTime createdAt
LocalDateTime updatedAt
Long createdBy
Long updatedBy
Integer version = 1
版本号，用于乐观锁
String code
设备编码，唯一标识
String name
设备名称
EquipmentType equipmentType
设备类型ID
EquipmentStatus status
设备状态
String responsiblePerson
负责人
String supplier
供应商
Date purchaseDate
购买日期
Date acceptanceDate
验收日期
Date commissioningDate
启用日期
Date nextCalibrationDate
下次校准日期
Date nextMaintenanceDate
下次维护日期
Boolean enabled = true
是否启用
String createdBy
创建人
Date createdTime
创建时间
String updatedBy
更新人
Date updatedTime
更新时间
Detailed Description
GMP设备台账实体
设备实体类 表示设备的基本信息和状态
管理制药生产设备的完整生命周期，包括：
设备基本信息和技术参数
采购、安装、验收记录
运行状态和使用监控
维护计划和历史记录
校准验证和合格状态
财务成本和折旧信息
Definition at line 59 of file Equipment.java.
Member Function Documentation
getUsageYears()
BigDecimal com.gmp.equipment.entity.Equipment.getUsageYears ()
获取设备使用年限
Definition at line 322 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testGetUsageYears().
isCalibrationOverdue()
boolean com.gmp.equipment.entity.Equipment.isCalibrationOverdue ()
判断设备校准是否过期
Definition at line 300 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsCalibrationOverdue().
isMaintenanceDue()
boolean com.gmp.equipment.entity.Equipment.isMaintenanceDue ()
判断设备是否需要维护
Definition at line 278 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsMaintenanceDue().
isRunnable()
boolean com.gmp.equipment.entity.Equipment.isRunnable ()
判断设备是否可以运行
Definition at line 268 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), and com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
isUnderWarranty()
boolean com.gmp.equipment.entity.Equipment.isUnderWarranty ()
判断设备是否处于质保期内
Definition at line 311 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsUnderWarranty().
prePersist()
void com.gmp.equipment.entity.Equipment.prePersist ()
实体创建前的钩子方法，设置创建时间和更新时间
Definition at line 162 of file Equipment.java.
preUpdate()
void com.gmp.equipment.entity.Equipment.preUpdate ()
实体更新前的钩子方法，更新最后修改时间
Definition at line 172 of file Equipment.java.
Member Data Documentation
acceptanceDate
Date com.gmp.equipment.entity.Equipment.acceptanceDate private
验收日期
Definition at line 91 of file Equipment.java.
area
String com.gmp.equipment.entity.Equipment.area private
Definition at line 130 of file Equipment.java.
code
String com.gmp.equipment.entity.Equipment.code private
设备编码，唯一标识
Definition at line 27 of file Equipment.java.
commissioningDate [1/2]
LocalDateTime com.gmp.equipment.entity.Equipment.commissioningDate private
Definition at line 167 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testGetUsageYears().
commissioningDate [2/2]
Date com.gmp.equipment.entity.Equipment.commissioningDate private
启用日期
Definition at line 98 of file Equipment.java.
createdAt
LocalDateTime com.gmp.equipment.entity.Equipment.createdAt private
Definition at line 204 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testAuditFields().
createdBy [1/2]
Long com.gmp.equipment.entity.Equipment.createdBy private
Definition at line 211 of file Equipment.java.
createdBy [2/2]
String com.gmp.equipment.entity.Equipment.createdBy private
创建人
Definition at line 130 of file Equipment.java.
createdTime
Date com.gmp.equipment.entity.Equipment.createdTime private
创建时间
Definition at line 137 of file Equipment.java.
criticalEquipment
Boolean com.gmp.equipment.entity.Equipment.criticalEquipment = false private
Definition at line 183 of file Equipment.java.
currency
String com.gmp.equipment.entity.Equipment.currency private
Definition at line 152 of file Equipment.java.
depreciationYears
BigDecimal com.gmp.equipment.entity.Equipment.depreciationYears private
Definition at line 160 of file Equipment.java.
description
String com.gmp.equipment.entity.Equipment.description private
设备描述
Definition at line 84 of file Equipment.java.
dimensions
String com.gmp.equipment.entity.Equipment.dimensions private
Definition at line 116 of file Equipment.java.
enabled
Boolean com.gmp.equipment.entity.Equipment.enabled = true private
是否启用
Definition at line 124 of file Equipment.java.
equipmentCode
String com.gmp.equipment.entity.Equipment.equipmentCode private
Definition at line 70 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentCreation(), and com.gmp.equipment.entity.EquipmentTest.testEquipmentValidation().
equipmentName
String com.gmp.equipment.entity.Equipment.equipmentName private
Definition at line 75 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testCriticalEquipmentManagement().
equipmentStatus
EquipmentStatus com.gmp.equipment.entity.Equipment.equipmentStatus = EquipmentStatus.INACTIVE private
Definition at line 135 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), and com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
equipmentType [1/2]
String com.gmp.equipment.entity.Equipment.equipmentType private
Definition at line 80 of file Equipment.java.
equipmentType [2/2]
EquipmentType com.gmp.equipment.entity.Equipment.equipmentType private
设备类型ID
Definition at line 52 of file Equipment.java.
id
Long com.gmp.equipment.entity.Equipment.id private
主键ID
Definition at line 63 of file Equipment.java.
installationDate
LocalDateTime com.gmp.equipment.entity.Equipment.installationDate private
Definition at line 164 of file Equipment.java.
lastCalibrationDate
LocalDateTime com.gmp.equipment.entity.Equipment.lastCalibrationDate private
Definition at line 176 of file Equipment.java.
lastMaintenanceDate
LocalDateTime com.gmp.equipment.entity.Equipment.lastMaintenanceDate private
Definition at line 170 of file Equipment.java.
location
String com.gmp.equipment.entity.Equipment.location private
放置位置
Definition at line 122 of file Equipment.java.
manufacturer
String com.gmp.equipment.entity.Equipment.manufacturer private
Definition at line 90 of file Equipment.java.
model
String com.gmp.equipment.entity.Equipment.model private
设备型号
Definition at line 94 of file Equipment.java.
monitoringEnabled
Boolean com.gmp.equipment.entity.Equipment.monitoringEnabled = false private
Definition at line 199 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentMonitoring().
name
String com.gmp.equipment.entity.Equipment.name private
设备名称
Definition at line 33 of file Equipment.java.
nextCalibrationDate [1/2]
LocalDateTime com.gmp.equipment.entity.Equipment.nextCalibrationDate private
Definition at line 179 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsCalibrationOverdue().
nextCalibrationDate [2/2]
Date com.gmp.equipment.entity.Equipment.nextCalibrationDate private
下次校准日期
Definition at line 105 of file Equipment.java.
nextMaintenanceDate [1/2]
LocalDateTime com.gmp.equipment.entity.Equipment.nextMaintenanceDate private
Definition at line 173 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsMaintenanceDue().
nextMaintenanceDate [2/2]
Date com.gmp.equipment.entity.Equipment.nextMaintenanceDate private
下次维护日期
Definition at line 112 of file Equipment.java.
operationalStatus
OperationalStatus com.gmp.equipment.entity.Equipment.operationalStatus = OperationalStatus.STOPPED private
Definition at line 139 of file Equipment.java.
powerRating
String com.gmp.equipment.entity.Equipment.powerRating private
Definition at line 103 of file Equipment.java.
purchaseCost
BigDecimal com.gmp.equipment.entity.Equipment.purchaseCost private
Definition at line 145 of file Equipment.java.
purchaseDate [1/2]
LocalDateTime com.gmp.equipment.entity.Equipment.purchaseDate private
Definition at line 148 of file Equipment.java.
purchaseDate [2/2]
Date com.gmp.equipment.entity.Equipment.purchaseDate private
购买日期
Definition at line 84 of file Equipment.java.
responsiblePerson
String com.gmp.equipment.entity.Equipment.responsiblePerson private
负责人
Definition at line 71 of file Equipment.java.
riskLevel
String com.gmp.equipment.entity.Equipment.riskLevel private
Definition at line 187 of file Equipment.java.
sensorId
String com.gmp.equipment.entity.Equipment.sensorId private
Definition at line 196 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentMonitoring().
serialNumber
String com.gmp.equipment.entity.Equipment.serialNumber private
设备序列号
Definition at line 98 of file Equipment.java.
status
EquipmentStatus com.gmp.equipment.entity.Equipment.status private
设备状态
Definition at line 59 of file Equipment.java.
supplier
String com.gmp.equipment.entity.Equipment.supplier private
供应商
Definition at line 77 of file Equipment.java.
updatedAt
LocalDateTime com.gmp.equipment.entity.Equipment.updatedAt private
Definition at line 208 of file Equipment.java.
updatedBy [1/2]
Long com.gmp.equipment.entity.Equipment.updatedBy private
Definition at line 214 of file Equipment.java.
updatedBy [2/2]
String com.gmp.equipment.entity.Equipment.updatedBy private
更新人
Definition at line 143 of file Equipment.java.
updatedTime
Date com.gmp.equipment.entity.Equipment.updatedTime private
更新时间
Definition at line 150 of file Equipment.java.
usageRequirements
String com.gmp.equipment.entity.Equipment.usageRequirements private
Definition at line 191 of file Equipment.java.
version
Integer com.gmp.equipment.entity.Equipment.version = 1 private
版本号，用于乐观锁
Definition at line 219 of file Equipment.java.
voltage
String com.gmp.equipment.entity.Equipment.voltage private
Definition at line 107 of file Equipment.java.
warrantyExpiry
LocalDateTime com.gmp.equipment.entity.Equipment.warrantyExpiry private
Definition at line 155 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsUnderWarranty().
weightKg
BigDecimal com.gmp.equipment.entity.Equipment.weightKg private
Definition at line 112 of file Equipment.java.
workshop
String com.gmp.equipment.entity.Equipment.workshop private
Definition at line 126 of file Equipment.java.
The documentation for this class was generated from the following files:
equipment-management/src/main/java/com/gmp/equipment/entity/Equipment.java
equipment-service/src/main/java/com/gmp/equipment/entity/Equipment.java