GMP系统: com.gmp.equipment.controller.EquipmentTypeController Class Reference
com.gmp.equipment.controller.EquipmentTypeController Class Reference
设备类型控制器 提供设备类型相关的RESTful API接口
Public Member Functions
ResponseEntity< ResponseResult< EquipmentTypeDTO > > getById (@PathVariable Long id)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > getByCode (@PathVariable String code)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > getByName (@PathVariable String name)
ResponseEntity< ResponseResult< PageResultDTO< EquipmentTypeDTO > > > listPage (@RequestParam(required=false) String keyword, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
ResponseEntity< ResponseResult< List< EquipmentTypeDTO > > > listAll ()
ResponseEntity< ResponseResult< List< EquipmentTypeDTO > > > listEnabled ()
ResponseEntity< ResponseResult< Boolean > > checkCode (@RequestParam String code, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< Boolean > > checkName (@RequestParam String name, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > create (@RequestBody EquipmentTypeDTO equipmentTypeDTO)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > update (@PathVariable Long id, @RequestBody EquipmentTypeDTO equipmentTypeDTO)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > enable (@PathVariable Long id)
ResponseEntity< ResponseResult< EquipmentTypeDTO > > disable (@PathVariable Long id)
ResponseEntity< ResponseResult< Boolean > > delete (@PathVariable Long id)
ResponseEntity< ResponseResult< Boolean > > deleteBatch (@RequestBody List< Long > ids)
Private Attributes
EquipmentTypeService equipmentTypeService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(EquipmentTypeController.class)
Detailed Description
设备类型控制器 提供设备类型相关的RESTful API接口
Definition at line 26 of file EquipmentTypeController.java.
Member Function Documentation
checkCode()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentTypeController.checkCode (@RequestParam String code, @RequestParam(required=false) Long id)
Definition at line 125 of file EquipmentTypeController.java.
checkName()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentTypeController.checkName (@RequestParam String name, @RequestParam(required=false) Long id)
Definition at line 138 of file EquipmentTypeController.java.
create()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.create (@RequestBody EquipmentTypeDTO equipmentTypeDTO)
Definition at line 151 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.create_success().
delete()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentTypeController.delete (@PathVariable Long id)
Definition at line 215 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.delete_success().
deleteBatch()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.EquipmentTypeController.deleteBatch (@RequestBody List< Long > ids)
Definition at line 231 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.deleteBatch_success().
disable()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.disable (@PathVariable Long id)
Definition at line 199 of file EquipmentTypeController.java.
enable()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.enable (@PathVariable Long id)
Definition at line 183 of file EquipmentTypeController.java.
getByCode()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.getByCode (@PathVariable String code)
Definition at line 51 of file EquipmentTypeController.java.
getById()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.getById (@PathVariable Long id)
Definition at line 35 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_notFound(), and com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_success().
getByName()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.getByName (@PathVariable String name)
Definition at line 67 of file EquipmentTypeController.java.
listAll()
ResponseEntity< ResponseResult< List< EquipmentTypeDTO > > > com.gmp.equipment.controller.EquipmentTypeController.listAll ()
Definition at line 99 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.listAll_success().
listEnabled()
ResponseEntity< ResponseResult< List< EquipmentTypeDTO > > > com.gmp.equipment.controller.EquipmentTypeController.listEnabled ()
Definition at line 112 of file EquipmentTypeController.java.
listPage()
ResponseEntity< ResponseResult< PageResultDTO< EquipmentTypeDTO > > > com.gmp.equipment.controller.EquipmentTypeController.listPage (@RequestParam(required=false) String keyword, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
Definition at line 83 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.listPage_success().
update()
ResponseEntity< ResponseResult< EquipmentTypeDTO > > com.gmp.equipment.controller.EquipmentTypeController.update (@PathVariable Long id, @RequestBody EquipmentTypeDTO equipmentTypeDTO)
Definition at line 167 of file EquipmentTypeController.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.update_success().
Member Data Documentation
equipmentTypeService
EquipmentTypeService com.gmp.equipment.controller.EquipmentTypeController.equipmentTypeService private
Definition at line 31 of file EquipmentTypeController.java.
logger
final Logger com.gmp.equipment.controller.EquipmentTypeController.logger = LoggerFactory.getLogger(EquipmentTypeController.class) static private
Definition at line 28 of file EquipmentTypeController.java.
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/controller/EquipmentTypeController.java