GMP系统: com.gmp.auth.service.PasswordPolicyService Class Reference
com.gmp.auth.service.PasswordPolicyService Class Reference
密码策略服务 负责密码复杂度验证、历史记录检查和密码过期管理
Public Member Functions
String validatePasswordComplexity (String password)
验证密码复杂度
boolean isPasswordInHistory (Long userId, String rawPassword)
检查密码是否在历史记录中
LocalDateTime calculatePasswordExpiryTime ()
计算密码过期时间
boolean isPasswordExpiringSoon (LocalDateTime passwordExpiredAt)
检查密码是否即将过期（提前7天提醒）
void recordPasswordHistory (Long userId, String hashedPassword)
记录新密码到历史记录
boolean validatePassword (String password)
验证密码是否符合策略要求
String getPasswordComplexityRequirements ()
获取密码复杂度要求描述
String getPasswordRequirementsDescription ()
获取密码要求描述
Private Attributes
PasswordEncoder passwordEncoder
UserPasswordHistoryService userPasswordHistoryService
int minPasswordLength
int passwordExpiryDays
int passwordHistoryCount
Static Private Attributes
static final int MIN_PASSWORD_LENGTH = 8
static final Logger log = LoggerFactory.getLogger(PasswordPolicyService.class)
static final Pattern HAS_DIGIT = Pattern.compile("\\d")
static final Pattern HAS_LOWERCASE = Pattern.compile("[a-z]")
static final Pattern HAS_UPPERCASE = Pattern.compile("[A-Z]")
static final Pattern HAS_SPECIAL = Pattern.compile("[!@#$%^&*(),.?\":{}|<>]")
Detailed Description
密码策略服务 负责密码复杂度验证、历史记录检查和密码过期管理
Definition at line 19 of file PasswordPolicyService.java.
Member Function Documentation
calculatePasswordExpiryTime()
LocalDateTime com.gmp.auth.service.PasswordPolicyService.calculatePasswordExpiryTime ()
计算密码过期时间
Returns
密码过期时间
Definition at line 104 of file PasswordPolicyService.java.
References com.gmp.auth.service.PasswordPolicyService.passwordExpiryDays.
getPasswordComplexityRequirements()
String com.gmp.auth.service.PasswordPolicyService.getPasswordComplexityRequirements ()
获取密码复杂度要求描述
Returns
复杂度要求描述
Definition at line 145 of file PasswordPolicyService.java.
References com.gmp.auth.service.PasswordPolicyService.MIN_PASSWORD_LENGTH.
getPasswordRequirementsDescription()
String com.gmp.auth.service.PasswordPolicyService.getPasswordRequirementsDescription ()
获取密码要求描述
Returns
密码要求描述字符串
Definition at line 161 of file PasswordPolicyService.java.
References com.gmp.auth.service.PasswordPolicyService.MIN_PASSWORD_LENGTH.
isPasswordExpiringSoon()
boolean com.gmp.auth.service.PasswordPolicyService.isPasswordExpiringSoon (LocalDateTime passwordExpiredAt)
检查密码是否即将过期（提前7天提醒）
Parameters
passwordExpiredAt 密码过期时间
Returns
是否即将过期
Definition at line 113 of file PasswordPolicyService.java.
isPasswordInHistory()
boolean com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory (Long userId, String rawPassword)
检查密码是否在历史记录中
Parameters
userId 用户ID
rawPassword 原始密码
Returns
检查结果，true表示密码在历史记录中，false表示不在
Definition at line 88 of file PasswordPolicyService.java.
References com.gmp.auth.service.UserPasswordHistoryService.getPasswordHistory(), com.gmp.auth.service.PasswordPolicyService.log, com.gmp.auth.service.PasswordPolicyService.passwordEncoder, com.gmp.auth.service.PasswordPolicyService.passwordHistoryCount, and com.gmp.auth.service.PasswordPolicyService.userPasswordHistoryService.
recordPasswordHistory()
void com.gmp.auth.service.PasswordPolicyService.recordPasswordHistory (Long userId, String hashedPassword)
记录新密码到历史记录
Parameters
userId 用户ID
hashedPassword 哈希后的密码
Definition at line 126 of file PasswordPolicyService.java.
References com.gmp.auth.service.UserPasswordHistoryService.recordPasswordHistory(), and com.gmp.auth.service.PasswordPolicyService.userPasswordHistoryService.
validatePassword()
boolean com.gmp.auth.service.PasswordPolicyService.validatePassword (String password)
验证密码是否符合策略要求
Parameters
password 密码
Returns
是否符合要求
Definition at line 135 of file PasswordPolicyService.java.
References com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success().
validatePasswordComplexity()
String com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity (String password)
验证密码复杂度
Parameters
password 待验证的密码
Returns
验证结果，null表示验证通过，否则返回错误消息
Definition at line 58 of file PasswordPolicyService.java.
References com.gmp.auth.service.PasswordPolicyService.HAS_DIGIT, com.gmp.auth.service.PasswordPolicyService.HAS_LOWERCASE, com.gmp.auth.service.PasswordPolicyService.HAS_SPECIAL, com.gmp.auth.service.PasswordPolicyService.HAS_UPPERCASE, and com.gmp.auth.service.PasswordPolicyService.minPasswordLength.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePassword().
Member Data Documentation
HAS_DIGIT
final Pattern com.gmp.auth.service.PasswordPolicyService.HAS_DIGIT = Pattern.compile("\\d") static private
Definition at line 45 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
HAS_LOWERCASE
final Pattern com.gmp.auth.service.PasswordPolicyService.HAS_LOWERCASE = Pattern.compile("[a-z]") static private
Definition at line 47 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
HAS_SPECIAL
final Pattern com.gmp.auth.service.PasswordPolicyService.HAS_SPECIAL = Pattern.compile("[!@#$%^&*(),.?\":{}|<>]") static private
Definition at line 51 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
HAS_UPPERCASE
final Pattern com.gmp.auth.service.PasswordPolicyService.HAS_UPPERCASE = Pattern.compile("[A-Z]") static private
Definition at line 49 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
log
final Logger com.gmp.auth.service.PasswordPolicyService.log = LoggerFactory.getLogger(PasswordPolicyService.class) static private
Definition at line 24 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory().
MIN_PASSWORD_LENGTH
final int com.gmp.auth.service.PasswordPolicyService.MIN_PASSWORD_LENGTH = 8 static private
Definition at line 22 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.getPasswordComplexityRequirements(), and com.gmp.auth.service.PasswordPolicyService.getPasswordRequirementsDescription().
minPasswordLength
int com.gmp.auth.service.PasswordPolicyService.minPasswordLength private
Definition at line 34 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.validatePasswordComplexity().
passwordEncoder
PasswordEncoder com.gmp.auth.service.PasswordPolicyService.passwordEncoder private
Definition at line 27 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory().
passwordExpiryDays
int com.gmp.auth.service.PasswordPolicyService.passwordExpiryDays private
Definition at line 38 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.calculatePasswordExpiryTime().
passwordHistoryCount
int com.gmp.auth.service.PasswordPolicyService.passwordHistoryCount private
Definition at line 42 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory().
userPasswordHistoryService
UserPasswordHistoryService com.gmp.auth.service.PasswordPolicyService.userPasswordHistoryService private
Definition at line 30 of file PasswordPolicyService.java.
Referenced by com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory(), and com.gmp.auth.service.PasswordPolicyService.recordPasswordHistory().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/PasswordPolicyService.java