GMP系统: com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl Class Reference
com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl Class Reference
审批工作流服务实现类 实现设计文档中的工作流引擎核心功能
Public Member Functions
ApprovalInstanceDTO startApprovalProcess (Document document, String workflowCode, String initiator)
启动审批流程
boolean executeApprovalStep (Long instanceId, String userId, String decision, String comments)
执行审批决策
ApprovalInstanceDTO getApprovalInstance (Long instanceId)
获取审批实例详情
List< ApprovalInstanceDTO > getPendingTasks (String userId)
获取用户的待办审批任务
List< ApprovalInstanceDTO > getDocumentApprovalHistory (Long documentId)
获取文档的审批历史
ApprovalWorkflowDTO createWorkflow (ApprovalWorkflowDTO workflowDTO)
创建审批工作流模板
List< ApprovalWorkflowDTO > getAllWorkflows ()
获取所有可用的工作流模板
List< ApprovalWorkflowDTO > getWorkflowsByDocumentType (String documentType)
根据文档类型获取适用的工作流
boolean withdrawApproval (Long instanceId, String userId, String reason)
撤回审批流程
boolean transferApproval (Long instanceId, String fromUserId, String toUserId, String reason)
转办审批任务
ApprovalStepDTO getCurrentStep (Long instanceId)
获取审批进度
boolean urgeApproval (Long instanceId, String userId)
催办审批任务
void calculateNextStep (ApprovalInstance instance)
Private Member Functions
String getFirstStepName (JsonNode workflowDef)
boolean validateApproverPermission (ApprovalInstance instance, String userId)
void recordApprovalDecision (ApprovalInstance instance, String userId, String decision, String comments)
String calculateNextStep (JsonNode workflowDef, String currentStep, String decision)
String getManager (String userId)
String getFinalApprover ()
void assignNextStep (ApprovalInstance instance, JsonNode workflowDef, String nextStep)
void finalizeApprovalProcess (ApprovalInstance instance, String decision)
void notifyApprovers (ApprovalInstance instance, JsonNode workflowDef)
Field findField (Class<?> clazz, String fieldName)
Object getFieldValue (Object obj, String fieldName)
void setFieldValue (Object obj, String fieldName, Object value)
Private Attributes
ApprovalWorkflowRepository workflowRepository
ApprovalInstanceRepository instanceRepository
DocumentRepository documentRepository
ModelMapper modelMapper
ObjectMapper objectMapper
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(ApprovalWorkflowServiceImpl.class)
Detailed Description
审批工作流服务实现类 实现设计文档中的工作流引擎核心功能
Definition at line 33 of file ApprovalWorkflowServiceImpl.java.
Member Function Documentation
assignNextStep()
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.assignNextStep (ApprovalInstance instance, JsonNode workflowDef, String nextStep) private
Definition at line 332 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep().
calculateNextStep() [1/2]
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep (ApprovalInstance instance)
Definition at line 305 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFinalApprover(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getManager(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
calculateNextStep() [2/2]
String com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep (JsonNode workflowDef, String currentStep, String decision) private
Definition at line 285 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep().
createWorkflow()
ApprovalWorkflowDTO com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.createWorkflow (ApprovalWorkflowDTO workflowDTO)
创建审批工作流模板
Parameters
workflowDTO 工作流DTO
Returns
创建的工作流
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 162 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.workflowRepository.
executeApprovalStep()
boolean com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep (Long instanceId, String userId, String decision, String comments)
执行审批决策
Parameters
instanceId 审批实例ID
userId 用户ID
decision 审批决策
comments 审批意见
Returns
执行结果
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 85 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.assignNextStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.notifyApprovers(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.objectMapper, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.recordApprovalDecision(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.validateApproverPermission().
finalizeApprovalProcess()
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess (ApprovalInstance instance, String decision) private
Definition at line 337 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.documentRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep().
findField()
Field com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.findField (Class<?> clazz, String fieldName) private
Definition at line 356 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.findField(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
getAllWorkflows()
List< ApprovalWorkflowDTO > com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getAllWorkflows ()
获取所有可用的工作流模板
Returns
工作流列表
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 172 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.workflowRepository.
getApprovalInstance()
ApprovalInstanceDTO com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getApprovalInstance (Long instanceId)
获取审批实例详情
Parameters
instanceId 实例ID
Returns
审批实例
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 126 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper.
getCurrentStep()
ApprovalStepDTO com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getCurrentStep (Long instanceId)
获取审批进度
Parameters
instanceId 实例ID
Returns
当前步骤和进度信息
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 232 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
getDocumentApprovalHistory()
List< ApprovalInstanceDTO > com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getDocumentApprovalHistory (Long documentId)
获取文档的审批历史
Parameters
documentId 文档ID
Returns
审批历史
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 145 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper.
getFieldValue()
Object com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue (Object obj, String fieldName) private
Definition at line 368 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.findField(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getCurrentStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getDocumentApprovalHistory(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getPendingTasks(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.transferApproval(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.validateApproverPermission(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.withdrawApproval().
getFinalApprover()
String com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFinalApprover () private
Definition at line 327 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep().
getFirstStepName()
String com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFirstStepName (JsonNode workflowDef) private
Definition at line 263 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess().
getManager()
String com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getManager (String userId) private
Definition at line 322 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep().
getPendingTasks()
List< ApprovalInstanceDTO > com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getPendingTasks (String userId)
获取用户的待办审批任务
Parameters
userId 用户ID
Returns
待办任务列表
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 133 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper.
getWorkflowsByDocumentType()
List< ApprovalWorkflowDTO > com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getWorkflowsByDocumentType (String documentType)
根据文档类型获取适用的工作流
Parameters
documentType 文档类型
Returns
工作流列表
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 180 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.workflowRepository.
notifyApprovers()
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.notifyApprovers (ApprovalInstance instance, JsonNode workflowDef) private
Definition at line 351 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval().
recordApprovalDecision()
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.recordApprovalDecision (ApprovalInstance instance, String userId, String decision, String comments) private
Definition at line 277 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep().
setFieldValue()
void com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue (Object obj, String fieldName, Object value) private
Definition at line 379 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.findField(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.createWorkflow(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getCurrentStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.recordApprovalDecision(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.transferApproval(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.withdrawApproval().
startApprovalProcess()
ApprovalInstanceDTO com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess (Document document, String workflowCode, String initiator)
启动审批流程
Parameters
document 文档
workflowCode 工作流编码
initiator 发起人
Returns
审批实例
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 52 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFirstStepName(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.objectMapper, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.workflowRepository.
transferApproval()
boolean com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.transferApproval (Long instanceId, String fromUserId, String toUserId, String reason)
转办审批任务
Parameters
instanceId 实例ID
fromUserId 原审批人
toUserId 新审批人
reason 转办原因
Returns
转办结果
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 211 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
urgeApproval()
boolean com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval (Long instanceId, String userId)
催办审批任务
Parameters
instanceId 实例ID
userId 催办人
Returns
催办结果
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 244 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.notifyApprovers(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.objectMapper.
validateApproverPermission()
boolean com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.validateApproverPermission (ApprovalInstance instance, String userId) private
Definition at line 271 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep().
withdrawApproval()
boolean com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.withdrawApproval (Long instanceId, String userId, String reason)
撤回审批流程
Parameters
instanceId 实例ID
userId 用户ID
reason 撤回原因
Returns
撤回结果
Implements com.gmp.edms.service.ApprovalWorkflowService.
Definition at line 188 of file ApprovalWorkflowServiceImpl.java.
References com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository, com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log, and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue().
Member Data Documentation
documentRepository
DocumentRepository com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.documentRepository private
Definition at line 43 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess().
instanceRepository
ApprovalInstanceRepository com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.instanceRepository private
Definition at line 40 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.calculateNextStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.finalizeApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getApprovalInstance(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getCurrentStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getDocumentApprovalHistory(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getPendingTasks(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.transferApproval(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.withdrawApproval().
log
final Logger com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.log = LoggerFactory.getLogger(ApprovalWorkflowServiceImpl.class) static private
Definition at line 34 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.setFieldValue(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.transferApproval(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.withdrawApproval().
modelMapper
ModelMapper com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.modelMapper private
Definition at line 46 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.createWorkflow(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getAllWorkflows(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getApprovalInstance(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getDocumentApprovalHistory(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getPendingTasks(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getWorkflowsByDocumentType(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess().
objectMapper
ObjectMapper com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.objectMapper private
Definition at line 49 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.executeApprovalStep(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.urgeApproval().
workflowRepository
ApprovalWorkflowRepository com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.workflowRepository private
Definition at line 37 of file ApprovalWorkflowServiceImpl.java.
Referenced by com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.createWorkflow(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getAllWorkflows(), com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.getWorkflowsByDocumentType(), and com.gmp.edms.service.impl.ApprovalWorkflowServiceImpl.startApprovalProcess().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/ApprovalWorkflowServiceImpl.java