GMP系统: com.gmp.qms.client.ErpClientFallback Class Reference
com.gmp.qms.client.ErpClientFallback Class Reference
ERP系统客户端降级实现，当ERP服务不可用时提供备用功能
Public Member Functions
SupplierDTO getSupplier (String supplierId)
MaterialDTO getMaterial (String materialCode)
void sendNotification (NotificationDTO notificationDTO)
boolean isSupplierQualified (String supplierId)
MaterialDTO getMaterialBatch (String materialCode, String batchNumber)
SupplierDTO getSupplier (@PathVariable("supplierId") String supplierId)
获取供应商信息
MaterialDTO getMaterial (@PathVariable("materialCode") String materialCode)
获取物料信息
void sendNotification (@RequestBody NotificationDTO notificationDTO)
发送通知到ERP系统
boolean isSupplierQualified (@PathVariable("supplierId") String supplierId)
检查供应商是否合格
MaterialDTO getMaterialBatch (@PathVariable("materialCode") String materialCode, @PathVariable("batchNumber") String batchNumber)
获取物料批次信息
Package Functions
private< T > void saveToRetryQueue (String queueType, T data)
保存请求到重试队列，后续可进行重试
Private Member Functions
void recordFallbackRequest (String methodName, String params)
记录降级请求信息，用于监控和分析
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(ErpClientFallback.class)
Detailed Description
ERP系统客户端降级实现，当ERP服务不可用时提供备用功能
Author
GMP系统开发团队
Definition at line 16 of file ErpClientFallback.java.
Member Function Documentation
getMaterial() [1/2]
MaterialDTO com.gmp.qms.client.ErpClient.getMaterial (@PathVariable("materialCode") String materialCode) inherited
获取物料信息
Parameters
materialCode 物料代码
Returns
物料信息
getMaterial() [2/2]
MaterialDTO com.gmp.qms.client.ErpClientFallback.getMaterial (String materialCode)
Definition at line 32 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log, and com.gmp.qms.client.ErpClientFallback.recordFallbackRequest().
getMaterialBatch() [1/2]
MaterialDTO com.gmp.qms.client.ErpClient.getMaterialBatch (@PathVariable("materialCode") String materialCode, @PathVariable("batchNumber") String batchNumber) inherited
获取物料批次信息
Parameters
materialCode 物料代码
batchNumber 批次号
Returns
物料信息（包含批次信息）
getMaterialBatch() [2/2]
MaterialDTO com.gmp.qms.client.ErpClientFallback.getMaterialBatch (String materialCode, String batchNumber)
Definition at line 59 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log, and com.gmp.qms.client.ErpClientFallback.recordFallbackRequest().
getSupplier() [1/2]
SupplierDTO com.gmp.qms.client.ErpClient.getSupplier (@PathVariable("supplierId") String supplierId) inherited
获取供应商信息
Parameters
supplierId 供应商ID
Returns
供应商信息
getSupplier() [2/2]
SupplierDTO com.gmp.qms.client.ErpClientFallback.getSupplier (String supplierId)
Definition at line 21 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log, and com.gmp.qms.client.ErpClientFallback.recordFallbackRequest().
isSupplierQualified() [1/2]
boolean com.gmp.qms.client.ErpClient.isSupplierQualified (@PathVariable("supplierId") String supplierId) inherited
检查供应商是否合格
Parameters
supplierId 供应商ID
Returns
供应商是否合格
isSupplierQualified() [2/2]
boolean com.gmp.qms.client.ErpClientFallback.isSupplierQualified (String supplierId)
Definition at line 51 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log, and com.gmp.qms.client.ErpClientFallback.recordFallbackRequest().
recordFallbackRequest()
void com.gmp.qms.client.ErpClientFallback.recordFallbackRequest (String methodName, String params) private
记录降级请求信息，用于监控和分析
Definition at line 73 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log.
Referenced by com.gmp.qms.client.ErpClientFallback.getMaterial(), com.gmp.qms.client.ErpClientFallback.getMaterialBatch(), com.gmp.qms.client.ErpClientFallback.getSupplier(), com.gmp.qms.client.ErpClientFallback.isSupplierQualified(), and com.gmp.qms.client.ErpClientFallback.sendNotification().
saveToRetryQueue()
private< T > void com.gmp.qms.client.ErpClientFallback.saveToRetryQueue (String queueType, T data) package
保存请求到重试队列，后续可进行重试
Definition at line 81 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log.
Referenced by com.gmp.qms.client.ErpClientFallback.sendNotification().
sendNotification() [1/2]
void com.gmp.qms.client.ErpClient.sendNotification (@RequestBody NotificationDTO notificationDTO) inherited
发送通知到ERP系统
Parameters
notificationDTO 通知信息
sendNotification() [2/2]
void com.gmp.qms.client.ErpClientFallback.sendNotification (NotificationDTO notificationDTO)
Definition at line 43 of file ErpClientFallback.java.
References com.gmp.qms.client.ErpClientFallback.log, com.gmp.qms.client.ErpClientFallback.recordFallbackRequest(), and com.gmp.qms.client.ErpClientFallback.saveToRetryQueue().
Member Data Documentation
log
final Logger com.gmp.qms.client.ErpClientFallback.log = LoggerFactory.getLogger(ErpClientFallback.class) static private
Definition at line 18 of file ErpClientFallback.java.
Referenced by com.gmp.qms.client.ErpClientFallback.getMaterial(), com.gmp.qms.client.ErpClientFallback.getMaterialBatch(), com.gmp.qms.client.ErpClientFallback.getSupplier(), com.gmp.qms.client.ErpClientFallback.isSupplierQualified(), com.gmp.qms.client.ErpClientFallback.recordFallbackRequest(), com.gmp.qms.client.ErpClientFallback.saveToRetryQueue(), and com.gmp.qms.client.ErpClientFallback.sendNotification().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/client/ErpClientFallback.java