GMP系统: com.gmp.training.service.impl.TrainingAssessmentServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingAssessmentServiceImplTest Class Reference
培训考核服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByCourseId ()
void testFindByUserId ()
void testFindByStatus ()
void testFindByAssessmentType ()
void testFindByDateRange ()
void testFindNotStarted ()
void testFindInProgress ()
void testFindCompleted ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testGetCourseAverageScore ()
void testFindPassedAssessments ()
void testSearch ()
void testStartAssessment ()
void testSubmitAssessment ()
Private Attributes
TrainingAssessmentRepository trainingAssessmentRepository
TrainingAssessmentServiceImpl trainingAssessmentService
TrainingAssessment trainingAssessment
Detailed Description
培训考核服务实现的单元测试
Definition at line 27 of file TrainingAssessmentServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.setUp () package
Definition at line 38 of file TrainingAssessmentServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testBatchUpdateStatus () package
Definition at line 243 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.batchUpdateStatus().
testDelete()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testDelete () package
Definition at line 92 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindAll () package
Definition at line 77 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findAll().
testFindByAssessmentType()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByAssessmentType () package
Definition at line 146 of file TrainingAssessmentServiceImplTest.java.
testFindByCourseId()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByCourseId () package
Definition at line 101 of file TrainingAssessmentServiceImplTest.java.
testFindByDateRange()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByDateRange () package
Definition at line 163 of file TrainingAssessmentServiceImplTest.java.
testFindById()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindById () package
Definition at line 66 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findById().
testFindByStatus()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByStatus () package
Definition at line 131 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByStatus().
testFindByUserId()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByUserId () package
Definition at line 116 of file TrainingAssessmentServiceImplTest.java.
testFindCompleted()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindCompleted () package
Definition at line 214 of file TrainingAssessmentServiceImplTest.java.
testFindInProgress()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindInProgress () package
Definition at line 198 of file TrainingAssessmentServiceImplTest.java.
testFindNotStarted()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindNotStarted () package
Definition at line 182 of file TrainingAssessmentServiceImplTest.java.
testFindPassedAssessments()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindPassedAssessments () package
Definition at line 264 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findPassedAssessments().
testGetCourseAverageScore()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testGetCourseAverageScore () package
Definition at line 254 of file TrainingAssessmentServiceImplTest.java.
testSave()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testSave () package
Definition at line 55 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testSearch () package
Definition at line 280 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.search().
testStartAssessment()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testStartAssessment () package
Definition at line 294 of file TrainingAssessmentServiceImplTest.java.
testSubmitAssessment()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testSubmitAssessment () package
Definition at line 307 of file TrainingAssessmentServiceImplTest.java.
testUpdateStatus()
void com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testUpdateStatus () package
Definition at line 230 of file TrainingAssessmentServiceImplTest.java.
References com.gmp.training.service.impl.TrainingAssessmentServiceImpl.updateStatus().
Member Data Documentation
trainingAssessment
TrainingAssessment com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.trainingAssessment private
Definition at line 35 of file TrainingAssessmentServiceImplTest.java.
trainingAssessmentRepository
TrainingAssessmentRepository com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.trainingAssessmentRepository private
Definition at line 30 of file TrainingAssessmentServiceImplTest.java.
trainingAssessmentService
TrainingAssessmentServiceImpl com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.trainingAssessmentService private
Definition at line 33 of file TrainingAssessmentServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingAssessmentServiceImplTest.java