GMP系统: com.gmp.equipment.service.impl.MaintenancePlanServiceImpl Class Reference
com.gmp.equipment.service.impl.MaintenancePlanServiceImpl Class Reference
设备维护计划服务实现类 实现维护计划相关的业务逻辑
Public Member Functions
MaintenancePlanDTO getById (Long id)
根据ID查询维护计划
MaintenancePlanDTO getByPlanNumber (String planNumber)
根据计划编号查询维护计划
PageResultDTO< MaintenancePlanDTO > listPage (Long equipmentId, Integer pageNum, Integer pageSize)
分页查询维护计划
List< MaintenancePlanDTO > listByEquipmentId (Long equipmentId)
根据设备ID查询维护计划列表
List< MaintenancePlanDTO > listByDateRange (Date startDate, Date endDate)
根据计划日期范围查询维护计划
List< MaintenancePlanDTO > listByStatus (String status)
根据计划状态查询维护计划
MaintenancePlanDTO getLatestByEquipmentId (Long equipmentId)
查询设备的最新维护计划
MaintenancePlanDTO create (MaintenancePlanDTO maintenancePlanDTO)
新增维护计划
MaintenancePlanDTO update (Long id, MaintenancePlanDTO maintenancePlanDTO)
更新维护计划
void delete (Long id)
删除维护计划
void deleteBatch (List< Long > ids)
批量删除维护计划
void updateStatus (Long id, String status)
更新维护计划状态
boolean existsByPlanNumber (String planNumber, Long id)
检查计划编号是否存在
Private Member Functions
MaintenancePlanDTO convertToDTO (MaintenancePlan maintenancePlan)
将实体类转换为DTO
PageResultDTO< MaintenancePlanDTO > convertToPageResultDTO (Page< MaintenancePlan > page)
将分页实体转换为分页DTO
Private Attributes
MaintenancePlanRepository maintenancePlanRepository
Detailed Description
设备维护计划服务实现类 实现维护计划相关的业务逻辑
Definition at line 25 of file MaintenancePlanServiceImpl.java.
Member Function Documentation
convertToDTO()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO (MaintenancePlan maintenancePlan) private
将实体类转换为DTO
Parameters
maintenancePlan 维护计划实体
Returns
维护计划DTO
Definition at line 165 of file MaintenancePlanServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.create(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getById(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getByPlanNumber(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getLatestByEquipmentId(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.update().
convertToPageResultDTO()
PageResultDTO< MaintenancePlanDTO > com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToPageResultDTO (Page< MaintenancePlan > page) private
将分页实体转换为分页DTO
Parameters
page 分页实体
Returns
分页DTO
Definition at line 176 of file MaintenancePlanServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listPage().
create()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.create (MaintenancePlanDTO maintenancePlanDTO)
新增维护计划
Parameters
maintenancePlanDTO 维护计划DTO
Returns
新增后的维护计划DTO
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 89 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.existsByPlanNumber(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
delete()
void com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.delete (Long id)
删除维护计划
Parameters
id 维护计划ID
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 125 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
deleteBatch()
void com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.deleteBatch (List< Long > ids)
批量删除维护计划
Parameters
ids 维护计划ID列表
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 133 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
existsByPlanNumber()
boolean com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.existsByPlanNumber (String planNumber, Long id)
检查计划编号是否存在
Parameters
planNumber 计划编号
id 排除的ID，用于更新时检查
Returns
是否存在
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 152 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
Referenced by com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.create(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.update().
getById()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getById (Long id)
根据ID查询维护计划
Parameters
id 维护计划ID
Returns
维护计划DTO
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 31 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
getByPlanNumber()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getByPlanNumber (String planNumber)
根据计划编号查询维护计划
Parameters
planNumber 计划编号
Returns
维护计划DTO
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 38 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
getLatestByEquipmentId()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getLatestByEquipmentId (Long equipmentId)
查询设备的最新维护计划
Parameters
equipmentId 设备ID
Returns
维护计划DTO
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 81 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
listByDateRange()
List< MaintenancePlanDTO > com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByDateRange (Date startDate, Date endDate)
根据计划日期范围查询维护计划
Parameters
startDate 开始日期
endDate 结束日期
Returns
维护计划DTO列表
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 69 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
listByEquipmentId()
List< MaintenancePlanDTO > com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByEquipmentId (Long equipmentId)
根据设备ID查询维护计划列表
Parameters
equipmentId 设备ID
Returns
维护计划DTO列表
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 63 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
listByStatus()
List< MaintenancePlanDTO > com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByStatus (String status)
根据计划状态查询维护计划
Parameters
status 计划状态
Returns
维护计划DTO列表
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 75 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
listPage()
PageResultDTO< MaintenancePlanDTO > com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listPage (Long equipmentId, Integer pageNum, Integer pageSize)
分页查询维护计划
Parameters
equipmentId 设备ID
pageNum 页码
pageSize 每页大小
Returns
维护计划分页结果
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 45 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToPageResultDTO(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
update()
MaintenancePlanDTO com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.update (Long id, MaintenancePlanDTO maintenancePlanDTO)
更新维护计划
Parameters
id 维护计划ID
maintenancePlanDTO 维护计划DTO
Returns
更新后的维护计划DTO
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 106 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.convertToDTO(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.existsByPlanNumber(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
updateStatus()
void com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.updateStatus (Long id, String status)
更新维护计划状态
Parameters
id 维护计划ID
status 新状态
Implements com.gmp.equipment.service.MaintenancePlanService.
Definition at line 143 of file MaintenancePlanServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository.
Member Data Documentation
maintenancePlanRepository
MaintenancePlanRepository com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.maintenancePlanRepository private
Definition at line 28 of file MaintenancePlanServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.create(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.delete(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.deleteBatch(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.existsByPlanNumber(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getById(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getByPlanNumber(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.getLatestByEquipmentId(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByDateRange(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByEquipmentId(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listByStatus(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.listPage(), com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.update(), and com.gmp.equipment.service.impl.MaintenancePlanServiceImpl.updateStatus().
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/service/impl/MaintenancePlanServiceImpl.java