GMP系统: com.gmp.auth.dto.ApiResponseTest Class Reference
com.gmp.auth.dto.ApiResponseTest Class Reference
ApiResponse DTO单元测试
Package Functions
void testSuccessApiResponse ()
void testSuccessApiResponseWithMessage ()
void testSuccessApiResponseEmpty ()
void testErrorApiResponseWithCode ()
void testErrorApiResponseDefaultCode ()
void testCustomApiResponse ()
void testApiResponseFullConstructor ()
void testApiResponseWithDifferentDataTypes ()
void testErrorApiResponseWithDifferentCodes ()
void testDefaultConstructorAndSetters ()
Detailed Description
ApiResponse DTO单元测试
Author
GMP系统开发团队
Definition at line 19 of file ApiResponseTest.java.
Member Function Documentation
testApiResponseFullConstructor()
void com.gmp.auth.dto.ApiResponseTest.testApiResponseFullConstructor () package
Definition at line 122 of file ApiResponseTest.java.
testApiResponseWithDifferentDataTypes()
void com.gmp.auth.dto.ApiResponseTest.testApiResponseWithDifferentDataTypes () package
Definition at line 142 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.success.
testCustomApiResponse()
void com.gmp.auth.dto.ApiResponseTest.testCustomApiResponse () package
Definition at line 101 of file ApiResponseTest.java.
testDefaultConstructorAndSetters()
void com.gmp.auth.dto.ApiResponseTest.testDefaultConstructorAndSetters () package
Definition at line 182 of file ApiResponseTest.java.
testErrorApiResponseDefaultCode()
void com.gmp.auth.dto.ApiResponseTest.testErrorApiResponseDefaultCode () package
Definition at line 85 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.error().
testErrorApiResponseWithCode()
void com.gmp.auth.dto.ApiResponseTest.testErrorApiResponseWithCode () package
Definition at line 68 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.error().
testErrorApiResponseWithDifferentCodes()
void com.gmp.auth.dto.ApiResponseTest.testErrorApiResponseWithDifferentCodes () package
Definition at line 166 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.error().
testSuccessApiResponse()
void com.gmp.auth.dto.ApiResponseTest.testSuccessApiResponse () package
Definition at line 22 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.success.
testSuccessApiResponseEmpty()
void com.gmp.auth.dto.ApiResponseTest.testSuccessApiResponseEmpty () package
Definition at line 55 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.success.
testSuccessApiResponseWithMessage()
void com.gmp.auth.dto.ApiResponseTest.testSuccessApiResponseWithMessage () package
Definition at line 38 of file ApiResponseTest.java.
References com.gmp.auth.dto.ApiResponse< T >.success.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/dto/ApiResponseTest.java