GMP系统: com.gmp.auth.interceptor.SubsystemAccessInterceptor Class Reference
com.gmp.auth.interceptor.SubsystemAccessInterceptor Class Reference
子系统访问权限控制拦截器 用于拦截API请求，验证用户对子系统的访问权限
Public Member Functions
boolean preHandle (HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception
Private Member Functions
boolean shouldExclude (String requestUri)
检查路径是否应该被排除在拦截之外
String extractTokenFromHeader (HttpServletRequest request)
从请求头中提取令牌
String determineSubsystemCode (String requestUri)
根据请求路径确定对应的子系统代码
boolean isWriteOperation (String method)
判断是否为写入操作
void sendErrorResponse (HttpServletResponse response, String errorCode, String errorMessage) throws IOException
发送错误响应
Private Attributes
JwtConfig jwtConfig
AuthService authService
ObjectMapper objectMapper
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(SubsystemAccessInterceptor.class)
static final Set< String > EXCLUDED_PATHS
static final Set< String > SUBSYSTEM_PATHS
Detailed Description
子系统访问权限控制拦截器 用于拦截API请求，验证用户对子系统的访问权限
Author
GMP系统开发团队
Definition at line 28 of file SubsystemAccessInterceptor.java.
Member Function Documentation
determineSubsystemCode()
String com.gmp.auth.interceptor.SubsystemAccessInterceptor.determineSubsystemCode (String requestUri) private
根据请求路径确定对应的子系统代码
Definition at line 145 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
extractTokenFromHeader()
String com.gmp.auth.interceptor.SubsystemAccessInterceptor.extractTokenFromHeader (HttpServletRequest request) private
从请求头中提取令牌
Definition at line 134 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
isWriteOperation()
boolean com.gmp.auth.interceptor.SubsystemAccessInterceptor.isWriteOperation (String method) private
判断是否为写入操作
Definition at line 166 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
preHandle()
boolean com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle (HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception
Definition at line 58 of file SubsystemAccessInterceptor.java.
References com.gmp.auth.interceptor.SubsystemAccessInterceptor.authService, com.gmp.auth.interceptor.SubsystemAccessInterceptor.determineSubsystemCode(), com.gmp.auth.interceptor.SubsystemAccessInterceptor.extractTokenFromHeader(), com.gmp.auth.interceptor.SubsystemAccessInterceptor.isWriteOperation(), com.gmp.auth.interceptor.SubsystemAccessInterceptor.jwtConfig, com.gmp.auth.interceptor.SubsystemAccessInterceptor.log, com.gmp.auth.interceptor.SubsystemAccessInterceptor.sendErrorResponse(), and com.gmp.auth.interceptor.SubsystemAccessInterceptor.shouldExclude().
sendErrorResponse()
void com.gmp.auth.interceptor.SubsystemAccessInterceptor.sendErrorResponse (HttpServletResponse response, String errorCode, String errorMessage) throws IOException private
发送错误响应
Definition at line 173 of file SubsystemAccessInterceptor.java.
References com.gmp.auth.interceptor.SubsystemAccessInterceptor.objectMapper.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
shouldExclude()
boolean com.gmp.auth.interceptor.SubsystemAccessInterceptor.shouldExclude (String requestUri) private
检查路径是否应该被排除在拦截之外
Definition at line 119 of file SubsystemAccessInterceptor.java.
References com.gmp.auth.interceptor.SubsystemAccessInterceptor.EXCLUDED_PATHS.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
Member Data Documentation
authService
AuthService com.gmp.auth.interceptor.SubsystemAccessInterceptor.authService private
Definition at line 35 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
EXCLUDED_PATHS
final Set<String> com.gmp.auth.interceptor.SubsystemAccessInterceptor.EXCLUDED_PATHS static private
Initial value:
= new HashSet<>(Arrays.asList(
            "/api/auth/login",
            "/api/auth/logout",
            "/api/subsystems/check/",
            "/api/subsystems/accessible/",
            "/api/subsystems/access-levels/"
    ))
Definition at line 41 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.shouldExclude().
jwtConfig
JwtConfig com.gmp.auth.interceptor.SubsystemAccessInterceptor.jwtConfig private
Definition at line 32 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
log
final Logger com.gmp.auth.interceptor.SubsystemAccessInterceptor.log = LoggerFactory.getLogger(SubsystemAccessInterceptor.class) static private
Definition at line 29 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.preHandle().
objectMapper
ObjectMapper com.gmp.auth.interceptor.SubsystemAccessInterceptor.objectMapper private
Definition at line 38 of file SubsystemAccessInterceptor.java.
Referenced by com.gmp.auth.interceptor.SubsystemAccessInterceptor.sendErrorResponse().
SUBSYSTEM_PATHS
final Set<String> com.gmp.auth.interceptor.SubsystemAccessInterceptor.SUBSYSTEM_PATHS static private
Initial value:
= new HashSet<>(Arrays.asList(
            "/api/subsystems/",
            "/api/users/",
            "/api/roles/",
            "/api/permissions/"
    ))
Definition at line 50 of file SubsystemAccessInterceptor.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/interceptor/SubsystemAccessInterceptor.java