GMP系统: com.gmp.qms.service.impl.ChangeControlServiceImplTest Class Reference
com.gmp.qms.service.impl.ChangeControlServiceImplTest Class Reference
ChangeControlServiceImpl单元测试
Package Functions
void setUp ()
void testGetChangeControlById ()
void testGetChangeControlByIdNotFound ()
void testGetChangeControlByCode ()
void testCreateChangeControl ()
void testUpdateChangeControl ()
void testFindAllChangeControls ()
void testSearchChangeControls ()
void testUpdateChangeControlStatus ()
void testGenerateChangeCode ()
void testAddAttachment () throws IOException
void testAddAttachmentNotFound ()
void testRemoveAttachment ()
void testRemoveAttachmentNotFound ()
void testFindOverdueChangeControls ()
Private Attributes
ChangeControlRepository changeControlRepository
ChangeControlServiceImpl changeControlService
ChangeControl changeControl
ChangeControlDTO changeControlDTO
Detailed Description
ChangeControlServiceImpl单元测试
Author
GMP系统开发团队
Definition at line 42 of file ChangeControlServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.setUp () package
Definition at line 54 of file ChangeControlServiceImplTest.java.
testAddAttachment()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testAddAttachment () throws IOException package
Definition at line 189 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.addAttachment().
testAddAttachmentNotFound()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testAddAttachmentNotFound () package
Definition at line 213 of file ChangeControlServiceImplTest.java.
testCreateChangeControl()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testCreateChangeControl () package
Definition at line 112 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.createChangeControl().
testFindAllChangeControls()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testFindAllChangeControls () package
Definition at line 135 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.findAllChangeControls().
testFindOverdueChangeControls()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testFindOverdueChangeControls () package
Definition at line 262 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.findOverdueChangeControls().
testGenerateChangeCode()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testGenerateChangeCode () package
Definition at line 179 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.generateChangeCode().
testGetChangeControlByCode()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testGetChangeControlByCode () package
Definition at line 101 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.getChangeControlByCode().
testGetChangeControlById()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testGetChangeControlById () package
Definition at line 79 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.getChangeControlById().
testGetChangeControlByIdNotFound()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testGetChangeControlByIdNotFound () package
Definition at line 90 of file ChangeControlServiceImplTest.java.
testRemoveAttachment()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testRemoveAttachment () package
Definition at line 228 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.removeAttachment().
testRemoveAttachmentNotFound()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testRemoveAttachmentNotFound () package
Definition at line 249 of file ChangeControlServiceImplTest.java.
testSearchChangeControls()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testSearchChangeControls () package
Definition at line 149 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.searchChangeControls().
testUpdateChangeControl()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testUpdateChangeControl () package
Definition at line 123 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.updateChangeControl().
testUpdateChangeControlStatus()
void com.gmp.qms.service.impl.ChangeControlServiceImplTest.testUpdateChangeControlStatus () package
Definition at line 166 of file ChangeControlServiceImplTest.java.
References com.gmp.qms.service.impl.ChangeControlServiceImpl.updateChangeControlStatus().
Member Data Documentation
changeControl
ChangeControl com.gmp.qms.service.impl.ChangeControlServiceImplTest.changeControl private
Definition at line 50 of file ChangeControlServiceImplTest.java.
changeControlDTO
ChangeControlDTO com.gmp.qms.service.impl.ChangeControlServiceImplTest.changeControlDTO private
Definition at line 51 of file ChangeControlServiceImplTest.java.
changeControlRepository
ChangeControlRepository com.gmp.qms.service.impl.ChangeControlServiceImplTest.changeControlRepository private
Definition at line 45 of file ChangeControlServiceImplTest.java.
changeControlService
ChangeControlServiceImpl com.gmp.qms.service.impl.ChangeControlServiceImplTest.changeControlService private
Definition at line 48 of file ChangeControlServiceImplTest.java.
The documentation for this class was generated from the following file:
qms-service/src/test/java/com/gmp/qms/service/impl/ChangeControlServiceImplTest.java