GMP系统: com.gmp.auth.entity.OperationLogTest Class Reference
com.gmp.auth.entity.OperationLogTest Class Reference
OperationLog实体单元测试
Package Functions
void testOperationLogDefaultConstructor ()
void testOperationLogAllArgsConstructor ()
void testOperationLogBuilder ()
void testOperationLogGettersAndSetters ()
void testOperationLogEnums ()
void testCreateLoginLog ()
void testCreateLoginLogFailure ()
void testCreateLogoutLog ()
void testCreateUserOperationLog ()
void testCreateUserOperationLogFailure ()
Detailed Description
OperationLog实体单元测试
Author
GMP系统开发团队
Definition at line 16 of file OperationLogTest.java.
Member Function Documentation
testCreateLoginLog()
void com.gmp.auth.entity.OperationLogTest.testCreateLoginLog () package
Definition at line 151 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.createLoginLog(), com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getIpAddress(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserAgent(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), and com.gmp.auth.entity.OperationLog.Result.SUCCESS.
testCreateLoginLogFailure()
void com.gmp.auth.entity.OperationLogTest.testCreateLoginLogFailure () package
Definition at line 168 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.createLoginLog(), com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.getAction(), and com.gmp.auth.entity.OperationLog.getResult().
testCreateLogoutLog()
void com.gmp.auth.entity.OperationLogTest.testCreateLogoutLog () package
Definition at line 179 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.createLogoutLog(), com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getIpAddress(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), and com.gmp.auth.entity.OperationLog.Result.SUCCESS.
testCreateUserOperationLog()
void com.gmp.auth.entity.OperationLogTest.testCreateUserOperationLog () package
Definition at line 195 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.createUserOperationLog(), com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), com.gmp.auth.entity.OperationLog.Result.SUCCESS, and com.gmp.auth.entity.OperationLog.OperationType.USER_UPDATE.
testCreateUserOperationLogFailure()
void com.gmp.auth.entity.OperationLogTest.testCreateUserOperationLogFailure () package
Definition at line 210 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.createUserOperationLog(), com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.getResult(), and com.gmp.auth.entity.OperationLog.OperationType.USER_DELETE.
testOperationLogAllArgsConstructor()
void com.gmp.auth.entity.OperationLogTest.testOperationLogAllArgsConstructor () package
Definition at line 36 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getDurationMs(), com.gmp.auth.entity.OperationLog.getId(), com.gmp.auth.entity.OperationLog.getIpAddress(), com.gmp.auth.entity.OperationLog.getMetadata(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getOperationTime(), com.gmp.auth.entity.OperationLog.getRequestData(), com.gmp.auth.entity.OperationLog.getResponseData(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserAgent(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), and com.gmp.auth.entity.OperationLog.Result.SUCCESS.
testOperationLogBuilder()
void com.gmp.auth.entity.OperationLogTest.testOperationLogBuilder () package
Definition at line 62 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.builder(), com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getDurationMs(), com.gmp.auth.entity.OperationLog.getId(), com.gmp.auth.entity.OperationLog.getIpAddress(), com.gmp.auth.entity.OperationLog.getMetadata(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getOperationTime(), com.gmp.auth.entity.OperationLog.getRequestData(), com.gmp.auth.entity.OperationLog.getResponseData(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserAgent(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), com.gmp.auth.entity.OperationLog.Builder.id, and com.gmp.auth.entity.OperationLog.Result.SUCCESS.
testOperationLogDefaultConstructor()
void com.gmp.auth.entity.OperationLogTest.testOperationLogDefaultConstructor () package
Definition at line 19 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getDurationMs(), com.gmp.auth.entity.OperationLog.getId(), com.gmp.auth.entity.OperationLog.getMetadata(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getOperationTime(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), and com.gmp.auth.entity.OperationLog.Result.SUCCESS.
testOperationLogEnums()
void com.gmp.auth.entity.OperationLogTest.testOperationLogEnums () package
Definition at line 136 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.Module.AUTH, com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.OperationType.LOGIN, com.gmp.auth.entity.OperationLog.OperationType.LOGOUT, com.gmp.auth.entity.OperationLog.Module.ROLE, com.gmp.auth.entity.OperationLog.Result.SUCCESS, com.gmp.auth.entity.OperationLog.Module.USER, and com.gmp.auth.entity.OperationLog.OperationType.USER_CREATE.
testOperationLogGettersAndSetters()
void com.gmp.auth.entity.OperationLogTest.testOperationLogGettersAndSetters () package
Definition at line 99 of file OperationLogTest.java.
References com.gmp.auth.entity.OperationLog.Result.FAILED, com.gmp.auth.entity.OperationLog.getAction(), com.gmp.auth.entity.OperationLog.getDurationMs(), com.gmp.auth.entity.OperationLog.getId(), com.gmp.auth.entity.OperationLog.getIpAddress(), com.gmp.auth.entity.OperationLog.getMetadata(), com.gmp.auth.entity.OperationLog.getModule(), com.gmp.auth.entity.OperationLog.getOperation(), com.gmp.auth.entity.OperationLog.getOperationTime(), com.gmp.auth.entity.OperationLog.getRequestData(), com.gmp.auth.entity.OperationLog.getResponseData(), com.gmp.auth.entity.OperationLog.getResult(), com.gmp.auth.entity.OperationLog.getUserAgent(), com.gmp.auth.entity.OperationLog.getUserId(), com.gmp.auth.entity.OperationLog.getUsername(), com.gmp.auth.entity.OperationLog.setAction(), com.gmp.auth.entity.OperationLog.setDurationMs(), com.gmp.auth.entity.OperationLog.setId(), com.gmp.auth.entity.OperationLog.setIpAddress(), com.gmp.auth.entity.OperationLog.setMetadata(), com.gmp.auth.entity.OperationLog.setModule(), com.gmp.auth.entity.OperationLog.setOperation(), com.gmp.auth.entity.OperationLog.setOperationTime(), com.gmp.auth.entity.OperationLog.setRequestData(), com.gmp.auth.entity.OperationLog.setResponseData(), com.gmp.auth.entity.OperationLog.setResult(), com.gmp.auth.entity.OperationLog.setUserAgent(), com.gmp.auth.entity.OperationLog.setUserId(), and com.gmp.auth.entity.OperationLog.setUsername().
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/OperationLogTest.java