GMP系统: com.gmp.edms.service.CommonFileServiceTest Class Reference
com.gmp.edms.service.CommonFileServiceTest Class Reference
通用文件服务测试类
Package Functions
void setUp () throws IOException
void testUploadFile_Success () throws Exception
void testUploadFile_FileAlreadyExists () throws Exception
void testUploadFile_EmptyFile ()
void testUploadFile_EmptyModule ()
void testDownloadFile_Success () throws Exception
void testDownloadFile_FileNotFound ()
void testGetFileInfo_Success () throws Exception
void testDeleteFile_Success () throws Exception
void testBatchDeleteFiles_Success () throws Exception
void testGeneratePresignedUrl_Success () throws Exception
void testQueryFiles_Success ()
void testUpdateFileMetadata_Success () throws Exception
void testGetFileStatistics_Success ()
Private Attributes
CommonFileRepository commonFileRepository
FileStorageService fileStorageService
CommonFileServiceImpl commonFileService
MultipartFile testFile
CommonFile testCommonFile
final String MODULE = "test-module"
Detailed Description
通用文件服务测试类
Definition at line 29 of file CommonFileServiceTest.java.
Member Function Documentation
setUp()
void com.gmp.edms.service.CommonFileServiceTest.setUp () throws IOException package
Definition at line 45 of file CommonFileServiceTest.java.
testBatchDeleteFiles_Success()
void com.gmp.edms.service.CommonFileServiceTest.testBatchDeleteFiles_Success () throws Exception package
Definition at line 191 of file CommonFileServiceTest.java.
testDeleteFile_Success()
void com.gmp.edms.service.CommonFileServiceTest.testDeleteFile_Success () throws Exception package
Definition at line 175 of file CommonFileServiceTest.java.
testDownloadFile_FileNotFound()
void com.gmp.edms.service.CommonFileServiceTest.testDownloadFile_FileNotFound () package
Definition at line 148 of file CommonFileServiceTest.java.
testDownloadFile_Success()
void com.gmp.edms.service.CommonFileServiceTest.testDownloadFile_Success () throws Exception package
Definition at line 133 of file CommonFileServiceTest.java.
References com.gmp.edms.service.FileStorageService.downloadFile().
testGeneratePresignedUrl_Success()
void com.gmp.edms.service.CommonFileServiceTest.testGeneratePresignedUrl_Success () throws Exception package
Definition at line 210 of file CommonFileServiceTest.java.
References com.gmp.edms.service.FileStorageService.generatePresignedUrl().
testGetFileInfo_Success()
void com.gmp.edms.service.CommonFileServiceTest.testGetFileInfo_Success () throws Exception package
Definition at line 161 of file CommonFileServiceTest.java.
testGetFileStatistics_Success()
void com.gmp.edms.service.CommonFileServiceTest.testGetFileStatistics_Success () package
Definition at line 261 of file CommonFileServiceTest.java.
testQueryFiles_Success()
void com.gmp.edms.service.CommonFileServiceTest.testQueryFiles_Success () package
Definition at line 226 of file CommonFileServiceTest.java.
testUpdateFileMetadata_Success()
void com.gmp.edms.service.CommonFileServiceTest.testUpdateFileMetadata_Success () throws Exception package
Definition at line 243 of file CommonFileServiceTest.java.
testUploadFile_EmptyFile()
void com.gmp.edms.service.CommonFileServiceTest.testUploadFile_EmptyFile () package
Definition at line 110 of file CommonFileServiceTest.java.
testUploadFile_EmptyModule()
void com.gmp.edms.service.CommonFileServiceTest.testUploadFile_EmptyModule () package
Definition at line 123 of file CommonFileServiceTest.java.
testUploadFile_FileAlreadyExists()
void com.gmp.edms.service.CommonFileServiceTest.testUploadFile_FileAlreadyExists () throws Exception package
Definition at line 93 of file CommonFileServiceTest.java.
testUploadFile_Success()
void com.gmp.edms.service.CommonFileServiceTest.testUploadFile_Success () throws Exception package
Definition at line 67 of file CommonFileServiceTest.java.
References com.gmp.edms.service.FileStorageService.uploadFile().
Member Data Documentation
commonFileRepository
CommonFileRepository com.gmp.edms.service.CommonFileServiceTest.commonFileRepository private
Definition at line 32 of file CommonFileServiceTest.java.
commonFileService
CommonFileServiceImpl com.gmp.edms.service.CommonFileServiceTest.commonFileService private
Definition at line 38 of file CommonFileServiceTest.java.
fileStorageService
FileStorageService com.gmp.edms.service.CommonFileServiceTest.fileStorageService private
Definition at line 35 of file CommonFileServiceTest.java.
MODULE
final String com.gmp.edms.service.CommonFileServiceTest.MODULE = "test-module" private
Definition at line 42 of file CommonFileServiceTest.java.
testCommonFile
CommonFile com.gmp.edms.service.CommonFileServiceTest.testCommonFile private
Definition at line 41 of file CommonFileServiceTest.java.
testFile
MultipartFile com.gmp.edms.service.CommonFileServiceTest.testFile private
Definition at line 40 of file CommonFileServiceTest.java.
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/CommonFileServiceTest.java