GMP系统: com.gmp.auth.service.TotpUtils Class Reference
com.gmp.auth.service.TotpUtils Class Reference
TOTP工具类，提供基础的基于时间的一次性密码生成和验证功能
Public Member Functions
String generateSecretKey ()
生成随机的TOTP密钥
String generateTotpCode (String secretKey)
生成当前时间的TOTP码
String generateTotpCode (String secretKey, long timestamp)
生成指定时间戳的TOTP码
boolean verifyTotpCode (String secretKey, String code)
验证TOTP码（包含时间容错）
boolean verifyTotpCodeAtTimestamp (String secretKey, String code, long timestamp)
在指定时间戳验证TOTP码
String generateTotpUri (String secretKey, String accountName, String issuer)
生成TOTP二维码的URI（符合Google Authenticator格式）
long getCurrentTimeWindow ()
获取当前时间窗口
int getRemainingSeconds ()
获取剩余有效期（秒）
Private Member Functions
byte[] hmacSha1 (byte[] key, byte[] data) throws Exception
计算HMAC-SHA1哈希值
Static Private Attributes
static final int TOTP_TIME_STEP = 30
static final int TOTP_CODE_LENGTH = 6
static final int SECRET_KEY_LENGTH = 16
static final SecureRandom SECURE_RANDOM = new SecureRandom()
Detailed Description
TOTP工具类，提供基础的基于时间的一次性密码生成和验证功能
Definition at line 14 of file TotpUtils.java.
Member Function Documentation
generateSecretKey()
String com.gmp.auth.service.TotpUtils.generateSecretKey ()
生成随机的TOTP密钥
Returns
Base64编码的密钥
Definition at line 24 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.SECRET_KEY_LENGTH, and com.gmp.auth.service.TotpUtils.SECURE_RANDOM.
Referenced by com.gmp.auth.service.MfaService.generateSecretKey(), com.gmp.auth.service.MfaServiceTest.testGenerateSecretKey(), and com.gmp.auth.service.TotpUtilsTest.testGenerateSecretKey().
generateTotpCode() [1/2]
String com.gmp.auth.service.TotpUtils.generateTotpCode (String secretKey)
生成当前时间的TOTP码
Parameters
secretKey 密钥
Returns
6位TOTP码
Definition at line 35 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode().
Referenced by com.gmp.auth.service.MfaService.generateTotpCode(), com.gmp.auth.service.TotpUtils.generateTotpCode(), com.gmp.auth.service.TotpUtilsTest.testEdgeCaseEmptySecretKey(), com.gmp.auth.service.TotpUtilsTest.testEdgeCaseNullSecretKey(), com.gmp.auth.service.MfaServiceTest.testGenerateTotpCode(), com.gmp.auth.service.TotpUtilsTest.testGenerateTotpCode(), com.gmp.auth.service.TotpUtilsTest.testTimestampCalculation(), com.gmp.auth.service.TotpUtilsTest.testVerifyTotpCodeValid(), and com.gmp.auth.service.TotpUtils.verifyTotpCodeAtTimestamp().
generateTotpCode() [2/2]
String com.gmp.auth.service.TotpUtils.generateTotpCode (String secretKey, long timestamp)
生成指定时间戳的TOTP码
Parameters
secretKey 密钥
timestamp 时间戳（秒）
Returns
6位TOTP码
Definition at line 45 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.hmacSha1(), com.gmp.auth.service.TotpUtils.TOTP_CODE_LENGTH, and com.gmp.auth.service.TotpUtils.TOTP_TIME_STEP.
generateTotpUri()
String com.gmp.auth.service.TotpUtils.generateTotpUri (String secretKey, String accountName, String issuer)
生成TOTP二维码的URI（符合Google Authenticator格式）
Parameters
secretKey 密钥
accountName 账号名
issuer 发行商名称
Returns
二维码URI
Definition at line 117 of file TotpUtils.java.
Referenced by com.gmp.auth.service.MfaService.generateQrCodeUrl(), and com.gmp.auth.service.MfaServiceTest.testGenerateQrCodeUrl().
getCurrentTimeWindow()
long com.gmp.auth.service.TotpUtils.getCurrentTimeWindow ()
获取当前时间窗口
Returns
当前时间窗口索引
Definition at line 142 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.TOTP_TIME_STEP.
getRemainingSeconds()
int com.gmp.auth.service.TotpUtils.getRemainingSeconds ()
获取剩余有效期（秒）
Returns
剩余有效期
Definition at line 150 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.TOTP_TIME_STEP.
Referenced by com.gmp.auth.service.MfaService.getRemainingSeconds(), com.gmp.auth.service.MfaServiceTest.testGetRemainingSeconds(), and com.gmp.auth.service.TotpUtilsTest.testGetRemainingSeconds().
hmacSha1()
byte[] com.gmp.auth.service.TotpUtils.hmacSha1 (byte[] key, byte[] data) throws Exception private
计算HMAC-SHA1哈希值
Parameters
key 密钥
data 数据
Returns
哈希结果
Exceptions
Exception 计算过程中的异常
Definition at line 131 of file TotpUtils.java.
Referenced by com.gmp.auth.service.TotpUtils.generateTotpCode().
verifyTotpCode()
boolean com.gmp.auth.service.TotpUtils.verifyTotpCode (String secretKey, String code)
验证TOTP码（包含时间容错）
Parameters
secretKey 密钥
code 用户输入的验证码
Returns
是否验证成功
Definition at line 82 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.TOTP_TIME_STEP, and com.gmp.auth.service.TotpUtils.verifyTotpCodeAtTimestamp().
Referenced by com.gmp.auth.service.TotpUtilsTest.testEdgeCaseEmptySecretKey(), com.gmp.auth.service.TotpUtilsTest.testEdgeCaseNullSecretKey(), com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Failure(), com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Success(), com.gmp.auth.service.TotpUtilsTest.testVerifyTotpCodeInvalid(), com.gmp.auth.service.TotpUtilsTest.testVerifyTotpCodeValid(), and com.gmp.auth.service.MfaService.verifyTotpCode().
verifyTotpCodeAtTimestamp()
boolean com.gmp.auth.service.TotpUtils.verifyTotpCodeAtTimestamp (String secretKey, String code, long timestamp)
在指定时间戳验证TOTP码
Parameters
secretKey 密钥
code 用户输入的验证码
timestamp 时间戳
Returns
是否验证成功
Definition at line 101 of file TotpUtils.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.TotpUtils.TOTP_CODE_LENGTH.
Referenced by com.gmp.auth.service.TotpUtils.verifyTotpCode().
Member Data Documentation
SECRET_KEY_LENGTH
final int com.gmp.auth.service.TotpUtils.SECRET_KEY_LENGTH = 16 static private
Definition at line 17 of file TotpUtils.java.
Referenced by com.gmp.auth.service.TotpUtils.generateSecretKey().
SECURE_RANDOM
final SecureRandom com.gmp.auth.service.TotpUtils.SECURE_RANDOM = new SecureRandom() static private
Definition at line 18 of file TotpUtils.java.
Referenced by com.gmp.auth.service.TotpUtils.generateSecretKey().
TOTP_CODE_LENGTH
final int com.gmp.auth.service.TotpUtils.TOTP_CODE_LENGTH = 6 static private
Definition at line 16 of file TotpUtils.java.
Referenced by com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCodeAtTimestamp().
TOTP_TIME_STEP
final int com.gmp.auth.service.TotpUtils.TOTP_TIME_STEP = 30 static private
Definition at line 15 of file TotpUtils.java.
Referenced by com.gmp.auth.service.TotpUtils.generateTotpCode(), com.gmp.auth.service.TotpUtils.getCurrentTimeWindow(), com.gmp.auth.service.TotpUtils.getRemainingSeconds(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/TotpUtils.java