GMP系统: com.gmp.auth.test.AuthTestErrorHandler Class Reference
com.gmp.auth.test.AuthTestErrorHandler Class Reference
GMP系统认证测试错误处理器
Classes
class ErrorRecord
错误记录类
enum ErrorType
class TestExecutionException
测试执行异常类
interface TestMethod
测试方法函数式接口
class TestStatus
测试状态类
Public Member Functions
AuthTestErrorHandler ()
TestStatus getTestStatus (String testMethodName)
获取测试状态
Map< String, TestStatus > getAllTestStatuses ()
获取所有测试状态
Map< ErrorType, Integer > getErrorStatistics ()
获取错误统计信息
List< ErrorRecord > getErrorHistory ()
获取错误历史记录
String generateErrorReport ()
生成错误报告
void resetStatistics ()
重置错误统计
Package Functions
public< T > T handleTestMethod (String testMethodName, TestMethod< T > method)
处理测试方法执行过程中的异常
Private Member Functions
ErrorType classifyError (Exception e)
分类错误类型
void handleException (Exception e, String testMethodName, ErrorType errorType, int retryCount)
处理异常
boolean shouldRetry (ErrorType errorType, int retryCount)
判断是否需要重试
long calculateRetryDelay (int retryCount)
计算重试延迟时间（指数退避）
Private Attributes
final Map< String, TestStatus > testStatusMap = new ConcurrentHashMap<>()
final Map< ErrorType, Integer > errorCountMap = new EnumMap<>(ErrorType.class)
final List< ErrorRecord > errorHistory = new ArrayList<>()
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(AuthTestErrorHandler.class)
static final int MAX_RETRY_COUNT = 3
Detailed Description
GMP系统认证测试错误处理器
提供统一的错误处理机制，确保测试脚本能够优雅地处理异常
Definition at line 21 of file AuthTestErrorHandler.java.
Constructor & Destructor Documentation
AuthTestErrorHandler()
com.gmp.auth.test.AuthTestErrorHandler.AuthTestErrorHandler ()
Definition at line 50 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.errorCountMap.
Member Function Documentation
calculateRetryDelay()
long com.gmp.auth.test.AuthTestErrorHandler.calculateRetryDelay (int retryCount) private
计算重试延迟时间（指数退避）
Definition at line 184 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
classifyError()
ErrorType com.gmp.auth.test.AuthTestErrorHandler.classifyError (Exception e) private
分类错误类型
Definition at line 125 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.ErrorType.AUTHENTICATION_ERROR, com.gmp.auth.test.AuthTestErrorHandler.ErrorType.DATABASE_ERROR, com.gmp.auth.test.AuthTestErrorHandler.ErrorType.INITIALIZATION_ERROR, com.gmp.auth.test.AuthTestErrorHandler.ErrorType.OTHER_ERROR, and com.gmp.auth.test.AuthTestErrorHandler.ErrorType.VALIDATION_ERROR.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
generateErrorReport()
String com.gmp.auth.test.AuthTestErrorHandler.generateErrorReport ()
生成错误报告
Definition at line 222 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.errorCountMap, com.gmp.auth.test.AuthTestErrorHandler.errorHistory, com.gmp.auth.test.AuthTestErrorHandler.TestStatus.isSuccess(), and com.gmp.auth.test.AuthTestErrorHandler.testStatusMap.
getAllTestStatuses()
Map< String, TestStatus > com.gmp.auth.test.AuthTestErrorHandler.getAllTestStatuses ()
获取所有测试状态
Definition at line 201 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.testStatusMap.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.generateTestReport(), and com.gmp.auth.test.AuthSystemTestExecutor.getStatus().
getErrorHistory()
List< ErrorRecord > com.gmp.auth.test.AuthTestErrorHandler.getErrorHistory ()
获取错误历史记录
Definition at line 215 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.errorHistory.
getErrorStatistics()
Map< ErrorType, Integer > com.gmp.auth.test.AuthTestErrorHandler.getErrorStatistics ()
获取错误统计信息
Definition at line 208 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.errorCountMap.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.generateTestReport().
getTestStatus()
TestStatus com.gmp.auth.test.AuthTestErrorHandler.getTestStatus (String testMethodName)
获取测试状态
Definition at line 194 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.testStatusMap.
handleException()
void com.gmp.auth.test.AuthTestErrorHandler.handleException (Exception e, String testMethodName, ErrorType errorType, int retryCount) private
处理异常
Definition at line 144 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.log.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
handleTestMethod()
public< T > T com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod (String testMethodName, TestMethod< T > method) package
处理测试方法执行过程中的异常
Definition at line 60 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.calculateRetryDelay(), com.gmp.auth.test.AuthTestErrorHandler.classifyError(), com.gmp.auth.test.AuthTestErrorHandler.errorCountMap, com.gmp.auth.test.AuthTestErrorHandler.errorHistory, com.gmp.auth.test.AuthTestErrorHandler.TestMethod< T >.execute(), com.gmp.auth.test.AuthTestErrorHandler.handleException(), com.gmp.auth.test.AuthTestErrorHandler.log, com.gmp.auth.test.AuthTestErrorHandler.MAX_RETRY_COUNT, com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setEndTime(), com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setErrorMessage(), com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setErrorType(), com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setStartTime(), com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setSuccess(), com.gmp.auth.test.AuthTestErrorHandler.shouldRetry(), and com.gmp.auth.test.AuthTestErrorHandler.testStatusMap.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.executeInitialization(), and com.gmp.auth.test.AuthSystemTestExecutor.executeTestMethods().
resetStatistics()
void com.gmp.auth.test.AuthTestErrorHandler.resetStatistics ()
重置错误统计
Definition at line 267 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.errorCountMap, com.gmp.auth.test.AuthTestErrorHandler.errorHistory, com.gmp.auth.test.AuthTestErrorHandler.log, and com.gmp.auth.test.AuthTestErrorHandler.testStatusMap.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.executeTests().
shouldRetry()
boolean com.gmp.auth.test.AuthTestErrorHandler.shouldRetry (ErrorType errorType, int retryCount) private
判断是否需要重试
Definition at line 170 of file AuthTestErrorHandler.java.
References com.gmp.auth.test.AuthTestErrorHandler.ErrorType.INITIALIZATION_ERROR, and com.gmp.auth.test.AuthTestErrorHandler.MAX_RETRY_COUNT.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
Member Data Documentation
errorCountMap
final Map<ErrorType, Integer> com.gmp.auth.test.AuthTestErrorHandler.errorCountMap = new EnumMap<>(ErrorType.class) private
Definition at line 39 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.AuthTestErrorHandler(), com.gmp.auth.test.AuthTestErrorHandler.generateErrorReport(), com.gmp.auth.test.AuthTestErrorHandler.getErrorStatistics(), com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod(), and com.gmp.auth.test.AuthTestErrorHandler.resetStatistics().
errorHistory
final List<ErrorRecord> com.gmp.auth.test.AuthTestErrorHandler.errorHistory = new ArrayList<>() private
Definition at line 42 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.generateErrorReport(), com.gmp.auth.test.AuthTestErrorHandler.getErrorHistory(), com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod(), and com.gmp.auth.test.AuthTestErrorHandler.resetStatistics().
log
final Logger com.gmp.auth.test.AuthTestErrorHandler.log = LoggerFactory.getLogger(AuthTestErrorHandler.class) static private
Definition at line 47 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleException(), com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod(), and com.gmp.auth.test.AuthTestErrorHandler.resetStatistics().
MAX_RETRY_COUNT
final int com.gmp.auth.test.AuthTestErrorHandler.MAX_RETRY_COUNT = 3 static private
Definition at line 48 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod(), and com.gmp.auth.test.AuthTestErrorHandler.shouldRetry().
testStatusMap
final Map<String, TestStatus> com.gmp.auth.test.AuthTestErrorHandler.testStatusMap = new ConcurrentHashMap<>() private
Definition at line 36 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.generateErrorReport(), com.gmp.auth.test.AuthTestErrorHandler.getAllTestStatuses(), com.gmp.auth.test.AuthTestErrorHandler.getTestStatus(), com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod(), and com.gmp.auth.test.AuthTestErrorHandler.resetStatistics().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/test/AuthTestErrorHandler.java