GMP系统: com.gmp.equipment.controller.CalibrationRecordController Class Reference
com.gmp.equipment.controller.CalibrationRecordController Class Reference
设备校准记录控制器 提供校准记录相关的RESTful API接口
Public Member Functions
ResponseEntity< ResponseResult< CalibrationRecordDTO > > getById (@PathVariable Long id)
ResponseEntity< ResponseResult< CalibrationRecordDTO > > getByCalibrationNumber (@PathVariable String calibrationNumber)
ResponseEntity< ResponseResult< PageResultDTO< CalibrationRecordDTO > > > listPage (@RequestParam(required=false) Long equipmentId, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
ResponseEntity< ResponseResult< List< CalibrationRecordDTO > > > listByEquipmentId (@PathVariable Long equipmentId)
ResponseEntity< ResponseResult< List< CalibrationRecordDTO > > > listByDateRange (@RequestParam String startDate, @RequestParam String endDate) throws ParseException
ResponseEntity< ResponseResult< CalibrationRecordDTO > > getLatestByEquipmentId (@PathVariable Long equipmentId)
ResponseEntity< ResponseResult< Boolean > > checkCalibrationNumber (@RequestParam String calibrationNumber, @RequestParam(required=false) Long id)
ResponseEntity< ResponseResult< CalibrationRecordDTO > > create (@RequestBody CalibrationRecordDTO calibrationRecordDTO)
ResponseEntity< ResponseResult< CalibrationRecordDTO > > update (@PathVariable Long id, @RequestBody CalibrationRecordDTO calibrationRecordDTO)
ResponseEntity< ResponseResult< Boolean > > delete (@PathVariable Long id)
ResponseEntity< ResponseResult< Boolean > > deleteBatch (@RequestBody List< Long > ids)
Private Attributes
CalibrationRecordService calibrationRecordService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(CalibrationRecordController.class)
Detailed Description
设备校准记录控制器 提供校准记录相关的RESTful API接口
Definition at line 29 of file CalibrationRecordController.java.
Member Function Documentation
checkCalibrationNumber()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.CalibrationRecordController.checkCalibrationNumber (@RequestParam String calibrationNumber, @RequestParam(required=false) Long id)
Definition at line 136 of file CalibrationRecordController.java.
create()
ResponseEntity< ResponseResult< CalibrationRecordDTO > > com.gmp.equipment.controller.CalibrationRecordController.create (@RequestBody CalibrationRecordDTO calibrationRecordDTO)
Definition at line 149 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.create_success().
delete()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.CalibrationRecordController.delete (@PathVariable Long id)
Definition at line 181 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.delete_success().
deleteBatch()
ResponseEntity< ResponseResult< Boolean > > com.gmp.equipment.controller.CalibrationRecordController.deleteBatch (@RequestBody List< Long > ids)
Definition at line 197 of file CalibrationRecordController.java.
getByCalibrationNumber()
ResponseEntity< ResponseResult< CalibrationRecordDTO > > com.gmp.equipment.controller.CalibrationRecordController.getByCalibrationNumber (@PathVariable String calibrationNumber)
Definition at line 54 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.getByCalibrationNumber_success().
getById()
ResponseEntity< ResponseResult< CalibrationRecordDTO > > com.gmp.equipment.controller.CalibrationRecordController.getById (@PathVariable Long id)
Definition at line 38 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.getById_success().
getLatestByEquipmentId()
ResponseEntity< ResponseResult< CalibrationRecordDTO > > com.gmp.equipment.controller.CalibrationRecordController.getLatestByEquipmentId (@PathVariable Long equipmentId)
Definition at line 120 of file CalibrationRecordController.java.
listByDateRange()
ResponseEntity< ResponseResult< List< CalibrationRecordDTO > > > com.gmp.equipment.controller.CalibrationRecordController.listByDateRange (@RequestParam String startDate, @RequestParam String endDate) throws ParseException
Definition at line 99 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_invalidDateFormat(), and com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_success().
listByEquipmentId()
ResponseEntity< ResponseResult< List< CalibrationRecordDTO > > > com.gmp.equipment.controller.CalibrationRecordController.listByEquipmentId (@PathVariable Long equipmentId)
Definition at line 86 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.listByEquipmentId_success().
listPage()
ResponseEntity< ResponseResult< PageResultDTO< CalibrationRecordDTO > > > com.gmp.equipment.controller.CalibrationRecordController.listPage (@RequestParam(required=false) Long equipmentId, @RequestParam(defaultValue="1") Integer pageNum, @RequestParam(defaultValue="10") Integer pageSize)
Definition at line 70 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.listPage_success().
update()
ResponseEntity< ResponseResult< CalibrationRecordDTO > > com.gmp.equipment.controller.CalibrationRecordController.update (@PathVariable Long id, @RequestBody CalibrationRecordDTO calibrationRecordDTO)
Definition at line 165 of file CalibrationRecordController.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.update_success().
Member Data Documentation
calibrationRecordService
CalibrationRecordService com.gmp.equipment.controller.CalibrationRecordController.calibrationRecordService private
Definition at line 34 of file CalibrationRecordController.java.
logger
final Logger com.gmp.equipment.controller.CalibrationRecordController.logger = LoggerFactory.getLogger(CalibrationRecordController.class) static private
Definition at line 31 of file CalibrationRecordController.java.
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/controller/CalibrationRecordController.java