GMP系统: com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint Class Reference
com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint Class Reference
Public Member Functions
String getTimestamp ()
void setTimestamp (String timestamp)
long getCalls ()
void setCalls (long calls)
long getAverageResponseTime ()
void setAverageResponseTime (long averageResponseTime)
double getSuccessRate ()
void setSuccessRate (double successRate)
Private Attributes
String timestamp
long calls
long averageResponseTime
double successRate
Detailed Description
Definition at line 173 of file McpPerformanceReportService.java.
Member Function Documentation
getAverageResponseTime()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getAverageResponseTime ()
Definition at line 184 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.averageResponseTime.
getCalls()
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getCalls ()
Definition at line 182 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.calls.
getSuccessRate()
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getSuccessRate ()
Definition at line 186 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.successRate.
getTimestamp()
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getTimestamp ()
Definition at line 180 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.timestamp.
setAverageResponseTime()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime (long averageResponseTime)
Definition at line 185 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.averageResponseTime.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek().
setCalls()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls (long calls)
Definition at line 183 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.calls.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek().
setSuccessRate()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate (double successRate)
Definition at line 187 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.successRate.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek().
setTimestamp()
void com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp (String timestamp)
Definition at line 181 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.timestamp.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek().
Member Data Documentation
averageResponseTime
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.averageResponseTime private
Definition at line 176 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getAverageResponseTime(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime().
calls
long com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.calls private
Definition at line 175 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getCalls(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls().
successRate
double com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.successRate private
Definition at line 177 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate().
timestamp
String com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.timestamp private
Definition at line 174 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.getTimestamp(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpPerformanceReportService.java