GMP系统: com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics Class Reference
com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics Class Reference
工具调用指标
Public Member Functions
void incrementTotalCalls ()
void incrementSuccessCalls ()
void incrementFailedCalls ()
void recordDuration (long duration)
int getTotalCalls ()
int getSuccessCalls ()
int getFailedCalls ()
long getTotalDuration ()
long getMaxDuration ()
double getAverageDuration ()
double getSuccessRate ()
Private Attributes
final AtomicInteger totalCalls = new AtomicInteger(0)
final AtomicInteger successCalls = new AtomicInteger(0)
final AtomicInteger failedCalls = new AtomicInteger(0)
final AtomicLong totalDuration = new AtomicLong(0)
final AtomicLong maxDuration = new AtomicLong(0)
Detailed Description
工具调用指标
Definition at line 159 of file McpMonitoringService.java.
Member Function Documentation
getAverageDuration()
double com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration ()
Definition at line 203 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
getFailedCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getFailedCalls ()
Definition at line 191 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls.
getMaxDuration()
long com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getMaxDuration ()
Definition at line 199 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration.
getSuccessCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessCalls ()
Definition at line 187 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls.
getSuccessRate()
double com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate ()
Definition at line 208 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
getTotalCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalCalls ()
Definition at line 183 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
getTotalDuration()
long com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalDuration ()
Definition at line 195 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
incrementFailedCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementFailedCalls ()
Definition at line 174 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
incrementSuccessCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementSuccessCalls ()
Definition at line 170 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
incrementTotalCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls ()
Definition at line 166 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.startResourceAccess(), and com.gmp.qms.monitoring.McpMonitoringService.startToolCall().
recordDuration()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration (long duration)
Definition at line 178 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
Member Data Documentation
failedCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls = new AtomicInteger(0) private
Definition at line 162 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getFailedCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementFailedCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
maxDuration
final AtomicLong com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration = new AtomicLong(0) private
Definition at line 164 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getMaxDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
successCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls = new AtomicInteger(0) private
Definition at line 161 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementSuccessCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
totalCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls = new AtomicInteger(0) private
Definition at line 160 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
totalDuration
final AtomicLong com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration = new AtomicLong(0) private
Definition at line 163 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/monitoring/McpMonitoringService.java