GMP系统: com.gmp.edms.service.CommonFileServiceIntegrationTest Class Reference
com.gmp.edms.service.CommonFileServiceIntegrationTest Class Reference
CommonFileService集成测试 验证文件存储功能整合的正确性
Package Functions
void setUp ()
void testUploadFile () throws Exception
测试文件上传功能
void testBatchUploadFiles () throws Exception
测试批量上传文件功能
void testDeleteFile () throws Exception
测试文件删除功能
void testGetFileInfo () throws Exception
测试获取文件信息功能
void testGeneratePresignedUrl () throws Exception
测试生成预签名URL功能
void testQueryFiles () throws Exception
测试查询文件功能
void testUpdateFileMetadata () throws Exception
测试更新文件元数据功能
void testGetFileStatistics () throws Exception
测试获取文件统计信息功能
Private Attributes
CommonFileService commonFileService
CommonFileRepository commonFileRepository
MockMultipartFile testFile
Map< String, Object > metadata
Detailed Description
CommonFileService集成测试 验证文件存储功能整合的正确性
Definition at line 29 of file CommonFileServiceIntegrationTest.java.
Member Function Documentation
setUp()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.setUp () package
Definition at line 41 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, and com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile.
testBatchUploadFiles()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testBatchUploadFiles () throws Exception package
测试批量上传文件功能
Definition at line 84 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileService.batchUploadFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, and com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile.
testDeleteFile()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile () throws Exception package
测试文件删除功能
Definition at line 113 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileRepository, com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.deleteFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
testGeneratePresignedUrl()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl () throws Exception package
测试生成预签名URL功能
Definition at line 153 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.generatePresignedUrl(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
testGetFileInfo()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo () throws Exception package
测试获取文件信息功能
Definition at line 132 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.getFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
testGetFileStatistics()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics () throws Exception package
测试获取文件统计信息功能
Definition at line 214 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.getFileStatistics(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
testQueryFiles()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles () throws Exception package
测试查询文件功能
Definition at line 170 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileService.queryFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
testUpdateFileMetadata()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata () throws Exception package
测试更新文件元数据功能
Definition at line 190 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.getFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, com.gmp.edms.service.CommonFileService.updateFileMetadata(), and com.gmp.edms.service.CommonFileService.uploadFile().
testUploadFile()
void com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile () throws Exception package
测试文件上传功能
Definition at line 59 of file CommonFileServiceIntegrationTest.java.
References com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileRepository, com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService, com.gmp.edms.service.CommonFileService.downloadFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata, com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile, and com.gmp.edms.service.CommonFileService.uploadFile().
Member Data Documentation
commonFileRepository
CommonFileRepository com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileRepository private
Definition at line 35 of file CommonFileServiceIntegrationTest.java.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
commonFileService
CommonFileService com.gmp.edms.service.CommonFileServiceIntegrationTest.commonFileService private
Definition at line 32 of file CommonFileServiceIntegrationTest.java.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testBatchUploadFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
metadata
Map<String, Object> com.gmp.edms.service.CommonFileServiceIntegrationTest.metadata private
Definition at line 38 of file CommonFileServiceIntegrationTest.java.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.setUp(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testBatchUploadFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
testFile
MockMultipartFile com.gmp.edms.service.CommonFileServiceIntegrationTest.testFile private
Definition at line 37 of file CommonFileServiceIntegrationTest.java.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.setUp(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testBatchUploadFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/CommonFileServiceIntegrationTest.java