GMP系统: com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest Class Reference
com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest Class Reference
Public Member Functions
String getUsername ()
void setUsername (String username)
String getEmail ()
void setEmail (String email)
String getVerificationCode ()
void setVerificationCode (String verificationCode)
Private Attributes
String username
String email
String verificationCode
Detailed Description
Definition at line 1384 of file GMPComprehensiveAuthIntegrationTest.java.
Member Function Documentation
getEmail()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.getEmail ()
Definition at line 1391 of file GMPComprehensiveAuthIntegrationTest.java.
getUsername()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.getUsername ()
Definition at line 1389 of file GMPComprehensiveAuthIntegrationTest.java.
getVerificationCode()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.getVerificationCode ()
Definition at line 1393 of file GMPComprehensiveAuthIntegrationTest.java.
setEmail()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.setEmail (String email)
Definition at line 1392 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.performGMPPasswordReset(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordResetFlow().
setUsername()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.setUsername (String username)
Definition at line 1390 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.performGMPPasswordReset(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordResetFlow().
setVerificationCode()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.setVerificationCode (String verificationCode)
Definition at line 1394 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.performGMPPasswordReset(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordResetFlow().
Member Data Documentation
email
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.email private
Definition at line 1386 of file GMPComprehensiveAuthIntegrationTest.java.
username
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.username private
Definition at line 1385 of file GMPComprehensiveAuthIntegrationTest.java.
verificationCode
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetRequest.verificationCode private
Definition at line 1387 of file GMPComprehensiveAuthIntegrationTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/GMPComprehensiveAuthIntegrationTest.java