GMP系统: com.gmp.edms.service.impl.DocumentVersionServiceImpl Class Reference
com.gmp.edms.service.impl.DocumentVersionServiceImpl Class Reference
文档版本服务实现
Classes
class MockMultipartFile
模拟MultipartFile类，用于创建临时文件上传
Public Member Functions
DocumentVersionDTO uploadDocumentVersion (Long documentId, MultipartFile file, String versionType, String changeReason, String changeSummary, String author) throws Exception
上传新版本文档
List< DocumentVersionDTO > getDocumentVersions (Long documentId)
获取文档版本列表
DocumentVersionDTO getCurrentVersion (Long documentId)
获取文档当前版本
DocumentVersionDTO getCurrentDocumentVersion (Long documentId)
DocumentVersionDTO getVersionById (Long versionId)
根据版本ID获取版本信息
byte[] downloadDocumentVersion (Long versionId) throws Exception
下载文档版本
void deleteDocumentVersion (Long versionId) throws Exception
删除文档版本
void setCurrentVersion (Long documentId, Long versionId)
设置文档当前版本
DocumentVersionDTO approveVersion (Long versionId, String approver, boolean isApproved, String comments)
审批文档版本
String generatePresignedUrl (Long versionId)
生成预签名URL用于文件访问 注意：此方法目前不是接口定义的一部分
String generateNewVersionNumber (Long documentId, String versionType)
生成新版本号
boolean checkFileExists (String checksum)
检查文件是否已存在（基于校验和）
long getVersionCount (Long documentId)
获取版本历史统计
String compareVersions (Long versionId1, Long versionId2) throws Exception
比较两个版本的差异
DocumentVersionDTO rollbackToVersion (Long versionId) throws Exception
回滚到指定版本
Map< String, Long > calculateUsageStatistics ()
void restoreDocumentVersion (Long documentId, Long versionId) throws Exception
恢复文档到指定版本
String compareDocumentVersions (Long documentId, Long fromVersionId, Long toVersionId) throws Exception
比较文档版本（详细比较）
Protected Member Functions
String calculateChecksum (MultipartFile file) throws IOException
计算文件哈希值
String formatFileSize (long size)
格式化文件大小
Private Member Functions
Long sumFileSize (List< DocumentVersion > versions)
String getFileExtension (String fileName)
获取文件扩展名
Object getFieldValue (Object obj, String fieldName)
使用反射获取对象的字段值
void setFieldValue (Object obj, String fieldName, Object value)
使用反射设置对象的字段值
java.lang.reflect.Field findField (Class<?> clazz, String fieldName)
查找字段，包括父类中的字段
Private Attributes
DocumentVersionRepository documentVersionRepository
DocumentRepository documentRepository
FileStorageService fileStorageService
ModelMapper modelMapper
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(DocumentVersionServiceImpl.class)
Detailed Description
文档版本服务实现
Definition at line 38 of file DocumentVersionServiceImpl.java.
Member Function Documentation
approveVersion()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.approveVersion (Long versionId, String approver, boolean isApproved, String comments)
审批文档版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 262 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testApproveVersion().
calculateChecksum()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.calculateChecksum (MultipartFile file) throws IOException protected
计算文件哈希值
Definition at line 418 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testCalculateChecksum(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
calculateUsageStatistics()
Map< String, Long > com.gmp.edms.service.impl.DocumentVersionServiceImpl.calculateUsageStatistics ()
Definition at line 594 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.sumFileSize().
checkFileExists()
boolean com.gmp.edms.service.impl.DocumentVersionServiceImpl.checkFileExists (String checksum)
检查文件是否已存在（基于校验和）
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 334 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
compareDocumentVersions()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareDocumentVersions (Long documentId, Long fromVersionId, Long toVersionId) throws Exception
比较文档版本（详细比较）
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 629 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testCompareVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testCompareVersionsDifferentChecksum(), and com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testCompareVersionsDifferentSize().
compareVersions()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareVersions (Long versionId1, Long versionId2) throws Exception
比较两个版本的差异
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 344 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue().
deleteDocumentVersion()
void com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion (Long versionId) throws Exception
删除文档版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 186 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.FileStorageService.deleteFile(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService, com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testDeleteDocumentVersion().
downloadDocumentVersion()
byte[] com.gmp.edms.service.impl.DocumentVersionServiceImpl.downloadDocumentVersion (Long versionId) throws Exception
下载文档版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 172 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.FileStorageService.downloadFile(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue().
findField()
java.lang.reflect.Field com.gmp.edms.service.impl.DocumentVersionServiceImpl.findField (Class<?> clazz, String fieldName) private
查找字段，包括父类中的字段
Definition at line 582 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
formatFileSize()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize (long size) protected
格式化文件大小
Definition at line 443 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById(), and com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testFormatFileSize().
generateNewVersionNumber()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.generateNewVersionNumber (Long documentId, String versionType)
生成新版本号
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 295 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
generatePresignedUrl()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.generatePresignedUrl (Long versionId)
生成预签名URL用于文件访问 注意：此方法目前不是接口定义的一部分
Definition at line 281 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService, com.gmp.edms.service.FileStorageService.generatePresignedUrl(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue().
getCurrentDocumentVersion()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion (Long documentId)
Definition at line 139 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
getCurrentVersion()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion (Long documentId)
获取文档当前版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 127 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
getDocumentVersions()
List< DocumentVersionDTO > com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions (Long documentId)
获取文档版本列表
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 112 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImplTest.testGetDocumentVersions().
getFieldValue()
Object com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue (Object obj, String fieldName) private
使用反射获取对象的字段值
Definition at line 517 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.downloadDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.generatePresignedUrl(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.restoreDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.setCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.sumFileSize(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
getFileExtension()
String com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFileExtension (String fileName) private
获取文件扩展名
Definition at line 408 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion().
getVersionById()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById (Long versionId)
根据版本ID获取版本信息
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 159 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.formatFileSize(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
getVersionCount()
long com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionCount (Long documentId)
获取版本历史统计
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 339 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository.
restoreDocumentVersion()
void com.gmp.edms.service.impl.DocumentVersionServiceImpl.restoreDocumentVersion (Long documentId, Long versionId) throws Exception
恢复文档到指定版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 606 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
rollbackToVersion()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion (Long versionId) throws Exception
回滚到指定版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 363 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.FileStorageService.downloadFile(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService, com.gmp.edms.service.impl.DocumentVersionServiceImpl.generateNewVersionNumber(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFileExtension(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
setCurrentVersion()
void com.gmp.edms.service.impl.DocumentVersionServiceImpl.setCurrentVersion (Long documentId, Long versionId)
设置文档当前版本
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 237 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue().
setFieldValue()
void com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue (Object obj, String fieldName, Object value) private
使用反射设置对象的字段值
Definition at line 546 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.approveVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.restoreDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.setCurrentVersion(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
sumFileSize()
Long com.gmp.edms.service.impl.DocumentVersionServiceImpl.sumFileSize (List< DocumentVersion > versions) private
Definition at line 229 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.calculateUsageStatistics().
uploadDocumentVersion()
DocumentVersionDTO com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion (Long documentId, MultipartFile file, String versionType, String changeReason, String changeSummary, String author) throws Exception
上传新版本文档
Implements com.gmp.edms.service.DocumentVersionService.
Definition at line 55 of file DocumentVersionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentVersionServiceImpl.calculateChecksum(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.checkFileExists(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository, com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService, com.gmp.edms.service.impl.DocumentVersionServiceImpl.generateNewVersionNumber(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper, com.gmp.edms.service.impl.DocumentVersionServiceImpl.setFieldValue(), and com.gmp.edms.service.FileStorageService.uploadFile().
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion().
Member Data Documentation
documentRepository
DocumentRepository com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentRepository private
Definition at line 45 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.restoreDocumentVersion(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.setCurrentVersion().
documentVersionRepository
DocumentVersionRepository com.gmp.edms.service.impl.DocumentVersionServiceImpl.documentVersionRepository private
Definition at line 42 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.approveVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.calculateUsageStatistics(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.checkFileExists(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.compareVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.downloadDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.generateNewVersionNumber(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.generatePresignedUrl(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionCount(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.restoreDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.setCurrentVersion(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
fileStorageService
FileStorageService com.gmp.edms.service.impl.DocumentVersionServiceImpl.fileStorageService private
Definition at line 48 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.downloadDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.generatePresignedUrl(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
log
final Logger com.gmp.edms.service.impl.DocumentVersionServiceImpl.log = LoggerFactory.getLogger(DocumentVersionServiceImpl.class) static private
Definition at line 39 of file DocumentVersionServiceImpl.java.
modelMapper
ModelMapper com.gmp.edms.service.impl.DocumentVersionServiceImpl.modelMapper private
Definition at line 51 of file DocumentVersionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.approveVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getCurrentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getDocumentVersions(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.getVersionById(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/DocumentVersionServiceImpl.java