GMP系统: com.gmp.qms.service.monitoring.McpMonitoringService Class Reference
com.gmp.qms.service.monitoring.McpMonitoringService Class Reference
MCP监控服务，负责收集和管理MCP通信的性能指标、错误日志和系统健康状态
Classes
class CacheStats
class CallDetail
class CircuitBreakerStats
class ErrorLog
class McpTimer
MCP计时器内部类
class MessageQueueStats
class SystemCallStats
class SystemHealthStatus
class SystemMetrics
Public Member Functions
McpTimer startTimer (String operationName)
启动计时
void incrementCounter (String counterName, String tag)
增加计数器
SystemMetrics getSystemMetrics ()
获取系统指标
Map< String, SystemCallStats > getAllSystemCallStats ()
获取所有系统调用统计
List< ErrorLog > getRecentErrors (int limit)
获取最近的错误
SystemHealthStatus getSystemHealthStatus ()
获取系统健康状态
List< CallDetail > getCallDetailsBySystem (String systemName, int limit)
根据系统获取调用详情
List< CallDetail > getRecentCallDetails (int limit)
获取最近的调用详情
List< ErrorLog > getErrorLogs (int page, int pageSize)
获取错误日志
int getErrorLogCount ()
获取错误日志数量
CacheStats getCacheStats ()
获取缓存统计
MessageQueueStats getMessageQueueStats ()
获取消息队列统计
Map< String, CircuitBreakerStats > getCircuitBreakerStats ()
获取断路器统计
void resetAllMetrics ()
重置所有指标
Private Member Functions
long getTotalCalls ()
double getSuccessRate ()
long getAverageResponseTime ()
long getErrorCount ()
double getErrorRate ()
int getActiveConnections ()
long getServiceUptime ()
Private Attributes
final Map< String, AtomicLong > counters = new ConcurrentHashMap<>()
final Map< String, List< Long > > performanceMetrics = new ConcurrentHashMap<>()
final List< ErrorLog > errorLogs = Collections.synchronizedList(new ArrayList<>())
final Map< String, SystemCallStats > systemCallStats = new ConcurrentHashMap<>()
final CacheStats cacheStats = new CacheStats()
final MessageQueueStats messageQueueStats = new MessageQueueStats()
final Map< String, CircuitBreakerStats > circuitBreakerStats = new ConcurrentHashMap<>()
Detailed Description
MCP监控服务，负责收集和管理MCP通信的性能指标、错误日志和系统健康状态
Definition at line 16 of file McpMonitoringService.java.
Member Function Documentation
getActiveConnections()
int com.gmp.qms.service.monitoring.McpMonitoringService.getActiveConnections () private
Definition at line 210 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
getAllSystemCallStats()
Map< String, SystemCallStats > com.gmp.qms.service.monitoring.McpMonitoringService.getAllSystemCallStats ()
获取所有系统调用统计
Returns
系统调用统计映射
Definition at line 75 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.systemCallStats.
getAverageResponseTime()
long com.gmp.qms.service.monitoring.McpMonitoringService.getAverageResponseTime () private
Definition at line 196 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
getCacheStats()
CacheStats com.gmp.qms.service.monitoring.McpMonitoringService.getCacheStats ()
获取缓存统计
Returns
缓存统计
Definition at line 153 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.cacheStats.
getCallDetailsBySystem()
List< CallDetail > com.gmp.qms.service.monitoring.McpMonitoringService.getCallDetailsBySystem (String systemName, int limit)
根据系统获取调用详情
Parameters
systemName 系统名称
limit 限制数量
Returns
调用详情列表
Definition at line 111 of file McpMonitoringService.java.
getCircuitBreakerStats()
Map< String, CircuitBreakerStats > com.gmp.qms.service.monitoring.McpMonitoringService.getCircuitBreakerStats ()
获取断路器统计
Returns
断路器统计映射
Definition at line 169 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.circuitBreakerStats.
getErrorCount()
long com.gmp.qms.service.monitoring.McpMonitoringService.getErrorCount () private
Definition at line 201 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getErrorRate(), and com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
getErrorLogCount()
int com.gmp.qms.service.monitoring.McpMonitoringService.getErrorLogCount ()
获取错误日志数量
Returns
错误日志数量
Definition at line 145 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs.
getErrorLogs()
List< ErrorLog > com.gmp.qms.service.monitoring.McpMonitoringService.getErrorLogs (int page, int pageSize)
获取错误日志
Parameters
page 页码
pageSize 每页大小
Returns
错误日志列表
Definition at line 130 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs.
getErrorRate()
double com.gmp.qms.service.monitoring.McpMonitoringService.getErrorRate () private
Definition at line 205 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.getErrorCount(), and com.gmp.qms.service.monitoring.McpMonitoringService.getTotalCalls().
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
getMessageQueueStats()
MessageQueueStats com.gmp.qms.service.monitoring.McpMonitoringService.getMessageQueueStats ()
获取消息队列统计
Returns
消息队列统计
Definition at line 161 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.messageQueueStats.
getRecentCallDetails()
List< CallDetail > com.gmp.qms.service.monitoring.McpMonitoringService.getRecentCallDetails (int limit)
获取最近的调用详情
Parameters
limit 限制数量
Returns
调用详情列表
Definition at line 120 of file McpMonitoringService.java.
getRecentErrors()
List< ErrorLog > com.gmp.qms.service.monitoring.McpMonitoringService.getRecentErrors (int limit)
获取最近的错误
Parameters
limit 限制数量
Returns
错误日志列表
Definition at line 84 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs.
getServiceUptime()
long com.gmp.qms.service.monitoring.McpMonitoringService.getServiceUptime () private
Definition at line 215 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
getSuccessRate()
double com.gmp.qms.service.monitoring.McpMonitoringService.getSuccessRate () private
Definition at line 191 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
getSystemHealthStatus()
SystemHealthStatus com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus ()
获取系统健康状态
Returns
系统健康状态
Definition at line 96 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.getActiveConnections(), com.gmp.qms.service.monitoring.McpMonitoringService.getErrorRate(), com.gmp.qms.service.monitoring.McpMonitoringService.getServiceUptime(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setActiveConnections(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setErrorRate(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setOverallStatus(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setServiceUptime().
getSystemMetrics()
SystemMetrics com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics ()
获取系统指标
Returns
系统指标
Definition at line 62 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.getAverageResponseTime(), com.gmp.qms.service.monitoring.McpMonitoringService.getErrorCount(), com.gmp.qms.service.monitoring.McpMonitoringService.getSuccessRate(), com.gmp.qms.service.monitoring.McpMonitoringService.getTotalCalls(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setAvgResponseTime(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setErrorCount(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setSuccessRate(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setTotalCalls().
getTotalCalls()
long com.gmp.qms.service.monitoring.McpMonitoringService.getTotalCalls () private
Definition at line 187 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.counters.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getErrorRate(), and com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
incrementCounter()
void com.gmp.qms.service.monitoring.McpMonitoringService.incrementCounter (String counterName, String tag)
增加计数器
Parameters
counterName 计数器名称
tag 标签
Definition at line 53 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.counters.
resetAllMetrics()
void com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics ()
重置所有指标
Definition at line 176 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.cacheStats, com.gmp.qms.service.monitoring.McpMonitoringService.circuitBreakerStats, com.gmp.qms.service.monitoring.McpMonitoringService.counters, com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs, com.gmp.qms.service.monitoring.McpMonitoringService.messageQueueStats, com.gmp.qms.service.monitoring.McpMonitoringService.performanceMetrics, com.gmp.qms.service.monitoring.McpMonitoringService.CacheStats.reset(), com.gmp.qms.service.monitoring.McpMonitoringService.MessageQueueStats.reset(), and com.gmp.qms.service.monitoring.McpMonitoringService.systemCallStats.
startTimer()
McpTimer com.gmp.qms.service.monitoring.McpMonitoringService.startTimer (String operationName)
启动计时
Parameters
operationName 操作名称
Returns
McpTimer实例
Definition at line 44 of file McpMonitoringService.java.
Member Data Documentation
cacheStats
final CacheStats com.gmp.qms.service.monitoring.McpMonitoringService.cacheStats = new CacheStats() private
Definition at line 31 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getCacheStats(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
circuitBreakerStats
final Map<String, CircuitBreakerStats> com.gmp.qms.service.monitoring.McpMonitoringService.circuitBreakerStats = new ConcurrentHashMap<>() private
Definition at line 37 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getCircuitBreakerStats(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
counters
final Map<String, AtomicLong> com.gmp.qms.service.monitoring.McpMonitoringService.counters = new ConcurrentHashMap<>() private
Definition at line 19 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getTotalCalls(), com.gmp.qms.service.monitoring.McpMonitoringService.incrementCounter(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
errorLogs
final List<ErrorLog> com.gmp.qms.service.monitoring.McpMonitoringService.errorLogs = Collections.synchronizedList(new ArrayList<>()) private
Definition at line 25 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getErrorCount(), com.gmp.qms.service.monitoring.McpMonitoringService.getErrorLogCount(), com.gmp.qms.service.monitoring.McpMonitoringService.getErrorLogs(), com.gmp.qms.service.monitoring.McpMonitoringService.getRecentErrors(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
messageQueueStats
final MessageQueueStats com.gmp.qms.service.monitoring.McpMonitoringService.messageQueueStats = new MessageQueueStats() private
Definition at line 34 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getMessageQueueStats(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
performanceMetrics
final Map<String, List<Long> > com.gmp.qms.service.monitoring.McpMonitoringService.performanceMetrics = new ConcurrentHashMap<>() private
Definition at line 22 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.complete(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
systemCallStats
final Map<String, SystemCallStats> com.gmp.qms.service.monitoring.McpMonitoringService.systemCallStats = new ConcurrentHashMap<>() private
Definition at line 28 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.complete(), com.gmp.qms.service.monitoring.McpMonitoringService.getAllSystemCallStats(), and com.gmp.qms.service.monitoring.McpMonitoringService.resetAllMetrics().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpMonitoringService.java