GMP系统: com.gmp.auth.exception.GlobalExceptionHandler Class Reference
com.gmp.auth.exception.GlobalExceptionHandler Class Reference
全局异常处理器 用于统一处理认证相关的异常
Classes
class ErrorResponse
错误响应类
Public Member Functions
ResponseEntity< ErrorResponse > handleAuthenticationException (AuthenticationException ex)
处理认证异常
ResponseEntity< ErrorResponse > handleAccessDeniedException (AccessDeniedException ex)
处理访问被拒绝异常
ResponseEntity< ErrorResponse > handleValidationException (MethodArgumentNotValidException ex)
处理请求参数验证异常
ResponseEntity< ErrorResponse > handleTokenException (TokenException ex)
处理令牌相关异常
ResponseEntity< ErrorResponse > handleBusinessException (BusinessException ex)
处理业务异常
ResponseEntity< ErrorResponse > handleGenericException (Exception ex)
处理其他所有异常
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class)
Detailed Description
全局异常处理器 用于统一处理认证相关的异常
Definition at line 28 of file GlobalExceptionHandler.java.
Member Function Documentation
handleAccessDeniedException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleAccessDeniedException (AccessDeniedException ex)
处理访问被拒绝异常
Definition at line 66 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAccessDeniedException().
handleAuthenticationException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException (AuthenticationException ex)
处理认证异常
Definition at line 38 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_BadCredentials(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Disabled(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Generic(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleAuthenticationException_Locked(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.testMissingBusinessExceptionDoesNotBreakOtherFunctionality().
handleBusinessException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleBusinessException (BusinessException ex)
处理业务异常
Definition at line 126 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.BusinessException.getErrorCode(), com.gmp.auth.exception.BusinessException.getStatusCode(), and com.gmp.auth.exception.GlobalExceptionHandler.logger.
handleGenericException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleGenericException (Exception ex)
处理其他所有异常
Definition at line 145 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleGenericException().
handleTokenException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleTokenException (TokenException ex)
处理令牌相关异常
Definition at line 108 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException(), com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Expired(), and com.gmp.auth.exception.GlobalExceptionHandlerTest.handleTokenException_Invalid().
handleValidationException()
ResponseEntity< ErrorResponse > com.gmp.auth.exception.GlobalExceptionHandler.handleValidationException (MethodArgumentNotValidException ex)
处理请求参数验证异常
Definition at line 85 of file GlobalExceptionHandler.java.
References com.gmp.auth.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.auth.exception.GlobalExceptionHandlerTest.handleValidationException().
Member Data Documentation
logger
final Logger com.gmp.auth.exception.GlobalExceptionHandler.logger = LoggerFactory.getLogger(GlobalExceptionHandler.class) static private
Definition at line 30 of file GlobalExceptionHandler.java.
Referenced by com.gmp.auth.exception.GlobalExceptionHandler.handleAccessDeniedException(), com.gmp.auth.exception.GlobalExceptionHandler.handleAuthenticationException(), com.gmp.auth.exception.GlobalExceptionHandler.handleBusinessException(), com.gmp.auth.exception.GlobalExceptionHandler.handleGenericException(), com.gmp.auth.exception.GlobalExceptionHandler.handleTokenException(), and com.gmp.auth.exception.GlobalExceptionHandler.handleValidationException().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/exception/GlobalExceptionHandler.java