GMP系统: com.gmp.auth.entity.Permission Class Reference
com.gmp.auth.entity.Permission Class Reference
GMP系统权限实体
Public Member Functions
boolean isValid ()
检查权限是否有效
boolean matches (String url, String method)
检查是否匹配给定的请求
Private Attributes
Long id
String permissionCode
String permissionName
String resourceType
String resourceUrl
String httpMethod = "ALL"
String description
Boolean isActive = true
LocalDateTime createdAt
LocalDateTime updatedAt
Long createdBy
Long updatedBy
Integer version = 1
Detailed Description
GMP系统权限实体
Author
GMP系统开发团队
Definition at line 27 of file Permission.java.
Member Function Documentation
isValid()
boolean com.gmp.auth.entity.Permission.isValid ()
检查权限是否有效
Definition at line 88 of file Permission.java.
Referenced by com.gmp.auth.entity.PermissionTest.testPermissionActiveState(), com.gmp.auth.entity.PermissionTest.testPermissionCreation(), and com.gmp.auth.entity.PermissionTest.testPermissionValidationScenarios().
matches()
boolean com.gmp.auth.entity.Permission.matches (String url, String method)
检查是否匹配给定的请求
Definition at line 96 of file Permission.java.
Referenced by com.gmp.auth.entity.PermissionTest.testPermissionWithNullResourceUrl(), com.gmp.auth.entity.PermissionTest.testResourceUrlMatching(), and com.gmp.auth.entity.PermissionTest.testUrlPatternMatching().
Member Data Documentation
createdAt
LocalDateTime com.gmp.auth.entity.Permission.createdAt private
Definition at line 68 of file Permission.java.
createdBy
Long com.gmp.auth.entity.Permission.createdBy private
Definition at line 75 of file Permission.java.
description
String com.gmp.auth.entity.Permission.description private
Definition at line 59 of file Permission.java.
httpMethod
String com.gmp.auth.entity.Permission.httpMethod = "ALL" private
Definition at line 56 of file Permission.java.
id
Long com.gmp.auth.entity.Permission.id private
Definition at line 31 of file Permission.java.
isActive
Boolean com.gmp.auth.entity.Permission.isActive = true private
Definition at line 63 of file Permission.java.
permissionCode
String com.gmp.auth.entity.Permission.permissionCode private
Definition at line 37 of file Permission.java.
Referenced by com.gmp.auth.entity.PermissionTest.testHttpMethodValidation(), com.gmp.auth.entity.PermissionTest.testPermissionActiveState(), com.gmp.auth.entity.PermissionTest.testPermissionAuditFields(), com.gmp.auth.entity.PermissionTest.testPermissionCodeValidation(), com.gmp.auth.entity.PermissionTest.testPermissionCreation(), com.gmp.auth.entity.PermissionTest.testPermissionValidationScenarios(), com.gmp.auth.entity.PermissionTest.testPermissionWithMinimalData(), com.gmp.auth.entity.PermissionTest.testPermissionWithNullResourceUrl(), com.gmp.auth.entity.PermissionTest.testResourceTypeValidation(), com.gmp.auth.entity.PermissionTest.testResourceUrlMatching(), and com.gmp.auth.entity.PermissionTest.testUrlPatternMatching().
permissionName
String com.gmp.auth.entity.Permission.permissionName private
Definition at line 42 of file Permission.java.
Referenced by com.gmp.auth.entity.PermissionTest.testPermissionValidationScenarios().
resourceType
String com.gmp.auth.entity.Permission.resourceType private
Definition at line 47 of file Permission.java.
resourceUrl
String com.gmp.auth.entity.Permission.resourceUrl private
Definition at line 51 of file Permission.java.
updatedAt
LocalDateTime com.gmp.auth.entity.Permission.updatedAt private
Definition at line 72 of file Permission.java.
updatedBy
Long com.gmp.auth.entity.Permission.updatedBy private
Definition at line 78 of file Permission.java.
version
Integer com.gmp.auth.entity.Permission.version = 1 private
Definition at line 82 of file Permission.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/Permission.java