GMP系统: com.gmp.equipment.controller.EquipmentTypeControllerTest Class Reference
com.gmp.equipment.controller.EquipmentTypeControllerTest Class Reference
EquipmentTypeController的单元测试类
Package Functions
void setUp ()
void getById_success ()
void getById_notFound ()
void listPage_success ()
void listAll_success ()
void create_success ()
void update_success ()
void delete_success ()
void deleteBatch_success ()
Private Attributes
EquipmentTypeService equipmentTypeService
EquipmentTypeController equipmentTypeController
Detailed Description
EquipmentTypeController的单元测试类
Definition at line 23 of file EquipmentTypeControllerTest.java.
Member Function Documentation
create_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.create_success () package
Definition at line 130 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeController.create(), com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, and com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService.
delete_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.delete_success () package
Definition at line 177 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeController.delete(), com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, and com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService.
deleteBatch_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.deleteBatch_success () package
Definition at line 194 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeController.deleteBatch(), com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, and com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService.
getById_notFound()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_notFound () package
Definition at line 57 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService, and com.gmp.equipment.controller.EquipmentTypeController.getById().
getById_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_success () package
Definition at line 37 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService, and com.gmp.equipment.controller.EquipmentTypeController.getById().
listAll_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.listAll_success () package
Definition at line 105 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService, and com.gmp.equipment.controller.EquipmentTypeController.listAll().
listPage_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.listPage_success () package
Definition at line 74 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService, and com.gmp.equipment.controller.EquipmentTypeController.listPage().
setUp()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.setUp () package
Definition at line 32 of file EquipmentTypeControllerTest.java.
update_success()
void com.gmp.equipment.controller.EquipmentTypeControllerTest.update_success () package
Definition at line 154 of file EquipmentTypeControllerTest.java.
References com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController, com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService, and com.gmp.equipment.controller.EquipmentTypeController.update().
Member Data Documentation
equipmentTypeController
EquipmentTypeController com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeController private
Definition at line 29 of file EquipmentTypeControllerTest.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.create_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.delete_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.deleteBatch_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_notFound(), com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.listAll_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.listPage_success(), and com.gmp.equipment.controller.EquipmentTypeControllerTest.update_success().
equipmentTypeService
EquipmentTypeService com.gmp.equipment.controller.EquipmentTypeControllerTest.equipmentTypeService private
Definition at line 26 of file EquipmentTypeControllerTest.java.
Referenced by com.gmp.equipment.controller.EquipmentTypeControllerTest.create_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.delete_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.deleteBatch_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_notFound(), com.gmp.equipment.controller.EquipmentTypeControllerTest.getById_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.listAll_success(), com.gmp.equipment.controller.EquipmentTypeControllerTest.listPage_success(), and com.gmp.equipment.controller.EquipmentTypeControllerTest.update_success().
The documentation for this class was generated from the following file:
equipment-service/src/test/java/com/gmp/equipment/controller/EquipmentTypeControllerTest.java