GMP系统: com.gmp.qms.service.McpPerformanceCacheService Class Reference
com.gmp.qms.service.McpPerformanceCacheService Class Reference
MCP性能缓存服务
Public Member Functions
Map< String, Object > getCache ()
获取缓存对象
void put (String key, Object value)
添加缓存项
Object get (String key)
获取缓存项
void clear ()
清除缓存
int size ()
获取缓存大小
Private Attributes
final Map< String, Object > cache = new ConcurrentHashMap<>()
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(McpPerformanceCacheService.class)
Detailed Description
MCP性能缓存服务
Definition at line 13 of file McpPerformanceCacheService.java.
Member Function Documentation
clear()
void com.gmp.qms.service.McpPerformanceCacheService.clear ()
清除缓存
Definition at line 50 of file McpPerformanceCacheService.java.
References com.gmp.qms.service.McpPerformanceCacheService.cache, and com.gmp.qms.service.McpPerformanceCacheService.log.
get()
Object com.gmp.qms.service.McpPerformanceCacheService.get (String key)
获取缓存项
Parameters
key 缓存键
Returns
缓存值
Definition at line 41 of file McpPerformanceCacheService.java.
References com.gmp.qms.service.McpPerformanceCacheService.cache, and com.gmp.qms.service.McpPerformanceCacheService.log.
getCache()
Map< String, Object > com.gmp.qms.service.McpPerformanceCacheService.getCache ()
获取缓存对象
Returns
缓存Map
Definition at line 22 of file McpPerformanceCacheService.java.
References com.gmp.qms.service.McpPerformanceCacheService.cache.
put()
void com.gmp.qms.service.McpPerformanceCacheService.put (String key, Object value)
添加缓存项
Parameters
key 缓存键
value 缓存值
Definition at line 31 of file McpPerformanceCacheService.java.
References com.gmp.qms.service.McpPerformanceCacheService.cache, and com.gmp.qms.service.McpPerformanceCacheService.log.
size()
int com.gmp.qms.service.McpPerformanceCacheService.size ()
获取缓存大小
Returns
缓存项数量
Definition at line 59 of file McpPerformanceCacheService.java.
References com.gmp.qms.service.McpPerformanceCacheService.cache.
Member Data Documentation
cache
final Map<String, Object> com.gmp.qms.service.McpPerformanceCacheService.cache = new ConcurrentHashMap<>() private
Definition at line 16 of file McpPerformanceCacheService.java.
Referenced by com.gmp.qms.service.McpPerformanceCacheService.clear(), com.gmp.qms.service.McpPerformanceCacheService.get(), com.gmp.qms.service.McpPerformanceCacheService.getCache(), com.gmp.qms.service.McpPerformanceCacheService.put(), and com.gmp.qms.service.McpPerformanceCacheService.size().
log
final Logger com.gmp.qms.service.McpPerformanceCacheService.log = LoggerFactory.getLogger(McpPerformanceCacheService.class) static private
Definition at line 15 of file McpPerformanceCacheService.java.
Referenced by com.gmp.qms.service.McpPerformanceCacheService.clear(), com.gmp.qms.service.McpPerformanceCacheService.get(), and com.gmp.qms.service.McpPerformanceCacheService.put().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/McpPerformanceCacheService.java