GMP系统: com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus Class Reference
com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus Class Reference
Public Member Functions
String getOverallStatus ()
void setOverallStatus (String overallStatus)
int getActiveConnections ()
void setActiveConnections (int activeConnections)
double getErrorRate ()
void setErrorRate (double errorRate)
long getServiceUptime ()
void setServiceUptime (long serviceUptime)
Private Attributes
String overallStatus
int activeConnections
double errorRate
long serviceUptime
Detailed Description
Definition at line 312 of file McpMonitoringService.java.
Member Function Documentation
getActiveConnections()
int com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getActiveConnections ()
Definition at line 321 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.activeConnections.
getErrorRate()
double com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getErrorRate ()
Definition at line 323 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.errorRate.
getOverallStatus()
String com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getOverallStatus ()
Definition at line 319 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.overallStatus.
getServiceUptime()
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getServiceUptime ()
Definition at line 325 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.serviceUptime.
setActiveConnections()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setActiveConnections (int activeConnections)
Definition at line 322 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.activeConnections.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
setErrorRate()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setErrorRate (double errorRate)
Definition at line 324 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.errorRate.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
setOverallStatus()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setOverallStatus (String overallStatus)
Definition at line 320 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.overallStatus.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
setServiceUptime()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setServiceUptime (long serviceUptime)
Definition at line 326 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.serviceUptime.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemHealthStatus().
Member Data Documentation
activeConnections
int com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.activeConnections private
Definition at line 314 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getActiveConnections(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setActiveConnections().
errorRate
double com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.errorRate private
Definition at line 315 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getErrorRate(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setErrorRate().
overallStatus
String com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.overallStatus private
Definition at line 313 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getOverallStatus(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setOverallStatus().
serviceUptime
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.serviceUptime private
Definition at line 316 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.getServiceUptime(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemHealthStatus.setServiceUptime().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpMonitoringService.java