GMP系统: com.gmp.auth.entity.OrganizationTest Class Reference
com.gmp.auth.entity.OrganizationTest Class Reference
测试Why-What-How注释:
Package Functions
void testOrganizationCreation ()
void testOrganizationTypeEnum ()
void testOrganizationStatusEnum ()
void testIsActive ()
void testGetFullPathWithParent ()
void testGetFullPathWithoutParent ()
void testIsGmpOrganization ()
void testGetResponsibleManager ()
void testOrganizationHierarchy ()
void testAuditFields ()
void testOrganizationValidation ()
void testGmpCompliance ()
void testOrganizationBuilderDefaultValues ()
void testNestedOrganizationHierarchy ()
Detailed Description
测试Why-What-How注释:
WHY: GMP企业组织架构是多组织多角色权限管控的基础，必须确保组织实体的准确性和 业务逻辑的正确性，因为组织架构变化会影响所有用户的权限计算，任何错误都可能 导致系统级别的安全问题，需要严格验证所有业务规则。
WHAT: OrganizationEntityTest完整测试组织实体的所有功能：组织类型枚举、层级关系、 GMP合规性判断、状态控制、业务规则验证，确保组织管理的核心功能在各种情况下 都能正确工作，支撑多组织架构的权限管控需求。
HOW: 使用JUnit 5 + AssertJ框架实现TDD测试模式，通过构建器模式创建测试数据， 覆盖正常流程、边界条件、异常场景，通过断言验证预期结果，确保测试的可靠性。
Definition at line 25 of file OrganizationTest.java.
Member Function Documentation
testAuditFields()
void com.gmp.auth.entity.OrganizationTest.testAuditFields () package
Definition at line 231 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.createdAt.
testGetFullPathWithoutParent()
void com.gmp.auth.entity.OrganizationTest.testGetFullPathWithoutParent () package
Definition at line 122 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.getFullPath(), and com.gmp.auth.entity.Organization.orgName.
testGetFullPathWithParent()
void com.gmp.auth.entity.OrganizationTest.testGetFullPathWithParent () package
Definition at line 105 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.getFullPath(), and com.gmp.auth.entity.Organization.orgName.
testGetResponsibleManager()
void com.gmp.auth.entity.OrganizationTest.testGetResponsibleManager () package
Definition at line 171 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.getResponsibleManager(), and com.gmp.auth.entity.Organization.manager.
testGmpCompliance()
void com.gmp.auth.entity.OrganizationTest.testGmpCompliance () package
Definition at line 268 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationType.DEPARTMENT, com.gmp.auth.entity.Organization.getResponsibleManager(), com.gmp.auth.entity.Organization.isGmpOrganization(), com.gmp.auth.entity.Organization.orgName, and com.gmp.auth.entity.Organization.OrganizationType.QUALITY.
testIsActive()
void com.gmp.auth.entity.OrganizationTest.testIsActive () package
Definition at line 84 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationStatus.ACTIVE, com.gmp.auth.entity.Organization.OrganizationStatus.ARCHIVED, com.gmp.auth.entity.Organization.OrganizationStatus.INACTIVE, com.gmp.auth.entity.Organization.isActive(), and com.gmp.auth.entity.Organization.orgStatus.
testIsGmpOrganization()
void com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization () package
Definition at line 133 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationType.COMPLIANCE, com.gmp.auth.entity.Organization.OrganizationType.DEPARTMENT, com.gmp.auth.entity.Organization.OrganizationType.HR, com.gmp.auth.entity.Organization.isGmpOrganization(), com.gmp.auth.entity.Organization.orgType, com.gmp.auth.entity.Organization.OrganizationType.PRODUCTION, com.gmp.auth.entity.Organization.OrganizationType.QUALITY, and com.gmp.auth.entity.Organization.OrganizationType.TRAINING.
testNestedOrganizationHierarchy()
void com.gmp.auth.entity.OrganizationTest.testNestedOrganizationHierarchy () package
Definition at line 310 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.getFullPath(), and com.gmp.auth.entity.Organization.orgCode.
testOrganizationBuilderDefaultValues()
void com.gmp.auth.entity.OrganizationTest.testOrganizationBuilderDefaultValues () package
Definition at line 295 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationStatus.ACTIVE, and com.gmp.auth.entity.Organization.orgCode.
testOrganizationCreation()
void com.gmp.auth.entity.OrganizationTest.testOrganizationCreation () package
Definition at line 28 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationStatus.ACTIVE, com.gmp.auth.entity.Organization.OrganizationType.DEPARTMENT, com.gmp.auth.entity.Organization.isActive(), and com.gmp.auth.entity.Organization.orgCode.
testOrganizationHierarchy()
void com.gmp.auth.entity.OrganizationTest.testOrganizationHierarchy () package
Definition at line 194 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.getFullPath(), and com.gmp.auth.entity.Organization.orgCode.
testOrganizationStatusEnum()
void com.gmp.auth.entity.OrganizationTest.testOrganizationStatusEnum () package
Definition at line 69 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationStatus.ACTIVE, and com.gmp.auth.entity.Organization.OrganizationStatus.ARCHIVED.
testOrganizationTypeEnum()
void com.gmp.auth.entity.OrganizationTest.testOrganizationTypeEnum () package
Definition at line 51 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.OrganizationType.DEPARTMENT, com.gmp.auth.entity.Organization.OrganizationType.PRODUCTION, and com.gmp.auth.entity.Organization.OrganizationType.QUALITY.
testOrganizationValidation()
void com.gmp.auth.entity.OrganizationTest.testOrganizationValidation () package
Definition at line 252 of file OrganizationTest.java.
References com.gmp.auth.entity.Organization.orgCode.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/OrganizationTest.java