GMP系统: com.gmp.equipment.entity.EquipmentTest Class Reference
com.gmp.equipment.entity.EquipmentTest Class Reference
测试Why-What-How注释:
Package Functions
void testEquipmentCreation ()
void testEquipmentStatusEnum ()
void testOperationalStatusEnum ()
void testIsRunnable ()
void testIsMaintenanceDue ()
void testIsCalibrationOverdue ()
void testIsUnderWarranty ()
void testGetUsageYears ()
void testAuditFields ()
void testEquipmentValidation ()
void testCriticalEquipmentManagement ()
void testEquipmentMonitoring ()
void testEquipmentLifecycleManagement ()
Detailed Description
测试Why-What-How注释:
WHY: GMP设备管理系统是制药生产的核心基础设施，必须确保设备台账数据的准确性、 状态管理的可靠性以及业务规则验证的正确性，因为任何数据错误都可能导致 生产中断和质量问题的发生，而GMP合规性要求我们必须验证所有核心业务逻辑。
WHAT: EquipmentEntityTest完整测试设备实体的所有业务逻辑：设备状态转换、 业务规则验证、枚举类型正确性、审计字段处理、性能计算方法，确保设备 管理的核心功能在各种边界条件下都能正确工作。
HOW: 使用JUnit 5 + AssertJ框架实现TDD测试模式，通过构建器模式创建测试数据， 覆盖Given-When-Then测试场景，包含正常流程、边界条件、异常情况和并发安全的验证。
Definition at line 26 of file EquipmentTest.java.
Member Function Documentation
testAuditFields()
void com.gmp.equipment.entity.EquipmentTest.testAuditFields () package
Definition at line 222 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.createdAt.
testCriticalEquipmentManagement()
void com.gmp.equipment.entity.EquipmentTest.testCriticalEquipmentManagement () package
Definition at line 263 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE, and com.gmp.equipment.entity.Equipment.equipmentName.
testEquipmentCreation()
void com.gmp.equipment.entity.EquipmentTest.testEquipmentCreation () package
Definition at line 29 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE, com.gmp.equipment.entity.Equipment.equipmentCode, and com.gmp.equipment.entity.Equipment.OperationalStatus.STOPPED.
testEquipmentLifecycleManagement()
void com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement () package
Definition at line 318 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE, com.gmp.equipment.entity.Equipment.EquipmentStatus.DECOMMISSIONED, com.gmp.equipment.entity.Equipment.equipmentStatus, com.gmp.equipment.entity.Equipment.EquipmentStatus.INACTIVE, com.gmp.equipment.entity.Equipment.isRunnable(), com.gmp.equipment.entity.Equipment.EquipmentStatus.MAINTENANCE, and com.gmp.equipment.entity.Equipment.OperationalStatus.STOPPED.
testEquipmentMonitoring()
void com.gmp.equipment.entity.EquipmentTest.testEquipmentMonitoring () package
Definition at line 293 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.monitoringEnabled, and com.gmp.equipment.entity.Equipment.sensorId.
testEquipmentStatusEnum()
void com.gmp.equipment.entity.EquipmentTest.testEquipmentStatusEnum () package
Definition at line 54 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE, com.gmp.equipment.entity.Equipment.EquipmentStatus.DECOMMISSIONED, and com.gmp.equipment.entity.Equipment.EquipmentStatus.MAINTENANCE.
testEquipmentValidation()
void com.gmp.equipment.entity.EquipmentTest.testEquipmentValidation () package
Definition at line 243 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.equipmentCode.
testGetUsageYears()
void com.gmp.equipment.entity.EquipmentTest.testGetUsageYears () package
Definition at line 195 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.commissioningDate, and com.gmp.equipment.entity.Equipment.getUsageYears().
testIsCalibrationOverdue()
void com.gmp.equipment.entity.EquipmentTest.testIsCalibrationOverdue () package
Definition at line 149 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.isCalibrationOverdue(), and com.gmp.equipment.entity.Equipment.nextCalibrationDate.
testIsMaintenanceDue()
void com.gmp.equipment.entity.EquipmentTest.testIsMaintenanceDue () package
Definition at line 120 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.isMaintenanceDue(), and com.gmp.equipment.entity.Equipment.nextMaintenanceDate.
testIsRunnable()
void com.gmp.equipment.entity.EquipmentTest.testIsRunnable () package
Definition at line 87 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE, com.gmp.equipment.entity.Equipment.equipmentStatus, com.gmp.equipment.entity.Equipment.isRunnable(), com.gmp.equipment.entity.Equipment.EquipmentStatus.MAINTENANCE, com.gmp.equipment.entity.Equipment.OperationalStatus.RUNNING, com.gmp.equipment.entity.Equipment.OperationalStatus.STANDBY, and com.gmp.equipment.entity.Equipment.OperationalStatus.STOPPED.
testIsUnderWarranty()
void com.gmp.equipment.entity.EquipmentTest.testIsUnderWarranty () package
Definition at line 172 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.isUnderWarranty(), and com.gmp.equipment.entity.Equipment.warrantyExpiry.
testOperationalStatusEnum()
void com.gmp.equipment.entity.EquipmentTest.testOperationalStatusEnum () package
Definition at line 72 of file EquipmentTest.java.
References com.gmp.equipment.entity.Equipment.OperationalStatus.FAULT, and com.gmp.equipment.entity.Equipment.OperationalStatus.RUNNING.
The documentation for this class was generated from the following file:
equipment-management/src/test/java/com/gmp/equipment/entity/EquipmentTest.java