GMP系统: com.gmp.qms.monitoring.McpMonitoringService Class Reference
com.gmp.qms.monitoring.McpMonitoringService Class Reference
MCP监控服务，用于收集和管理MCP调用的性能指标
Classes
class McpTimer
MCP计时对象
class ResourceMetrics
资源访问指标
class SystemMetrics
系统整体指标
class ToolMetrics
工具调用指标
Public Member Functions
McpTimer startToolCall (String toolName)
记录工具调用开始
McpTimer startResourceAccess (String resourceName)
记录资源访问开始
void endCall (McpTimer timer, boolean success)
记录工具调用结束
ToolMetrics getToolMetrics (String toolName)
获取工具调用指标
ResourceMetrics getResourceMetrics (String resourceName)
获取资源访问指标
SystemMetrics getSystemMetrics ()
获取系统整体指标
void resetMetrics ()
清除所有指标
Private Attributes
final ConcurrentHashMap< String, ToolMetrics > toolMetrics = new ConcurrentHashMap<>()
工具调用统计信息
final ConcurrentHashMap< String, ResourceMetrics > resourceMetrics = new ConcurrentHashMap<>()
资源访问统计信息
final SystemMetrics systemMetrics = new SystemMetrics()
系统整体MCP调用统计
Detailed Description
MCP监控服务，用于收集和管理MCP调用的性能指标
Author
GMP系统开发团队
Definition at line 16 of file McpMonitoringService.java.
Member Function Documentation
endCall()
void com.gmp.qms.monitoring.McpMonitoringService.endCall (McpTimer timer, boolean success)
记录工具调用结束
Parameters
timer 计时对象
success 是否成功
Definition at line 63 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementFailedCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementSuccessCalls(), com.gmp.qms.monitoring.McpMonitoringService.McpTimer.isResourceAccess, com.gmp.qms.monitoring.McpMonitoringService.McpTimer.name, com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration(), com.gmp.qms.monitoring.McpMonitoringService.resourceMetrics, com.gmp.qms.monitoring.McpMonitoringService.McpTimer.stop(), com.gmp.qms.monitoring.McpMonitoringService.systemMetrics, and com.gmp.qms.monitoring.McpMonitoringService.toolMetrics.
getResourceMetrics()
ResourceMetrics com.gmp.qms.monitoring.McpMonitoringService.getResourceMetrics (String resourceName)
获取资源访问指标
Parameters
resourceName 资源名称
Returns
资源指标
Definition at line 113 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.resourceMetrics.
getSystemMetrics()
SystemMetrics com.gmp.qms.monitoring.McpMonitoringService.getSystemMetrics ()
获取系统整体指标
Returns
系统指标
Definition at line 122 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.systemMetrics.
getToolMetrics()
ToolMetrics com.gmp.qms.monitoring.McpMonitoringService.getToolMetrics (String toolName)
获取工具调用指标
Parameters
toolName 工具名称
Returns
工具指标
Definition at line 103 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.toolMetrics.
resetMetrics()
void com.gmp.qms.monitoring.McpMonitoringService.resetMetrics ()
清除所有指标
Definition at line 129 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset(), com.gmp.qms.monitoring.McpMonitoringService.resourceMetrics, com.gmp.qms.monitoring.McpMonitoringService.systemMetrics, and com.gmp.qms.monitoring.McpMonitoringService.toolMetrics.
startResourceAccess()
McpTimer com.gmp.qms.monitoring.McpMonitoringService.startResourceAccess (String resourceName)
记录资源访问开始
Parameters
resourceName 资源名称
Returns
计时对象
Definition at line 51 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls(), com.gmp.qms.monitoring.McpMonitoringService.resourceMetrics, and com.gmp.qms.monitoring.McpMonitoringService.systemMetrics.
startToolCall()
McpTimer com.gmp.qms.monitoring.McpMonitoringService.startToolCall (String toolName)
记录工具调用开始
Parameters
toolName 工具名称
Returns
计时对象
Definition at line 39 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls(), com.gmp.qms.monitoring.McpMonitoringService.systemMetrics, and com.gmp.qms.monitoring.McpMonitoringService.toolMetrics.
Member Data Documentation
resourceMetrics
final ConcurrentHashMap<String, ResourceMetrics> com.gmp.qms.monitoring.McpMonitoringService.resourceMetrics = new ConcurrentHashMap<>() private
资源访问统计信息
Definition at line 26 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall(), com.gmp.qms.monitoring.McpMonitoringService.getResourceMetrics(), com.gmp.qms.monitoring.McpMonitoringService.resetMetrics(), and com.gmp.qms.monitoring.McpMonitoringService.startResourceAccess().
systemMetrics
final SystemMetrics com.gmp.qms.monitoring.McpMonitoringService.systemMetrics = new SystemMetrics() private
系统整体MCP调用统计
Definition at line 31 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall(), com.gmp.qms.monitoring.McpMonitoringService.getSystemMetrics(), com.gmp.qms.monitoring.McpMonitoringService.resetMetrics(), com.gmp.qms.monitoring.McpMonitoringService.startResourceAccess(), and com.gmp.qms.monitoring.McpMonitoringService.startToolCall().
toolMetrics
final ConcurrentHashMap<String, ToolMetrics> com.gmp.qms.monitoring.McpMonitoringService.toolMetrics = new ConcurrentHashMap<>() private
工具调用统计信息
Definition at line 21 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall(), com.gmp.qms.monitoring.McpMonitoringService.getToolMetrics(), com.gmp.qms.monitoring.McpMonitoringService.resetMetrics(), and com.gmp.qms.monitoring.McpMonitoringService.startToolCall().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/monitoring/McpMonitoringService.java