GMP系统: com.gmp.training.service.impl.TrainingSessionServiceImpl Class Reference
com.gmp.training.service.impl.TrainingSessionServiceImpl Class Reference
培训场次服务实现类
Public Member Functions
TrainingSession findById (Long id)
根据ID查找培训场次
TrainingSession save (TrainingSession trainingSession)
保存培训场次
void delete (Long id)
删除培训场次
Page< TrainingSession > findAll (Pageable pageable)
查找所有培训场次
Page< TrainingSession > findByCourseId (Long courseId, Pageable pageable)
根据课程ID查找培训场次（带分页）
Page< TrainingSession > findByLecturerId (Long lecturerId, Pageable pageable)
根据讲师ID查找培训场次（带分页）
List< TrainingSession > findByStatus (TrainingSession.Status status)
根据状态查找培训场次
Page< TrainingSession > findByStatus (TrainingSession.Status status, Pageable pageable)
根据状态查找培训场次（带分页）
List< TrainingSession > findByStartTimeBetween (LocalDateTime startDate, LocalDateTime endDate)
根据时间范围查找培训场次
Page< TrainingSession > findByMethod (TrainingSession.Method method, Pageable pageable)
根据培训方式查找培训场次（带分页）
Page< TrainingSession > findByVenue (String venue, Pageable pageable)
根据培训地点查找培训场次（带分页）
Page< TrainingSession > findBySessionDateBetween (LocalDate startDate, LocalDate endDate, Pageable pageable)
根据场次日期范围查找培训场次（带分页）
Page< TrainingSession > findFutureSessions (Pageable pageable)
查找未来的培训场次（带分页）
Page< TrainingSession > findCompletedSessions (Pageable pageable)
查找已完成的培训场次（带分页）
Page< TrainingSession > findOngoingSessions (Pageable pageable)
查找进行中的培训场次（带分页）
TrainingSession updateStatus (Long id, TrainingSession.Status status)
更新培训场次状态
int batchUpdateStatus (List< Long > ids, TrainingSession.Status status)
批量更新培训场次状态
Page< TrainingSession > search (String keyword, Pageable pageable)
搜索培训场次（带分页）
int getActualAttendance (Long sessionId)
获取实际出席人数
double getAttendanceRate (Long sessionId)
获取出席率
Private Attributes
TrainingSessionRepository repository
Detailed Description
培训场次服务实现类
Author
GMP系统开发团队
Definition at line 24 of file TrainingSessionServiceImpl.java.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingSessionServiceImpl.batchUpdateStatus (List< Long > ids, TrainingSession.Status status)
批量更新培训场次状态
Parameters
ids 培训场次ID列表
status 新状态
Returns
更新数量
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 129 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.updateStatus().
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testBatchUpdateStatus().
delete()
void com.gmp.training.service.impl.TrainingSessionServiceImpl.delete (Long id)
删除培训场次
Parameters
id 培训场次ID
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 41 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testDelete().
findAll()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findAll (Pageable pageable)
查找所有培训场次
Parameters
pageable 分页参数
Returns
培训场次列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 47 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindAll().
findByCourseId()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByCourseId (Long courseId, Pageable pageable)
根据课程ID查找培训场次（带分页）
Parameters
courseId 课程ID
pageable 分页参数
Returns
培训场次列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 53 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByCourseId().
findById()
TrainingSession com.gmp.training.service.impl.TrainingSessionServiceImpl.findById (Long id)
根据ID查找培训场次
Parameters
id 培训场次ID
Returns
培训场次信息
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 31 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindById().
findByLecturerId()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByLecturerId (Long lecturerId, Pageable pageable)
根据讲师ID查找培训场次（带分页）
Parameters
lecturerId 讲师ID
pageable 分页参数
Returns
培训场次列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 59 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findByMethod()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByMethod (TrainingSession.Method method, Pageable pageable)
根据培训方式查找培训场次（带分页）
Parameters
method 培训方式
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 83 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findBySessionDateBetween()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findBySessionDateBetween (LocalDate startDate, LocalDate endDate, Pageable pageable)
根据场次日期范围查找培训场次（带分页）
Parameters
startDate 开始日期
endDate 结束日期
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 95 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findByStartTimeBetween()
List< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStartTimeBetween (LocalDateTime startDate, LocalDateTime endDate)
根据时间范围查找培训场次
Parameters
startDate 开始时间
endDate 结束时间
Returns
培训场次列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 77 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findByStatus() [1/2]
List< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStatus (TrainingSession.Status status)
根据状态查找培训场次
Parameters
status 状态
Returns
培训场次列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 65 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindByStatus().
findByStatus() [2/2]
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStatus (TrainingSession.Status status, Pageable pageable)
根据状态查找培训场次（带分页）
Parameters
status 培训场次状态
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 71 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findByVenue()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findByVenue (String venue, Pageable pageable)
根据培训地点查找培训场次（带分页）
Parameters
venue 培训地点
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 89 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
findCompletedSessions()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findCompletedSessions (Pageable pageable)
查找已完成的培训场次（带分页）
Parameters
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 107 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindCompletedSessions().
findFutureSessions()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findFutureSessions (Pageable pageable)
查找未来的培训场次（带分页）
Parameters
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 101 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindFutureSessions().
findOngoingSessions()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.findOngoingSessions (Pageable pageable)
查找进行中的培训场次（带分页）
Parameters
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 113 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testFindOngoingSessions().
getActualAttendance()
int com.gmp.training.service.impl.TrainingSessionServiceImpl.getActualAttendance (Long sessionId)
获取实际出席人数
Parameters
sessionId 培训场次ID
Returns
实际出席人数
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 155 of file TrainingSessionServiceImpl.java.
getAttendanceRate()
double com.gmp.training.service.impl.TrainingSessionServiceImpl.getAttendanceRate (Long sessionId)
获取出席率
Parameters
sessionId 培训场次ID
Returns
出席率（百分比）
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 162 of file TrainingSessionServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testGetAttendanceRate().
save()
TrainingSession com.gmp.training.service.impl.TrainingSessionServiceImpl.save (TrainingSession trainingSession)
保存培训场次
Parameters
trainingSession 培训场次
Returns
保存后的培训场次
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 36 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testSave().
search()
Page< TrainingSession > com.gmp.training.service.impl.TrainingSessionServiceImpl.search (String keyword, Pageable pageable)
搜索培训场次（带分页）
Parameters
keyword 搜索关键词
pageable 分页参数
Returns
培训场次分页列表
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 146 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImplTest.testSearch().
updateStatus()
TrainingSession com.gmp.training.service.impl.TrainingSessionServiceImpl.updateStatus (Long id, TrainingSession.Status status)
更新培训场次状态
Parameters
id 培训场次ID
status 新状态
Returns
更新后的培训场次
Implements com.gmp.training.service.TrainingSessionService.
Definition at line 118 of file TrainingSessionServiceImpl.java.
References com.gmp.training.service.impl.TrainingSessionServiceImpl.repository.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImpl.batchUpdateStatus(), and com.gmp.training.service.impl.TrainingSessionServiceImplTest.testUpdateStatus().
Member Data Documentation
repository
TrainingSessionRepository com.gmp.training.service.impl.TrainingSessionServiceImpl.repository private
Definition at line 27 of file TrainingSessionServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingSessionServiceImpl.delete(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findAll(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByCourseId(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findById(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByLecturerId(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByMethod(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findBySessionDateBetween(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStartTimeBetween(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStatus(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByStatus(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findByVenue(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findCompletedSessions(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findFutureSessions(), com.gmp.training.service.impl.TrainingSessionServiceImpl.findOngoingSessions(), com.gmp.training.service.impl.TrainingSessionServiceImpl.save(), com.gmp.training.service.impl.TrainingSessionServiceImpl.search(), and com.gmp.training.service.impl.TrainingSessionServiceImpl.updateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingSessionServiceImpl.java