GMP系统: com.gmp.auth.service.impl.AuthServiceImplTest Class Reference
com.gmp.auth.service.impl.AuthServiceImplTest Class Reference
AuthServiceImpl的单元测试类
Package Functions
void setUp ()
void testLoadUserByUsername_Success ()
void testLoadUserByUsername_UserNotFound ()
void testLoadUserByUsername_AccountDisabled ()
void testLogin_Success ()
void testLogin_InvalidPassword ()
void testLogin_AccountLockedAfterFailedAttempts ()
void testLogin_MfaRequired ()
void testHasPermission_UserHasRequiredPermission ()
void testHasPermission_UserDoesNotHaveRequiredPermission ()
void testHasRole_UserHasRequiredRole ()
void testHasRole_UserDoesNotHaveRequiredRole ()
void testChangePassword_Success ()
void testChangePassword_InvalidOldPassword ()
void testChangePassword_InvalidNewPassword ()
void testVerifyMfa_Success ()
void testVerifyMfa_InvalidSession ()
void testLogout ()
void testResetPassword_Success ()
void testRegenerateRecoveryCodes ()
void testRegenerateRecoveryCodes_MfaNotEnabled ()
void testHasSubsystemAccess_ReadAccess ()
void testHasSubsystemAccess_NoAccess ()
void testHasSubsystemWriteAccess_HasWriteAccess ()
void testHasSubsystemWriteAccess_NoWriteAccess ()
void testHasSubsystemWriteAccess_AdminAccess ()
void testChangePassword_PasswordInHistory ()
void testHasSubsystemAdminAccess_WithAdminAccess ()
void testHasSubsystemAdminAccess_WithoutAdminAccess ()
void testGetSubsystemAccessLevel ()
void testValidateToken_ExpiredToken ()
void testValidateToken_BlacklistedToken ()
Private Attributes
UserRepository userRepository
UserPasswordHistoryService userPasswordHistoryService
UserRoleService userRoleService
RolePermissionService rolePermissionService
PasswordEncoder passwordEncoder
PasswordPolicyService passwordPolicyService
AuditLogService auditLogService
AuthenticationManager authenticationManager
UserOrganizationRoleService userOrganizationRoleService
TokenBlacklistService tokenBlacklistService
JwtUtil jwtUtil
JwtProperties jwtProperties
AuthServiceImpl authService
User testUser
Detailed Description
AuthServiceImpl的单元测试类
Author
GMP系统开发团队
Definition at line 37 of file AuthServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.service.impl.AuthServiceImplTest.setUp () package
Definition at line 81 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authenticationManager, com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations(), com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesAcrossOrganizations(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userOrganizationRoleService, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testChangePassword_InvalidNewPassword()
void com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword () package
Definition at line 441 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.passwordPolicyService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.PasswordPolicyService.validatePassword().
testChangePassword_InvalidOldPassword()
void com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword () package
Definition at line 415 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testChangePassword_PasswordInHistory()
void com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory () package
Definition at line 655 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.UserPasswordHistoryService.isPasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.passwordPolicyService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userPasswordHistoryService, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.PasswordPolicyService.validatePassword().
testChangePassword_Success()
void com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success () package
Definition at line 382 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.changePassword(), com.gmp.auth.service.UserPasswordHistoryService.isPasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.passwordPolicyService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userPasswordHistoryService, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.PasswordPolicyService.validatePassword().
testGetSubsystemAccessLevel()
void com.gmp.auth.service.impl.AuthServiceImplTest.testGetSubsystemAccessLevel () package
Definition at line 709 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), and com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels().
testHasPermission_UserDoesNotHaveRequiredPermission()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission () package
Definition at line 340 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.RolePermissionService.hasAnyPermission(), com.gmp.auth.service.impl.AuthServiceImpl.hasPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testHasPermission_UserHasRequiredPermission()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission () package
Definition at line 327 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.RolePermissionService.hasAnyPermission(), com.gmp.auth.service.impl.AuthServiceImpl.hasPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testHasRole_UserDoesNotHaveRequiredRole()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole () package
Definition at line 369 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService.
testHasRole_UserHasRequiredRole()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole () package
Definition at line 356 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService.
testHasSubsystemAccess_NoAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_NoAccess () package
Definition at line 597 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess().
testHasSubsystemAccess_ReadAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_ReadAccess () package
Definition at line 580 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAccess().
testHasSubsystemAdminAccess_WithAdminAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithAdminAccess () package
Definition at line 683 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess().
testHasSubsystemAdminAccess_WithoutAdminAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithoutAdminAccess () package
Definition at line 696 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemAdminAccess().
testHasSubsystemWriteAccess_AdminAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_AdminAccess () package
Definition at line 640 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess().
testHasSubsystemWriteAccess_HasWriteAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_HasWriteAccess () package
Definition at line 610 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess().
testHasSubsystemWriteAccess_NoWriteAccess()
void com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_NoWriteAccess () package
Definition at line 627 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels(), and com.gmp.auth.service.impl.AuthServiceImpl.hasSubsystemWriteAccess().
testLoadUserByUsername_AccountDisabled()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_AccountDisabled () package
Definition at line 148 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testLoadUserByUsername_Success()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success () package
Definition at line 118 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.RolePermissionService.getUserPermissionCodes(), com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername(), com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService.
testLoadUserByUsername_UserNotFound()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_UserNotFound () package
Definition at line 137 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.loadUserByUsername(), and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testLogin_AccountLockedAfterFailedAttempts()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts () package
Definition at line 241 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testLogin_InvalidPassword()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword () package
Definition at line 203 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testLogin_MfaRequired()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired () package
Definition at line 281 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testLogin_Success()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success () package
Definition at line 160 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.RolePermissionService.getUserPermissionCodes(), com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.UserOrganizationRoleService.getUserRoleCodesInOrganization(), com.gmp.auth.service.impl.AuthServiceImplTest.jwtProperties, com.gmp.auth.service.impl.AuthServiceImplTest.jwtUtil, com.gmp.auth.service.impl.AuthServiceImpl.login(), com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userOrganizationRoleService, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService.
testLogout()
void com.gmp.auth.service.impl.AuthServiceImplTest.testLogout () package
Definition at line 525 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, and com.gmp.auth.service.impl.AuthServiceImpl.logout().
testRegenerateRecoveryCodes()
void com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes () package
Definition at line 551 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testRegenerateRecoveryCodes_MfaNotEnabled()
void com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes_MfaNotEnabled () package
Definition at line 569 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImpl.regenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, and com.gmp.auth.service.impl.AuthServiceImplTest.userRepository.
testResetPassword_Success()
void com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success () package
Definition at line 534 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder, com.gmp.auth.service.impl.AuthServiceImplTest.passwordPolicyService, com.gmp.auth.service.impl.AuthServiceImpl.resetPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userPasswordHistoryService, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.PasswordPolicyService.validatePassword().
testValidateToken_BlacklistedToken()
void com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_BlacklistedToken () package
Definition at line 736 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.TokenBlacklistService.isTokenBlacklisted(), com.gmp.auth.service.impl.AuthServiceImplTest.tokenBlacklistService, and com.gmp.auth.service.impl.AuthServiceImpl.validateToken().
testValidateToken_ExpiredToken()
void com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_ExpiredToken () package
Definition at line 726 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, and com.gmp.auth.service.impl.AuthServiceImpl.validateToken().
testVerifyMfa_InvalidSession()
void com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_InvalidSession () package
Definition at line 502 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
testVerifyMfa_Success()
void com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success () package
Definition at line 468 of file AuthServiceImplTest.java.
References com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService, com.gmp.auth.service.impl.AuthServiceImplTest.authService, com.gmp.auth.service.RolePermissionService.getUserPermissionCodes(), com.gmp.auth.service.UserRoleService.getUserRoleCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.jwtProperties, com.gmp.auth.service.impl.AuthServiceImplTest.jwtUtil, com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService, com.gmp.auth.service.impl.AuthServiceImplTest.testUser, com.gmp.auth.service.impl.AuthServiceImplTest.userRepository, com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService, and com.gmp.auth.service.impl.AuthServiceImpl.verifyMfa().
Member Data Documentation
auditLogService
AuditLogService com.gmp.auth.service.impl.AuthServiceImplTest.auditLogService private
Definition at line 58 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogout(), com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
authenticationManager
AuthenticationManager com.gmp.auth.service.impl.AuthServiceImplTest.authenticationManager private
Definition at line 61 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.setUp().
authService
AuthServiceImpl com.gmp.auth.service.impl.AuthServiceImplTest.authService private
Definition at line 76 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testGetSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_NoAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAccess_ReadAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithAdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemAdminAccess_WithoutAdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_AdminAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_HasWriteAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasSubsystemWriteAccess_NoWriteAccess(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_AccountDisabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_UserNotFound(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogout(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes_MfaNotEnabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_BlacklistedToken(), com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_ExpiredToken(), com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_InvalidSession(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
jwtProperties
JwtProperties com.gmp.auth.service.impl.AuthServiceImplTest.jwtProperties private
Definition at line 73 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
jwtUtil
JwtUtil com.gmp.auth.service.impl.AuthServiceImplTest.jwtUtil private
Definition at line 70 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
passwordEncoder
PasswordEncoder com.gmp.auth.service.impl.AuthServiceImplTest.passwordEncoder private
Definition at line 52 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.setUp(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes(), and com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success().
passwordPolicyService
PasswordPolicyService com.gmp.auth.service.impl.AuthServiceImplTest.passwordPolicyService private
Definition at line 55 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success().
rolePermissionService
RolePermissionService com.gmp.auth.service.impl.AuthServiceImplTest.rolePermissionService private
Definition at line 49 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
testUser
User com.gmp.auth.service.impl.AuthServiceImplTest.testUser private
Definition at line 78 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.setUp(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_AccountDisabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes_MfaNotEnabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_InvalidSession(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
tokenBlacklistService
TokenBlacklistService com.gmp.auth.service.impl.AuthServiceImplTest.tokenBlacklistService private
Definition at line 67 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_BlacklistedToken().
userOrganizationRoleService
UserOrganizationRoleService com.gmp.auth.service.impl.AuthServiceImplTest.userOrganizationRoleService private
Definition at line 64 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.setUp(), and com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success().
userPasswordHistoryService
UserPasswordHistoryService com.gmp.auth.service.impl.AuthServiceImplTest.userPasswordHistoryService private
Definition at line 43 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success().
userRepository
UserRepository com.gmp.auth.service.impl.AuthServiceImplTest.userRepository private
Definition at line 40 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.setUp(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidNewPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_InvalidOldPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_PasswordInHistory(), com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_AccountDisabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_UserNotFound(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_AccountLockedAfterFailedAttempts(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_InvalidPassword(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_MfaRequired(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes(), com.gmp.auth.service.impl.AuthServiceImplTest.testRegenerateRecoveryCodes_MfaNotEnabled(), com.gmp.auth.service.impl.AuthServiceImplTest.testResetPassword_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_InvalidSession(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
userRoleService
UserRoleService com.gmp.auth.service.impl.AuthServiceImplTest.userRoleService private
Definition at line 46 of file AuthServiceImplTest.java.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/impl/AuthServiceImplTest.java