GMP系统: com.gmp.auth.test.AuthSystemTestScript Class Reference
com.gmp.auth.test.AuthSystemTestScript Class Reference
GMP系统认证测试脚本
Public Member Functions
void initializeTestData ()
void testOrganizationInitialization ()
void testRolePermissionInitialization ()
void testUserInitialization ()
void testUserOrganizationRoleAssociation ()
void testFindUserRolesByUserId ()
void testUserLogin ()
void testUserPermissionDifferences ()
void runAllTests ()
boolean hasPermission (String username, String permissionCode)
Private Member Functions
Authentication testLogin (String username, String password, boolean expectedSuccess)
Private Attributes
final OrganizationStructureInitializer organizationInitializer
final RolePermissionInitializer rolePermissionInitializer
final UserInitializer userInitializer
final UserRepository userRepository
final RoleRepository roleRepository
final PermissionRepository permissionRepository
final UserOrganizationRoleRepository userOrganizationRoleRepository
final AuthenticationManager authenticationManager
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(AuthSystemTestScript.class)
Detailed Description
GMP系统认证测试脚本
Definition at line 32 of file AuthSystemTestScript.java.
Member Function Documentation
hasPermission()
boolean com.gmp.auth.test.AuthSystemTestScript.hasPermission (String username, String permissionCode)
Definition at line 203 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.testLogin().
initializeTestData()
void com.gmp.auth.test.AuthSystemTestScript.initializeTestData ()
Definition at line 44 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.userInitializer.
Referenced by com.gmp.auth.test.AuthSystemTestScript.runAllTests().
runAllTests()
void com.gmp.auth.test.AuthSystemTestScript.runAllTests ()
Definition at line 184 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.initializeTestData(), com.gmp.auth.test.AuthSystemTestScript.log, com.gmp.auth.test.AuthSystemTestScript.testOrganizationInitialization(), com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserLogin(), com.gmp.auth.test.AuthSystemTestScript.testUserOrganizationRoleAssociation(), and com.gmp.auth.test.AuthSystemTestScript.testUserPermissionDifferences().
testFindUserRolesByUserId()
void com.gmp.auth.test.AuthSystemTestScript.testFindUserRolesByUserId ()
Definition at line 113 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log.
testLogin()
Authentication com.gmp.auth.test.AuthSystemTestScript.testLogin (String username, String password, boolean expectedSuccess) private
Definition at line 135 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.authenticationManager, and com.gmp.auth.test.AuthSystemTestScript.log.
Referenced by com.gmp.auth.test.AuthSystemTestScript.hasPermission(), com.gmp.auth.test.AuthSystemTestScript.testUserLogin(), and com.gmp.auth.test.AuthSystemTestScript.testUserPermissionDifferences().
testOrganizationInitialization()
void com.gmp.auth.test.AuthSystemTestScript.testOrganizationInitialization ()
Definition at line 56 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
testRolePermissionInitialization()
void com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization ()
Definition at line 66 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, com.gmp.auth.test.AuthSystemTestScript.permissionRepository, and com.gmp.auth.test.AuthSystemTestScript.roleRepository.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
testUserInitialization()
void com.gmp.auth.test.AuthSystemTestScript.testUserInitialization ()
Definition at line 80 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.userRepository.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
testUserLogin()
void com.gmp.auth.test.AuthSystemTestScript.testUserLogin ()
Definition at line 126 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.testLogin().
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
testUserOrganizationRoleAssociation()
void com.gmp.auth.test.AuthSystemTestScript.testUserOrganizationRoleAssociation ()
Definition at line 96 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.userRepository.
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
testUserPermissionDifferences()
void com.gmp.auth.test.AuthSystemTestScript.testUserPermissionDifferences ()
Definition at line 171 of file AuthSystemTestScript.java.
References com.gmp.auth.test.AuthSystemTestScript.log, and com.gmp.auth.test.AuthSystemTestScript.testLogin().
Referenced by com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods(), and com.gmp.auth.test.AuthSystemTestScript.runAllTests().
Member Data Documentation
authenticationManager
final AuthenticationManager com.gmp.auth.test.AuthSystemTestScript.authenticationManager private
Definition at line 41 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.testLogin().
log
final Logger com.gmp.auth.test.AuthSystemTestScript.log = LoggerFactory.getLogger(AuthSystemTestScript.class) static private
Definition at line 42 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.hasPermission(), com.gmp.auth.test.AuthSystemTestScript.initializeTestData(), com.gmp.auth.test.AuthSystemTestScript.runAllTests(), com.gmp.auth.test.AuthSystemTestScript.testFindUserRolesByUserId(), com.gmp.auth.test.AuthSystemTestScript.testLogin(), com.gmp.auth.test.AuthSystemTestScript.testOrganizationInitialization(), com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserLogin(), com.gmp.auth.test.AuthSystemTestScript.testUserOrganizationRoleAssociation(), and com.gmp.auth.test.AuthSystemTestScript.testUserPermissionDifferences().
organizationInitializer
final OrganizationStructureInitializer com.gmp.auth.test.AuthSystemTestScript.organizationInitializer private
Definition at line 34 of file AuthSystemTestScript.java.
permissionRepository
final PermissionRepository com.gmp.auth.test.AuthSystemTestScript.permissionRepository private
Definition at line 39 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization().
rolePermissionInitializer
final RolePermissionInitializer com.gmp.auth.test.AuthSystemTestScript.rolePermissionInitializer private
Definition at line 35 of file AuthSystemTestScript.java.
roleRepository
final RoleRepository com.gmp.auth.test.AuthSystemTestScript.roleRepository private
Definition at line 38 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization().
userInitializer
final UserInitializer com.gmp.auth.test.AuthSystemTestScript.userInitializer private
Definition at line 36 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.initializeTestData().
userOrganizationRoleRepository
final UserOrganizationRoleRepository com.gmp.auth.test.AuthSystemTestScript.userOrganizationRoleRepository private
Definition at line 40 of file AuthSystemTestScript.java.
userRepository
final UserRepository com.gmp.auth.test.AuthSystemTestScript.userRepository private
Definition at line 37 of file AuthSystemTestScript.java.
Referenced by com.gmp.auth.test.AuthSystemTestScript.testUserInitialization(), and com.gmp.auth.test.AuthSystemTestScript.testUserOrganizationRoleAssociation().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/test/AuthSystemTestScript.java