GMP系统: com.gmp.qms.service.reporting.McpPerformanceReportService Class Reference
com.gmp.qms.service.reporting.McpPerformanceReportService Class Reference
MCP性能分析报告服务，用于生成定期性能报告和性能趋势分析
Classes
class PerformanceSnapshot
Public Member Functions
Map< String, Object > generateCurrentReport ()
生成当前系统性能报告
Map< String, Object > generateTrendReport (int hours)
生成性能趋势报告
void savePerformanceSnapshot ()
定期保存性能快照（每5分钟）
void clearHistoricalData ()
清除所有历史数据
Map< String, Integer > getHistoricalDataSize ()
获取当前历史数据大小
Private Member Functions
List< String > generateRecommendations (McpMonitoringService.SystemMetrics metrics)
生成性能优化建议
void cleanOldSnapshots (String key, int maxSnapshots)
清理旧的快照数据
Private Attributes
McpMonitoringService monitoringService
final Map< String, List< PerformanceSnapshot > > historicalData = new ConcurrentHashMap<>()
Detailed Description
MCP性能分析报告服务，用于生成定期性能报告和性能趋势分析
Author
GMP系统开发团队
Definition at line 19 of file McpPerformanceReportService.java.
Member Function Documentation
cleanOldSnapshots()
void com.gmp.qms.service.reporting.McpPerformanceReportService.cleanOldSnapshots (String key, int maxSnapshots) private
清理旧的快照数据
Definition at line 215 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData.
Referenced by com.gmp.qms.service.reporting.McpPerformanceReportService.savePerformanceSnapshot().
clearHistoricalData()
void com.gmp.qms.service.reporting.McpPerformanceReportService.clearHistoricalData ()
清除所有历史数据
Definition at line 226 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData.
generateCurrentReport()
Map< String, Object > com.gmp.qms.service.reporting.McpPerformanceReportService.generateCurrentReport ()
生成当前系统性能报告
Definition at line 47 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.generateRecommendations(), and com.gmp.qms.service.reporting.McpPerformanceReportService.monitoringService.
generateRecommendations()
List< String > com.gmp.qms.service.reporting.McpPerformanceReportService.generateRecommendations (McpMonitoringService.SystemMetrics metrics) private
生成性能优化建议
Definition at line 156 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.reporting.McpPerformanceReportService.generateCurrentReport().
generateTrendReport()
Map< String, Object > com.gmp.qms.service.reporting.McpPerformanceReportService.generateTrendReport (int hours)
生成性能趋势报告
Definition at line 102 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.PerformanceSnapshot.avgResponseTime, com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData, com.gmp.qms.service.reporting.McpPerformanceReportService.PerformanceSnapshot.successRate, and com.gmp.qms.service.reporting.McpPerformanceReportService.PerformanceSnapshot.totalCalls.
getHistoricalDataSize()
Map< String, Integer > com.gmp.qms.service.reporting.McpPerformanceReportService.getHistoricalDataSize ()
获取当前历史数据大小
Definition at line 233 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData.
savePerformanceSnapshot()
void com.gmp.qms.service.reporting.McpPerformanceReportService.savePerformanceSnapshot ()
定期保存性能快照（每5分钟）
Definition at line 190 of file McpPerformanceReportService.java.
References com.gmp.qms.service.reporting.McpPerformanceReportService.cleanOldSnapshots(), com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData, and com.gmp.qms.service.reporting.McpPerformanceReportService.monitoringService.
Member Data Documentation
historicalData
final Map<String, List<PerformanceSnapshot> > com.gmp.qms.service.reporting.McpPerformanceReportService.historicalData = new ConcurrentHashMap<>() private
Definition at line 25 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.reporting.McpPerformanceReportService.cleanOldSnapshots(), com.gmp.qms.service.reporting.McpPerformanceReportService.clearHistoricalData(), com.gmp.qms.service.reporting.McpPerformanceReportService.generateTrendReport(), com.gmp.qms.service.reporting.McpPerformanceReportService.getHistoricalDataSize(), and com.gmp.qms.service.reporting.McpPerformanceReportService.savePerformanceSnapshot().
monitoringService
McpMonitoringService com.gmp.qms.service.reporting.McpPerformanceReportService.monitoringService private
Definition at line 22 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.reporting.McpPerformanceReportService.generateCurrentReport(), and com.gmp.qms.service.reporting.McpPerformanceReportService.savePerformanceSnapshot().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/reporting/McpPerformanceReportService.java