GMP系统: com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext Class Reference
com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext Class Reference
Public Member Functions
String getUserId ()
void setUserId (String userId)
Long getDocumentId ()
void setDocumentId (Long documentId)
String getDocumentType ()
void setDocumentType (String documentType)
String getConfidentialityLevel ()
void setConfidentialityLevel (String confidentialityLevel)
LocalDateTime getCurrentTime ()
void setCurrentTime (LocalDateTime currentTime)
Private Attributes
String userId
Long documentId
String documentType
String confidentialityLevel
LocalDateTime currentTime
Detailed Description
Definition at line 383 of file DocumentPermissionServiceImpl.java.
Member Function Documentation
getConfidentialityLevel()
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getConfidentialityLevel ()
Definition at line 415 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.confidentialityLevel.
getCurrentTime()
LocalDateTime com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getCurrentTime ()
Definition at line 423 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.currentTime.
getDocumentId()
Long com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getDocumentId ()
Definition at line 399 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentId.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions().
getDocumentType()
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getDocumentType ()
Definition at line 407 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentType.
getUserId()
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getUserId ()
Definition at line 391 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.userId.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.DocumentOwnerPolicy.evaluate(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions().
setConfidentialityLevel()
void com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setConfidentialityLevel (String confidentialityLevel)
Definition at line 419 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.confidentialityLevel.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext().
setCurrentTime()
void com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setCurrentTime (LocalDateTime currentTime)
Definition at line 427 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.currentTime.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext().
setDocumentId()
void com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentId (Long documentId)
Definition at line 403 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentId.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext().
setDocumentType()
void com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentType (String documentType)
Definition at line 411 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentType.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext().
setUserId()
void com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setUserId (String userId)
Definition at line 395 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.userId.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext().
Member Data Documentation
confidentialityLevel
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.confidentialityLevel private
Definition at line 387 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getConfidentialityLevel(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setConfidentialityLevel().
currentTime
LocalDateTime com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.currentTime private
Definition at line 388 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getCurrentTime(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setCurrentTime().
documentId
Long com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentId private
Definition at line 385 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getDocumentId(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentId().
documentType
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.documentType private
Definition at line 386 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getDocumentType(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentType().
userId
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.userId private
Definition at line 384 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getUserId(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setUserId().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/DocumentPermissionServiceImpl.java