GMP系统: com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl Class Reference
com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl Class Reference
用户密码历史服务实现
Public Member Functions
List< String > getPasswordHistory (Long userId, int limit)
获取用户的密码历史记录
void recordPasswordHistory (Long userId, String hashedPassword)
记录密码历史
void cleanOldPasswordHistory (Long userId, int keepCount)
清理过旧的密码历史记录
void savePasswordHistory (Long userId, String passwordHash)
保存密码历史记录
boolean isPasswordInHistory (Long userId, String passwordHash)
检查密码是否在历史记录中
Private Attributes
UserPasswordHistoryRepository userPasswordHistoryRepository
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(UserPasswordHistoryServiceImpl.class)
Detailed Description
用户密码历史服务实现
Definition at line 19 of file UserPasswordHistoryServiceImpl.java.
Member Function Documentation
cleanOldPasswordHistory()
void com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.cleanOldPasswordHistory (Long userId, int keepCount)
清理过旧的密码历史记录
Parameters
userId 用户ID
keepCount 保留的记录数
Implements com.gmp.auth.service.UserPasswordHistoryService.
Definition at line 42 of file UserPasswordHistoryServiceImpl.java.
References com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.log.
getPasswordHistory()
List< String > com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.getPasswordHistory (Long userId, int limit)
获取用户的密码历史记录
Parameters
userId 用户ID
limit 限制返回记录数
Returns
密码历史记录列表（哈希值）
Implements com.gmp.auth.service.UserPasswordHistoryService.
Definition at line 27 of file UserPasswordHistoryServiceImpl.java.
References com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.log.
isPasswordInHistory()
boolean com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.isPasswordInHistory (Long userId, String password)
检查密码是否在历史记录中
Parameters
userId 用户ID
password 密码
Returns
是否在历史记录中
Implements com.gmp.auth.service.UserPasswordHistoryService.
Definition at line 55 of file UserPasswordHistoryServiceImpl.java.
recordPasswordHistory()
void com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.recordPasswordHistory (Long userId, String hashedPassword)
记录密码历史
Parameters
userId 用户ID
hashedPassword 哈希后的密码
Implements com.gmp.auth.service.UserPasswordHistoryService.
Definition at line 35 of file UserPasswordHistoryServiceImpl.java.
References com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.log.
savePasswordHistory()
void com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.savePasswordHistory (Long userId, String password)
保存密码历史记录
Parameters
userId 用户ID
password 密码
Implements com.gmp.auth.service.UserPasswordHistoryService.
Definition at line 49 of file UserPasswordHistoryServiceImpl.java.
Member Data Documentation
log
final Logger com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.log = LoggerFactory.getLogger(UserPasswordHistoryServiceImpl.class) static private
Definition at line 21 of file UserPasswordHistoryServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.cleanOldPasswordHistory(), com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.getPasswordHistory(), and com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.recordPasswordHistory().
userPasswordHistoryRepository
UserPasswordHistoryRepository com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.userPasswordHistoryRepository private
Definition at line 24 of file UserPasswordHistoryServiceImpl.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/UserPasswordHistoryServiceImpl.java