GMP系统: com.gmp.auth.test.AuthTestErrorHandler.TestStatus Class Reference
com.gmp.auth.test.AuthTestErrorHandler.TestStatus Class Reference
测试状态类
Public Member Functions
TestStatus (String testName)
String getTestName ()
LocalDateTime getStartTime ()
void setStartTime (LocalDateTime startTime)
LocalDateTime getEndTime ()
void setEndTime (LocalDateTime endTime)
boolean isSuccess ()
void setSuccess (boolean success)
String getErrorMessage ()
void setErrorMessage (String errorMessage)
ErrorType getErrorType ()
void setErrorType (ErrorType errorType)
long getExecutionTime ()
Private Attributes
final String testName
LocalDateTime startTime
LocalDateTime endTime
boolean success
String errorMessage
ErrorType errorType
Detailed Description
测试状态类
Definition at line 287 of file AuthTestErrorHandler.java.
Constructor & Destructor Documentation
TestStatus()
com.gmp.auth.test.AuthTestErrorHandler.TestStatus.TestStatus (String testName)
Definition at line 295 of file AuthTestErrorHandler.java.
Member Function Documentation
getEndTime()
LocalDateTime com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getEndTime ()
Definition at line 304 of file AuthTestErrorHandler.java.
getErrorMessage()
String com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getErrorMessage ()
Definition at line 308 of file AuthTestErrorHandler.java.
getErrorType()
ErrorType com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getErrorType ()
Definition at line 310 of file AuthTestErrorHandler.java.
getExecutionTime()
long com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getExecutionTime ()
Definition at line 314 of file AuthTestErrorHandler.java.
getStartTime()
LocalDateTime com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getStartTime ()
Definition at line 302 of file AuthTestErrorHandler.java.
getTestName()
String com.gmp.auth.test.AuthTestErrorHandler.TestStatus.getTestName ()
Definition at line 301 of file AuthTestErrorHandler.java.
isSuccess()
boolean com.gmp.auth.test.AuthTestErrorHandler.TestStatus.isSuccess ()
Definition at line 306 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.generateErrorReport().
setEndTime()
void com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setEndTime (LocalDateTime endTime)
Definition at line 305 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
setErrorMessage()
void com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setErrorMessage (String errorMessage)
Definition at line 309 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
setErrorType()
void com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setErrorType (ErrorType errorType)
Definition at line 311 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
setStartTime()
void com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setStartTime (LocalDateTime startTime)
Definition at line 303 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
setSuccess()
void com.gmp.auth.test.AuthTestErrorHandler.TestStatus.setSuccess (boolean success)
Definition at line 307 of file AuthTestErrorHandler.java.
Referenced by com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
Member Data Documentation
endTime
LocalDateTime com.gmp.auth.test.AuthTestErrorHandler.TestStatus.endTime private
Definition at line 290 of file AuthTestErrorHandler.java.
errorMessage
String com.gmp.auth.test.AuthTestErrorHandler.TestStatus.errorMessage private
Definition at line 292 of file AuthTestErrorHandler.java.
errorType
ErrorType com.gmp.auth.test.AuthTestErrorHandler.TestStatus.errorType private
Definition at line 293 of file AuthTestErrorHandler.java.
startTime
LocalDateTime com.gmp.auth.test.AuthTestErrorHandler.TestStatus.startTime private
Definition at line 289 of file AuthTestErrorHandler.java.
success
boolean com.gmp.auth.test.AuthTestErrorHandler.TestStatus.success private
Definition at line 291 of file AuthTestErrorHandler.java.
testName
final String com.gmp.auth.test.AuthTestErrorHandler.TestStatus.testName private
Definition at line 288 of file AuthTestErrorHandler.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/test/AuthTestErrorHandler.java