GMP系统: com.gmp.training.service.impl.TrainingCourseServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingCourseServiceImplTest Class Reference
培训课程服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByCode ()
void testFindByName ()
void testFindByPlanId ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testFindByCourseType ()
void testFindByStatus ()
void testFindByDateRange ()
void testSearch ()
void testValidateUniqueCode ()
void testCountByPlanId ()
Private Attributes
TrainingCourseRepository trainingCourseRepository
TrainingCourseServiceImpl trainingCourseService
TrainingCourse trainingCourse
Detailed Description
培训课程服务实现的单元测试
Definition at line 27 of file TrainingCourseServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.setUp () package
Definition at line 38 of file TrainingCourseServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testBatchUpdateStatus () package
Definition at line 160 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.batchUpdateStatus().
testCountByPlanId()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testCountByPlanId () package
Definition at line 247 of file TrainingCourseServiceImplTest.java.
testDelete()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testDelete () package
Definition at line 93 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindAll () package
Definition at line 78 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findAll().
testFindByCode()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByCode () package
Definition at line 102 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.findByCode().
testFindByCourseType()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByCourseType () package
Definition at line 171 of file TrainingCourseServiceImplTest.java.
testFindByDateRange()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByDateRange () package
Definition at line 203 of file TrainingCourseServiceImplTest.java.
testFindById()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindById () package
Definition at line 67 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findById().
testFindByName()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByName () package
Definition at line 117 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.findByName().
testFindByPlanId()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByPlanId () package
Definition at line 132 of file TrainingCourseServiceImplTest.java.
testFindByStatus()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByStatus () package
Definition at line 188 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.findByStatus().
testSave()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testSave () package
Definition at line 55 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testSearch () package
Definition at line 220 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.search().
testUpdateStatus()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testUpdateStatus () package
Definition at line 147 of file TrainingCourseServiceImplTest.java.
References com.gmp.training.service.impl.TrainingCourseServiceImpl.updateStatus().
testValidateUniqueCode()
void com.gmp.training.service.impl.TrainingCourseServiceImplTest.testValidateUniqueCode () package
Definition at line 235 of file TrainingCourseServiceImplTest.java.
Member Data Documentation
trainingCourse
TrainingCourse com.gmp.training.service.impl.TrainingCourseServiceImplTest.trainingCourse private
Definition at line 35 of file TrainingCourseServiceImplTest.java.
trainingCourseRepository
TrainingCourseRepository com.gmp.training.service.impl.TrainingCourseServiceImplTest.trainingCourseRepository private
Definition at line 30 of file TrainingCourseServiceImplTest.java.
trainingCourseService
TrainingCourseServiceImpl com.gmp.training.service.impl.TrainingCourseServiceImplTest.trainingCourseService private
Definition at line 33 of file TrainingCourseServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingCourseServiceImplTest.java