GMP系统: com.gmp.auth.util.JwtUtilTest Class Reference
com.gmp.auth.util.JwtUtilTest Class Reference
Package Functions
void setUp ()
void testGenerateAccessToken_Success ()
void testGenerateRefreshToken_Success ()
void testGenerateRefreshToken_NullUserDetails ()
void testValidateToken_ValidToken ()
void testValidateToken_NullToken ()
void testValidateToken_InvalidToken ()
void testGetUsernameFromToken_Success ()
void testGetUsernameFromToken_InvalidToken ()
void testGetExpirationDateFromToken_Success ()
void testIsTokenExpired_NotExpired ()
void testIsTokenRevoked_NotRevoked ()
void testRevokeToken_Success ()
void testGetTokenIdFromToken_Success ()
void testParseTokenWithoutValidation_Success ()
void testValidateTokenForUserDetails_Success ()
void testValidateTokenForUserDetails_WrongUsername ()
void testValidateTokenForUserDetails_NullToken ()
void testValidateTokenForUserDetails_NullUserDetails ()
void testValidateTokenForUserDetails_ValidToken ()
Private Attributes
JwtUtil jwtUtil
String username
UserDetails userDetails
Detailed Description
Definition at line 20 of file JwtUtilTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.util.JwtUtilTest.setUp () package
Definition at line 29 of file JwtUtilTest.java.
testGenerateAccessToken_Success()
void com.gmp.auth.util.JwtUtilTest.testGenerateAccessToken_Success () package
Definition at line 58 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.getUsernameFromToken().
testGenerateRefreshToken_NullUserDetails()
void com.gmp.auth.util.JwtUtilTest.testGenerateRefreshToken_NullUserDetails () package
Definition at line 79 of file JwtUtilTest.java.
testGenerateRefreshToken_Success()
void com.gmp.auth.util.JwtUtilTest.testGenerateRefreshToken_Success () package
Definition at line 69 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateRefreshToken().
testGetExpirationDateFromToken_Success()
void com.gmp.auth.util.JwtUtilTest.testGetExpirationDateFromToken_Success () package
Definition at line 145 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.getExpirationDateFromToken().
testGetTokenIdFromToken_Success()
void com.gmp.auth.util.JwtUtilTest.testGetTokenIdFromToken_Success () package
Definition at line 196 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.getTokenIdFromToken().
testGetUsernameFromToken_InvalidToken()
void com.gmp.auth.util.JwtUtilTest.testGetUsernameFromToken_InvalidToken () package
Definition at line 132 of file JwtUtilTest.java.
testGetUsernameFromToken_Success()
void com.gmp.auth.util.JwtUtilTest.testGetUsernameFromToken_Success () package
Definition at line 120 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.getUsernameFromToken().
testIsTokenExpired_NotExpired()
void com.gmp.auth.util.JwtUtilTest.testIsTokenExpired_NotExpired () package
Definition at line 159 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.isTokenExpired().
testIsTokenRevoked_NotRevoked()
void com.gmp.auth.util.JwtUtilTest.testIsTokenRevoked_NotRevoked () package
Definition at line 171 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.isTokenRevoked().
testParseTokenWithoutValidation_Success()
void com.gmp.auth.util.JwtUtilTest.testParseTokenWithoutValidation_Success () package
Definition at line 209 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.parseTokenWithoutValidation().
testRevokeToken_Success()
void com.gmp.auth.util.JwtUtilTest.testRevokeToken_Success () package
Definition at line 183 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), com.gmp.auth.util.JwtUtil.isTokenRevoked(), and com.gmp.auth.util.JwtUtil.revokeToken().
testValidateToken_InvalidToken()
void com.gmp.auth.util.JwtUtilTest.testValidateToken_InvalidToken () package
Definition at line 108 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.validateToken().
testValidateToken_NullToken()
void com.gmp.auth.util.JwtUtilTest.testValidateToken_NullToken () package
Definition at line 99 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.validateToken().
testValidateToken_ValidToken()
void com.gmp.auth.util.JwtUtilTest.testValidateToken_ValidToken () package
Definition at line 87 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.validateToken().
testValidateTokenForUserDetails_NullToken()
void com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_NullToken () package
Definition at line 253 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.validateToken().
testValidateTokenForUserDetails_NullUserDetails()
void com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_NullUserDetails () package
Definition at line 262 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.validateToken().
testValidateTokenForUserDetails_Success()
void com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_Success () package
Definition at line 222 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.validateToken().
testValidateTokenForUserDetails_ValidToken()
void com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_ValidToken () package
Definition at line 274 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.validateToken().
testValidateTokenForUserDetails_WrongUsername()
void com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_WrongUsername () package
Definition at line 234 of file JwtUtilTest.java.
References com.gmp.auth.util.JwtUtil.generateAccessToken(), and com.gmp.auth.util.JwtUtil.validateToken().
Member Data Documentation
jwtUtil
JwtUtil com.gmp.auth.util.JwtUtilTest.jwtUtil private
Definition at line 23 of file JwtUtilTest.java.
userDetails
UserDetails com.gmp.auth.util.JwtUtilTest.userDetails private
Definition at line 26 of file JwtUtilTest.java.
username
String com.gmp.auth.util.JwtUtilTest.username private
Definition at line 25 of file JwtUtilTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/util/JwtUtilTest.java