GMP系统: com.gmp.lims.util.TestUtils Class Reference
com.gmp.lims.util.TestUtils Class Reference
测试工具类 提供测试数据和辅助方法
Static Public Member Functions
static Sample createSample ()
创建测试用样品实体
static SampleDTO createSampleDTO ()
创建测试用样品DTO
static InspectionTask createInspectionTask ()
创建测试用检测任务实体
static InspectionTaskDTO createInspectionTaskDTO ()
创建测试用检测任务DTO
static InspectionResult createInspectionResult ()
创建测试用检测结果实体
static InspectionResultDTO createInspectionResultDTO ()
创建测试用检测结果DTO
static TraditionalIdentifyRecord createTraditionalIdentifyRecord ()
创建测试用传统鉴别记录
static FingerprintAnalysis createFingerprintAnalysis ()
创建测试用指纹图谱分析记录
static AuthenticityAssessment createAuthenticityAssessment ()
创建测试用道地性评估记录
static List< Sample > getSamplesWithDifferentStatus ()
获取不同状态的样品列表
static List< InspectionTask > getTasksWithDifferentStatus ()
获取不同状态的检测任务列表
Detailed Description
测试工具类 提供测试数据和辅助方法
Definition at line 25 of file TestUtils.java.
Member Function Documentation
createAuthenticityAssessment()
static AuthenticityAssessment com.gmp.lims.util.TestUtils.createAuthenticityAssessment () static
创建测试用道地性评估记录
Definition at line 240 of file TestUtils.java.
createFingerprintAnalysis()
static FingerprintAnalysis com.gmp.lims.util.TestUtils.createFingerprintAnalysis () static
创建测试用指纹图谱分析记录
Definition at line 191 of file TestUtils.java.
createInspectionResult()
static InspectionResult com.gmp.lims.util.TestUtils.createInspectionResult () static
创建测试用检测结果实体
Definition at line 117 of file TestUtils.java.
createInspectionResultDTO()
static InspectionResultDTO com.gmp.lims.util.TestUtils.createInspectionResultDTO () static
创建测试用检测结果DTO
Definition at line 144 of file TestUtils.java.
createInspectionTask()
static InspectionTask com.gmp.lims.util.TestUtils.createInspectionTask () static
创建测试用检测任务实体
Definition at line 71 of file TestUtils.java.
Referenced by com.gmp.lims.util.TestUtils.getTasksWithDifferentStatus().
createInspectionTaskDTO()
static InspectionTaskDTO com.gmp.lims.util.TestUtils.createInspectionTaskDTO () static
创建测试用检测任务DTO
Definition at line 92 of file TestUtils.java.
createSample()
static Sample com.gmp.lims.util.TestUtils.createSample () static
创建测试用样品实体
Definition at line 30 of file TestUtils.java.
Referenced by com.gmp.lims.util.TestUtils.getSamplesWithDifferentStatus().
createSampleDTO()
static SampleDTO com.gmp.lims.util.TestUtils.createSampleDTO () static
创建测试用样品DTO
Definition at line 53 of file TestUtils.java.
createTraditionalIdentifyRecord()
static TraditionalIdentifyRecord com.gmp.lims.util.TestUtils.createTraditionalIdentifyRecord () static
创建测试用传统鉴别记录
Definition at line 172 of file TestUtils.java.
getSamplesWithDifferentStatus()
static List< Sample > com.gmp.lims.util.TestUtils.getSamplesWithDifferentStatus () static
获取不同状态的样品列表
Definition at line 254 of file TestUtils.java.
References com.gmp.lims.util.TestUtils.createSample().
getTasksWithDifferentStatus()
static List< InspectionTask > com.gmp.lims.util.TestUtils.getTasksWithDifferentStatus () static
获取不同状态的检测任务列表
Definition at line 287 of file TestUtils.java.
References com.gmp.lims.util.TestUtils.createInspectionTask().
The documentation for this class was generated from the following file:
lims-service/src/test/java/com/gmp/lims/util/TestUtils.java