GMP系统: com.gmp.auth.service.TokenBlacklistServiceTest Class Reference
com.gmp.auth.service.TokenBlacklistServiceTest Class Reference
Package Functions
void setUp ()
void testBlacklistToken_Success ()
void testBlacklistToken_AlreadyExpired ()
void testIsTokenBlacklisted_TokenIsBlacklisted ()
void testIsTokenBlacklisted_TokenNotBlacklisted ()
void testIsTokenBlacklisted_NullToken ()
void testBlacklistTokenWithDifferentExpirations ()
void testBlacklistTokenWithZeroExpiration ()
Private Attributes
RedisTemplate< String, String > redisTemplate
ValueOperations< String, String > valueOperations
RedisTokenBlacklistService tokenBlacklistService
String testToken
long expirationTime
Detailed Description
Definition at line 22 of file TokenBlacklistServiceTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.service.TokenBlacklistServiceTest.setUp () package
Definition at line 37 of file TokenBlacklistServiceTest.java.
testBlacklistToken_AlreadyExpired()
void com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistToken_AlreadyExpired () package
Definition at line 59 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken().
testBlacklistToken_Success()
void com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistToken_Success () package
Definition at line 46 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken().
testBlacklistTokenWithDifferentExpirations()
void com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistTokenWithDifferentExpirations () package
Definition at line 107 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken().
testBlacklistTokenWithZeroExpiration()
void com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistTokenWithZeroExpiration () package
Definition at line 130 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken().
testIsTokenBlacklisted_NullToken()
void com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_NullToken () package
Definition at line 97 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.isTokenBlacklisted().
testIsTokenBlacklisted_TokenIsBlacklisted()
void com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_TokenIsBlacklisted () package
Definition at line 71 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.isTokenBlacklisted().
testIsTokenBlacklisted_TokenNotBlacklisted()
void com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_TokenNotBlacklisted () package
Definition at line 84 of file TokenBlacklistServiceTest.java.
References com.gmp.auth.service.RedisTokenBlacklistService.isTokenBlacklisted().
Member Data Documentation
expirationTime
long com.gmp.auth.service.TokenBlacklistServiceTest.expirationTime private
Definition at line 34 of file TokenBlacklistServiceTest.java.
redisTemplate
RedisTemplate<String, String> com.gmp.auth.service.TokenBlacklistServiceTest.redisTemplate private
Definition at line 25 of file TokenBlacklistServiceTest.java.
testToken
String com.gmp.auth.service.TokenBlacklistServiceTest.testToken private
Definition at line 33 of file TokenBlacklistServiceTest.java.
tokenBlacklistService
RedisTokenBlacklistService com.gmp.auth.service.TokenBlacklistServiceTest.tokenBlacklistService private
Definition at line 31 of file TokenBlacklistServiceTest.java.
valueOperations
ValueOperations<String, String> com.gmp.auth.service.TokenBlacklistServiceTest.valueOperations private
Definition at line 28 of file TokenBlacklistServiceTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/TokenBlacklistServiceTest.java