GMP系统: com.gmp.auth.config.RedisConfigTest Class Reference
com.gmp.auth.config.RedisConfigTest Class Reference
RedisConfig配置类单元测试 提高配置层覆盖率
Package Functions
void testRedisConfigCreation ()
void testRedisTemplateBeanCreation ()
void testRedisTemplateConfiguration ()
void testRedisTemplateWithNullConnectionFactory ()
void testRedisTemplateTypeParameters ()
Detailed Description
RedisConfig配置类单元测试 提高配置层覆盖率
Author
GMP系统开发团队
Definition at line 20 of file RedisConfigTest.java.
Member Function Documentation
testRedisConfigCreation()
void com.gmp.auth.config.RedisConfigTest.testRedisConfigCreation () package
Definition at line 23 of file RedisConfigTest.java.
testRedisTemplateBeanCreation()
void com.gmp.auth.config.RedisConfigTest.testRedisTemplateBeanCreation () package
Definition at line 32 of file RedisConfigTest.java.
References com.gmp.auth.config.RedisConfig.redisTemplate().
testRedisTemplateConfiguration()
void com.gmp.auth.config.RedisConfigTest.testRedisTemplateConfiguration () package
Definition at line 51 of file RedisConfigTest.java.
References com.gmp.auth.config.RedisConfig.redisTemplate().
testRedisTemplateTypeParameters()
void com.gmp.auth.config.RedisConfigTest.testRedisTemplateTypeParameters () package
Definition at line 80 of file RedisConfigTest.java.
References com.gmp.auth.config.RedisConfig.redisTemplate().
testRedisTemplateWithNullConnectionFactory()
void com.gmp.auth.config.RedisConfigTest.testRedisTemplateWithNullConnectionFactory () package
Definition at line 68 of file RedisConfigTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/config/RedisConfigTest.java