GMP系统: com.gmp.qms.security.McpAuthenticationToken Class Reference
com.gmp.qms.security.McpAuthenticationToken Class Reference
MCP认证令牌，用于表示MCP请求的认证信息和状态
Public Member Functions
McpAuthenticationToken (Object credentials)
创建未认证的MCP令牌
McpAuthenticationToken (Object principal, Object credentials, Collection<? extends GrantedAuthority > authorities)
创建已认证的MCP令牌
Object getCredentials ()
Object getPrincipal ()
void setAuthenticated (boolean authenticated)
void eraseCredentials ()
Private Attributes
final Object principal
final Object credentials
Detailed Description
MCP认证令牌，用于表示MCP请求的认证信息和状态
Author
GMP系统开发团队
Definition at line 14 of file McpAuthenticationToken.java.
Constructor & Destructor Documentation
McpAuthenticationToken() [1/2]
com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken (Object credentials)
创建未认证的MCP令牌
Parameters
credentials 通常是JWT令牌字符串
Definition at line 24 of file McpAuthenticationToken.java.
References com.gmp.qms.security.McpAuthenticationToken.credentials, and com.gmp.qms.security.McpAuthenticationToken.setAuthenticated().
McpAuthenticationToken() [2/2]
com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken (Object principal, Object credentials, Collection<? extends GrantedAuthority > authorities)
创建已认证的MCP令牌
Parameters
principal 客户端主体信息
credentials JWT令牌
authorities 授予的权限列表
Definition at line 38 of file McpAuthenticationToken.java.
References com.gmp.qms.security.McpAuthenticationToken.credentials, com.gmp.qms.security.McpAuthenticationToken.principal, and com.gmp.qms.security.McpAuthenticationToken.setAuthenticated().
Member Function Documentation
eraseCredentials()
void com.gmp.qms.security.McpAuthenticationToken.eraseCredentials ()
Definition at line 66 of file McpAuthenticationToken.java.
getCredentials()
Object com.gmp.qms.security.McpAuthenticationToken.getCredentials ()
Definition at line 47 of file McpAuthenticationToken.java.
References com.gmp.qms.security.McpAuthenticationToken.credentials.
getPrincipal()
Object com.gmp.qms.security.McpAuthenticationToken.getPrincipal ()
Definition at line 52 of file McpAuthenticationToken.java.
References com.gmp.qms.security.McpAuthenticationToken.principal.
setAuthenticated()
void com.gmp.qms.security.McpAuthenticationToken.setAuthenticated (boolean authenticated)
Definition at line 57 of file McpAuthenticationToken.java.
Referenced by com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken(), and com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken().
Member Data Documentation
credentials
final Object com.gmp.qms.security.McpAuthenticationToken.credentials private
Definition at line 17 of file McpAuthenticationToken.java.
Referenced by com.gmp.qms.security.McpAuthenticationToken.getCredentials(), com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken(), and com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken().
principal
final Object com.gmp.qms.security.McpAuthenticationToken.principal private
Definition at line 16 of file McpAuthenticationToken.java.
Referenced by com.gmp.qms.security.McpAuthenticationToken.getPrincipal(), and com.gmp.qms.security.McpAuthenticationToken.McpAuthenticationToken().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/security/McpAuthenticationToken.java