GMP系统: com.gmp.qms.service.impl.DeviationServiceImpl Class Reference
com.gmp.qms.service.impl.DeviationServiceImpl Class Reference
偏差管理服务实现类
Public Member Functions
Deviation createDeviation (DeviationDTO deviationDTO)
创建新的偏差记录
Deviation updateDeviation (Long id, DeviationDTO deviationDTO)
更新偏差记录
Deviation getDeviationById (Long id)
根据ID查询偏差
Deviation getDeviationByCode (String deviationCode)
根据编号查询偏差
Page< Deviation > findAllDeviations (Pageable pageable)
分页查询偏差列表
Page< Deviation > searchDeviations (DeviationSearchCriteria criteria, Pageable pageable)
根据条件查询偏差列表
Deviation updateDeviationStatus (Long id, Deviation.DeviationStatus status, String comments)
更新偏差状态
Deviation addAttachment (Long deviationId, MultipartFile file, String description)
为偏差添加附件
Deviation removeAttachment (Long deviationId, Long attachmentId)
删除偏差附件
List< Deviation > findOverdueDeviations ()
查询逾期未处理的偏差
String generateDeviationCode ()
生成偏差编号
Private Member Functions
Specification< Deviation > buildDeviationSpecification (DeviationSearchCriteria criteria)
构建偏差查询条件
Private Attributes
final DeviationRepository deviationRepository
final DeviationAttachmentRepository deviationAttachmentRepository
Static Private Attributes
static final String UPLOAD_DIR = "/opt/gmp-system/uploads/deviations/"
Detailed Description
偏差管理服务实现类
Author
GMP系统开发团队
Definition at line 38 of file DeviationServiceImpl.java.
Member Function Documentation
addAttachment()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.addAttachment (Long deviationId, MultipartFile file, String description)
为偏差添加附件
Parameters
deviationId 偏差ID
file 上传的文件
description 文件描述
Returns
更新后的偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 101 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationAttachmentRepository, com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById(), and com.gmp.qms.service.impl.DeviationServiceImpl.UPLOAD_DIR.
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testAddAttachment().
buildDeviationSpecification()
Specification< Deviation > com.gmp.qms.service.impl.DeviationServiceImpl.buildDeviationSpecification (DeviationSearchCriteria criteria) private
构建偏差查询条件
Definition at line 182 of file DeviationServiceImpl.java.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.searchDeviations().
createDeviation()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.createDeviation (DeviationDTO deviationDTO)
创建新的偏差记录
Parameters
deviationDTO 偏差信息DTO
Returns
创建的偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 47 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository, and com.gmp.qms.service.impl.DeviationServiceImpl.generateDeviationCode().
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testCreateDeviation().
findAllDeviations()
Page< Deviation > com.gmp.qms.service.impl.DeviationServiceImpl.findAllDeviations (Pageable pageable)
分页查询偏差列表
Parameters
pageable 分页参数
Returns
偏差分页列表
Implements com.gmp.qms.service.DeviationService.
Definition at line 80 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testFindAllDeviations().
findOverdueDeviations()
List< Deviation > com.gmp.qms.service.impl.DeviationServiceImpl.findOverdueDeviations ()
查询逾期未处理的偏差
Returns
逾期偏差列表
Implements com.gmp.qms.service.DeviationService.
Definition at line 158 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testFindOverdueDeviations().
generateDeviationCode()
String com.gmp.qms.service.impl.DeviationServiceImpl.generateDeviationCode ()
生成偏差编号
Returns
新的偏差编号
Implements com.gmp.qms.service.DeviationService.
Definition at line 165 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.createDeviation(), and com.gmp.qms.service.impl.DeviationServiceImplTest.testGenerateDeviationCode().
getDeviationByCode()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationByCode (String deviationCode)
根据编号查询偏差
Parameters
deviationCode 偏差编号
Returns
偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 75 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testGetDeviationByCode().
getDeviationById()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById (Long id)
根据ID查询偏差
Parameters
id 偏差ID
Returns
偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 69 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.addAttachment(), com.gmp.qms.service.impl.DeviationServiceImpl.removeAttachment(), com.gmp.qms.service.impl.DeviationServiceImplTest.testGetDeviationById(), com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviation(), and com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviationStatus().
removeAttachment()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.removeAttachment (Long deviationId, Long attachmentId)
删除偏差附件
Parameters
deviationId 偏差ID
attachmentId 附件ID
Returns
更新后的偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 143 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationAttachmentRepository, and com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById().
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testRemoveAttachment().
searchDeviations()
Page< Deviation > com.gmp.qms.service.impl.DeviationServiceImpl.searchDeviations (DeviationSearchCriteria criteria, Pageable pageable)
根据条件查询偏差列表
Parameters
criteria 查询条件
pageable 分页参数
Returns
偏差分页列表
Implements com.gmp.qms.service.DeviationService.
Definition at line 85 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.buildDeviationSpecification(), and com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository.
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testSearchDeviations().
updateDeviation()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviation (Long id, DeviationDTO deviationDTO)
更新偏差记录
Parameters
id 偏差ID
deviationDTO 更新的偏差信息
Returns
更新后的偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 62 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository, and com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById().
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testUpdateDeviation().
updateDeviationStatus()
Deviation com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviationStatus (Long id, Deviation.DeviationStatus status, String comments)
更新偏差状态
Parameters
id 偏差ID
status 新状态
comments 状态变更说明
Returns
更新后的偏差实体
Implements com.gmp.qms.service.DeviationService.
Definition at line 92 of file DeviationServiceImpl.java.
References com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository, and com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById().
Referenced by com.gmp.qms.service.impl.DeviationServiceImplTest.testUpdateDeviationStatus().
Member Data Documentation
deviationAttachmentRepository
final DeviationAttachmentRepository com.gmp.qms.service.impl.DeviationServiceImpl.deviationAttachmentRepository private
Definition at line 41 of file DeviationServiceImpl.java.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.addAttachment(), and com.gmp.qms.service.impl.DeviationServiceImpl.removeAttachment().
deviationRepository
final DeviationRepository com.gmp.qms.service.impl.DeviationServiceImpl.deviationRepository private
Definition at line 40 of file DeviationServiceImpl.java.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.createDeviation(), com.gmp.qms.service.impl.DeviationServiceImpl.findAllDeviations(), com.gmp.qms.service.impl.DeviationServiceImpl.findOverdueDeviations(), com.gmp.qms.service.impl.DeviationServiceImpl.generateDeviationCode(), com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationByCode(), com.gmp.qms.service.impl.DeviationServiceImpl.getDeviationById(), com.gmp.qms.service.impl.DeviationServiceImpl.searchDeviations(), com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviation(), and com.gmp.qms.service.impl.DeviationServiceImpl.updateDeviationStatus().
UPLOAD_DIR
final String com.gmp.qms.service.impl.DeviationServiceImpl.UPLOAD_DIR = "/opt/gmp-system/uploads/deviations/" static private
Definition at line 43 of file DeviationServiceImpl.java.
Referenced by com.gmp.qms.service.impl.DeviationServiceImpl.addAttachment().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/impl/DeviationServiceImpl.java