GMP系统: com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer Class Reference
com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer Class Reference
MCP计时器内部类
Public Member Functions
McpTimer (String operationName)
void complete (boolean success)
完成计时
Private Attributes
final String operationName
final long startTime
Detailed Description
MCP计时器内部类
Definition at line 223 of file McpMonitoringService.java.
Constructor & Destructor Documentation
McpTimer()
com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.McpTimer (String operationName)
Definition at line 227 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.operationName.
Member Function Documentation
complete()
void com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.complete (boolean success)
完成计时
Parameters
success 是否成功
Definition at line 236 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemCallStats.addResponseTime(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemCallStats.incrementCalls(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemCallStats.incrementFailures(), com.gmp.qms.service.monitoring.McpMonitoringService.SystemCallStats.incrementSuccesses(), com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.operationName, com.gmp.qms.service.monitoring.McpMonitoringService.performanceMetrics, com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.startTime, and com.gmp.qms.service.monitoring.McpMonitoringService.systemCallStats.
Member Data Documentation
operationName
final String com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.operationName private
Definition at line 224 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.complete(), and com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.McpTimer().
startTime
final long com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.startTime private
Definition at line 225 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.McpTimer.complete().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpMonitoringService.java