GMP系统: com.gmp.auth.service.MfaService Class Reference
com.gmp.auth.service.MfaService Class Reference
MFA服务类，提供多因素认证相关功能
Public Member Functions
MfaService (TotpUtils totpUtils)
String generateSecretKey ()
生成新的MFA密钥
String generateTotpCode (String secretKey)
生成TOTP验证码
boolean verifyTotpCode (String secretKey, String code)
验证TOTP验证码
List< String > generateRecoveryCodes ()
生成指定数量的恢复码
String generateQrCodeUrl (String username, String secretKey, String issuer)
生成用于Google Authenticator等应用的二维码URL
int getRemainingSeconds ()
获取TOTP验证码的剩余有效期（秒）
boolean verifyRecoveryCode (List< String > userRecoveryCodes, String providedCode)
验证恢复码是否有效
List< String > removeUsedRecoveryCode (List< String > recoveryCodes, String usedCode)
从用户的恢复码列表中移除已使用的恢复码
Private Member Functions
String generateRecoveryCode ()
生成单个恢复码
Private Attributes
final SecureRandom secureRandom = new SecureRandom()
final TotpUtils totpUtils
Static Private Attributes
static final int RECOVERY_CODES_COUNT = 10
static final int RECOVERY_CODE_LENGTH = 8
Detailed Description
MFA服务类，提供多因素认证相关功能
Definition at line 13 of file MfaService.java.
Constructor & Destructor Documentation
MfaService()
com.gmp.auth.service.MfaService.MfaService (TotpUtils totpUtils)
Definition at line 20 of file MfaService.java.
References com.gmp.auth.service.MfaService.totpUtils.
Member Function Documentation
generateQrCodeUrl()
String com.gmp.auth.service.MfaService.generateQrCodeUrl (String username, String secretKey, String issuer)
生成用于Google Authenticator等应用的二维码URL
Definition at line 70 of file MfaService.java.
References com.gmp.auth.service.TotpUtils.generateTotpUri(), and com.gmp.auth.service.MfaService.totpUtils.
Referenced by com.gmp.auth.service.MfaServiceTest.testGenerateQrCodeUrl().
generateRecoveryCode()
String com.gmp.auth.service.MfaService.generateRecoveryCode () private
生成单个恢复码
Definition at line 59 of file MfaService.java.
References com.gmp.auth.service.MfaService.RECOVERY_CODE_LENGTH, and com.gmp.auth.service.MfaService.secureRandom.
Referenced by com.gmp.auth.service.MfaService.generateRecoveryCodes().
generateRecoveryCodes()
List< String > com.gmp.auth.service.MfaService.generateRecoveryCodes ()
生成指定数量的恢复码
Definition at line 48 of file MfaService.java.
References com.gmp.auth.service.MfaService.generateRecoveryCode(), and com.gmp.auth.service.MfaService.RECOVERY_CODES_COUNT.
Referenced by com.gmp.auth.service.MfaServiceTest.testGenerateRecoveryCodes().
generateSecretKey()
String com.gmp.auth.service.MfaService.generateSecretKey ()
生成新的MFA密钥
Definition at line 27 of file MfaService.java.
References com.gmp.auth.service.TotpUtils.generateSecretKey(), and com.gmp.auth.service.MfaService.totpUtils.
Referenced by com.gmp.auth.service.MfaServiceTest.testGenerateSecretKey().
generateTotpCode()
String com.gmp.auth.service.MfaService.generateTotpCode (String secretKey)
生成TOTP验证码
Definition at line 34 of file MfaService.java.
References com.gmp.auth.service.TotpUtils.generateTotpCode(), and com.gmp.auth.service.MfaService.totpUtils.
Referenced by com.gmp.auth.service.MfaServiceTest.testGenerateTotpCode().
getRemainingSeconds()
int com.gmp.auth.service.MfaService.getRemainingSeconds ()
获取TOTP验证码的剩余有效期（秒）
Definition at line 77 of file MfaService.java.
References com.gmp.auth.service.TotpUtils.getRemainingSeconds(), and com.gmp.auth.service.MfaService.totpUtils.
Referenced by com.gmp.auth.service.MfaServiceTest.testGetRemainingSeconds().
removeUsedRecoveryCode()
List< String > com.gmp.auth.service.MfaService.removeUsedRecoveryCode (List< String > recoveryCodes, String usedCode)
从用户的恢复码列表中移除已使用的恢复码
Parameters
recoveryCodes 用户的恢复码列表
usedCode 已使用的恢复码
Returns
更新后的恢复码列表
Definition at line 100 of file MfaService.java.
Referenced by com.gmp.auth.service.MfaServiceTest.testRemoveNonExistentRecoveryCode(), com.gmp.auth.service.MfaServiceTest.testRemoveUsedRecoveryCode(), and com.gmp.auth.service.MfaServiceTest.testRemoveUsedRecoveryCode_EmptyList().
verifyRecoveryCode()
boolean com.gmp.auth.service.MfaService.verifyRecoveryCode (List< String > userRecoveryCodes, String providedCode)
验证恢复码是否有效
Parameters
userRecoveryCodes 用户存储的恢复码
providedCode 用户提供的恢复码
Returns
是否有效
Definition at line 87 of file MfaService.java.
References com.gmp.auth.service.MfaService.RECOVERY_CODE_LENGTH.
Referenced by com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_Failure(), com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_InvalidFormat(), com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_NullParams(), and com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_Success().
verifyTotpCode()
boolean com.gmp.auth.service.MfaService.verifyTotpCode (String secretKey, String code)
验证TOTP验证码
Definition at line 41 of file MfaService.java.
References com.gmp.auth.service.MfaService.totpUtils, and com.gmp.auth.service.TotpUtils.verifyTotpCode().
Referenced by com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Failure(), and com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Success().
Member Data Documentation
RECOVERY_CODE_LENGTH
final int com.gmp.auth.service.MfaService.RECOVERY_CODE_LENGTH = 8 static private
Definition at line 15 of file MfaService.java.
Referenced by com.gmp.auth.service.MfaService.generateRecoveryCode(), and com.gmp.auth.service.MfaService.verifyRecoveryCode().
RECOVERY_CODES_COUNT
final int com.gmp.auth.service.MfaService.RECOVERY_CODES_COUNT = 10 static private
Definition at line 14 of file MfaService.java.
Referenced by com.gmp.auth.service.MfaService.generateRecoveryCodes().
secureRandom
final SecureRandom com.gmp.auth.service.MfaService.secureRandom = new SecureRandom() private
Definition at line 16 of file MfaService.java.
Referenced by com.gmp.auth.service.MfaService.generateRecoveryCode().
totpUtils
final TotpUtils com.gmp.auth.service.MfaService.totpUtils private
Definition at line 17 of file MfaService.java.
Referenced by com.gmp.auth.service.MfaService.generateQrCodeUrl(), com.gmp.auth.service.MfaService.generateSecretKey(), com.gmp.auth.service.MfaService.generateTotpCode(), com.gmp.auth.service.MfaService.getRemainingSeconds(), com.gmp.auth.service.MfaService.MfaService(), and com.gmp.auth.service.MfaService.verifyTotpCode().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/MfaService.java