GMP系统: com.gmp.training.service.impl.TrainingCourseServiceImpl Class Reference
com.gmp.training.service.impl.TrainingCourseServiceImpl Class Reference
培训课程服务实现类
Public Member Functions
TrainingCourseServiceImpl (TrainingCourseRepository repository)
Optional< TrainingCourse > findByCode (String code)
根据课程编码查找培训课程
Optional< TrainingCourse > findByName (String name)
根据课程名称查找培训课程
List< TrainingCourse > findByTrainingPlan (TrainingPlan trainingPlan)
查找特定培训计划的培训课程
List< TrainingCourse > findByStatus (TrainingCourse.Status status)
查找特定状态的培训课程
List< TrainingCourse > findByType (TrainingCourse.Type type)
查找特定类型的培训课程
List< TrainingCourse > findByMethod (TrainingCourse.Method method)
查找特定培训方式的培训课程
List< TrainingCourse > findRecurringCourses ()
查找需要复训的培训课程
List< TrainingCourse > findCompulsoryCourses ()
查找必修的培训课程
List< TrainingCourse > findOptionalCourses ()
查找选修的培训课程
List< TrainingCourse > findByCreationDateBetween (LocalDate startDate, LocalDate endDate)
查找时间范围内创建的培训课程
TrainingCourse updateStatus (Long id, TrainingCourse.Status status)
更新培训课程状态
int batchUpdateStatus (List< Long > ids, TrainingCourse.Status status)
批量更新培训课程状态
List< TrainingCourse > search (String keyword)
搜索培训课程
TrainingCourse save (TrainingCourse course)
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Protected Member Functions
String getEntityName ()
Detailed Description
培训课程服务实现类
Author
GMP系统开发团队
Definition at line 22 of file TrainingCourseServiceImpl.java.
Constructor & Destructor Documentation
TrainingCourseServiceImpl()
com.gmp.training.service.impl.TrainingCourseServiceImpl.TrainingCourseServiceImpl (TrainingCourseRepository repository)
Definition at line 25 of file TrainingCourseServiceImpl.java.
References repository.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingCourseServiceImpl.batchUpdateStatus (List< Long > ids, TrainingCourse.Status status)
批量更新培训课程状态
Parameters
ids 课程ID列表
status 状态
Returns
影响的行数
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 89 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testBatchUpdateStatus().
count()
long com.gmp.training.service.BaseService< T, ID >.count () inherited
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity) inherited
删除实体
Parameters
entity 实体对象
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll () inherited
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities) inherited
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id) inherited
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id) inherited
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll () inherited
查询所有实体
Returns
实体列表
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable) inherited
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort) inherited
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids) inherited
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findByCode()
Optional< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByCode (String code)
根据课程编码查找培训课程
Parameters
code 课程编码
Returns
培训课程信息
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 30 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByCode().
findByCreationDateBetween()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByCreationDateBetween (LocalDate startDate, LocalDate endDate)
查找时间范围内创建的培训课程
Parameters
startDate 开始日期
endDate 结束日期
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 75 of file TrainingCourseServiceImpl.java.
References repository.
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id) inherited
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
findByMethod()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByMethod (TrainingCourse.Method method)
查找特定培训方式的培训课程
Parameters
method 培训方式
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 55 of file TrainingCourseServiceImpl.java.
References repository.
findByName()
Optional< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByName (String name)
根据课程名称查找培训课程
Parameters
name 课程名称
Returns
培训课程信息
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 35 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByName().
findByStatus()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByStatus (TrainingCourse.Status status)
查找特定状态的培训课程
Parameters
status 状态
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 45 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindByStatus().
findByTrainingPlan()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByTrainingPlan (TrainingPlan trainingPlan)
查找特定培训计划的培训课程
Parameters
trainingPlan 培训计划
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 40 of file TrainingCourseServiceImpl.java.
References repository.
findByType()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findByType (TrainingCourse.Type type)
查找特定类型的培训课程
Parameters
type 类型
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 50 of file TrainingCourseServiceImpl.java.
References repository.
findCompulsoryCourses()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findCompulsoryCourses ()
查找必修的培训课程
Returns
必修的培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 65 of file TrainingCourseServiceImpl.java.
References repository.
findOptionalCourses()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findOptionalCourses ()
查找选修的培训课程
Returns
选修的培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 70 of file TrainingCourseServiceImpl.java.
References repository.
findRecurringCourses()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.findRecurringCourses ()
查找需要复训的培训课程
Returns
需要复训的培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 60 of file TrainingCourseServiceImpl.java.
References repository.
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id) inherited
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
getEntityName()
String com.gmp.training.service.impl.TrainingCourseServiceImpl.getEntityName () protected
Definition at line 114 of file TrainingCourseServiceImpl.java.
save() [1/2]
T com.gmp.training.service.BaseService< T, ID >.save (T entity) inherited
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
save() [2/2]
TrainingCourse com.gmp.training.service.impl.TrainingCourseServiceImpl.save (TrainingCourse course)
Definition at line 104 of file TrainingCourseServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testSave().
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities) inherited
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
search()
List< TrainingCourse > com.gmp.training.service.impl.TrainingCourseServiceImpl.search (String keyword)
搜索培训课程
Parameters
keyword 关键词
Returns
培训课程列表
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 97 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testSearch().
updateStatus()
TrainingCourse com.gmp.training.service.impl.TrainingCourseServiceImpl.updateStatus (Long id, TrainingCourse.Status status)
更新培训课程状态
Parameters
id 课程ID
status 状态
Returns
更新后的培训课程
Implements com.gmp.training.service.TrainingCourseService.
Definition at line 81 of file TrainingCourseServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingCourseServiceImplTest.testUpdateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingCourseServiceImpl.java