GMP系统: com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics Class Reference
com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics Class Reference
系统整体指标
Public Member Functions
void incrementActiveCalls ()
void decrementActiveCalls ()
int getActiveCalls ()
int getPeakConcurrentCalls ()
void reset ()
void incrementTotalCalls ()
void incrementSuccessCalls ()
void incrementFailedCalls ()
void recordDuration (long duration)
int getTotalCalls ()
int getSuccessCalls ()
int getFailedCalls ()
long getTotalDuration ()
long getMaxDuration ()
double getAverageDuration ()
double getSuccessRate ()
Private Attributes
final AtomicInteger activeCalls = new AtomicInteger(0)
final AtomicInteger peakConcurrentCalls = new AtomicInteger(0)
final AtomicInteger totalCalls = new AtomicInteger(0)
final AtomicInteger successCalls = new AtomicInteger(0)
final AtomicInteger failedCalls = new AtomicInteger(0)
final AtomicLong totalDuration = new AtomicLong(0)
final AtomicLong maxDuration = new AtomicLong(0)
Detailed Description
系统整体指标
Definition at line 224 of file McpMonitoringService.java.
Member Function Documentation
decrementActiveCalls()
void com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.decrementActiveCalls ()
Definition at line 233 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.activeCalls.
getActiveCalls()
int com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.getActiveCalls ()
Definition at line 237 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.activeCalls.
getAverageDuration()
double com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration () inherited
Definition at line 203 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
getFailedCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getFailedCalls () inherited
Definition at line 191 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls.
getMaxDuration()
long com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getMaxDuration () inherited
Definition at line 199 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration.
getPeakConcurrentCalls()
int com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.getPeakConcurrentCalls ()
Definition at line 241 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.peakConcurrentCalls.
getSuccessCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessCalls () inherited
Definition at line 187 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls.
getSuccessRate()
double com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate () inherited
Definition at line 208 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
getTotalCalls()
int com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalCalls () inherited
Definition at line 183 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
getTotalDuration()
long com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalDuration () inherited
Definition at line 195 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
incrementActiveCalls()
void com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.incrementActiveCalls ()
Definition at line 228 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.activeCalls, and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.peakConcurrentCalls.
incrementFailedCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementFailedCalls () inherited
Definition at line 174 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
incrementSuccessCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementSuccessCalls () inherited
Definition at line 170 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
incrementTotalCalls()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls () inherited
Definition at line 166 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.startResourceAccess(), and com.gmp.qms.monitoring.McpMonitoringService.startToolCall().
recordDuration()
void com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration (long duration) inherited
Definition at line 178 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.endCall().
reset()
void com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset ()
Definition at line 245 of file McpMonitoringService.java.
References com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.activeCalls, com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls, com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration, com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.peakConcurrentCalls, com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls, com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls, and com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.resetMetrics().
Member Data Documentation
activeCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.activeCalls = new AtomicInteger(0) private
Definition at line 225 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.decrementActiveCalls(), com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.getActiveCalls(), com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.incrementActiveCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
failedCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.failedCalls = new AtomicInteger(0) private inherited
Definition at line 162 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getFailedCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementFailedCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
maxDuration
final AtomicLong com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.maxDuration = new AtomicLong(0) private inherited
Definition at line 164 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getMaxDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
peakConcurrentCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.peakConcurrentCalls = new AtomicInteger(0) private
Definition at line 226 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.getPeakConcurrentCalls(), com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.incrementActiveCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
successCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.successCalls = new AtomicInteger(0) private inherited
Definition at line 161 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementSuccessCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
totalCalls
final AtomicInteger com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalCalls = new AtomicInteger(0) private inherited
Definition at line 160 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getSuccessRate(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalCalls(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.incrementTotalCalls(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
totalDuration
final AtomicLong com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.totalDuration = new AtomicLong(0) private inherited
Definition at line 163 of file McpMonitoringService.java.
Referenced by com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getAverageDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.getTotalDuration(), com.gmp.qms.monitoring.McpMonitoringService.ToolMetrics.recordDuration(), and com.gmp.qms.monitoring.McpMonitoringService.SystemMetrics.reset().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/monitoring/McpMonitoringService.java