GMP系统: com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl Class Reference
com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl Class Reference
用户组织角色关联服务实现 管理用户、组织、角色三者之间的关联关系
Public Member Functions
UserOrganizationRole assignRoleToUserInOrganization (Long userId, Long organizationId, Long roleId, Long assignedBy, String assignmentReason, LocalDateTime effectiveUntil)
为用户分配组织角色
List< UserOrganizationRole > assignRolesToUserInOrganizations (Long userId, Map< Long, List< Long > > orgRoleAssignments, Long assignedBy, String assignmentReason)
批量为用户分配组织角色
void removeRoleFromUserInOrganization (Long userId, Long organizationId, Long roleId)
从组织中移除用户角色
List< UserOrganizationRole > getUserOrganizationRoles (Long userId)
获取用户在所有组织中的有效角色
List< UserOrganizationRole > getUserOrganizationRolesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的有效角色
Set< Long > getUserOrganizations (Long userId)
获取用户拥有的所有组织
Set< String > getUserRoleCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的角色代码
Set< String > getUserPermissionCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的权限代码
Set< String > getUserPermissionCodesAcrossOrganizations (Long userId)
获取用户在所有组织中的所有权限
boolean hasRoleInOrganization (Long userId, Long organizationId, String roleCode)
检查用户在指定组织中是否拥有特定角色
boolean hasPermissionInOrganization (Long userId, Long organizationId, String permissionCode)
检查用户在指定组织中是否拥有特定权限
UserOrganizationRole updateStatus (Long id, UserOrganizationRole.AssignmentStatus status, Long updatedBy)
更新用户组织角色状态
UserOrganizationRole approveAssignment (Long id, boolean approved, Long approvedBy, String approvalNote)
审批用户组织角色分配
void refreshExpiredAssignments ()
刷新过期的用户组织角色关联
List< UserOrganizationRole > getExpiringSoonAssignments (int warningDays)
获取即将过期的用户组织角色关联
List< UserOrganizationRole > getOrganizationUserRoles (Long organizationId)
获取组织中的所有用户角色关联
List< UserOrganizationRole > getRoleUserOrganizations (Long roleId)
获取拥有特定角色的所有用户组织关联
boolean hasOrganizationAccess (Long userId, Long organizationId)
检查用户是否有权限访问指定组织
List< String > getUserAccessibleSubsystems (Long userId, Long organizationId)
获取用户可访问的子系统列表
Map< String, Integer > getUserSubsystemAccessLevels (Long userId, Long organizationId)
获取用户子系统访问级别
Private Attributes
UserOrganizationRoleRepository userOrgRoleRepository
UserRepository userRepository
OrganizationRepository organizationRepository
RoleRepository roleRepository
RolePermissionRepository rolePermissionRepository
Static Private Attributes
static final Set< UserOrganizationRole.AssignmentStatus > ACTIVE_STATUSES
Detailed Description
用户组织角色关联服务实现 管理用户、组织、角色三者之间的关联关系
Definition at line 27 of file UserOrganizationRoleServiceImpl.java.
Member Function Documentation
approveAssignment()
UserOrganizationRole com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.approveAssignment (Long id, boolean approved, Long approvedBy, String approvalNote)
审批用户组织角色分配
Parameters
id 关联ID
approved 是否批准
approvedBy 审批人ID
approvalNote 审批意见
Returns
更新后的关联实体
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 220 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
assignRolesToUserInOrganizations()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRolesToUserInOrganizations (Long userId, Map< Long, List< Long > > orgRoleAssignments, Long assignedBy, String assignmentReason)
批量为用户分配组织角色
Parameters
userId 用户ID
orgRoleAssignments 组织角色分配映射
assignedBy 分配人ID
assignmentReason 分配理由
Returns
创建的关联实体列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 93 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization().
assignRoleToUserInOrganization()
UserOrganizationRole com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization (Long userId, Long organizationId, Long roleId, Long assignedBy, String assignmentReason, LocalDateTime effectiveUntil)
为用户分配组织角色
Parameters
userId 用户ID
organizationId 组织ID
roleId 角色ID
assignedBy 分配人ID
assignmentReason 分配理由
effectiveUntil 有效期至
Returns
创建的关联实体
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 52 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.organizationRepository, com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.roleRepository, com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userRepository.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRolesToUserInOrganizations().
getExpiringSoonAssignments()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getExpiringSoonAssignments (int warningDays)
获取即将过期的用户组织角色关联
Parameters
warningDays 预警天数
Returns
即将过期的关联列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 259 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
getOrganizationUserRoles()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getOrganizationUserRoles (Long organizationId)
获取组织中的所有用户角色关联
Parameters
organizationId 组织ID
Returns
关联列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 267 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
getRoleUserOrganizations()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getRoleUserOrganizations (Long roleId)
获取拥有特定角色的所有用户组织关联
Parameters
roleId 角色ID
Returns
关联列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 273 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
getUserAccessibleSubsystems()
List< String > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserAccessibleSubsystems (Long userId, Long organizationId)
获取用户可访问的子系统列表
Parameters
userId 用户ID
organizationId 组织ID
Returns
子系统代码列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 293 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRolesInOrganization(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.roleRepository.
getUserOrganizationRoles()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRoles (Long userId)
获取用户在所有组织中的有效角色
Parameters
userId 用户ID
Returns
用户组织角色关联列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 139 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
getUserOrganizationRolesInOrganization()
List< UserOrganizationRole > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRolesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的有效角色
Parameters
userId 用户ID
organizationId 组织ID
Returns
用户组织角色关联列表
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 145 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserAccessibleSubsystems(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserSubsystemAccessLevels().
getUserOrganizations()
Set< Long > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizations (Long userId)
获取用户拥有的所有组织
Parameters
userId 用户ID
Returns
组织ID集合
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 152 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesAcrossOrganizations().
getUserPermissionCodesAcrossOrganizations()
Set< String > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesAcrossOrganizations (Long userId)
获取用户在所有组织中的所有权限
Parameters
userId 用户ID
Returns
权限代码集合
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 180 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizations(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesInOrganization().
getUserPermissionCodesInOrganization()
Set< String > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的权限代码
Parameters
userId 用户ID
organizationId 组织ID
Returns
权限代码集合
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 166 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserRoleCodesInOrganization().
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesAcrossOrganizations(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasPermissionInOrganization().
getUserRoleCodesInOrganization()
Set< String > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserRoleCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的角色代码
Parameters
userId 用户ID
organizationId 组织ID
Returns
角色代码集合
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 159 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesInOrganization(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasRoleInOrganization().
getUserSubsystemAccessLevels()
Map< String, Integer > com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserSubsystemAccessLevels (Long userId, Long organizationId)
获取用户子系统访问级别
Parameters
userId 用户ID
organizationId 组织ID
Returns
子系统访问级别映射
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 365 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRolesInOrganization(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.roleRepository.
hasOrganizationAccess()
boolean com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasOrganizationAccess (Long userId, Long organizationId)
检查用户是否有权限访问指定组织
Parameters
userId 用户ID
organizationId 组织ID
Returns
是否有权限访问
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 279 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
hasPermissionInOrganization()
boolean com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasPermissionInOrganization (Long userId, Long organizationId, String permissionCode)
检查用户在指定组织中是否拥有特定权限
Parameters
userId 用户ID
organizationId 组织ID
permissionCode 权限代码
Returns
是否拥有该权限
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 200 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserPermissionCodesInOrganization().
hasRoleInOrganization()
boolean com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasRoleInOrganization (Long userId, Long organizationId, String roleCode)
检查用户在指定组织中是否拥有特定角色
Parameters
userId 用户ID
organizationId 组织ID
roleCode 角色代码
Returns
是否拥有该角色
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 193 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserRoleCodesInOrganization().
refreshExpiredAssignments()
void com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.refreshExpiredAssignments ()
刷新过期的用户组织角色关联
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 243 of file UserOrganizationRoleServiceImpl.java.
removeRoleFromUserInOrganization()
void com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.removeRoleFromUserInOrganization (Long userId, Long organizationId, Long roleId)
从组织中移除用户角色
Parameters
userId 用户ID
organizationId 组织ID
roleId 角色ID
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 121 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES, and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
updateStatus()
UserOrganizationRole com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.updateStatus (Long id, UserOrganizationRole.AssignmentStatus status, Long updatedBy)
更新用户组织角色状态
Parameters
id 关联ID
status 新状态
updatedBy 更新人ID
Returns
更新后的关联实体
Implements com.gmp.auth.service.UserOrganizationRoleService.
Definition at line 206 of file UserOrganizationRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository.
Member Data Documentation
ACTIVE_STATUSES
final Set<UserOrganizationRole.AssignmentStatus> com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.ACTIVE_STATUSES static private
Initial value:
=
            Collections.unmodifiableSet(EnumSet.of(
                    UserOrganizationRole.AssignmentStatus.ACTIVE,
                    UserOrganizationRole.AssignmentStatus.APPROVED
            ))
Definition at line 45 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getExpiringSoonAssignments(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getOrganizationUserRoles(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getRoleUserOrganizations(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRoles(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRolesInOrganization(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasOrganizationAccess(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.removeRoleFromUserInOrganization().
organizationRepository
OrganizationRepository com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.organizationRepository private
Definition at line 36 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization().
rolePermissionRepository
RolePermissionRepository com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.rolePermissionRepository private
Definition at line 42 of file UserOrganizationRoleServiceImpl.java.
roleRepository
RoleRepository com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.roleRepository private
Definition at line 39 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserAccessibleSubsystems(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserSubsystemAccessLevels().
userOrgRoleRepository
UserOrganizationRoleRepository com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userOrgRoleRepository private
Definition at line 30 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.approveAssignment(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getExpiringSoonAssignments(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getOrganizationUserRoles(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getRoleUserOrganizations(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRoles(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.getUserOrganizationRolesInOrganization(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.hasOrganizationAccess(), com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.removeRoleFromUserInOrganization(), and com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.updateStatus().
userRepository
UserRepository com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.userRepository private
Definition at line 33 of file UserOrganizationRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.assignRoleToUserInOrganization().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/UserOrganizationRoleServiceImpl.java