GMP系统: com.gmp.qms.util.McpVersionControl Class Reference
com.gmp.qms.util.McpVersionControl Class Reference
MCP版本控制工具类 提供版本号解析、比较、兼容性检查等功能 遵循语义化版本控制规范 (Semantic Versioning)
Public Member Functions
String getCurrentVersion ()
获取当前系统版本
int[] parseVersion (String version)
解析版本号为整数数组 [MAJOR, MINOR, PATCH]
int compareVersions (String version1, String version2)
比较两个版本号的大小
boolean isCompatible (String clientVersion)
检查客户端版本是否兼容
String getCompatibilityInfo (String clientVersion)
获取兼容性信息
boolean isValidVersion (String version)
验证版本号格式是否正确
String getUpgradePath (String fromVersion, String toVersion)
获取版本升级路径建议
void logVersionWarning (String clientVersion, String systemName)
记录版本兼容性警告
Static Private Attributes
static final String CURRENT_VERSION = "1.0.0"
static final Pattern VERSION_PATTERN = Pattern.compile("^(\\d+)\\.(\\d+)\\.(\\d+)(?:-(\\w+\\.?\\w*))?(?:\\+(\\w+))?$")
Detailed Description
MCP版本控制工具类 提供版本号解析、比较、兼容性检查等功能 遵循语义化版本控制规范 (Semantic Versioning)
Definition at line 17 of file McpVersionControl.java.
Member Function Documentation
compareVersions()
int com.gmp.qms.util.McpVersionControl.compareVersions (String version1, String version2)
比较两个版本号的大小
Parameters
version1 第一个版本号
version2 第二个版本号
Returns
如果version1 > version2返回1，如果version1 < version2返回-1，如果相等返回0
Definition at line 62 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.parseVersion().
Referenced by com.gmp.qms.util.McpVersionControl.getCompatibilityInfo(), and com.gmp.qms.util.McpVersionControl.getUpgradePath().
getCompatibilityInfo()
String com.gmp.qms.util.McpVersionControl.getCompatibilityInfo (String clientVersion)
获取兼容性信息
Parameters
clientVersion 客户端版本
Returns
兼容性信息字符串
Definition at line 113 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.compareVersions(), com.gmp.qms.util.McpVersionControl.CURRENT_VERSION, and com.gmp.qms.util.McpVersionControl.isCompatible().
getCurrentVersion()
String com.gmp.qms.util.McpVersionControl.getCurrentVersion ()
获取当前系统版本
Returns
当前版本号
Definition at line 26 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.CURRENT_VERSION.
getUpgradePath()
String com.gmp.qms.util.McpVersionControl.getUpgradePath (String fromVersion, String toVersion)
获取版本升级路径建议
Parameters
fromVersion 从哪个版本开始
toVersion 目标版本
Returns
升级路径建议
Definition at line 155 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.compareVersions(), com.gmp.qms.util.McpVersionControl.isValidVersion(), and com.gmp.qms.util.McpVersionControl.parseVersion().
isCompatible()
boolean com.gmp.qms.util.McpVersionControl.isCompatible (String clientVersion)
检查客户端版本是否兼容
Parameters
clientVersion 客户端版本
Returns
是否兼容
Definition at line 82 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.CURRENT_VERSION, and com.gmp.qms.util.McpVersionControl.parseVersion().
Referenced by com.gmp.qms.util.McpVersionControl.getCompatibilityInfo(), and com.gmp.qms.util.McpVersionControl.logVersionWarning().
isValidVersion()
boolean com.gmp.qms.util.McpVersionControl.isValidVersion (String version)
验证版本号格式是否正确
Parameters
version 版本号字符串
Returns
格式是否正确
Definition at line 142 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.VERSION_PATTERN.
Referenced by com.gmp.qms.util.McpVersionControl.getUpgradePath().
logVersionWarning()
void com.gmp.qms.util.McpVersionControl.logVersionWarning (String clientVersion, String systemName)
记录版本兼容性警告
Parameters
clientVersion 客户端版本
systemName 系统名称
Definition at line 222 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.CURRENT_VERSION, and com.gmp.qms.util.McpVersionControl.isCompatible().
parseVersion()
int[] com.gmp.qms.util.McpVersionControl.parseVersion (String version)
解析版本号为整数数组 [MAJOR, MINOR, PATCH]
Parameters
version 版本号字符串
Returns
解析后的版本号数组，格式为 [MAJOR, MINOR, PATCH]
Exceptions
IllegalArgumentException 当版本号格式不正确时抛出
Definition at line 39 of file McpVersionControl.java.
References com.gmp.qms.util.McpVersionControl.VERSION_PATTERN.
Referenced by com.gmp.qms.util.McpVersionControl.compareVersions(), com.gmp.qms.util.McpVersionControl.getUpgradePath(), and com.gmp.qms.util.McpVersionControl.isCompatible().
Member Data Documentation
CURRENT_VERSION
final String com.gmp.qms.util.McpVersionControl.CURRENT_VERSION = "1.0.0" static private
Definition at line 20 of file McpVersionControl.java.
Referenced by com.gmp.qms.util.McpVersionControl.getCompatibilityInfo(), com.gmp.qms.util.McpVersionControl.getCurrentVersion(), com.gmp.qms.util.McpVersionControl.isCompatible(), and com.gmp.qms.util.McpVersionControl.logVersionWarning().
VERSION_PATTERN
final Pattern com.gmp.qms.util.McpVersionControl.VERSION_PATTERN = Pattern.compile("^(\\d+)\\.(\\d+)\\.(\\d+)(?:-(\\w+\\.?\\w*))?(?:\\+(\\w+))?$") static private
Definition at line 31 of file McpVersionControl.java.
Referenced by com.gmp.qms.util.McpVersionControl.isValidVersion(), and com.gmp.qms.util.McpVersionControl.parseVersion().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/util/McpVersionControl.java