GMP系统: com.gmp.hr.service.impl.TrainingRecordServiceImpl Class Reference
com.gmp.hr.service.impl.TrainingRecordServiceImpl Class Reference
培训记录服务实现类
Public Member Functions
TrainingRecordDTO createTrainingRecord (TrainingRecordDTO trainingRecordDTO)
创建培训记录
TrainingRecordDTO getTrainingRecordById (Long id)
根据ID获取培训记录
TrainingRecordDTO updateTrainingRecord (Long id, TrainingRecordDTO trainingRecordDTO)
更新培训记录
void deleteTrainingRecord (Long id)
删除培训记录
List< TrainingRecordDTO > getAllTrainingRecords ()
获取所有培训记录
List< TrainingRecordDTO > getTrainingRecordsByEmployee (Long employeeId)
根据员工ID获取培训记录列表
List< TrainingRecordDTO > getTrainingRecordsByType (String trainingType)
根据培训类型获取培训记录列表
List< TrainingRecordDTO > getTrainingRecordsByDateRange (Date startDate, Date endDate)
根据日期范围查询培训记录
List< TrainingRecordDTO > getTrainingRecordsByResult (String result)
根据考核结果查询培训记录
List< TrainingRecordDTO > getTrainingRecordsByTrainer (String trainer)
根据培训机构查询培训记录
List< TrainingRecordDTO > getTrainingRecordsByDepartment (Long departmentId)
查询指定部门的培训记录
List< TrainingRecordDTO > getUpcomingTrainings (int daysThreshold)
查询即将进行的培训
int getEmployeeTrainingHoursByYear (Long employeeId, int year)
获取员工年度培训总时长
Private Member Functions
TrainingRecordDTO convertToDTO (TrainingRecord trainingRecord)
将培训记录实体转换为DTO
Private Attributes
TrainingRecordRepository trainingRecordRepository
EmployeeRepository employeeRepository
DepartmentRepository departmentRepository
Detailed Description
培训记录服务实现类
Author
GMP Team
Version
1.0.0
Definition at line 28 of file TrainingRecordServiceImpl.java.
Member Function Documentation
convertToDTO()
TrainingRecordDTO com.gmp.hr.service.impl.TrainingRecordServiceImpl.convertToDTO (TrainingRecord trainingRecord) private
将培训记录实体转换为DTO
Parameters
trainingRecord 培训记录实体
Returns
培训记录DTO
Definition at line 258 of file TrainingRecordServiceImpl.java.
Referenced by com.gmp.hr.service.impl.TrainingRecordServiceImpl.createTrainingRecord(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordById(), and com.gmp.hr.service.impl.TrainingRecordServiceImpl.updateTrainingRecord().
createTrainingRecord()
TrainingRecordDTO com.gmp.hr.service.impl.TrainingRecordServiceImpl.createTrainingRecord (TrainingRecordDTO trainingRecordDTO)
创建培训记录
Parameters
trainingRecordDTO 培训记录DTO
Returns
创建的培训记录DTO
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 41 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.convertToDTO(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.employeeRepository, and com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
Referenced by com.gmp.hr.service.impl.TrainingRecordServiceImplTest.testCreateTrainingRecord_Success().
deleteTrainingRecord()
void com.gmp.hr.service.impl.TrainingRecordServiceImpl.deleteTrainingRecord (Long id)
删除培训记录
Parameters
id 培训记录ID
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 162 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
getAllTrainingRecords()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getAllTrainingRecords ()
获取所有培训记录
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 175 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
getEmployeeTrainingHoursByYear()
int com.gmp.hr.service.impl.TrainingRecordServiceImpl.getEmployeeTrainingHoursByYear (Long employeeId, int year)
获取员工年度培训总时长
Parameters
employeeId 员工ID
year 年份
Returns
培训总时长（小时）
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 242 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.employeeRepository.
getTrainingRecordById()
TrainingRecordDTO com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordById (Long id)
根据ID获取培训记录
Parameters
id 培训记录ID
Returns
培训记录DTO
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 82 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
getTrainingRecordsByDateRange()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByDateRange (Date startDate, Date endDate)
根据日期范围查询培训记录
Parameters
startDate 开始日期
endDate 结束日期
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 207 of file TrainingRecordServiceImpl.java.
getTrainingRecordsByDepartment()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByDepartment (Long departmentId)
查询指定部门的培训记录
Parameters
departmentId 部门ID
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 225 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.departmentRepository.
getTrainingRecordsByEmployee()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByEmployee (Long employeeId)
根据员工ID获取培训记录列表
Parameters
employeeId 员工ID
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 184 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.employeeRepository, and com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
getTrainingRecordsByResult()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByResult (String result)
根据考核结果查询培训记录
Parameters
result 考核结果（如：优秀、良好、合格、不合格）
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 213 of file TrainingRecordServiceImpl.java.
getTrainingRecordsByTrainer()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByTrainer (String trainer)
根据培训机构查询培训记录
Parameters
trainer 培训机构/人员
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 219 of file TrainingRecordServiceImpl.java.
getTrainingRecordsByType()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByType (String trainingType)
根据培训类型获取培训记录列表
Parameters
trainingType 培训类型
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 201 of file TrainingRecordServiceImpl.java.
getUpcomingTrainings()
List< TrainingRecordDTO > com.gmp.hr.service.impl.TrainingRecordServiceImpl.getUpcomingTrainings (int daysThreshold)
查询即将进行的培训
Parameters
daysThreshold 天数阈值
Returns
培训记录DTO列表
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 236 of file TrainingRecordServiceImpl.java.
updateTrainingRecord()
TrainingRecordDTO com.gmp.hr.service.impl.TrainingRecordServiceImpl.updateTrainingRecord (Long id, TrainingRecordDTO trainingRecordDTO)
更新培训记录
Parameters
id 培训记录ID
trainingRecordDTO 培训记录DTO
Returns
更新后的培训记录DTO
Implements com.gmp.hr.service.TrainingRecordService.
Definition at line 92 of file TrainingRecordServiceImpl.java.
References com.gmp.hr.service.impl.TrainingRecordServiceImpl.convertToDTO(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.employeeRepository, and com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository.
Member Data Documentation
departmentRepository
DepartmentRepository com.gmp.hr.service.impl.TrainingRecordServiceImpl.departmentRepository private
Definition at line 37 of file TrainingRecordServiceImpl.java.
Referenced by com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByDepartment().
employeeRepository
EmployeeRepository com.gmp.hr.service.impl.TrainingRecordServiceImpl.employeeRepository private
Definition at line 34 of file TrainingRecordServiceImpl.java.
Referenced by com.gmp.hr.service.impl.TrainingRecordServiceImpl.createTrainingRecord(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getEmployeeTrainingHoursByYear(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByEmployee(), and com.gmp.hr.service.impl.TrainingRecordServiceImpl.updateTrainingRecord().
trainingRecordRepository
TrainingRecordRepository com.gmp.hr.service.impl.TrainingRecordServiceImpl.trainingRecordRepository private
Definition at line 31 of file TrainingRecordServiceImpl.java.
Referenced by com.gmp.hr.service.impl.TrainingRecordServiceImpl.createTrainingRecord(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.deleteTrainingRecord(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getAllTrainingRecords(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordById(), com.gmp.hr.service.impl.TrainingRecordServiceImpl.getTrainingRecordsByEmployee(), and com.gmp.hr.service.impl.TrainingRecordServiceImpl.updateTrainingRecord().
The documentation for this class was generated from the following file:
hr-service/src/main/java/com/gmp/hr/service/impl/TrainingRecordServiceImpl.java