GMP系统: com.gmp.mes.service.BatchOperationService Class Reference
com.gmp.mes.service.BatchOperationService Class Reference
批操作服务 - 实现批次执行过程中的操作管理和记录功能
Public Member Functions
BatchOperation createBatchOperation (BatchOperation batchOperation)
创建批操作
Optional< BatchOperation > getBatchOperationById (Long id)
获取批操作
Optional< BatchOperation > getBatchOperationByNumber (String operationNumber)
根据操作编号获取批操作
List< BatchOperation > getBatchOperationsByBatchId (Long batchId)
获取批次的所有操作
List< BatchOperation > getBatchOperationsByType (Long batchId, String operationType)
获取批次的特定类型操作
BatchOperation updateBatchOperation (BatchOperation batchOperation)
更新批操作
BatchOperation startBatchOperation (long id, String operator)
开始执行批操作 - 兼容版本 为了兼容测试代码中使用的方法签名
BatchOperation startBatchOperation (Long id, Map< String, Object > parameters, String operator)
开始执行批操作
BatchOperation completeBatchOperation (Long id, Map< String, Object > results, String operator)
完成批操作
BatchOperation cancelBatchOperation (Long id, String reason, String operator)
取消批操作
BatchOperation failBatchOperation (Long id, Map< String, Object > errorDetails, String operator)
标记批操作为失败
void deleteBatchOperation (Long id)
删除批操作
BatchOperation getBatchOperationByOperationNumber (String operationNumber)
根据操作编号获取批操作 - 兼容方法 为了兼容测试代码中使用的方法名
BatchOperation markBatchOperationFailed (Long id, String reason, String operator)
标记批操作为失败 - 兼容方法 为了兼容测试代码中使用的方法签名
List< BatchOperation > findBatchOperationsByStatus (BatchOperation.OperationStatus status)
根据状态查找批操作列表
List< BatchOperation > getAllBatchOperations ()
获取所有批操作 - 兼容方法 为了兼容测试代码中的方法调用
String generateOperationNumber ()
生成唯一的操作编号
BatchOperation updateOperationParameters (Long id, Map< String, Object > parameters)
更新操作参数
BatchOperation addOperationRemark (Long id, String remark)
添加操作备注
Private Attributes
BatchOperationRepository batchOperationRepository
ObjectMapper objectMapper
ProductionBatchRepository productionBatchRepository
Detailed Description
批操作服务 - 实现批次执行过程中的操作管理和记录功能
Author
gmp-system
Definition at line 24 of file BatchOperationService.java.
Member Function Documentation
addOperationRemark()
BatchOperation com.gmp.mes.service.BatchOperationService.addOperationRemark (Long id, String remark)
添加操作备注
Parameters
id 批操作ID
remark 备注内容
Returns
更新后的批操作
Definition at line 398 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testAddOperationRemark().
cancelBatchOperation()
BatchOperation com.gmp.mes.service.BatchOperationService.cancelBatchOperation (Long id, String reason, String operator)
取消批操作
Parameters
id 批操作ID
reason 取消原因
operator 操作人员
Returns
更新后的批操作
Definition at line 224 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testCancelBatchOperation().
completeBatchOperation()
BatchOperation com.gmp.mes.service.BatchOperationService.completeBatchOperation (Long id, Map< String, Object > results, String operator)
完成批操作
Parameters
id 批操作ID
results 操作结果
operator 操作人员
Returns
更新后的批操作
Definition at line 189 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, and com.gmp.mes.service.BatchOperationService.objectMapper.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testCompleteBatchOperation().
createBatchOperation()
BatchOperation com.gmp.mes.service.BatchOperationService.createBatchOperation (BatchOperation batchOperation)
创建批操作
Parameters
batchOperation 批操作对象
Returns
创建的批操作
Definition at line 42 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, and com.gmp.mes.service.BatchOperationService.productionBatchRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testCreateBatchOperation().
deleteBatchOperation()
void com.gmp.mes.service.BatchOperationService.deleteBatchOperation (Long id)
删除批操作
Parameters
id 批操作ID
Definition at line 290 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testDeleteBatchOperation().
failBatchOperation()
BatchOperation com.gmp.mes.service.BatchOperationService.failBatchOperation (Long id, Map< String, Object > errorDetails, String operator)
标记批操作为失败
Parameters
id 批操作ID
errorDetails 错误详情
operator 操作人员
Returns
更新后的批操作
Definition at line 256 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, and com.gmp.mes.service.BatchOperationService.objectMapper.
Referenced by com.gmp.mes.service.BatchOperationService.markBatchOperationFailed().
findBatchOperationsByStatus()
List< BatchOperation > com.gmp.mes.service.BatchOperationService.findBatchOperationsByStatus (BatchOperation.OperationStatus status)
根据状态查找批操作列表
Parameters
status 操作状态
Returns
批操作列表
Definition at line 334 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testFindBatchOperationsByStatus().
generateOperationNumber()
String com.gmp.mes.service.BatchOperationService.generateOperationNumber ()
生成唯一的操作编号
Returns
操作编号
Definition at line 355 of file BatchOperationService.java.
Referenced by com.gmp.mes.service.BatchOperationService.startBatchOperation(), and com.gmp.mes.service.BatchOperationServiceTest.testGenerateOperationNumber().
getAllBatchOperations()
List< BatchOperation > com.gmp.mes.service.BatchOperationService.getAllBatchOperations ()
获取所有批操作 - 兼容方法 为了兼容测试代码中的方法调用
Returns
所有批操作列表
Definition at line 345 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testGetAllBatchOperations().
getBatchOperationById()
Optional< BatchOperation > com.gmp.mes.service.BatchOperationService.getBatchOperationById (Long id)
获取批操作
Parameters
id 批操作ID
Returns
批操作对象
Definition at line 70 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testGetBatchOperationById().
getBatchOperationByNumber()
Optional< BatchOperation > com.gmp.mes.service.BatchOperationService.getBatchOperationByNumber (String operationNumber)
根据操作编号获取批操作
Parameters
operationNumber 操作编号
Returns
批操作对象
Definition at line 80 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationService.getBatchOperationByOperationNumber().
getBatchOperationByOperationNumber()
BatchOperation com.gmp.mes.service.BatchOperationService.getBatchOperationByOperationNumber (String operationNumber)
根据操作编号获取批操作 - 兼容方法 为了兼容测试代码中使用的方法名
Parameters
operationNumber 操作编号
Returns
批操作对象
Definition at line 301 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.getBatchOperationByNumber().
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testGetBatchOperationByOperationNumber().
getBatchOperationsByBatchId()
List< BatchOperation > com.gmp.mes.service.BatchOperationService.getBatchOperationsByBatchId (Long batchId)
获取批次的所有操作
Parameters
batchId 批次ID
Returns
批操作列表
Definition at line 93 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testGetBatchOperationsByBatchId().
getBatchOperationsByType()
List< BatchOperation > com.gmp.mes.service.BatchOperationService.getBatchOperationsByType (Long batchId, String operationType)
获取批次的特定类型操作
Parameters
batchId 批次ID
operationType 操作类型
Returns
批操作列表
Definition at line 104 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
markBatchOperationFailed()
BatchOperation com.gmp.mes.service.BatchOperationService.markBatchOperationFailed (Long id, String reason, String operator)
标记批操作为失败 - 兼容方法 为了兼容测试代码中使用的方法签名
Parameters
id 批操作ID
reason 失败原因
operator 操作人员
Returns
更新后的批操作
Definition at line 317 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, and com.gmp.mes.service.BatchOperationService.failBatchOperation().
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testMarkBatchOperationFailed().
startBatchOperation() [1/2]
BatchOperation com.gmp.mes.service.BatchOperationService.startBatchOperation (Long id, Map< String, Object > parameters, String operator)
开始执行批操作
Parameters
id 批操作ID
parameters 操作参数
operator 操作人员
Returns
更新后的批操作
Definition at line 147 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, com.gmp.mes.service.BatchOperationService.generateOperationNumber(), and com.gmp.mes.service.BatchOperationService.objectMapper.
startBatchOperation() [2/2]
BatchOperation com.gmp.mes.service.BatchOperationService.startBatchOperation (long id, String operator)
开始执行批操作 - 兼容版本 为了兼容测试代码中使用的方法签名
Parameters
id 批操作ID
operator 操作人员
Returns
更新后的批操作
Definition at line 133 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.startBatchOperation().
Referenced by com.gmp.mes.service.BatchOperationService.startBatchOperation(), and com.gmp.mes.service.BatchOperationServiceTest.testStartBatchOperation().
updateBatchOperation()
BatchOperation com.gmp.mes.service.BatchOperationService.updateBatchOperation (BatchOperation batchOperation)
更新批操作
Parameters
batchOperation 批操作对象
Returns
更新后的批操作
Definition at line 120 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testUpdateBatchOperation().
updateOperationParameters()
BatchOperation com.gmp.mes.service.BatchOperationService.updateOperationParameters (Long id, Map< String, Object > parameters)
更新操作参数
Parameters
id 批操作ID
parameters 新的操作参数
Returns
更新后的批操作
Definition at line 370 of file BatchOperationService.java.
References com.gmp.mes.service.BatchOperationService.batchOperationRepository, and com.gmp.mes.service.BatchOperationService.objectMapper.
Referenced by com.gmp.mes.service.BatchOperationServiceTest.testUpdateOperationParameters().
Member Data Documentation
batchOperationRepository
BatchOperationRepository com.gmp.mes.service.BatchOperationService.batchOperationRepository private
Definition at line 27 of file BatchOperationService.java.
Referenced by com.gmp.mes.service.BatchOperationService.addOperationRemark(), com.gmp.mes.service.BatchOperationService.cancelBatchOperation(), com.gmp.mes.service.BatchOperationService.completeBatchOperation(), com.gmp.mes.service.BatchOperationService.createBatchOperation(), com.gmp.mes.service.BatchOperationService.deleteBatchOperation(), com.gmp.mes.service.BatchOperationService.failBatchOperation(), com.gmp.mes.service.BatchOperationService.findBatchOperationsByStatus(), com.gmp.mes.service.BatchOperationService.getAllBatchOperations(), com.gmp.mes.service.BatchOperationService.getBatchOperationById(), com.gmp.mes.service.BatchOperationService.getBatchOperationByNumber(), com.gmp.mes.service.BatchOperationService.getBatchOperationsByBatchId(), com.gmp.mes.service.BatchOperationService.getBatchOperationsByType(), com.gmp.mes.service.BatchOperationService.markBatchOperationFailed(), com.gmp.mes.service.BatchOperationService.startBatchOperation(), com.gmp.mes.service.BatchOperationService.updateBatchOperation(), and com.gmp.mes.service.BatchOperationService.updateOperationParameters().
objectMapper
ObjectMapper com.gmp.mes.service.BatchOperationService.objectMapper private
Definition at line 30 of file BatchOperationService.java.
Referenced by com.gmp.mes.service.BatchOperationService.completeBatchOperation(), com.gmp.mes.service.BatchOperationService.failBatchOperation(), com.gmp.mes.service.BatchOperationService.startBatchOperation(), and com.gmp.mes.service.BatchOperationService.updateOperationParameters().
productionBatchRepository
ProductionBatchRepository com.gmp.mes.service.BatchOperationService.productionBatchRepository private
Definition at line 33 of file BatchOperationService.java.
Referenced by com.gmp.mes.service.BatchOperationService.createBatchOperation().
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/service/BatchOperationService.java