GMP系统: com.gmp.edms.service.MinioFileStorageServiceIntegrationTest Class Reference
com.gmp.edms.service.MinioFileStorageServiceIntegrationTest Class Reference
MinIO文件存储服务集成测试
Package Functions
void setUp () throws Exception
void tearDown () throws Exception
void testUploadFile_Success () throws Exception
void testDownloadFile_Success () throws Exception
void testDeleteFile_Success () throws Exception
void testBatchDeleteFiles_Success () throws Exception
void testGeneratePresignedUrl_Success () throws Exception
void testGetFileInfo_Success () throws Exception
void testCopyFile_Success () throws Exception
void testMoveFile_Success () throws Exception
void testCreateDirectory_Success () throws Exception
void testListFiles_Success () throws Exception
void testGetBucketStorageInfo_Success () throws Exception
Private Member Functions
boolean bucketExists (String bucketName)
boolean fileExists (String bucketName, String filePath)
boolean directoryExists (String bucketName, String directoryPath)
List< String > listObjects (String bucketName, String prefix)
String readFileContent (String bucketName, String filePath) throws Exception
Private Attributes
FileStorageService fileStorageService
MinioClient minioClient
Static Private Attributes
static final String TEST_BUCKET = "test-bucket"
static final String TEST_PREFIX = "test/"
Detailed Description
MinIO文件存储服务集成测试
Definition at line 26 of file MinioFileStorageServiceIntegrationTest.java.
Member Function Documentation
bucketExists()
boolean com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.bucketExists (String bucketName) private
Definition at line 314 of file MinioFileStorageServiceIntegrationTest.java.
directoryExists()
boolean com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.directoryExists (String bucketName, String directoryPath) private
Definition at line 340 of file MinioFileStorageServiceIntegrationTest.java.
fileExists()
boolean com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.fileExists (String bucketName, String filePath) private
Definition at line 326 of file MinioFileStorageServiceIntegrationTest.java.
listObjects()
List< String > com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.listObjects (String bucketName, String prefix) private
Definition at line 355 of file MinioFileStorageServiceIntegrationTest.java.
readFileContent()
String com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.readFileContent (String bucketName, String filePath) throws Exception private
Definition at line 374 of file MinioFileStorageServiceIntegrationTest.java.
setUp()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.setUp () throws Exception package
Definition at line 38 of file MinioFileStorageServiceIntegrationTest.java.
tearDown()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.tearDown () throws Exception package
Definition at line 50 of file MinioFileStorageServiceIntegrationTest.java.
testBatchDeleteFiles_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testBatchDeleteFiles_Success () throws Exception package
Definition at line 133 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.batchDeleteFiles(), and com.gmp.edms.service.FileStorageService.uploadFile().
testCopyFile_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testCopyFile_Success () throws Exception package
Definition at line 204 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.copyFile(), and com.gmp.edms.service.FileStorageService.uploadFile().
testCreateDirectory_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testCreateDirectory_Success () throws Exception package
Definition at line 252 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.createDirectory().
testDeleteFile_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDeleteFile_Success () throws Exception package
Definition at line 112 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.deleteFile(), and com.gmp.edms.service.FileStorageService.uploadFile().
testDownloadFile_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDownloadFile_Success () throws Exception package
Definition at line 92 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.downloadFile(), and com.gmp.edms.service.FileStorageService.uploadFile().
testGeneratePresignedUrl_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGeneratePresignedUrl_Success () throws Exception package
Definition at line 161 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.generatePresignedUrl(), and com.gmp.edms.service.FileStorageService.uploadFile().
testGetBucketStorageInfo_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetBucketStorageInfo_Success () throws Exception package
Definition at line 288 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.getBucketStorageInfo(), and com.gmp.edms.service.FileStorageService.uploadFile().
testGetFileInfo_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetFileInfo_Success () throws Exception package
Definition at line 181 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.getFileInfo(), and com.gmp.edms.service.FileStorageService.uploadFile().
testListFiles_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testListFiles_Success () throws Exception package
Definition at line 263 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.listFiles(), and com.gmp.edms.service.FileStorageService.uploadFile().
testMoveFile_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testMoveFile_Success () throws Exception package
Definition at line 228 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.moveFile(), and com.gmp.edms.service.FileStorageService.uploadFile().
testUploadFile_Success()
void com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testUploadFile_Success () throws Exception package
Definition at line 67 of file MinioFileStorageServiceIntegrationTest.java.
References com.gmp.edms.service.FileStorageService.uploadFile().
Member Data Documentation
fileStorageService
FileStorageService com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.fileStorageService private
Definition at line 29 of file MinioFileStorageServiceIntegrationTest.java.
minioClient
MinioClient com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.minioClient private
Definition at line 32 of file MinioFileStorageServiceIntegrationTest.java.
TEST_BUCKET
final String com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.TEST_BUCKET = "test-bucket" static private
Definition at line 34 of file MinioFileStorageServiceIntegrationTest.java.
TEST_PREFIX
final String com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.TEST_PREFIX = "test/" static private
Definition at line 35 of file MinioFileStorageServiceIntegrationTest.java.
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/MinioFileStorageServiceIntegrationTest.java