GMP系统: com.gmp.auth.util.JwtUtil Class Reference
com.gmp.auth.util.JwtUtil Class Reference
Public Member Functions
String getUsernameFromToken (String token)
Date getExpirationDateFromToken (String token)
String getTokenIdFromToken (String token)
Boolean isTokenExpired (String token)
Boolean isTokenRevoked (String token)
String generateAccessToken (UserDetails userDetails)
String generateToken (String username)
String generateRefreshToken (UserDetails userDetails)
String generateRefreshToken (String username)
Boolean validateToken (String token, UserDetails userDetails)
Boolean validateToken (String token)
void revokeToken (String token)
void cleanupRevokedTokens ()
Claims parseTokenWithoutValidation (String token)
Claims parseToken (String token)
String generateToken (Map< String, Object > extraClaims, String username)
String refreshToken (String refreshToken)
Package Functions
public< T > T getClaimFromToken (String token, Function< Claims, T > claimsResolver)
Private Member Functions
Claims getAllClaimsFromToken (String token)
Key getSigningKey ()
String doGenerateToken (Map< String, Object > claims, String subject, long expiration)
Private Attributes
String jwtSecret
long expiration
long refreshExpiration
Set< String > revokedTokens = Collections.synchronizedSet(new HashSet<>())
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(JwtUtil.class)
Detailed Description
Definition at line 19 of file JwtUtil.java.
Member Function Documentation
cleanupRevokedTokens()
void com.gmp.auth.util.JwtUtil.cleanupRevokedTokens ()
Definition at line 237 of file JwtUtil.java.
doGenerateToken()
String com.gmp.auth.util.JwtUtil.doGenerateToken (Map< String, Object > claims, String subject, long expiration) private
Definition at line 146 of file JwtUtil.java.
generateAccessToken()
String com.gmp.auth.util.JwtUtil.generateAccessToken (UserDetails userDetails)
Definition at line 117 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testGenerateAccessToken_Success(), com.gmp.auth.util.JwtUtilTest.testGetExpirationDateFromToken_Success(), com.gmp.auth.util.JwtUtilTest.testGetTokenIdFromToken_Success(), com.gmp.auth.util.JwtUtilTest.testGetUsernameFromToken_Success(), com.gmp.auth.util.JwtUtilTest.testIsTokenExpired_NotExpired(), com.gmp.auth.util.JwtUtilTest.testIsTokenRevoked_NotRevoked(), com.gmp.auth.util.JwtUtilTest.testParseTokenWithoutValidation_Success(), com.gmp.auth.util.JwtUtilTest.testRevokeToken_Success(), com.gmp.auth.util.JwtUtilTest.testValidateToken_ValidToken(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_NullUserDetails(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_Success(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_ValidToken(), and com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_WrongUsername().
generateRefreshToken() [1/2]
String com.gmp.auth.util.JwtUtil.generateRefreshToken (String username)
Definition at line 140 of file JwtUtil.java.
generateRefreshToken() [2/2]
String com.gmp.auth.util.JwtUtil.generateRefreshToken (UserDetails userDetails)
Definition at line 134 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testGenerateRefreshToken_Success().
generateToken() [1/2]
String com.gmp.auth.util.JwtUtil.generateToken (Map< String, Object > extraClaims, String username)
Definition at line 257 of file JwtUtil.java.
generateToken() [2/2]
String com.gmp.auth.util.JwtUtil.generateToken (String username)
Definition at line 128 of file JwtUtil.java.
getAllClaimsFromToken()
Claims com.gmp.auth.util.JwtUtil.getAllClaimsFromToken (String token) private
Definition at line 58 of file JwtUtil.java.
getClaimFromToken()
public< T > T com.gmp.auth.util.JwtUtil.getClaimFromToken (String token, Function< Claims, T > claimsResolver) package
Definition at line 52 of file JwtUtil.java.
getExpirationDateFromToken()
Date com.gmp.auth.util.JwtUtil.getExpirationDateFromToken (String token)
Definition at line 42 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testGetExpirationDateFromToken_Success().
getSigningKey()
Key com.gmp.auth.util.JwtUtil.getSigningKey () private
Definition at line 85 of file JwtUtil.java.
getTokenIdFromToken()
String com.gmp.auth.util.JwtUtil.getTokenIdFromToken (String token)
Definition at line 47 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testGetTokenIdFromToken_Success().
getUsernameFromToken()
String com.gmp.auth.util.JwtUtil.getUsernameFromToken (String token)
Definition at line 37 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testGenerateAccessToken_Success(), and com.gmp.auth.util.JwtUtilTest.testGetUsernameFromToken_Success().
isTokenExpired()
Boolean com.gmp.auth.util.JwtUtil.isTokenExpired (String token)
Definition at line 95 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testIsTokenExpired_NotExpired().
isTokenRevoked()
Boolean com.gmp.auth.util.JwtUtil.isTokenRevoked (String token)
Definition at line 106 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testIsTokenRevoked_NotRevoked(), and com.gmp.auth.util.JwtUtilTest.testRevokeToken_Success().
parseToken()
Claims com.gmp.auth.util.JwtUtil.parseToken (String token)
Definition at line 252 of file JwtUtil.java.
parseTokenWithoutValidation()
Claims com.gmp.auth.util.JwtUtil.parseTokenWithoutValidation (String token)
Definition at line 242 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testParseTokenWithoutValidation_Success().
refreshToken()
String com.gmp.auth.util.JwtUtil.refreshToken (String refreshToken)
Definition at line 262 of file JwtUtil.java.
revokeToken()
void com.gmp.auth.util.JwtUtil.revokeToken (String token)
Definition at line 226 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testRevokeToken_Success().
validateToken() [1/2]
Boolean com.gmp.auth.util.JwtUtil.validateToken (String token)
Definition at line 182 of file JwtUtil.java.
validateToken() [2/2]
Boolean com.gmp.auth.util.JwtUtil.validateToken (String token, UserDetails userDetails)
Definition at line 162 of file JwtUtil.java.
Referenced by com.gmp.auth.util.JwtUtilTest.testValidateToken_InvalidToken(), com.gmp.auth.util.JwtUtilTest.testValidateToken_NullToken(), com.gmp.auth.util.JwtUtilTest.testValidateToken_ValidToken(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_NullToken(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_NullUserDetails(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_Success(), com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_ValidToken(), and com.gmp.auth.util.JwtUtilTest.testValidateTokenForUserDetails_WrongUsername().
Member Data Documentation
expiration
long com.gmp.auth.util.JwtUtil.expiration private
Definition at line 28 of file JwtUtil.java.
jwtSecret
String com.gmp.auth.util.JwtUtil.jwtSecret private
Definition at line 25 of file JwtUtil.java.
logger
final Logger com.gmp.auth.util.JwtUtil.logger = LoggerFactory.getLogger(JwtUtil.class) static private
Definition at line 21 of file JwtUtil.java.
refreshExpiration
long com.gmp.auth.util.JwtUtil.refreshExpiration private
Definition at line 31 of file JwtUtil.java.
revokedTokens
Set<String> com.gmp.auth.util.JwtUtil.revokedTokens = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 34 of file JwtUtil.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/util/JwtUtil.java