GMP系统: com.gmp.qms.service.monitoring.McpPerformanceReportService Class Reference
com.gmp.qms.service.monitoring.McpPerformanceReportService Class Reference
MCP性能报告服务，负责生成和管理MCP通信的性能报告
Classes
class PerformanceReport
class PerformanceTrendPoint
Public Member Functions
PerformanceReport getLatestPerformanceReport ()
获取最新的性能报告
List< PerformanceTrendPoint > getPerformanceTrendsByMinute (int minutes)
按分钟获取性能趋势
List< PerformanceTrendPoint > getPerformanceTrendsByHour (int hours)
按小时获取性能趋势
List< PerformanceTrendPoint > getPerformanceTrendsByDay (int days)
按天获取性能趋势
List< PerformanceTrendPoint > getPerformanceTrendsByWeek (int weeks)
按周获取性能趋势
Private Member Functions
String getTimeAgo (int value, String unit)
Map< String, Long > getSystemDistribution ()
Detailed Description
MCP性能报告服务，负责生成和管理MCP通信的性能报告
Definition at line 14 of file McpPerformanceReportService.java.
Member Function Documentation
getLatestPerformanceReport()
PerformanceReport com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport ()
获取最新的性能报告
Returns
性能报告
Definition at line 20 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.getSystemDistribution(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setAverageResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setErrorRate(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP95ResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setP99ResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setPeriod(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSuccessRate(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setSystemDistribution(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTimestamp(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceReport.setTotalCalls().
getPerformanceTrendsByDay()
List< PerformanceTrendPoint > com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay (int days)
按天获取性能趋势
Parameters
days 天数
Returns
性能趋势数据
Definition at line 77 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.getTimeAgo(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp().
getPerformanceTrendsByHour()
List< PerformanceTrendPoint > com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour (int hours)
按小时获取性能趋势
Parameters
hours 小时数
Returns
性能趋势数据
Definition at line 58 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.getTimeAgo(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp().
getPerformanceTrendsByMinute()
List< PerformanceTrendPoint > com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute (int minutes)
按分钟获取性能趋势
Parameters
minutes 分钟数
Returns
性能趋势数据
Definition at line 39 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.getTimeAgo(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp().
getPerformanceTrendsByWeek()
List< PerformanceTrendPoint > com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek (int weeks)
按周获取性能趋势
Parameters
weeks 周数
Returns
性能趋势数据
Definition at line 96 of file McpPerformanceReportService.java.
References com.gmp.qms.service.monitoring.McpPerformanceReportService.getTimeAgo(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setAverageResponseTime(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setCalls(), com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setSuccessRate(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.PerformanceTrendPoint.setTimestamp().
getSystemDistribution()
Map< String, Long > com.gmp.qms.service.monitoring.McpPerformanceReportService.getSystemDistribution () private
Definition at line 130 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getLatestPerformanceReport().
getTimeAgo()
String com.gmp.qms.service.monitoring.McpPerformanceReportService.getTimeAgo (int value, String unit) private
Definition at line 111 of file McpPerformanceReportService.java.
Referenced by com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByDay(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByHour(), com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByMinute(), and com.gmp.qms.service.monitoring.McpPerformanceReportService.getPerformanceTrendsByWeek().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpPerformanceReportService.java