GMP系统: com.gmp.edms.service.impl.DocumentPermissionServiceImpl Class Reference
com.gmp.edms.service.impl.DocumentPermissionServiceImpl Class Reference
文档权限服务实现类 实现设计文档中的复杂权限控制架构
Classes
class ConfidentialityPolicy
class DepartmentPolicy
class DocumentOwnerPolicy
class PermissionContext
interface PermissionPolicy
class StatusPolicy
Public Member Functions
boolean hasPermission (String userId, Long documentId, PermissionType permission)
检查用户对文档的访问权限
boolean hasCreatePermission (String userId, Long categoryId)
检查用户对文档的创建权限
Set< PermissionType > getUserPermissions (String userId, Long documentId)
获取用户对文档的所有权限
boolean canApprove (String userId, Long documentId)
检查用户是否可以审批指定文档
boolean canView (String userId, Long documentId)
检查用户是否可以查看文档内容
boolean canEdit (String userId, Long documentId)
检查用户是否可以编辑文档
boolean canDelete (String userId, Long documentId)
检查用户是否可以删除文档
boolean canDownload (String userId, Long documentId)
检查用户是否可以下载文档
Set< Long > getAccessibleDocumentIds (String userId, PermissionType permission)
获取用户可访问的文档ID列表
boolean hasPermissionWithTimeWindow (String userId, Long documentId, PermissionType permission, LocalDateTime currentTime)
boolean hasPermissionWithLocation (String userId, Long documentId, PermissionType permission, String location)
基于地理位置检查权限
boolean hasPermissionWithTimeWindow (String userId, Long documentId, PermissionType permission, java.time.LocalDateTime currentTime)
基于时间窗口检查权限
Private Member Functions
Set< String > getUserRoles (String userId)
List< PermissionPolicy > getDocumentPolicies (Document document)
Object getFieldValue (Object obj, String fieldName)
使用反射获取对象字段值
Field findField (Class<?> clazz, String fieldName)
查找字段，包括父类中的字段
PermissionContext getContext (String userId, Document document)
boolean evaluatePermissions (Set< String > roles, List< PermissionPolicy > policies, PermissionType required, PermissionContext context)
String getDocumentAuthor (Long documentId)
boolean hasCategoryPermission (String userId, Long categoryId, PermissionType permission)
Static Private Member Functions
static boolean isAdmin (Set< String > roles)
Private Attributes
DocumentRepository documentRepository
final Set< String > adminUsers = Set.of("admin", "system", "gmp_admin")
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(DocumentPermissionServiceImpl.class)
Detailed Description
文档权限服务实现类 实现设计文档中的复杂权限控制架构
Definition at line 26 of file DocumentPermissionServiceImpl.java.
Member Function Documentation
canApprove()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canApprove (String userId, Long documentId)
检查用户是否可以审批指定文档
Parameters
userId 用户ID
documentId 文档ID
Returns
是否可以审批
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 95 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.DocumentPermissionService.PermissionType.APPROVE, and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
canDelete()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDelete (String userId, Long documentId)
检查用户是否可以删除文档
Parameters
userId 用户ID
documentId 文档ID
Returns
是否可以删除
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 110 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.DocumentPermissionService.PermissionType.DELETE, and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
canDownload()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDownload (String userId, Long documentId)
检查用户是否可以下载文档
Parameters
userId 用户ID
documentId 文档ID
Returns
是否可以下载
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 115 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.DocumentPermissionService.PermissionType.DOWNLOAD, and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
canEdit()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canEdit (String userId, Long documentId)
检查用户是否可以编辑文档
Parameters
userId 用户ID
documentId 文档ID
Returns
是否可以编辑
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 105 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.DocumentPermissionService.PermissionType.EDIT, and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
canView()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canView (String userId, Long documentId)
检查用户是否可以查看文档内容
Parameters
userId 用户ID
documentId 文档ID
Returns
是否可以查看
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 100 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission(), and com.gmp.edms.service.DocumentPermissionService.PermissionType.VIEW.
evaluatePermissions()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions (Set< String > roles, List< PermissionPolicy > policies, PermissionType required, PermissionContext context) private
Definition at line 267 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentAuthor(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getDocumentId(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.getUserId(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.isAdmin().
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
findField()
Field com.gmp.edms.service.impl.DocumentPermissionServiceImpl.findField (Class<?> clazz, String fieldName) private
查找字段，包括父类中的字段
Definition at line 227 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getFieldValue().
getAccessibleDocumentIds()
Set< Long > com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getAccessibleDocumentIds (String userId, PermissionType permission)
获取用户可访问的文档ID列表
Parameters
userId 用户ID
permission 权限类型
Returns
文档ID列表
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 120 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
getContext()
PermissionContext com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext (String userId, Document document) private
Definition at line 239 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setConfidentialityLevel(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setCurrentTime(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentId(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setDocumentType(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.PermissionContext.setUserId().
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
getDocumentAuthor()
String com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentAuthor (Long documentId) private
Definition at line 295 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions().
getDocumentPolicies()
List< PermissionPolicy > com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentPolicies (Document document) private
Definition at line 185 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
getFieldValue()
Object com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getFieldValue (Object obj, String fieldName) private
使用反射获取对象字段值
Definition at line 197 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.findField(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.log.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentPolicies(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithTimeWindow().
getUserPermissions()
Set< PermissionType > com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions (String userId, Long documentId)
获取用户对文档的所有权限
Parameters
userId 用户ID
documentId 文档ID
Returns
权限集合
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 73 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentPolicies(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserRoles().
getUserRoles()
Set< String > com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserRoles (String userId) private
Definition at line 173 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.adminUsers.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCreatePermission(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
hasCategoryPermission()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCategoryPermission (String userId, Long categoryId, PermissionType permission) private
Definition at line 309 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCreatePermission().
hasCreatePermission()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCreatePermission (String userId, Long categoryId)
检查用户对文档的创建权限
Parameters
userId 用户ID
categoryId 分类ID
Returns
是否有权限
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 59 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.DocumentPermissionService.PermissionType.EDIT, com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserRoles(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCategoryPermission(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.isAdmin().
hasPermission()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission (String userId, Long documentId, PermissionType permission)
检查用户对文档的访问权限
Parameters
userId 用户ID
documentId 文档ID
permission 权限类型
Returns
是否有权限
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 37 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getContext(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentPolicies(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserRoles().
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canApprove(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDelete(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDownload(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canEdit(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canView(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getAccessibleDocumentIds(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithLocation(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithTimeWindow().
hasPermissionWithLocation()
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithLocation (String userId, Long documentId, PermissionType permission, String location)
基于地理位置检查权限
Parameters
userId 用户ID
documentId 文档ID
permission 权限类型
location 地理位置
Returns
是否有权限
Implements com.gmp.edms.service.DocumentPermissionService.
Definition at line 164 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
hasPermissionWithTimeWindow() [1/2]
boolean com.gmp.edms.service.DocumentPermissionService.hasPermissionWithTimeWindow (String userId, Long documentId, PermissionType permission, java.time.LocalDateTime currentTime) inherited
基于时间窗口检查权限
Parameters
userId 用户ID
documentId 文档ID
permission 权限类型
currentTime 当前时间
Returns
是否有权限
hasPermissionWithTimeWindow() [2/2]
boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithTimeWindow (String userId, Long documentId, PermissionType permission, LocalDateTime currentTime)
Definition at line 141 of file DocumentPermissionServiceImpl.java.
References com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission().
isAdmin()
static boolean com.gmp.edms.service.impl.DocumentPermissionServiceImpl.isAdmin (Set< String > roles) static private
Definition at line 290 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.ConfidentialityPolicy.evaluate(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.evaluatePermissions(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCreatePermission().
Member Data Documentation
adminUsers
final Set<String> com.gmp.edms.service.impl.DocumentPermissionServiceImpl.adminUsers = Set.of("admin", "system", "gmp_admin") private
Definition at line 34 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserRoles().
documentRepository
DocumentRepository com.gmp.edms.service.impl.DocumentPermissionServiceImpl.documentRepository private
Definition at line 31 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getAccessibleDocumentIds(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getDocumentAuthor(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getUserPermissions(), com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermission(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasPermissionWithTimeWindow().
log
final Logger com.gmp.edms.service.impl.DocumentPermissionServiceImpl.log = LoggerFactory.getLogger(DocumentPermissionServiceImpl.class) static private
Definition at line 28 of file DocumentPermissionServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.getFieldValue().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/DocumentPermissionServiceImpl.java