GMP系统: com.gmp.auth.service.AuthServiceTest Class Reference
com.gmp.auth.service.AuthServiceTest Class Reference
AuthService集成测试 主要测试服务接口方法的基本调用，确保服务层接口完整性
Package Functions
void testAuthServiceBeanCreation ()
void testLoginMethodSignature ()
void testRefreshTokenMethodSignature ()
void testValidateTokenMethodSignature ()
void testLogoutMethodSignature ()
void testHasPermissionMethodSignature ()
void testHasRoleMethodSignature ()
void testGetUserPermissionsMethodSignature ()
void testGetUserRolesMethodSignature ()
void testMultiplePermissionCheck ()
void testMultipleRoleCheck ()
Private Attributes
AuthService authService
Detailed Description
AuthService集成测试 主要测试服务接口方法的基本调用，确保服务层接口完整性
Author
GMP系统开发团队
Definition at line 24 of file AuthServiceTest.java.
Member Function Documentation
testAuthServiceBeanCreation()
void com.gmp.auth.service.AuthServiceTest.testAuthServiceBeanCreation () package
Definition at line 30 of file AuthServiceTest.java.
testGetUserPermissionsMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testGetUserPermissionsMethodSignature () package
Definition at line 144 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.getUserPermissions().
testGetUserRolesMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testGetUserRolesMethodSignature () package
Definition at line 161 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.getUserRoles().
testHasPermissionMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testHasPermissionMethodSignature () package
Definition at line 110 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.hasPermission().
testHasRoleMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testHasRoleMethodSignature () package
Definition at line 127 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.hasRole().
testLoginMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testLoginMethodSignature () package
Definition at line 36 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.login().
testLogoutMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testLogoutMethodSignature () package
Definition at line 91 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.logout().
testMultiplePermissionCheck()
void com.gmp.auth.service.AuthServiceTest.testMultiplePermissionCheck () package
Definition at line 178 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.hasPermission().
testMultipleRoleCheck()
void com.gmp.auth.service.AuthServiceTest.testMultipleRoleCheck () package
Definition at line 195 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.hasRole().
testRefreshTokenMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testRefreshTokenMethodSignature () package
Definition at line 57 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.refreshToken().
testValidateTokenMethodSignature()
void com.gmp.auth.service.AuthServiceTest.testValidateTokenMethodSignature () package
Definition at line 74 of file AuthServiceTest.java.
References com.gmp.auth.service.AuthService.validateToken().
Member Data Documentation
authService
AuthService com.gmp.auth.service.AuthServiceTest.authService private
Definition at line 27 of file AuthServiceTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/AuthServiceTest.java