GMP系统: com.gmp.mes.entity.ProductionOrder Class Reference
com.gmp.mes.entity.ProductionOrder Class Reference
生产订单实体
Classes
enum OrderPriority
订单优先级枚举
enum OrderStatus
订单状态枚举
Public Member Functions
LocalDateTime getPlanStartTime ()
void setPlanStartTime (LocalDateTime planStartTime)
LocalDateTime getPlanEndTime ()
void setPlanEndTime (LocalDateTime planEndTime)
LocalDateTime getActualStartTime ()
void setActualStartTime (LocalDateTime actualStartTime)
LocalDateTime getActualEndTime ()
void setActualEndTime (LocalDateTime actualEndTime)
Long getId ()
void setId (Long id)
String getOrderNumber ()
void setOrderNumber (String orderNumber)
OrderStatus getStatus ()
void setStatus (OrderStatus status)
String getUnit ()
void setUnit (String unit)
String getPriority ()
void setPriority (String priority)
String getApplicant ()
void setApplicant (String applicant)
String getDepartment ()
void setDepartment (String department)
String getRemark ()
void setRemark (String remark)
Set< ProductionBatch > getProductionBatches ()
void setProductionBatches (Set< ProductionBatch > productionBatches)
void addProductionBatch (ProductionBatch batch)
void removeProductionBatch (ProductionBatch batch)
Private Attributes
Long id
String orderNumber
String productId
String productName
BigDecimal batchSize
String unit
String department
String remark
LocalDateTime plannedStartDate
LocalDateTime plannedEndDate
OrderStatus status = OrderStatus.DRAFT
OrderPriority priority = OrderPriority.NORMAL
String requester
String approver
LocalDateTime approvedAt
List< ProductionBatch > batches = new ArrayList<>()
LocalDateTime createdAt
LocalDateTime updatedAt
Detailed Description
生产订单实体
Author
gmp-system
Definition at line 25 of file ProductionOrder.java.
Member Function Documentation
addProductionBatch()
void com.gmp.mes.entity.ProductionOrder.addProductionBatch (ProductionBatch batch)
Definition at line 217 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testAddProductionBatch(), and com.gmp.mes.entity.ProductionOrderTest.testRemoveProductionBatch().
getActualEndTime()
LocalDateTime com.gmp.mes.entity.ProductionOrder.getActualEndTime ()
Definition at line 78 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testActualEndTimeGetterAndSetter().
getActualStartTime()
LocalDateTime com.gmp.mes.entity.ProductionOrder.getActualStartTime ()
Definition at line 68 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testActualStartTimeGetterAndSetter().
getApplicant()
String com.gmp.mes.entity.ProductionOrder.getApplicant ()
Definition at line 179 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testApplicantGetterAndSetter().
getDepartment()
String com.gmp.mes.entity.ProductionOrder.getDepartment ()
Definition at line 188 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testDepartmentGetterAndSetter().
getId()
Long com.gmp.mes.entity.ProductionOrder.getId ()
Definition at line 103 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testIdGetterAndSetter().
getOrderNumber()
String com.gmp.mes.entity.ProductionOrder.getOrderNumber ()
Definition at line 111 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testOrderNumberGetterAndSetter().
getPlanEndTime()
LocalDateTime com.gmp.mes.entity.ProductionOrder.getPlanEndTime ()
Definition at line 59 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPlanEndTimeGetterAndSetter().
getPlanStartTime()
LocalDateTime com.gmp.mes.entity.ProductionOrder.getPlanStartTime ()
Definition at line 50 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPlanStartTimeGetterAndSetter().
getPriority()
String com.gmp.mes.entity.ProductionOrder.getPriority ()
Definition at line 166 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPriorityGetterAndSetter().
getProductionBatches()
Set< ProductionBatch > com.gmp.mes.entity.ProductionOrder.getProductionBatches ()
Definition at line 206 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testAddProductionBatch(), com.gmp.mes.entity.ProductionOrderTest.testProductionBatchesGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductionOrderGetterAndSetter(), and com.gmp.mes.entity.ProductionOrderTest.testRemoveProductionBatch().
getRemark()
String com.gmp.mes.entity.ProductionOrder.getRemark ()
Definition at line 197 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testRemarkGetterAndSetter().
getStatus()
OrderStatus com.gmp.mes.entity.ProductionOrder.getStatus ()
Definition at line 119 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testStatusGetterAndSetter().
getUnit()
String com.gmp.mes.entity.ProductionOrder.getUnit ()
Definition at line 157 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testUnitGetterAndSetter().
removeProductionBatch()
void com.gmp.mes.entity.ProductionOrder.removeProductionBatch (ProductionBatch batch)
Definition at line 228 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testRemoveProductionBatch().
setActualEndTime()
void com.gmp.mes.entity.ProductionOrder.setActualEndTime (LocalDateTime actualEndTime)
Definition at line 83 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testActualEndTimeGetterAndSetter().
setActualStartTime()
void com.gmp.mes.entity.ProductionOrder.setActualStartTime (LocalDateTime actualStartTime)
Definition at line 73 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testActualStartTimeGetterAndSetter().
setApplicant()
void com.gmp.mes.entity.ProductionOrder.setApplicant (String applicant)
Definition at line 183 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testApplicantGetterAndSetter().
setDepartment()
void com.gmp.mes.entity.ProductionOrder.setDepartment (String department)
Definition at line 192 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testDepartmentGetterAndSetter().
setId()
void com.gmp.mes.entity.ProductionOrder.setId (Long id)
Definition at line 107 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testEqualsAndHashCode(), com.gmp.mes.entity.ProductionOrderTest.testIdGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductionOrderGetterAndSetter(), and com.gmp.mes.entity.ProductionOrderTest.testToString().
setOrderNumber()
void com.gmp.mes.entity.ProductionOrder.setOrderNumber (String orderNumber)
Definition at line 115 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testEqualsAndHashCode(), com.gmp.mes.entity.ProductionOrderTest.testOrderNumberGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductionOrderGetterAndSetter(), and com.gmp.mes.entity.ProductionOrderTest.testToString().
setPlanEndTime()
void com.gmp.mes.entity.ProductionOrder.setPlanEndTime (LocalDateTime planEndTime)
Definition at line 63 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPlanEndTimeGetterAndSetter().
setPlanStartTime()
void com.gmp.mes.entity.ProductionOrder.setPlanStartTime (LocalDateTime planStartTime)
Definition at line 54 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPlanStartTimeGetterAndSetter().
setPriority()
void com.gmp.mes.entity.ProductionOrder.setPriority (String priority)
Definition at line 170 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testPriorityGetterAndSetter().
setProductionBatches()
void com.gmp.mes.entity.ProductionOrder.setProductionBatches (Set< ProductionBatch > productionBatches)
Definition at line 210 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testProductionBatchesGetterAndSetter().
setRemark()
void com.gmp.mes.entity.ProductionOrder.setRemark (String remark)
Definition at line 201 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testRemarkGetterAndSetter().
setStatus()
void com.gmp.mes.entity.ProductionOrder.setStatus (OrderStatus status)
Definition at line 123 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testStatusGetterAndSetter().
setUnit()
void com.gmp.mes.entity.ProductionOrder.setUnit (String unit)
Definition at line 161 of file ProductionOrder.java.
Referenced by com.gmp.mes.entity.ProductionOrderTest.testUnitGetterAndSetter().
Member Data Documentation
approvedAt
LocalDateTime com.gmp.mes.entity.ProductionOrder.approvedAt private
Definition at line 97 of file ProductionOrder.java.
approver
String com.gmp.mes.entity.ProductionOrder.approver private
Definition at line 96 of file ProductionOrder.java.
batches
List<ProductionBatch> com.gmp.mes.entity.ProductionOrder.batches = new ArrayList<>() private
Definition at line 100 of file ProductionOrder.java.
batchSize
BigDecimal com.gmp.mes.entity.ProductionOrder.batchSize private
Definition at line 38 of file ProductionOrder.java.
createdAt
LocalDateTime com.gmp.mes.entity.ProductionOrder.createdAt private
Definition at line 129 of file ProductionOrder.java.
department
String com.gmp.mes.entity.ProductionOrder.department private
Definition at line 40 of file ProductionOrder.java.
id
Long com.gmp.mes.entity.ProductionOrder.id private
Definition at line 29 of file ProductionOrder.java.
orderNumber
String com.gmp.mes.entity.ProductionOrder.orderNumber private
Definition at line 32 of file ProductionOrder.java.
plannedEndDate
LocalDateTime com.gmp.mes.entity.ProductionOrder.plannedEndDate private
Definition at line 47 of file ProductionOrder.java.
plannedStartDate
LocalDateTime com.gmp.mes.entity.ProductionOrder.plannedStartDate private
Definition at line 44 of file ProductionOrder.java.
priority
OrderPriority com.gmp.mes.entity.ProductionOrder.priority = OrderPriority.NORMAL private
Definition at line 91 of file ProductionOrder.java.
productId
String com.gmp.mes.entity.ProductionOrder.productId private
Definition at line 35 of file ProductionOrder.java.
productName
String com.gmp.mes.entity.ProductionOrder.productName private
Definition at line 37 of file ProductionOrder.java.
remark
String com.gmp.mes.entity.ProductionOrder.remark private
Definition at line 41 of file ProductionOrder.java.
requester
String com.gmp.mes.entity.ProductionOrder.requester private
Definition at line 94 of file ProductionOrder.java.
status
OrderStatus com.gmp.mes.entity.ProductionOrder.status = OrderStatus.DRAFT private
Definition at line 88 of file ProductionOrder.java.
unit
String com.gmp.mes.entity.ProductionOrder.unit private
Definition at line 39 of file ProductionOrder.java.
updatedAt
LocalDateTime com.gmp.mes.entity.ProductionOrder.updatedAt private
Definition at line 132 of file ProductionOrder.java.
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/entity/ProductionOrder.java