GMP系统: com.gmp.training.service.impl.TrainingAssessmentServiceImpl Class Reference
com.gmp.training.service.impl.TrainingAssessmentServiceImpl Class Reference
培训考核服务实现类
Public Member Functions
TrainingAssessmentServiceImpl (TrainingAssessmentRepository repository)
List< TrainingAssessment > findByTrainingCourse (TrainingCourse trainingCourse)
根据培训课程查找考核
List< TrainingAssessment > findByUser (User user)
根据用户查找考核记录
List< TrainingAssessment > findByStatus (TrainingAssessment.Status status)
根据考核状态查找
List< TrainingAssessment > findByUserAndTrainingCourse (User user, TrainingCourse trainingCourse)
根据用户和培训课程查找考核记录
List< TrainingAssessment > findByAssessmentDateBetween (LocalDate startDate, LocalDate endDate)
查找特定时间范围内的考核记录
List< TrainingAssessment > findNotStartedAssessments ()
查找未开始的考核
List< TrainingAssessment > findInProgressAssessments ()
查找进行中的考核
List< TrainingAssessment > findCompletedAssessments ()
查找已完成的考核
TrainingAssessment updateStatus (Long id, TrainingAssessment.Status status)
更新考核状态
int batchUpdateStatus (List< Long > ids, TrainingAssessment.Status status)
批量更新考核状态
List< TrainingAssessment > search (String keyword)
搜索考核记录
List< TrainingAssessment > findByType (TrainingAssessment.Type type)
根据考核类型查找
Double getAverageScoreByCourseId (Long courseId)
获取培训课程的平均考核分数
Double getAverageScoreByUserId (Long userId)
获取用户的平均考核分数
List< TrainingAssessment > findPassedAssessments (Double passScore)
查找考核通过的记录
TrainingAssessment save (TrainingAssessment assessment)
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Protected Member Functions
String getEntityName ()
Detailed Description
培训考核服务实现类
Author
GMP系统开发团队
Definition at line 24 of file TrainingAssessmentServiceImpl.java.
Constructor & Destructor Documentation
TrainingAssessmentServiceImpl()
com.gmp.training.service.impl.TrainingAssessmentServiceImpl.TrainingAssessmentServiceImpl (TrainingAssessmentRepository repository)
Definition at line 27 of file TrainingAssessmentServiceImpl.java.
References repository.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingAssessmentServiceImpl.batchUpdateStatus (List< Long > ids, TrainingAssessment.Status status)
批量更新考核状态
Parameters
ids 考核ID列表
status 状态
Returns
影响的行数
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 85 of file TrainingAssessmentServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testBatchUpdateStatus().
count()
long com.gmp.training.service.BaseService< T, ID >.count () inherited
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity) inherited
删除实体
Parameters
entity 实体对象
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll () inherited
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities) inherited
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id) inherited
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id) inherited
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll () inherited
查询所有实体
Returns
实体列表
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable) inherited
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort) inherited
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids) inherited
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findByAssessmentDateBetween()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByAssessmentDateBetween (LocalDate startDate, LocalDate endDate)
查找特定时间范围内的考核记录
Parameters
startDate 开始日期
endDate 结束日期
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 52 of file TrainingAssessmentServiceImpl.java.
References repository.
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id) inherited
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
findByStatus()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByStatus (TrainingAssessment.Status status)
根据考核状态查找
Parameters
status 状态
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 42 of file TrainingAssessmentServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindByStatus().
findByTrainingCourse()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByTrainingCourse (TrainingCourse trainingCourse)
根据培训课程查找考核
Parameters
trainingCourse 培训课程
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 32 of file TrainingAssessmentServiceImpl.java.
References repository.
findByType()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByType (TrainingAssessment.Type type)
根据考核类型查找
Parameters
type 考核类型
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 105 of file TrainingAssessmentServiceImpl.java.
References repository.
findByUser()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByUser (User user)
根据用户查找考核记录
Parameters
user 用户
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 37 of file TrainingAssessmentServiceImpl.java.
References repository.
findByUserAndTrainingCourse()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findByUserAndTrainingCourse (User user, TrainingCourse trainingCourse)
根据用户和培训课程查找考核记录
Parameters
user 用户
trainingCourse 培训课程
Returns
培训考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 47 of file TrainingAssessmentServiceImpl.java.
References repository.
findCompletedAssessments()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findCompletedAssessments ()
查找已完成的考核
Returns
已完成的考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 67 of file TrainingAssessmentServiceImpl.java.
References repository.
findInProgressAssessments()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findInProgressAssessments ()
查找进行中的考核
Returns
进行中的考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 62 of file TrainingAssessmentServiceImpl.java.
References repository.
findNotStartedAssessments()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findNotStartedAssessments ()
查找未开始的考核
Returns
未开始的考核列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 57 of file TrainingAssessmentServiceImpl.java.
References repository.
findPassedAssessments()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.findPassedAssessments (Double passScore)
查找考核通过的记录
Parameters
passScore 及格分数
Returns
通过考核的记录列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 130 of file TrainingAssessmentServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindPassedAssessments().
getAverageScoreByCourseId()
Double com.gmp.training.service.impl.TrainingAssessmentServiceImpl.getAverageScoreByCourseId (Long courseId)
获取培训课程的平均考核分数
Parameters
courseId 课程ID
Returns
平均考核分数
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 110 of file TrainingAssessmentServiceImpl.java.
References repository.
getAverageScoreByUserId()
Double com.gmp.training.service.impl.TrainingAssessmentServiceImpl.getAverageScoreByUserId (Long userId)
获取用户的平均考核分数
Parameters
userId 用户ID
Returns
平均考核分数
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 120 of file TrainingAssessmentServiceImpl.java.
References repository.
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id) inherited
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
getEntityName()
String com.gmp.training.service.impl.TrainingAssessmentServiceImpl.getEntityName () protected
Definition at line 145 of file TrainingAssessmentServiceImpl.java.
save() [1/2]
T com.gmp.training.service.BaseService< T, ID >.save (T entity) inherited
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
save() [2/2]
TrainingAssessment com.gmp.training.service.impl.TrainingAssessmentServiceImpl.save (TrainingAssessment assessment)
Definition at line 136 of file TrainingAssessmentServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testSave().
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities) inherited
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
search()
List< TrainingAssessment > com.gmp.training.service.impl.TrainingAssessmentServiceImpl.search (String keyword)
搜索考核记录
Parameters
keyword 关键词
Returns
考核记录列表
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 99 of file TrainingAssessmentServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testSearch().
updateStatus()
TrainingAssessment com.gmp.training.service.impl.TrainingAssessmentServiceImpl.updateStatus (Long id, TrainingAssessment.Status status)
更新考核状态
Parameters
id 考核ID
status 状态
Returns
更新后的考核
Implements com.gmp.training.service.TrainingAssessmentService.
Definition at line 73 of file TrainingAssessmentServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testUpdateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingAssessmentServiceImpl.java