GMP系统: com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl Class Reference
com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl Class Reference
设备维护记录服务实现类 实现维护记录相关的业务逻辑
Public Member Functions
MaintenanceRecordDTO getById (Long id)
根据ID查询维护记录
MaintenanceRecordDTO getByMaintenanceNumber (String maintenanceNumber)
根据维护编号查询维护记录
PageResultDTO< MaintenanceRecordDTO > listPage (Long equipmentId, Integer pageNum, Integer pageSize)
分页查询维护记录
List< MaintenanceRecordDTO > listByEquipmentId (Long equipmentId)
根据设备ID查询维护记录列表
List< MaintenanceRecordDTO > listByMaintenancePlanId (Long maintenancePlanId)
根据维护计划ID查询维护记录
List< MaintenanceRecordDTO > listByDateRange (Date startDate, Date endDate)
根据维护日期范围查询维护记录
MaintenanceRecordDTO getLatestByEquipmentId (Long equipmentId)
查询设备的最新维护记录
MaintenanceRecordDTO create (MaintenanceRecordDTO maintenanceRecordDTO)
新增维护记录
MaintenanceRecordDTO update (Long id, MaintenanceRecordDTO maintenanceRecordDTO)
更新维护记录
void delete (Long id)
删除维护记录
void deleteBatch (List< Long > ids)
批量删除维护记录
boolean existsByMaintenanceNumber (String maintenanceNumber, Long id)
检查维护编号是否存在
Private Member Functions
MaintenanceRecordDTO convertToDTO (MaintenanceRecord maintenanceRecord)
将实体类转换为DTO
PageResultDTO< MaintenanceRecordDTO > convertToPageResultDTO (Page< MaintenanceRecord > page)
将分页实体转换为分页DTO
Private Attributes
MaintenanceRecordRepository maintenanceRecordRepository
Detailed Description
设备维护记录服务实现类 实现维护记录相关的业务逻辑
Definition at line 25 of file MaintenanceRecordServiceImpl.java.
Member Function Documentation
convertToDTO()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO (MaintenanceRecord maintenanceRecord) private
将实体类转换为DTO
Parameters
maintenanceRecord 维护记录实体
Returns
维护记录DTO
Definition at line 155 of file MaintenanceRecordServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.create(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getById(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getByMaintenanceNumber(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getLatestByEquipmentId(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.update().
convertToPageResultDTO()
PageResultDTO< MaintenanceRecordDTO > com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToPageResultDTO (Page< MaintenanceRecord > page) private
将分页实体转换为分页DTO
Parameters
page 分页实体
Returns
分页DTO
Definition at line 166 of file MaintenanceRecordServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listPage().
create()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.create (MaintenanceRecordDTO maintenanceRecordDTO)
新增维护记录
Parameters
maintenanceRecordDTO 维护记录DTO
Returns
新增后的维护记录DTO
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 89 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.existsByMaintenanceNumber(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
delete()
void com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.delete (Long id)
删除维护记录
Parameters
id 维护记录ID
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 125 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
deleteBatch()
void com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.deleteBatch (List< Long > ids)
批量删除维护记录
Parameters
ids 维护记录ID列表
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 133 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
existsByMaintenanceNumber()
boolean com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.existsByMaintenanceNumber (String maintenanceNumber, Long id)
检查维护编号是否存在
Parameters
maintenanceNumber 维护编号
id 排除的ID，用于更新时检查
Returns
是否存在
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 142 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
Referenced by com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.create(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.update().
getById()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getById (Long id)
根据ID查询维护记录
Parameters
id 维护记录ID
Returns
维护记录DTO
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 31 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
getByMaintenanceNumber()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getByMaintenanceNumber (String maintenanceNumber)
根据维护编号查询维护记录
Parameters
maintenanceNumber 维护编号
Returns
维护记录DTO
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 38 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
getLatestByEquipmentId()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getLatestByEquipmentId (Long equipmentId)
查询设备的最新维护记录
Parameters
equipmentId 设备ID
Returns
维护记录DTO
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 81 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
listByDateRange()
List< MaintenanceRecordDTO > com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByDateRange (Date startDate, Date endDate)
根据维护日期范围查询维护记录
Parameters
startDate 开始日期
endDate 结束日期
Returns
维护记录DTO列表
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 75 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
listByEquipmentId()
List< MaintenanceRecordDTO > com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByEquipmentId (Long equipmentId)
根据设备ID查询维护记录列表
Parameters
equipmentId 设备ID
Returns
维护记录DTO列表
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 63 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
listByMaintenancePlanId()
List< MaintenanceRecordDTO > com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByMaintenancePlanId (Long maintenancePlanId)
根据维护计划ID查询维护记录
Parameters
maintenancePlanId 维护计划ID
Returns
维护记录DTO列表
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 69 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
listPage()
PageResultDTO< MaintenanceRecordDTO > com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listPage (Long equipmentId, Integer pageNum, Integer pageSize)
分页查询维护记录
Parameters
equipmentId 设备ID
pageNum 页码
pageSize 每页大小
Returns
维护记录分页结果
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 45 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToPageResultDTO(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
update()
MaintenanceRecordDTO com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.update (Long id, MaintenanceRecordDTO maintenanceRecordDTO)
更新维护记录
Parameters
id 维护记录ID
maintenanceRecordDTO 维护记录DTO
Returns
更新后的维护记录DTO
Implements com.gmp.equipment.service.MaintenanceRecordService.
Definition at line 106 of file MaintenanceRecordServiceImpl.java.
References com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.convertToDTO(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.existsByMaintenanceNumber(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository.
Member Data Documentation
maintenanceRecordRepository
MaintenanceRecordRepository com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.maintenanceRecordRepository private
Definition at line 28 of file MaintenanceRecordServiceImpl.java.
Referenced by com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.create(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.delete(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.deleteBatch(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.existsByMaintenanceNumber(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getById(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getByMaintenanceNumber(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.getLatestByEquipmentId(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByDateRange(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByEquipmentId(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listByMaintenancePlanId(), com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.listPage(), and com.gmp.equipment.service.impl.MaintenanceRecordServiceImpl.update().
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/service/impl/MaintenanceRecordServiceImpl.java