GMP系统: com.gmp.hr.service.impl.QualificationServiceImpl Class Reference
com.gmp.hr.service.impl.QualificationServiceImpl Class Reference
资质服务实现类
Public Member Functions
QualificationDTO createQualification (QualificationDTO qualificationDTO)
创建员工资质
QualificationDTO getQualificationById (Long id)
根据ID获取资质
QualificationDTO getQualificationByCertificateNumber (String certificateNumber)
根据证书编号获取资质
QualificationDTO updateQualification (Long id, QualificationDTO qualificationDTO)
更新资质
void deleteQualification (Long id)
删除资质
List< QualificationDTO > getAllQualifications ()
获取所有资质
List< QualificationDTO > getQualificationsByEmployee (Long employeeId)
根据员工ID获取资质列表
List< QualificationDTO > getQualificationsByType (Long qualificationTypeId)
根据资质类型ID获取资质列表
List< QualificationDTO > getExpiringQualifications (int daysThreshold)
获取即将过期的资质
List< QualificationDTO > getExpiredQualifications ()
获取已过期的资质
QualificationDTO getQualificationByEmployeeAndType (Long employeeId, Long qualificationTypeId)
根据员工ID和资质类型ID获取资质
List< QualificationDTO > getQualificationsByDateRange (Date startDate, Date endDate)
根据日期范围查询资质
Private Member Functions
QualificationDTO convertToDTO (Qualification qualification)
将资质实体转换为DTO
Private Attributes
QualificationRepository qualificationRepository
EmployeeRepository employeeRepository
QualificationTypeRepository qualificationTypeRepository
final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd")
Detailed Description
资质服务实现类
Author
GMP Team
Version
1.0.0
Definition at line 31 of file QualificationServiceImpl.java.
Member Function Documentation
convertToDTO()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO (Qualification qualification) private
将资质实体转换为DTO
Parameters
qualification 资质实体
Returns
资质DTO
Definition at line 273 of file QualificationServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationServiceImpl.createQualification(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByCertificateNumber(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByEmployeeAndType(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationById(), and com.gmp.hr.service.impl.QualificationServiceImpl.updateQualification().
createQualification()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.createQualification (QualificationDTO qualificationDTO)
创建员工资质
Parameters
qualificationDTO 资质DTO
Returns
创建的资质DTO
Implements com.gmp.hr.service.QualificationService.
Definition at line 46 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO(), com.gmp.hr.service.impl.QualificationServiceImpl.employeeRepository, com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository, and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testCreateQualification_CertificateNumberExists(), com.gmp.hr.service.impl.QualificationServiceImplTest.testCreateQualification_EmployeeNotExists(), and com.gmp.hr.service.impl.QualificationServiceImplTest.testCreateQualification_Success().
deleteQualification()
void com.gmp.hr.service.impl.QualificationServiceImpl.deleteQualification (Long id)
删除资质
Parameters
id 资质ID
Implements com.gmp.hr.service.QualificationService.
Definition at line 157 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testDeleteQualification_Success().
getAllQualifications()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getAllQualifications ()
获取所有资质
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 170 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetAllQualifications_Success().
getExpiredQualifications()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getExpiredQualifications ()
获取已过期的资质
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 229 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetExpiredQualifications_Success().
getExpiringQualifications()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getExpiringQualifications (int daysThreshold)
获取即将过期的资质
Parameters
daysThreshold 过期天数阈值
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 212 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetExpiringQualifications_Success().
getQualificationByCertificateNumber()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByCertificateNumber (String certificateNumber)
根据证书编号获取资质
Parameters
certificateNumber 证书编号
Returns
资质DTO
Implements com.gmp.hr.service.QualificationService.
Definition at line 96 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetQualificationByCertificateNumber_Success().
getQualificationByEmployeeAndType()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByEmployeeAndType (Long employeeId, Long qualificationTypeId)
根据员工ID和资质类型ID获取资质
Parameters
employeeId 员工ID
qualificationTypeId 资质类型ID
Returns
资质DTO
Implements com.gmp.hr.service.QualificationService.
Definition at line 240 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
getQualificationById()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationById (Long id)
根据ID获取资质
Parameters
id 资质ID
Returns
资质DTO
Implements com.gmp.hr.service.QualificationService.
Definition at line 87 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetQualificationById_NotFound(), and com.gmp.hr.service.impl.QualificationServiceImplTest.testGetQualificationById_Success().
getQualificationsByDateRange()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByDateRange (Date startDate, Date endDate)
根据日期范围查询资质
Parameters
startDate 开始日期
endDate 结束日期
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 254 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
getQualificationsByEmployee()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByEmployee (Long employeeId)
根据员工ID获取资质列表
Parameters
employeeId 员工ID
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 180 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.employeeRepository, and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetQualificationsByEmployee_Success().
getQualificationsByType()
List< QualificationDTO > com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByType (Long qualificationTypeId)
根据资质类型ID获取资质列表
Parameters
qualificationTypeId 资质类型ID
Returns
资质DTO列表
Implements com.gmp.hr.service.QualificationService.
Definition at line 196 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository, and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testGetQualificationsByType_Success().
updateQualification()
QualificationDTO com.gmp.hr.service.impl.QualificationServiceImpl.updateQualification (Long id, QualificationDTO qualificationDTO)
更新资质
Parameters
id 资质ID
qualificationDTO 资质DTO
Returns
更新后的资质DTO
Implements com.gmp.hr.service.QualificationService.
Definition at line 108 of file QualificationServiceImpl.java.
References com.gmp.hr.service.impl.QualificationServiceImpl.convertToDTO(), com.gmp.hr.service.impl.QualificationServiceImpl.employeeRepository, com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository, and com.gmp.hr.service.impl.QualificationServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationServiceImplTest.testUpdateQualification_Success().
Member Data Documentation
dateFormat
final SimpleDateFormat com.gmp.hr.service.impl.QualificationServiceImpl.dateFormat = new SimpleDateFormat("yyyy-MM-dd") private
Definition at line 42 of file QualificationServiceImpl.java.
employeeRepository
EmployeeRepository com.gmp.hr.service.impl.QualificationServiceImpl.employeeRepository private
Definition at line 37 of file QualificationServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationServiceImpl.createQualification(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByEmployee(), and com.gmp.hr.service.impl.QualificationServiceImpl.updateQualification().
qualificationRepository
QualificationRepository com.gmp.hr.service.impl.QualificationServiceImpl.qualificationRepository private
Definition at line 34 of file QualificationServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationServiceImpl.createQualification(), com.gmp.hr.service.impl.QualificationServiceImpl.deleteQualification(), com.gmp.hr.service.impl.QualificationServiceImpl.getAllQualifications(), com.gmp.hr.service.impl.QualificationServiceImpl.getExpiredQualifications(), com.gmp.hr.service.impl.QualificationServiceImpl.getExpiringQualifications(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByCertificateNumber(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationByEmployeeAndType(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationById(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByDateRange(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByEmployee(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByType(), and com.gmp.hr.service.impl.QualificationServiceImpl.updateQualification().
qualificationTypeRepository
QualificationTypeRepository com.gmp.hr.service.impl.QualificationServiceImpl.qualificationTypeRepository private
Definition at line 40 of file QualificationServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationServiceImpl.createQualification(), com.gmp.hr.service.impl.QualificationServiceImpl.getQualificationsByType(), and com.gmp.hr.service.impl.QualificationServiceImpl.updateQualification().
The documentation for this class was generated from the following file:
hr-service/src/main/java/com/gmp/hr/service/impl/QualificationServiceImpl.java