GMP系统: com.gmp.edms.entity.DocumentCategoryTest Class Reference
com.gmp.edms.entity.DocumentCategoryTest Class Reference
DocumentCategory实体类的单元测试
Public Member Functions
void setUp ()
void testFieldAccess ()
Private Member Functions
void setField (Object obj, String fieldName, Object value)
Object getField (Object obj, String fieldName)
Private Attributes
DocumentCategory category
DocumentCategory parentCategory
DocumentCategory childCategory1
DocumentCategory childCategory2
Detailed Description
DocumentCategory实体类的单元测试
Author
GMP Team
Version
1.0.0
Since
2023-08-01
Definition at line 17 of file DocumentCategoryTest.java.
Member Function Documentation
getField()
Object com.gmp.edms.entity.DocumentCategoryTest.getField (Object obj, String fieldName) private
Definition at line 34 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.testFieldAccess().
setField()
void com.gmp.edms.entity.DocumentCategoryTest.setField (Object obj, String fieldName, Object value) private
Definition at line 24 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.setUp().
setUp()
void com.gmp.edms.entity.DocumentCategoryTest.setUp ()
Definition at line 46 of file DocumentCategoryTest.java.
References com.gmp.edms.entity.DocumentCategoryTest.category, com.gmp.edms.entity.DocumentCategoryTest.childCategory1, com.gmp.edms.entity.DocumentCategoryTest.childCategory2, com.gmp.edms.entity.DocumentCategoryTest.parentCategory, and com.gmp.edms.entity.DocumentCategoryTest.setField().
testFieldAccess()
void com.gmp.edms.entity.DocumentCategoryTest.testFieldAccess ()
Definition at line 192 of file DocumentCategoryTest.java.
References com.gmp.edms.entity.DocumentCategoryTest.category, and com.gmp.edms.entity.DocumentCategoryTest.getField().
Member Data Documentation
category
DocumentCategory com.gmp.edms.entity.DocumentCategoryTest.category private
Definition at line 19 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.setUp(), and com.gmp.edms.entity.DocumentCategoryTest.testFieldAccess().
childCategory1
DocumentCategory com.gmp.edms.entity.DocumentCategoryTest.childCategory1 private
Definition at line 21 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.setUp().
childCategory2
DocumentCategory com.gmp.edms.entity.DocumentCategoryTest.childCategory2 private
Definition at line 22 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.setUp().
parentCategory
DocumentCategory com.gmp.edms.entity.DocumentCategoryTest.parentCategory private
Definition at line 20 of file DocumentCategoryTest.java.
Referenced by com.gmp.edms.entity.DocumentCategoryTest.setUp().
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/entity/DocumentCategoryTest.java