GMP系统: com.gmp.qms.filter.McpVersionCompatibilityFilter Class Reference
com.gmp.qms.filter.McpVersionCompatibilityFilter Class Reference
MCP版本兼容性过滤器 在请求处理前验证客户端版本的兼容性 过滤掉不兼容版本的请求，确保系统安全性和稳定性
Public Member Functions
void clearVersionCache ()
清除版本缓存 用于在版本更新或配置更改后刷新缓存
Map< String, Object > getCacheStatistics ()
获取当前版本缓存统计信息
Static Public Attributes
static final String MCP_VERSION_HEADER = "X-MCP-Version"
static final String MCP_SYSTEM_HEADER = "X-MCP-System"
Protected Member Functions
void doFilterInternal (HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException
Private Member Functions
boolean shouldSkipVersionCheck (String requestUri)
判断是否需要跳过版本检查
void handleMissingVersionHeader (HttpServletResponse response) throws IOException
处理缺少版本头的情况
void handleInvalidVersionFormat (HttpServletResponse response, String version, String errorMessage) throws IOException
处理版本格式错误的情况
void handleIncompatibleVersion (HttpServletResponse response, String systemName, String clientVersion) throws IOException
处理不兼容版本的情况
void logVersionInfo (String systemName, String clientVersion, boolean isCompatible)
记录版本信息
Private Attributes
final McpVersionControl versionControl
final Map< String, Boolean > versionCache = new ConcurrentHashMap<>()
Static Private Attributes
static final String INCOMPATIBLE_VERSION_MESSAGE = "Incompatible MCP version. Please update your client."
static final String[] EXCLUDED_PATHS
Detailed Description
MCP版本兼容性过滤器 在请求处理前验证客户端版本的兼容性 过滤掉不兼容版本的请求，确保系统安全性和稳定性
Definition at line 30 of file McpVersionCompatibilityFilter.java.
Member Function Documentation
clearVersionCache()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.clearVersionCache ()
清除版本缓存 用于在版本更新或配置更改后刷新缓存
Definition at line 191 of file McpVersionCompatibilityFilter.java.
References com.gmp.qms.filter.McpVersionCompatibilityFilter.versionCache.
doFilterInternal()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal (HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException protected
Definition at line 54 of file McpVersionCompatibilityFilter.java.
References com.gmp.qms.filter.McpVersionCompatibilityFilter.handleIncompatibleVersion(), com.gmp.qms.filter.McpVersionCompatibilityFilter.handleInvalidVersionFormat(), com.gmp.qms.filter.McpVersionCompatibilityFilter.handleMissingVersionHeader(), com.gmp.qms.filter.McpVersionCompatibilityFilter.logVersionInfo(), com.gmp.qms.filter.McpVersionCompatibilityFilter.MCP_SYSTEM_HEADER, com.gmp.qms.filter.McpVersionCompatibilityFilter.MCP_VERSION_HEADER, com.gmp.qms.filter.McpVersionCompatibilityFilter.shouldSkipVersionCheck(), com.gmp.qms.filter.McpVersionCompatibilityFilter.versionCache, and com.gmp.qms.filter.McpVersionCompatibilityFilter.versionControl.
getCacheStatistics()
Map< String, Object > com.gmp.qms.filter.McpVersionCompatibilityFilter.getCacheStatistics ()
获取当前版本缓存统计信息
Definition at line 199 of file McpVersionCompatibilityFilter.java.
References com.gmp.qms.filter.McpVersionCompatibilityFilter.versionCache.
handleIncompatibleVersion()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.handleIncompatibleVersion (HttpServletResponse response, String systemName, String clientVersion) throws IOException private
处理不兼容版本的情况
Definition at line 155 of file McpVersionCompatibilityFilter.java.
References com.gmp.qms.filter.McpVersionCompatibilityFilter.INCOMPATIBLE_VERSION_MESSAGE, and com.gmp.qms.filter.McpVersionCompatibilityFilter.MCP_VERSION_HEADER.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
handleInvalidVersionFormat()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.handleInvalidVersionFormat (HttpServletResponse response, String version, String errorMessage) throws IOException private
处理版本格式错误的情况
Definition at line 144 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
handleMissingVersionHeader()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.handleMissingVersionHeader (HttpServletResponse response) throws IOException private
处理缺少版本头的情况
Definition at line 134 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
logVersionInfo()
void com.gmp.qms.filter.McpVersionCompatibilityFilter.logVersionInfo (String systemName, String clientVersion, boolean isCompatible) private
记录版本信息
Definition at line 174 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
shouldSkipVersionCheck()
boolean com.gmp.qms.filter.McpVersionCompatibilityFilter.shouldSkipVersionCheck (String requestUri) private
判断是否需要跳过版本检查
Definition at line 119 of file McpVersionCompatibilityFilter.java.
References com.gmp.qms.filter.McpVersionCompatibilityFilter.EXCLUDED_PATHS.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
Member Data Documentation
EXCLUDED_PATHS
final String [] com.gmp.qms.filter.McpVersionCompatibilityFilter.EXCLUDED_PATHS static private
Initial value:
= {
        "/health",
        "/actuator",
        "/api/v1/mcp/version",
        "/api/v1/mcp/compatibility"
    }
Definition at line 46 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.shouldSkipVersionCheck().
INCOMPATIBLE_VERSION_MESSAGE
final String com.gmp.qms.filter.McpVersionCompatibilityFilter.INCOMPATIBLE_VERSION_MESSAGE = "Incompatible MCP version. Please update your client." static private
Definition at line 37 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.handleIncompatibleVersion().
MCP_SYSTEM_HEADER
final String com.gmp.qms.filter.McpVersionCompatibilityFilter.MCP_SYSTEM_HEADER = "X-MCP-System" static
Definition at line 35 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
MCP_VERSION_HEADER
final String com.gmp.qms.filter.McpVersionCompatibilityFilter.MCP_VERSION_HEADER = "X-MCP-Version" static
Definition at line 33 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal(), and com.gmp.qms.filter.McpVersionCompatibilityFilter.handleIncompatibleVersion().
versionCache
final Map<String, Boolean> com.gmp.qms.filter.McpVersionCompatibilityFilter.versionCache = new ConcurrentHashMap<>() private
Definition at line 43 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.clearVersionCache(), com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal(), and com.gmp.qms.filter.McpVersionCompatibilityFilter.getCacheStatistics().
versionControl
final McpVersionControl com.gmp.qms.filter.McpVersionCompatibilityFilter.versionControl private
Definition at line 40 of file McpVersionCompatibilityFilter.java.
Referenced by com.gmp.qms.filter.McpVersionCompatibilityFilter.doFilterInternal().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/filter/McpVersionCompatibilityFilter.java