GMP系统: com.gmp.auth.service.impl.SubsystemServiceImpl Class Reference
com.gmp.auth.service.impl.SubsystemServiceImpl Class Reference
子系统管理服务实现类
Public Member Functions
List< Subsystem > getAllSubsystems ()
获取所有子系统
List< Subsystem > getEnabledSubsystems ()
获取所有启用的子系统
Subsystem getSubsystemById (Long id)
根据ID获取子系统
Subsystem getSubsystemByCode (String subsystemCode)
根据子系统代码获取子系统
Subsystem createSubsystem (Subsystem subsystem)
创建子系统
Subsystem updateSubsystem (Subsystem subsystem)
更新子系统
void deleteSubsystem (Long id)
删除子系统
Subsystem toggleSubsystemStatus (Long id, boolean enabled)
启用或禁用子系统
SubsystemPermission addPermissionToSubsystem (Long subsystemId, Long permissionId, Integer accessLevel)
为子系统添加权限
void removePermissionFromSubsystem (Long subsystemId, Long permissionId)
从子系统移除权限
SubsystemPermission updateSubsystemPermissionAccessLevel (Long subsystemId, Long permissionId, Integer accessLevel)
更新子系统权限访问级别
List< SubsystemPermission > getSubsystemPermissions (Long subsystemId)
获取子系统的所有权限
boolean hasSubsystemAccess (String username, String subsystemCode)
检查用户是否有子系统访问权限
Integer getSubsystemAccessLevel (String username, String subsystemCode)
检查用户对子系统的访问级别
List< Subsystem > getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
Set< String > getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
Map< String, Integer > getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
boolean hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统的写权限
boolean hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
List< Subsystem > getGmpCriticalSubsystems ()
获取所有GMP关键子系统
void initializeDefaultSubsystemPermissions ()
初始化默认子系统权限配置
Private Attributes
final SubsystemRepository subsystemRepository
final SubsystemPermissionRepository subsystemPermissionRepository
final PermissionRepository permissionRepository
Static Private Attributes
static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubsystemServiceImpl.class.getName())
Detailed Description
子系统管理服务实现类
Author
GMP系统开发团队
Definition at line 27 of file SubsystemServiceImpl.java.
Member Function Documentation
addPermissionToSubsystem()
SubsystemPermission com.gmp.auth.service.impl.SubsystemServiceImpl.addPermissionToSubsystem (Long subsystemId, Long permissionId, Integer accessLevel)
为子系统添加权限
Parameters
subsystemId 子系统ID
permissionId 权限ID
accessLevel 访问级别
Returns
子系统权限关联对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 96 of file SubsystemServiceImpl.java.
createSubsystem()
Subsystem com.gmp.auth.service.impl.SubsystemServiceImpl.createSubsystem (Subsystem subsystem)
创建子系统
Parameters
subsystem 子系统对象
Returns
创建的子系统对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 62 of file SubsystemServiceImpl.java.
References com.gmp.auth.service.impl.SubsystemServiceImpl.logger, and com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemRepository.
deleteSubsystem()
void com.gmp.auth.service.impl.SubsystemServiceImpl.deleteSubsystem (Long id)
删除子系统
Parameters
id 子系统ID
Implements com.gmp.auth.service.SubsystemService.
Definition at line 80 of file SubsystemServiceImpl.java.
References com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemPermissionRepository, and com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemRepository.
getAllSubsystems()
List< Subsystem > com.gmp.auth.service.impl.SubsystemServiceImpl.getAllSubsystems ()
获取所有子系统
Returns
子系统列表
Implements com.gmp.auth.service.SubsystemService.
Definition at line 38 of file SubsystemServiceImpl.java.
References com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemRepository.
getEnabledSubsystems()
List< Subsystem > com.gmp.auth.service.impl.SubsystemServiceImpl.getEnabledSubsystems ()
获取所有启用的子系统
Returns
启用的子系统列表
Implements com.gmp.auth.service.SubsystemService.
Definition at line 43 of file SubsystemServiceImpl.java.
getGmpCriticalSubsystems()
List< Subsystem > com.gmp.auth.service.impl.SubsystemServiceImpl.getGmpCriticalSubsystems ()
获取所有GMP关键子系统
Returns
GMP关键子系统列表
Implements com.gmp.auth.service.SubsystemService.
Definition at line 163 of file SubsystemServiceImpl.java.
getSubsystemAccessLevel()
Integer com.gmp.auth.service.impl.SubsystemServiceImpl.getSubsystemAccessLevel (String username, String subsystemCode)
检查用户对子系统的访问级别
Parameters
username 用户名
subsystemCode 子系统代码
Returns
访问级别，无权限返回0
Implements com.gmp.auth.service.SubsystemService.
Definition at line 127 of file SubsystemServiceImpl.java.
getSubsystemByCode()
Subsystem com.gmp.auth.service.impl.SubsystemServiceImpl.getSubsystemByCode (String subsystemCode)
根据子系统代码获取子系统
Parameters
subsystemCode 子系统代码
Returns
子系统对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 55 of file SubsystemServiceImpl.java.
getSubsystemById()
Subsystem com.gmp.auth.service.impl.SubsystemServiceImpl.getSubsystemById (Long id)
根据ID获取子系统
Parameters
id 子系统ID
Returns
子系统对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 49 of file SubsystemServiceImpl.java.
getSubsystemPermissions()
List< SubsystemPermission > com.gmp.auth.service.impl.SubsystemServiceImpl.getSubsystemPermissions (Long subsystemId)
获取子系统的所有权限
Parameters
subsystemId 子系统ID
Returns
子系统权限关联列表
Implements com.gmp.auth.service.SubsystemService.
Definition at line 115 of file SubsystemServiceImpl.java.
getUserAccessibleSubsystemCodes()
Set< String > com.gmp.auth.service.impl.SubsystemServiceImpl.getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
Parameters
username 用户名
Returns
子系统代码集合
Implements com.gmp.auth.service.SubsystemService.
Definition at line 139 of file SubsystemServiceImpl.java.
getUserAccessibleSubsystems()
List< Subsystem > com.gmp.auth.service.impl.SubsystemServiceImpl.getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
Parameters
username 用户名
Returns
可访问的子系统列表
Implements com.gmp.auth.service.SubsystemService.
Definition at line 133 of file SubsystemServiceImpl.java.
getUserSubsystemAccessLevels()
Map< String, Integer > com.gmp.auth.service.impl.SubsystemServiceImpl.getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
Parameters
username 用户名
Returns
子系统代码到访问级别的映射
Implements com.gmp.auth.service.SubsystemService.
Definition at line 145 of file SubsystemServiceImpl.java.
hasSubsystemAccess()
boolean com.gmp.auth.service.impl.SubsystemServiceImpl.hasSubsystemAccess (String username, String subsystemCode)
检查用户是否有子系统访问权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
是否有访问权限
Implements com.gmp.auth.service.SubsystemService.
Definition at line 121 of file SubsystemServiceImpl.java.
hasSubsystemAdminAccess()
boolean com.gmp.auth.service.impl.SubsystemServiceImpl.hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
是否有管理权限
Implements com.gmp.auth.service.SubsystemService.
Definition at line 157 of file SubsystemServiceImpl.java.
hasSubsystemWriteAccess()
boolean com.gmp.auth.service.impl.SubsystemServiceImpl.hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统的写权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
是否有写权限
Implements com.gmp.auth.service.SubsystemService.
Definition at line 151 of file SubsystemServiceImpl.java.
initializeDefaultSubsystemPermissions()
void com.gmp.auth.service.impl.SubsystemServiceImpl.initializeDefaultSubsystemPermissions ()
初始化默认子系统权限配置
Implements com.gmp.auth.service.SubsystemService.
Definition at line 170 of file SubsystemServiceImpl.java.
References com.gmp.auth.service.impl.SubsystemServiceImpl.logger.
removePermissionFromSubsystem()
void com.gmp.auth.service.impl.SubsystemServiceImpl.removePermissionFromSubsystem (Long subsystemId, Long permissionId)
从子系统移除权限
Parameters
subsystemId 子系统ID
permissionId 权限ID
Implements com.gmp.auth.service.SubsystemService.
Definition at line 103 of file SubsystemServiceImpl.java.
toggleSubsystemStatus()
Subsystem com.gmp.auth.service.impl.SubsystemServiceImpl.toggleSubsystemStatus (Long id, boolean enabled)
启用或禁用子系统
Parameters
id 子系统ID
enabled 是否启用
Returns
更新后的子系统对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 89 of file SubsystemServiceImpl.java.
updateSubsystem()
Subsystem com.gmp.auth.service.impl.SubsystemServiceImpl.updateSubsystem (Subsystem subsystem)
更新子系统
Parameters
subsystem 子系统对象
Returns
更新后的子系统对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 71 of file SubsystemServiceImpl.java.
References com.gmp.auth.service.impl.SubsystemServiceImpl.logger, and com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemRepository.
updateSubsystemPermissionAccessLevel()
SubsystemPermission com.gmp.auth.service.impl.SubsystemServiceImpl.updateSubsystemPermissionAccessLevel (Long subsystemId, Long permissionId, Integer accessLevel)
更新子系统权限访问级别
Parameters
subsystemId 子系统ID
permissionId 权限ID
accessLevel 访问级别
Returns
更新后的子系统权限关联对象
Implements com.gmp.auth.service.SubsystemService.
Definition at line 109 of file SubsystemServiceImpl.java.
Member Data Documentation
logger
final java.util.logging.Logger com.gmp.auth.service.impl.SubsystemServiceImpl.logger = java.util.logging.Logger.getLogger(SubsystemServiceImpl.class.getName()) static private
Definition at line 29 of file SubsystemServiceImpl.java.
Referenced by com.gmp.auth.service.impl.SubsystemServiceImpl.createSubsystem(), com.gmp.auth.service.impl.SubsystemServiceImpl.initializeDefaultSubsystemPermissions(), and com.gmp.auth.service.impl.SubsystemServiceImpl.updateSubsystem().
permissionRepository
final PermissionRepository com.gmp.auth.service.impl.SubsystemServiceImpl.permissionRepository private
Definition at line 32 of file SubsystemServiceImpl.java.
subsystemPermissionRepository
final SubsystemPermissionRepository com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemPermissionRepository private
Definition at line 31 of file SubsystemServiceImpl.java.
Referenced by com.gmp.auth.service.impl.SubsystemServiceImpl.deleteSubsystem().
subsystemRepository
final SubsystemRepository com.gmp.auth.service.impl.SubsystemServiceImpl.subsystemRepository private
Definition at line 30 of file SubsystemServiceImpl.java.
Referenced by com.gmp.auth.service.impl.SubsystemServiceImpl.createSubsystem(), com.gmp.auth.service.impl.SubsystemServiceImpl.deleteSubsystem(), com.gmp.auth.service.impl.SubsystemServiceImpl.getAllSubsystems(), and com.gmp.auth.service.impl.SubsystemServiceImpl.updateSubsystem().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/SubsystemServiceImpl.java