GMP系统: com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics Class Reference
com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics Class Reference
Public Member Functions
long getTotalCalls ()
void setTotalCalls (long totalCalls)
double getSuccessRate ()
void setSuccessRate (double successRate)
long getAvgResponseTime ()
void setAvgResponseTime (long avgResponseTime)
long getErrorCount ()
void setErrorCount (long errorCount)
Private Attributes
long totalCalls
double successRate
long avgResponseTime
long errorCount
Detailed Description
Definition at line 258 of file McpMonitoringService.java.
Member Function Documentation
getAvgResponseTime()
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getAvgResponseTime ()
Definition at line 269 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.avgResponseTime.
getErrorCount()
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getErrorCount ()
Definition at line 271 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.errorCount.
getSuccessRate()
double com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getSuccessRate ()
Definition at line 267 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.successRate.
getTotalCalls()
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getTotalCalls ()
Definition at line 265 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.totalCalls.
setAvgResponseTime()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setAvgResponseTime (long avgResponseTime)
Definition at line 270 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.avgResponseTime.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
setErrorCount()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setErrorCount (long errorCount)
Definition at line 272 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.errorCount.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
setSuccessRate()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setSuccessRate (double successRate)
Definition at line 268 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.successRate.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
setTotalCalls()
void com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setTotalCalls (long totalCalls)
Definition at line 266 of file McpMonitoringService.java.
References com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.totalCalls.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.getSystemMetrics().
Member Data Documentation
avgResponseTime
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.avgResponseTime private
Definition at line 261 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getAvgResponseTime(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setAvgResponseTime().
errorCount
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.errorCount private
Definition at line 262 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getErrorCount(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setErrorCount().
successRate
double com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.successRate private
Definition at line 260 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getSuccessRate(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setSuccessRate().
totalCalls
long com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.totalCalls private
Definition at line 259 of file McpMonitoringService.java.
Referenced by com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.getTotalCalls(), and com.gmp.qms.service.monitoring.McpMonitoringService.SystemMetrics.setTotalCalls().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/monitoring/McpMonitoringService.java