GMP系统: com.gmp.hr.service.impl.QualificationTypeServiceImpl Class Reference
com.gmp.hr.service.impl.QualificationTypeServiceImpl Class Reference
资质类型服务实现类
Public Member Functions
QualificationTypeServiceImpl (QualificationTypeRepository qualificationTypeRepository, QualificationRepository qualificationRepository)
QualificationTypeDTO createQualificationType (QualificationTypeDTO qualificationTypeDTO)
创建资质类型
QualificationTypeDTO getQualificationTypeById (Long id)
根据ID获取资质类型
QualificationTypeDTO getQualificationTypeByCode (String typeCode)
根据资质代码获取资质类型
QualificationTypeDTO updateQualificationType (Long id, QualificationTypeDTO qualificationTypeDTO)
更新资质类型
void deleteQualificationType (Long id)
删除资质类型
List< QualificationTypeDTO > getAllQualificationTypes ()
获取所有资质类型
List< QualificationTypeDTO > getQualificationTypesByName (String typeName)
根据资质名称查询资质类型
List< QualificationTypeDTO > getQualificationTypesNeedUpdate ()
获取需要定期更新的资质类型
Private Member Functions
QualificationTypeDTO convertToDTO (QualificationType qualificationType)
将资质类型实体转换为DTO
Private Attributes
final QualificationTypeRepository qualificationTypeRepository
final QualificationRepository qualificationRepository
Detailed Description
资质类型服务实现类
Author
GMP Team
Version
1.0.0
Definition at line 24 of file QualificationTypeServiceImpl.java.
Constructor & Destructor Documentation
QualificationTypeServiceImpl()
com.gmp.hr.service.impl.QualificationTypeServiceImpl.QualificationTypeServiceImpl (QualificationTypeRepository qualificationTypeRepository, QualificationRepository qualificationRepository)
Definition at line 30 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationRepository, and com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Member Function Documentation
convertToDTO()
QualificationTypeDTO com.gmp.hr.service.impl.QualificationTypeServiceImpl.convertToDTO (QualificationType qualificationType) private
将资质类型实体转换为DTO
Parameters
qualificationType 资质类型实体
Returns
资质类型DTO
Definition at line 201 of file QualificationTypeServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImpl.createQualificationType(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypeById(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.updateQualificationType().
createQualificationType()
QualificationTypeDTO com.gmp.hr.service.impl.QualificationTypeServiceImpl.createQualificationType (QualificationTypeDTO qualificationTypeDTO)
创建资质类型
Parameters
qualificationTypeDTO 资质类型DTO
Returns
创建的资质类型DTO
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 38 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testCreateQualificationType_CodeExists(), and com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testCreateQualificationType_Success().
deleteQualificationType()
void com.gmp.hr.service.impl.QualificationTypeServiceImpl.deleteQualificationType (Long id)
删除资质类型
Parameters
id 资质类型ID
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 146 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationRepository, and com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testDeleteQualificationType_HasQualifications(), and com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testDeleteQualificationType_Success().
getAllQualificationTypes()
List< QualificationTypeDTO > com.gmp.hr.service.impl.QualificationTypeServiceImpl.getAllQualificationTypes ()
获取所有资质类型
Returns
资质类型DTO列表
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 167 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testGetAllQualificationTypes_NeedUpdate(), and com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testGetAllQualificationTypes_Success().
getQualificationTypeByCode()
QualificationTypeDTO com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypeByCode (String typeCode)
根据资质代码获取资质类型
Parameters
typeCode 资质代码
Returns
资质类型DTO
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 88 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
getQualificationTypeById()
QualificationTypeDTO com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypeById (Long id)
根据ID获取资质类型
Parameters
id 资质类型ID
Returns
资质类型DTO
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 75 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testGetQualificationTypeById_NotFound(), and com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testGetQualificationTypeById_Success().
getQualificationTypesByName()
List< QualificationTypeDTO > com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypesByName (String typeName)
根据资质名称查询资质类型
Parameters
typeName 资质名称
Returns
资质类型DTO列表
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 177 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
getQualificationTypesNeedUpdate()
List< QualificationTypeDTO > com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypesNeedUpdate ()
获取需要定期更新的资质类型
Returns
资质类型DTO列表
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 187 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
updateQualificationType()
QualificationTypeDTO com.gmp.hr.service.impl.QualificationTypeServiceImpl.updateQualificationType (Long id, QualificationTypeDTO qualificationTypeDTO)
更新资质类型
Parameters
id 资质类型ID
qualificationTypeDTO 资质类型DTO
Returns
更新后的资质类型DTO
Implements com.gmp.hr.service.QualificationTypeService.
Definition at line 99 of file QualificationTypeServiceImpl.java.
References com.gmp.hr.service.impl.QualificationTypeServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImplTest.testUpdateQualificationType_Success().
Member Data Documentation
qualificationRepository
final QualificationRepository com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationRepository private
Definition at line 27 of file QualificationTypeServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImpl.deleteQualificationType(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.QualificationTypeServiceImpl().
qualificationTypeRepository
final QualificationTypeRepository com.gmp.hr.service.impl.QualificationTypeServiceImpl.qualificationTypeRepository private
Definition at line 26 of file QualificationTypeServiceImpl.java.
Referenced by com.gmp.hr.service.impl.QualificationTypeServiceImpl.createQualificationType(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.deleteQualificationType(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getAllQualificationTypes(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypeByCode(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypeById(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypesByName(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.getQualificationTypesNeedUpdate(), com.gmp.hr.service.impl.QualificationTypeServiceImpl.QualificationTypeServiceImpl(), and com.gmp.hr.service.impl.QualificationTypeServiceImpl.updateQualificationType().
The documentation for this class was generated from the following file:
hr-service/src/main/java/com/gmp/hr/service/impl/QualificationTypeServiceImpl.java