GMP系统: com.gmp.equipment.exception.GlobalExceptionHandler Class Reference
com.gmp.equipment.exception.GlobalExceptionHandler Class Reference
全局异常处理器 用于统一处理系统中的各种异常
Public Member Functions
ResponseResult< Object > handleEquipmentServiceException (EquipmentServiceException ex)
处理设备服务业务异常
ResponseResult< Object > handleMethodArgumentNotValidException (MethodArgumentNotValidException ex)
处理参数验证异常（方法参数验证）
ResponseResult< Object > handleConstraintViolationException (ConstraintViolationException ex)
处理参数验证异常（请求参数验证）
ResponseResult< Object > handleNullPointerException (NullPointerException ex)
处理空指针异常
ResponseResult< Object > handleException (Exception ex)
处理所有未捕获的异常
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class)
Detailed Description
全局异常处理器 用于统一处理系统中的各种异常
Definition at line 21 of file GlobalExceptionHandler.java.
Member Function Documentation
handleConstraintViolationException()
ResponseResult< Object > com.gmp.equipment.exception.GlobalExceptionHandler.handleConstraintViolationException (ConstraintViolationException ex)
处理参数验证异常（请求参数验证）
Parameters
ex 约束违反异常
Returns
统一响应结果
Definition at line 62 of file GlobalExceptionHandler.java.
References com.gmp.equipment.exception.GlobalExceptionHandler.logger.
handleEquipmentServiceException()
ResponseResult< Object > com.gmp.equipment.exception.GlobalExceptionHandler.handleEquipmentServiceException (EquipmentServiceException ex)
处理设备服务业务异常
Parameters
ex 设备服务异常
Returns
统一响应结果
Definition at line 32 of file GlobalExceptionHandler.java.
References com.gmp.equipment.exception.EquipmentServiceException.getErrorCode(), and com.gmp.equipment.exception.GlobalExceptionHandler.logger.
handleException()
ResponseResult< Object > com.gmp.equipment.exception.GlobalExceptionHandler.handleException (Exception ex)
处理所有未捕获的异常
Parameters
ex 异常
Returns
统一响应结果
Definition at line 88 of file GlobalExceptionHandler.java.
References com.gmp.equipment.exception.GlobalExceptionHandler.logger.
handleMethodArgumentNotValidException()
ResponseResult< Object > com.gmp.equipment.exception.GlobalExceptionHandler.handleMethodArgumentNotValidException (MethodArgumentNotValidException ex)
处理参数验证异常（方法参数验证）
Parameters
ex 方法参数验证异常
Returns
统一响应结果
Definition at line 47 of file GlobalExceptionHandler.java.
References com.gmp.equipment.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.equipment.exception.GlobalExceptionHandlerTest.testHandleMethodArgumentNotValidException().
handleNullPointerException()
ResponseResult< Object > com.gmp.equipment.exception.GlobalExceptionHandler.handleNullPointerException (NullPointerException ex)
处理空指针异常
Parameters
ex 空指针异常
Returns
统一响应结果
Definition at line 76 of file GlobalExceptionHandler.java.
References com.gmp.equipment.exception.GlobalExceptionHandler.logger.
Referenced by com.gmp.equipment.exception.GlobalExceptionHandlerTest.testHandleNullPointerException().
Member Data Documentation
logger
final Logger com.gmp.equipment.exception.GlobalExceptionHandler.logger = LoggerFactory.getLogger(GlobalExceptionHandler.class) static private
Definition at line 23 of file GlobalExceptionHandler.java.
Referenced by com.gmp.equipment.exception.GlobalExceptionHandler.handleConstraintViolationException(), com.gmp.equipment.exception.GlobalExceptionHandler.handleEquipmentServiceException(), com.gmp.equipment.exception.GlobalExceptionHandler.handleException(), com.gmp.equipment.exception.GlobalExceptionHandler.handleMethodArgumentNotValidException(), and com.gmp.equipment.exception.GlobalExceptionHandler.handleNullPointerException().
The documentation for this class was generated from the following file:
equipment-service/src/main/java/com/gmp/equipment/exception/GlobalExceptionHandler.java