GMP系统: com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest Class Reference
com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest Class Reference
测试Why-What-How注释:
Package Functions
void testSaveAndFindByEquipmentCode ()
void testFindByStatus ()
void testFindByStatusWithPaging ()
void testFindEquipmentDueForMaintenance ()
void testFindCalibrationOverdueEquipment ()
void testFindEquipmentDueForCalibration ()
void testFindEquipmentUnderWarranty ()
void testCountEquipmentByType ()
void testFindCriticalEquipment ()
void testFindMonitoredEquipment ()
void testFindEquipmentWithFilters ()
void testExistsByEquipmentCode ()
void testFindBySensorId ()
Private Attributes
EquipmentRepository equipmentRepository
Detailed Description
测试Why-What-How注释:
WHY: Equipment管理系统的数据访问层是GMP合规的核心，必须确保数据库查询的准确性、 性能和数据完整性，因为任何查询错误都可能导致设备状态误判、生产作业错误， 而GMP要求所有设备数据必须具有完整可追溯性。
WHAT: EquipmentRepositoryIntegrationTest通过完整数据库测试验证所有查询接口的正确性， 包含CRUD操作、业务查询、统计分析、边界条件处理，确保数据访问层能在生产环境 下可靠稳定运行，支持高并发和大数据量的处理需求。
HOW: 使用Spring Boot的@DataJpaTest注解创建干净的数据库测试环境，结合TestContainers 提供真实的PostgreSQL数据库，通过实体构建器创建测试数据，采用断言式验证结果。
Definition at line 33 of file EquipmentRepositoryIntegrationTest.java.
Member Function Documentation
testCountEquipmentByType()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testCountEquipmentByType () package
Definition at line 322 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.countEquipmentByType().
testExistsByEquipmentCode()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testExistsByEquipmentCode () package
Definition at line 548 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.existsByEquipmentCode().
testFindBySensorId()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindBySensorId () package
Definition at line 570 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findBySensorId().
testFindByStatus()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindByStatus () package
Definition at line 69 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findByEquipmentStatus().
testFindByStatusWithPaging()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindByStatusWithPaging () package
Definition at line 108 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findByEquipmentStatus().
testFindCalibrationOverdueEquipment()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindCalibrationOverdueEquipment () package
Definition at line 181 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findCalibrationOverdueEquipment().
testFindCriticalEquipment()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindCriticalEquipment () package
Definition at line 380 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findCriticalEquipment().
testFindEquipmentDueForCalibration()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentDueForCalibration () package
Definition at line 237 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findEquipmentDueForCalibration().
testFindEquipmentDueForMaintenance()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentDueForMaintenance () package
Definition at line 139 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findEquipmentDueForMaintenance().
testFindEquipmentUnderWarranty()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentUnderWarranty () package
Definition at line 280 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findEquipmentUnderWarranty().
testFindEquipmentWithFilters()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentWithFilters () package
Definition at line 490 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findEquipmentWithFilters().
testFindMonitoredEquipment()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindMonitoredEquipment () package
Definition at line 434 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findMonitoredEquipment().
testSaveAndFindByEquipmentCode()
void com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testSaveAndFindByEquipmentCode () package
Definition at line 39 of file EquipmentRepositoryIntegrationTest.java.
References com.gmp.equipment.repository.EquipmentRepository.findByEquipmentCode().
Member Data Documentation
equipmentRepository
EquipmentRepository com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.equipmentRepository private
Definition at line 36 of file EquipmentRepositoryIntegrationTest.java.
The documentation for this class was generated from the following file:
equipment-management/src/test/java/com/gmp/equipment/repository/EquipmentRepositoryIntegrationTest.java