GMP系统: com.gmp.auth.service.impl.UserRoleServiceImpl Class Reference
com.gmp.auth.service.impl.UserRoleServiceImpl Class Reference
用户角色管理服务实现
Public Member Functions
UserRole assignRoleToUser (Long userId, Long roleId, Long assignedBy)
为用户分配角色
List< UserRole > assignRolesToUser (Long userId, List< Long > roleIds, Long assignedBy)
为用户分配多个角色
void removeRoleFromUser (Long userId, Long roleId)
移除用户的角色
List< Role > getUserRoles (Long userId)
获取用户的所有角色
Set< String > getUserRoleCodes (Long userId)
获取用户的角色代码集合
boolean hasRole (Long userId, String roleCode)
检查用户是否拥有指定角色
boolean hasAnyRole (Long userId, List< String > roleCodes)
检查用户是否拥有指定角色之一
void refreshExpiredUserRoles ()
刷新用户过期的角色
Private Attributes
UserRoleRepository userRoleRepository
RoleRepository roleRepository
Detailed Description
用户角色管理服务实现
Author
GMP系统开发团队
Definition at line 26 of file UserRoleServiceImpl.java.
Member Function Documentation
assignRolesToUser()
List< UserRole > com.gmp.auth.service.impl.UserRoleServiceImpl.assignRolesToUser (Long userId, List< Long > roleIds, Long assignedBy)
为用户分配多个角色
为指定用户分配多个角色
Parameters
userId 用户ID
roleIds 角色ID列表
assignedBy 分配人ID
Returns
List<UserRole> 分配结果列表
See also
com.gmp.auth.entity.UserRole
Implements com.gmp.auth.service.UserRoleService.
Definition at line 43 of file UserRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserRoleServiceImpl.assignRoleToUser().
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.assignRolesToUser_Exception(), com.gmp.auth.service.impl.UserRoleServiceImplTest.assignRolesToUser_RoleAlreadyExists(), and com.gmp.auth.service.impl.UserRoleServiceImplTest.assignRolesToUser_Success().
assignRoleToUser()
UserRole com.gmp.auth.service.impl.UserRoleServiceImpl.assignRoleToUser (Long userId, Long roleId, Long assignedBy)
为用户分配角色
为指定用户分配指定角色
Parameters
userId 用户ID
roleId 角色ID
assignedBy 分配人ID
Returns
UserRole 分配结果
See also
com.gmp.auth.entity.UserRole
Implements com.gmp.auth.service.UserRoleService.
Definition at line 35 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImpl.assignRolesToUser(), and com.gmp.auth.service.impl.UserRoleServiceImplTest.assignRoleToUser_Success().
getUserRoleCodes()
Set< String > com.gmp.auth.service.impl.UserRoleServiceImpl.getUserRoleCodes (Long userId)
获取用户的角色代码集合
获取指定用户的角色代码集合
Parameters
userId 用户ID
Returns
Set<String> 角色代码集合
Implements com.gmp.auth.service.UserRoleService.
Definition at line 77 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.getUserRoleCodes_ReturnsEmptySet(), com.gmp.auth.service.impl.UserRoleServiceImpl.hasAnyRole(), and com.gmp.auth.service.impl.UserRoleServiceImplTest.hasAnyRole_NoMatchingRole().
getUserRoles()
List< Role > com.gmp.auth.service.impl.UserRoleServiceImpl.getUserRoles (Long userId)
获取用户的所有角色
获取指定用户的所有角色列表
Parameters
userId 用户ID
Returns
List<Role> 角色列表
See also
com.gmp.auth.entity.Role
Implements com.gmp.auth.service.UserRoleService.
Definition at line 71 of file UserRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserRoleServiceImpl.roleRepository.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.getUserRoles_Success().
hasAnyRole()
boolean com.gmp.auth.service.impl.UserRoleServiceImpl.hasAnyRole (Long userId, List< String > roleCodes)
检查用户是否拥有指定角色之一
检查指定用户是否拥有指定角色列表中的任一角色
Parameters
userId 用户ID
roleCodes 角色代码列表
Returns
boolean 如果用户拥有任一角色返回true，否则返回false
Implements com.gmp.auth.service.UserRoleService.
Definition at line 91 of file UserRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserRoleServiceImpl.getUserRoleCodes().
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.hasAnyRole_HasMatchingRole(), and com.gmp.auth.service.impl.UserRoleServiceImplTest.hasAnyRole_NoMatchingRole().
hasRole()
boolean com.gmp.auth.service.impl.UserRoleServiceImpl.hasRole (Long userId, String roleCode)
检查用户是否拥有指定角色
检查指定用户是否拥有指定角色
Parameters
userId 用户ID
roleCode 角色代码
Returns
boolean 如果用户拥有该角色返回true，否则返回false
Implements com.gmp.auth.service.UserRoleService.
Definition at line 84 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.hasRole_ReturnsFalse().
refreshExpiredUserRoles()
void com.gmp.auth.service.impl.UserRoleServiceImpl.refreshExpiredUserRoles ()
刷新用户过期的角色
刷新用户过期的角色，更新角色状态
Implements com.gmp.auth.service.UserRoleService.
Definition at line 97 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.refreshExpiredUserRoles_NoOperation().
removeRoleFromUser()
void com.gmp.auth.service.impl.UserRoleServiceImpl.removeRoleFromUser (Long userId, Long roleId)
移除用户的角色
移除指定用户的指定角色
Parameters
userId 用户ID
roleId 角色ID
Implements com.gmp.auth.service.UserRoleService.
Definition at line 62 of file UserRoleServiceImpl.java.
References com.gmp.auth.service.impl.UserRoleServiceImpl.userRoleRepository.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImplTest.removeRoleFromUser_Success().
Member Data Documentation
roleRepository
RoleRepository com.gmp.auth.service.impl.UserRoleServiceImpl.roleRepository private
Definition at line 32 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImpl.getUserRoles().
userRoleRepository
UserRoleRepository com.gmp.auth.service.impl.UserRoleServiceImpl.userRoleRepository private
Definition at line 29 of file UserRoleServiceImpl.java.
Referenced by com.gmp.auth.service.impl.UserRoleServiceImpl.removeRoleFromUser().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/UserRoleServiceImpl.java