GMP系统: com.gmp.auth.service.impl.AuditLogServiceImpl Class Reference
com.gmp.auth.service.impl.AuditLogServiceImpl Class Reference
审计日志服务实现类 提供增强的审计日志功能实现
Public Member Functions
void logLogout (String username)
记录登出（简化版）
void logLoginSuccess (String username, String ipAddress, String userAgent)
记录登录成功（简化版）
void logLoginFailure (String username, String ipAddress, String userAgent, String reason)
记录登录失败
void logPasswordChange (String username)
记录密码修改（简化版）
void logPasswordReset (String username)
记录密码重置（简化版）
void logPasswordReset (Long userId, String username, String ipAddress)
记录密码重置事件
void logPasswordChange (Long userId, String username, String ipAddress)
记录密码修改事件
void logLoginSuccess (Long userId, String username, String ipAddress, String userAgent)
记录登录成功
OperationLog logOperation (OperationLog log)
记录操作日志
OperationLog logLogin (Long userId, String username, String ipAddress, String userAgent, boolean success, Map< String, Object > additionalInfo)
记录登录操作
OperationLog logLogout (Long userId, String username, String ipAddress)
记录登出操作
OperationLog logUserManagement (Long operatorId, String operatorName, Long targetUserId, String targetUsername, OperationLog.OperationType operationType, boolean success, String details)
记录用户管理操作
OperationLog logRolePermissionChange (Long operatorId, String operatorName, Long roleId, String roleCode, String permissionChanges, boolean success)
记录角色权限变更操作
OperationLog logRoleAssignment (Long operatorId, String operatorName, Long userId, String username, Long roleId, String roleCode, boolean isAssign, boolean success)
记录用户角色分配操作
OperationLog logSecurityEvent (Long userId, String username, String eventType, String severity, String details, String ipAddress)
记录安全事件
Page< OperationLog > findLogsByPage (Pageable pageable, Map< String, Object > filters)
分页查询操作日志
Page< OperationLog > findLogsByUserId (Long userId, Pageable pageable)
根据用户ID查询操作日志
Page< OperationLog > findLogsByTimeRange (LocalDateTime startTime, LocalDateTime endTime, Pageable pageable)
查询指定时间范围内的操作日志
Page< OperationLog > findFailedOperations (LocalDateTime since, Pageable pageable)
查询失败的操作日志
Map< String, Object > getOperationStatistics (LocalDateTime startTime, LocalDateTime endTime)
获取操作统计信息
int cleanupOldLogs (int daysToKeep)
清理过期日志
byte[] exportLogs (Map< String, Object > filters, String format)
导出日志到指定格式
Private Attributes
OperationLogRepository operationLogRepository
ObjectMapper objectMapper
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(AuditLogServiceImpl.class)
Detailed Description
审计日志服务实现类 提供增强的审计日志功能实现
Author
GMP系统开发团队
Definition at line 30 of file AuditLogServiceImpl.java.
Member Function Documentation
cleanupOldLogs()
int com.gmp.auth.service.impl.AuditLogServiceImpl.cleanupOldLogs (int daysToKeep)
清理过期日志
Parameters
daysToKeep 保留天数
Returns
删除的日志数量
Implements com.gmp.auth.service.AuditLogService.
Definition at line 336 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, and com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
exportLogs()
byte[] com.gmp.auth.service.impl.AuditLogServiceImpl.exportLogs (Map< String, Object > filters, String format)
导出日志到指定格式
Parameters
filters 过滤条件
format 导出格式
Returns
导出的日志数据
Implements com.gmp.auth.service.AuditLogService.
Definition at line 351 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper, and com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
findFailedOperations()
Page< OperationLog > com.gmp.auth.service.impl.AuditLogServiceImpl.findFailedOperations (LocalDateTime since, Pageable pageable)
查询失败的操作日志
Parameters
since 从什么时间开始
pageable 分页参数
Returns
分页后的操作日志列表
Implements com.gmp.auth.service.AuditLogService.
Definition at line 297 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
findLogsByPage()
Page< OperationLog > com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByPage (Pageable pageable, Map< String, Object > filters)
分页查询操作日志
Parameters
pageable 分页参数
filters 过滤条件
Returns
分页后的操作日志列表
Implements com.gmp.auth.service.AuditLogService.
Definition at line 266 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
findLogsByTimeRange()
Page< OperationLog > com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByTimeRange (LocalDateTime startTime, LocalDateTime endTime, Pageable pageable)
查询指定时间范围内的操作日志
Parameters
startTime 开始时间
endTime 结束时间
pageable 分页参数
Returns
分页后的操作日志列表
Implements com.gmp.auth.service.AuditLogService.
Definition at line 285 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
findLogsByUserId()
Page< OperationLog > com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByUserId (Long userId, Pageable pageable)
根据用户ID查询操作日志
Parameters
userId 用户ID
pageable 分页参数
Returns
分页后的操作日志列表
Implements com.gmp.auth.service.AuditLogService.
Definition at line 273 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
getOperationStatistics()
Map< String, Object > com.gmp.auth.service.impl.AuditLogServiceImpl.getOperationStatistics (LocalDateTime startTime, LocalDateTime endTime)
获取操作统计信息
Parameters
startTime 开始时间
endTime 结束时间
Returns
统计结果
Implements com.gmp.auth.service.AuditLogService.
Definition at line 309 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
logLogin()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logLogin (Long userId, String username, String ipAddress, String userAgent, boolean success, Map< String, Object > additionalInfo)
记录登录操作
Parameters
userId 用户ID
username 用户名
ipAddress IP地址
userAgent 用户代理
success 是否成功
additionalInfo 附加信息
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 115 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), and com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper.
logLoginFailure()
void com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginFailure (String username, String ipAddress, String userAgent, String reason)
记录登录失败
Parameters
username 用户名
ipAddress IP地址
userAgent 用户代理
reason 失败原因
Implements com.gmp.auth.service.AuditLogService.
Definition at line 53 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger.
logLoginSuccess() [1/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginSuccess (Long userId, String username, String ipAddress, String userAgent)
记录登录成功
Parameters
userId 用户ID
username 用户名
ipAddress IP地址
userAgent 用户代理
Implements com.gmp.auth.service.AuditLogService.
Definition at line 93 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation().
logLoginSuccess() [2/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginSuccess (String username, String ipAddress, String userAgent)
记录登录成功（简化版）
Parameters
username 用户名
ipAddress IP地址
userAgent 用户代理
Implements com.gmp.auth.service.AuditLogService.
Definition at line 47 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger.
logLogout() [1/2]
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logLogout (Long userId, String username, String ipAddress)
记录登出操作
Parameters
userId 用户ID
username 用户名
ipAddress IP地址
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 141 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation().
logLogout() [2/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logLogout (String username)
记录登出（简化版）
Parameters
username 用户名
Implements com.gmp.auth.service.AuditLogService.
Definition at line 41 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger.
logOperation()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation (OperationLog log)
记录操作日志
Parameters
log 操作日志实体
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 105 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, and com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository.
Referenced by com.gmp.auth.service.impl.AuditLogServiceImpl.logLogin(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginSuccess(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLogout(), com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordChange(), com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordReset(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRoleAssignment(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRolePermissionChange(), com.gmp.auth.service.impl.AuditLogServiceImpl.logSecurityEvent(), and com.gmp.auth.service.impl.AuditLogServiceImpl.logUserManagement().
logPasswordChange() [1/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordChange (Long userId, String username, String ipAddress)
记录密码修改事件
Parameters
userId 用户ID
username 用户名
ipAddress IP地址
Implements com.gmp.auth.service.AuditLogService.
Definition at line 82 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation().
logPasswordChange() [2/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordChange (String username)
记录密码修改（简化版）
Parameters
username 用户名
Implements com.gmp.auth.service.AuditLogService.
Definition at line 59 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger.
logPasswordReset() [1/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordReset (Long userId, String username, String ipAddress)
记录密码重置事件
Parameters
userId 用户ID
username 用户名
ipAddress IP地址
Implements com.gmp.auth.service.AuditLogService.
Definition at line 71 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation().
logPasswordReset() [2/2]
void com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordReset (String username)
记录密码重置（简化版）
Parameters
username 用户名
Implements com.gmp.auth.service.AuditLogService.
Definition at line 65 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger.
logRoleAssignment()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logRoleAssignment (Long operatorId, String operatorName, Long userId, String username, Long roleId, String roleCode, boolean isAssign, boolean success)
记录用户角色分配操作
Parameters
operatorId 操作者ID
operatorName 操作者名称
userId 用户ID
username 用户名
roleId 角色ID
roleCode 角色代码
isAssign 是否为分配操作（true为分配，false为撤销）
success 是否成功
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 203 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), and com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper.
logRolePermissionChange()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logRolePermissionChange (Long operatorId, String operatorName, Long roleId, String roleCode, String permissionChanges, boolean success)
记录角色权限变更操作
Parameters
operatorId 操作者ID
operatorName 操作者名称
roleId 角色ID
roleCode 角色代码
permissionChanges 权限变更详情
success 是否成功
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 176 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), and com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper.
logSecurityEvent()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logSecurityEvent (Long userId, String username, String eventType, String severity, String details, String ipAddress)
记录安全事件
Parameters
userId 用户ID
username 用户名
eventType 事件类型
severity 严重程度
details 事件详情
ipAddress IP地址
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 236 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), and com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper.
logUserManagement()
OperationLog com.gmp.auth.service.impl.AuditLogServiceImpl.logUserManagement (Long operatorId, String operatorName, Long targetUserId, String targetUsername, OperationLog.OperationType operationType, boolean success, String details)
记录用户管理操作
Parameters
operatorId 操作者ID
operatorName 操作者名称
targetUserId 目标用户ID
targetUsername 目标用户名
operationType 操作类型
success 是否成功
details 操作详情
Returns
保存后的操作日志
Implements com.gmp.auth.service.AuditLogService.
Definition at line 146 of file AuditLogServiceImpl.java.
References com.gmp.auth.service.impl.AuditLogServiceImpl.logger, com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), and com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper.
Member Data Documentation
logger
final Logger com.gmp.auth.service.impl.AuditLogServiceImpl.logger = LoggerFactory.getLogger(AuditLogServiceImpl.class) static private
Definition at line 32 of file AuditLogServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuditLogServiceImpl.cleanupOldLogs(), com.gmp.auth.service.impl.AuditLogServiceImpl.exportLogs(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLogin(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginFailure(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLoginSuccess(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLogout(), com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation(), com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordChange(), com.gmp.auth.service.impl.AuditLogServiceImpl.logPasswordReset(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRoleAssignment(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRolePermissionChange(), com.gmp.auth.service.impl.AuditLogServiceImpl.logSecurityEvent(), and com.gmp.auth.service.impl.AuditLogServiceImpl.logUserManagement().
objectMapper
ObjectMapper com.gmp.auth.service.impl.AuditLogServiceImpl.objectMapper private
Definition at line 38 of file AuditLogServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuditLogServiceImpl.exportLogs(), com.gmp.auth.service.impl.AuditLogServiceImpl.logLogin(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRoleAssignment(), com.gmp.auth.service.impl.AuditLogServiceImpl.logRolePermissionChange(), com.gmp.auth.service.impl.AuditLogServiceImpl.logSecurityEvent(), and com.gmp.auth.service.impl.AuditLogServiceImpl.logUserManagement().
operationLogRepository
OperationLogRepository com.gmp.auth.service.impl.AuditLogServiceImpl.operationLogRepository private
Definition at line 35 of file AuditLogServiceImpl.java.
Referenced by com.gmp.auth.service.impl.AuditLogServiceImpl.cleanupOldLogs(), com.gmp.auth.service.impl.AuditLogServiceImpl.exportLogs(), com.gmp.auth.service.impl.AuditLogServiceImpl.findFailedOperations(), com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByPage(), com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByTimeRange(), com.gmp.auth.service.impl.AuditLogServiceImpl.findLogsByUserId(), com.gmp.auth.service.impl.AuditLogServiceImpl.getOperationStatistics(), and com.gmp.auth.service.impl.AuditLogServiceImpl.logOperation().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/AuditLogServiceImpl.java