GMP系统: com.gmp.qms.client.LimsClientFallback Class Reference
com.gmp.qms.client.LimsClientFallback Class Reference
LIMS系统客户端降级类，实现服务降级机制 当LIMS系统不可用时，提供默认响应，确保QMS系统正常运行
Public Member Functions
TestResultDTO getTestResults (String sampleId)
QualityStandardDTO getQualityStandard (String standardCode)
void sendNotification (NotificationDTO notificationDTO)
TestResultDTO getSampleInfo (String sampleId)
boolean isSampleTestCompleted (String sampleId)
TestResultDTO getTestResults (@PathVariable("sampleId") String sampleId)
获取测试结果
QualityStandardDTO getQualityStandard (@PathVariable("standardCode") String standardCode)
获取质量标准
void sendNotification (@RequestBody NotificationDTO notificationDTO)
发送通知到LIMS系统
TestResultDTO getSampleInfo (@PathVariable("sampleId") String sampleId)
获取样品信息
boolean isSampleTestCompleted (@PathVariable("sampleId") String sampleId)
检查样品测试是否完成
Private Member Functions
void recordFallbackRequest (String operation, String identifier)
记录降级请求信息
void saveToRetryQueue (String operation, Object data)
保存到重试队列
Detailed Description
LIMS系统客户端降级类，实现服务降级机制 当LIMS系统不可用时，提供默认响应，确保QMS系统正常运行
Author
GMP系统开发团队
Definition at line 17 of file LimsClientFallback.java.
Member Function Documentation
getQualityStandard() [1/2]
QualityStandardDTO com.gmp.qms.client.LimsClient.getQualityStandard (@PathVariable("standardCode") String standardCode) inherited
获取质量标准
Parameters
standardCode 标准代码
Returns
质量标准信息
getQualityStandard() [2/2]
QualityStandardDTO com.gmp.qms.client.LimsClientFallback.getQualityStandard (String standardCode)
Definition at line 34 of file LimsClientFallback.java.
References com.gmp.qms.client.LimsClientFallback.recordFallbackRequest().
getSampleInfo() [1/2]
TestResultDTO com.gmp.qms.client.LimsClient.getSampleInfo (@PathVariable("sampleId") String sampleId) inherited
获取样品信息
Parameters
sampleId 样品ID
Returns
测试结果（包含样品信息）
getSampleInfo() [2/2]
TestResultDTO com.gmp.qms.client.LimsClientFallback.getSampleInfo (String sampleId)
Definition at line 54 of file LimsClientFallback.java.
References com.gmp.qms.client.LimsClientFallback.recordFallbackRequest().
getTestResults() [1/2]
TestResultDTO com.gmp.qms.client.LimsClient.getTestResults (@PathVariable("sampleId") String sampleId) inherited
获取测试结果
Parameters
sampleId 样品ID
Returns
测试结果信息
getTestResults() [2/2]
TestResultDTO com.gmp.qms.client.LimsClientFallback.getTestResults (String sampleId)
Definition at line 20 of file LimsClientFallback.java.
References com.gmp.qms.client.LimsClientFallback.recordFallbackRequest().
isSampleTestCompleted() [1/2]
boolean com.gmp.qms.client.LimsClient.isSampleTestCompleted (@PathVariable("sampleId") String sampleId) inherited
检查样品测试是否完成
Parameters
sampleId 样品ID
Returns
是否已完成测试
isSampleTestCompleted() [2/2]
boolean com.gmp.qms.client.LimsClientFallback.isSampleTestCompleted (String sampleId)
Definition at line 67 of file LimsClientFallback.java.
References com.gmp.qms.client.LimsClientFallback.recordFallbackRequest().
recordFallbackRequest()
void com.gmp.qms.client.LimsClientFallback.recordFallbackRequest (String operation, String identifier) private
记录降级请求信息
Parameters
operation 操作类型
identifier 标识符
Definition at line 81 of file LimsClientFallback.java.
Referenced by com.gmp.qms.client.LimsClientFallback.getQualityStandard(), com.gmp.qms.client.LimsClientFallback.getSampleInfo(), com.gmp.qms.client.LimsClientFallback.getTestResults(), com.gmp.qms.client.LimsClientFallback.isSampleTestCompleted(), and com.gmp.qms.client.LimsClientFallback.sendNotification().
saveToRetryQueue()
void com.gmp.qms.client.LimsClientFallback.saveToRetryQueue (String operation, Object data) private
保存到重试队列
Parameters
operation 操作类型
data 数据对象
Definition at line 91 of file LimsClientFallback.java.
Referenced by com.gmp.qms.client.LimsClientFallback.sendNotification().
sendNotification() [1/2]
void com.gmp.qms.client.LimsClient.sendNotification (@RequestBody NotificationDTO notificationDTO) inherited
发送通知到LIMS系统
Parameters
notificationDTO 通知信息
sendNotification() [2/2]
void com.gmp.qms.client.LimsClientFallback.sendNotification (NotificationDTO notificationDTO)
Definition at line 47 of file LimsClientFallback.java.
References com.gmp.qms.client.LimsClientFallback.recordFallbackRequest(), and com.gmp.qms.client.LimsClientFallback.saveToRetryQueue().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/client/LimsClientFallback.java