GMP系统: com.gmp.auth.test.AuthSystemTestExecutor Class Reference
com.gmp.auth.test.AuthSystemTestExecutor Class Reference
GMP系统认证测试执行器
Classes
class TestExecutorStatus
测试执行器状态类
class TestMethodInfo
测试方法信息类
Public Member Functions
void afterPropertiesSet ()
void run (String... args)
void executeTests ()
执行所有测试
TestExecutorStatus getStatus ()
获取测试执行器状态
Private Member Functions
void registerTestMethods ()
注册测试方法
void executeInitialization ()
执行初始化步骤
void executeTestMethods ()
执行测试方法
String generateTestReport ()
生成测试报告
Private Attributes
final OrganizationStructureInitializer organizationInitializer
final RolePermissionInitializer rolePermissionInitializer
final UserInitializer userInitializer
final UserRepository userRepository
final RoleRepository roleRepository
final PermissionRepository permissionRepository
final UserOrganizationRoleRepository userOrganizationRoleRepository
final AuthenticationManager authenticationManager
final AuthTestErrorHandler errorHandler
AuthSystemTestScript testScript
final List< TestMethodInfo<?> > testMethods = new ArrayList<>()
final AtomicBoolean isRunning = new AtomicBoolean(false)
LocalDateTime startTime
LocalDateTime endTime
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(AuthSystemTestExecutor.class)
Detailed Description
GMP系统认证测试执行器
整合测试脚本和错误处理器，提供完整的测试执行环境
Definition at line 36 of file AuthSystemTestExecutor.java.
Member Function Documentation
afterPropertiesSet()
void com.gmp.auth.test.AuthSystemTestExecutor.afterPropertiesSet ()
Definition at line 64 of file AuthSystemTestExecutor.java.
executeInitialization()
void com.gmp.auth.test.AuthSystemTestExecutor.executeInitialization () private
执行初始化步骤
Definition at line 162 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
executeTestMethods()
void com.gmp.auth.test.AuthSystemTestExecutor.executeTestMethods () private
执行测试方法
Definition at line 195 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthTestErrorHandler.handleTestMethod().
executeTests()
void com.gmp.auth.test.AuthSystemTestExecutor.executeTests ()
执行所有测试
Definition at line 127 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthTestErrorHandler.resetStatistics().
generateTestReport()
String com.gmp.auth.test.AuthSystemTestExecutor.generateTestReport () private
生成测试报告
Definition at line 209 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthTestErrorHandler.getAllTestStatuses(), and com.gmp.auth.test.AuthTestErrorHandler.getErrorStatistics().
getStatus()
TestExecutorStatus com.gmp.auth.test.AuthSystemTestExecutor.getStatus ()
获取测试执行器状态
Definition at line 303 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthTestErrorHandler.getAllTestStatuses().
registerTestMethods()
void com.gmp.auth.test.AuthSystemTestExecutor.registerTestMethods () private
注册测试方法
Definition at line 84 of file AuthSystemTestExecutor.java.
References com.gmp.auth.test.AuthSystemTestScript.testOrganizationInitialization(), com.gmp.auth.test.AuthSystemTestScript.testRolePermissionInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserInitialization(), com.gmp.auth.test.AuthSystemTestScript.testUserLogin(), com.gmp.auth.test.AuthSystemTestScript.testUserOrganizationRoleAssociation(), and com.gmp.auth.test.AuthSystemTestScript.testUserPermissionDifferences().
run()
void com.gmp.auth.test.AuthSystemTestExecutor.run (String... args)
Definition at line 119 of file AuthSystemTestExecutor.java.
Member Data Documentation
authenticationManager
final AuthenticationManager com.gmp.auth.test.AuthSystemTestExecutor.authenticationManager private
Definition at line 46 of file AuthSystemTestExecutor.java.
endTime
LocalDateTime com.gmp.auth.test.AuthSystemTestExecutor.endTime private
Definition at line 58 of file AuthSystemTestExecutor.java.
errorHandler
final AuthTestErrorHandler com.gmp.auth.test.AuthSystemTestExecutor.errorHandler private
Definition at line 47 of file AuthSystemTestExecutor.java.
isRunning
final AtomicBoolean com.gmp.auth.test.AuthSystemTestExecutor.isRunning = new AtomicBoolean(false) private
Definition at line 56 of file AuthSystemTestExecutor.java.
log
final Logger com.gmp.auth.test.AuthSystemTestExecutor.log = LoggerFactory.getLogger(AuthSystemTestExecutor.class) static private
Definition at line 61 of file AuthSystemTestExecutor.java.
organizationInitializer
final OrganizationStructureInitializer com.gmp.auth.test.AuthSystemTestExecutor.organizationInitializer private
Definition at line 39 of file AuthSystemTestExecutor.java.
permissionRepository
final PermissionRepository com.gmp.auth.test.AuthSystemTestExecutor.permissionRepository private
Definition at line 44 of file AuthSystemTestExecutor.java.
rolePermissionInitializer
final RolePermissionInitializer com.gmp.auth.test.AuthSystemTestExecutor.rolePermissionInitializer private
Definition at line 40 of file AuthSystemTestExecutor.java.
roleRepository
final RoleRepository com.gmp.auth.test.AuthSystemTestExecutor.roleRepository private
Definition at line 43 of file AuthSystemTestExecutor.java.
startTime
LocalDateTime com.gmp.auth.test.AuthSystemTestExecutor.startTime private
Definition at line 57 of file AuthSystemTestExecutor.java.
testMethods
final List<TestMethodInfo<?> > com.gmp.auth.test.AuthSystemTestExecutor.testMethods = new ArrayList<>() private
Definition at line 53 of file AuthSystemTestExecutor.java.
testScript
AuthSystemTestScript com.gmp.auth.test.AuthSystemTestExecutor.testScript private
Definition at line 50 of file AuthSystemTestExecutor.java.
userInitializer
final UserInitializer com.gmp.auth.test.AuthSystemTestExecutor.userInitializer private
Definition at line 41 of file AuthSystemTestExecutor.java.
userOrganizationRoleRepository
final UserOrganizationRoleRepository com.gmp.auth.test.AuthSystemTestExecutor.userOrganizationRoleRepository private
Definition at line 45 of file AuthSystemTestExecutor.java.
userRepository
final UserRepository com.gmp.auth.test.AuthSystemTestExecutor.userRepository private
Definition at line 42 of file AuthSystemTestExecutor.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/test/AuthSystemTestExecutor.java