GMP系统: com.gmp.edms.service.impl.DocumentServiceImpl Class Reference
com.gmp.edms.service.impl.DocumentServiceImpl Class Reference
文档服务实现
Public Member Functions
DocumentDTO createDocument (DocumentCreateDTO documentCreateDTO)
创建文档
DocumentDTO createDocumentWithFile (DocumentCreateDTO documentCreateDTO, MultipartFile file) throws Exception
创建带文件的文档
DocumentDTO uploadDocumentFile (Long documentId, MultipartFile file) throws Exception
为文档上传文件
byte[] downloadDocumentFile (Long documentId) throws Exception
下载文档文件
DocumentDTO updateDocument (Long id, DocumentUpdateDTO documentUpdateDTO)
更新文档
void deleteDocument (Long id)
删除文档
void batchDeleteDocuments (List< Long > ids)
批量删除文档
DocumentDTO getDocumentById (Long id)
根据ID获取文档
DocumentDTO getDocumentByDocCode (String docCode)
根据文档编号获取文档
PageResponseDTO< DocumentDTO > queryDocuments (PageRequestDTO pageRequest, Map< String, Object > filters)
分页查询文档
List< DocumentDTO > getDocumentsByCategory (Long categoryId)
根据分类ID查询文档
void updateDocumentStatus (Long id, String status)
更新文档状态
List< DocumentDTO > searchDocuments (String keyword, Integer pageNo, Integer pageSize)
搜索文档
PageResponseDTO< DocumentDTO > advancedSearch (PageRequestDTO pageRequest, String keyword, Long categoryId, String status, Long departmentId, String approvalStatus)
高级搜索文档
List< DocumentDTO > getUserAccessibleDocuments (String username)
获取用户权限的文档列表
DocumentDTO approveDocument (Long id, String approvalStatus, String comments)
文档审批
default List< DocumentDTO > searchDocuments (String keyword)
搜索文档（兼容单参数调用）
Protected Member Functions
String generateDocCode ()
生成文档编号
Private Member Functions
String calculateChecksum (MultipartFile file) throws IOException, NoSuchAlgorithmException
计算文件校验和
Object getFieldValue (Object obj, String fieldName)
Object getFieldValue (Object obj, String fieldName, Object defaultValue)
void setFieldValue (Object obj, String fieldName, Object value)
Field findField (Class<?> clazz, String fieldName)
Private Attributes
DocumentRepository documentRepository
ModelMapper modelMapper
DocumentCategoryService documentCategoryService
FileStorageService fileStorageService
DocumentSearchService documentSearchService
EventPublisher eventPublisher
Detailed Description
文档服务实现
Definition at line 45 of file DocumentServiceImpl.java.
Member Function Documentation
advancedSearch()
PageResponseDTO< DocumentDTO > com.gmp.edms.service.impl.DocumentServiceImpl.advancedSearch (PageRequestDTO pageRequest, String keyword, Long categoryId, String status, Long departmentId, String approvalStatus)
高级搜索文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 384 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
approveDocument()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.approveDocument (Long id, String approvalStatus, String comments)
文档审批
Implements com.gmp.edms.service.DocumentService.
Definition at line 424 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue().
batchDeleteDocuments()
void com.gmp.edms.service.impl.DocumentServiceImpl.batchDeleteDocuments (List< Long > ids)
批量删除文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 278 of file DocumentServiceImpl.java.
References com.gmp.edms.service.DocumentSearchService.deleteDocumentIndex(), com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.documentSearchService.
calculateChecksum()
String com.gmp.edms.service.impl.DocumentServiceImpl.calculateChecksum (MultipartFile file) throws IOException, NoSuchAlgorithmException private
计算文件校验和
Definition at line 171 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
createDocument()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.createDocument (DocumentCreateDTO documentCreateDTO)
创建文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 68 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.documentSearchService, com.gmp.edms.service.impl.DocumentServiceImpl.eventPublisher, com.gmp.edms.service.impl.DocumentServiceImpl.generateDocCode(), com.gmp.edms.service.DocumentSearchService.indexDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper, and com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.createDocumentWithFile(), and com.gmp.edms.service.impl.DocumentServiceImplTest.testCreateDocument().
createDocumentWithFile()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.createDocumentWithFile (DocumentCreateDTO documentCreateDTO, MultipartFile file) throws Exception
创建带文件的文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 105 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
deleteDocument()
void com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument (Long id)
删除文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 252 of file DocumentServiceImpl.java.
References com.gmp.edms.service.DocumentSearchService.deleteDocumentIndex(), com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.documentSearchService, com.gmp.edms.service.impl.DocumentServiceImpl.eventPublisher, and com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testDeleteDocument().
downloadDocumentFile()
byte[] com.gmp.edms.service.impl.DocumentServiceImpl.downloadDocumentFile (Long documentId) throws Exception
下载文档文件
Implements com.gmp.edms.service.DocumentService.
Definition at line 151 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.FileStorageService.downloadFile(), com.gmp.edms.service.impl.DocumentServiceImpl.fileStorageService, and com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue().
findField()
Field com.gmp.edms.service.impl.DocumentServiceImpl.findField (Class<?> clazz, String fieldName) private
Definition at line 515 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue().
generateDocCode()
String com.gmp.edms.service.impl.DocumentServiceImpl.generateDocCode () protected
生成文档编号
Definition at line 445 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), and com.gmp.edms.service.impl.DocumentServiceImplTest.testGenerateDocCode().
getDocumentByDocCode()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentByDocCode (String docCode)
根据文档编号获取文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 301 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testGetDocumentByDocCode().
getDocumentById()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentById (Long id)
根据ID获取文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 290 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testGetDocumentById().
getDocumentsByCategory()
List< DocumentDTO > com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentsByCategory (Long categoryId)
根据分类ID查询文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 347 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testFindDocumentsByCategory().
getFieldValue() [1/2]
Object com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue (Object obj, String fieldName) private
Definition at line 478 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.advancedSearch(), com.gmp.edms.service.impl.DocumentServiceImpl.createDocumentWithFile(), com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.downloadDocumentFile(), com.gmp.edms.service.impl.DocumentServiceImpl.generateDocCode(), com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentServiceImpl.queryDocuments(), and com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument().
getFieldValue() [2/2]
Object com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue (Object obj, String fieldName, Object defaultValue) private
Definition at line 482 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.findField().
getUserAccessibleDocuments()
List< DocumentDTO > com.gmp.edms.service.impl.DocumentServiceImpl.getUserAccessibleDocuments (String username)
获取用户权限的文档列表
Implements com.gmp.edms.service.DocumentService.
Definition at line 412 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
queryDocuments()
PageResponseDTO< DocumentDTO > com.gmp.edms.service.impl.DocumentServiceImpl.queryDocuments (PageRequestDTO pageRequest, Map< String, Object > filters)
分页查询文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 311 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
searchDocuments() [1/2]
default List< DocumentDTO > com.gmp.edms.service.DocumentService.searchDocuments (String keyword) inherited
搜索文档（兼容单参数调用）
Definition at line 86 of file DocumentService.java.
References com.gmp.edms.service.DocumentService.searchDocuments().
searchDocuments() [2/2]
List< DocumentDTO > com.gmp.edms.service.impl.DocumentServiceImpl.searchDocuments (String keyword, Integer pageNo, Integer pageSize)
搜索文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 373 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper.
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testSearchDocuments().
setFieldValue()
void com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue (Object obj, String fieldName, Object value) private
Definition at line 499 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.findField().
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.approveDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.updateDocumentStatus(), and com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
updateDocument()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument (Long id, DocumentUpdateDTO documentUpdateDTO)
更新文档
Implements com.gmp.edms.service.DocumentService.
Definition at line 196 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.documentSearchService, com.gmp.edms.service.impl.DocumentServiceImpl.eventPublisher, com.gmp.edms.service.impl.DocumentServiceImpl.getFieldValue(), com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper, com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue(), and com.gmp.edms.service.DocumentSearchService.updateDocumentIndex().
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testUpdateDocument().
updateDocumentStatus()
void com.gmp.edms.service.impl.DocumentServiceImpl.updateDocumentStatus (Long id, String status)
更新文档状态
Implements com.gmp.edms.service.DocumentService.
Definition at line 359 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, and com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue().
Referenced by com.gmp.edms.service.impl.DocumentServiceImplTest.testUpdateDocumentStatus().
uploadDocumentFile()
DocumentDTO com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile (Long documentId, MultipartFile file) throws Exception
为文档上传文件
Implements com.gmp.edms.service.DocumentService.
Definition at line 116 of file DocumentServiceImpl.java.
References com.gmp.edms.service.impl.DocumentServiceImpl.calculateChecksum(), com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository, com.gmp.edms.service.impl.DocumentServiceImpl.fileStorageService, com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper, com.gmp.edms.service.impl.DocumentServiceImpl.setFieldValue(), and com.gmp.edms.service.FileStorageService.uploadFile().
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.createDocumentWithFile().
Member Data Documentation
documentCategoryService
DocumentCategoryService com.gmp.edms.service.impl.DocumentServiceImpl.documentCategoryService private
Definition at line 54 of file DocumentServiceImpl.java.
documentRepository
DocumentRepository com.gmp.edms.service.impl.DocumentServiceImpl.documentRepository private
Definition at line 48 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.advancedSearch(), com.gmp.edms.service.impl.DocumentServiceImpl.approveDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.batchDeleteDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.downloadDocumentFile(), com.gmp.edms.service.impl.DocumentServiceImpl.generateDocCode(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentByDocCode(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentById(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentsByCategory(), com.gmp.edms.service.impl.DocumentServiceImpl.getUserAccessibleDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.queryDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.searchDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.updateDocumentStatus(), and com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
documentSearchService
DocumentSearchService com.gmp.edms.service.impl.DocumentServiceImpl.documentSearchService private
Definition at line 60 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.batchDeleteDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument(), and com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument().
eventPublisher
EventPublisher com.gmp.edms.service.impl.DocumentServiceImpl.eventPublisher private
Definition at line 63 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument(), and com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument().
fileStorageService
FileStorageService com.gmp.edms.service.impl.DocumentServiceImpl.fileStorageService private
Definition at line 57 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.downloadDocumentFile(), and com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
modelMapper
ModelMapper com.gmp.edms.service.impl.DocumentServiceImpl.modelMapper private
Definition at line 51 of file DocumentServiceImpl.java.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.advancedSearch(), com.gmp.edms.service.impl.DocumentServiceImpl.approveDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.createDocument(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentByDocCode(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentById(), com.gmp.edms.service.impl.DocumentServiceImpl.getDocumentsByCategory(), com.gmp.edms.service.impl.DocumentServiceImpl.getUserAccessibleDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.queryDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.searchDocuments(), com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument(), and com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile().
The documentation for this class was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/impl/DocumentServiceImpl.java