GMP系统: com.gmp.auth.service.RedisTokenBlacklistService Class Reference
com.gmp.auth.service.RedisTokenBlacklistService Class Reference
Redis实现的Token黑名单服务
Public Member Functions
RedisTokenBlacklistService (RedisTemplate< String, String > redisTemplate)
void blacklistToken (String token, long expirationTime)
将令牌加入黑名单
boolean isTokenBlacklisted (String token)
检查令牌是否在黑名单中
void removeTokenFromBlacklist (String token)
从黑名单中移除令牌
void cleanExpiredTokens ()
清理过期的黑名单令牌
Private Attributes
final RedisTemplate< String, String > redisTemplate
Detailed Description
Redis实现的Token黑名单服务
Definition at line 11 of file RedisTokenBlacklistService.java.
Constructor & Destructor Documentation
RedisTokenBlacklistService()
com.gmp.auth.service.RedisTokenBlacklistService.RedisTokenBlacklistService (RedisTemplate< String, String > redisTemplate)
Definition at line 14 of file RedisTokenBlacklistService.java.
References com.gmp.auth.service.RedisTokenBlacklistService.redisTemplate.
Member Function Documentation
blacklistToken()
void com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken (String token, long expiration)
将令牌加入黑名单
Parameters
token JWT令牌
expiration 令牌过期时间（毫秒）
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 19 of file RedisTokenBlacklistService.java.
References com.gmp.auth.service.RedisTokenBlacklistService.redisTemplate.
Referenced by com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistToken_AlreadyExpired(), com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistToken_Success(), com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistTokenWithDifferentExpirations(), and com.gmp.auth.service.TokenBlacklistServiceTest.testBlacklistTokenWithZeroExpiration().
cleanExpiredTokens()
void com.gmp.auth.service.TokenBlacklistService.cleanExpiredTokens () inherited
清理过期的黑名单令牌
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl.
isTokenBlacklisted()
boolean com.gmp.auth.service.RedisTokenBlacklistService.isTokenBlacklisted (String token)
检查令牌是否在黑名单中
Parameters
token JWT令牌
Returns
true表示令牌在黑名单中，false表示不在
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 29 of file RedisTokenBlacklistService.java.
References com.gmp.auth.service.RedisTokenBlacklistService.redisTemplate.
Referenced by com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_NullToken(), com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_TokenIsBlacklisted(), and com.gmp.auth.service.TokenBlacklistServiceTest.testIsTokenBlacklisted_TokenNotBlacklisted().
removeTokenFromBlacklist()
void com.gmp.auth.service.TokenBlacklistService.removeTokenFromBlacklist (String token) inherited
从黑名单中移除令牌
Parameters
token JWT令牌
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl.
Member Data Documentation
redisTemplate
final RedisTemplate<String, String> com.gmp.auth.service.RedisTokenBlacklistService.redisTemplate private
Definition at line 12 of file RedisTokenBlacklistService.java.
Referenced by com.gmp.auth.service.RedisTokenBlacklistService.blacklistToken(), com.gmp.auth.service.RedisTokenBlacklistService.isTokenBlacklisted(), and com.gmp.auth.service.RedisTokenBlacklistService.RedisTokenBlacklistService().
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/RedisTokenBlacklistService.java