GMP系统: com.gmp.mes.entity.ProductionBatch Class Reference
com.gmp.mes.entity.ProductionBatch Class Reference
生产批次实体
Classes
enum BatchStatus
批次状态枚举
Public Member Functions
ProductionOrder getOrder ()
void setOrder (ProductionOrder order)
List< BatchOperation > getOperations ()
void setOperations (List< BatchOperation > operations)
void addBatchOperation (BatchOperation operation)
void removeBatchOperation (BatchOperation operation)
boolean equals (Object o)
int hashCode ()
BatchStatus getStatus ()
void setStatus (BatchStatus status)
LocalDateTime getEndTime ()
void setEndTime (LocalDateTime endTime)
Private Attributes
Long id
String batchNumber
ProductionOrder productionOrder
String productId
String productName
Integer batchSize
String equipmentId
String equipmentName
Integer goodQuantity
Integer rejectQuantity
String operator
String remark
BatchStatus status = BatchStatus.PENDING
LocalDateTime startTime
LocalDateTime endTime
Set< BatchOperation > batchOperations = new HashSet<>()
LocalDateTime createdAt
LocalDateTime updatedAt
Detailed Description
生产批次实体
Author
gmp-system
Definition at line 24 of file ProductionBatch.java.
Member Function Documentation
addBatchOperation()
void com.gmp.mes.entity.ProductionBatch.addBatchOperation (BatchOperation operation)
Definition at line 91 of file ProductionBatch.java.
References com.gmp.mes.entity.BatchOperation.setBatch().
Referenced by com.gmp.mes.entity.ProductionBatchTest.testAddBatchOperation(), and com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation().
equals()
boolean com.gmp.mes.entity.ProductionBatch.equals (Object o)
Definition at line 102 of file ProductionBatch.java.
References com.gmp.mes.entity.ProductionBatch.equals(), and com.gmp.mes.entity.ProductionBatch.id.
Referenced by com.gmp.mes.entity.ProductionBatch.equals().
getEndTime()
LocalDateTime com.gmp.mes.entity.ProductionBatch.getEndTime ()
Definition at line 138 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testEndTimeGetterAndSetter().
getOperations()
List< BatchOperation > com.gmp.mes.entity.ProductionBatch.getOperations ()
Definition at line 72 of file ProductionBatch.java.
getOrder()
ProductionOrder com.gmp.mes.entity.ProductionBatch.getOrder ()
Definition at line 38 of file ProductionBatch.java.
getStatus()
BatchStatus com.gmp.mes.entity.ProductionBatch.getStatus ()
Definition at line 130 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testStatusGetterAndSetter().
hashCode()
int com.gmp.mes.entity.ProductionBatch.hashCode ()
Definition at line 113 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testEqualsAndHashCode().
removeBatchOperation()
void com.gmp.mes.entity.ProductionBatch.removeBatchOperation (BatchOperation operation)
Definition at line 96 of file ProductionBatch.java.
References com.gmp.mes.entity.BatchOperation.setBatch().
Referenced by com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation().
setEndTime()
void com.gmp.mes.entity.ProductionBatch.setEndTime (LocalDateTime endTime)
Definition at line 142 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testEndTimeGetterAndSetter().
setOperations()
void com.gmp.mes.entity.ProductionBatch.setOperations (List< BatchOperation > operations)
Definition at line 76 of file ProductionBatch.java.
setOrder()
void com.gmp.mes.entity.ProductionBatch.setOrder (ProductionOrder order)
Definition at line 42 of file ProductionBatch.java.
setStatus()
void com.gmp.mes.entity.ProductionBatch.setStatus (BatchStatus status)
Definition at line 134 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testStatusGetterAndSetter().
Member Data Documentation
batchNumber
String com.gmp.mes.entity.ProductionBatch.batchNumber private
Definition at line 31 of file ProductionBatch.java.
batchOperations
Set<BatchOperation> com.gmp.mes.entity.ProductionBatch.batchOperations = new HashSet<>() private
Definition at line 69 of file ProductionBatch.java.
batchSize
Integer com.gmp.mes.entity.ProductionBatch.batchSize private
Definition at line 50 of file ProductionBatch.java.
createdAt
LocalDateTime com.gmp.mes.entity.ProductionBatch.createdAt private
Definition at line 85 of file ProductionBatch.java.
endTime
LocalDateTime com.gmp.mes.entity.ProductionBatch.endTime private
Definition at line 66 of file ProductionBatch.java.
equipmentId
String com.gmp.mes.entity.ProductionBatch.equipmentId private
Definition at line 51 of file ProductionBatch.java.
equipmentName
String com.gmp.mes.entity.ProductionBatch.equipmentName private
Definition at line 52 of file ProductionBatch.java.
goodQuantity
Integer com.gmp.mes.entity.ProductionBatch.goodQuantity private
Definition at line 54 of file ProductionBatch.java.
id
Long com.gmp.mes.entity.ProductionBatch.id private
Definition at line 28 of file ProductionBatch.java.
Referenced by com.gmp.mes.entity.ProductionBatch.equals().
operator
String com.gmp.mes.entity.ProductionBatch.operator private
Definition at line 56 of file ProductionBatch.java.
productId
String com.gmp.mes.entity.ProductionBatch.productId private
Definition at line 47 of file ProductionBatch.java.
productionOrder
ProductionOrder com.gmp.mes.entity.ProductionBatch.productionOrder private
Definition at line 35 of file ProductionBatch.java.
productName
String com.gmp.mes.entity.ProductionBatch.productName private
Definition at line 49 of file ProductionBatch.java.
rejectQuantity
Integer com.gmp.mes.entity.ProductionBatch.rejectQuantity private
Definition at line 55 of file ProductionBatch.java.
remark
String com.gmp.mes.entity.ProductionBatch.remark private
Definition at line 57 of file ProductionBatch.java.
startTime
LocalDateTime com.gmp.mes.entity.ProductionBatch.startTime private
Definition at line 63 of file ProductionBatch.java.
status
BatchStatus com.gmp.mes.entity.ProductionBatch.status = BatchStatus.PENDING private
Definition at line 60 of file ProductionBatch.java.
updatedAt
LocalDateTime com.gmp.mes.entity.ProductionBatch.updatedAt private
Definition at line 88 of file ProductionBatch.java.
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/entity/ProductionBatch.java