GMP系统: com.gmp.qms.listener.McpMessageListener Class Reference
com.gmp.qms.listener.McpMessageListener Class Reference
MCP消息监听器，用于接收和处理来自其他系统的消息
Public Member Functions
void listenEdmsMessages (Map< String, Object > message)
监听来自EDMS系统的消息
void listenMesMessages (Map< String, Object > message)
监听来自MES系统的消息
void listenLimsMessages (Map< String, Object > message)
监听来自LIMS系统的消息
void listenErpMessages (Map< String, Object > message)
监听来自ERP系统的消息
void listenTrainingMessages (Map< String, Object > message)
监听来自培训系统的消息
void listenEquipmentMessages (Map< String, Object > message)
监听来自设备系统的消息
void listenDeadLetterMessages (Map< String, Object > message)
监听死信队列中的失败消息
void registerMessageHandler (String operation, Consumer< Map< String, Object > > handler)
注册消息处理器
void unregisterMessageHandler (String operation)
注销消息处理器
int getRegisteredHandlersCount ()
获取当前注册的消息处理器数量
boolean hasHandlerForOperation (String operation)
检查是否有针对特定操作的处理器
Private Member Functions
void processMessage (String sourceSystem, Map< String, Object > message)
处理接收到的消息
void handleDefaultMessage (String sourceSystem, Map< String, Object > message)
默认消息处理逻辑
Private Attributes
McpMonitoringService monitoringService
final Map< String, Consumer< Map< String, Object > > > messageHandlers = new ConcurrentHashMap<>()
Detailed Description
MCP消息监听器，用于接收和处理来自其他系统的消息
Author
GMP系统开发团队
Definition at line 20 of file McpMessageListener.java.
Member Function Documentation
getRegisteredHandlersCount()
int com.gmp.qms.listener.McpMessageListener.getRegisteredHandlersCount ()
获取当前注册的消息处理器数量
Definition at line 165 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.messageHandlers.
handleDefaultMessage()
void com.gmp.qms.listener.McpMessageListener.handleDefaultMessage (String sourceSystem, Map< String, Object > message) private
默认消息处理逻辑
Definition at line 152 of file McpMessageListener.java.
Referenced by com.gmp.qms.listener.McpMessageListener.processMessage().
hasHandlerForOperation()
boolean com.gmp.qms.listener.McpMessageListener.hasHandlerForOperation (String operation)
检查是否有针对特定操作的处理器
Definition at line 172 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.messageHandlers.
listenDeadLetterMessages()
void com.gmp.qms.listener.McpMessageListener.listenDeadLetterMessages (Map< String, Object > message)
监听死信队列中的失败消息
Definition at line 80 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.monitoringService.
listenEdmsMessages()
void com.gmp.qms.listener.McpMessageListener.listenEdmsMessages (Map< String, Object > message)
监听来自EDMS系统的消息
Definition at line 32 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
listenEquipmentMessages()
void com.gmp.qms.listener.McpMessageListener.listenEquipmentMessages (Map< String, Object > message)
监听来自设备系统的消息
Definition at line 72 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
listenErpMessages()
void com.gmp.qms.listener.McpMessageListener.listenErpMessages (Map< String, Object > message)
监听来自ERP系统的消息
Definition at line 56 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
listenLimsMessages()
void com.gmp.qms.listener.McpMessageListener.listenLimsMessages (Map< String, Object > message)
监听来自LIMS系统的消息
Definition at line 48 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
listenMesMessages()
void com.gmp.qms.listener.McpMessageListener.listenMesMessages (Map< String, Object > message)
监听来自MES系统的消息
Definition at line 40 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
listenTrainingMessages()
void com.gmp.qms.listener.McpMessageListener.listenTrainingMessages (Map< String, Object > message)
监听来自培训系统的消息
Definition at line 64 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.processMessage().
processMessage()
void com.gmp.qms.listener.McpMessageListener.processMessage (String sourceSystem, Map< String, Object > message) private
处理接收到的消息
Definition at line 116 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.handleDefaultMessage(), com.gmp.qms.listener.McpMessageListener.messageHandlers, and com.gmp.qms.listener.McpMessageListener.monitoringService.
Referenced by com.gmp.qms.listener.McpMessageListener.listenEdmsMessages(), com.gmp.qms.listener.McpMessageListener.listenEquipmentMessages(), com.gmp.qms.listener.McpMessageListener.listenErpMessages(), com.gmp.qms.listener.McpMessageListener.listenLimsMessages(), com.gmp.qms.listener.McpMessageListener.listenMesMessages(), and com.gmp.qms.listener.McpMessageListener.listenTrainingMessages().
registerMessageHandler()
void com.gmp.qms.listener.McpMessageListener.registerMessageHandler (String operation, Consumer< Map< String, Object > > handler)
注册消息处理器
Parameters
operation 操作类型
handler 消息处理函数
Definition at line 101 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.messageHandlers.
unregisterMessageHandler()
void com.gmp.qms.listener.McpMessageListener.unregisterMessageHandler (String operation)
注销消息处理器
Parameters
operation 操作类型
Definition at line 109 of file McpMessageListener.java.
References com.gmp.qms.listener.McpMessageListener.messageHandlers.
Member Data Documentation
messageHandlers
final Map<String, Consumer<Map<String, Object> > > com.gmp.qms.listener.McpMessageListener.messageHandlers = new ConcurrentHashMap<>() private
Definition at line 26 of file McpMessageListener.java.
Referenced by com.gmp.qms.listener.McpMessageListener.getRegisteredHandlersCount(), com.gmp.qms.listener.McpMessageListener.hasHandlerForOperation(), com.gmp.qms.listener.McpMessageListener.processMessage(), com.gmp.qms.listener.McpMessageListener.registerMessageHandler(), and com.gmp.qms.listener.McpMessageListener.unregisterMessageHandler().
monitoringService
McpMonitoringService com.gmp.qms.listener.McpMessageListener.monitoringService private
Definition at line 23 of file McpMessageListener.java.
Referenced by com.gmp.qms.listener.McpMessageListener.listenDeadLetterMessages(), and com.gmp.qms.listener.McpMessageListener.processMessage().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/listener/McpMessageListener.java