GMP系统: com.gmp.mes.entity.BatchOperation Class Reference
com.gmp.mes.entity.BatchOperation Class Reference
批操作实体 - 记录批次执行过程中的具体操作
Classes
enum OperationStatus
操作状态枚举
Public Member Functions
void setOperationNumber (String operationNumber)
String getOperationNumber ()
ProductionBatch getProductionBatch ()
String getRemark ()
void setRemark (String remark)
void setBatch (ProductionBatch batch)
String getLastOperator ()
Map< String, Object > getParameters ()
void setParametersMap (Map< String, Object > parameters)
Private Attributes
Long id
ProductionBatch batch
String operationName
String operationType
OperationStatus status = OperationStatus.PENDING
LocalDateTime startTime
LocalDateTime endTime
String operator
String equipmentId
String parameters
String resultValues
String notes
String remark
LocalDateTime createdAt
LocalDateTime updatedAt
Detailed Description
批操作实体 - 记录批次执行过程中的具体操作
Author
gmp-system
Definition at line 22 of file BatchOperation.java.
Member Function Documentation
getLastOperator()
String com.gmp.mes.entity.BatchOperation.getLastOperator ()
Definition at line 110 of file BatchOperation.java.
getOperationNumber()
String com.gmp.mes.entity.BatchOperation.getOperationNumber ()
Definition at line 83 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.BatchOperationTest.testOperationNumberGetterAndSetter().
getParameters()
Map< String, Object > com.gmp.mes.entity.BatchOperation.getParameters ()
Definition at line 115 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.BatchOperationTest.testJsonbSerialization(), and com.gmp.mes.entity.BatchOperationTest.testParametersGetterAndSetter().
getProductionBatch()
ProductionBatch com.gmp.mes.entity.BatchOperation.getProductionBatch ()
Definition at line 89 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testAddBatchOperation(), com.gmp.mes.entity.BatchOperationTest.testProductionBatchGetterAndSetter(), and com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation().
getRemark()
String com.gmp.mes.entity.BatchOperation.getRemark ()
Definition at line 94 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.BatchOperationTest.testRemarkGetterAndSetter().
setBatch()
void com.gmp.mes.entity.BatchOperation.setBatch (ProductionBatch batch)
Definition at line 104 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.ProductionBatch.addBatchOperation(), and com.gmp.mes.entity.ProductionBatch.removeBatchOperation().
setOperationNumber()
void com.gmp.mes.entity.BatchOperation.setOperationNumber (String operationNumber)
Definition at line 77 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.testAddBatchOperation(), com.gmp.mes.entity.ProductionBatchTest.testBatchOperationsGetterAndSetter(), com.gmp.mes.entity.BatchOperationTest.testEqualsAndHashCode(), com.gmp.mes.entity.BatchOperationTest.testOperationNumberGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation(), and com.gmp.mes.entity.BatchOperationTest.testToString().
setParametersMap()
void com.gmp.mes.entity.BatchOperation.setParametersMap (Map< String, Object > parameters)
Definition at line 121 of file BatchOperation.java.
setRemark()
void com.gmp.mes.entity.BatchOperation.setRemark (String remark)
Definition at line 99 of file BatchOperation.java.
Referenced by com.gmp.mes.entity.BatchOperationTest.testRemarkGetterAndSetter().
Member Data Documentation
batch
ProductionBatch com.gmp.mes.entity.BatchOperation.batch private
Definition at line 30 of file BatchOperation.java.
createdAt
LocalDateTime com.gmp.mes.entity.BatchOperation.createdAt private
Definition at line 59 of file BatchOperation.java.
endTime
LocalDateTime com.gmp.mes.entity.BatchOperation.endTime private
Definition at line 42 of file BatchOperation.java.
equipmentId
String com.gmp.mes.entity.BatchOperation.equipmentId private
Definition at line 44 of file BatchOperation.java.
id
Long com.gmp.mes.entity.BatchOperation.id private
Definition at line 26 of file BatchOperation.java.
notes
String com.gmp.mes.entity.BatchOperation.notes private
Definition at line 54 of file BatchOperation.java.
operationName
String com.gmp.mes.entity.BatchOperation.operationName private
Definition at line 33 of file BatchOperation.java.
operationType
String com.gmp.mes.entity.BatchOperation.operationType private
Definition at line 36 of file BatchOperation.java.
operator
String com.gmp.mes.entity.BatchOperation.operator private
Definition at line 43 of file BatchOperation.java.
parameters
String com.gmp.mes.entity.BatchOperation.parameters private
Definition at line 48 of file BatchOperation.java.
remark
String com.gmp.mes.entity.BatchOperation.remark private
Definition at line 55 of file BatchOperation.java.
resultValues
String com.gmp.mes.entity.BatchOperation.resultValues private
Definition at line 52 of file BatchOperation.java.
startTime
LocalDateTime com.gmp.mes.entity.BatchOperation.startTime private
Definition at line 41 of file BatchOperation.java.
status
OperationStatus com.gmp.mes.entity.BatchOperation.status = OperationStatus.PENDING private
Definition at line 39 of file BatchOperation.java.
updatedAt
LocalDateTime com.gmp.mes.entity.BatchOperation.updatedAt private
Definition at line 62 of file BatchOperation.java.
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/entity/BatchOperation.java