GMP系统: com.gmp.qms.security.McpPermissionEvaluator Class Reference
com.gmp.qms.security.McpPermissionEvaluator Class Reference
MCP权限评估器，用于评估MCP请求对特定工具或资源的访问权限
Public Member Functions
boolean hasPermission (Authentication authentication, Object targetDomainObject, Object permission)
boolean hasPermission (Authentication authentication, Serializable targetId, String targetType, Object permission)
Private Member Functions
boolean hasToolPermission (McpPrincipal principal, String toolName, String permission)
检查主体是否有调用特定工具的权限
boolean hasResourcePermission (McpPrincipal principal, String resourceName, String permission)
检查主体是否有访问特定资源的权限
Private Attributes
McpToolRegistry toolRegistry
McpResourceRegistry resourceRegistry
Detailed Description
MCP权限评估器，用于评估MCP请求对特定工具或资源的访问权限
Author
GMP系统开发团队
Definition at line 17 of file McpPermissionEvaluator.java.
Member Function Documentation
hasPermission() [1/2]
boolean com.gmp.qms.security.McpPermissionEvaluator.hasPermission (Authentication authentication, Object targetDomainObject, Object permission)
Definition at line 26 of file McpPermissionEvaluator.java.
References com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission().
hasPermission() [2/2]
boolean com.gmp.qms.security.McpPermissionEvaluator.hasPermission (Authentication authentication, Serializable targetId, String targetType, Object permission)
Definition at line 53 of file McpPermissionEvaluator.java.
References com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission().
hasResourcePermission()
boolean com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission (McpPrincipal principal, String resourceName, String permission) private
检查主体是否有访问特定资源的权限
Definition at line 128 of file McpPermissionEvaluator.java.
References com.gmp.qms.security.McpPrincipal.hasPermission(), com.gmp.qms.security.McpPrincipal.hasRole(), and com.gmp.qms.security.McpPermissionEvaluator.resourceRegistry.
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasPermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasPermission().
hasToolPermission()
boolean com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission (McpPrincipal principal, String toolName, String permission) private
检查主体是否有调用特定工具的权限
Definition at line 76 of file McpPermissionEvaluator.java.
References com.gmp.qms.security.McpPrincipal.hasPermission(), com.gmp.qms.security.McpPrincipal.hasRole(), and com.gmp.qms.security.McpPermissionEvaluator.toolRegistry.
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasPermission(), and com.gmp.qms.security.McpPermissionEvaluator.hasPermission().
Member Data Documentation
resourceRegistry
McpResourceRegistry com.gmp.qms.security.McpPermissionEvaluator.resourceRegistry private
Definition at line 23 of file McpPermissionEvaluator.java.
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasResourcePermission().
toolRegistry
McpToolRegistry com.gmp.qms.security.McpPermissionEvaluator.toolRegistry private
Definition at line 20 of file McpPermissionEvaluator.java.
Referenced by com.gmp.qms.security.McpPermissionEvaluator.hasToolPermission().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/security/McpPermissionEvaluator.java