GMP系统: com.gmp.auth.service.impl.TokenBlacklistServiceImpl Class Reference
com.gmp.auth.service.impl.TokenBlacklistServiceImpl Class Reference
令牌黑名单服务实现 使用Redis存储已撤销的JWT令牌
Public Member Functions
boolean isTokenBlacklisted (String token)
检查令牌是否在黑名单中
void blacklistToken (String token, long expiration)
将令牌加入黑名单
void removeTokenFromBlacklist (String token)
从黑名单中移除令牌
void cleanExpiredTokens ()
清理过期的黑名单令牌
Private Member Functions
String generateTokenKey (String token)
生成令牌的键 为了安全考虑，不对原始令牌进行哈希
Private Attributes
RedisTemplate< String, Object > redisTemplate
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(TokenBlacklistServiceImpl.class)
static final String BLACKLIST_PREFIX = "token:blacklist:"
Detailed Description
令牌黑名单服务实现 使用Redis存储已撤销的JWT令牌
Definition at line 20 of file TokenBlacklistServiceImpl.java.
Member Function Documentation
blacklistToken()
void com.gmp.auth.service.impl.TokenBlacklistServiceImpl.blacklistToken (String token, long expiration)
将令牌加入黑名单
Parameters
token JWT令牌
expiration 令牌过期时间（毫秒）
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 44 of file TokenBlacklistServiceImpl.java.
References com.gmp.auth.service.impl.TokenBlacklistServiceImpl.BLACKLIST_PREFIX, com.gmp.auth.service.impl.TokenBlacklistServiceImpl.generateTokenKey(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.logger, and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.redisTemplate.
cleanExpiredTokens()
void com.gmp.auth.service.impl.TokenBlacklistServiceImpl.cleanExpiredTokens ()
清理过期的黑名单令牌
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 83 of file TokenBlacklistServiceImpl.java.
References com.gmp.auth.service.impl.TokenBlacklistServiceImpl.logger.
generateTokenKey()
String com.gmp.auth.service.impl.TokenBlacklistServiceImpl.generateTokenKey (String token) private
生成令牌的键 为了安全考虑，不对原始令牌进行哈希
Definition at line 93 of file TokenBlacklistServiceImpl.java.
Referenced by com.gmp.auth.service.impl.TokenBlacklistServiceImpl.blacklistToken(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.isTokenBlacklisted(), and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.removeTokenFromBlacklist().
isTokenBlacklisted()
boolean com.gmp.auth.service.impl.TokenBlacklistServiceImpl.isTokenBlacklisted (String token)
检查令牌是否在黑名单中
Parameters
token JWT令牌
Returns
true表示令牌在黑名单中，false表示不在
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 31 of file TokenBlacklistServiceImpl.java.
References com.gmp.auth.service.impl.TokenBlacklistServiceImpl.BLACKLIST_PREFIX, com.gmp.auth.service.impl.TokenBlacklistServiceImpl.generateTokenKey(), and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.redisTemplate.
removeTokenFromBlacklist()
void com.gmp.auth.service.impl.TokenBlacklistServiceImpl.removeTokenFromBlacklist (String token)
从黑名单中移除令牌
Parameters
token JWT令牌
Implements com.gmp.auth.service.TokenBlacklistService.
Definition at line 68 of file TokenBlacklistServiceImpl.java.
References com.gmp.auth.service.impl.TokenBlacklistServiceImpl.BLACKLIST_PREFIX, com.gmp.auth.service.impl.TokenBlacklistServiceImpl.generateTokenKey(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.logger, and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.redisTemplate.
Member Data Documentation
BLACKLIST_PREFIX
final String com.gmp.auth.service.impl.TokenBlacklistServiceImpl.BLACKLIST_PREFIX = "token:blacklist:" static private
Definition at line 24 of file TokenBlacklistServiceImpl.java.
Referenced by com.gmp.auth.service.impl.TokenBlacklistServiceImpl.blacklistToken(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.isTokenBlacklisted(), and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.removeTokenFromBlacklist().
logger
final Logger com.gmp.auth.service.impl.TokenBlacklistServiceImpl.logger = LoggerFactory.getLogger(TokenBlacklistServiceImpl.class) static private
Definition at line 22 of file TokenBlacklistServiceImpl.java.
Referenced by com.gmp.auth.service.impl.TokenBlacklistServiceImpl.blacklistToken(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.cleanExpiredTokens(), and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.removeTokenFromBlacklist().
redisTemplate
RedisTemplate<String, Object> com.gmp.auth.service.impl.TokenBlacklistServiceImpl.redisTemplate private
Definition at line 27 of file TokenBlacklistServiceImpl.java.
Referenced by com.gmp.auth.service.impl.TokenBlacklistServiceImpl.blacklistToken(), com.gmp.auth.service.impl.TokenBlacklistServiceImpl.isTokenBlacklisted(), and com.gmp.auth.service.impl.TokenBlacklistServiceImpl.removeTokenFromBlacklist().
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/impl/TokenBlacklistServiceImpl.java