GMP系统: com.gmp.mes.entity.ProductionBatchTest Class Reference
com.gmp.mes.entity.ProductionBatchTest Class Reference
生产批次实体类的单元测试
Package Functions
void setUp ()
void testIdGetterAndSetter ()
void testBatchNumberGetterAndSetter ()
void testProductIdGetterAndSetter ()
void testProductNameGetterAndSetter ()
void testEquipmentIdGetterAndSetter ()
void testEquipmentNameGetterAndSetter ()
void testBatchSizeGetterAndSetter ()
void testGoodQuantityGetterAndSetter ()
void testRejectQuantityGetterAndSetter ()
void testStatusGetterAndSetter ()
void testStartTimeGetterAndSetter ()
void testEndTimeGetterAndSetter ()
void testOperatorGetterAndSetter ()
void testRemarkGetterAndSetter ()
void testProductionOrderGetterAndSetter ()
void testBatchOperationsGetterAndSetter ()
void testAddBatchOperation ()
void testRemoveBatchOperation ()
void testEqualsAndHashCode ()
void testToString ()
Private Attributes
ProductionBatch productionBatch
Detailed Description
生产批次实体类的单元测试
Author
gmp-system
Definition at line 17 of file ProductionBatchTest.java.
Member Function Documentation
setUp()
void com.gmp.mes.entity.ProductionBatchTest.setUp () package
Definition at line 22 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testAddBatchOperation()
void com.gmp.mes.entity.ProductionBatchTest.testAddBatchOperation () package
Definition at line 149 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatch.addBatchOperation(), com.gmp.mes.entity.BatchOperation.getProductionBatch(), com.gmp.mes.entity.ProductionBatchTest.productionBatch, and com.gmp.mes.entity.BatchOperation.setOperationNumber().
testBatchNumberGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testBatchNumberGetterAndSetter () package
Definition at line 34 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testBatchOperationsGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testBatchOperationsGetterAndSetter () package
Definition at line 136 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch, and com.gmp.mes.entity.BatchOperation.setOperationNumber().
testBatchSizeGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testBatchSizeGetterAndSetter () package
Definition at line 69 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testEndTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testEndTimeGetterAndSetter () package
Definition at line 104 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatch.getEndTime(), com.gmp.mes.entity.ProductionBatchTest.productionBatch, and com.gmp.mes.entity.ProductionBatch.setEndTime().
testEqualsAndHashCode()
void com.gmp.mes.entity.ProductionBatchTest.testEqualsAndHashCode () package
Definition at line 174 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatch.hashCode(), and com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testEquipmentIdGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testEquipmentIdGetterAndSetter () package
Definition at line 55 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testEquipmentNameGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testEquipmentNameGetterAndSetter () package
Definition at line 62 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testGoodQuantityGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testGoodQuantityGetterAndSetter () package
Definition at line 76 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testIdGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testIdGetterAndSetter () package
Definition at line 27 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testOperatorGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testOperatorGetterAndSetter () package
Definition at line 111 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testProductIdGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testProductIdGetterAndSetter () package
Definition at line 41 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testProductionOrderGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testProductionOrderGetterAndSetter () package
Definition at line 125 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionOrder.getProductionBatches(), com.gmp.mes.entity.ProductionBatchTest.productionBatch, com.gmp.mes.entity.ProductionOrder.setId(), and com.gmp.mes.entity.ProductionOrder.setOrderNumber().
testProductNameGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testProductNameGetterAndSetter () package
Definition at line 48 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testRejectQuantityGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testRejectQuantityGetterAndSetter () package
Definition at line 83 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testRemarkGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testRemarkGetterAndSetter () package
Definition at line 118 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testRemoveBatchOperation()
void com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation () package
Definition at line 160 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatch.addBatchOperation(), com.gmp.mes.entity.BatchOperation.getProductionBatch(), com.gmp.mes.entity.ProductionBatchTest.productionBatch, com.gmp.mes.entity.ProductionBatch.removeBatchOperation(), and com.gmp.mes.entity.BatchOperation.setOperationNumber().
testStartTimeGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testStartTimeGetterAndSetter () package
Definition at line 97 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
testStatusGetterAndSetter()
void com.gmp.mes.entity.ProductionBatchTest.testStatusGetterAndSetter () package
Definition at line 90 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatch.getStatus(), com.gmp.mes.entity.ProductionBatch.BatchStatus.IN_PROGRESS, com.gmp.mes.entity.ProductionBatchTest.productionBatch, and com.gmp.mes.entity.ProductionBatch.setStatus().
testToString()
void com.gmp.mes.entity.ProductionBatchTest.testToString () package
Definition at line 191 of file ProductionBatchTest.java.
References com.gmp.mes.entity.ProductionBatchTest.productionBatch.
Member Data Documentation
productionBatch
ProductionBatch com.gmp.mes.entity.ProductionBatchTest.productionBatch private
Definition at line 19 of file ProductionBatchTest.java.
Referenced by com.gmp.mes.entity.ProductionBatchTest.setUp(), com.gmp.mes.entity.ProductionBatchTest.testAddBatchOperation(), com.gmp.mes.entity.ProductionBatchTest.testBatchNumberGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testBatchOperationsGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testBatchSizeGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testEndTimeGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testEqualsAndHashCode(), com.gmp.mes.entity.ProductionBatchTest.testEquipmentIdGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testEquipmentNameGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testGoodQuantityGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testIdGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testOperatorGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductIdGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductionOrderGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testProductNameGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testRejectQuantityGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testRemarkGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testRemoveBatchOperation(), com.gmp.mes.entity.ProductionBatchTest.testStartTimeGetterAndSetter(), com.gmp.mes.entity.ProductionBatchTest.testStatusGetterAndSetter(), and com.gmp.mes.entity.ProductionBatchTest.testToString().
The documentation for this class was generated from the following file:
mes-service/src/test/java/com/gmp/mes/entity/ProductionBatchTest.java