GMP系统: com.gmp.hr.service.impl.PositionServiceImpl Class Reference
com.gmp.hr.service.impl.PositionServiceImpl Class Reference
职位服务实现类
Public Member Functions
PositionServiceImpl (PositionRepository positionRepository, DepartmentRepository departmentRepository, EmployeeRepository employeeRepository)
PositionDTO createPosition (PositionDTO positionDTO)
创建职位
PositionDTO getPositionById (Long id)
根据ID获取职位
PositionDTO getPositionByCode (String positionCode)
根据职位代码获取职位
PositionDTO updatePosition (Long id, PositionDTO positionDTO)
更新职位
void deletePosition (Long id)
删除职位
List< PositionDTO > getAllPositions ()
获取所有职位
List< PositionDTO > getPositionsByDepartment (Long departmentId)
根据部门ID获取职位
List< PositionDTO > getPositionsByLevel (Integer level)
根据职位等级获取职位
List< PositionDTO > getPositionsByStatus (String status)
根据职位状态获取职位
Private Member Functions
PositionDTO convertToDTO (Position position)
将职位实体转换为DTO，并设置员工数量
Private Attributes
final PositionRepository positionRepository
final DepartmentRepository departmentRepository
final EmployeeRepository employeeRepository
Detailed Description
职位服务实现类
Author
GMP Team
Version
1.0.0
Definition at line 27 of file PositionServiceImpl.java.
Constructor & Destructor Documentation
PositionServiceImpl()
com.gmp.hr.service.impl.PositionServiceImpl.PositionServiceImpl (PositionRepository positionRepository, DepartmentRepository departmentRepository, EmployeeRepository employeeRepository)
Definition at line 34 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.departmentRepository, com.gmp.hr.service.impl.PositionServiceImpl.employeeRepository, and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Member Function Documentation
convertToDTO()
PositionDTO com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO (Position position) private
将职位实体转换为DTO，并设置员工数量
Parameters
position 职位实体
Returns
职位DTO
Definition at line 235 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.employeeRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImpl.createPosition(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionByCode(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionById(), and com.gmp.hr.service.impl.PositionServiceImpl.updatePosition().
createPosition()
PositionDTO com.gmp.hr.service.impl.PositionServiceImpl.createPosition (PositionDTO positionDTO)
创建职位
Parameters
positionDTO 职位DTO
Returns
创建的职位DTO
Implements com.gmp.hr.service.PositionService.
Definition at line 44 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO(), com.gmp.hr.service.impl.PositionServiceImpl.departmentRepository, and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testCreatePosition_CodeExists(), com.gmp.hr.service.impl.PositionServiceImplTest.testCreatePosition_DepartmentNotExists(), and com.gmp.hr.service.impl.PositionServiceImplTest.testCreatePosition_Success().
deletePosition()
void com.gmp.hr.service.impl.PositionServiceImpl.deletePosition (Long id)
删除职位
Parameters
id 职位ID
Implements com.gmp.hr.service.PositionService.
Definition at line 169 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.employeeRepository, and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testDeletePosition_HasEmployees(), and com.gmp.hr.service.impl.PositionServiceImplTest.testDeletePosition_Success().
getAllPositions()
List< PositionDTO > com.gmp.hr.service.impl.PositionServiceImpl.getAllPositions ()
获取所有职位
Returns
职位DTO列表
Implements com.gmp.hr.service.PositionService.
Definition at line 190 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testGetAllPositions_Success().
getPositionByCode()
PositionDTO com.gmp.hr.service.impl.PositionServiceImpl.getPositionByCode (String positionCode)
根据职位代码获取职位
Parameters
positionCode 职位代码
Returns
职位DTO
Implements com.gmp.hr.service.PositionService.
Definition at line 106 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testGetPositionByCode_Success().
getPositionById()
PositionDTO com.gmp.hr.service.impl.PositionServiceImpl.getPositionById (Long id)
根据ID获取职位
Parameters
id 职位ID
Returns
职位DTO
Implements com.gmp.hr.service.PositionService.
Definition at line 92 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO(), and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testGetPositionById_NotFound(), and com.gmp.hr.service.impl.PositionServiceImplTest.testGetPositionById_Success().
getPositionsByDepartment()
List< PositionDTO > com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByDepartment (Long departmentId)
根据部门ID获取职位
Parameters
departmentId 部门ID
Returns
职位DTO列表
Implements com.gmp.hr.service.PositionService.
Definition at line 200 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testGetPositionsByDepartment_Success().
getPositionsByLevel()
List< PositionDTO > com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByLevel (Integer level)
根据职位等级获取职位
Parameters
level 职位等级
Returns
职位DTO列表
Implements com.gmp.hr.service.PositionService.
Definition at line 209 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
getPositionsByStatus()
List< PositionDTO > com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByStatus (String status)
根据职位状态获取职位
Parameters
status 职位状态
Returns
职位DTO列表
Implements com.gmp.hr.service.PositionService.
Definition at line 220 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
updatePosition()
PositionDTO com.gmp.hr.service.impl.PositionServiceImpl.updatePosition (Long id, PositionDTO positionDTO)
更新职位
Parameters
id 职位ID
positionDTO 职位DTO
Returns
更新后的职位DTO
Implements com.gmp.hr.service.PositionService.
Definition at line 115 of file PositionServiceImpl.java.
References com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO(), com.gmp.hr.service.impl.PositionServiceImpl.departmentRepository, and com.gmp.hr.service.impl.PositionServiceImpl.positionRepository.
Referenced by com.gmp.hr.service.impl.PositionServiceImplTest.testUpdatePosition_Success().
Member Data Documentation
departmentRepository
final DepartmentRepository com.gmp.hr.service.impl.PositionServiceImpl.departmentRepository private
Definition at line 30 of file PositionServiceImpl.java.
Referenced by com.gmp.hr.service.impl.PositionServiceImpl.createPosition(), com.gmp.hr.service.impl.PositionServiceImpl.PositionServiceImpl(), and com.gmp.hr.service.impl.PositionServiceImpl.updatePosition().
employeeRepository
final EmployeeRepository com.gmp.hr.service.impl.PositionServiceImpl.employeeRepository private
Definition at line 31 of file PositionServiceImpl.java.
Referenced by com.gmp.hr.service.impl.PositionServiceImpl.convertToDTO(), com.gmp.hr.service.impl.PositionServiceImpl.deletePosition(), and com.gmp.hr.service.impl.PositionServiceImpl.PositionServiceImpl().
positionRepository
final PositionRepository com.gmp.hr.service.impl.PositionServiceImpl.positionRepository private
Definition at line 29 of file PositionServiceImpl.java.
Referenced by com.gmp.hr.service.impl.PositionServiceImpl.createPosition(), com.gmp.hr.service.impl.PositionServiceImpl.deletePosition(), com.gmp.hr.service.impl.PositionServiceImpl.getAllPositions(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionByCode(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionById(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByDepartment(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByLevel(), com.gmp.hr.service.impl.PositionServiceImpl.getPositionsByStatus(), com.gmp.hr.service.impl.PositionServiceImpl.PositionServiceImpl(), and com.gmp.hr.service.impl.PositionServiceImpl.updatePosition().
The documentation for this class was generated from the following file:
hr-service/src/main/java/com/gmp/hr/service/impl/PositionServiceImpl.java