GMP系统: com.gmp.edms.service.FileServiceCoreLogicTest Class Reference
com.gmp.edms.service.FileServiceCoreLogicTest Class Reference
文件服务核心逻辑测试 测试文件服务的业务逻辑，不依赖具体的存储实现
Package Functions
void setUp ()
void testFileMetadataValidation ()
void testFileContentIntegrity () throws IOException
void testFileNameExtraction ()
void testFileSizeFormatting ()
void testFileTypeDetection ()
void testFilePathGeneration ()
Private Member Functions
String extractFileNameFromPath (String filePath)
String formatFileSize (long size)
String detectFileType (String fileName)
String generateFilePath (String fileName, String module)
Private Attributes
MultipartFile mockFile
Detailed Description
文件服务核心逻辑测试 测试文件服务的业务逻辑，不依赖具体的存储实现
Definition at line 20 of file FileServiceCoreLogicTest.java.
Member Function Documentation
detectFileType()
String com.gmp.edms.service.FileServiceCoreLogicTest.detectFileType (String fileName) private
Definition at line 142 of file FileServiceCoreLogicTest.java.
Referenced by com.gmp.edms.service.FileServiceCoreLogicTest.testFileTypeDetection().
extractFileNameFromPath()
String com.gmp.edms.service.FileServiceCoreLogicTest.extractFileNameFromPath (String filePath) private
Definition at line 122 of file FileServiceCoreLogicTest.java.
Referenced by com.gmp.edms.service.FileServiceCoreLogicTest.testFileNameExtraction().
formatFileSize()
String com.gmp.edms.service.FileServiceCoreLogicTest.formatFileSize (long size) private
Definition at line 135 of file FileServiceCoreLogicTest.java.
Referenced by com.gmp.edms.service.FileServiceCoreLogicTest.testFileSizeFormatting().
generateFilePath()
String com.gmp.edms.service.FileServiceCoreLogicTest.generateFilePath (String fileName, String module) private
Definition at line 149 of file FileServiceCoreLogicTest.java.
Referenced by com.gmp.edms.service.FileServiceCoreLogicTest.testFilePathGeneration().
setUp()
void com.gmp.edms.service.FileServiceCoreLogicTest.setUp () package
Definition at line 26 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.mockFile.
testFileContentIntegrity()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFileContentIntegrity () throws IOException package
Definition at line 61 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.mockFile.
testFileMetadataValidation()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFileMetadataValidation () package
Definition at line 40 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.mockFile.
testFileNameExtraction()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFileNameExtraction () package
Definition at line 75 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.extractFileNameFromPath().
testFilePathGeneration()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFilePathGeneration () package
Definition at line 106 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.generateFilePath().
testFileSizeFormatting()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFileSizeFormatting () package
Definition at line 87 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.formatFileSize().
testFileTypeDetection()
void com.gmp.edms.service.FileServiceCoreLogicTest.testFileTypeDetection () package
Definition at line 96 of file FileServiceCoreLogicTest.java.
References com.gmp.edms.service.FileServiceCoreLogicTest.detectFileType().
Member Data Documentation
mockFile
MultipartFile com.gmp.edms.service.FileServiceCoreLogicTest.mockFile private
Definition at line 23 of file FileServiceCoreLogicTest.java.
Referenced by com.gmp.edms.service.FileServiceCoreLogicTest.setUp(), com.gmp.edms.service.FileServiceCoreLogicTest.testFileContentIntegrity(), and com.gmp.edms.service.FileServiceCoreLogicTest.testFileMetadataValidation().
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/FileServiceCoreLogicTest.java