GMP系统: com.gmp.training.service.impl.TrainingRecordServiceImpl Class Reference
com.gmp.training.service.impl.TrainingRecordServiceImpl Class Reference
培训记录服务实现类
Public Member Functions
TrainingRecordServiceImpl (TrainingRecordRepository repository)
List< TrainingRecord > findByUser (User user)
根据用户查找培训记录
List< TrainingRecord > findByTrainingSession (TrainingSession trainingSession)
根据培训场次查找培训记录
List< TrainingRecord > findByTrainingCourse (TrainingCourse trainingCourse)
根据培训课程查找培训记录
List< TrainingRecord > findByStatus (TrainingRecord.Status status)
根据培训记录状态查找
List< TrainingRecord > findByUserAndTrainingCourse (User user, TrainingCourse trainingCourse)
根据用户和培训课程查找培训记录
List< TrainingRecord > findByUserAndStatus (User user, TrainingRecord.Status status)
根据用户和培训状态查找培训记录
List< TrainingRecord > findByTrainingDateBetween (LocalDate startDate, LocalDate endDate)
查找特定时间范围内的培训记录
List< TrainingRecord > findNotAttendedRecords ()
查找未签到的培训记录
TrainingRecord updateStatus (Long id, TrainingRecord.Status status)
更新培训记录状态
int batchUpdateStatus (List< Long > ids, TrainingRecord.Status status)
批量更新培训记录状态
List< TrainingRecord > search (String keyword)
搜索培训记录
Double getUserCompletionRate (Long userId)
获取用户的培训完成率
Double getCourseCompletionRate (Long courseId)
获取培训课程的总体完成率
List< TrainingRecord > findByDepartmentId (Long departmentId)
根据部门统计培训记录
List< TrainingRecord > findByPositionId (Long positionId)
根据岗位统计培训记录
TrainingRecord save (TrainingRecord record)
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Protected Member Functions
String getEntityName ()
Detailed Description
培训记录服务实现类
Author
GMP系统开发团队
Definition at line 24 of file TrainingRecordServiceImpl.java.
Constructor & Destructor Documentation
TrainingRecordServiceImpl()
com.gmp.training.service.impl.TrainingRecordServiceImpl.TrainingRecordServiceImpl (TrainingRecordRepository repository)
Definition at line 27 of file TrainingRecordServiceImpl.java.
References repository.
Member Function Documentation
batchUpdateStatus()
int com.gmp.training.service.impl.TrainingRecordServiceImpl.batchUpdateStatus (List< Long > ids, TrainingRecord.Status status)
批量更新培训记录状态
Parameters
ids 记录ID列表
status 状态
Returns
影响的行数
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 85 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testBatchUpdateStatus().
count()
long com.gmp.training.service.BaseService< T, ID >.count () inherited
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity) inherited
删除实体
Parameters
entity 实体对象
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll () inherited
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities) inherited
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id) inherited
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id) inherited
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll () inherited
查询所有实体
Returns
实体列表
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable) inherited
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort) inherited
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids) inherited
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findByDepartmentId()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByDepartmentId (Long departmentId)
根据部门统计培训记录
Parameters
departmentId 部门ID
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 139 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByDepartmentId().
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id) inherited
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
findByPositionId()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByPositionId (Long positionId)
根据岗位统计培训记录
Parameters
positionId 岗位ID
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 146 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByPositionId().
findByStatus()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByStatus (TrainingRecord.Status status)
根据培训记录状态查找
Parameters
status 状态
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 47 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindByStatus().
findByTrainingCourse()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByTrainingCourse (TrainingCourse trainingCourse)
根据培训课程查找培训记录
Parameters
trainingCourse 培训课程
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 42 of file TrainingRecordServiceImpl.java.
References repository.
findByTrainingDateBetween()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByTrainingDateBetween (LocalDate startDate, LocalDate endDate)
查找特定时间范围内的培训记录
Parameters
startDate 开始日期
endDate 结束日期
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 62 of file TrainingRecordServiceImpl.java.
References repository.
findByTrainingSession()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByTrainingSession (TrainingSession trainingSession)
根据培训场次查找培训记录
Parameters
trainingSession 培训场次
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 37 of file TrainingRecordServiceImpl.java.
References repository.
findByUser()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByUser (User user)
根据用户查找培训记录
Parameters
user 用户
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 32 of file TrainingRecordServiceImpl.java.
References repository.
findByUserAndStatus()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByUserAndStatus (User user, TrainingRecord.Status status)
根据用户和培训状态查找培训记录
Parameters
user 用户
status 状态
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 57 of file TrainingRecordServiceImpl.java.
References repository.
findByUserAndTrainingCourse()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findByUserAndTrainingCourse (User user, TrainingCourse trainingCourse)
根据用户和培训课程查找培训记录
Parameters
user 用户
trainingCourse 培训课程
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 52 of file TrainingRecordServiceImpl.java.
References repository.
findNotAttendedRecords()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.findNotAttendedRecords ()
查找未签到的培训记录
Returns
未签到的培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 67 of file TrainingRecordServiceImpl.java.
References repository.
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id) inherited
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
getCourseCompletionRate()
Double com.gmp.training.service.impl.TrainingRecordServiceImpl.getCourseCompletionRate (Long courseId)
获取培训课程的总体完成率
Parameters
courseId 课程ID
Returns
总体完成率（0-100）
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 122 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testGetCourseCompletionRate().
getEntityName()
String com.gmp.training.service.impl.TrainingRecordServiceImpl.getEntityName () protected
Definition at line 163 of file TrainingRecordServiceImpl.java.
getUserCompletionRate()
Double com.gmp.training.service.impl.TrainingRecordServiceImpl.getUserCompletionRate (Long userId)
获取用户的培训完成率
Parameters
userId 用户ID
Returns
培训完成率（0-100）
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 105 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testGetUserCompletionRate().
save() [1/2]
T com.gmp.training.service.BaseService< T, ID >.save (T entity) inherited
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
save() [2/2]
TrainingRecord com.gmp.training.service.impl.TrainingRecordServiceImpl.save (TrainingRecord record)
Definition at line 154 of file TrainingRecordServiceImpl.java.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testSave().
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities) inherited
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
search()
List< TrainingRecord > com.gmp.training.service.impl.TrainingRecordServiceImpl.search (String keyword)
搜索培训记录
Parameters
keyword 关键词
Returns
培训记录列表
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 99 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testSearch().
updateStatus()
TrainingRecord com.gmp.training.service.impl.TrainingRecordServiceImpl.updateStatus (Long id, TrainingRecord.Status status)
更新培训记录状态
Parameters
id 记录ID
status 状态
Returns
更新后的培训记录
Implements com.gmp.training.service.TrainingRecordService.
Definition at line 73 of file TrainingRecordServiceImpl.java.
References repository.
Referenced by com.gmp.training.service.impl.TrainingRecordServiceImplTest.testUpdateStatus().
The documentation for this class was generated from the following file:
training-service/src/main/java/com/gmp/training/service/impl/TrainingRecordServiceImpl.java