GMP系统: com.gmp.qms.controller.impl.McpResourceAccessImpl Class Reference
com.gmp.qms.controller.impl.McpResourceAccessImpl Class Reference
MCP资源访问实现类，负责处理AI模型对QMS系统结构化数据的访问请求
Public Member Functions
Object accessResource (String resourceName, String operation, Map< String, Object > parameters) throws Exception
Object access (String resourceName, Map< String, Object > parameters) throws Exception
Private Member Functions
Object handleDeviationResource (String operation, Map< String, Object > parameters)
处理偏差资源的访问请求
Object handleCapaResource (String operation, Map< String, Object > parameters)
处理CAPA资源的访问请求
Object handleChangeControlResource (String operation, Map< String, Object > parameters)
处理变更控制资源的访问请求
Deviation getDeviationById (Map< String, Object > parameters)
根据ID获取偏差记录
List< Deviation > listDeviations (Map< String, Object > parameters)
获取偏差记录列表
Map< String, Long > getDeviationStatistics (Map< String, Object > parameters)
获取偏差统计信息
Capa getCapaById (Map< String, Object > parameters)
根据ID获取CAPA记录
List< Capa > listCapas (Map< String, Object > parameters)
获取CAPA记录列表
Map< String, Long > getCapaStatistics (Map< String, Object > parameters)
获取CAPA统计信息
ChangeControl getChangeControlById (Map< String, Object > parameters)
根据ID获取变更控制记录
List< ChangeControl > listChangeControls (Map< String, Object > parameters)
获取变更控制记录列表
Map< String, Long > getChangeControlStatistics (Map< String, Object > parameters)
获取变更控制统计信息
Private Attributes
final DeviationRepository deviationRepository
final CapaRepository capaRepository
final ChangeControlRepository changeControlRepository
Detailed Description
MCP资源访问实现类，负责处理AI模型对QMS系统结构化数据的访问请求
Author
GMP系统开发团队
Definition at line 24 of file McpResourceAccessImpl.java.
Member Function Documentation
access()
Object com.gmp.qms.controller.McpController.McpResourceAccess.access (String resourceName, Map< String, Object > parameters) throws Exception inherited
Referenced by com.gmp.qms.controller.McpController.accessResource().
accessResource()
Object com.gmp.qms.controller.impl.McpResourceAccessImpl.accessResource (String resourceName, String operation, Map< String, Object > parameters) throws Exception
Definition at line 31 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.handleCapaResource(), com.gmp.qms.controller.impl.McpResourceAccessImpl.handleChangeControlResource(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.handleDeviationResource().
getCapaById()
Capa com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaById (Map< String, Object > parameters) private
根据ID获取CAPA记录
Definition at line 146 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.capaRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleCapaResource().
getCapaStatistics()
Map< String, Long > com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaStatistics (Map< String, Object > parameters) private
获取CAPA统计信息
Definition at line 173 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.capaRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleCapaResource().
getChangeControlById()
ChangeControl com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlById (Map< String, Object > parameters) private
根据ID获取变更控制记录
Definition at line 183 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.changeControlRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleChangeControlResource().
getChangeControlStatistics()
Map< String, Long > com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlStatistics (Map< String, Object > parameters) private
获取变更控制统计信息
Definition at line 210 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.changeControlRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleChangeControlResource().
getDeviationById()
Deviation com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationById (Map< String, Object > parameters) private
根据ID获取偏差记录
Definition at line 105 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.deviationRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleDeviationResource().
getDeviationStatistics()
Map< String, Long > com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationStatistics (Map< String, Object > parameters) private
获取偏差统计信息
Definition at line 135 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.deviationRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleDeviationResource().
handleCapaResource()
Object com.gmp.qms.controller.impl.McpResourceAccessImpl.handleCapaResource (String operation, Map< String, Object > parameters) private
处理CAPA资源的访问请求
Definition at line 71 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listCapas().
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.accessResource().
handleChangeControlResource()
Object com.gmp.qms.controller.impl.McpResourceAccessImpl.handleChangeControlResource (String operation, Map< String, Object > parameters) private
处理变更控制资源的访问请求
Definition at line 87 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listChangeControls().
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.accessResource().
handleDeviationResource()
Object com.gmp.qms.controller.impl.McpResourceAccessImpl.handleDeviationResource (String operation, Map< String, Object > parameters) private
处理偏差资源的访问请求
Definition at line 55 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listDeviations().
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.accessResource().
listCapas()
List< Capa > com.gmp.qms.controller.impl.McpResourceAccessImpl.listCapas (Map< String, Object > parameters) private
获取CAPA记录列表
Definition at line 155 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.capaRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleCapaResource().
listChangeControls()
List< ChangeControl > com.gmp.qms.controller.impl.McpResourceAccessImpl.listChangeControls (Map< String, Object > parameters) private
获取变更控制记录列表
Definition at line 192 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.changeControlRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleChangeControlResource().
listDeviations()
List< Deviation > com.gmp.qms.controller.impl.McpResourceAccessImpl.listDeviations (Map< String, Object > parameters) private
获取偏差记录列表
Definition at line 114 of file McpResourceAccessImpl.java.
References com.gmp.qms.controller.impl.McpResourceAccessImpl.deviationRepository.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.handleDeviationResource().
Member Data Documentation
capaRepository
final CapaRepository com.gmp.qms.controller.impl.McpResourceAccessImpl.capaRepository private
Definition at line 27 of file McpResourceAccessImpl.java.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getCapaStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listCapas().
changeControlRepository
final ChangeControlRepository com.gmp.qms.controller.impl.McpResourceAccessImpl.changeControlRepository private
Definition at line 28 of file McpResourceAccessImpl.java.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getChangeControlStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listChangeControls().
deviationRepository
final DeviationRepository com.gmp.qms.controller.impl.McpResourceAccessImpl.deviationRepository private
Definition at line 26 of file McpResourceAccessImpl.java.
Referenced by com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationById(), com.gmp.qms.controller.impl.McpResourceAccessImpl.getDeviationStatistics(), and com.gmp.qms.controller.impl.McpResourceAccessImpl.listDeviations().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/controller/impl/McpResourceAccessImpl.java