GMP系统: com.gmp.auth.service.MfaServiceTest Class Reference
com.gmp.auth.service.MfaServiceTest Class Reference
MfaService的单元测试类
Package Functions
void setUp ()
void testGenerateSecretKey ()
void testGenerateTotpCode ()
void testVerifyTotpCode_Success ()
void testVerifyTotpCode_Failure ()
void testGenerateRecoveryCodes ()
void testGenerateQrCodeUrl ()
void testGetRemainingSeconds ()
void testVerifyRecoveryCode_Success ()
void testVerifyRecoveryCode_Failure ()
void testVerifyRecoveryCode_InvalidFormat ()
void testVerifyRecoveryCode_NullParams ()
void testRemoveUsedRecoveryCode ()
void testRemoveNonExistentRecoveryCode ()
void testRemoveUsedRecoveryCode_EmptyList ()
Private Attributes
MfaService mfaService
TotpUtils totpUtils
String testSecretKey
String testUsername
String testIssuer
String testTotpCode
String testRecoveryCode
Detailed Description
MfaService的单元测试类
Definition at line 19 of file MfaServiceTest.java.
Member Function Documentation
setUp()
void com.gmp.auth.service.MfaServiceTest.setUp () package
Definition at line 34 of file MfaServiceTest.java.
testGenerateQrCodeUrl()
void com.gmp.auth.service.MfaServiceTest.testGenerateQrCodeUrl () package
Definition at line 119 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.generateQrCodeUrl(), and com.gmp.auth.service.TotpUtils.generateTotpUri().
testGenerateRecoveryCodes()
void com.gmp.auth.service.MfaServiceTest.testGenerateRecoveryCodes () package
Definition at line 104 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.generateRecoveryCodes().
testGenerateSecretKey()
void com.gmp.auth.service.MfaServiceTest.testGenerateSecretKey () package
Definition at line 45 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.generateSecretKey(), and com.gmp.auth.service.TotpUtils.generateSecretKey().
testGenerateTotpCode()
void com.gmp.auth.service.MfaServiceTest.testGenerateTotpCode () package
Definition at line 60 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.generateTotpCode(), and com.gmp.auth.service.TotpUtils.generateTotpCode().
testGetRemainingSeconds()
void com.gmp.auth.service.MfaServiceTest.testGetRemainingSeconds () package
Definition at line 135 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.getRemainingSeconds(), and com.gmp.auth.service.TotpUtils.getRemainingSeconds().
testRemoveNonExistentRecoveryCode()
void com.gmp.auth.service.MfaServiceTest.testRemoveNonExistentRecoveryCode () package
Definition at line 227 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.removeUsedRecoveryCode().
testRemoveUsedRecoveryCode()
void com.gmp.auth.service.MfaServiceTest.testRemoveUsedRecoveryCode () package
Definition at line 207 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.removeUsedRecoveryCode().
testRemoveUsedRecoveryCode_EmptyList()
void com.gmp.auth.service.MfaServiceTest.testRemoveUsedRecoveryCode_EmptyList () package
Definition at line 243 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.removeUsedRecoveryCode().
testVerifyRecoveryCode_Failure()
void com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_Failure () package
Definition at line 164 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyRecoveryCode().
testVerifyRecoveryCode_InvalidFormat()
void com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_InvalidFormat () package
Definition at line 178 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyRecoveryCode().
testVerifyRecoveryCode_NullParams()
void com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_NullParams () package
Definition at line 192 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyRecoveryCode().
testVerifyRecoveryCode_Success()
void com.gmp.auth.service.MfaServiceTest.testVerifyRecoveryCode_Success () package
Definition at line 150 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyRecoveryCode().
testVerifyTotpCode_Failure()
void com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Failure () package
Definition at line 89 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
testVerifyTotpCode_Success()
void com.gmp.auth.service.MfaServiceTest.testVerifyTotpCode_Success () package
Definition at line 75 of file MfaServiceTest.java.
References com.gmp.auth.service.MfaService.verifyTotpCode(), and com.gmp.auth.service.TotpUtils.verifyTotpCode().
Member Data Documentation
mfaService
MfaService com.gmp.auth.service.MfaServiceTest.mfaService private
Definition at line 22 of file MfaServiceTest.java.
testIssuer
String com.gmp.auth.service.MfaServiceTest.testIssuer private
Definition at line 29 of file MfaServiceTest.java.
testRecoveryCode
String com.gmp.auth.service.MfaServiceTest.testRecoveryCode private
Definition at line 31 of file MfaServiceTest.java.
testSecretKey
String com.gmp.auth.service.MfaServiceTest.testSecretKey private
Definition at line 27 of file MfaServiceTest.java.
testTotpCode
String com.gmp.auth.service.MfaServiceTest.testTotpCode private
Definition at line 30 of file MfaServiceTest.java.
testUsername
String com.gmp.auth.service.MfaServiceTest.testUsername private
Definition at line 28 of file MfaServiceTest.java.
totpUtils
TotpUtils com.gmp.auth.service.MfaServiceTest.totpUtils private
Definition at line 25 of file MfaServiceTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/service/MfaServiceTest.java