GMP系统: com.gmp.training.service.impl.TrainingPlanServiceImplTest Class Reference
com.gmp.training.service.impl.TrainingPlanServiceImplTest Class Reference
培训计划服务实现的单元测试
Package Functions
void setUp ()
void testSave ()
void testFindById ()
void testFindAll ()
void testDelete ()
void testFindByName ()
void testFindByYear ()
void testFindByYearAndQuarter ()
void testUpdateStatus ()
void testBatchUpdateStatus ()
void testCalculateCompletionRate ()
void testGetActualCost ()
void testSearch ()
Private Attributes
TrainingPlanRepository trainingPlanRepository
TrainingPlanServiceImpl trainingPlanService
TrainingPlan trainingPlan
Detailed Description
培训计划服务实现的单元测试
Definition at line 27 of file TrainingPlanServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.setUp () package
Definition at line 38 of file TrainingPlanServiceImplTest.java.
testBatchUpdateStatus()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testBatchUpdateStatus () package
Definition at line 158 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.batchUpdateStatus().
testCalculateCompletionRate()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testCalculateCompletionRate () package
Definition at line 169 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.calculateCompletionRate().
testDelete()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testDelete () package
Definition at line 91 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.delete().
testFindAll()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindAll () package
Definition at line 76 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findAll().
testFindById()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindById () package
Definition at line 65 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.BaseService< T, ID >.findById().
testFindByName()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByName () package
Definition at line 100 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.findByName().
testFindByYear()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByYear () package
Definition at line 115 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.findByYear().
testFindByYearAndQuarter()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindByYearAndQuarter () package
Definition at line 130 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.findByYearAndQuarter().
testGetActualCost()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testGetActualCost () package
Definition at line 185 of file TrainingPlanServiceImplTest.java.
testSave()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testSave () package
Definition at line 53 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.save().
testSearch()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testSearch () package
Definition at line 197 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.search().
testUpdateStatus()
void com.gmp.training.service.impl.TrainingPlanServiceImplTest.testUpdateStatus () package
Definition at line 145 of file TrainingPlanServiceImplTest.java.
References com.gmp.training.service.impl.TrainingPlanServiceImpl.updateStatus().
Member Data Documentation
trainingPlan
TrainingPlan com.gmp.training.service.impl.TrainingPlanServiceImplTest.trainingPlan private
Definition at line 35 of file TrainingPlanServiceImplTest.java.
trainingPlanRepository
TrainingPlanRepository com.gmp.training.service.impl.TrainingPlanServiceImplTest.trainingPlanRepository private
Definition at line 30 of file TrainingPlanServiceImplTest.java.
trainingPlanService
TrainingPlanServiceImpl com.gmp.training.service.impl.TrainingPlanServiceImplTest.trainingPlanService private
Definition at line 33 of file TrainingPlanServiceImplTest.java.
The documentation for this class was generated from the following file:
training-service/src/test/java/com/gmp/training/service/impl/TrainingPlanServiceImplTest.java