GMP系统: com.gmp.edms.service.impl.MinioFileStorageServiceImplTest Class Reference
com.gmp.edms.service.impl.MinioFileStorageServiceImplTest Class Reference
Classes
class Bucket
Package Functions
void setUp () throws IOException
void testUploadFile () throws Exception
void testDownloadFile ()
void testDeleteFile () throws Exception
void testBatchDeleteFiles () throws Exception
void testFileExists () throws Exception
void testFileExists_FileNotFound () throws Exception
void testGeneratePresignedUrl () throws Exception
void testGetFileInfo () throws Exception
void testCopyFile () throws Exception
void testMoveFile () throws Exception
void testListFiles () throws Exception
void testCreateBucket () throws Exception
void testDeleteBucket () throws Exception
void testBucketExists () throws Exception
void testListBuckets () throws Exception
Private Attributes
MinioClient minioClient
MinioFileStorageServiceImpl fileStorageService
String bucketName = "test-bucket"
String objectName = "test/file.pdf"
MultipartFile multipartFile
byte[] testData = "test content".getBytes()
Detailed Description
Definition at line 29 of file MinioFileStorageServiceImplTest.java.
Member Function Documentation
setUp()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.setUp () throws IOException package
Definition at line 43 of file MinioFileStorageServiceImplTest.java.
testBatchDeleteFiles()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testBatchDeleteFiles () throws Exception package
Definition at line 101 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.batchDeleteFiles().
testBucketExists()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testBucketExists () throws Exception package
Definition at line 253 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.bucketExists().
testCopyFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testCopyFile () throws Exception package
Definition at line 170 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.copyFile().
testCreateBucket()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testCreateBucket () throws Exception package
Definition at line 227 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.createBucket().
testDeleteBucket()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDeleteBucket () throws Exception package
Definition at line 240 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteBucket().
testDeleteFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDeleteFile () throws Exception package
Definition at line 89 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.deleteFile().
testDownloadFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testDownloadFile () package
Definition at line 70 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.downloadFile().
testFileExists()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testFileExists () throws Exception package
Definition at line 114 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.fileExists().
testFileExists_FileNotFound()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testFileExists_FileNotFound () throws Exception package
Definition at line 128 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.fileExists().
testGeneratePresignedUrl()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testGeneratePresignedUrl () throws Exception package
Definition at line 140 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.generatePresignedUrl().
testGetFileInfo()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testGetFileInfo () throws Exception package
Definition at line 154 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.getFileInfo().
testListBuckets()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testListBuckets () throws Exception package
Definition at line 266 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listBuckets().
testListFiles()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testListFiles () throws Exception package
Definition at line 202 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.listFiles().
testMoveFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testMoveFile () throws Exception package
Definition at line 185 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.moveFile().
testUploadFile()
void com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testUploadFile () throws Exception package
Definition at line 53 of file MinioFileStorageServiceImplTest.java.
References com.gmp.edms.service.impl.MinioFileStorageServiceImpl.uploadFile().
Member Data Documentation
bucketName
String com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.bucketName = "test-bucket" private
Definition at line 37 of file MinioFileStorageServiceImplTest.java.
fileStorageService
MinioFileStorageServiceImpl com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.fileStorageService private
Definition at line 35 of file MinioFileStorageServiceImplTest.java.
minioClient
MinioClient com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.minioClient private
Definition at line 32 of file MinioFileStorageServiceImplTest.java.
multipartFile
MultipartFile com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.multipartFile private
Definition at line 39 of file MinioFileStorageServiceImplTest.java.
objectName
String com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.objectName = "test/file.pdf" private
Definition at line 38 of file MinioFileStorageServiceImplTest.java.
testData
byte [] com.gmp.edms.service.impl.MinioFileStorageServiceImplTest.testData = "test content".getBytes() private
Definition at line 40 of file MinioFileStorageServiceImplTest.java.
The documentation for this class was generated from the following file:
edms-service/src/test/java/com/gmp/edms/service/impl/MinioFileStorageServiceImplTest.java