GMP系统: com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest Class Reference
com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest Class Reference
Public Member Functions
String getEmployeeId ()
void setEmployeeId (String employeeId)
String getEventType ()
void setEventType (String eventType)
String getUsername ()
void setUsername (String username)
String getDepartment ()
void setDepartment (String department)
String getPosition ()
void setPosition (String position)
LocalDateTime getEffectiveDate ()
void setEffectiveDate (LocalDateTime effectiveDate)
Private Attributes
String employeeId
String eventType
String username
String department
String position
LocalDateTime effectiveDate
Detailed Description
Definition at line 1424 of file GMPComprehensiveAuthIntegrationTest.java.
Member Function Documentation
getDepartment()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getDepartment ()
Definition at line 1438 of file GMPComprehensiveAuthIntegrationTest.java.
getEffectiveDate()
LocalDateTime com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getEffectiveDate ()
Definition at line 1442 of file GMPComprehensiveAuthIntegrationTest.java.
getEmployeeId()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getEmployeeId ()
Definition at line 1432 of file GMPComprehensiveAuthIntegrationTest.java.
getEventType()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getEventType ()
Definition at line 1434 of file GMPComprehensiveAuthIntegrationTest.java.
getPosition()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getPosition ()
Definition at line 1440 of file GMPComprehensiveAuthIntegrationTest.java.
getUsername()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.getUsername ()
Definition at line 1436 of file GMPComprehensiveAuthIntegrationTest.java.
setDepartment()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setDepartment (String department)
Definition at line 1439 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
setEffectiveDate()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setEffectiveDate (LocalDateTime effectiveDate)
Definition at line 1443 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
setEmployeeId()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setEmployeeId (String employeeId)
Definition at line 1433 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
setEventType()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setEventType (String eventType)
Definition at line 1435 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
setPosition()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setPosition (String position)
Definition at line 1441 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
setUsername()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.setUsername (String username)
Definition at line 1437 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testHRSystemIntegration().
Member Data Documentation
department
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.department private
Definition at line 1428 of file GMPComprehensiveAuthIntegrationTest.java.
effectiveDate
LocalDateTime com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.effectiveDate private
Definition at line 1430 of file GMPComprehensiveAuthIntegrationTest.java.
employeeId
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.employeeId private
Definition at line 1425 of file GMPComprehensiveAuthIntegrationTest.java.
eventType
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.eventType private
Definition at line 1426 of file GMPComprehensiveAuthIntegrationTest.java.
position
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.position private
Definition at line 1429 of file GMPComprehensiveAuthIntegrationTest.java.
username
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.HRSystemSyncRequest.username private
Definition at line 1427 of file GMPComprehensiveAuthIntegrationTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/GMPComprehensiveAuthIntegrationTest.java