GMP系统: com.gmp.auth.entity.RoleTest Class Reference
com.gmp.auth.entity.RoleTest Class Reference
Role实体单元测试
Package Functions
void testRoleCreation ()
void testRoleCodeValidation ()
void testRoleActiveState ()
void testRolePriorityOrdering ()
void testRoleWithNullValues ()
void testRoleAuditFields ()
void testRoleValidationScenarios ()
Detailed Description
Role实体单元测试
Author
GMP系统开发团队
Definition at line 16 of file RoleTest.java.
Member Function Documentation
testRoleActiveState()
void com.gmp.auth.entity.RoleTest.testRoleActiveState () package
Definition at line 65 of file RoleTest.java.
References com.gmp.auth.entity.Role.isValid(), and com.gmp.auth.entity.Role.roleCode.
testRoleAuditFields()
void com.gmp.auth.entity.RoleTest.testRoleAuditFields () package
Definition at line 112 of file RoleTest.java.
References com.gmp.auth.entity.Role.roleCode.
testRoleCodeValidation()
void com.gmp.auth.entity.RoleTest.testRoleCodeValidation () package
Definition at line 41 of file RoleTest.java.
References com.gmp.auth.entity.Role.roleCode.
testRoleCreation()
void com.gmp.auth.entity.RoleTest.testRoleCreation () package
Definition at line 19 of file RoleTest.java.
References com.gmp.auth.entity.Role.isValid(), and com.gmp.auth.entity.Role.roleCode.
testRolePriorityOrdering()
void com.gmp.auth.entity.RoleTest.testRolePriorityOrdering () package
Definition at line 85 of file RoleTest.java.
References com.gmp.auth.entity.Role.roleCode.
testRoleValidationScenarios()
void com.gmp.auth.entity.RoleTest.testRoleValidationScenarios () package
Definition at line 130 of file RoleTest.java.
References com.gmp.auth.entity.Role.isValid(), com.gmp.auth.entity.Role.roleCode, and com.gmp.auth.entity.Role.roleName.
testRoleWithNullValues()
void com.gmp.auth.entity.RoleTest.testRoleWithNullValues () package
Definition at line 98 of file RoleTest.java.
References com.gmp.auth.entity.Role.roleCode.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/RoleTest.java