GMP系统: com.gmp.qms.service.impl.CapaServiceImpl Class Reference
com.gmp.qms.service.impl.CapaServiceImpl Class Reference
CAPA管理服务实现类
Public Member Functions
Capa createCapa (CapaDTO capaDTO)
创建新的CAPA记录
Capa updateCapa (Long id, CapaDTO capaDTO)
更新CAPA记录
Capa getCapaById (Long id)
根据ID查询CAPA
Capa getCapaByCode (String capaCode)
根据编号查询CAPA
Page< Capa > findAllCapas (Pageable pageable)
分页查询CAPA列表
Page< Capa > searchCapas (CapaSearchCriteria criteria, Pageable pageable)
根据条件查询CAPA列表
Capa updateCapaStatus (Long id, Capa.CapaStatus status, String comments)
更新CAPA状态
Capa addAttachment (Long capaId, MultipartFile file, String description)
为CAPA添加附件
Capa removeAttachment (Long capaId, Long attachmentId)
删除CAPA附件
List< Capa > findOverdueCapas ()
查询逾期未处理的CAPA
String generateCapaCode ()
生成CAPA编号
Private Member Functions
Specification< Capa > buildCapaSpecification (CapaSearchCriteria criteria)
构建CAPA查询条件
Private Attributes
final CapaRepository capaRepository
Static Private Attributes
static final String UPLOAD_DIR = "/opt/gmp-system/uploads/capas/"
Detailed Description
CAPA管理服务实现类
Author
GMP系统开发团队
Definition at line 36 of file CapaServiceImpl.java.
Member Function Documentation
addAttachment()
Capa com.gmp.qms.service.impl.CapaServiceImpl.addAttachment (Long capaId, MultipartFile file, String description)
为CAPA添加附件
Parameters
capaId CAPA ID
file 上传的文件
description 文件描述
Returns
更新后的CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 98 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository, com.gmp.qms.service.impl.CapaServiceImpl.getCapaById(), and com.gmp.qms.service.impl.CapaServiceImpl.UPLOAD_DIR.
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testAddAttachmentSuccess().
buildCapaSpecification()
Specification< Capa > com.gmp.qms.service.impl.CapaServiceImpl.buildCapaSpecification (CapaSearchCriteria criteria) private
构建CAPA查询条件
Definition at line 172 of file CapaServiceImpl.java.
Referenced by com.gmp.qms.service.impl.CapaServiceImpl.searchCapas().
createCapa()
Capa com.gmp.qms.service.impl.CapaServiceImpl.createCapa (CapaDTO capaDTO)
创建新的CAPA记录
Parameters
capaDTO CAPA信息DTO
Returns
创建的CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 44 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository, and com.gmp.qms.service.impl.CapaServiceImpl.generateCapaCode().
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testCreateCapa().
findAllCapas()
Page< Capa > com.gmp.qms.service.impl.CapaServiceImpl.findAllCapas (Pageable pageable)
分页查询CAPA列表
Parameters
pageable 分页参数
Returns
CAPA分页列表
Implements com.gmp.qms.service.CapaService.
Definition at line 77 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testFindAllCapas().
findOverdueCapas()
List< Capa > com.gmp.qms.service.impl.CapaServiceImpl.findOverdueCapas ()
查询逾期未处理的CAPA
Returns
逾期CAPA列表
Implements com.gmp.qms.service.CapaService.
Definition at line 148 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testFindOverdueCapas().
generateCapaCode()
String com.gmp.qms.service.impl.CapaServiceImpl.generateCapaCode ()
生成CAPA编号
Returns
新的CAPA编号
Implements com.gmp.qms.service.CapaService.
Definition at line 158 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImpl.createCapa(), and com.gmp.qms.service.impl.CapaServiceImplTest.testGenerateCapaCode().
getCapaByCode()
Capa com.gmp.qms.service.impl.CapaServiceImpl.getCapaByCode (String capaCode)
根据编号查询CAPA
Parameters
capaCode CAPA编号
Returns
CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 72 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testGetCapaByCode().
getCapaById()
Capa com.gmp.qms.service.impl.CapaServiceImpl.getCapaById (Long id)
根据ID查询CAPA
Parameters
id CAPA ID
Returns
CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 66 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImpl.addAttachment(), com.gmp.qms.service.impl.CapaServiceImpl.removeAttachment(), com.gmp.qms.service.impl.CapaServiceImplTest.testGetCapaById(), com.gmp.qms.service.impl.CapaServiceImpl.updateCapa(), and com.gmp.qms.service.impl.CapaServiceImpl.updateCapaStatus().
removeAttachment()
Capa com.gmp.qms.service.impl.CapaServiceImpl.removeAttachment (Long capaId, Long attachmentId)
删除CAPA附件
Parameters
capaId CAPA ID
attachmentId 附件ID
Returns
更新后的CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 133 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository, and com.gmp.qms.service.impl.CapaServiceImpl.getCapaById().
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testRemoveAttachment().
searchCapas()
Page< Capa > com.gmp.qms.service.impl.CapaServiceImpl.searchCapas (CapaSearchCriteria criteria, Pageable pageable)
根据条件查询CAPA列表
Parameters
criteria 查询条件
pageable 分页参数
Returns
CAPA分页列表
Implements com.gmp.qms.service.CapaService.
Definition at line 82 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.buildCapaSpecification(), and com.gmp.qms.service.impl.CapaServiceImpl.capaRepository.
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testSearchCapas().
updateCapa()
Capa com.gmp.qms.service.impl.CapaServiceImpl.updateCapa (Long id, CapaDTO capaDTO)
更新CAPA记录
Parameters
id CAPA ID
capaDTO 更新的CAPA信息
Returns
更新后的CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 59 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository, and com.gmp.qms.service.impl.CapaServiceImpl.getCapaById().
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testUpdateCapa().
updateCapaStatus()
Capa com.gmp.qms.service.impl.CapaServiceImpl.updateCapaStatus (Long id, Capa.CapaStatus status, String comments)
更新CAPA状态
Parameters
id CAPA ID
status 新状态
comments 状态变更说明
Returns
更新后的CAPA实体
Implements com.gmp.qms.service.CapaService.
Definition at line 89 of file CapaServiceImpl.java.
References com.gmp.qms.service.impl.CapaServiceImpl.capaRepository, and com.gmp.qms.service.impl.CapaServiceImpl.getCapaById().
Referenced by com.gmp.qms.service.impl.CapaServiceImplTest.testUpdateCapaStatus().
Member Data Documentation
capaRepository
final CapaRepository com.gmp.qms.service.impl.CapaServiceImpl.capaRepository private
Definition at line 38 of file CapaServiceImpl.java.
Referenced by com.gmp.qms.service.impl.CapaServiceImpl.addAttachment(), com.gmp.qms.service.impl.CapaServiceImpl.createCapa(), com.gmp.qms.service.impl.CapaServiceImpl.findAllCapas(), com.gmp.qms.service.impl.CapaServiceImpl.findOverdueCapas(), com.gmp.qms.service.impl.CapaServiceImpl.generateCapaCode(), com.gmp.qms.service.impl.CapaServiceImpl.getCapaByCode(), com.gmp.qms.service.impl.CapaServiceImpl.getCapaById(), com.gmp.qms.service.impl.CapaServiceImpl.removeAttachment(), com.gmp.qms.service.impl.CapaServiceImpl.searchCapas(), com.gmp.qms.service.impl.CapaServiceImpl.updateCapa(), and com.gmp.qms.service.impl.CapaServiceImpl.updateCapaStatus().
UPLOAD_DIR
final String com.gmp.qms.service.impl.CapaServiceImpl.UPLOAD_DIR = "/opt/gmp-system/uploads/capas/" static private
Definition at line 40 of file CapaServiceImpl.java.
Referenced by com.gmp.qms.service.impl.CapaServiceImpl.addAttachment().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/service/impl/CapaServiceImpl.java