GMP系统: com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest Class Reference
com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest Class Reference
Public Member Functions
String getResetToken ()
void setResetToken (String resetToken)
String getNewPassword ()
void setNewPassword (String newPassword)
Private Attributes
String resetToken
String newPassword
Detailed Description
Definition at line 1397 of file GMPComprehensiveAuthIntegrationTest.java.
Member Function Documentation
getNewPassword()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.getNewPassword ()
Definition at line 1403 of file GMPComprehensiveAuthIntegrationTest.java.
getResetToken()
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.getResetToken ()
Definition at line 1401 of file GMPComprehensiveAuthIntegrationTest.java.
setNewPassword()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.setNewPassword (String newPassword)
Definition at line 1404 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.performGMPPasswordReset(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordResetFlow().
setResetToken()
void com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.setResetToken (String resetToken)
Definition at line 1402 of file GMPComprehensiveAuthIntegrationTest.java.
Referenced by com.gmp.auth.GMPComprehensiveAuthIntegrationTest.performGMPPasswordReset(), and com.gmp.auth.GMPComprehensiveAuthIntegrationTest.testPasswordResetFlow().
Member Data Documentation
newPassword
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.newPassword private
Definition at line 1399 of file GMPComprehensiveAuthIntegrationTest.java.
resetToken
String com.gmp.auth.GMPComprehensiveAuthIntegrationTest.PasswordResetConfirmRequest.resetToken private
Definition at line 1398 of file GMPComprehensiveAuthIntegrationTest.java.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/GMPComprehensiveAuthIntegrationTest.java