GMP系统: com.gmp.equipment.controller.CalibrationRecordControllerTest Class Reference
com.gmp.equipment.controller.CalibrationRecordControllerTest Class Reference
CalibrationRecordController的单元测试类
Package Functions
void setUp ()
void getById_success ()
void getByCalibrationNumber_success ()
void listPage_success ()
void listByEquipmentId_success ()
void listByDateRange_success () throws ParseException
void listByDateRange_invalidDateFormat () throws ParseException
void create_success ()
void update_success ()
void delete_success ()
Private Attributes
CalibrationRecordService calibrationRecordService
CalibrationRecordController calibrationRecordController
Detailed Description
CalibrationRecordController的单元测试类
Definition at line 26 of file CalibrationRecordControllerTest.java.
Member Function Documentation
create_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.create_success () package
Definition at line 176 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.create().
delete_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.delete_success () package
Definition at line 223 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.delete().
getByCalibrationNumber_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.getByCalibrationNumber_success () package
Definition at line 60 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.getByCalibrationNumber().
getById_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.getById_success () package
Definition at line 40 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.getById().
listByDateRange_invalidDateFormat()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_invalidDateFormat () throws ParseException package
Definition at line 160 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.listByDateRange().
listByDateRange_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_success () throws ParseException package
Definition at line 134 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.listByDateRange().
listByEquipmentId_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.listByEquipmentId_success () package
Definition at line 112 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.listByEquipmentId().
listPage_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.listPage_success () package
Definition at line 80 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.listPage().
setUp()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.setUp () package
Definition at line 35 of file CalibrationRecordControllerTest.java.
update_success()
void com.gmp.equipment.controller.CalibrationRecordControllerTest.update_success () package
Definition at line 200 of file CalibrationRecordControllerTest.java.
References com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController, com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService, and com.gmp.equipment.controller.CalibrationRecordController.update().
Member Data Documentation
calibrationRecordController
CalibrationRecordController com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordController private
Definition at line 32 of file CalibrationRecordControllerTest.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.create_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.delete_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.getByCalibrationNumber_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.getById_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_invalidDateFormat(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByEquipmentId_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listPage_success(), and com.gmp.equipment.controller.CalibrationRecordControllerTest.update_success().
calibrationRecordService
CalibrationRecordService com.gmp.equipment.controller.CalibrationRecordControllerTest.calibrationRecordService private
Definition at line 29 of file CalibrationRecordControllerTest.java.
Referenced by com.gmp.equipment.controller.CalibrationRecordControllerTest.create_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.delete_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.getByCalibrationNumber_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.getById_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_invalidDateFormat(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByDateRange_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listByEquipmentId_success(), com.gmp.equipment.controller.CalibrationRecordControllerTest.listPage_success(), and com.gmp.equipment.controller.CalibrationRecordControllerTest.update_success().
The documentation for this class was generated from the following file:
equipment-service/src/test/java/com/gmp/equipment/controller/CalibrationRecordControllerTest.java