GMP系统: com.gmp.equipment.controller.EquipmentControllerTest Class Reference
com.gmp.equipment.controller.EquipmentControllerTest Class Reference
EquipmentController的单元测试类
Package Functions
void setUp ()
void getById_success ()
void getById_notFound ()
void listPage_success ()
void create_success ()
void update_success ()
void delete_success ()
void deleteBatch_success ()
Private Attributes
EquipmentService equipmentService
EquipmentController equipmentController
Detailed Description
EquipmentController的单元测试类
Definition at line 23 of file EquipmentControllerTest.java.
Member Function Documentation
create_success()
void com.gmp.equipment.controller.EquipmentControllerTest.create_success () package
Definition at line 106 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentController.create(), com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, and com.gmp.equipment.controller.EquipmentControllerTest.equipmentService.
delete_success()
void com.gmp.equipment.controller.EquipmentControllerTest.delete_success () package
Definition at line 153 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentController.delete(), com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, and com.gmp.equipment.controller.EquipmentControllerTest.equipmentService.
deleteBatch_success()
void com.gmp.equipment.controller.EquipmentControllerTest.deleteBatch_success () package
Definition at line 170 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentController.deleteBatch(), com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, and com.gmp.equipment.controller.EquipmentControllerTest.equipmentService.
getById_notFound()
void com.gmp.equipment.controller.EquipmentControllerTest.getById_notFound () package
Definition at line 57 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, com.gmp.equipment.controller.EquipmentControllerTest.equipmentService, and com.gmp.equipment.controller.EquipmentController.getById().
getById_success()
void com.gmp.equipment.controller.EquipmentControllerTest.getById_success () package
Definition at line 37 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, com.gmp.equipment.controller.EquipmentControllerTest.equipmentService, and com.gmp.equipment.controller.EquipmentController.getById().
listPage_success()
void com.gmp.equipment.controller.EquipmentControllerTest.listPage_success () package
Definition at line 74 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, com.gmp.equipment.controller.EquipmentControllerTest.equipmentService, and com.gmp.equipment.controller.EquipmentController.listPage().
setUp()
void com.gmp.equipment.controller.EquipmentControllerTest.setUp () package
Definition at line 32 of file EquipmentControllerTest.java.
update_success()
void com.gmp.equipment.controller.EquipmentControllerTest.update_success () package
Definition at line 130 of file EquipmentControllerTest.java.
References com.gmp.equipment.controller.EquipmentControllerTest.equipmentController, com.gmp.equipment.controller.EquipmentControllerTest.equipmentService, and com.gmp.equipment.controller.EquipmentController.update().
Member Data Documentation
equipmentController
EquipmentController com.gmp.equipment.controller.EquipmentControllerTest.equipmentController private
Definition at line 29 of file EquipmentControllerTest.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.create_success(), com.gmp.equipment.controller.EquipmentControllerTest.delete_success(), com.gmp.equipment.controller.EquipmentControllerTest.deleteBatch_success(), com.gmp.equipment.controller.EquipmentControllerTest.getById_notFound(), com.gmp.equipment.controller.EquipmentControllerTest.getById_success(), com.gmp.equipment.controller.EquipmentControllerTest.listPage_success(), and com.gmp.equipment.controller.EquipmentControllerTest.update_success().
equipmentService
EquipmentService com.gmp.equipment.controller.EquipmentControllerTest.equipmentService private
Definition at line 26 of file EquipmentControllerTest.java.
Referenced by com.gmp.equipment.controller.EquipmentControllerTest.create_success(), com.gmp.equipment.controller.EquipmentControllerTest.delete_success(), com.gmp.equipment.controller.EquipmentControllerTest.deleteBatch_success(), com.gmp.equipment.controller.EquipmentControllerTest.getById_notFound(), com.gmp.equipment.controller.EquipmentControllerTest.getById_success(), com.gmp.equipment.controller.EquipmentControllerTest.listPage_success(), and com.gmp.equipment.controller.EquipmentControllerTest.update_success().
The documentation for this class was generated from the following file:
equipment-service/src/test/java/com/gmp/equipment/controller/EquipmentControllerTest.java