GMP系统: com.gmp.hr.service.impl.DepartmentServiceImpl Class Reference
com.gmp.hr.service.impl.DepartmentServiceImpl Class Reference
部门服务实现类
Public Member Functions
DepartmentServiceImpl (DepartmentRepository departmentRepository, EmployeeRepository employeeRepository, DepartmentMapper departmentMapper)
DepartmentDTO createDepartment (DepartmentDTO departmentDTO)
创建部门
DepartmentDTO getDepartmentById (Long id)
根据ID获取部门
DepartmentDTO getDepartmentByCode (String departmentCode)
根据部门代码获取部门
DepartmentDTO updateDepartment (Long id, DepartmentDTO departmentDTO)
更新部门信息
void deleteDepartment (Long id)
删除部门（软删除）
List< DepartmentDTO > getAllDepartments ()
获取所有部门列表
List< DepartmentDTO > getTopDepartments ()
获取所有顶级部门
List< DepartmentDTO > getChildDepartments (Long parentId)
根据父部门ID获取子部门
List< DepartmentDTO > getDepartmentTree ()
获取部门树结构
DepartmentDTO getDepartmentByManager (Long managerId)
根据部门经理ID获取部门
Private Member Functions
boolean isCircularReference (Department department, Long targetId)
检查是否会形成循环引用
DepartmentDTO buildDepartmentTree (Department department)
递归构建部门树
Private Attributes
final DepartmentRepository departmentRepository
final EmployeeRepository employeeRepository
final DepartmentMapper departmentMapper
Detailed Description
部门服务实现类
Author
GMP Team
Version
1.0.0
Definition at line 24 of file DepartmentServiceImpl.java.
Constructor & Destructor Documentation
DepartmentServiceImpl()
com.gmp.hr.service.impl.DepartmentServiceImpl.DepartmentServiceImpl (DepartmentRepository departmentRepository, EmployeeRepository employeeRepository, DepartmentMapper departmentMapper)
Definition at line 31 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
Member Function Documentation
buildDepartmentTree()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree (Department department) private
递归构建部门树
Parameters
department 部门实体
Returns
部门DTO树节点
Definition at line 271 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), and com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentTree().
createDepartment()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.createDepartment (DepartmentDTO departmentDTO)
创建部门
Parameters
departmentDTO 部门DTO
Returns
创建的部门DTO
Implements com.gmp.hr.service.DepartmentService.
Definition at line 41 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.isCircularReference().
Referenced by com.gmp.hr.service.impl.DepartmentServiceImplTest.testCreateDepartment_CodeExists(), and com.gmp.hr.service.impl.DepartmentServiceImplTest.testCreateDepartment_Success().
deleteDepartment()
void com.gmp.hr.service.impl.DepartmentServiceImpl.deleteDepartment (Long id)
删除部门（软删除）
Parameters
id 部门ID
Implements com.gmp.hr.service.DepartmentService.
Definition at line 196 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImplTest.testDeleteDepartment_HasEmployees(), com.gmp.hr.service.impl.DepartmentServiceImplTest.testDeleteDepartment_HasSubDepartments(), and com.gmp.hr.service.impl.DepartmentServiceImplTest.testDeleteDepartment_Success().
getAllDepartments()
List< DepartmentDTO > com.gmp.hr.service.impl.DepartmentServiceImpl.getAllDepartments ()
获取所有部门列表
Returns
部门列表
Implements com.gmp.hr.service.DepartmentService.
Definition at line 223 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImplTest.testGetAllDepartments_Success().
getChildDepartments()
List< DepartmentDTO > com.gmp.hr.service.impl.DepartmentServiceImpl.getChildDepartments (Long parentId)
根据父部门ID获取子部门
Parameters
parentId 父部门ID
Returns
子部门列表
Implements com.gmp.hr.service.DepartmentService.
Definition at line 242 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository.
getDepartmentByCode()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByCode (String departmentCode)
根据部门代码获取部门
Parameters
departmentCode 部门代码
Returns
部门DTO
Implements com.gmp.hr.service.DepartmentService.
Definition at line 121 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
getDepartmentById()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentById (Long id)
根据ID获取部门
Parameters
id 部门ID
Returns
部门DTO
Implements com.gmp.hr.service.DepartmentService.
Definition at line 104 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImplTest.testGetDepartmentById_NotFound(), and com.gmp.hr.service.impl.DepartmentServiceImplTest.testGetDepartmentById_Success().
getDepartmentByManager()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByManager (Long managerId)
根据部门经理ID获取部门
Parameters
managerId 部门经理ID
Returns
部门DTO
Implements com.gmp.hr.service.DepartmentService.
Definition at line 292 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository.
getDepartmentTree()
List< DepartmentDTO > com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentTree ()
获取部门树结构
Returns
部门树结构
Implements com.gmp.hr.service.DepartmentService.
Definition at line 251 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), and com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository.
getTopDepartments()
List< DepartmentDTO > com.gmp.hr.service.impl.DepartmentServiceImpl.getTopDepartments ()
获取所有顶级部门
Returns
顶级部门列表
Implements com.gmp.hr.service.DepartmentService.
Definition at line 233 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository.
isCircularReference()
boolean com.gmp.hr.service.impl.DepartmentServiceImpl.isCircularReference (Department department, Long targetId) private
检查是否会形成循环引用
Parameters
department 部门
targetId 目标部门ID
Returns
是否形成循环引用
Definition at line 92 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.isCircularReference().
Referenced by com.gmp.hr.service.impl.DepartmentServiceImpl.createDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.isCircularReference(), and com.gmp.hr.service.impl.DepartmentServiceImpl.updateDepartment().
updateDepartment()
DepartmentDTO com.gmp.hr.service.impl.DepartmentServiceImpl.updateDepartment (Long id, DepartmentDTO departmentDTO)
更新部门信息
Parameters
id 部门ID
departmentDTO 部门DTO
Returns
更新后的部门DTO
Implements com.gmp.hr.service.DepartmentService.
Definition at line 134 of file DepartmentServiceImpl.java.
References com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper, com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository, com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository, and com.gmp.hr.service.impl.DepartmentServiceImpl.isCircularReference().
Referenced by com.gmp.hr.service.impl.DepartmentServiceImplTest.testUpdateDepartment_Success().
Member Data Documentation
departmentMapper
final DepartmentMapper com.gmp.hr.service.impl.DepartmentServiceImpl.departmentMapper private
Definition at line 28 of file DepartmentServiceImpl.java.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), com.gmp.hr.service.impl.DepartmentServiceImpl.createDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.DepartmentServiceImpl(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByCode(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentById(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByManager(), and com.gmp.hr.service.impl.DepartmentServiceImpl.updateDepartment().
departmentRepository
final DepartmentRepository com.gmp.hr.service.impl.DepartmentServiceImpl.departmentRepository private
Definition at line 26 of file DepartmentServiceImpl.java.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), com.gmp.hr.service.impl.DepartmentServiceImpl.createDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.deleteDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.DepartmentServiceImpl(), com.gmp.hr.service.impl.DepartmentServiceImpl.getAllDepartments(), com.gmp.hr.service.impl.DepartmentServiceImpl.getChildDepartments(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByCode(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentById(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByManager(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentTree(), com.gmp.hr.service.impl.DepartmentServiceImpl.getTopDepartments(), and com.gmp.hr.service.impl.DepartmentServiceImpl.updateDepartment().
employeeRepository
final EmployeeRepository com.gmp.hr.service.impl.DepartmentServiceImpl.employeeRepository private
Definition at line 27 of file DepartmentServiceImpl.java.
Referenced by com.gmp.hr.service.impl.DepartmentServiceImpl.buildDepartmentTree(), com.gmp.hr.service.impl.DepartmentServiceImpl.createDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.deleteDepartment(), com.gmp.hr.service.impl.DepartmentServiceImpl.DepartmentServiceImpl(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByCode(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentById(), com.gmp.hr.service.impl.DepartmentServiceImpl.getDepartmentByManager(), and com.gmp.hr.service.impl.DepartmentServiceImpl.updateDepartment().
The documentation for this class was generated from the following file:
hr-service/src/main/java/com/gmp/hr/service/impl/DepartmentServiceImpl.java