GMP系统: com.gmp.auth.entity.PermissionTest Class Reference
com.gmp.auth.entity.PermissionTest Class Reference
Permission实体单元测试
Package Functions
void testPermissionCreation ()
void testPermissionCodeValidation ()
void testResourceTypeValidation ()
void testHttpMethodValidation ()
void testResourceUrlMatching ()
void testPermissionWithNullResourceUrl ()
void testPermissionActiveState ()
void testPermissionWithMinimalData ()
void testPermissionAuditFields ()
void testPermissionValidationScenarios ()
void testUrlPatternMatching ()
Detailed Description
Permission实体单元测试
Author
GMP系统开发团队
Definition at line 16 of file PermissionTest.java.
Member Function Documentation
testHttpMethodValidation()
void com.gmp.auth.entity.PermissionTest.testHttpMethodValidation () package
Definition at line 96 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.permissionCode.
testPermissionActiveState()
void com.gmp.auth.entity.PermissionTest.testPermissionActiveState () package
Definition at line 162 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.isValid(), and com.gmp.auth.entity.Permission.permissionCode.
testPermissionAuditFields()
void com.gmp.auth.entity.PermissionTest.testPermissionAuditFields () package
Definition at line 198 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.permissionCode.
testPermissionCodeValidation()
void com.gmp.auth.entity.PermissionTest.testPermissionCodeValidation () package
Definition at line 43 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.permissionCode.
testPermissionCreation()
void com.gmp.auth.entity.PermissionTest.testPermissionCreation () package
Definition at line 19 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.isValid(), and com.gmp.auth.entity.Permission.permissionCode.
testPermissionValidationScenarios()
void com.gmp.auth.entity.PermissionTest.testPermissionValidationScenarios () package
Definition at line 216 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.isValid(), com.gmp.auth.entity.Permission.permissionCode, and com.gmp.auth.entity.Permission.permissionName.
testPermissionWithMinimalData()
void com.gmp.auth.entity.PermissionTest.testPermissionWithMinimalData () package
Definition at line 182 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.permissionCode.
testPermissionWithNullResourceUrl()
void com.gmp.auth.entity.PermissionTest.testPermissionWithNullResourceUrl () package
Definition at line 147 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.matches(), and com.gmp.auth.entity.Permission.permissionCode.
testResourceTypeValidation()
void com.gmp.auth.entity.PermissionTest.testResourceTypeValidation () package
Definition at line 67 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.permissionCode.
testResourceUrlMatching()
void com.gmp.auth.entity.PermissionTest.testResourceUrlMatching () package
Definition at line 119 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.matches(), and com.gmp.auth.entity.Permission.permissionCode.
testUrlPatternMatching()
void com.gmp.auth.entity.PermissionTest.testUrlPatternMatching () package
Definition at line 237 of file PermissionTest.java.
References com.gmp.auth.entity.Permission.matches(), and com.gmp.auth.entity.Permission.permissionCode.
The documentation for this class was generated from the following file:
auth-service/src/test/java/com/gmp/auth/entity/PermissionTest.java