GMP系统: com.gmp.auth.entity.Organization Class Reference
com.gmp.auth.entity.Organization Class Reference
GMP系统组织架构实体
Classes
enum OrganizationStatus
组织状态枚举
enum OrganizationType
组织类型枚举 - 定义GMP企业常见的组织架构类型
Public Member Functions
boolean isActive ()
判断组织是否有效（可运营状态）
String getFullPath ()
获取组织的完整层级路径
boolean isGmpOrganization ()
判断是否为GMP相关组织
String getResponsibleManager ()
获取组织的管理责任人
Private Attributes
Long id
String orgCode
String orgName
String description
OrganizationType orgType = OrganizationType.DEPARTMENT
Organization parent
Integer hierarchyLevel = 1
String manager
String contactInfo
OrganizationStatus orgStatus = OrganizationStatus.ACTIVE
Boolean gmpRelevant = false
String gmpResponsible
String gmpRequirements
LocalDateTime createdAt
LocalDateTime updatedAt
Long createdBy
Long updatedBy
Integer version = 1
Detailed Description
GMP系统组织架构实体
支持多层次组织架构管理，包括：
部门管理架构：行政、人事、财务等职能部门
生产管理架构：车间、分车间、生产线级别的生产组织
质量管理架构：质量检验、审核、体系管理等
合规审核架构：GMP审核、法规事务等
培训管理架构：培训规划、执行、评估等
Definition at line 53 of file Organization.java.
Member Function Documentation
getFullPath()
String com.gmp.auth.entity.Organization.getFullPath ()
获取组织的完整层级路径
Definition at line 196 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGetFullPathWithoutParent(), com.gmp.auth.entity.OrganizationTest.testGetFullPathWithParent(), com.gmp.auth.entity.OrganizationTest.testNestedOrganizationHierarchy(), and com.gmp.auth.entity.OrganizationTest.testOrganizationHierarchy().
getResponsibleManager()
String com.gmp.auth.entity.Organization.getResponsibleManager ()
获取组织的管理责任人
Definition at line 218 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGetResponsibleManager(), and com.gmp.auth.entity.OrganizationTest.testGmpCompliance().
isActive()
boolean com.gmp.auth.entity.Organization.isActive ()
判断组织是否有效（可运营状态）
Definition at line 188 of file Organization.java.
References com.gmp.auth.entity.Organization.OrganizationStatus.ACTIVE.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsActive(), and com.gmp.auth.entity.OrganizationTest.testOrganizationCreation().
isGmpOrganization()
boolean com.gmp.auth.entity.Organization.isGmpOrganization ()
判断是否为GMP相关组织
Definition at line 207 of file Organization.java.
References com.gmp.auth.entity.Organization.OrganizationType.TRAINING.
Referenced by com.gmp.auth.entity.OrganizationTest.testGmpCompliance(), and com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization().
Member Data Documentation
contactInfo
String com.gmp.auth.entity.Organization.contactInfo private
Definition at line 96 of file Organization.java.
createdAt
LocalDateTime com.gmp.auth.entity.Organization.createdAt private
Definition at line 120 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testAuditFields().
createdBy
Long com.gmp.auth.entity.Organization.createdBy private
Definition at line 127 of file Organization.java.
description
String com.gmp.auth.entity.Organization.description private
Definition at line 73 of file Organization.java.
gmpRelevant
Boolean com.gmp.auth.entity.Organization.gmpRelevant = false private
Definition at line 107 of file Organization.java.
gmpRequirements
String com.gmp.auth.entity.Organization.gmpRequirements private
Definition at line 115 of file Organization.java.
gmpResponsible
String com.gmp.auth.entity.Organization.gmpResponsible private
Definition at line 111 of file Organization.java.
hierarchyLevel
Integer com.gmp.auth.entity.Organization.hierarchyLevel = 1 private
Definition at line 88 of file Organization.java.
id
Long com.gmp.auth.entity.Organization.id private
Definition at line 57 of file Organization.java.
manager
String com.gmp.auth.entity.Organization.manager private
Definition at line 92 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGetResponsibleManager().
orgCode
String com.gmp.auth.entity.Organization.orgCode private
Definition at line 64 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testNestedOrganizationHierarchy(), com.gmp.auth.entity.OrganizationTest.testOrganizationBuilderDefaultValues(), com.gmp.auth.entity.OrganizationTest.testOrganizationCreation(), com.gmp.auth.entity.OrganizationTest.testOrganizationHierarchy(), and com.gmp.auth.entity.OrganizationTest.testOrganizationValidation().
orgName
String com.gmp.auth.entity.Organization.orgName private
Definition at line 69 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGetFullPathWithoutParent(), com.gmp.auth.entity.OrganizationTest.testGetFullPathWithParent(), and com.gmp.auth.entity.OrganizationTest.testGmpCompliance().
orgStatus
OrganizationStatus com.gmp.auth.entity.Organization.orgStatus = OrganizationStatus.ACTIVE private
Definition at line 102 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsActive().
orgType
OrganizationType com.gmp.auth.entity.Organization.orgType = OrganizationType.DEPARTMENT private
Definition at line 79 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization().
parent
Organization com.gmp.auth.entity.Organization.parent private
Definition at line 84 of file Organization.java.
updatedAt
LocalDateTime com.gmp.auth.entity.Organization.updatedAt private
Definition at line 124 of file Organization.java.
updatedBy
Long com.gmp.auth.entity.Organization.updatedBy private
Definition at line 130 of file Organization.java.
version
Integer com.gmp.auth.entity.Organization.version = 1 private
Definition at line 135 of file Organization.java.
The documentation for this class was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/Organization.java