GMP系统: com.gmp.mes.entity.EquipmentMonitor Class Reference
com.gmp.mes.entity.EquipmentMonitor Class Reference
设备监控实体 - 用于跟踪设备状态和性能指标
Classes
enum EquipmentStatus
设备状态枚举
Public Member Functions
String getEquipmentId ()
void setEquipmentId (String equipmentId)
String getType ()
void setType (String type)
Double getTempThreshold ()
void setTempThreshold (Double tempThreshold)
Double getPressThreshold ()
void setPressThreshold (Double pressThreshold)
Double getHumidityThreshold ()
void setHumidityThreshold (Double humidityThreshold)
Double getVibrationThreshold ()
void setVibrationThreshold (Double vibrationThreshold)
boolean isTemperatureOutOfRange ()
boolean isPressureOutOfRange ()
boolean isHumidityOutOfRange ()
boolean isVibrationOutOfRange ()
boolean isAnyParameterOutOfRange ()
Double getTemperatureThreshold ()
void setTemperatureThreshold (Double temperatureThreshold)
Double getPressureThreshold ()
void setPressureThreshold (Double pressureThreshold)
Double getVibrationThreshold ()
void setVibrationThreshold (Double vibrationThreshold)
Private Attributes
Long id
String equipmentCode
String equipmentName
String equipmentType
Integer port
EquipmentStatus status = EquipmentStatus.OFFLINE
String location
String ipAddress
String firmwareVersion
String manufacturer
String model
Double temperature
Double pressure
Double humidity
Double vibration
Integer runtimeHours
Integer cycles
LocalDateTime lastUpdatedTime
Double alertThresholdTemperature
Double alertThresholdPressure
Double alertThresholdHumidity
Double alertThresholdVibration
String maintenanceSchedule
LocalDateTime lastMaintenance
LocalDateTime nextMaintenance
LocalDateTime maintenanceDate
String maintenancePerson
String remark
LocalDateTime createdAt
LocalDateTime updatedAt
Detailed Description
设备监控实体 - 用于跟踪设备状态和性能指标
Author
gmp-system
Definition at line 20 of file EquipmentMonitor.java.
Member Function Documentation
getEquipmentId()
String com.gmp.mes.entity.EquipmentMonitor.getEquipmentId ()
Definition at line 90 of file EquipmentMonitor.java.
getHumidityThreshold()
Double com.gmp.mes.entity.EquipmentMonitor.getHumidityThreshold ()
Definition at line 122 of file EquipmentMonitor.java.
getPressThreshold()
Double com.gmp.mes.entity.EquipmentMonitor.getPressThreshold ()
Definition at line 114 of file EquipmentMonitor.java.
getPressureThreshold()
Double com.gmp.mes.entity.EquipmentMonitor.getPressureThreshold ()
Definition at line 177 of file EquipmentMonitor.java.
getTemperatureThreshold()
Double com.gmp.mes.entity.EquipmentMonitor.getTemperatureThreshold ()
Definition at line 169 of file EquipmentMonitor.java.
getTempThreshold()
Double com.gmp.mes.entity.EquipmentMonitor.getTempThreshold ()
Definition at line 106 of file EquipmentMonitor.java.
getType()
String com.gmp.mes.entity.EquipmentMonitor.getType ()
Definition at line 98 of file EquipmentMonitor.java.
getVibrationThreshold() [1/2]
Double com.gmp.mes.entity.EquipmentMonitor.getVibrationThreshold ()
Definition at line 130 of file EquipmentMonitor.java.
getVibrationThreshold() [2/2]
Double com.gmp.mes.entity.EquipmentMonitor.getVibrationThreshold ()
Definition at line 185 of file EquipmentMonitor.java.
isAnyParameterOutOfRange()
boolean com.gmp.mes.entity.EquipmentMonitor.isAnyParameterOutOfRange ()
Definition at line 163 of file EquipmentMonitor.java.
Referenced by com.gmp.mes.entity.EquipmentMonitorTest.testIsAnyParameterOutOfRange().
isHumidityOutOfRange()
boolean com.gmp.mes.entity.EquipmentMonitor.isHumidityOutOfRange ()
Definition at line 151 of file EquipmentMonitor.java.
Referenced by com.gmp.mes.entity.EquipmentMonitorTest.testIsHumidityOutOfRange().
isPressureOutOfRange()
boolean com.gmp.mes.entity.EquipmentMonitor.isPressureOutOfRange ()
Definition at line 145 of file EquipmentMonitor.java.
Referenced by com.gmp.mes.entity.EquipmentMonitorTest.testIsPressureOutOfRange().
isTemperatureOutOfRange()
boolean com.gmp.mes.entity.EquipmentMonitor.isTemperatureOutOfRange ()
Definition at line 139 of file EquipmentMonitor.java.
Referenced by com.gmp.mes.entity.EquipmentMonitorTest.testIsTemperatureOutOfRange().
isVibrationOutOfRange()
boolean com.gmp.mes.entity.EquipmentMonitor.isVibrationOutOfRange ()
Definition at line 157 of file EquipmentMonitor.java.
Referenced by com.gmp.mes.entity.EquipmentMonitorTest.testIsVibrationOutOfRange().
setEquipmentId()
void com.gmp.mes.entity.EquipmentMonitor.setEquipmentId (String equipmentId)
Definition at line 94 of file EquipmentMonitor.java.
setHumidityThreshold()
void com.gmp.mes.entity.EquipmentMonitor.setHumidityThreshold (Double humidityThreshold)
Definition at line 126 of file EquipmentMonitor.java.
setPressThreshold()
void com.gmp.mes.entity.EquipmentMonitor.setPressThreshold (Double pressThreshold)
Definition at line 118 of file EquipmentMonitor.java.
setPressureThreshold()
void com.gmp.mes.entity.EquipmentMonitor.setPressureThreshold (Double pressureThreshold)
Definition at line 181 of file EquipmentMonitor.java.
setTemperatureThreshold()
void com.gmp.mes.entity.EquipmentMonitor.setTemperatureThreshold (Double temperatureThreshold)
Definition at line 173 of file EquipmentMonitor.java.
setTempThreshold()
void com.gmp.mes.entity.EquipmentMonitor.setTempThreshold (Double tempThreshold)
Definition at line 110 of file EquipmentMonitor.java.
setType()
void com.gmp.mes.entity.EquipmentMonitor.setType (String type)
Definition at line 102 of file EquipmentMonitor.java.
setVibrationThreshold() [1/2]
void com.gmp.mes.entity.EquipmentMonitor.setVibrationThreshold (Double vibrationThreshold)
Definition at line 134 of file EquipmentMonitor.java.
setVibrationThreshold() [2/2]
void com.gmp.mes.entity.EquipmentMonitor.setVibrationThreshold (Double vibrationThreshold)
Definition at line 189 of file EquipmentMonitor.java.
Member Data Documentation
alertThresholdHumidity
Double com.gmp.mes.entity.EquipmentMonitor.alertThresholdHumidity private
Definition at line 59 of file EquipmentMonitor.java.
alertThresholdPressure
Double com.gmp.mes.entity.EquipmentMonitor.alertThresholdPressure private
Definition at line 58 of file EquipmentMonitor.java.
alertThresholdTemperature
Double com.gmp.mes.entity.EquipmentMonitor.alertThresholdTemperature private
Definition at line 57 of file EquipmentMonitor.java.
alertThresholdVibration
Double com.gmp.mes.entity.EquipmentMonitor.alertThresholdVibration private
Definition at line 60 of file EquipmentMonitor.java.
createdAt
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.createdAt private
Definition at line 72 of file EquipmentMonitor.java.
cycles
Integer com.gmp.mes.entity.EquipmentMonitor.cycles private
Definition at line 53 of file EquipmentMonitor.java.
equipmentCode
String com.gmp.mes.entity.EquipmentMonitor.equipmentCode private
Definition at line 27 of file EquipmentMonitor.java.
equipmentName
String com.gmp.mes.entity.EquipmentMonitor.equipmentName private
Definition at line 30 of file EquipmentMonitor.java.
equipmentType
String com.gmp.mes.entity.EquipmentMonitor.equipmentType private
Definition at line 33 of file EquipmentMonitor.java.
firmwareVersion
String com.gmp.mes.entity.EquipmentMonitor.firmwareVersion private
Definition at line 43 of file EquipmentMonitor.java.
humidity
Double com.gmp.mes.entity.EquipmentMonitor.humidity private
Definition at line 50 of file EquipmentMonitor.java.
id
Long com.gmp.mes.entity.EquipmentMonitor.id private
Definition at line 24 of file EquipmentMonitor.java.
ipAddress
String com.gmp.mes.entity.EquipmentMonitor.ipAddress private
Definition at line 42 of file EquipmentMonitor.java.
lastMaintenance
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.lastMaintenance private
Definition at line 64 of file EquipmentMonitor.java.
lastUpdatedTime
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.lastUpdatedTime private
Definition at line 54 of file EquipmentMonitor.java.
location
String com.gmp.mes.entity.EquipmentMonitor.location private
Definition at line 41 of file EquipmentMonitor.java.
maintenanceDate
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.maintenanceDate private
Definition at line 66 of file EquipmentMonitor.java.
maintenancePerson
String com.gmp.mes.entity.EquipmentMonitor.maintenancePerson private
Definition at line 67 of file EquipmentMonitor.java.
maintenanceSchedule
String com.gmp.mes.entity.EquipmentMonitor.maintenanceSchedule private
Definition at line 63 of file EquipmentMonitor.java.
manufacturer
String com.gmp.mes.entity.EquipmentMonitor.manufacturer private
Definition at line 44 of file EquipmentMonitor.java.
model
String com.gmp.mes.entity.EquipmentMonitor.model private
Definition at line 45 of file EquipmentMonitor.java.
nextMaintenance
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.nextMaintenance private
Definition at line 65 of file EquipmentMonitor.java.
port
Integer com.gmp.mes.entity.EquipmentMonitor.port private
Definition at line 36 of file EquipmentMonitor.java.
pressure
Double com.gmp.mes.entity.EquipmentMonitor.pressure private
Definition at line 49 of file EquipmentMonitor.java.
remark
String com.gmp.mes.entity.EquipmentMonitor.remark private
Definition at line 68 of file EquipmentMonitor.java.
runtimeHours
Integer com.gmp.mes.entity.EquipmentMonitor.runtimeHours private
Definition at line 52 of file EquipmentMonitor.java.
status
EquipmentStatus com.gmp.mes.entity.EquipmentMonitor.status = EquipmentStatus.OFFLINE private
Definition at line 39 of file EquipmentMonitor.java.
temperature
Double com.gmp.mes.entity.EquipmentMonitor.temperature private
Definition at line 48 of file EquipmentMonitor.java.
updatedAt
LocalDateTime com.gmp.mes.entity.EquipmentMonitor.updatedAt private
Definition at line 75 of file EquipmentMonitor.java.
vibration
Double com.gmp.mes.entity.EquipmentMonitor.vibration private
Definition at line 51 of file EquipmentMonitor.java.
The documentation for this class was generated from the following file:
mes-service/src/main/java/com/gmp/mes/entity/EquipmentMonitor.java