GMP系统: com.gmp.hr.mapper.DepartmentMapperImpl Class Reference
com.gmp.hr.mapper.DepartmentMapperImpl Class Reference
Public Member Functions
DepartmentDTO toDTO (Department department)
将部门实体转换为DTO
Department toEntity (DepartmentDTO dto)
将部门DTO转换为实体
List< DepartmentDTO > toDTOList (List< Department > departments)
将部门实体列表转换为DTO列表
Department updateEntityFromDTO (DepartmentDTO dto, Department entity)
更新部门实体
Public Attributes
DepartmentMapper INSTANCE = Mappers.getMapper(DepartmentMapper.class)
Protected Member Functions
List< DepartmentDTO > departmentSetToDepartmentDTOList (Set< Department > set)
Private Member Functions
Long departmentParentId (Department department)
String departmentParentDepartmentName (Department department)
Long departmentManagerId (Department department)
String departmentManagerName (Department department)
Detailed Description
Definition at line 18 of file DepartmentMapperImpl.java.
Member Function Documentation
departmentManagerId()
Long com.gmp.hr.mapper.DepartmentMapperImpl.departmentManagerId (Department department) private
Definition at line 123 of file DepartmentMapperImpl.java.
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
departmentManagerName()
String com.gmp.hr.mapper.DepartmentMapperImpl.departmentManagerName (Department department) private
Definition at line 138 of file DepartmentMapperImpl.java.
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
departmentParentDepartmentName()
String com.gmp.hr.mapper.DepartmentMapperImpl.departmentParentDepartmentName (Department department) private
Definition at line 108 of file DepartmentMapperImpl.java.
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
departmentParentId()
Long com.gmp.hr.mapper.DepartmentMapperImpl.departmentParentId (Department department) private
Definition at line 93 of file DepartmentMapperImpl.java.
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
departmentSetToDepartmentDTOList()
List< DepartmentDTO > com.gmp.hr.mapper.DepartmentMapperImpl.departmentSetToDepartmentDTOList (Set< Department > set) protected
Definition at line 153 of file DepartmentMapperImpl.java.
References com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
toDTO()
DepartmentDTO com.gmp.hr.mapper.DepartmentMapperImpl.toDTO (Department department)
将部门实体转换为DTO
Parameters
department 部门实体
Returns
部门DTO
Implements com.gmp.hr.mapper.DepartmentMapper.
Definition at line 21 of file DepartmentMapperImpl.java.
References com.gmp.hr.mapper.DepartmentMapperImpl.departmentManagerId(), com.gmp.hr.mapper.DepartmentMapperImpl.departmentManagerName(), com.gmp.hr.mapper.DepartmentMapperImpl.departmentParentDepartmentName(), com.gmp.hr.mapper.DepartmentMapperImpl.departmentParentId(), and com.gmp.hr.mapper.DepartmentMapperImpl.departmentSetToDepartmentDTOList().
Referenced by com.gmp.hr.mapper.DepartmentMapperImpl.departmentSetToDepartmentDTOList(), and com.gmp.hr.mapper.DepartmentMapperImpl.toDTOList().
toDTOList()
List< DepartmentDTO > com.gmp.hr.mapper.DepartmentMapperImpl.toDTOList (List< Department > departments)
将部门实体列表转换为DTO列表
Parameters
departments 部门实体列表
Returns
部门DTO列表
Implements com.gmp.hr.mapper.DepartmentMapper.
Definition at line 62 of file DepartmentMapperImpl.java.
References com.gmp.hr.mapper.DepartmentMapperImpl.toDTO().
toEntity()
Department com.gmp.hr.mapper.DepartmentMapperImpl.toEntity (DepartmentDTO dto)
将部门DTO转换为实体
Parameters
dto 部门DTO
Returns
部门实体
Implements com.gmp.hr.mapper.DepartmentMapper.
Definition at line 46 of file DepartmentMapperImpl.java.
updateEntityFromDTO()
Department com.gmp.hr.mapper.DepartmentMapperImpl.updateEntityFromDTO (DepartmentDTO dto, Department entity)
更新部门实体
Parameters
dto 部门DTO
entity 部门实体
Returns
更新后的部门实体
Implements com.gmp.hr.mapper.DepartmentMapper.
Definition at line 76 of file DepartmentMapperImpl.java.
Member Data Documentation
INSTANCE
DepartmentMapper com.gmp.hr.mapper.DepartmentMapper.INSTANCE = Mappers.getMapper(DepartmentMapper.class) inherited
Definition at line 21 of file DepartmentMapper.java.
The documentation for this class was generated from the following file:
hr-service/target/generated-sources/annotations/com/gmp/hr/mapper/DepartmentMapperImpl.java