GMP系统: com.gmp.qms.config.McpMessageQueueConfig Class Reference
com.gmp.qms.config.McpMessageQueueConfig Class Reference
MCP消息队列配置，实现系统间的异步通信机制
Public Member Functions
DirectExchange gmpMcpExchange ()
创建主交换机
Queue qmsToEdmsQueue ()
创建QMS到EDMS的队列
Queue qmsToMesQueue ()
创建QMS到MES的队列
Queue qmsToLimsQueue ()
创建QMS到LIMS的队列
Queue qmsToErpQueue ()
创建QMS到ERP的队列
Queue qmsToTrainingQueue ()
创建QMS到培训系统的队列
Queue qmsToEquipmentQueue ()
创建QMS到设备系统的队列
Declarables bindings ()
绑定所有队列到交换机
Jackson2JsonMessageConverter messageConverter ()
配置消息转换器
RabbitTemplate rabbitTemplate (ConnectionFactory connectionFactory)
配置RabbitTemplate
SimpleRabbitListenerContainerFactory rabbitListenerContainerFactory (ConnectionFactory connectionFactory)
配置消息监听器容器工厂
Static Public Attributes
static final String QMS_TO_EDMS_QUEUE = "gmp.qms.to.edms.queue"
static final String QMS_TO_MES_QUEUE = "gmp.qms.to.mes.queue"
static final String QMS_TO_LIMS_QUEUE = "gmp.qms.to.lims.queue"
static final String QMS_TO_ERP_QUEUE = "gmp.qms.to.erp.queue"
static final String QMS_TO_TRAINING_QUEUE = "gmp.qms.to.training.queue"
static final String QMS_TO_EQUIPMENT_QUEUE = "gmp.qms.to.equipment.queue"
static final String GMP_MCP_EXCHANGE = "gmp.mcp.exchange"
static final String ROUTING_KEY_PREFIX = "gmp.mcp."
Private Attributes
McpPerformanceConfig performanceConfig
Detailed Description
MCP消息队列配置，实现系统间的异步通信机制
Author
GMP系统开发团队
Definition at line 17 of file McpMessageQueueConfig.java.
Member Function Documentation
bindings()
Declarables com.gmp.qms.config.McpMessageQueueConfig.bindings ()
绑定所有队列到交换机
Definition at line 132 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.gmpMcpExchange(), com.gmp.qms.config.McpMessageQueueConfig.qmsToEdmsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToEquipmentQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToErpQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToLimsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToMesQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToTrainingQueue(), and com.gmp.qms.config.McpMessageQueueConfig.ROUTING_KEY_PREFIX.
gmpMcpExchange()
DirectExchange com.gmp.qms.config.McpMessageQueueConfig.gmpMcpExchange ()
创建主交换机
Definition at line 40 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
messageConverter()
Jackson2JsonMessageConverter com.gmp.qms.config.McpMessageQueueConfig.messageConverter ()
配置消息转换器
Definition at line 147 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.rabbitListenerContainerFactory(), and com.gmp.qms.config.McpMessageQueueConfig.rabbitTemplate().
qmsToEdmsQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToEdmsQueue ()
创建QMS到EDMS的队列
Definition at line 48 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_EDMS_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
qmsToEquipmentQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToEquipmentQueue ()
创建QMS到设备系统的队列
Definition at line 118 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_EQUIPMENT_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
qmsToErpQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToErpQueue ()
创建QMS到ERP的队列
Definition at line 90 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_ERP_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
qmsToLimsQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToLimsQueue ()
创建QMS到LIMS的队列
Definition at line 76 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_LIMS_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
qmsToMesQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToMesQueue ()
创建QMS到MES的队列
Definition at line 62 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_MES_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
qmsToTrainingQueue()
Queue com.gmp.qms.config.McpMessageQueueConfig.qmsToTrainingQueue ()
创建QMS到培训系统的队列
Definition at line 104 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE, com.gmp.qms.config.McpMessageQueueConfig.performanceConfig, and com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_TRAINING_QUEUE.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
rabbitListenerContainerFactory()
SimpleRabbitListenerContainerFactory com.gmp.qms.config.McpMessageQueueConfig.rabbitListenerContainerFactory (ConnectionFactory connectionFactory)
配置消息监听器容器工厂
Definition at line 175 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.messageConverter(), and com.gmp.qms.config.McpMessageQueueConfig.performanceConfig.
rabbitTemplate()
RabbitTemplate com.gmp.qms.config.McpMessageQueueConfig.rabbitTemplate (ConnectionFactory connectionFactory)
配置RabbitTemplate
Definition at line 155 of file McpMessageQueueConfig.java.
References com.gmp.qms.config.McpMessageQueueConfig.messageConverter().
Member Data Documentation
GMP_MCP_EXCHANGE
final String com.gmp.qms.config.McpMessageQueueConfig.GMP_MCP_EXCHANGE = "gmp.mcp.exchange" static
Definition at line 31 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.gmpMcpExchange(), com.gmp.qms.config.McpMessageQueueConfig.qmsToEdmsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToEquipmentQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToErpQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToLimsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToMesQueue(), and com.gmp.qms.config.McpMessageQueueConfig.qmsToTrainingQueue().
performanceConfig
McpPerformanceConfig com.gmp.qms.config.McpMessageQueueConfig.performanceConfig private
Definition at line 20 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToEdmsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToEquipmentQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToErpQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToLimsQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToMesQueue(), com.gmp.qms.config.McpMessageQueueConfig.qmsToTrainingQueue(), and com.gmp.qms.config.McpMessageQueueConfig.rabbitListenerContainerFactory().
QMS_TO_EDMS_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_EDMS_QUEUE = "gmp.qms.to.edms.queue" static
Definition at line 23 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToEdmsQueue().
QMS_TO_EQUIPMENT_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_EQUIPMENT_QUEUE = "gmp.qms.to.equipment.queue" static
Definition at line 28 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToEquipmentQueue().
QMS_TO_ERP_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_ERP_QUEUE = "gmp.qms.to.erp.queue" static
Definition at line 26 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToErpQueue().
QMS_TO_LIMS_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_LIMS_QUEUE = "gmp.qms.to.lims.queue" static
Definition at line 25 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToLimsQueue().
QMS_TO_MES_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_MES_QUEUE = "gmp.qms.to.mes.queue" static
Definition at line 24 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToMesQueue().
QMS_TO_TRAINING_QUEUE
final String com.gmp.qms.config.McpMessageQueueConfig.QMS_TO_TRAINING_QUEUE = "gmp.qms.to.training.queue" static
Definition at line 27 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.qmsToTrainingQueue().
ROUTING_KEY_PREFIX
final String com.gmp.qms.config.McpMessageQueueConfig.ROUTING_KEY_PREFIX = "gmp.mcp." static
Definition at line 34 of file McpMessageQueueConfig.java.
Referenced by com.gmp.qms.config.McpMessageQueueConfig.bindings().
The documentation for this class was generated from the following file:
qms-service/src/main/java/com/gmp/qms/config/McpMessageQueueConfig.java