GMP系统: com.gmp.auth.entity.Organization.OrganizationType Enum Reference
com.gmp.auth.entity.Organization.OrganizationType Enum Reference
组织类型枚举 - 定义GMP企业常见的组织架构类型
Public Member Functions
OrganizationType (String description)
String getDescription ()
Public Attributes
DEPARTMENT =("部门管理")
PRODUCTION =("生产管理")
QUALITY =("质量管理")
COMPLIANCE =("合规审核")
TRAINING =("培训管理")
HR =("人力资源")
IT =("信息技术")
MAINTENANCE =("设备维护")
LOGISTICS =("后勤保障")
SAFETY =("安全环保")
Private Attributes
final String description
Detailed Description
组织类型枚举 - 定义GMP企业常见的组织架构类型
Definition at line 140 of file Organization.java.
Constructor & Destructor Documentation
OrganizationType()
com.gmp.auth.entity.Organization.OrganizationType.OrganizationType (String description)
Definition at line 154 of file Organization.java.
Member Function Documentation
getDescription()
String com.gmp.auth.entity.Organization.OrganizationType.getDescription ()
Definition at line 158 of file Organization.java.
Member Data Documentation
COMPLIANCE
com.gmp.auth.entity.Organization.OrganizationType.COMPLIANCE =("合规审核")
Definition at line 144 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization().
DEPARTMENT
com.gmp.auth.entity.Organization.OrganizationType.DEPARTMENT =("部门管理")
Definition at line 141 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGmpCompliance(), com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization(), com.gmp.auth.entity.OrganizationTest.testOrganizationCreation(), and com.gmp.auth.entity.OrganizationTest.testOrganizationTypeEnum().
description
final String com.gmp.auth.entity.Organization.OrganizationType.description private
Definition at line 152 of file Organization.java.
HR
com.gmp.auth.entity.Organization.OrganizationType.HR =("人力资源")
Definition at line 146 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization().
IT
com.gmp.auth.entity.Organization.OrganizationType.IT =("信息技术")
Definition at line 147 of file Organization.java.
LOGISTICS
com.gmp.auth.entity.Organization.OrganizationType.LOGISTICS =("后勤保障")
Definition at line 149 of file Organization.java.
MAINTENANCE
com.gmp.auth.entity.Organization.OrganizationType.MAINTENANCE =("设备维护")
Definition at line 148 of file Organization.java.
PRODUCTION
com.gmp.auth.entity.Organization.OrganizationType.PRODUCTION =("生产管理")
Definition at line 142 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization(), and com.gmp.auth.entity.OrganizationTest.testOrganizationTypeEnum().
QUALITY
com.gmp.auth.entity.Organization.OrganizationType.QUALITY =("质量管理")
Definition at line 143 of file Organization.java.
Referenced by com.gmp.auth.entity.OrganizationTest.testGmpCompliance(), com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization(), and com.gmp.auth.entity.OrganizationTest.testOrganizationTypeEnum().
SAFETY
com.gmp.auth.entity.Organization.OrganizationType.SAFETY =("安全环保")
Definition at line 150 of file Organization.java.
TRAINING
com.gmp.auth.entity.Organization.OrganizationType.TRAINING =("培训管理")
Definition at line 145 of file Organization.java.
Referenced by com.gmp.auth.entity.Organization.isGmpOrganization(), and com.gmp.auth.entity.OrganizationTest.testIsGmpOrganization().
The documentation for this enum was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/Organization.java