GMP系统: com.gmp.edms.service.DocumentPermissionService.PermissionType Enum Reference
com.gmp.edms.service.DocumentPermissionService.PermissionType Enum Reference
权限类型枚举
Public Member Functions
PermissionType (String description)
String getDescription ()
Public Attributes
VIEW =("查看")
EDIT =("编辑")
DELETE =("删除")
DOWNLOAD =("下载")
APPROVE =("审批")
PUBLISH =("发布")
WITHDRAW =("撤回")
SHARE =("分享")
PRINT =("打印")
COPY =("复制")
Private Attributes
final String description
Detailed Description
权限类型枚举
Definition at line 119 of file DocumentPermissionService.java.
Constructor & Destructor Documentation
PermissionType()
com.gmp.edms.service.DocumentPermissionService.PermissionType.PermissionType (String description)
Definition at line 133 of file DocumentPermissionService.java.
Member Function Documentation
getDescription()
String com.gmp.edms.service.DocumentPermissionService.PermissionType.getDescription ()
Definition at line 137 of file DocumentPermissionService.java.
Member Data Documentation
APPROVE
com.gmp.edms.service.DocumentPermissionService.PermissionType.APPROVE =("审批")
Definition at line 124 of file DocumentPermissionService.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canApprove().
COPY
com.gmp.edms.service.DocumentPermissionService.PermissionType.COPY =("复制")
Definition at line 129 of file DocumentPermissionService.java.
DELETE
com.gmp.edms.service.DocumentPermissionService.PermissionType.DELETE =("删除")
Definition at line 122 of file DocumentPermissionService.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDelete().
description
final String com.gmp.edms.service.DocumentPermissionService.PermissionType.description private
Definition at line 131 of file DocumentPermissionService.java.
DOWNLOAD
com.gmp.edms.service.DocumentPermissionService.PermissionType.DOWNLOAD =("下载")
Definition at line 123 of file DocumentPermissionService.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canDownload().
EDIT
com.gmp.edms.service.DocumentPermissionService.PermissionType.EDIT =("编辑")
Definition at line 121 of file DocumentPermissionService.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canEdit(), and com.gmp.edms.service.impl.DocumentPermissionServiceImpl.hasCreatePermission().
PRINT
com.gmp.edms.service.DocumentPermissionService.PermissionType.PRINT =("打印")
Definition at line 128 of file DocumentPermissionService.java.
PUBLISH
com.gmp.edms.service.DocumentPermissionService.PermissionType.PUBLISH =("发布")
Definition at line 125 of file DocumentPermissionService.java.
SHARE
com.gmp.edms.service.DocumentPermissionService.PermissionType.SHARE =("分享")
Definition at line 127 of file DocumentPermissionService.java.
VIEW
com.gmp.edms.service.DocumentPermissionService.PermissionType.VIEW =("查看")
Definition at line 120 of file DocumentPermissionService.java.
Referenced by com.gmp.edms.service.impl.DocumentPermissionServiceImpl.canView().
WITHDRAW
com.gmp.edms.service.DocumentPermissionService.PermissionType.WITHDRAW =("撤回")
Definition at line 126 of file DocumentPermissionService.java.
The documentation for this enum was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/DocumentPermissionService.java