GMP系统: com.gmp.auth.entity.OperationLog.Module Enum Reference
com.gmp.auth.entity.OperationLog.Module Enum Reference
模块枚举
Public Member Functions
Module (String description)
String getDescription ()
Public Attributes
AUTH =("认证模块")
USER =("用户管理")
ROLE =("角色管理")
PERMISSION =("权限管理")
SYSTEM =("系统管理")
Private Attributes
final String description
Detailed Description
模块枚举
Definition at line 374 of file OperationLog.java.
Constructor & Destructor Documentation
Module()
com.gmp.auth.entity.OperationLog.Module.Module (String description)
Definition at line 383 of file OperationLog.java.
Member Function Documentation
getDescription()
String com.gmp.auth.entity.OperationLog.Module.getDescription ()
Definition at line 387 of file OperationLog.java.
Member Data Documentation
AUTH
com.gmp.auth.entity.OperationLog.Module.AUTH =("认证模块")
Definition at line 375 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLoginLog(), and com.gmp.auth.entity.OperationLog.createLogoutLog().
description
final String com.gmp.auth.entity.OperationLog.Module.description private
Definition at line 381 of file OperationLog.java.
PERMISSION
com.gmp.auth.entity.OperationLog.Module.PERMISSION =("权限管理")
Definition at line 378 of file OperationLog.java.
ROLE
com.gmp.auth.entity.OperationLog.Module.ROLE =("角色管理")
Definition at line 377 of file OperationLog.java.
SYSTEM
com.gmp.auth.entity.OperationLog.Module.SYSTEM =("系统管理")
Definition at line 379 of file OperationLog.java.
USER
com.gmp.auth.entity.OperationLog.Module.USER =("用户管理")
Definition at line 376 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createUserOperationLog().
The documentation for this enum was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/OperationLog.java