GMP系统: com.gmp.auth.entity.OperationLog.OperationType Enum Reference
com.gmp.auth.entity.OperationLog.OperationType Enum Reference
操作类型枚举
Public Member Functions
OperationType (String description)
构造函数
String getDescription ()
获取操作类型描述
Public Attributes
LOGIN =("用户登录")
用户登录
LOGOUT =("用户登出")
用户登出
USER_CREATE =("创建用户")
创建用户
USER_UPDATE =("更新用户")
更新用户
USER_DELETE =("删除用户")
删除用户
USER_STATUS_CHANGE =("用户状态变更")
用户状态变更
ROLE_ASSIGN =("分配角色")
分配角色
ROLE_REVOKE =("撤销角色")
撤销角色
ROLE_PERMISSION_CHANGE =("角色权限变更")
角色权限变更
PERMISSION_CHANGE =("权限变更")
权限变更
SYSTEM_CONFIG =("系统配置")
系统配置
AUDIT_REVIEW =("审计审查")
审计审查
Private Attributes
final String description
操作类型描述
Detailed Description
操作类型枚举
定义了系统支持的各种操作类型
Definition at line 445 of file OperationLog.java.
Constructor & Destructor Documentation
OperationType()
com.gmp.auth.entity.OperationLog.OperationType.OperationType (String description)
构造函数
Parameters
description 操作类型描述
Definition at line 540 of file OperationLog.java.
Member Function Documentation
getDescription()
String com.gmp.auth.entity.OperationLog.OperationType.getDescription ()
获取操作类型描述
Returns
String 操作类型描述
Definition at line 549 of file OperationLog.java.
Member Data Documentation
AUDIT_REVIEW
com.gmp.auth.entity.OperationLog.OperationType.AUDIT_REVIEW =("审计审查")
审计审查
审查系统审计日志
Definition at line 528 of file OperationLog.java.
description
final String com.gmp.auth.entity.OperationLog.OperationType.description private
操作类型描述
Definition at line 533 of file OperationLog.java.
LOGIN
com.gmp.auth.entity.OperationLog.OperationType.LOGIN =("用户登录")
用户登录
用户登录系统
Definition at line 451 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLoginLog(), and com.gmp.auth.entity.OperationLogTest.testOperationLogEnums().
LOGOUT
com.gmp.auth.entity.OperationLog.OperationType.LOGOUT =("用户登出")
用户登出
用户退出系统
Definition at line 458 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLogoutLog(), and com.gmp.auth.entity.OperationLogTest.testOperationLogEnums().
PERMISSION_CHANGE
com.gmp.auth.entity.OperationLog.OperationType.PERMISSION_CHANGE =("权限变更")
权限变更
变更权限设置
Definition at line 514 of file OperationLog.java.
ROLE_ASSIGN
com.gmp.auth.entity.OperationLog.OperationType.ROLE_ASSIGN =("分配角色")
分配角色
为用户分配角色
Definition at line 493 of file OperationLog.java.
ROLE_PERMISSION_CHANGE
com.gmp.auth.entity.OperationLog.OperationType.ROLE_PERMISSION_CHANGE =("角色权限变更")
角色权限变更
变更角色的权限
Definition at line 507 of file OperationLog.java.
ROLE_REVOKE
com.gmp.auth.entity.OperationLog.OperationType.ROLE_REVOKE =("撤销角色")
撤销角色
撤销用户的角色
Definition at line 500 of file OperationLog.java.
SYSTEM_CONFIG
com.gmp.auth.entity.OperationLog.OperationType.SYSTEM_CONFIG =("系统配置")
系统配置
变更系统配置
Definition at line 521 of file OperationLog.java.
USER_CREATE
com.gmp.auth.entity.OperationLog.OperationType.USER_CREATE =("创建用户")
创建用户
创建新用户
Definition at line 465 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLogTest.testOperationLogEnums().
USER_DELETE
com.gmp.auth.entity.OperationLog.OperationType.USER_DELETE =("删除用户")
删除用户
删除用户
Definition at line 479 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLogTest.testCreateUserOperationLogFailure().
USER_STATUS_CHANGE
com.gmp.auth.entity.OperationLog.OperationType.USER_STATUS_CHANGE =("用户状态变更")
用户状态变更
变更用户状态
Definition at line 486 of file OperationLog.java.
USER_UPDATE
com.gmp.auth.entity.OperationLog.OperationType.USER_UPDATE =("更新用户")
更新用户
更新现有用户信息
Definition at line 472 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLogTest.testCreateUserOperationLog().
The documentation for this enum was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/OperationLog.java