GMP系统: com.gmp.equipment.entity.Equipment.EquipmentStatus Enum Reference
com.gmp.equipment.entity.Equipment.EquipmentStatus Enum Reference
设备状态枚举（生命周期状态）
Public Member Functions
EquipmentStatus (String description)
String getDescription ()
Public Attributes
ACTIVE =("正常运行")
INACTIVE =("未激活")
MAINTENANCE =("维护中")
CALIBRATION =("校准中")
LOCKED =("已锁定")
DECOMMISSIONED =("已退役")
Private Attributes
final String description
Detailed Description
设备状态枚举（生命周期状态）
Definition at line 224 of file Equipment.java.
Constructor & Destructor Documentation
EquipmentStatus()
com.gmp.equipment.entity.Equipment.EquipmentStatus.EquipmentStatus (String description)
Definition at line 234 of file Equipment.java.
Member Function Documentation
getDescription()
String com.gmp.equipment.entity.Equipment.EquipmentStatus.getDescription ()
Definition at line 238 of file Equipment.java.
Member Data Documentation
ACTIVE
com.gmp.equipment.entity.Equipment.EquipmentStatus.ACTIVE =("正常运行")
Definition at line 225 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testCriticalEquipmentManagement(), com.gmp.equipment.entity.EquipmentTest.testEquipmentCreation(), com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), com.gmp.equipment.entity.EquipmentTest.testEquipmentStatusEnum(), and com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
CALIBRATION
com.gmp.equipment.entity.Equipment.EquipmentStatus.CALIBRATION =("校准中")
Definition at line 228 of file Equipment.java.
DECOMMISSIONED
com.gmp.equipment.entity.Equipment.EquipmentStatus.DECOMMISSIONED =("已退役")
Definition at line 230 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), and com.gmp.equipment.entity.EquipmentTest.testEquipmentStatusEnum().
description
final String com.gmp.equipment.entity.Equipment.EquipmentStatus.description private
Definition at line 232 of file Equipment.java.
INACTIVE
com.gmp.equipment.entity.Equipment.EquipmentStatus.INACTIVE =("未激活")
Definition at line 226 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement().
LOCKED
com.gmp.equipment.entity.Equipment.EquipmentStatus.LOCKED =("已锁定")
Definition at line 229 of file Equipment.java.
MAINTENANCE
com.gmp.equipment.entity.Equipment.EquipmentStatus.MAINTENANCE =("维护中")
Definition at line 227 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), com.gmp.equipment.entity.EquipmentTest.testEquipmentStatusEnum(), and com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
The documentation for this enum was generated from the following file:
equipment-management/src/main/java/com/gmp/equipment/entity/Equipment.java