GMP系统: com.gmp.auth.entity.User.UserStatus Enum Reference
com.gmp.auth.entity.User.UserStatus Enum Reference
用户状态枚举
Public Member Functions
UserStatus (String description)
构造函数
String getDescription ()
获取状态描述
Public Attributes
ACTIVE =("活跃")
活跃状态
INACTIVE =("未激活")
未激活状态
LOCKED =("锁定")
锁定状态
EXPIRED =("过期")
过期状态
Private Attributes
final String description
状态描述
Detailed Description
用户状态枚举
定义了用户在系统中的各种状态
Definition at line 392 of file User.java.
Constructor & Destructor Documentation
UserStatus()
com.gmp.auth.entity.User.UserStatus.UserStatus (String description)
构造函数
Parameters
description 状态描述
Definition at line 431 of file User.java.
Member Function Documentation
getDescription()
String com.gmp.auth.entity.User.UserStatus.getDescription ()
获取状态描述
Returns
状态描述
Definition at line 440 of file User.java.
Member Data Documentation
ACTIVE
com.gmp.auth.entity.User.UserStatus.ACTIVE =("活跃")
活跃状态
用户可以正常登录和使用系统
Definition at line 398 of file User.java.
Referenced by com.gmp.auth.entity.User.isActive(), com.gmp.auth.entity.User.setExpired(), com.gmp.auth.entity.User.setLocked(), com.gmp.auth.entity.UserTest.testAccountLocking(), com.gmp.auth.entity.UserTest.testLockedUserDetection(), com.gmp.auth.entity.UserTest.testUserCreation(), com.gmp.auth.entity.UserTest.testUserStatusEnum(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
description
final String com.gmp.auth.entity.User.UserStatus.description private
状态描述
Definition at line 424 of file User.java.
EXPIRED
com.gmp.auth.entity.User.UserStatus.EXPIRED =("过期")
过期状态
用户账户已过期，无法登录系统
Definition at line 419 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testUserStatusEnum(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
INACTIVE
com.gmp.auth.entity.User.UserStatus.INACTIVE =("未激活")
未激活状态
用户尚未激活，无法登录系统
Definition at line 405 of file User.java.
Referenced by com.gmp.auth.entity.User.setActive(), com.gmp.auth.entity.UserTest.testUserStatusEnum(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
LOCKED
com.gmp.auth.entity.User.UserStatus.LOCKED =("锁定")
锁定状态
用户因多次登录失败或其他原因被锁定，无法登录系统
Definition at line 412 of file User.java.
Referenced by com.gmp.auth.entity.UserTest.testAccountLocking(), com.gmp.auth.entity.UserTest.testLockedUserDetection(), com.gmp.auth.entity.UserTest.testUserStatusEnum(), and com.gmp.auth.entity.UserTest.testUserStatusValidation().
The documentation for this enum was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/User.java