GMP系统: com.gmp.auth.entity.OperationLog.Result Enum Reference
com.gmp.auth.entity.OperationLog.Result Enum Reference
操作结果枚举
Public Member Functions
Result (String description)
String getDescription ()
Public Attributes
SUCCESS =("成功")
FAILED =("失败")
Private Attributes
final String description
Detailed Description
操作结果枚举
Definition at line 321 of file OperationLog.java.
Constructor & Destructor Documentation
Result()
com.gmp.auth.entity.OperationLog.Result.Result (String description)
Definition at line 327 of file OperationLog.java.
Member Function Documentation
getDescription()
String com.gmp.auth.entity.OperationLog.Result.getDescription ()
Definition at line 331 of file OperationLog.java.
Member Data Documentation
description
final String com.gmp.auth.entity.OperationLog.Result.description private
Definition at line 325 of file OperationLog.java.
FAILED
com.gmp.auth.entity.OperationLog.Result.FAILED =("失败")
Definition at line 323 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLoginLog(), and com.gmp.auth.entity.OperationLog.createUserOperationLog().
SUCCESS
com.gmp.auth.entity.OperationLog.Result.SUCCESS =("成功")
Definition at line 322 of file OperationLog.java.
Referenced by com.gmp.auth.entity.OperationLog.createLoginLog(), com.gmp.auth.entity.OperationLog.createLogoutLog(), com.gmp.auth.entity.OperationLog.createUserOperationLog(), com.gmp.auth.entity.OperationLog.onCreate(), and com.gmp.auth.entity.OperationLog.OperationLog().
The documentation for this enum was generated from the following file:
auth-service/src/main/java/com/gmp/auth/entity/OperationLog.java