GMP系统: com.gmp.equipment.entity.Equipment.OperationalStatus Enum Reference
com.gmp.equipment.entity.Equipment.OperationalStatus Enum Reference
运行状态枚举（当前运行状态）
Public Member Functions
OperationalStatus (String description)
String getDescription ()
Public Attributes
RUNNING =("运行中")
STOPPED =("已停止")
STANDBY =("待机中")
FAULT =("故障")
MAINTENANCE =("维护中")
Private Attributes
final String description
Detailed Description
运行状态枚举（当前运行状态）
Definition at line 246 of file Equipment.java.
Constructor & Destructor Documentation
OperationalStatus()
com.gmp.equipment.entity.Equipment.OperationalStatus.OperationalStatus (String description)
Definition at line 255 of file Equipment.java.
Member Function Documentation
getDescription()
String com.gmp.equipment.entity.Equipment.OperationalStatus.getDescription ()
Definition at line 259 of file Equipment.java.
Member Data Documentation
description
final String com.gmp.equipment.entity.Equipment.OperationalStatus.description private
Definition at line 253 of file Equipment.java.
FAULT
com.gmp.equipment.entity.Equipment.OperationalStatus.FAULT =("故障")
Definition at line 250 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testOperationalStatusEnum().
MAINTENANCE
com.gmp.equipment.entity.Equipment.OperationalStatus.MAINTENANCE =("维护中")
Definition at line 251 of file Equipment.java.
RUNNING
com.gmp.equipment.entity.Equipment.OperationalStatus.RUNNING =("运行中")
Definition at line 247 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsRunnable(), and com.gmp.equipment.entity.EquipmentTest.testOperationalStatusEnum().
STANDBY
com.gmp.equipment.entity.Equipment.OperationalStatus.STANDBY =("待机中")
Definition at line 249 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
STOPPED
com.gmp.equipment.entity.Equipment.OperationalStatus.STOPPED =("已停止")
Definition at line 248 of file Equipment.java.
Referenced by com.gmp.equipment.entity.EquipmentTest.testEquipmentCreation(), com.gmp.equipment.entity.EquipmentTest.testEquipmentLifecycleManagement(), and com.gmp.equipment.entity.EquipmentTest.testIsRunnable().
The documentation for this enum was generated from the following file:
equipment-management/src/main/java/com/gmp/equipment/entity/Equipment.java