GMP系统: com.gmp.auth.service.UserOrganizationRoleService Interface Reference
com.gmp.auth.service.UserOrganizationRoleService Interface Reference
用户组织角色关联服务接口 管理用户、组织、角色三者之间的关联关系
Public Member Functions
UserOrganizationRole assignRoleToUserInOrganization (Long userId, Long organizationId, Long roleId, Long assignedBy, String assignmentReason, LocalDateTime effectiveUntil)
为用户分配组织角色
List< UserOrganizationRole > assignRolesToUserInOrganizations (Long userId, Map< Long, List< Long > > orgRoleAssignments, Long assignedBy, String assignmentReason)
批量为用户分配组织角色
void removeRoleFromUserInOrganization (Long userId, Long organizationId, Long roleId)
从组织中移除用户角色
List< UserOrganizationRole > getUserOrganizationRoles (Long userId)
获取用户在所有组织中的有效角色
List< UserOrganizationRole > getUserOrganizationRolesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的有效角色
Set< Long > getUserOrganizations (Long userId)
获取用户拥有的所有组织
Set< String > getUserRoleCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的角色代码
Set< String > getUserPermissionCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的权限代码
Set< String > getUserPermissionCodesAcrossOrganizations (Long userId)
获取用户在所有组织中的所有权限
boolean hasRoleInOrganization (Long userId, Long organizationId, String roleCode)
检查用户在指定组织中是否拥有特定角色
boolean hasPermissionInOrganization (Long userId, Long organizationId, String permissionCode)
检查用户在指定组织中是否拥有特定权限
UserOrganizationRole updateStatus (Long id, UserOrganizationRole.AssignmentStatus status, Long updatedBy)
更新用户组织角色状态
UserOrganizationRole approveAssignment (Long id, boolean approved, Long approvedBy, String approvalNote)
审批用户组织角色分配
void refreshExpiredAssignments ()
刷新过期的用户组织角色关联
List< UserOrganizationRole > getExpiringSoonAssignments (int warningDays)
获取即将过期的用户组织角色关联
List< UserOrganizationRole > getOrganizationUserRoles (Long organizationId)
获取组织中的所有用户角色关联
List< UserOrganizationRole > getRoleUserOrganizations (Long roleId)
获取拥有特定角色的所有用户组织关联
boolean hasOrganizationAccess (Long userId, Long organizationId)
检查用户是否有权限访问指定组织
List< String > getUserAccessibleSubsystems (Long userId, Long organizationId)
获取用户可访问的子系统列表
Map< String, Integer > getUserSubsystemAccessLevels (Long userId, Long organizationId)
获取用户子系统访问级别
Detailed Description
用户组织角色关联服务接口 管理用户、组织、角色三者之间的关联关系
Definition at line 16 of file UserOrganizationRoleService.java.
Member Function Documentation
approveAssignment()
UserOrganizationRole com.gmp.auth.service.UserOrganizationRoleService.approveAssignment (Long id, boolean approved, Long approvedBy, String approvalNote)
审批用户组织角色分配
Parameters
id 关联ID
approved 是否批准
approvedBy 审批人ID
approvalNote 审批意见
Returns
更新后的关联实体
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
assignRolesToUserInOrganizations()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.assignRolesToUserInOrganizations (Long userId, Map< Long, List< Long > > orgRoleAssignments, Long assignedBy, String assignmentReason)
批量为用户分配组织角色
Parameters
userId 用户ID
orgRoleAssignments 组织角色分配映射
assignedBy 分配人ID
assignmentReason 分配理由
Returns
创建的关联实体列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
assignRoleToUserInOrganization()
UserOrganizationRole com.gmp.auth.service.UserOrganizationRoleService.assignRoleToUserInOrganization (Long userId, Long organizationId, Long roleId, Long assignedBy, String assignmentReason, LocalDateTime effectiveUntil)
为用户分配组织角色
Parameters
userId 用户ID
organizationId 组织ID
roleId 角色ID
assignedBy 分配人ID
assignmentReason 分配理由
effectiveUntil 有效期至
Returns
创建的关联实体
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getExpiringSoonAssignments()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.getExpiringSoonAssignments (int warningDays)
获取即将过期的用户组织角色关联
Parameters
warningDays 预警天数
Returns
即将过期的关联列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getOrganizationUserRoles()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.getOrganizationUserRoles (Long organizationId)
获取组织中的所有用户角色关联
Parameters
organizationId 组织ID
Returns
关联列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getRoleUserOrganizations()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.getRoleUserOrganizations (Long roleId)
获取拥有特定角色的所有用户组织关联
Parameters
roleId 角色ID
Returns
关联列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getUserAccessibleSubsystems()
List< String > com.gmp.auth.service.UserOrganizationRoleService.getUserAccessibleSubsystems (Long userId, Long organizationId)
获取用户可访问的子系统列表
Parameters
userId 用户ID
organizationId 组织ID
Returns
子系统代码列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes(), and com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystems().
getUserOrganizationRoles()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizationRoles (Long userId)
获取用户在所有组织中的有效角色
Parameters
userId 用户ID
Returns
用户组织角色关联列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getUserOrganizationRolesInOrganization()
List< UserOrganizationRole > com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizationRolesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的有效角色
Parameters
userId 用户ID
organizationId 组织ID
Returns
用户组织角色关联列表
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
getUserOrganizations()
Set< Long > com.gmp.auth.service.UserOrganizationRoleService.getUserOrganizations (Long userId)
获取用户拥有的所有组织
Parameters
userId 用户ID
Returns
组织ID集合
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes(), com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), and com.gmp.auth.service.impl.AuthServiceImplTest.setUp().
getUserPermissionCodesAcrossOrganizations()
Set< String > com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesAcrossOrganizations (Long userId)
获取用户在所有组织中的所有权限
Parameters
userId 用户ID
Returns
权限代码集合
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions(), com.gmp.auth.service.impl.AuthServiceImpl.hasPermission(), and com.gmp.auth.service.impl.AuthServiceImplTest.setUp().
getUserPermissionCodesInOrganization()
Set< String > com.gmp.auth.service.UserOrganizationRoleService.getUserPermissionCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的权限代码
Parameters
userId 用户ID
organizationId 组织ID
Returns
权限代码集合
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserPermissions().
getUserRoleCodesInOrganization()
Set< String > com.gmp.auth.service.UserOrganizationRoleService.getUserRoleCodesInOrganization (Long userId, Long organizationId)
获取用户在指定组织中的角色代码
Parameters
userId 用户ID
organizationId 组织ID
Returns
角色代码集合
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getUserRoles(), com.gmp.auth.service.impl.AuthServiceImpl.hasRole(), and com.gmp.auth.service.impl.AuthServiceImpl.login().
getUserSubsystemAccessLevels()
Map< String, Integer > com.gmp.auth.service.UserOrganizationRoleService.getUserSubsystemAccessLevels (Long userId, Long organizationId)
获取用户子系统访问级别
Parameters
userId 用户ID
organizationId 组织ID
Returns
子系统访问级别映射
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), and com.gmp.auth.service.impl.AuthServiceImpl.getUserSubsystemAccessLevels().
hasOrganizationAccess()
boolean com.gmp.auth.service.UserOrganizationRoleService.hasOrganizationAccess (Long userId, Long organizationId)
检查用户是否有权限访问指定组织
Parameters
userId 用户ID
organizationId 组织ID
Returns
是否有权限访问
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.getSubsystemAccessLevel(), com.gmp.auth.service.impl.AuthServiceImpl.getUserAccessibleSubsystemCodes(), com.gmp.auth.service.impl.AuthServiceImpl.hasOrganizationAccess(), com.gmp.auth.service.impl.AuthServiceImpl.login(), and com.gmp.auth.service.impl.AuthServiceImpl.refreshToken().
hasPermissionInOrganization()
boolean com.gmp.auth.service.UserOrganizationRoleService.hasPermissionInOrganization (Long userId, Long organizationId, String permissionCode)
检查用户在指定组织中是否拥有特定权限
Parameters
userId 用户ID
organizationId 组织ID
permissionCode 权限代码
Returns
是否拥有该权限
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
hasRoleInOrganization()
boolean com.gmp.auth.service.UserOrganizationRoleService.hasRoleInOrganization (Long userId, Long organizationId, String roleCode)
检查用户在指定组织中是否拥有特定角色
Parameters
userId 用户ID
organizationId 组织ID
roleCode 角色代码
Returns
是否拥有该角色
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
refreshExpiredAssignments()
void com.gmp.auth.service.UserOrganizationRoleService.refreshExpiredAssignments ()
刷新过期的用户组织角色关联
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
removeRoleFromUserInOrganization()
void com.gmp.auth.service.UserOrganizationRoleService.removeRoleFromUserInOrganization (Long userId, Long organizationId, Long roleId)
从组织中移除用户角色
Parameters
userId 用户ID
organizationId 组织ID
roleId 角色ID
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
updateStatus()
UserOrganizationRole com.gmp.auth.service.UserOrganizationRoleService.updateStatus (Long id, UserOrganizationRole.AssignmentStatus status, Long updatedBy)
更新用户组织角色状态
Parameters
id 关联ID
status 新状态
updatedBy 更新人ID
Returns
更新后的关联实体
Implemented in com.gmp.auth.service.impl.UserOrganizationRoleServiceImpl.
The documentation for this interface was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/UserOrganizationRoleService.java