GMP系统: com.gmp.auth.service.TokenBlacklistService Interface Reference
com.gmp.auth.service.TokenBlacklistService Interface Reference
令牌黑名单服务 用于管理已撤销的JWT令牌
Public Member Functions
void blacklistToken (String token, long expiration)
将令牌加入黑名单
boolean isTokenBlacklisted (String token)
检查令牌是否在黑名单中
void removeTokenFromBlacklist (String token)
从黑名单中移除令牌
void cleanExpiredTokens ()
清理过期的黑名单令牌
void blacklistToken (String token, long expirationTime)
将token加入黑名单
boolean isTokenBlacklisted (String token)
检查token是否在黑名单中
Detailed Description
令牌黑名单服务 用于管理已撤销的JWT令牌
Token黑名单服务接口
Definition at line 7 of file TokenBlacklistService.java.
Member Function Documentation
blacklistToken() [1/2]
void com.gmp.auth.service.TokenBlacklistService.blacklistToken (String token, long expiration)
将令牌加入黑名单
Parameters
token JWT令牌
expiration 令牌过期时间（毫秒）
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl, and com.gmp.auth.service.RedisTokenBlacklistService.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.logout().
blacklistToken() [2/2]
void com.gmp.auth.service.TokenBlacklistService.blacklistToken (String token, long expirationTime)
将token加入黑名单
Parameters
token 要加入黑名单的token
expirationTime token的过期时间戳
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl, and com.gmp.auth.service.RedisTokenBlacklistService.
cleanExpiredTokens()
void com.gmp.auth.service.TokenBlacklistService.cleanExpiredTokens ()
清理过期的黑名单令牌
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl.
isTokenBlacklisted() [1/2]
boolean com.gmp.auth.service.TokenBlacklistService.isTokenBlacklisted (String token)
检查令牌是否在黑名单中
Parameters
token JWT令牌
Returns
true表示令牌在黑名单中，false表示不在
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl, and com.gmp.auth.service.RedisTokenBlacklistService.
Referenced by com.gmp.auth.service.impl.AuthServiceImpl.refreshToken(), com.gmp.auth.service.impl.AuthServiceImplTest.testValidateToken_BlacklistedToken(), and com.gmp.auth.service.impl.AuthServiceImpl.validateToken().
isTokenBlacklisted() [2/2]
boolean com.gmp.auth.service.TokenBlacklistService.isTokenBlacklisted (String token)
检查token是否在黑名单中
Parameters
token 要检查的token
Returns
如果token在黑名单中返回true，否则返回false
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl, and com.gmp.auth.service.RedisTokenBlacklistService.
removeTokenFromBlacklist()
void com.gmp.auth.service.TokenBlacklistService.removeTokenFromBlacklist (String token)
从黑名单中移除令牌
Parameters
token JWT令牌
Implemented in com.gmp.auth.service.impl.TokenBlacklistServiceImpl.
The documentation for this interface was generated from the following files:
auth-service/src/main/java/com/gmp/auth/service/TokenBlacklistService.java
auth-service/src/test/java/com/gmp/auth/service/TokenBlacklistService.java