GMP系统: com.gmp.edms.service.DocumentService Interface Reference
com.gmp.edms.service.DocumentService Interface Reference
文档服务接口
Public Member Functions
DocumentDTO createDocument (DocumentCreateDTO documentCreateDTO)
创建文档
DocumentDTO createDocumentWithFile (DocumentCreateDTO documentCreateDTO, MultipartFile file) throws Exception
创建带文件的文档
DocumentDTO uploadDocumentFile (Long documentId, MultipartFile file) throws Exception
为文档上传文件
byte[] downloadDocumentFile (Long documentId) throws Exception
下载文档文件
DocumentDTO updateDocument (Long id, DocumentUpdateDTO documentUpdateDTO)
更新文档
void deleteDocument (Long id)
删除文档
void batchDeleteDocuments (List< Long > ids)
批量删除文档
DocumentDTO getDocumentById (Long id)
根据ID获取文档
DocumentDTO getDocumentByDocCode (String docCode)
根据文档编号获取文档
PageResponseDTO< DocumentDTO > queryDocuments (PageRequestDTO pageRequest, Map< String, Object > filters)
分页查询文档
List< DocumentDTO > getDocumentsByCategory (Long categoryId)
根据分类ID查询文档
void updateDocumentStatus (Long id, String status)
更新文档状态
List< DocumentDTO > searchDocuments (String keyword, Integer pageNo, Integer pageSize)
搜索文档
default List< DocumentDTO > searchDocuments (String keyword)
搜索文档（兼容单参数调用）
PageResponseDTO< DocumentDTO > advancedSearch (PageRequestDTO pageRequest, String keyword, Long categoryId, String status, Long departmentId, String approvalStatus)
高级搜索文档
List< DocumentDTO > getUserAccessibleDocuments (String username)
获取用户权限的文档列表
DocumentDTO approveDocument (Long id, String approvalStatus, String comments)
文档审批
Detailed Description
文档服务接口
Definition at line 16 of file DocumentService.java.
Member Function Documentation
advancedSearch()
PageResponseDTO< DocumentDTO > com.gmp.edms.service.DocumentService.advancedSearch (PageRequestDTO pageRequest, String keyword, Long categoryId, String status, Long departmentId, String approvalStatus)
高级搜索文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
approveDocument()
DocumentDTO com.gmp.edms.service.DocumentService.approveDocument (Long id, String approvalStatus, String comments)
文档审批
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
batchDeleteDocuments()
void com.gmp.edms.service.DocumentService.batchDeleteDocuments (List< Long > ids)
批量删除文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
createDocument()
DocumentDTO com.gmp.edms.service.DocumentService.createDocument (DocumentCreateDTO documentCreateDTO)
创建文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentStorageIntegrationTest.testCreateDocumentWithFileUpload().
createDocumentWithFile()
DocumentDTO com.gmp.edms.service.DocumentService.createDocumentWithFile (DocumentCreateDTO documentCreateDTO, MultipartFile file) throws Exception
创建带文件的文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentStorageIntegrationTest.testBatchDocumentUpload(), and com.gmp.edms.service.DocumentStorageIntegrationTest.testCreateDocumentWithFileUpload().
deleteDocument()
void com.gmp.edms.service.DocumentService.deleteDocument (Long id)
删除文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
downloadDocumentFile()
byte[] com.gmp.edms.service.DocumentService.downloadDocumentFile (Long documentId) throws Exception
下载文档文件
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentStorageIntegrationTest.testDownloadDocumentFile().
getDocumentByDocCode()
DocumentDTO com.gmp.edms.service.DocumentService.getDocumentByDocCode (String docCode)
根据文档编号获取文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
getDocumentById()
DocumentDTO com.gmp.edms.service.DocumentService.getDocumentById (Long id)
根据ID获取文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentStorageIntegrationTest.testUpdateDocumentVersionWithFileUpload().
getDocumentsByCategory()
List< DocumentDTO > com.gmp.edms.service.DocumentService.getDocumentsByCategory (Long categoryId)
根据分类ID查询文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
getUserAccessibleDocuments()
List< DocumentDTO > com.gmp.edms.service.DocumentService.getUserAccessibleDocuments (String username)
获取用户权限的文档列表
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
queryDocuments()
PageResponseDTO< DocumentDTO > com.gmp.edms.service.DocumentService.queryDocuments (PageRequestDTO pageRequest, Map< String, Object > filters)
分页查询文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
searchDocuments() [1/2]
default List< DocumentDTO > com.gmp.edms.service.DocumentService.searchDocuments (String keyword)
搜索文档（兼容单参数调用）
Definition at line 86 of file DocumentService.java.
References com.gmp.edms.service.DocumentService.searchDocuments().
searchDocuments() [2/2]
List< DocumentDTO > com.gmp.edms.service.DocumentService.searchDocuments (String keyword, Integer pageNo, Integer pageSize)
搜索文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentService.searchDocuments().
updateDocument()
DocumentDTO com.gmp.edms.service.DocumentService.updateDocument (Long id, DocumentUpdateDTO documentUpdateDTO)
更新文档
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
updateDocumentStatus()
void com.gmp.edms.service.DocumentService.updateDocumentStatus (Long id, String status)
更新文档状态
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
uploadDocumentFile()
DocumentDTO com.gmp.edms.service.DocumentService.uploadDocumentFile (Long documentId, MultipartFile file) throws Exception
为文档上传文件
Implemented in com.gmp.edms.service.impl.DocumentServiceImpl.
Referenced by com.gmp.edms.service.DocumentStorageIntegrationTest.testUpdateDocumentVersionWithFileUpload().
The documentation for this interface was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/DocumentService.java