GMP系统: com.gmp.auth.service.UserPasswordHistoryService Interface Reference
com.gmp.auth.service.UserPasswordHistoryService Interface Reference
用户密码历史服务接口
Public Member Functions
List< String > getPasswordHistory (Long userId, int limit)
获取用户的密码历史记录
void recordPasswordHistory (Long userId, String hashedPassword)
记录密码历史
void cleanOldPasswordHistory (Long userId, int keepCount)
清理过旧的密码历史记录
boolean isPasswordInHistory (Long userId, String password)
检查密码是否在历史记录中
void savePasswordHistory (Long userId, String password)
保存密码历史记录
Detailed Description
用户密码历史服务接口
Definition at line 8 of file UserPasswordHistoryService.java.
Member Function Documentation
cleanOldPasswordHistory()
void com.gmp.auth.service.UserPasswordHistoryService.cleanOldPasswordHistory (Long userId, int keepCount)
清理过旧的密码历史记录
Parameters
userId 用户ID
keepCount 保留的记录数
Implemented in com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.
getPasswordHistory()
List< String > com.gmp.auth.service.UserPasswordHistoryService.getPasswordHistory (Long userId, int limit)
获取用户的密码历史记录
Parameters
userId 用户ID
limit 限制返回记录数
Returns
密码历史记录列表（哈希值）
Implemented in com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.
Referenced by com.gmp.auth.service.PasswordPolicyService.isPasswordInHistory().
isPasswordInHistory()
boolean com.gmp.auth.service.UserPasswordHistoryService.isPasswordInHistory (Long userId, String password)
检查密码是否在历史记录中
Parameters
userId 用户ID
password 密码
Returns
是否在历史记录中
Implemented in com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testChangePassword_Success().
recordPasswordHistory()
void com.gmp.auth.service.UserPasswordHistoryService.recordPasswordHistory (Long userId, String hashedPassword)
记录密码历史
Parameters
userId 用户ID
hashedPassword 哈希后的密码
Implemented in com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.
Referenced by com.gmp.auth.service.PasswordPolicyService.recordPasswordHistory().
savePasswordHistory()
void com.gmp.auth.service.UserPasswordHistoryService.savePasswordHistory (Long userId, String password)
保存密码历史记录
Parameters
userId 用户ID
password 密码
Implemented in com.gmp.auth.service.impl.UserPasswordHistoryServiceImpl.
The documentation for this interface was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/UserPasswordHistoryService.java