GMP系统: com.gmp.edms.service.DocumentSearchService Interface Reference
com.gmp.edms.service.DocumentSearchService Interface Reference
Public Member Functions
List< DocumentDTO > fullTextSearch (String query)
全文搜索文档
List< DocumentDTO > advancedSearch (DocumentQueryDTO queryDTO)
高级搜索文档
void indexDocument (DocumentDTO documentDTO)
索引文档
void updateDocumentIndex (DocumentDTO documentDTO)
更新文档索引
void deleteDocumentIndex (Long documentId)
删除文档索引
void bulkIndexDocuments (List< DocumentDTO > documentDTOs)
批量索引文档
Detailed Description
Definition at line 8 of file DocumentSearchService.java.
Member Function Documentation
advancedSearch()
List< DocumentDTO > com.gmp.edms.service.DocumentSearchService.advancedSearch (DocumentQueryDTO queryDTO)
高级搜索文档
Parameters
queryDTO 搜索条件
Returns
文档列表
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
bulkIndexDocuments()
void com.gmp.edms.service.DocumentSearchService.bulkIndexDocuments (List< DocumentDTO > documentDTOs)
批量索引文档
Parameters
documentDTOs 文档DTO列表
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
deleteDocumentIndex()
void com.gmp.edms.service.DocumentSearchService.deleteDocumentIndex (Long documentId)
删除文档索引
Parameters
documentId 文档ID
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.batchDeleteDocuments(), and com.gmp.edms.service.impl.DocumentServiceImpl.deleteDocument().
fullTextSearch()
List< DocumentDTO > com.gmp.edms.service.DocumentSearchService.fullTextSearch (String query)
全文搜索文档
Parameters
query 搜索关键词
Returns
文档列表
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
indexDocument()
void com.gmp.edms.service.DocumentSearchService.indexDocument (DocumentDTO documentDTO)
索引文档
Parameters
documentDTO 文档DTO
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.createDocument().
updateDocumentIndex()
void com.gmp.edms.service.DocumentSearchService.updateDocumentIndex (DocumentDTO documentDTO)
更新文档索引
Parameters
documentDTO 文档DTO
Implemented in com.gmp.edms.service.impl.DocumentSearchServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.updateDocument().
The documentation for this interface was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/DocumentSearchService.java