GMP系统: com.gmp.training.service.BaseService< T, ID > Interface Template Reference
com.gmp.training.service.BaseService< T, ID > Interface Template Reference
基础服务接口，定义所有服务的通用方法
Public Member Functions
T save (T entity)
保存实体
List< T > saveAll (List< T > entities)
批量保存实体
Optional< T > findById (ID id)
根据ID查找实体
T getById (ID id)
根据ID查找实体，如果不存在则抛出异常
List< T > findAll ()
查询所有实体
List< T > findAllById (List< ID > ids)
根据ID列表查询实体
Page< T > findAll (Pageable pageable)
分页查询
List< T > findAll (Sort sort)
排序查询
boolean existsById (ID id)
判断实体是否存在
long count ()
统计实体数量
void deleteById (ID id)
根据ID删除实体
void delete (T entity)
删除实体
void deleteAll (List< T > entities)
批量删除实体
void deleteAll ()
删除所有实体
Detailed Description
基础服务接口，定义所有服务的通用方法
Parameters
<T> 实体类型
<ID> 主键类型
Author
GMP系统开发团队
Definition at line 17 of file BaseService.java.
Member Function Documentation
count()
long com.gmp.training.service.BaseService< T, ID >.count ()
统计实体数量
Returns
实体数量
delete()
void com.gmp.training.service.BaseService< T, ID >.delete (T entity)
删除实体
Parameters
entity 实体对象
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testDelete(), com.gmp.training.service.impl.TrainingCourseServiceImplTest.testDelete(), com.gmp.training.service.impl.TrainingNeedServiceImplTest.testDelete(), com.gmp.training.service.impl.TrainingPlanServiceImplTest.testDelete(), and com.gmp.training.service.impl.TrainingRecordServiceImplTest.testDelete().
deleteAll() [1/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll ()
删除所有实体
deleteAll() [2/2]
void com.gmp.training.service.BaseService< T, ID >.deleteAll (List< T > entities)
批量删除实体
Parameters
entities 实体列表
deleteById()
void com.gmp.training.service.BaseService< T, ID >.deleteById (ID id)
根据ID删除实体
Parameters
id 实体ID
existsById()
boolean com.gmp.training.service.BaseService< T, ID >.existsById (ID id)
判断实体是否存在
Parameters
id 实体ID
Returns
是否存在
findAll() [1/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll ()
查询所有实体
Returns
实体列表
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindAll(), com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindAll(), com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindAll(), com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindAll(), and com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindAll().
findAll() [2/3]
Page< T > com.gmp.training.service.BaseService< T, ID >.findAll (Pageable pageable)
分页查询
Parameters
pageable 分页参数
Returns
分页结果
findAll() [3/3]
List< T > com.gmp.training.service.BaseService< T, ID >.findAll (Sort sort)
排序查询
Parameters
sort 排序参数
Returns
排序后的实体列表
findAllById()
List< T > com.gmp.training.service.BaseService< T, ID >.findAllById (List< ID > ids)
根据ID列表查询实体
Parameters
ids ID列表
Returns
实体列表
findById()
Optional< T > com.gmp.training.service.BaseService< T, ID >.findById (ID id)
根据ID查找实体
Parameters
id 实体ID
Returns
实体对象，如果不存在则返回空
Referenced by com.gmp.training.service.impl.TrainingAssessmentServiceImplTest.testFindById(), com.gmp.training.service.impl.TrainingCourseServiceImplTest.testFindById(), com.gmp.training.service.impl.TrainingNeedServiceImplTest.testFindById(), com.gmp.training.service.impl.TrainingPlanServiceImplTest.testFindById(), and com.gmp.training.service.impl.TrainingRecordServiceImplTest.testFindById().
getById()
T com.gmp.training.service.BaseService< T, ID >.getById (ID id)
根据ID查找实体，如果不存在则抛出异常
Parameters
id 实体ID
Returns
实体对象
Exceptions
com.gmp.training.exception.EntityNotFoundException 如果实体不存在
save()
T com.gmp.training.service.BaseService< T, ID >.save (T entity)
保存实体
Parameters
entity 实体对象
Returns
保存后的实体
saveAll()
List< T > com.gmp.training.service.BaseService< T, ID >.saveAll (List< T > entities)
批量保存实体
Parameters
entities 实体对象列表
Returns
保存后的实体列表
The documentation for this interface was generated from the following file:
training-service/src/main/java/com/gmp/training/service/BaseService.java