GMP系统: com.gmp.equipment.repository.EquipmentRepository Interface Reference
com.gmp.equipment.repository.EquipmentRepository Interface Reference
设备数据仓库接口
Public Member Functions
Equipment findByEquipmentCode (String equipmentCode)
根据设备编码查找设备
boolean existsByEquipmentCode (String equipmentCode)
检查设备编码是否存在
List< Equipment > findByEquipmentStatus (Equipment.EquipmentStatus status)
根据设备状态查询设备列表
Page< Equipment > findByEquipmentStatus (Equipment.EquipmentStatus status, Pageable pageable)
根据设备状态分页查询
List< Equipment > findByLocation (String location)
根据位置查询设备
List< Equipment > findByEquipmentType (String equipmentType)
根据设备类型查询设备
List< Equipment > findByManufacturer (String manufacturer)
根据制造商查询设备
List< Equipment > findEquipmentDueForMaintenance (@Param("currentDate") LocalDateTime currentDate)
查询需要维护的设备（基于下次维护日期）
List< Equipment > findCalibrationOverdueEquipment (@Param("currentDate") LocalDateTime currentDate)
查询校准过期的设备
List< Equipment > findEquipmentDueForCalibration (@Param("currentDate") LocalDateTime currentDate, @Param("futureDate") LocalDateTime futureDate)
查询即将到期的校准设备（预警查询）
List< Equipment > findEquipmentUnderWarranty (@Param("currentDate") LocalDateTime currentDate)
查询质保期内的设备
List< Object[]> countEquipmentByType ()
统计按类型分组的设备数量
List< Object[]> countEquipmentByStatus ()
统计按状态分组的设备数量
List< Object[]> countEquipmentByOperationalStatus ()
统计按运行状态分组的设备数量
List< Equipment > findCriticalEquipment ()
查找关键设备（GMP合规的关键设备）
List< Equipment > findEquipmentInstalledBetween (@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate)
查询指定时间范围内安装的设备
List< Equipment > findMonitoredEquipment ()
查询支持监控的设备
Page< Equipment > findEquipmentWithFilters (@Param("equipmentCode") String equipmentCode, @Param("equipmentName") String equipmentName, @Param("equipmentType") String equipmentType, @Param("manufacturer") String manufacturer, @Param("location") String location, @Param("equipmentStatus") Equipment.EquipmentStatus equipmentStatus, Pageable pageable)
复杂查询：按多个条件组合查询设备
Equipment findBySensorId (String sensorId)
通过传感器ID查询设备
Detailed Description
设备数据仓库接口
提供设备管理的完整数据访问层功能：
基础CRUD操作（继承自JpaRepository）
设备状态查询
维护计划查询
统计聚合查询
业务规则验证方法
Definition at line 40 of file EquipmentRepository.java.
Member Function Documentation
countEquipmentByOperationalStatus()
List< Object[]> com.gmp.equipment.repository.EquipmentRepository.countEquipmentByOperationalStatus ()
统计按运行状态分组的设备数量
countEquipmentByStatus()
List< Object[]> com.gmp.equipment.repository.EquipmentRepository.countEquipmentByStatus ()
统计按状态分组的设备数量
countEquipmentByType()
List< Object[]> com.gmp.equipment.repository.EquipmentRepository.countEquipmentByType ()
统计按类型分组的设备数量
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testCountEquipmentByType().
existsByEquipmentCode()
boolean com.gmp.equipment.repository.EquipmentRepository.existsByEquipmentCode (String equipmentCode)
检查设备编码是否存在
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testExistsByEquipmentCode().
findByEquipmentCode()
Equipment com.gmp.equipment.repository.EquipmentRepository.findByEquipmentCode (String equipmentCode)
根据设备编码查找设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testSaveAndFindByEquipmentCode().
findByEquipmentStatus() [1/2]
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findByEquipmentStatus (Equipment.EquipmentStatus status)
根据设备状态查询设备列表
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindByStatus(), and com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindByStatusWithPaging().
findByEquipmentStatus() [2/2]
Page< Equipment > com.gmp.equipment.repository.EquipmentRepository.findByEquipmentStatus (Equipment.EquipmentStatus status, Pageable pageable)
根据设备状态分页查询
findByEquipmentType()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findByEquipmentType (String equipmentType)
根据设备类型查询设备
findByLocation()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findByLocation (String location)
根据位置查询设备
findByManufacturer()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findByManufacturer (String manufacturer)
根据制造商查询设备
findBySensorId()
Equipment com.gmp.equipment.repository.EquipmentRepository.findBySensorId (String sensorId)
通过传感器ID查询设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindBySensorId().
findCalibrationOverdueEquipment()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findCalibrationOverdueEquipment (@Param("currentDate") LocalDateTime currentDate)
查询校准过期的设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindCalibrationOverdueEquipment().
findCriticalEquipment()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findCriticalEquipment ()
查找关键设备（GMP合规的关键设备）
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindCriticalEquipment().
findEquipmentDueForCalibration()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findEquipmentDueForCalibration (@Param("currentDate") LocalDateTime currentDate, @Param("futureDate") LocalDateTime futureDate)
查询即将到期的校准设备（预警查询）
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentDueForCalibration().
findEquipmentDueForMaintenance()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findEquipmentDueForMaintenance (@Param("currentDate") LocalDateTime currentDate)
查询需要维护的设备（基于下次维护日期）
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentDueForMaintenance().
findEquipmentInstalledBetween()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findEquipmentInstalledBetween (@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate)
查询指定时间范围内安装的设备
findEquipmentUnderWarranty()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findEquipmentUnderWarranty (@Param("currentDate") LocalDateTime currentDate)
查询质保期内的设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentUnderWarranty().
findEquipmentWithFilters()
Page< Equipment > com.gmp.equipment.repository.EquipmentRepository.findEquipmentWithFilters (@Param("equipmentCode") String equipmentCode, @Param("equipmentName") String equipmentName, @Param("equipmentType") String equipmentType, @Param("manufacturer") String manufacturer, @Param("location") String location, @Param("equipmentStatus") Equipment.EquipmentStatus equipmentStatus, Pageable pageable)
复杂查询：按多个条件组合查询设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindEquipmentWithFilters().
findMonitoredEquipment()
List< Equipment > com.gmp.equipment.repository.EquipmentRepository.findMonitoredEquipment ()
查询支持监控的设备
Referenced by com.gmp.equipment.repository.EquipmentRepositoryIntegrationTest.testFindMonitoredEquipment().
The documentation for this interface was generated from the following file:
equipment-management/src/main/java/com/gmp/equipment/repository/EquipmentRepository.java