GMP系统: com.gmp.auth.service.UserRoleService Interface Reference
com.gmp.auth.service.UserRoleService Interface Reference
用户角色管理服务接口
Public Member Functions
UserRole assignRoleToUser (Long userId, Long roleId, Long assignedBy)
为用户分配角色
List< UserRole > assignRolesToUser (Long userId, List< Long > roleIds, Long assignedBy)
为用户分配多个角色
void removeRoleFromUser (Long userId, Long roleId)
移除用户的角色
List< Role > getUserRoles (Long userId)
获取用户的所有角色
Set< String > getUserRoleCodes (Long userId)
获取用户的角色代码集合
boolean hasRole (Long userId, String roleCode)
检查用户是否拥有指定角色
boolean hasAnyRole (Long userId, List< String > roleCodes)
检查用户是否拥有指定角色之一
void refreshExpiredUserRoles ()
刷新用户过期的角色
Detailed Description
用户角色管理服务接口
Author
GMP系统开发团队
Definition at line 13 of file UserRoleService.java.
Member Function Documentation
assignRolesToUser()
List< UserRole > com.gmp.auth.service.UserRoleService.assignRolesToUser (Long userId, List< Long > roleIds, Long assignedBy)
为用户分配多个角色
Parameters
userId 用户ID
roleIds 角色ID列表
assignedBy 分配人
Returns
分配结果列表
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
assignRoleToUser()
UserRole com.gmp.auth.service.UserRoleService.assignRoleToUser (Long userId, Long roleId, Long assignedBy)
为用户分配角色
Parameters
userId 用户ID
roleId 角色ID
assignedBy 分配人
Returns
分配结果
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
getUserRoleCodes()
Set< String > com.gmp.auth.service.UserRoleService.getUserRoleCodes (Long userId)
获取用户的角色代码集合
Parameters
userId 用户ID
Returns
角色代码集合
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserDoesNotHaveRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testHasRole_UserHasRequiredRole(), com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
getUserRoles()
List< Role > com.gmp.auth.service.UserRoleService.getUserRoles (Long userId)
获取用户的所有角色
Parameters
userId 用户ID
Returns
角色列表
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
hasAnyRole()
boolean com.gmp.auth.service.UserRoleService.hasAnyRole (Long userId, List< String > roleCodes)
检查用户是否拥有指定角色之一
Parameters
userId 用户ID
roleCodes 角色代码列表
Returns
是否拥有任一角色
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
hasRole()
boolean com.gmp.auth.service.UserRoleService.hasRole (Long userId, String roleCode)
检查用户是否拥有指定角色
Parameters
userId 用户ID
roleCode 角色代码
Returns
是否拥有
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
refreshExpiredUserRoles()
void com.gmp.auth.service.UserRoleService.refreshExpiredUserRoles ()
刷新用户过期的角色
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
removeRoleFromUser()
void com.gmp.auth.service.UserRoleService.removeRoleFromUser (Long userId, Long roleId)
移除用户的角色
Parameters
userId 用户ID
roleId 角色ID
Implemented in com.gmp.auth.service.impl.UserRoleServiceImpl.
The documentation for this interface was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/UserRoleService.java