GMP系统: com.gmp.auth.service.AuthService Interface Reference
com.gmp.auth.service.AuthService Interface Reference
认证服务接口
Public Member Functions
LoginResponse login (LoginRequest request, String ipAddress, String userAgent)
用户登录
void logout (String username, String token)
用户登出
com.gmp.auth.dto.TokenResponse refreshToken (String refreshToken)
刷新访问令牌
boolean validateToken (String token)
验证JWT令牌
boolean hasPermission (String username, String... requiredPermissions)
验证用户权限
boolean hasRole (String username, String... requiredRoles)
验证用户角色
java.util.List< String > getUserPermissions (String username)
获取用户所有权限
java.util.Set< String > getUserRoles (String username)
获取用户所有角色
boolean changePassword (String username, com.gmp.auth.dto.PasswordChangeRequest request)
修改密码
boolean resetPassword (String username, String newPassword)
重置密码
String getPasswordComplexityRequirements ()
获取密码复杂度要求
LoginResponse verifyMfa (MfaVerifyRequest request)
验证MFA
java.util.List< String > regenerateRecoveryCodes (String username)
重新生成恢复码
boolean hasSubsystemAccess (String username, String subsystemCode)
验证用户是否有子系统访问权限
Integer getSubsystemAccessLevel (String username, String subsystemCode)
获取用户对子系统的访问级别
List< String > getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
Map< String, Integer > getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
boolean hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统的写入权限
Set< String > getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
boolean hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
Detailed Description
认证服务接口
该接口定义了GMP系统的认证和授权服务，包括用户登录、登出、令牌管理、权限验证等功能。 继承自Spring Security的UserDetailsService，用于用户信息加载。
Author
GMP系统开发团队
Version
1.0
Since
2023-01-01
See also
org.springframework.security.core.userdetails.UserDetailsService
Definition at line 24 of file AuthService.java.
Member Function Documentation
changePassword()
boolean com.gmp.auth.service.AuthService.changePassword (String username, com.gmp.auth.dto.PasswordChangeRequest request)
修改密码
处理用户密码修改请求
Parameters
username 用户名
request 密码修改请求，包含旧密码和新密码
Returns
boolean 如果密码修改成功返回true，否则返回false
See also
com.gmp.auth.dto.PasswordChangeRequest
getPasswordComplexityRequirements()
String com.gmp.auth.service.AuthService.getPasswordComplexityRequirements ()
获取密码复杂度要求
获取系统的密码复杂度要求描述
Returns
String 密码复杂度要求描述
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
getSubsystemAccessLevel()
Integer com.gmp.auth.service.AuthService.getSubsystemAccessLevel (String username, String subsystemCode)
获取用户对子系统的访问级别
获取用户对指定子系统的访问级别
Parameters
username 用户名
subsystemCode 子系统代码
Returns
Integer 访问级别，无权限返回0
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
getUserAccessibleSubsystemCodes()
Set< String > com.gmp.auth.service.AuthService.getUserAccessibleSubsystemCodes (String username)
获取用户可访问的子系统代码集合
获取用户可以访问的所有子系统代码集合
Parameters
username 用户名
Returns
Set<String> 子系统代码集合
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
getUserAccessibleSubsystems()
List< String > com.gmp.auth.service.AuthService.getUserAccessibleSubsystems (String username)
获取用户可访问的子系统列表
获取用户可以访问的所有子系统列表
Parameters
username 用户名
Returns
List<String> 可访问的子系统列表
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
getUserPermissions()
java.util.List< String > com.gmp.auth.service.AuthService.getUserPermissions (String username)
获取用户所有权限
获取用户拥有的所有权限列表
Parameters
username 用户名
Returns
java.util.List<String> 用户权限列表
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testGetUserPermissionsMethodSignature().
getUserRoles()
java.util.Set< String > com.gmp.auth.service.AuthService.getUserRoles (String username)
获取用户所有角色
获取用户拥有的所有角色列表
Parameters
username 用户名
Returns
java.util.Set<String> 用户角色列表
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testGetUserRolesMethodSignature().
getUserSubsystemAccessLevels()
Map< String, Integer > com.gmp.auth.service.AuthService.getUserSubsystemAccessLevels (String username)
获取用户对子系统的访问级别映射
获取用户对所有子系统的访问级别映射
Parameters
username 用户名
Returns
Map<String, Integer> 子系统代码与访问级别的映射
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
hasPermission()
boolean com.gmp.auth.service.AuthService.hasPermission (String username, String... requiredPermissions)
验证用户权限
验证用户是否拥有指定的权限
Parameters
username 用户名
requiredPermissions 需要的权限列表
Returns
boolean 如果用户拥有所有指定权限返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testHasPermissionMethodSignature(), and com.gmp.auth.service.AuthServiceTest.testMultiplePermissionCheck().
hasRole()
boolean com.gmp.auth.service.AuthService.hasRole (String username, String... requiredRoles)
验证用户角色
验证用户是否拥有指定的角色
Parameters
username 用户名
requiredRoles 需要的角色列表
Returns
boolean 如果用户拥有所有指定角色返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testHasRoleMethodSignature(), and com.gmp.auth.service.AuthServiceTest.testMultipleRoleCheck().
hasSubsystemAccess()
boolean com.gmp.auth.service.AuthService.hasSubsystemAccess (String username, String subsystemCode)
验证用户是否有子系统访问权限
验证用户是否可以访问指定的子系统
Parameters
username 用户名
subsystemCode 子系统代码
Returns
boolean 如果用户有访问权限返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
hasSubsystemAdminAccess()
boolean com.gmp.auth.service.AuthService.hasSubsystemAdminAccess (String username, String subsystemCode)
检查用户是否有子系统的管理权限
检查用户是否对指定子系统有管理权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
boolean 如果用户有管理权限返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
hasSubsystemWriteAccess()
boolean com.gmp.auth.service.AuthService.hasSubsystemWriteAccess (String username, String subsystemCode)
检查用户是否有子系统的写入权限
检查用户是否对指定子系统有写入权限
Parameters
username 用户名
subsystemCode 子系统代码
Returns
boolean 如果用户有写入权限返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
login()
LoginResponse com.gmp.auth.service.AuthService.login (LoginRequest request, String ipAddress, String userAgent)
用户登录
处理用户登录请求，验证用户凭证，生成JWT令牌
Parameters
request 登录请求，包含用户名和密码
ipAddress 客户端IP地址，用于审计日志
userAgent 用户代理，用于审计日志
Returns
LoginResponse 登录响应，包含JWT令牌和用户信息
See also
com.gmp.auth.dto.LoginRequest
com.gmp.auth.dto.LoginResponse
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testLoginMethodSignature().
logout()
void com.gmp.auth.service.AuthService.logout (String username, String token)
用户登出
处理用户登出请求，将JWT令牌加入黑名单
Parameters
username 用户名
token JWT令牌
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testLogoutMethodSignature().
refreshToken()
com.gmp.auth.dto.TokenResponse com.gmp.auth.service.AuthService.refreshToken (String refreshToken)
刷新访问令牌
使用刷新令牌生成新的访问令牌
Parameters
refreshToken 刷新令牌
Returns
com.gmp.auth.dto.TokenResponse 新的令牌响应
See also
com.gmp.auth.dto.TokenResponse
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testRefreshTokenMethodSignature().
regenerateRecoveryCodes()
java.util.List< String > com.gmp.auth.service.AuthService.regenerateRecoveryCodes (String username)
重新生成恢复码
为用户重新生成MFA恢复码
Parameters
username 用户名
Returns
java.util.List<String> 新的恢复码列表
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
resetPassword()
boolean com.gmp.auth.service.AuthService.resetPassword (String username, String newPassword)
重置密码
重置用户密码
Parameters
username 用户名
newPassword 新密码
Returns
boolean 如果密码重置成功返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
validateToken()
boolean com.gmp.auth.service.AuthService.validateToken (String token)
验证JWT令牌
验证JWT令牌的有效性，包括签名、过期时间等
Parameters
token JWT令牌
Returns
boolean 如果令牌有效返回true，否则返回false
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
Referenced by com.gmp.auth.service.AuthServiceTest.testValidateTokenMethodSignature().
verifyMfa()
LoginResponse com.gmp.auth.service.AuthService.verifyMfa (MfaVerifyRequest request)
验证MFA
验证多因素认证码
Parameters
request MFA验证请求，包含用户名和MFA码
Returns
LoginResponse 登录响应，包含JWT令牌
See also
com.gmp.auth.dto.MfaVerifyRequest
com.gmp.auth.dto.LoginResponse
Implemented in com.gmp.auth.service.impl.AuthServiceImpl.
The documentation for this interface was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/AuthService.java