GMP系统: com.gmp.edms.repository.DocumentRepository Interface Reference
com.gmp.edms.repository.DocumentRepository Interface Reference
文档Repository接口
Public Member Functions
Optional< Document > findByDocCode (String docCode)
根据文档编号查询文档
List< Document > findByCategoryId (Long categoryId)
根据分类ID查询文档列表
List< Document > findByCreatedBy (String createdBy)
根据创建者查询文档列表
List< Document > findByTitleContaining (String keyword)
根据标题模糊查询文档
List< Document > searchByKeyword (String keyword, int offset, int limit)
按关键词搜索文档，支持分页
Page< Document > findByStatus (String status, Pageable pageable)
分页查询文档
long countByCategoryId (Long categoryId)
统计分类下文档数量
List< Document > findByDepartmentId (Long departmentId)
根据部门ID查询文档
List< Document > findByApprovalStatus (String approvalStatus)
根据审批状态查询文档
Page< Document > advancedSearch (@Param("keyword") String keyword, @Param("categoryId") Long categoryId, @Param("status") String status, @Param("departmentId") Long departmentId, @Param("approvalStatus") String approvalStatus, Pageable pageable)
高级查询文档
List< Document > findDocumentsByUserPermission (@Param("username") String username)
查询用户权限下的文档
Detailed Description
文档Repository接口
Definition at line 19 of file DocumentRepository.java.
Member Function Documentation
advancedSearch()
Page< Document > com.gmp.edms.repository.DocumentRepository.advancedSearch (@Param("keyword") String keyword, @Param("categoryId") Long categoryId, @Param("status") String status, @Param("departmentId") Long departmentId, @Param("approvalStatus") String approvalStatus, Pageable pageable)
高级查询文档
countByCategoryId()
long com.gmp.edms.repository.DocumentRepository.countByCategoryId (Long categoryId)
统计分类下文档数量
Referenced by com.gmp.edms.repository.DocumentRepositoryTest.testCountByCategoryId().
findByApprovalStatus()
List< Document > com.gmp.edms.repository.DocumentRepository.findByApprovalStatus (String approvalStatus)
根据审批状态查询文档
findByCategoryId()
List< Document > com.gmp.edms.repository.DocumentRepository.findByCategoryId (Long categoryId)
根据分类ID查询文档列表
findByCreatedBy()
List< Document > com.gmp.edms.repository.DocumentRepository.findByCreatedBy (String createdBy)
根据创建者查询文档列表
findByDepartmentId()
List< Document > com.gmp.edms.repository.DocumentRepository.findByDepartmentId (Long departmentId)
根据部门ID查询文档
findByDocCode()
Optional< Document > com.gmp.edms.repository.DocumentRepository.findByDocCode (String docCode)
根据文档编号查询文档
Referenced by com.gmp.edms.repository.DocumentRepositoryTest.testFindByDocCode().
findByStatus()
Page< Document > com.gmp.edms.repository.DocumentRepository.findByStatus (String status, Pageable pageable)
分页查询文档
findByTitleContaining()
List< Document > com.gmp.edms.repository.DocumentRepository.findByTitleContaining (String keyword)
根据标题模糊查询文档
findDocumentsByUserPermission()
List< Document > com.gmp.edms.repository.DocumentRepository.findDocumentsByUserPermission (@Param("username") String username)
查询用户权限下的文档
searchByKeyword()
List< Document > com.gmp.edms.repository.DocumentRepository.searchByKeyword (String keyword, int offset, int limit)
按关键词搜索文档，支持分页
Referenced by com.gmp.edms.repository.DocumentRepositoryTest.testSearchByKeyword().
The documentation for this interface was generated from the following file:
edms-service/src/main/java/com/gmp/edms/repository/DocumentRepository.java