GMP系统: com.gmp.edms.service.FileStorageService Interface Reference
com.gmp.edms.service.FileStorageService Interface Reference
文件存储服务接口
Public Member Functions
String uploadFile (MultipartFile file, String bucketName, String prefix) throws Exception
上传文件
InputStream downloadFile (String bucketName, String filePath) throws Exception
下载文件
void deleteFile (String bucketName, String filePath) throws Exception
删除文件
void batchDeleteFiles (String bucketName, List< String > filePaths) throws Exception
批量删除文件
boolean fileExists (String bucketName, String filePath)
检查文件是否存在
String generatePresignedUrl (String bucketName, String filePath, int expiration) throws Exception
生成预签名URL
Map< String, Object > getFileInfo (String bucketName, String filePath) throws Exception
获取文件信息
void copyFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
复制文件
void createBucket (String bucketName) throws Exception
创建存储桶
boolean bucketExists (String bucketName) throws Exception
检查存储桶是否存在
void deleteBucket (String bucketName) throws Exception
删除存储桶
List< String > listBuckets () throws Exception
列出所有存储桶
List< String > listFiles (String bucketName, String prefix) throws Exception
列出存储桶中的文件
long getFileSize (String bucketName, String filePath) throws Exception
获取文件大小
long getFileLastModified (String bucketName, String filePath) throws Exception
获取文件最后修改时间
String getContentType (String bucketName, String filePath) throws Exception
获取文件内容类型
void createDirectory (String bucketName, String directoryPath) throws Exception
创建目录
boolean directoryExists (String bucketName, String directoryPath)
检查目录是否存在
void deleteDirectory (String bucketName, String directoryPath) throws Exception
删除目录
void moveFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
移动文件
Map< String, Long > getBucketStorageInfo (String bucketName) throws Exception
获取存储桶存储使用情况
Detailed Description
文件存储服务接口
Definition at line 12 of file FileStorageService.java.
Member Function Documentation
batchDeleteFiles()
void com.gmp.edms.service.FileStorageService.batchDeleteFiles (String bucketName, List< String > filePaths) throws Exception
批量删除文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testBatchDeleteFiles_Success().
bucketExists()
boolean com.gmp.edms.service.FileStorageService.bucketExists (String bucketName) throws Exception
检查存储桶是否存在
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
copyFile()
void com.gmp.edms.service.FileStorageService.copyFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
复制文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testCopyFile_Success().
createBucket()
void com.gmp.edms.service.FileStorageService.createBucket (String bucketName) throws Exception
创建存储桶
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
createDirectory()
void com.gmp.edms.service.FileStorageService.createDirectory (String bucketName, String directoryPath) throws Exception
创建目录
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testCreateDirectory_Success().
deleteBucket()
void com.gmp.edms.service.FileStorageService.deleteBucket (String bucketName) throws Exception
删除存储桶
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
deleteDirectory()
void com.gmp.edms.service.FileStorageService.deleteDirectory (String bucketName, String directoryPath) throws Exception
删除目录
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
deleteFile()
void com.gmp.edms.service.FileStorageService.deleteFile (String bucketName, String filePath) throws Exception
删除文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.deleteDocumentVersion(), and com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDeleteFile_Success().
directoryExists()
boolean com.gmp.edms.service.FileStorageService.directoryExists (String bucketName, String directoryPath)
检查目录是否存在
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
downloadFile()
InputStream com.gmp.edms.service.FileStorageService.downloadFile (String bucketName, String filePath) throws Exception
下载文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentServiceImpl.downloadDocumentFile(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.downloadDocumentVersion(), com.gmp.edms.service.impl.DocumentVersionServiceImpl.rollbackToVersion(), com.gmp.edms.service.CommonFileServiceTest.testDownloadFile_Success(), and com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDownloadFile_Success().
fileExists()
boolean com.gmp.edms.service.FileStorageService.fileExists (String bucketName, String filePath)
检查文件是否存在
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
generatePresignedUrl()
String com.gmp.edms.service.FileStorageService.generatePresignedUrl (String bucketName, String filePath, int expiration) throws Exception
生成预签名URL
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.impl.DocumentVersionServiceImpl.generatePresignedUrl(), com.gmp.edms.service.CommonFileServiceTest.testGeneratePresignedUrl_Success(), and com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGeneratePresignedUrl_Success().
getBucketStorageInfo()
Map< String, Long > com.gmp.edms.service.FileStorageService.getBucketStorageInfo (String bucketName) throws Exception
获取存储桶存储使用情况
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetBucketStorageInfo_Success().
getContentType()
String com.gmp.edms.service.FileStorageService.getContentType (String bucketName, String filePath) throws Exception
获取文件内容类型
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
getFileInfo()
Map< String, Object > com.gmp.edms.service.FileStorageService.getFileInfo (String bucketName, String filePath) throws Exception
获取文件信息
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetFileInfo_Success().
getFileLastModified()
long com.gmp.edms.service.FileStorageService.getFileLastModified (String bucketName, String filePath) throws Exception
获取文件最后修改时间
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
getFileSize()
long com.gmp.edms.service.FileStorageService.getFileSize (String bucketName, String filePath) throws Exception
获取文件大小
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
listBuckets()
List< String > com.gmp.edms.service.FileStorageService.listBuckets () throws Exception
列出所有存储桶
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
listFiles()
List< String > com.gmp.edms.service.FileStorageService.listFiles (String bucketName, String prefix) throws Exception
列出存储桶中的文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testListFiles_Success().
moveFile()
void com.gmp.edms.service.FileStorageService.moveFile (String sourceBucket, String sourcePath, String targetBucket, String targetPath) throws Exception
移动文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testMoveFile_Success().
uploadFile()
String com.gmp.edms.service.FileStorageService.uploadFile (MultipartFile file, String bucketName, String prefix) throws Exception
上传文件
Implemented in com.gmp.edms.service.impl.MinioFileStorageServiceImpl.
Referenced by com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testBatchDeleteFiles_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testCopyFile_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDeleteFile_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testDownloadFile_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGeneratePresignedUrl_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetBucketStorageInfo_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testGetFileInfo_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testListFiles_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testMoveFile_Success(), com.gmp.edms.service.CommonFileServiceTest.testUploadFile_Success(), com.gmp.edms.service.MinioFileStorageServiceIntegrationTest.testUploadFile_Success(), com.gmp.edms.service.impl.DocumentServiceImpl.uploadDocumentFile(), and com.gmp.edms.service.impl.DocumentVersionServiceImpl.uploadDocumentVersion().
The documentation for this interface was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/FileStorageService.java