GMP系统: com.gmp.edms.service.CommonFileService Interface Reference
com.gmp.edms.service.CommonFileService Interface Reference
通用文件管理服务接口 提供跨模块的文件管理功能
Public Member Functions
CommonFileDTO uploadFile (MultipartFile file, String module, Map< String, Object > metadata) throws Exception
上传通用文件
List< CommonFileDTO > batchUploadFiles (List< MultipartFile > files, String module, Map< String, Object > metadata) throws Exception
批量上传文件
InputStream downloadFile (Long fileId) throws Exception
下载文件
CommonFileDTO getFileInfo (Long fileId) throws Exception
获取文件信息
void deleteFile (Long fileId) throws Exception
删除文件
void batchDeleteFiles (List< Long > fileIds) throws Exception
批量删除文件
String generatePresignedUrl (Long fileId, int expiration) throws Exception
生成文件访问的预签名URL
Map< String, Object > queryFiles (String module, Map< String, Object > filters, int page, int size)
查询模块下的文件
void updateFileMetadata (Long fileId, Map< String, Object > metadata) throws Exception
更新文件元数据
Map< String, Object > getFileStatistics (String module)
获取文件统计信息
Detailed Description
通用文件管理服务接口 提供跨模块的文件管理功能
Definition at line 15 of file CommonFileService.java.
Member Function Documentation
batchDeleteFiles()
void com.gmp.edms.service.CommonFileService.batchDeleteFiles (List< Long > fileIds) throws Exception
批量删除文件
Parameters
fileIds 文件ID列表
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
batchUploadFiles()
List< CommonFileDTO > com.gmp.edms.service.CommonFileService.batchUploadFiles (List< MultipartFile > files, String module, Map< String, Object > metadata) throws Exception
批量上传文件
Parameters
files 上传的文件列表
module 文件所属模块
metadata 文件元数据
Returns
文件信息DTO列表
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testBatchUploadFiles().
deleteFile()
void com.gmp.edms.service.CommonFileService.deleteFile (Long fileId) throws Exception
删除文件
Parameters
fileId 文件ID
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile().
downloadFile()
InputStream com.gmp.edms.service.CommonFileService.downloadFile (Long fileId) throws Exception
下载文件
Parameters
fileId 文件ID
Returns
文件输入流
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
generatePresignedUrl()
String com.gmp.edms.service.CommonFileService.generatePresignedUrl (Long fileId, int expiration) throws Exception
生成文件访问的预签名URL
Parameters
fileId 文件ID
expiration 过期时间（秒）
Returns
预签名URL
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl().
getFileInfo()
CommonFileDTO com.gmp.edms.service.CommonFileService.getFileInfo (Long fileId) throws Exception
获取文件信息
Parameters
fileId 文件ID
Returns
文件信息DTO
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata().
getFileStatistics()
Map< String, Object > com.gmp.edms.service.CommonFileService.getFileStatistics (String module)
获取文件统计信息
Parameters
module 模块名称
Returns
统计信息
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics().
queryFiles()
Map< String, Object > com.gmp.edms.service.CommonFileService.queryFiles (String module, Map< String, Object > filters, int page, int size)
查询模块下的文件
Parameters
module 模块名称
filters 过滤条件
page 页码
size 每页大小
Returns
文件列表
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles().
updateFileMetadata()
void com.gmp.edms.service.CommonFileService.updateFileMetadata (Long fileId, Map< String, Object > metadata) throws Exception
更新文件元数据
Parameters
fileId 文件ID
metadata 新的元数据
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata().
uploadFile()
CommonFileDTO com.gmp.edms.service.CommonFileService.uploadFile (MultipartFile file, String module, Map< String, Object > metadata) throws Exception
上传通用文件
Parameters
file 上传的文件
module 文件所属模块
metadata 文件元数据
Returns
文件信息DTO
Implemented in com.gmp.edms.service.impl.CommonFileServiceImpl.
Referenced by com.gmp.edms.service.CommonFileServiceIntegrationTest.testDeleteFile(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGeneratePresignedUrl(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileInfo(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testGetFileStatistics(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testQueryFiles(), com.gmp.edms.service.CommonFileServiceIntegrationTest.testUpdateFileMetadata(), and com.gmp.edms.service.CommonFileServiceIntegrationTest.testUploadFile().
The documentation for this interface was generated from the following file:
edms-service/src/main/java/com/gmp/edms/service/CommonFileService.java