GMP系统: com.gmp.auth.service.RolePermissionService Interface Reference
com.gmp.auth.service.RolePermissionService Interface Reference
角色权限管理服务接口
Public Member Functions
RolePermission assignPermissionToRole (Long roleId, Long permissionId)
为角色分配权限
List< RolePermission > assignPermissionsToRole (Long roleId, List< Long > permissionIds)
为角色分配多个权限
void removePermissionFromRole (Long roleId, Long permissionId)
移除角色的权限
List< Permission > getRolePermissions (Long roleId)
获取角色的所有权限
Set< String > getRolePermissionCodes (Long roleId)
获取角色的权限代码集合
List< Permission > getUserPermissions (Long userId)
获取用户的所有权限（通过角色继承）
Set< String > getUserPermissionCodes (Long userId)
获取用户的权限代码集合
boolean hasPermission (Long userId, String permissionCode)
检查用户是否拥有指定权限
boolean hasAnyPermission (Long userId, List< String > permissionCodes)
检查用户是否拥有指定权限之一
boolean hasAllPermissions (Long userId, List< String > permissionCodes)
检查用户是否拥有所有指定权限
Detailed Description
角色权限管理服务接口
Author
GMP系统开发团队
Definition at line 13 of file RolePermissionService.java.
Member Function Documentation
assignPermissionsToRole()
List< RolePermission > com.gmp.auth.service.RolePermissionService.assignPermissionsToRole (Long roleId, List< Long > permissionIds)
为角色分配多个权限
Parameters
roleId 角色ID
permissionIds 权限ID列表
Returns
分配结果列表
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
assignPermissionToRole()
RolePermission com.gmp.auth.service.RolePermissionService.assignPermissionToRole (Long roleId, Long permissionId)
为角色分配权限
Parameters
roleId 角色ID
permissionId 权限ID
Returns
分配结果
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
getRolePermissionCodes()
Set< String > com.gmp.auth.service.RolePermissionService.getRolePermissionCodes (Long roleId)
获取角色的权限代码集合
Parameters
roleId 角色ID
Returns
权限代码集合
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
getRolePermissions()
List< Permission > com.gmp.auth.service.RolePermissionService.getRolePermissions (Long roleId)
获取角色的所有权限
Parameters
roleId 角色ID
Returns
权限列表
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
getUserPermissionCodes()
Set< String > com.gmp.auth.service.RolePermissionService.getUserPermissionCodes (Long userId)
获取用户的权限代码集合
Parameters
userId 用户ID
Returns
权限代码集合
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testLoadUserByUsername_Success(), com.gmp.auth.service.impl.AuthServiceImplTest.testLogin_Success(), and com.gmp.auth.service.impl.AuthServiceImplTest.testVerifyMfa_Success().
getUserPermissions()
List< Permission > com.gmp.auth.service.RolePermissionService.getUserPermissions (Long userId)
获取用户的所有权限（通过角色继承）
Parameters
userId 用户ID
Returns
权限列表
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
hasAllPermissions()
boolean com.gmp.auth.service.RolePermissionService.hasAllPermissions (Long userId, List< String > permissionCodes)
检查用户是否拥有所有指定权限
Parameters
userId 用户ID
permissionCodes 权限代码列表
Returns
是否拥有所有权限
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
hasAnyPermission()
boolean com.gmp.auth.service.RolePermissionService.hasAnyPermission (Long userId, List< String > permissionCodes)
检查用户是否拥有指定权限之一
Parameters
userId 用户ID
permissionCodes 权限代码列表
Returns
是否拥有任一权限
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
Referenced by com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserDoesNotHaveRequiredPermission(), and com.gmp.auth.service.impl.AuthServiceImplTest.testHasPermission_UserHasRequiredPermission().
hasPermission()
boolean com.gmp.auth.service.RolePermissionService.hasPermission (Long userId, String permissionCode)
检查用户是否拥有指定权限
Parameters
userId 用户ID
permissionCode 权限代码
Returns
是否拥有
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
removePermissionFromRole()
void com.gmp.auth.service.RolePermissionService.removePermissionFromRole (Long roleId, Long permissionId)
移除角色的权限
Parameters
roleId 角色ID
permissionId 权限ID
Implemented in com.gmp.auth.service.impl.RolePermissionServiceImpl.
The documentation for this interface was generated from the following file:
auth-service/src/main/java/com/gmp/auth/service/RolePermissionService.java